"use client";

import { GcseFactPanel } from "./gcse-fact-panel";

export function BiologyOrganisationHumanDigestiveSystemDemo() {
  return (
    <GcseFactPanel
      title={"Key facts"}
      items={[
            {
                  "label": "Enzyme location",
                  "detail": "Amylase – mouth and pancreas; protease – stomach and pancreas; lipase – pancreas."
            },
            {
                  "label": "pH of stomach",
                  "detail": "Approximately 2, optimal for pepsin activity."
            },
            {
                  "label": "Bile function",
                  "detail": "Emulsifies fats, forming micelles for lipase access."
            },
            {
                  "label": "Surface area increase",
                  "detail": "Villi and microvilli in the small intestine greatly increase absorptive area."
            },
            {
                  "label": "Absorption site",
                  "detail": "Most nutrients are absorbed across the walls of the small intestine."
            }
      ]}
    />
  );
}

export function BiologyOrganisationHumanCirculatorySystemDemo() {
  return (
    <GcseFactPanel
      title={"Quick reference"}
      items={[
            {
                  "label": "Heart chambers",
                  "detail": "Right atrium → right ventricle → lungs; left atrium → left ventricle → body."
            },
            {
                  "label": "Blood pressure",
                  "detail": "Higher in arteries (~120 mmHg systolic) than veins (~10 mmHg)."
            },
            {
                  "label": "Red cell function",
                  "detail": "Contains haemoglobin which binds O₂ and CO₂."
            },
            {
                  "label": "Plasma proportion",
                  "detail": "Makes up about 55 % of total blood volume."
            },
            {
                  "label": "Valve purpose",
                  "detail": "Prevent backflow; e.g., tricuspid, mitral, pulmonary, aortic valves."
            }
      ]}
    />
  );
}

export function BiologyOrganisationPlantTissuesTranspirationTranslocationDemo() {
  return (
    <GcseFactPanel
      title={"Key facts"}
      items={[
            {
                  "label": "Xylem driver",
                  "detail": "Cohesion‑tension created by water evaporation from leaves."
            },
            {
                  "label": "Phloem driver",
                  "detail": "Pressure‑flow generated by loading sugars at source and unloading at sink."
            },
            {
                  "label": "Stomatal control",
                  "detail": "Guard cells swell with K⁺ uptake, opening the pore."
            },
            {
                  "label": "Transpiration rate",
                  "detail": "Increases with temperature, wind and low humidity."
            },
            {
                  "label": "Plant embolism",
                  "detail": "Can be caused by drought; plants may refill xylem via root pressure."
            }
      ]}
    />
  );
}
