import type { TopicContent } from "../types";
import {
  SubjectVerbAgreementDemo,
  TenseConsistencyDemo,
  ComparativesSuperlativesDemo,
  DoubleNegativesDemo,
  MisplacedModifiersDemo,
  ParallelStructureDemo,
} from "../notes-diagrams/grammar-demos";

const CLICK_INSTRUCTION = "Click the word with the error.";

export const agreementTenseErrorsTopic: TopicContent = {
  slug: "agreement-tense-errors",
  subject: "English",
  subjectSlug: "english",
  title: "Grammar: Agreement & Sentence-Level Errors",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "Beyond single-word errors, GL and CSSE-style papers test whether a whole sentence hangs together — does the verb agree with its real subject, does the tense stay consistent, is a comparison marked once rather than twice? This module works through subject-verb agreement, tense consistency, comparatives and superlatives, double negatives, misplaced modifiers and parallel structure.",
  subtopics: [
    {
      id: "subject-verb-agreement",
      title: "Subject-Verb Agreement",
      tier: "Standard",
      objective: "Identify the true subject of a sentence and match it to the correct singular or plural verb, even when other nouns sit in between.",
      whyMatters: "the trickiest agreement errors hide a plural noun right next to the verb, tempting you to match the wrong word — a favourite GL trap.",
      conceptTitle: "Find the real subject first",
      conceptBullets: [
        'The <b style="color:#C9A24B">subject</b> of a sentence is who or what is doing the verb — the verb must agree with it in number.',
        'Phrases like "of chocolates", "along with the others" or "as well as her friends" sit between the subject and the verb but do not change what the subject is.',
        'Example: "the <b>box</b> of chocolates <b>was</b> left on the table" — "box" is singular, so the verb is singular, even though "chocolates" is right next to it.',
        "Collective nouns (team, family, class) usually take a singular verb when acting as one unit: “the team is winning.”",
      ],
      conceptNote: "<b>Test it:</b> cross out any phrase starting with “of”, “along with” or “as well as” — what's left is the true subject.",
      glossary: [
        { term: "subject", def: "who or what is doing the verb" },
        { term: "agreement", def: "matching a singular subject to a singular verb, plural to plural" },
        { term: "collective noun", def: "names a group, usually takes a singular verb" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: SubjectVerbAgreementDemo,
      worked: {
        question: "Spot the error: “The list of ingredients were printed on the back of the packet.”",
        fastMethod: 'Cross out "of ingredients" — the true subject is "list", which is singular, so the verb should be "was".',
        steps: [
          "Cross out the phrase between the subject and the verb: “of ingredients”.",
          "What remains is “The list … were printed” — “list” is singular.",
          "A singular subject needs a singular verb: “was”, not “were”.",
          "Corrected: “The list of ingredients was printed on the back of the packet.”",
        ],
        answer: "The error is <b>were</b> — it should be <b>was</b>.",
      },
      selfCheck: { prompt: "True or false: in “the players on the team was training”, the verb is correct.", answer: "<b>False</b> — the subject is “players” (plural), so the verb should be “were training”." },
      kind: "click-error",
      questions: [
        {
          id: "sva-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "basket", "of", "apples", "were", "sitting", "on", "the", "counter", "all", "morning."],
          errorIdx: 4,
          correction: '"basket" is the true subject, not "apples" — the verb should be "was": the basket of apples was sitting...',
          hint: "Cross out the phrase starting with “of” and check what's left.",
        },
        {
          id: "sva-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Neither", "of", "the", "twins", "were", "ready", "when", "the", "taxi", "arrived."],
          errorIdx: 4,
          correction: '"neither" is a singular subject even though it\'s followed by a plural noun — it takes a singular verb: neither of the twins was ready.',
          hint: "“Neither” and “either” are always singular, however many things follow them.",
        },
        {
          id: "sva-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "committee", "members", "was", "arguing", "about", "the", "budget", "all", "afternoon."],
          errorIdx: 3,
          correction: '"members" (plural) is the true subject here, not "committee" acting alone — the verb should be "were": the committee members were arguing.',
          hint: "Here the subject is the plural noun right after “committee”, not the collective noun itself.",
        },
      ],
      mistakes: [
        "Matching the verb to the noun closest to it instead of the true subject — always cross out the phrase in between first.",
        "Treating “neither”, “either” and “each” as plural because they're often followed by a plural noun — they're always singular.",
      ],
      examTip: "Say the subject and verb alone, with the middle phrase removed — a wrong match will sound obviously off once the distraction is gone.",
      searchTerms: ["subject-verb agreement", "singular", "plural", "collective noun", "neither", "either"],
    },
    {
      id: "tense-consistency",
      title: "Tense Consistency",
      tier: "Standard",
      objective: "Keep verb tenses consistent within a sentence or short passage, and spot a verb that has slipped into the wrong time frame.",
      whyMatters: "tense-shift errors are easy to miss because each verb is spelled correctly on its own — the mistake only shows up when you compare it to the rest of the sentence.",
      conceptTitle: "One story, one time frame",
      conceptBullets: [
        'A <b style="color:#C9A24B">tense</b> tells you when an action happens — past, present or future.',
        "Within a single sentence describing one event, all the main verbs should normally stay in the same tense.",
        'Example: "She <i>opened</i> the door, <i>looked</i> around and <i>smiled</i>" — three past-tense verbs describing one continuous action.',
        "A verb that suddenly switches to a different tense breaks the timeline, even if it's a real word used correctly elsewhere.",
      ],
      conceptNote: "<b>Test it:</b> read the sentence and ask “is this all happening at the same time, in the same story?” — a lone present-tense verb in a past-tense sentence stands out.",
      glossary: [
        { term: "tense", def: "when an action happens (past, present, future)" },
        { term: "past tense", def: "already happened (opened, smiled)" },
        { term: "present tense", def: "happening now (opens, smiles)" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: TenseConsistencyDemo,
      worked: {
        question: "Spot the error: “He grabbed his coat, ran to the station and catches the last train.”",
        fastMethod: '"grabbed" and "ran" are past tense — "catches" breaks the timeline and should be "caught".',
        steps: [
          "List the main verbs in order: grabbed, ran, catches.",
          "The first two are past tense, describing something that already happened.",
          "“Catches” is present tense — it doesn't match the rest of the story.",
          "Corrected: “…ran to the station and caught the last train.”",
        ],
        answer: "The error is <b>catches</b> — it should be <b>caught</b>.",
      },
      selfCheck: { prompt: "True or false: a sentence can never mix tenses.", answer: "<b>False</b> — a sentence can compare two different times on purpose (e.g. “I used to walk, but now I cycle”). The error only occurs when the shift is accidental within one continuous action." },
      kind: "click-error",
      questions: [
        {
          id: "tense-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "packed", "her", "bag,", "locks", "the", "door", "and", "left", "for", "the", "airport."],
          errorIdx: 4,
          correction: '"packed" and "left" are past tense, so "locks" breaks the timeline — it should be "locked".',
          hint: "Two verbs agree on when this happened — one doesn't.",
        },
        {
          id: "tense-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "chef", "chops", "the", "vegetables", "and", "then", "stirred", "the", "sauce", "slowly."],
          errorIdx: 1,
          correction: '"stirred" is past tense, so "chops" should also be past tense: "chopped" the vegetables.',
          hint: "Check the very first verb against the one near the end of the sentence.",
        },
        {
          id: "tense-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["By", "the", "time", "the", "guests", "arrive,", "the", "cake", "had", "already", "been", "eaten."],
          errorIdx: 5,
          correction: '"had already been eaten" sets up a past timeline, so "arrive" should be past tense: by the time the guests arrived.',
          hint: "The second half of the sentence anchors the timeline — check the first verb against it.",
        },
      ],
      mistakes: [
        "Missing a tense shift because the wrong-tense verb is spelled correctly and grammatical on its own.",
        "Assuming every sentence must use only one tense, even when a deliberate contrast between two time periods is intended.",
      ],
      examTip: "List just the main verbs from the sentence in order — if they don't all belong to the same time frame, you've found the error.",
      searchTerms: ["tense", "tense consistency", "past tense", "present tense", "timeline"],
    },
    {
      id: "comparatives-superlatives",
      title: "Comparatives & Superlatives",
      tier: "Standard",
      objective: "Use comparative and superlative forms correctly, and spot when a comparison has been marked twice or the wrong form used for the number of things being compared.",
      whyMatters: "double comparatives (“more better”, “most shorter”) and mixing up two-thing vs. three-or-more-thing comparisons are classic “complete the sentence” traps.",
      conceptTitle: "Comparing two things vs. three or more",
      conceptBullets: [
        'A <b style="color:#C9A24B">comparative</b> compares exactly two things: <i>faster</i>, <i>more interesting</i>.',
        'A <b style="color:#C9A24B">superlative</b> compares three or more, picking out the extreme: <i>fastest</i>, <i>most interesting</i>.',
        "Short words usually add -er/-est (fast → faster → fastest); longer words use more/most instead (interesting → more interesting → most interesting).",
        "Never combine both methods on the same word — “more faster” or “most shortest” double-marks the comparison.",
      ],
      conceptNote: "<b>Remember:</b> count what's being compared first — two things need the comparative (-er/more), three or more need the superlative (-est/most).",
      glossary: [
        { term: "comparative", def: "compares two things (faster, more interesting)" },
        { term: "superlative", def: "compares three or more (fastest, most interesting)" },
        { term: "double comparative", def: "wrongly using -er and more together" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: ComparativesSuperlativesDemo,
      worked: {
        question: "Spot the error: “This is the most easiest puzzle in the whole book.”",
        fastMethod: '"most" and "-est" both mark a superlative — only one is needed. Remove "most": the easiest puzzle.',
        steps: [
          "Identify the comparison word: “easiest” already carries the superlative -est ending.",
          "“Most” in front of it repeats the same job — a double superlative.",
          "Only one marker is needed to show the superlative.",
          "Corrected: “This is the easiest puzzle in the whole book.”",
        ],
        answer: "The error is the extra <b>most</b> — it should be removed.",
      },
      selfCheck: { prompt: "Which is correct when comparing exactly two runners: “faster” or “fastest”?", answer: "<b>Faster</b> — the comparative form is used for exactly two things; “fastest” (superlative) is for three or more." },
      kind: "click-error",
      questions: [
        {
          id: "comp-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Of", "the", "three", "cakes,", "the", "chocolate", "one", "was", "more", "tastier."],
          errorIdx: 8,
          correction: '"more" and "-er" both mark a comparison — with three cakes being compared, the correct superlative is simply "tastiest", not "more tastier".',
          hint: "Two words together are both trying to do the same comparing job.",
        },
        {
          id: "comp-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["This", "bridge", "is", "the", "most", "longest", "one", "in", "the", "country."],
          errorIdx: 4,
          correction: '"longest" already carries the superlative ending — "most" is unnecessary and should be removed.',
          hint: "One word already shows the superlative by its ending — check what comes right before it.",
        },
        {
          id: "comp-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Between", "the", "two", "options,", "the", "bus", "is", "definitely", "the", "cheapest."],
          errorIdx: 9,
          correction: '"between the two options" signals exactly two things, so the comparative "cheaper" is needed, not the superlative "cheapest".',
          hint: "Count how many things are actually being compared, right at the start of the sentence.",
        },
      ],
      mistakes: [
        "Doubling up -er/-est with more/most on the same word (“more better”, “most shortest”).",
        "Using the superlative (-est/most) when only two things are being compared, instead of the comparative (-er/more).",
      ],
      examTip: "Count the things being compared before choosing the form — exactly two always needs the comparative, never the superlative.",
      searchTerms: ["comparative", "superlative", "more", "most", "-er", "-est", "double comparative"],
    },
    {
      id: "double-negatives",
      title: "Double Negatives",
      tier: "Foundation",
      objective: "Recognise when two negative words have been used together and cancel each other out, and correct the sentence to a single, clear negative.",
      whyMatters: "double negatives are one of the most common everyday speech habits that trips students up in writing — the sentence sounds natural but is technically wrong.",
      conceptTitle: "Two negatives make a positive",
      conceptBullets: [
        'A <b style="color:#C9A24B">negative</b> word turns a statement into its opposite: <i>not</i>, <i>never</i>, <i>no</i>, <i>nothing</i>, <i>nobody</i>.',
        "Standard English uses only one negative word per idea — using two cancels them out and (technically) flips the meaning back to positive.",
        'Example: "I haven\'t got no homework" technically means "I do have homework" — the opposite of what\'s intended.',
        'Fix a double negative either by removing one negative word, or by swapping the second for a positive equivalent ("no" → "any", "nobody" → "anybody").',
      ],
      conceptNote: "<b>Common trap:</b> “haven't got no”, “can't hardly”, and “don't know nothing” are all double negatives, even though they're common in casual speech.",
      glossary: [
        { term: "negative word", def: "turns a statement into its opposite (not, never, no, nothing)" },
        { term: "double negative", def: "two negative words used together, cancelling out" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: DoubleNegativesDemo,
      worked: {
        question: "Spot the error: “I can't hardly see the board from the back row.”",
        fastMethod: '"can\'t" and "hardly" are both negative — together they mean the opposite of what\'s intended. Remove "can\'t": I can hardly see.',
        steps: [
          "Identify every negative word in the sentence: “can't” and “hardly”.",
          "“Hardly” already means “almost not” — it's a negative on its own.",
          "Pairing it with “can't” creates a double negative that technically reverses the meaning.",
          "Corrected: “I can hardly see the board from the back row.”",
        ],
        answer: "The error is <b>can't</b> — it should be <b>can</b>.",
      },
      selfCheck: { prompt: "True or false: “I don't want nothing” is standard, correct English.", answer: "<b>False</b> — “don't” and “nothing” are both negatives; the standard form is “I don't want anything” or “I want nothing.”" },
      kind: "click-error",
      questions: [
        {
          id: "dn-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["We", "didn't", "see", "nobody", "at", "the", "park", "this", "morning."],
          errorIdx: 3,
          correction: '"didn\'t" and "nobody" are both negative — the correct word is "anybody": we didn\'t see anybody.',
          hint: "Two words in this sentence are both making it negative.",
        },
        {
          id: "dn-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["I", "can't", "hardly", "wait", "for", "the", "summer", "holidays", "to", "start."],
          errorIdx: 1,
          correction: '"hardly" is already a negative on its own — pairing it with "can\'t" is a double negative. It should simply be "can": I can hardly wait.',
          hint: "One of these words already means “almost not” by itself.",
        },
        {
          id: "dn-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["There", "isn't", "no", "point", "arguing", "about", "it", "any", "further."],
          errorIdx: 2,
          correction: '"isn\'t" and "no" are both negative — the correct word is "any": there isn\'t any point.',
          hint: "Find the second negative word — it appears very early in the sentence.",
        },
      ],
      mistakes: [
        "Not recognising “hardly”, “barely” and “scarcely” as negative words, since they don't look like typical negatives.",
        "Leaving both negatives in place because the sentence “sounds normal” from everyday speech.",
      ],
      examTip: "Count the negative words in the sentence — if you find two, one of them needs to go (or be swapped for a positive equivalent like “any”).",
      searchTerms: ["double negative", "negative word", "hardly", "nobody", "nothing"],
    },
    {
      id: "misplaced-modifiers",
      title: "Misplaced & Dangling Modifiers",
      tier: "Extension",
      objective: "Spot when a descriptive phrase is positioned so that it appears to describe the wrong noun, and identify how to fix it.",
      whyMatters: "modifier errors often create an unintentionally funny or nonsensical image, making them one of the more memorable — and testable — sentence-level error types.",
      conceptTitle: "A describing phrase needs the right neighbour",
      conceptBullets: [
        'A <b style="color:#C9A24B">modifier</b> is a word or phrase that describes something else in the sentence — it should sit right next to the thing it describes.',
        'An opening phrase followed by a comma (e.g. "Running for the bus,") describes whoever or whatever comes immediately after the comma.',
        'If the noun right after the comma isn\'t capable of doing that action, the modifier is "dangling" — it has nothing sensible to attach to.',
        'Example: "Running for the bus, my hat flew off" literally says the hat was running — the sentence needs a person right after the comma.',
      ],
      conceptNote: "<b>Test it:</b> read the opening phrase, then ask “can the very next noun actually do this?” — if not, the modifier is misplaced.",
      glossary: [
        { term: "modifier", def: "a word or phrase that describes something else" },
        { term: "dangling modifier", def: "a describing phrase with nothing sensible to attach to" },
        { term: "misplaced modifier", def: "a describing phrase positioned next to the wrong noun" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: MisplacedModifiersDemo,
      worked: {
        question: "Spot the error: “Covered in chocolate, Amir couldn't resist eating the cake.”",
        fastMethod: 'Read literally: is "Amir" covered in chocolate, or is the "cake"? As written, "Amir" is — probably not the intended meaning.',
        steps: [
          "Identify the opening modifier: “Covered in chocolate”.",
          "Check the noun immediately after the comma: “Amir”.",
          "As written, the sentence says Amir is covered in chocolate — likely not intended; it's the cake that should be.",
          "Corrected: “Covered in chocolate, the cake was impossible for Amir to resist.”",
        ],
        answer: "The modifier is misplaced — it currently describes <b>Amir</b> instead of the <b>cake</b>.",
      },
      selfCheck: { prompt: "In “Excited about the trip, the suitcase was packed by Leila the night before”, what does the opening phrase currently describe?", answer: "<b>The suitcase</b> — which can't feel excited. It should be repositioned so it describes “Leila” instead." },
      kind: "click-error",
      questions: [
        {
          id: "mm-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Barking", "loudly,", "the", "postman", "was", "frightened", "by", "the", "dog."],
          errorIdx: 3,
          correction: '"barking loudly" should describe the dog, but as written it attaches to "postman" — postmen don\'t bark. It should read "Barking loudly, the dog frightened the postman."',
          hint: "The opening phrase describes whoever barks — check the noun right after the comma.",
        },
        {
          id: "mm-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["After", "finishing", "the", "race,", "a", "medal", "was", "given", "to", "Priya."],
          errorIdx: 5,
          correction: '"after finishing the race" should describe Priya, but it currently attaches to "medal" — a medal cannot finish a race. It should read "After finishing the race, Priya was given a medal."',
          hint: "Check what noun comes right after the introductory phrase and comma.",
        },
        {
          id: "mm-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Hoping", "for", "sunshine,", "the", "picnic", "was", "planned", "by", "the", "children."],
          errorIdx: 4,
          correction: '"hoping for sunshine" should describe the children, but it currently attaches to "picnic" — a picnic can\'t hope. It should read "Hoping for sunshine, the children planned a picnic."',
          hint: "Only a person can hope — find the noun wrongly placed right after the comma.",
        },
      ],
      mistakes: [
        "Reading an opening modifier for overall meaning instead of checking exactly which noun follows the comma.",
        "Assuming a sentence is fine as long as the intended meaning is guessable — exam questions test the literal, written meaning.",
      ],
      examTip: "Read the opening phrase and the very next noun as a mini sentence on their own — if it sounds absurd, the modifier is misplaced.",
      searchTerms: ["modifier", "dangling modifier", "misplaced modifier", "opening phrase", "comma"],
    },
    {
      id: "parallel-structure",
      title: "Parallel Structure",
      tier: "Extension",
      objective: "Recognise when items in a list or comparison should share the same grammatical form, and spot the item that breaks the pattern.",
      whyMatters: "parallel structure errors are subtle because every individual word is spelled correctly — only the mismatch across the list gives the error away.",
      conceptTitle: "Match the pattern across a list",
      conceptBullets: [
        'When a sentence lists items joined by "and" or "or", every item should use the <b style="color:#C9A24B">same grammatical form</b>.',
        'Example: "She likes reading, painting and swimming" — all three end in -ing.',
        'If one item breaks the pattern (e.g. "reading, painting and to swim"), the sentence loses its balance, even though each word alone is correct.',
        "This applies to verb forms, noun phrases, and adjectives used in a series — the whole list has to match.",
      ],
      conceptNote: "<b>Test it:</b> read just the list items on their own, one after another — the odd one will sound like it belongs to a different sentence.",
      glossary: [
        { term: "parallel structure", def: "matching grammatical form across items in a list" },
        { term: "series", def: "a list of three or more items joined by and/or" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: ParallelStructureDemo,
      worked: {
        question: "Spot the error: “The job requires patience, creativity and to communicate well.”",
        fastMethod: '"patience" and "creativity" are nouns, but "to communicate well" is a verb phrase — it breaks the pattern.',
        steps: [
          "List the three items: patience, creativity, to communicate well.",
          "The first two are nouns; the third is a completely different grammatical form.",
          "To match, the third item needs to become a noun too.",
          "Corrected: “The job requires patience, creativity and good communication.”",
        ],
        answer: "The error is <b>to communicate well</b> — it should match the noun form of the others, e.g. <b>good communication</b>.",
      },
      selfCheck: { prompt: "Is this list parallel: “He enjoys hiking, biking and to fish”?", answer: "<b>No</b> — “hiking” and “biking” are -ing forms, but “to fish” breaks the pattern; it should be “fishing”." },
      kind: "click-error",
      questions: [
        {
          id: "ps-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "coach", "told", "the", "team", "to", "warm", "up,", "stretch", "and", "hydrating."],
          errorIdx: 10,
          correction: '"warm up" and "stretch" are base-form verbs after "to" — "hydrating" breaks the pattern and should be "hydrate".',
          hint: "Two verbs in this list share a form — the last one doesn't match.",
        },
        {
          id: "ps-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "recipe", "is", "quick,", "healthy", "and", "tastes", "good."],
          errorIdx: 6,
          correction: '"quick" and "healthy" are adjectives describing the recipe — "tastes good" is a verb phrase and breaks the pattern; it should be "tasty".',
          hint: "Two words in this list are simple describing words — the third item is a different type of phrase.",
        },
        {
          id: "ps-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Her", "goals", "this", "year", "are", "saving", "money,", "exercising", "more", "and", "read", "daily."],
          errorIdx: 10,
          correction: '"saving" and "exercising" are -ing forms — "read" breaks the pattern and should be "reading".',
          hint: "Check the ending of each item in this list of goals.",
        },
      ],
      mistakes: [
        "Only checking each item for correctness on its own instead of comparing its grammatical form to the rest of the list.",
        "Missing the break in a long list because the mismatched item is still a real, correctly spelled word.",
      ],
      examTip: "Read only the list items, stripped of the rest of the sentence, one under another in your head — the odd form stands out immediately.",
      searchTerms: ["parallel structure", "parallelism", "list", "series", "consistent form"],
    },
  ],
};
