import type { TopicContent } from "../types";
import {
  ContractionPossessiveDemo,
  SingularPossessionDemo,
  PluralPossessionDemo,
  IrregularPluralPossessionDemo,
  JointSeparatePossessionDemo,
  DecadesLettersApostropheDemo,
  GreengrocersApostropheDemo,
  PossessivePronounNoApostropheDemo,
  NamesEndingInSDemo,
  MixedApostropheReviewDemo,
} from "../notes-diagrams/apostrophes-possession-demos";

const CLICK_INSTRUCTION = "Click the word with the error.";

export const apostrophesPossessionErrorsTopic: TopicContent = {
  slug: "apostrophes-possession-errors",
  subject: "English",
  subjectSlug: "english",
  title: "Grammar: Apostrophes & Possession",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "The apostrophe is the smallest mark in punctuation and the one that trips up the most students — it shows ownership or a missing letter, and never anything else. This module works through contractions, singular and plural possession, irregular plurals, joint ownership, and the “greengrocer’s apostrophe”, training you to spot exactly when a stray or missing apostrophe is the error.",
  subtopics: [
    {
      id: "contractions-vs-possessives",
      title: "Contractions vs. Possessives (it's/its, you're/your)",
      tier: "Foundation",
      objective: "Tell a contraction (a shortened form with a missing letter) apart from a possessive, and use the apostrophe correctly in each case.",
      whyMatters: "it's/its and you're/your confusion is the single most common apostrophe error tested at 11+ — the two words sound identical, so the exam is testing your eye, not your ear.",
      conceptTitle: "Two jobs, one mark",
      conceptBullets: [
        'An <b style="color:#C9A24B">apostrophe</b> in a contraction stands in for a missing letter — <i>it\'s</i> = it is, <i>you\'re</i> = you are.',
        'A <b>possessive</b> word shows ownership and, confusingly, some of them use no apostrophe at all — <i>its</i> (belonging to it), <i>your</i> (belonging to you).',
        "The test is simple: try replacing the word with the full two-word form. If “it is” or “you are” still makes sense, the apostrophe version is correct.",
        "If the sentence is about something belonging to someone or something, the no-apostrophe possessive is correct instead.",
      ],
      conceptNote: "<b>Test it:</b> mentally expand the word — “it's raining” → “it is raining” (works); “the dog wagged it's tail” → “the dog wagged it is tail” (doesn't work, so it must be “its”).",
      glossary: [
        { term: "contraction", def: "a shortened word with an apostrophe replacing missing letters" },
        { term: "possessive", def: "shows ownership" },
        { term: "it's / its", def: "it is (contraction) vs. belonging to it (possessive)" },
        { term: "you're / your", def: "you are (contraction) vs. belonging to you (possessive)" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: ContractionPossessiveDemo,
      worked: {
        question: "Spot the error: “Your going to need your coat, its going to rain later.”",
        fastMethod: 'Expand each word: "Your going" → "You are going" (works, so it needs the apostrophe); "its going to rain" → "it is going to rain" (also works, so it needs the apostrophe too).',
        steps: [
          "Expand “Your” into “you are” — “You are going to need your coat” makes sense, so this should be “You're”.",
          "The second “your” in “your coat” shows possession, so it correctly has no apostrophe.",
          "Expand “its” into “it is” — “it is going to rain” makes sense, so this should be “it's”.",
          "Corrected: “You're going to need your coat, it's going to rain later.”",
        ],
        answer: "There are two errors here: <b>Your</b> should be <b>You're</b>, and <b>its</b> should be <b>it's</b>.",
      },
      selfCheck: { prompt: "Which is correct: “the cat cleaned it's paws” or “the cat cleaned its paws”?", answer: "<b>“The cat cleaned its paws”</b> — “its” shows possession here; “it's” would mean “it is”, which doesn't fit." },
      kind: "click-error",
      questions: [
        {
          id: "contr-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Its", "a", "lovely", "day", "for", "a", "picnic", "in", "the", "park."],
          errorIdx: 0,
          correction: '"Its" should be "It\'s" — short for "it is", which is needed here, not the possessive "its".',
          hint: "Try expanding the first word into “it is” and see if the sentence still makes sense.",
        },
        {
          id: "contr-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "cat", "licked", "it's", "paw", "before", "curling", "up", "to", "sleep."],
          errorIdx: 3,
          correction: '"it\'s" here should be the possessive "its" (no apostrophe) — it shows the paw belongs to the cat, not "it is".',
          hint: "Expand the word into “it is” — does “licked it is paw” make sense?",
        },
        {
          id: "contr-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Your", "going", "to", "love", "the", "school", "trip", "this", "year."],
          errorIdx: 0,
          correction: '"Your" should be "You\'re" — short for "you are", not the possessive "your".',
          hint: "Try expanding this word into “you are” and check if the sentence still works.",
        },
      ],
      mistakes: [
        "Adding an apostrophe to a possessive out of habit, because most other possessives (the dog's bone) do take one — “its” and “your” never do.",
        "Trusting how the sentence sounds rather than testing it — it's/its and you're/your are pronounced identically.",
      ],
      examTip: "Always run the “expand the word” test before moving on — if “it is” or “you are” doesn't fit, the apostrophe version is wrong.",
      searchTerms: ["apostrophe", "contraction", "possessive", "it's", "its", "you're", "your"],
    },
    {
      id: "singular-possession",
      title: "Singular Possession",
      tier: "Foundation",
      objective: "Add 's correctly to a singular noun to show that one person or thing owns something.",
      whyMatters: "singular possession is the foundation every other apostrophe rule builds on — get this automatic, and the plural and irregular rules become easy extensions.",
      conceptTitle: "One owner, apostrophe then s",
      conceptBullets: [
        'When exactly <b style="color:#C9A24B">one</b> person or thing owns something, add an apostrophe and then an <i>s</i> to the owner\'s name.',
        'Example: "the <i>dog\'s</i> bone" — one dog owns the bone.',
        'This applies even when the owner\'s name already ends in s: "James\'s book" (see the “Names Ending in S” topic for the full rule).',
        "The apostrophe sits between the owner's name and the added s — never after the thing being owned.",
      ],
      conceptNote: "<b>Test it:</b> rephrase as “the bone belonging to the dog” — whoever the “belonging to” points at is the owner, and gets the 's.",
      glossary: [
        { term: "possession", def: "showing that something belongs to someone or something" },
        { term: "singular", def: "just one" },
        { term: "'s", def: "apostrophe + s, added to a singular owner's name" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: SingularPossessionDemo,
      worked: {
        question: "Spot the error: “The girls violin was out of tune before the concert.”",
        fastMethod: 'Rephrase as "the violin belonging to the girl" — one girl owns it, so "girls" needs an apostrophe: girl\'s.',
        steps: [
          "Rephrase the sentence: “the violin belonging to the girl”.",
          "This tells you there's exactly one owner — the girl.",
          "A single owner needs an apostrophe before the s: girl's.",
          "Corrected: “The girl's violin was out of tune before the concert.”",
        ],
        answer: "The error is <b>girls</b> — it should be <b>girl's</b>.",
      },
      selfCheck: { prompt: "Where does the apostrophe go to show that one teacher owns a classroom?", answer: "<b>Teacher's classroom</b> — the apostrophe goes right after “teacher”, before the added s." },
      kind: "click-error",
      questions: [
        {
          id: "sing-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "teachers", "desk", "was", "covered", "in", "papers."],
          errorIdx: 1,
          correction: '"teachers" should be "teacher\'s" — one teacher owns the desk, so it needs an apostrophe before the s.',
          hint: "Rephrase as “the desk belonging to the teacher” — how many teachers are there?",
        },
        {
          id: "sing-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Sam", "football", "boots", "were", "muddy", "after", "training."],
          errorIdx: 0,
          correction: '"Sam" should be "Sam\'s" — the boots belong to one person, Sam, so it needs an apostrophe and s.',
          hint: "Find the owner's name and check whether it shows possession yet.",
        },
        {
          id: "sing-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "bakers", "bread", "was", "famous", "throughout", "the", "village."],
          errorIdx: 1,
          correction: '"bakers" should be "baker\'s" — one baker owns the bread, so it needs an apostrophe before the s.',
          hint: "Rephrase as “the bread belonging to the baker” to find the correct spot for the apostrophe.",
        },
      ],
      mistakes: [
        "Writing the plain plural (“the dogs bone”) when only one owner is meant, missing the apostrophe entirely.",
        "Putting the apostrophe after the s instead of before it when there's only one owner (“dogs' bone” instead of “dog's bone”).",
      ],
      examTip: "Before you write or check 's, count the owners in your head — if it's exactly one, the apostrophe goes before the s, no exceptions.",
      searchTerms: ["apostrophe", "possession", "singular possession", "'s", "ownership"],
    },
    {
      id: "plural-possession",
      title: "Plural Possession",
      tier: "Standard",
      objective: "Show possession for a regular plural noun by placing the apostrophe after the final s.",
      whyMatters: "mixing up singular and plural possession is one of the most common apostrophe slips — the words often sound identical when spoken aloud.",
      conceptTitle: "More than one owner, s then apostrophe",
      conceptBullets: [
        'When a <b style="color:#C9A24B">regular plural</b> noun (one that already ends in s) owns something, the apostrophe goes <i>after</i> the s, with nothing added.',
        'Example: "the <i>dogs\'</i> bones" — more than one dog, each owning a bone.',
        'Compare to singular: "the <i>dog\'s</i> bone" (one dog) vs. "the <i>dogs\'</i> bones" (several dogs) — the apostrophe position is the only difference.',
        "Say the sentence aloud first to count the owners, since singular and plural possessives usually sound identical.",
      ],
      conceptNote: "<b>Remember:</b> if the plural already ends in s, don't add another one — just move the apostrophe to after the existing s.",
      glossary: [
        { term: "regular plural", def: "a plural formed by adding s (dogs, students, players)" },
        { term: "plural possession", def: "showing ownership by more than one owner" },
        { term: "s'", def: "s + apostrophe, added after a regular plural owner" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: PluralPossessionDemo,
      worked: {
        question: "Spot the error: “The two brothers bikes were both stolen from the shed.”",
        fastMethod: 'There are two brothers (plural), and "brothers" already ends in s, so the apostrophe goes after it: brothers\'.',
        steps: [
          "Count the owners: “the two brothers” — more than one.",
          "“Brothers” is a regular plural, already ending in s.",
          "For a regular plural owner, the apostrophe goes after the existing s, with nothing added.",
          "Corrected: “The two brothers' bikes were both stolen from the shed.”",
        ],
        answer: "The error is <b>brothers</b> — it should be <b>brothers'</b>.",
      },
      selfCheck: { prompt: "How do you show that several students own one classroom?", answer: "<b>Students' classroom</b> — since “students” is already a regular plural, the apostrophe goes straight after the final s." },
      kind: "click-error",
      questions: [
        {
          id: "plur-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "players", "kits", "were", "hung", "up", "after", "the", "match."],
          errorIdx: 1,
          correction: '"players" should be "players\'" — several players own the kits, so the apostrophe goes after the existing s.',
          hint: "Count how many players there are, then decide where the apostrophe belongs.",
        },
        {
          id: "plur-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "twins", "bedroom", "was", "painted", "blue", "last", "summer."],
          errorIdx: 1,
          correction: '"twins" should be "twins\'" — two owners share the bedroom, so the apostrophe goes after the s: twins\'.',
          hint: "“Twins” already means more than one person — check where the apostrophe should sit.",
        },
        {
          id: "plur-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "girls", "netball", "kits", "were", "freshly", "washed", "for", "the", "tournament."],
          errorIdx: 1,
          correction: '"girls" should be "girls\'" — the whole team of girls owns the kits, so the apostrophe goes after the existing s.',
          hint: "This is a whole team, not one girl — where should the apostrophe go?",
        },
      ],
      mistakes: [
        "Using the singular possessive (dog's) when the sentence is actually about several owners (dogs').",
        "Adding an extra s after the apostrophe on a regular plural (“dogs's” is never correct).",
      ],
      examTip: "Say the sentence aloud and count the owners before you touch the apostrophe — singular and plural possessives sound the same but are spelled differently.",
      searchTerms: ["apostrophe", "plural possession", "s'", "regular plural", "ownership"],
    },
    {
      id: "irregular-plural-possession",
      title: "Irregular Plural Possession (children's, men's, women's)",
      tier: "Standard",
      objective: "Correctly apply 's to irregular plural nouns that don't already end in s.",
      whyMatters: "irregular plurals break the “add the apostrophe after the s” pattern students have just learned, making them a favourite trap right after plural possession is taught.",
      conceptTitle: "No s yet, so treat it like a singular",
      conceptBullets: [
        'An <b style="color:#C9A24B">irregular plural</b> is a plural noun that doesn\'t end in s — <i>children</i>, <i>men</i>, <i>women</i>, <i>people</i>, <i>mice</i>.',
        "Because these words don't already end in s, they follow the singular-possession rule: add an apostrophe, then s.",
        'Example: "the <i>children\'s</i> playground", "the <i>men\'s</i> changing room", "the <i>women\'s</i> football team".',
        'Writing "childrens\'" is always wrong — there\'s no plain word "childrens" to attach an apostrophe to.',
      ],
      conceptNote: "<b>Test it:</b> ask “does this plural word already end in s on its own?” If not, treat it exactly like a singular owner: apostrophe then s.",
      glossary: [
        { term: "irregular plural", def: "a plural that doesn't end in s (children, men, women, people)" },
        { term: "children's / men's / women's", def: "the correct possessive forms — 's, never s'" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: IrregularPluralPossessionDemo,
      worked: {
        question: "Spot the error: “The mens' football boots were left by the door.”",
        fastMethod: '"men" is an irregular plural that doesn\'t end in s, so it takes \'s like a singular noun, not an apostrophe after an s.',
        steps: [
          "Check whether “men” ends in s on its own — it doesn't.",
          "Irregular plurals that don't end in s follow the singular rule: apostrophe, then s.",
          "“Mens'” wrongly treats “men” as if it already ended in s.",
          "Corrected: “The men's football boots were left by the door.”",
        ],
        answer: "The error is <b>mens'</b> — it should be <b>men's</b>.",
      },
      selfCheck: { prompt: "How do you write “the toys belonging to the children” using a possessive?", answer: "<b>The children's toys</b> — “children” doesn't end in s, so it takes 's, just like a singular noun." },
      kind: "click-error",
      questions: [
        {
          id: "irreg-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "mens", "changing", "room", "was", "being", "repainted."],
          errorIdx: 1,
          correction: '"mens" should be "men\'s" — "men" is already plural and doesn\'t end in s, so it takes \'s like a singular noun.',
          hint: "Check whether this irregular plural already ends in s before deciding where the apostrophe goes.",
        },
        {
          id: "irreg-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "womens", "football", "team", "won", "the", "cup", "final."],
          errorIdx: 1,
          correction: '"womens" should be "women\'s" — "women" doesn\'t end in s, so the possessive is formed with \'s, not s\'.',
          hint: "This irregular plural is missing its apostrophe entirely — where should it go?",
        },
        {
          id: "irreg-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "childrens'", "playground", "was", "closed", "for", "repairs."],
          errorIdx: 1,
          correction: '"childrens\'" should be "children\'s" — never add an s before the apostrophe on an irregular plural that doesn\'t naturally end in s.',
          hint: "There's no word “childrens” — think about what the base plural word actually is.",
        },
      ],
      mistakes: [
        "Treating every plural the same way and adding s' out of habit, even when the plural doesn't end in s (children, men, women).",
        "Inventing a non-existent plural like “childrens” by adding an extra s before the apostrophe.",
      ],
      examTip: "Say the plain plural word on its own first — if it doesn't already end in s (children, men, women, people), it takes 's, exactly like a singular noun.",
      searchTerms: ["apostrophe", "irregular plural", "children's", "men's", "women's", "possession"],
    },
    {
      id: "joint-vs-separate-possession",
      title: "Joint vs. Separate Possession",
      tier: "Standard",
      objective: "Use a single apostrophe for shared ownership between two people, and a separate apostrophe on each name when ownership is separate.",
      whyMatters: "this is one of the more nuanced apostrophe rules on 11+ papers, and it tests whether you can read the meaning of a sentence, not just spot a pattern.",
      conceptTitle: "Shared thing vs. separate things",
      conceptBullets: [
        'When two people <b style="color:#C9A24B">jointly</b> own one thing, only the second name takes the apostrophe: "<i>Tom and Jerry\'s</i> house" (they share one house).',
        'When two people own <b>separate</b> things, each name needs its own apostrophe: "<i>Tom\'s and Jerry\'s</i> houses" (each has a different house).',
        "A useful clue is the noun itself: a singular shared noun (house, essay, car) often signals joint ownership; a plural noun (houses, essays) often signals separate ownership.",
        "Always check what's actually being owned before deciding how many apostrophes the sentence needs.",
      ],
      conceptNote: "<b>Test it:</b> ask “is this one shared thing, or two different things?” — one apostrophe for shared, two apostrophes for separate.",
      glossary: [
        { term: "joint possession", def: "two or more owners sharing one thing" },
        { term: "separate possession", def: "each owner has their own, separate thing" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: JointSeparatePossessionDemo,
      worked: {
        question: "Spot the error: “Aisha's and Ben's dog followed them everywhere.”",
        fastMethod: 'There is only one dog, shared by Aisha and Ben — joint possession needs just one apostrophe, on the second name: Aisha and Ben\'s.',
        steps: [
          "Check what's being owned: “dog” is singular — just one dog.",
          "One shared thing means joint possession, which needs only one apostrophe.",
          "Only the second name in the pair takes the apostrophe.",
          "Corrected: “Aisha and Ben's dog followed them everywhere.”",
        ],
        answer: "The error is <b>Aisha's</b> — it should be <b>Aisha</b> (no apostrophe), giving “Aisha and Ben's dog”.",
      },
      selfCheck: { prompt: "“Noah's and Ellie's bikes were both new.” Is this joint or separate possession, and is it correct?", answer: "<b>Separate</b> — “bikes” is plural, so each person owns their own bike, and each name correctly has its own apostrophe." },
      kind: "click-error",
      questions: [
        {
          id: "joint-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Mo's", "and", "Priya's", "essay", "won", "first", "prize", "in", "the", "competition."],
          errorIdx: 0,
          correction: '"Mo\'s" should be "Mo" — since Mo and Priya share one essay (joint possession), only the second name takes the apostrophe: Mo and Priya\'s essay.',
          hint: "Check whether there is one shared essay or two separate ones.",
        },
        {
          id: "joint-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Layla", "and", "Zara's", "phones", "were", "both", "left", "on", "the", "bus."],
          errorIdx: 0,
          correction: '"Layla" should be "Layla\'s" — Layla and Zara each own a separate phone, so both names need their own possessive: Layla\'s and Zara\'s phones.',
          hint: "“Phones” is plural — does that suggest one shared thing or two separate things?",
        },
        {
          id: "joint-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Ben's", "and", "Leo's", "grandmother", "baked", "a", "cake", "for", "the", "party."],
          errorIdx: 0,
          correction: '"Ben\'s" should be "Ben" — Ben and Leo share the same grandmother (joint possession), so only the second name needs the apostrophe: Ben and Leo\'s grandmother.',
          hint: "Think about whether Ben and Leo could realistically have two different grandmothers here.",
        },
      ],
      mistakes: [
        "Adding an apostrophe to both names for something that is clearly shared (one house, one grandmother, one essay).",
        "Using only one apostrophe when each person actually owns a separate thing (their own phone, their own bike).",
      ],
      examTip: "Look at the noun being owned first — singular usually means shared (one apostrophe), plural usually means separate (two apostrophes).",
      searchTerms: ["apostrophe", "joint possession", "separate possession", "shared ownership", "two owners"],
    },
    {
      id: "decades-and-plural-letters",
      title: "Apostrophes in Decades & Plurals of Numbers/Letters",
      tier: "Standard",
      objective: "Know when an apostrophe is and isn't needed for plural numbers, decades and letters.",
      whyMatters: "these plurals confuse students precisely because the rule is different from ordinary possession — an apostrophe appears here for clarity, not ownership.",
      conceptTitle: "Plural, not possessive",
      conceptBullets: [
        'Decades and plural numbers are simple <b style="color:#C9A24B">plurals</b>, not possessives, so they take <b>no apostrophe</b>: "the <i>1990s</i>", "she scored two <i>10s</i>".',
        'Plurals of single letters are the one exception — an apostrophe is used purely for <b>clarity</b>, since a letter plus s could be misread as a word: "mind your <i>p\'s and q\'s</i>".',
        "This apostrophe isn't showing ownership at all — it's there only so the reader doesn't misread the letter as a different word.",
        'Modern style increasingly drops the apostrophe even for letters when there\'s no risk of confusion (e.g. "the three Rs"), but 11+ papers expect the clarity apostrophe for single lower-case letters.',
      ],
      conceptNote: "<b>Remember:</b> numbers and decades — no apostrophe. Single letters — apostrophe allowed for clarity, not possession.",
      glossary: [
        { term: "decade plural", def: "a decade written as a simple plural (1990s), no apostrophe" },
        { term: "clarity apostrophe", def: "used on plural single letters to avoid confusion with a word" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: DecadesLettersApostropheDemo,
      worked: {
        question: "Spot the error: “Fashion in the 1960's was famous for bold colours and patterns.”",
        fastMethod: 'A decade is a simple plural, not a possessive — "1960\'s" should have no apostrophe: 1960s.',
        steps: [
          "Check what the apostrophe is trying to show — ownership, or just a plural.",
          "A decade is a plural of years, not something that owns anything.",
          "Decades never take an apostrophe: 1960s, not 1960's.",
          "Corrected: “Fashion in the 1960s was famous for bold colours and patterns.”",
        ],
        answer: "The error is <b>1960's</b> — it should be <b>1960s</b>.",
      },
      selfCheck: { prompt: "Does “mind your ps and qs” need any apostrophes?", answer: "<b>Yes</b> — “mind your p's and q's” — single letters use an apostrophe for clarity, so “ps” and “qs” aren't misread as words." },
      kind: "click-error",
      questions: [
        {
          id: "dec-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["My", "grandmother", "grew", "up", "in", "the", "1970's,", "a", "decade", "of", "big", "change."],
          errorIdx: 6,
          correction: '"1970\'s" should be "1970s" — decades are simple plurals and don\'t need an apostrophe.',
          hint: "Ask whether this number is showing possession, or is simply plural.",
        },
        {
          id: "dec-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Remember", "to", "dot", "your", "i's", "and", "cross", "your", "ts."],
          errorIdx: 8,
          correction: '"ts" should be "t\'s" — an apostrophe clarifies you\'re pluralising the single letter t, avoiding confusion with the word "ts".',
          hint: "One of these two similar phrases is missing its clarity apostrophe.",
        },
        {
          id: "dec-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "scored", "two", "9's", "in", "her", "gymnastics", "routine."],
          errorIdx: 3,
          correction: '"9\'s" should be "9s" — plural numbers don\'t need an apostrophe, unlike single letters, which may use one for clarity.',
          hint: "Check whether this is a plural number or a plural letter — the rule is different for each.",
        },
      ],
      mistakes: [
        "Adding a possessive-style apostrophe to a decade or plural number out of habit (“1990's” instead of “1990s”).",
        "Leaving out the clarity apostrophe on a plural single letter, making it look like a completely different short word.",
      ],
      examTip: "Ask “is this apostrophe showing ownership, or just helping the reader avoid misreading a letter?” — numbers and decades never need one either way.",
      searchTerms: ["apostrophe", "decade", "1990s", "plural numbers", "plural letters", "clarity apostrophe"],
    },
    {
      id: "greengrocers-apostrophe",
      title: "The “Greengrocer's Apostrophe”",
      tier: "Extension",
      objective: "Recognise and correct the common error of adding an apostrophe to an ordinary plural that shows no possession at all.",
      whyMatters: "the greengrocer's apostrophe is one of the most widely recognised punctuation errors in real-world English — spotting it instantly is a strong exam skill.",
      conceptTitle: "A plural is not a possessive",
      conceptBullets: [
        'The <b style="color:#C9A24B">“greengrocer\'s apostrophe”</b> is the mistake of adding an apostrophe to a simple plural, as if it were a possessive — e.g. a sign reading "<i>banana\'s</i> for sale".',
        "It's named after the classic (and very common) shop-sign error, though it can appear with any ordinary plural noun.",
        'The fix is simple: if nothing is being "owned", the word is just a plural and needs no apostrophe at all.',
        "This is the opposite mistake to forgetting a genuine possessive apostrophe — here, one has been added where it was never needed.",
      ],
      conceptNote: "<b>Test it:</b> ask “does this word own something else in the sentence?” If not, it's a plain plural — no apostrophe.",
      glossary: [
        { term: "greengrocer's apostrophe", def: "wrongly adding an apostrophe to a simple plural" },
        { term: "simple plural", def: "more than one of something, with no ownership involved" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: GreengrocersApostropheDemo,
      worked: {
        question: "Spot the error: “The stall sold fresh strawberry's and homemade jam every Saturday.”",
        fastMethod: 'Nothing belongs to the strawberries here — this is a plain plural, so it needs no apostrophe: strawberries.',
        steps: [
          "Check whether “strawberry's” is showing ownership of anything in the sentence.",
          "It isn't — the sentence is simply describing more than one strawberry.",
          "A plain plural never takes an apostrophe.",
          "Corrected: “The stall sold fresh strawberries and homemade jam every Saturday.”",
        ],
        answer: "The error is <b>strawberry's</b> — it should be <b>strawberries</b>.",
      },
      selfCheck: { prompt: "Is an apostrophe needed in “CDs” when talking about several compact discs?", answer: "<b>No</b> — “CDs” is a simple plural with no ownership involved, so it should never be written “CD's”." },
      kind: "click-error",
      questions: [
        {
          id: "green-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "shop", "sold", "fresh", "tomato's", "every", "morning."],
          errorIdx: 4,
          correction: '"tomato\'s" should be "tomatoes" — this is a simple plural, not a possessive, so it needs no apostrophe.',
          hint: "Ask what, if anything, belongs to the tomatoes in this sentence.",
        },
        {
          id: "green-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Please", "remove", "your", "shoe's", "before", "entering", "the", "house."],
          errorIdx: 3,
          correction: '"shoe\'s" should be "shoes" — a simple plural needs no apostrophe.',
          hint: "This word is just describing more than one item — no ownership is involved.",
        },
        {
          id: "green-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "car", "park", "has", "spaces", "for", "ten", "car's", "at", "a", "time."],
          errorIdx: 7,
          correction: '"car\'s" should be "cars" — this is a plain plural describing how many cars fit, with no possession involved.',
          hint: "Check whether anything is being “owned” by the cars in this sentence.",
        },
      ],
      mistakes: [
        "Adding an apostrophe to any plural noun ending in a vowel sound, purely out of habit, even with no ownership involved.",
        "Assuming every s at the end of a word signals a possessive, rather than checking what — if anything — is actually being owned.",
      ],
      examTip: "Before adding an apostrophe to a word ending in s, ask “does this word own something else in the sentence?” If the answer is no, leave the apostrophe out.",
      searchTerms: ["apostrophe", "greengrocer's apostrophe", "simple plural", "plural error", "punctuation"],
    },
    {
      id: "possessive-pronouns-no-apostrophe",
      title: "Possessive Pronouns Never Take an Apostrophe",
      tier: "Extension",
      objective: "Recognise the full set of possessive pronouns and use them correctly without an apostrophe, even though noun possessives normally take one.",
      whyMatters: "possessive pronouns are the one place where the usual apostrophe rule for possession is reversed — a favourite “spot the mistake” trap for exactly that reason.",
      conceptTitle: "An exception to the possession rule",
      conceptBullets: [
        'A <b style="color:#C9A24B">possessive pronoun</b> replaces a possessive noun phrase and shows ownership on its own: <i>mine</i>, <i>yours</i>, <i>his</i>, <i>hers</i>, <i>its</i>, <i>ours</i>, <i>theirs</i>.',
        "Unlike a noun possessive (the dog's bone), a possessive pronoun is <b>never</b> written with an apostrophe, in any form.",
        'Example: "That bike is <i>hers</i>", not "her\'s"; "The choice is <i>theirs</i>", not "their\'s".',
        "This contrasts directly with contractions that look similar — “it's” (it is) does take an apostrophe, but the possessive “its” never does.",
      ],
      conceptNote: "<b>Remember the list:</b> mine, yours, his, hers, its, ours, theirs — not one of them ever takes an apostrophe.",
      glossary: [
        { term: "possessive pronoun", def: "a pronoun that shows ownership on its own (mine, yours, his, hers, its, ours, theirs)" },
        { term: "possessive noun", def: "a noun with 's or s' added to show ownership" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: PossessivePronounNoApostropheDemo,
      worked: {
        question: "Spot the error: “I thought the red scarf was your's, but it turned out to be their's.”",
        fastMethod: 'Both "your\'s" and "their\'s" are possessive pronouns — neither should ever have an apostrophe.',
        steps: [
          "Identify the two possessive pronouns: “your's” and “their's”.",
          "Possessive pronouns never take an apostrophe, in any form.",
          "The correct spellings are “yours” and “theirs”.",
          "Corrected: “I thought the red scarf was yours, but it turned out to be theirs.”",
        ],
        answer: "Both <b>your's</b> and <b>their's</b> are wrong — they should be <b>yours</b> and <b>theirs</b>.",
      },
      selfCheck: { prompt: "True or false: “This coat is his's” is correct.", answer: "<b>False</b> — “his” is already the complete possessive pronoun; it never takes an apostrophe or an extra s." },
      kind: "click-error",
      questions: [
        {
          id: "poss-pro-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["This", "umbrella", "is", "your's,", "I", "think,", "not", "mine."],
          errorIdx: 3,
          correction: '"your\'s" should be "yours" — possessive pronouns never take an apostrophe.',
          hint: "This word already shows ownership on its own — check whether it needs any apostrophe at all.",
        },
        {
          id: "poss-pro-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "trophy", "is", "their's", "after", "winning", "the", "final."],
          errorIdx: 3,
          correction: '"their\'s" should be "theirs" — possessive pronouns are never written with an apostrophe.',
          hint: "Compare this word to “mine” and “his” — do those ever take an apostrophe?",
        },
        {
          id: "poss-pro-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["That", "seat", "is", "our's,", "we", "booked", "it", "in", "advance."],
          errorIdx: 3,
          correction: '"our\'s" should be "ours" — like all possessive pronouns, it never takes an apostrophe.',
          hint: "This possessive pronoun has picked up an apostrophe it should never have.",
        },
      ],
      mistakes: [
        "Adding an apostrophe to a possessive pronoun by analogy with noun possessives (the dog's bone), forgetting pronouns follow a different rule.",
        "Confusing “its” (possessive pronoun, no apostrophe) with “it's” (contraction of “it is”, always with an apostrophe).",
      ],
      examTip: "Learn the seven possessive pronouns by heart — mine, yours, his, hers, its, ours, theirs — and treat every apostrophe near one of them as an automatic error.",
      searchTerms: ["apostrophe", "possessive pronoun", "hers", "yours", "theirs", "ours", "its"],
    },
    {
      id: "names-ending-in-s",
      title: "Names Ending in S (James' vs. James's)",
      tier: "Extension",
      objective: "Apply the modern UK convention for forming the possessive of a singular name that already ends in s.",
      whyMatters: "this is a genuinely debated point of style, and 11+ papers expect a specific, consistent answer — knowing the exam-board convention avoids losing marks on a technicality.",
      conceptTitle: "Say it, then spell it",
      conceptBullets: [
        'For a singular name ending in <i>s</i> — <i>James</i>, <i>Thomas</i>, <i>Chris</i> — most modern style guides, and 11+ exam convention, add a full <b style="color:#C9A24B">\'s</b>: <i>James\'s</i>, <i>Thomas\'s</i>, <i>Chris\'s</i>.',
        "This matches how the word is actually spoken: you say the extra syllable (“James-iz”), so the spelling adds the extra 's to match.",
        'An older style drops the extra s and uses just an apostrophe (<i>James\'</i>) — you may see this in older books, but it is not the form to use in these exams.',
        "This rule is only for singular names — a plural name ending in s (the Jameses) still follows the ordinary plural-possession rule: the Jameses' house.",
      ],
      conceptNote: "<b>Remember:</b> for these exams, singular names ending in s take a full 's — James's, Chris's, Thomas's — matching the extra syllable you hear when you say it aloud.",
      glossary: [
        { term: "James's", def: "the modern, exam-convention possessive of a singular name ending in s" },
        { term: "James'", def: "an older style, apostrophe only — not the convention used here" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: NamesEndingInSDemo,
      worked: {
        question: "Spot the error: “Lucas' younger brother joined the same football club.”",
        fastMethod: 'Say the name aloud with the possessive: you hear an extra syllable, “Lucas-iz”, so it should be spelled Lucas\'s.',
        steps: [
          "Say the possessive form aloud: “Lucas's brother”.",
          "Notice the extra syllable you pronounce at the end of the name.",
          "The spelling should match that extra syllable with a full 's.",
          "Corrected: “Lucas's younger brother joined the same football club.”",
        ],
        answer: "The error is <b>Lucas'</b> — it should be <b>Lucas's</b>.",
      },
      selfCheck: { prompt: "Which is the exam-convention spelling: “Silas' pencil case” or “Silas's pencil case”?", answer: "<b>Silas's pencil case</b> — singular names ending in s take a full 's in this convention." },
      kind: "click-error",
      questions: [
        {
          id: "names-s-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Chris'", "guitar", "was", "left", "leaning", "against", "the", "wall."],
          errorIdx: 0,
          correction: '"Chris\'" should be "Chris\'s" — singular names ending in s take a full \'s, spoken with an extra syllable.',
          hint: "Say the name and the possessive together out loud — how many syllables do you hear at the end?",
        },
        {
          id: "names-s-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Thomas'", "younger", "sister", "joined", "the", "choir", "this", "term."],
          errorIdx: 0,
          correction: '"Thomas\'" should be "Thomas\'s" — the exam convention adds a full \'s to singular names ending in s.',
          hint: "This name is missing the extra s that matches how the possessive is actually pronounced.",
        },
        {
          id: "names-s-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["We", "borrowed", "Charles'", "bike", "for", "the", "weekend."],
          errorIdx: 2,
          correction: '"Charles\'" should be "Charles\'s" — following the modern convention for singular names ending in s.',
          hint: "Check whether this name has the full 's the exam convention expects.",
        },
      ],
      mistakes: [
        "Dropping the extra s on a singular name ending in s, using the older apostrophe-only style instead of the exam convention.",
        "Confusing this rule with plural possession — a name like James only follows this rule when there's one James, not several.",
      ],
      examTip: "For 11+ papers, always add the full 's to a singular name ending in s — James's, Chris's, Thomas's — matching the extra syllable you hear.",
      searchTerms: ["apostrophe", "names ending in s", "james's", "possessive names", "singular possession"],
    },
    {
      id: "mixed-review-apostrophes",
      title: "Mixed Review: Spot-the-Apostrophe-Error",
      tier: "Extension",
      objective: "Apply every apostrophe rule from this module together, quickly identifying which specific pattern has gone wrong in a mixed set of sentences.",
      whyMatters: "real exam papers don't label which apostrophe rule is being tested — this subtopic trains you to diagnose the pattern first, then apply the right fix.",
      conceptTitle: "Diagnose before you fix",
      conceptBullets: [
        "Before correcting an apostrophe error, first name which category it belongs to: contraction vs. possessive, singular vs. plural, irregular plural, joint/separate, or a simple plural with no apostrophe needed at all.",
        'Ask three quick questions in order: "Is anything being owned?" → "How many owners are there?" → "Does the owner\'s word already end in s?"',
        "A stray apostrophe on a simple plural (the greengrocer's apostrophe) is just as much an error as a missing one on a genuine possessive — both directions count.",
        "Possessive pronouns (hers, yours, theirs, its) are the one category that breaks the pattern entirely — they never take an apostrophe, whatever else is going on.",
      ],
      conceptNote: "<b>Fast method:</b> work through the three-question checklist above on any word ending in s before deciding whether — and where — an apostrophe belongs.",
      glossary: [
        { term: "diagnosis", def: "identifying which apostrophe rule applies before fixing the error" },
        { term: "possessive checklist", def: "ownership? how many owners? does the name already end in s?" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: MixedApostropheReviewDemo,
      worked: {
        question: "Spot the error: “The teachers' lounge was quiet, since it's usually busy at lunchtime.”",
        fastMethod: 'Check each apostrophe in turn: "teachers\'" (plural possession, several teachers) is correct; "it\'s" needs testing — does "it is usually busy" make sense? Yes, so it\'s also correct. Look again for a genuine error elsewhere in the full sentence.',
        steps: [
          "Work through every apostrophe in the sentence, not just the first one you notice.",
          "“Teachers'” — more than one teacher sharing a lounge — correctly plural possessive.",
          "“It's” — expand to “it is usually busy” — correctly a contraction here.",
          "In this sentence both apostrophes are actually correct — a reminder to check, not assume.",
        ],
        answer: "This sentence is actually <b>correct</b> as written — both apostrophes pass the test.",
      },
      selfCheck: { prompt: "In “the boys's football was left in the garden”, what's wrong?", answer: "<b>\"boys's\"</b> is wrong — for a regular plural like “boys”, the apostrophe goes after the s with nothing added: boys'." },
      kind: "click-error",
      questions: [
        {
          id: "mix-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "three", "boy's", "shared", "one", "bedroom", "at", "their", "grandparents", "house."],
          errorIdx: 2,
          correction: '"boy\'s" should be "boys\'" — three boys share the bedroom, so it needs the plural possessive, not the singular one.',
          hint: "Count the owners first — is this really about just one boy?",
        },
        {
          id: "mix-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Its", "been", "raining", "all", "week,", "so", "the", "match", "was", "postponed."],
          errorIdx: 0,
          correction: '"Its" should be "It\'s" — short for "it has" here, not the possessive "its".',
          hint: "Try expanding the first word into “it has” and see if the sentence still makes sense.",
        },
        {
          id: "mix-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "bakery", "sold", "fresh", "cake's", "to", "raise", "money", "for", "charity."],
          errorIdx: 4,
          correction: '"cake\'s" should be "cakes" — a simple plural, not a possessive, so it needs no apostrophe.',
          hint: "Ask whether anything in the sentence actually belongs to the cakes.",
        },
      ],
      mistakes: [
        "Fixing the first apostrophe that looks unusual without running the full ownership-and-count checklist on it.",
        "Assuming every sentence in a mixed review must contain an error of the most recently studied type, rather than checking each pattern fresh.",
      ],
      examTip: "Run the three-question checklist on every apostrophe you meet — ownership, number of owners, and whether the owner's word already ends in s — rather than relying on how the sentence sounds.",
      searchTerms: ["apostrophe", "possession", "mixed review", "spot the error", "punctuation"],
    },
  ],
};
