import type { TopicContent } from "../types";
import { BiologyInheritanceVariationEvolutionDnaGenesAndChromosomesDemo, BiologyInheritanceVariationEvolutionMeiosisAndGeneticCrossesDemo, BiologyInheritanceVariationEvolutionVariationMutationAndEvolutionDemo } from "../notes-diagrams/biology-inheritance-variation-evolution-demos";

export const biologyInheritanceVariationEvolutionTopic: TopicContent = {
  slug: "biology-inheritance-variation-evolution",
  subject: "Biology",
  subjectSlug: "gcse-science/biology",
  title: "GCSE Biology: Inheritance, Variation and Evolution",
  description: "AQA GCSE Biology — Inheritance, Variation and Evolution. Covers DNA structure, genes and chromosomes, meiosis and sexual/asexual reproduction, monohybrid genetic crosses and Punnett squares, variation and mutation, evolution by natural selection, and classification systems.",
  glyphs: ["🧬","🔬","🌱","🫀"],
  subtopics: [
    {
      id: "dna-genes-and-chromosomes",
      title: "DNA, genes and chromosomes",
      tier: "Foundation",
      objective: "Identify the structure of DNA and explain how genes are organised on chromosomes.",
      whyMatters: "Understanding DNA is fundamental for all later genetics questions and is frequently tested in multiple‑choice and short‑answer items.",
      conceptTitle: "Core concepts",
      conceptBullets: ["DNA is a double‑helix made of two strands of nucleotides linked by <b style=\"color:#C9A24B\">hydrogen bonds</b> between complementary bases.","Each nucleotide contains a <b style=\"color:#C9A24B\">phosphate‑sugar backbone</b> and one of four bases: adenine, thymine, cytosine or guanine.","A <b style=\"color:#C9A24B\">gene</b> is a segment of DNA that codes for a specific protein or RNA product.","Genes are arranged linearly on <b style=\"color:#C9A24B\">chromosomes</b>, which are duplicated during the S‑phase of the cell cycle."],
      conceptNote: "<b>Tip:</b> Sketch a labelled DNA double helix and colour‑code the base pairs – this visual cue speeds up recall in exams.",
      glossary: [{"term":"nucleotide","def":"The basic building block of DNA, consisting of a phosphate group, a sugar, and a nitrogenous base."},{"term":"gene","def":"A specific region of DNA that contains the instructions to make a particular protein."},{"term":"chromosome","def":"A long, thread‑like structure of DNA coiled around proteins, containing many genes."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyInheritanceVariationEvolutionDnaGenesAndChromosomesDemo,
      worked: {"question":"A cell has 46 chromosomes. If each chromosome contains on average 2 × 10⁸ base pairs, estimate the total number of base pairs in the cell’s DNA.","fastMethod":"Multiply chromosome number by average base pairs per chromosome.","steps":["46 chromosomes × 2 × 10⁸ base pairs = 9.2 × 10⁹ base pairs.","State the answer in scientific notation."],"answer":"9.2 × 10⁹ base pairs"},
      selfCheck: {"prompt":"True or false: DNA strands run in the same direction.","answer":"False – the strands are antiparallel."},
      questions: [{"id":"dna-genes-and-chromosomes-q1","prompt":"Name the four nitrogenous bases found in DNA.","accept":["adenine, thymine, cytosine, guanine","adenine thymine cytosine guanine"],"hint":"Two are purines, two are pyrimidines."},{"id":"dna-genes-and-chromosomes-q2","prompt":"What term describes a region of DNA that codes for a protein?","accept":["gene"],"hint":"It is the basic unit of heredity."},{"id":"dna-genes-and-chromosomes-q3","prompt":"How many chromosomes are present in a typical human somatic cell?","accept":["46","forty‑six"],"hint":"Think of pairs."}],
      mistakes: ["Confusing the number of chromosomes with the number of genes.","Reversing the base‑pairing rule (e.g., saying A pairs with C)."],
      examTip: "When a question asks for the number of chromosomes, remember it is always a whole number – never write ‘46 pairs’.",
      searchTerms: ["dna structure","what is a gene","human chromosomes","base pairing","nucleotide definition"],
    },
    {
      id: "meiosis-and-genetic-crosses",
      title: "Meiosis and genetic crosses",
      tier: "Standard",
      objective: "Explain how meiosis creates gametes and use Punnett squares to predict offspring ratios.",
      whyMatters: "Meiosis underpins inheritance; Punnett squares are a staple of GCSE exam questions, especially in 2‑mark and 3‑mark items.",
      conceptTitle: "Core concepts",
      conceptBullets: ["Meiosis consists of two successive divisions (Meiosis I and II) producing four <b style=\"color:#C9A24B\">haploid</b> cells from one diploid cell.","During <b style=\"color:#C9A24B\">crossing‑over</b> homologous chromosomes exchange segments, creating new allele combinations.","A <b style=\"color:#C9A24B\">monohybrid cross</b> involves one trait with two alleles, giving a 3:1 phenotypic ratio for a dominant‑recessive pair.","A <b style=\"color:#C9A24B\">Punnett square</b> visually combines parental gamete genotypes to show possible offspring genotypes."],
      conceptNote: "<b>Tip:</b> Always write the gamete alleles on the top and side of the Punnett square before filling in the boxes – it prevents mixing up dominant/recessive symbols.",
      glossary: [{"term":"haploid","def":"A cell containing a single set of chromosomes (n)."},{"term":"crossing‑over","def":"The exchange of genetic material between homologous chromosomes during meiosis I."},{"term":"Punnett square","def":"A grid used to predict the genotype and phenotype ratios of a genetic cross."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: BiologyInheritanceVariationEvolutionMeiosisAndGeneticCrossesDemo,
      worked: {"question":"A plant heterozygous for flower colour (Rr) is crossed with a homozygous recessive plant (rr). Use a Punnett square to find the expected proportion of red‑flowered offspring.","fastMethod":"Identify genotypes of gametes and count red (RR or Rr) squares.","steps":["Gametes: R or r from Rr; r only from rr.","Punnett square: Rr, rr, Rr, rr.","Two out of four squares are red‑flowered (Rr)."],"answer":"50 % of the offspring are expected to have red flowers."},
      selfCheck: {"prompt":"True or false: Meiosis produces genetically identical cells.","answer":"False – crossing‑over and independent assortment make each gamete unique."},
      questions: [{"id":"meiosis-and-genetic-crosses-q1","prompt":"What is the phenotypic ratio for a monohybrid cross of two heterozygotes?","accept":["3:1","three to one"],"hint":"Count dominant vs recessive phenotypes."},{"id":"meiosis-and-genetic-crosses-q2","prompt":"How many different types of gamete can a plant produce if it is heterozygous for two traits?","accept":["4","four"],"hint":"Use 2ⁿ where n = number of heterozygous traits."},{"id":"meiosis-and-genetic-crosses-q3","prompt":"Name the stage of meiosis where crossing‑over occurs.","accept":["prophase i","prophase 1"],"hint":"It is the first stage of meiosis I."}],
      mistakes: ["Drawing the Punnett square with alleles on the same side, leading to incorrect genotype combinations.","Assuming meiosis always yields identical gametes, ignoring crossing‑over."],
      examTip: "For 2‑mark questions, write the genotype ratio first, then convert to the phenotype ratio – examiners award marks for both steps.",
      searchTerms: ["meiosis stages","punnett square example","monohybrid cross ratio","crossing over definition","haploid cells"],
    },
    {
      id: "variation-mutation-and-evolution",
      title: "Variation, mutation and evolution",
      tier: "Extension",
      objective: "Analyse how genetic variation arises and how natural selection drives evolution.",
      whyMatters: "This subtopic links genetics to ecology and is heavily weighted in longer‑answer questions, requiring evaluation of evidence.",
      conceptTitle: "Core concepts",
      conceptBullets: ["Genetic <b style=\"color:#C9A24B\">variation</b> originates from mutations, sexual reproduction (independent assortment, crossing‑over) and gene flow.","A <b style=\"color:#C9A24B\">mutation</b> is a permanent change in the DNA sequence; most are neutral, some are harmful or beneficial.","Natural <b style=\"color:#C9A24B\">selection</b> favours individuals with traits that increase survival and reproductive success in a given environment.","Over many generations, favourable traits become more common, leading to <b style=\"color:#C9A24B\">evolution</b> of populations."],
      conceptNote: "<b>Tip:</b> When answering essay questions, structure your response: define, give example, explain mechanism, and evaluate limitations.",
      glossary: [{"term":"mutation","def":"A change in the nucleotide sequence of DNA that can alter gene function."},{"term":"natural selection","def":"The process by which organisms better adapted to their environment tend to survive and reproduce more."},{"term":"evolution","def":"A change in the genetic composition of a population over successive generations."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyInheritanceVariationEvolutionVariationMutationAndEvolutionDemo,
      worked: {"question":"In a population of 200 beetles, 60 are green (G) and 140 are brown (g). If green colour is dominant (Gg or GG) and provides camouflage, calculate the expected frequency of the green allele (p) assuming Hardy‑Weinberg equilibrium.","fastMethod":"Use p = sqrt(frequency of dominant phenotype) approximated by genotype frequencies.","steps":["Assume most green beetles are heterozygous (Gg) because brown is recessive.","Frequency of recessive phenotype (gg) = 140/200 = 0.70, so q² = 0.70, q = √0.70 ≈ 0.84.","p = 1 – q ≈ 0.16."],"answer":"The green allele frequency p ≈ 0.16 (16 %)."},
      selfCheck: {"prompt":"True or false: All mutations are harmful.","answer":"False – many mutations are neutral or can be beneficial."},
      questions: [{"id":"variation-mutation-and-evolution-q1","prompt":"Give one example of a beneficial mutation in humans.","accept":["sickle‑cell trait","sickle cell trait"],"hint":"Think of malaria resistance."},{"id":"variation-mutation-and-evolution-q2","prompt":"What is the main difference between natural selection and artificial selection?","accept":["humans choose traits","selection by humans"],"hint":"Consider who determines the favourable trait."},{"id":"variation-mutation-and-evolution-q3","prompt":"State one condition required for a population to be in Hardy‑Weinberg equilibrium.","accept":["no mutation","large population size","random mating","no migration","no selection"],"hint":"Pick any of the five standard conditions."}],
      mistakes: ["Confusing allele frequency (p) with phenotype frequency.","Treating a single beneficial mutation as proof of overall species evolution."],
      examTip: "When asked to evaluate natural selection, allocate a line for each point: evidence, mechanism, limitation – this ensures you earn marks for depth.",
      searchTerms: ["genetic variation sources","natural selection definition","mutation examples","hardy weinberg calculation","evolution mechanisms"],
    }
  ],
};
