import type { TopicContent } from "../types";
import { BiologyInfectionResponsePathogensAndCommunicableDiseasesDemo, BiologyInfectionResponseBodyDefencesAndTheImmuneSystemDemo, BiologyInfectionResponseDrugsAntibioticsAndResistanceDemo } from "../notes-diagrams/biology-infection-response-demos";

export const biologyInfectionResponseTopic: TopicContent = {
  slug: "biology-infection-response",
  subject: "Biology",
  subjectSlug: "gcse-science/biology",
  title: "GCSE Biology: Infection and Response",
  description: "AQA GCSE Biology — Infection and Response. Covers communicable diseases and pathogens (bacteria, viruses, fungi, protists), how the body defends against pathogens, the immune system (white blood cells, antibodies), vaccination (herd immunity), antibiotics and antibiotic resistance, and the stages of developing new drugs.",
  glyphs: ["🧬","🔬","🌱","🫀"],
  subtopics: [
    {
      id: "pathogens-and-communicable-diseases",
      title: "Pathogens and communicable diseases",
      tier: "Foundation",
      objective: "Identify the main types of pathogens and the diseases they cause.",
      whyMatters: "Understanding pathogens is essential for recognising how infections spread and for answering exam questions on disease transmission.",
      conceptTitle: "Types of disease‑causing organisms",
      conceptBullets: ["Bacteria are single‑celled <b style=\"color:#C9A24B\">prokaryotes</b> that can cause diseases such as tuberculosis and strep throat.","Viruses are <b style=\"color:#C9A24B\">non‑cellular</b> particles that need a host cell to replicate, causing flu, measles and COVID‑19.","Fungi are eukaryotic <b style=\"color:#C9A24B\">decomposers</b> that can cause skin infections like athlete’s foot and systemic infections in immunocompromised people.","Protists include <b style=\"color:#C9A24B\">protozoa</b> such as malaria‑causing Plasmodium and Giardia, which are transmitted via vectors or contaminated water."],
      conceptNote: "<b>Tip:</b> Group each pathogen by its cell structure and typical disease examples – this helps recall for multiple‑choice questions.",
      glossary: [{"term":"pathogen","def":"An organism that can cause disease in a host."},{"term":"prokaryote","def":"A cell without a nucleus, e.g., bacteria."},{"term":"protozoan","def":"A single‑celled eukaryotic organism, often a parasite."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyInfectionResponsePathogensAndCommunicableDiseasesDemo,
      worked: {"question":"A classroom of 30 pupils has 4 pupils with a bacterial infection. If the infection spreads to 25% of the susceptible pupils each day, how many new cases are expected after one day?","fastMethod":"Multiply the number of susceptible pupils by 0.25.","steps":["Susceptible pupils = 30 – 4 = 26.","New cases = 26 × 0.25.","Calculate 26 × 0.25 = 6.5 ≈ 7 pupils."],"answer":"Approximately 7 new cases."},
      selfCheck: {"prompt":"True or false: All viruses have a lipid envelope.","answer":"False – only enveloped viruses have a lipid membrane; others are naked."},
      questions: [{"id":"pathogens-and-communicable-diseases-q1","prompt":"Name one disease caused by a protozoan.","accept":["malaria","giardiasis"],"hint":"Think of a disease spread by mosquitoes."},{"id":"pathogens-and-communicable-diseases-q2","prompt":"What structural feature distinguishes bacteria from viruses?","accept":["cell wall","prokaryotic cell"],"hint":"Look for a component that bacteria have but viruses lack."},{"id":"pathogens-and-communicable-diseases-q3","prompt":"Which type of pathogen is responsible for athlete’s foot?","accept":["fungus","fungi"],"hint":"Consider the kingdom that includes moulds."}],
      mistakes: ["Confusing viruses with bacteria and attributing antibiotic treatment to viral infections.","Mixing up protozoa with fungi because both can cause ‘parasitic’ infections."],
      examTip: "When a question asks for a disease, always pair it with the correct pathogen type – this earns marks for both recall and understanding.",
      searchTerms: ["pathogen types","communicable disease examples","bacterial vs viral","protozoan diseases","fungal infection GCSE"],
    },
    {
      id: "body-defences-and-the-immune-system",
      title: "Body defences and the immune system",
      tier: "Standard",
      objective: "Explain how innate and adaptive immunity protect the body from pathogens.",
      whyMatters: "Exam questions often require you to compare first‑line defences with specific immune responses and label cell types.",
      conceptTitle: "Innate vs adaptive immunity",
      conceptBullets: ["The <b style=\"color:#C9A24B\">skin</b> provides a physical barrier that prevents most microbes entering the body.","Phagocytic <b style=\"color:#C9A24B\">white blood cells</b> such as neutrophils engulf and destroy invading bacteria.","The adaptive system uses <b style=\"color:#C9A24B\">B‑cells</b> to produce antibodies that specifically bind to antigens.","<b style=\"color:#C9A24B\">T‑cells</b> (cytotoxic and helper) recognise infected cells and coordinate the immune response."],
      conceptNote: "<b>Tip:</b> Draw a two‑column table (innate | adaptive) and fill in barrier, cells, speed and memory – a quick revision tool.",
      glossary: [{"term":"antibody","def":"A protein produced by B‑cells that binds to a specific antigen."},{"term":"phagocytosis","def":"The process by which a cell engulfs particles or microbes."},{"term":"memory cell","def":"A lymphocyte that remains after an infection to give faster response on re‑exposure."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: BiologyInfectionResponseBodyDefencesAndTheImmuneSystemDemo,
      worked: {"question":"A patient’s blood test shows 150 µL of IgG antibodies per mL. Convert this to mg/L (IgG molecular weight ≈ 150 kDa).","fastMethod":"Use mg = µL × MW ÷ 1000.","steps":["150 µL = 0.150 mL.","Mass = 0.150 mL × 150 kDa = 22.5 µg.","Convert µg to mg: 22.5 µg = 0.0225 mg per mL.","Per litre: 0.0225 mg × 1000 = 22.5 mg/L."],"answer":"22.5 mg/L of IgG."},
      selfCheck: {"prompt":"True or false: Memory B‑cells are part of innate immunity.","answer":"False – they belong to adaptive immunity."},
      questions: [{"id":"body-defences-and-the-immune-system-q1","prompt":"Name the cell type that produces antibodies.","accept":["b cell","b‑cell"],"hint":"It is a type of lymphocyte."},{"id":"body-defences-and-the-immune-system-q2","prompt":"What is the main function of neutrophils?","accept":["phagocytosis","engulf bacteria"],"hint":"Think of ‘first responders’ to bacterial infection."},{"id":"body-defences-and-the-immune-system-q3","prompt":"Why does vaccination give long‑term protection?","accept":["memory cells","immune memory"],"hint":"Recall the role of adaptive immunity."}],
      mistakes: ["Stating that antibodies are part of innate immunity.","Confusing the roles of helper T‑cells and cytotoxic T‑cells."],
      examTip: "When asked to label a diagram, always start with the most general defence (skin) and work inward – this ensures you don’t miss any required labels.",
      searchTerms: ["innate immunity","adaptive immunity GCSE","antibody function","white blood cells types","memory cells exam"],
    },
    {
      id: "drugs-antibiotics-and-resistance",
      title: "Drugs, antibiotics and resistance",
      tier: "Extension",
      objective: "Analyse how antibiotics work, why resistance develops, and outline the drug development pipeline.",
      whyMatters: "These concepts appear in multiple-choice, data‑analysis and extended‑answer questions, testing both knowledge and application.",
      conceptTitle: "Antibiotics, resistance and new drugs",
      conceptBullets: ["Antibiotics target bacterial <b style=\"color:#C9A24B\">cell walls</b>, protein synthesis or DNA replication, killing or inhibiting growth.","Resistance arises when bacteria acquire <b style=\"color:#C9A24B\">mutations</b> or plasmids that neutralise the drug’s action.","The drug development pipeline includes <b style=\"color:#C9A24B\">discovery, pre‑clinical testing, clinical trials (Phase I‑III), regulatory approval and post‑marketing surveillance</b>.","Vaccination reduces disease incidence and creates <b style=\"color:#C9A24B\">herd immunity</b>, protecting even unvaccinated individuals.","Over‑use of antibiotics in humans and agriculture accelerates the spread of resistant strains."],
      conceptNote: "<b>Tip:</b> Memorise the three main antibiotic targets and link each to a common resistance mechanism for quick recall.",
      glossary: [{"term":"antibiotic","def":"A drug that kills or inhibits bacteria without harming human cells."},{"term":"mutation","def":"A permanent change in DNA that can confer drug resistance."},{"term":"herd immunity","def":"Population-level protection when a high proportion are immune, reducing pathogen spread."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyInfectionResponseDrugsAntibioticsAndResistanceDemo,
      worked: {"question":"In a clinical trial 1200 patients receive a new antibiotic; 48 develop a resistant infection. What is the resistance rate per 100 patients?","fastMethod":"Divide number of cases by total and multiply by 100.","steps":["Rate = 48 ÷ 1200 = 0.04.","0.04 × 100 = 4.","Result = 4 per 100 patients."],"answer":"4 cases per 100 patients."},
      selfCheck: {"prompt":"True or false: Antibiotics are effective against viral infections.","answer":"False – they target bacterial processes only."},
      questions: [{"id":"drugs-antibiotics-and-resistance-q1","prompt":"Give one way bacteria can become resistant to penicillin.","accept":["beta‑lactamase","altered penicillin‑binding protein"],"hint":"Think of an enzyme that destroys the drug."},{"id":"drugs-antibiotics-and-resistance-q2","prompt":"What stage of drug development tests safety in a small group of healthy volunteers?","accept":["phase i","phase 1"],"hint":"It is the first clinical trial phase."},{"id":"drugs-antibiotics-and-resistance-q3","prompt":"Why does herd immunity protect unvaccinated individuals?","accept":["reduced transmission","fewer carriers"],"hint":"Consider the pathogen’s ability to find a host."}],
      mistakes: ["Confusing antibiotic resistance with immune resistance (e.g., thinking the body becomes resistant).","Listing all clinical trial phases but omitting the purpose of each."],
      examTip: "When a question asks for a ‘cause and effect’, write a short sentence linking the cause (e.g., over‑use) directly to the effect (resistance) before expanding – this secures the mark.",
      searchTerms: ["antibiotic resistance mechanisms","drug development phases","herd immunity definition","penicillin action","GCSE antibiotics"],
    }
  ],
};
