import type { TopicContent } from "../types";
import { BiologyEcologyEcosystemsAndCommunitiesDemo, BiologyEcologyTrophicLevelsFoodWebsCyclesDemo, BiologyEcologyBiodiversityHumanImpactsConservationDemo } from "../notes-diagrams/biology-ecology-demos";

export const biologyEcologyTopic: TopicContent = {
  slug: "biology-ecology",
  subject: "Biology",
  subjectSlug: "gcse-science/biology",
  title: "GCSE Biology: Ecology",
  description: "AQA GCSE Biology — Ecology. Covers ecosystems, communities and interdependence, abiotic/biotic factors, levels of organisation and trophic levels/food webs, the carbon cycle and water cycle, biodiversity, and human impacts on ecosystems (deforestation, land use, global warming).",
  glyphs: ["🧬","🔬","🌱","🫀"],
  subtopics: [
    {
      id: "ecosystems-and-communities",
      title: "Ecosystems and communities",
      tier: "Foundation",
      objective: "Identify the components of ecosystems and explain how biotic and abiotic factors interact.",
      whyMatters: "Understanding ecosystems underpins all later ecology questions and is frequently tested in multiple‑choice and label‑diagram items.",
      conceptTitle: "Core concepts of ecosystems",
      conceptBullets: ["An <b style=\"color:#C9A24B\">ecosystem</b> includes all living (biotic) and non‑living (abiotic) components interacting in a defined area.","A <b style=\"color:#C9A24B\">community</b> is the assemblage of populations of different species living together in the same habitat.","<b style=\"color:#C9A24B\">Abiotic factors</b> such as temperature, light and water influence which species can survive in a habitat.","<b style=\"color:#C9A24B\">Biotic interactions</b> (predation, competition, symbiosis) determine population sizes and community structure."],
      conceptNote: "<b>Tip:</b> When drawing a diagram, label at least two abiotic and two biotic factors to earn full marks.",
      glossary: [{"term":"ecosystem","def":"A system comprising all the living organisms and the non‑living environment in a particular area."},{"term":"community","def":"All the populations of different species that occupy the same area at the same time."},{"term":"abiotic factor","def":"Physical or chemical elements of the environment, e.g., temperature, light, water, soil."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyEcologyEcosystemsAndCommunitiesDemo,
      worked: {"question":"In a pond, the water temperature is 15 °C and the light intensity is low. Which of these is most likely the limiting abiotic factor for algae growth?","fastMethod":"Compare temperature and light to the optimum range for freshwater algae.","steps":["Recall optimal algae temperature (~20‑25 °C).","Recall that low light limits photosynthesis.","Since temperature is within tolerable range but light is low, light is limiting."],"answer":"Light intensity is the limiting factor because it directly restricts photosynthesis."},
      selfCheck: {"prompt":"True or false: A community includes both living and non‑living components.","answer":"False – a community only includes living populations; non‑living components belong to the ecosystem."},
      questions: [{"id":"ecosystems-and-communities-q1","prompt":"Define the term 'abiotic factor'.","accept":["non‑living factor","physical or chemical element of environment"],"hint":"Think of temperature, light, water."},{"id":"ecosystems-and-communities-q2","prompt":"Name one example of a biotic interaction.","accept":["predation","competition","mutualism","commensalism","parasitism"],"hint":"Consider how two species affect each other."},{"id":"ecosystems-and-communities-q3","prompt":"If a lake loses 80 % of its dissolved oxygen, which trophic level is most immediately affected?","accept":["primary consumers","herbivores"],"hint":"Think of organisms that rely directly on oxygen from water."}],
      mistakes: ["Confusing 'community' with 'ecosystem' and including abiotic factors in the community definition.","Stating that energy is 'lost' rather than transferred as heat at each trophic level."],
      examTip: "In label‑diagram questions, always write a brief sentence under each label to show understanding; this can gain extra marks.",
      searchTerms: ["ecosystem definition","biotic vs abiotic","community ecology","limiting factor examples","energy flow trophic levels"],
    },
    {
      id: "trophic-levels-food-webs-cycles",
      title: "Trophic levels, food webs & cycles",
      tier: "Standard",
      objective: "Interpret food webs, calculate energy transfer, and describe the carbon and water cycles.",
      whyMatters: "These concepts are core to many A‑level style data‑response questions and require accurate diagram interpretation.",
      conceptTitle: "Food chains, webs and biogeochemical cycles",
      conceptBullets: ["A <b style=\"color:#C9A24B\">trophic level</b> groups organisms that share the same feeding position, e.g., producers, primary consumers.","Energy transfer between trophic levels is typically about <b style=\"color:#C9A24B\">10 %</b> efficient, with 90 % lost as heat.","The <b style=\"color:#C9A24B\">carbon cycle</b> moves carbon through photosynthesis, respiration, decomposition and combustion.","The <b style=\"color:#C9A24B\">water cycle</b> involves evaporation, condensation, precipitation and transpiration, recycling water in ecosystems."],
      conceptNote: "<b>Tip:</b> When asked to calculate energy loss, multiply the energy at the lower level by 0.1 to get the next level’s energy.",
      glossary: [{"term":"trophic level","def":"A position in a food chain occupied by organisms that share the same feeding role."},{"term":"carbon cycle","def":"The series of processes by which carbon is exchanged among the biosphere, atmosphere, oceans and geosphere."},{"term":"water cycle","def":"The continuous movement of water on, above and below the Earth’s surface."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: BiologyEcologyTrophicLevelsFoodWebsCyclesDemo,
      worked: {"question":"A grassland ecosystem has 2000 kJ of energy in its producers. How much energy is available to tertiary consumers?","fastMethod":"Apply the 10 % rule twice (producer → primary → secondary → tertiary).","steps":["10 % of 2000 kJ = 200 kJ (primary consumers).","10 % of 200 kJ = 20 kJ (secondary consumers).","10 % of 20 kJ = 2 kJ (tertiary consumers)."],"answer":"2 kJ of energy is available to tertiary consumers."},
      selfCheck: {"prompt":"True or false: In the carbon cycle, combustion adds carbon to the atmosphere as CO₂.","answer":"True – burning fossil fuels releases stored carbon as CO₂."},
      questions: [{"id":"trophic-levels-food-webs-cycles-q1","prompt":"State the 10 % rule for energy transfer.","accept":["only 10 percent of energy passes to the next trophic level","10% efficiency"],"hint":"Think of the proportion that moves up the food chain."},{"id":"trophic-levels-food-webs-cycles-q2","prompt":"Name one process that moves carbon from the biosphere to the atmosphere.","accept":["respiration","combustion","decomposition"],"hint":"Consider how organisms release CO₂."},{"id":"trophic-levels-food-webs-cycles-q3","prompt":"If 500 mm of rain falls on a catchment and 30 % is lost to evaporation, how much water contributes to runoff?","accept":["350 mm","350mm"],"hint":"Subtract the evaporated amount from the total."}],
      mistakes: ["Using 10 % of the original energy each step instead of successive 10 % reductions.","Confusing the direction of carbon flow in photosynthesis (CO₂ into plants) versus respiration (CO₂ out of plants)."],
      examTip: "When a question provides a food web, first list the trophic levels before calculating energy to avoid missing a step.",
      searchTerms: ["trophic level definition","10 percent energy rule","carbon cycle steps","water cycle diagram","energy transfer calculation"],
    },
    {
      id: "biodiversity-human-impacts-conservation",
      title: "Biodiversity, human impacts & conservation",
      tier: "Extension",
      objective: "Analyse how human activities affect biodiversity and evaluate mitigation strategies.",
      whyMatters: "These topics are high‑weight in the exam’s extended response and data‑analysis sections, testing synthesis and evaluation skills.",
      conceptTitle: "Human influence on ecosystems",
      conceptBullets: ["Deforestation removes <b style=\"color:#C9A24B\">habitat</b>, leading to species loss and reduced ecosystem services.","Intensive <b style=\"color:#C9A24B\">land use</b> (agriculture, urbanisation) fragments habitats and lowers <b style=\"color:#C9A24B\">biodiversity</b>.","Global warming alters temperature and precipitation patterns, shifting species ranges and disrupting <b style=\"color:#C9A24B\">trophic interactions</b>.","Conservation measures such as <b style=\"color:#C9A24B\">reforestation</b>, protected areas and sustainable farming aim to restore ecosystem balance."],
      conceptNote: "<b>Tip:</b> When evaluating impacts, use the ‘cause‑effect‑mitigation’ structure to earn marks for both description and evaluation.",
      glossary: [{"term":"biodiversity","def":"The variety of life at genetic, species and ecosystem levels."},{"term":"deforestation","def":"The clearing or thinning of forested land, often for agriculture or timber."},{"term":"habitat fragmentation","def":"The breaking up of continuous habitat into smaller, isolated patches."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyEcologyBiodiversityHumanImpactsConservationDemo,
      worked: {"question":"A region of forest (100 km²) stores 150 t of carbon per km². If 40 % of the forest is cleared, how much carbon is released?","fastMethod":"Calculate total carbon, then multiply by the proportion cleared.","steps":["Total carbon = 150 t/km² × 100 km² = 15 000 t.","Carbon released = 15 000 t × 0.40 = 6 000 t."],"answer":"6 000 tonnes of carbon are released."},
      selfCheck: {"prompt":"True or false: Reforestation can both increase biodiversity and sequester carbon.","answer":"True – planting native trees restores habitats and captures atmospheric CO₂."},
      questions: [{"id":"biodiversity-human-impacts-conservation-q1","prompt":"Give one reason why habitat fragmentation reduces biodiversity.","accept":["isolates populations","reduces gene flow","increases edge effects"],"hint":"Think about population size and movement."},{"id":"biodiversity-human-impacts-conservation-q2","prompt":"What is one major effect of eutrophication on aquatic ecosystems?","accept":["dead zones","oxygen depletion","loss of fish"],"hint":"Consider what happens when algae die."},{"id":"biodiversity-human-impacts-conservation-q3","prompt":"Calculate the percentage increase in CO₂ emissions if a 5 % rise in deforestation adds 300 Mt of carbon, given current emissions are 3600 Mt.","accept":["8.33%","8.3%"],"hint":"Divide the added carbon by the original total and multiply by 100."}],
      mistakes: ["Confusing carbon stored in biomass with carbon emitted; only the cleared portion is released.","Providing only descriptive impacts without evaluating mitigation effectiveness."],
      examTip: "In data‑response questions, always reference the specific graph or table before drawing conclusions; examiners look for evidence‑based statements.",
      searchTerms: ["deforestation impact","biodiversity loss causes","global warming trophic effects","reforestation benefits","habitat fragmentation examples"],
    }
  ],
};
