import type { TopicContent } from "../types";
import { BiologyCellBiologyCellStructureBasicsDemo, BiologyCellBiologyCellDivisionAndStemCellsDemo, BiologyCellBiologyTransportAndSurfaceAreaDemo } from "../notes-diagrams/biology-cell-biology-demos";

export const biologyCellBiologyTopic: TopicContent = {
  slug: "biology-cell-biology",
  subject: "Biology",
  subjectSlug: "gcse-science/biology",
  title: "GCSE Biology: Cell Biology",
  description: "AQA GCSE Biology — Cell Biology. Covers eukaryotic vs prokaryotic cells, animal/plant cell organelles and their functions, microscopy and magnification calculations, cell division by mitosis and the cell cycle, stem cells (embryonic, adult, meristem) and their uses, diffusion/osmosis/active transport across membranes, and surface area to volume ratio.",
  glyphs: ["🧬","🔬","🌱","🫀"],
  subtopics: [
    {
      id: "cell-structure-basics",
      title: "Cell structure basics",
      tier: "Foundation",
      objective: "Identify the main differences between eukaryotic and prokaryotic cells and name the major animal and plant cell organelles with their functions.",
      whyMatters: "Understanding cell structure underpins all later topics and is a frequent basis for multiple‑choice and label‑the‑diagram questions in the exam.",
      conceptTitle: "Core cell components",
      conceptBullets: ["Eukaryotic cells contain a membrane‑bound <b style=\"color:#C9A24B\">nucleus</b> that houses DNA, whereas prokaryotes lack a nucleus and have DNA free in the cytoplasm.","Plant cells have a rigid <b style=\"color:#C9A24B\">cell wall</b> of cellulose that provides support, a feature absent in animal cells.","The <b style=\"color:#C9A24B\">mitochondrion</b> is the site of aerobic respiration, producing ATP for the cell’s energy needs.","The <b style=\"color:#C9A24B\">chloroplast</b> contains chlorophyll and conducts photosynthesis, a unique organelle of plant cells."],
      conceptNote: "<b>Tip:</b> When revising, draw a labelled cell diagram and colour‑code eukaryotic vs prokaryotic features to reinforce visual memory.",
      glossary: [{"term":"nucleus","def":"Membrane‑bound organelle containing the cell’s genetic material."},{"term":"cell wall","def":"Rigid outer layer of plant cells made of cellulose, providing structural support."},{"term":"mitochondrion","def":"Organelle where aerobic respiration occurs, generating ATP."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyCellBiologyCellStructureBasicsDemo,
      worked: {"question":"A microscope has a total magnification of 400×. If the ocular lens magnifies 10×, what is the power of the objective lens?","fastMethod":"Divide total magnification by ocular magnification.","steps":["Total magnification = ocular × objective","400 = 10 × objective","objective = 400 ÷ 10","objective = 40×"],"answer":"40×"},
      selfCheck: {"prompt":"True or false: Prokaryotic cells contain membrane‑bound mitochondria.","answer":"False – prokaryotes lack membrane‑bound organelles such as mitochondria."},
      questions: [{"id":"cell-structure-basics-q1","prompt":"Name the organelle where photosynthesis occurs.","accept":["chloroplast","chloroplasts"],"hint":"Look for the green pigment."},{"id":"cell-structure-basics-q2","prompt":"What structure gives plant cells their shape?","accept":["cell wall","cellwall"],"hint":"It is made of cellulose."},{"id":"cell-structure-basics-q3","prompt":"Calculate the total magnification if a 5× ocular is used with a 20× objective.","accept":["100×","100x"],"hint":"Multiply ocular and objective powers."}],
      mistakes: ["Confusing the location of DNA in prokaryotes with that in eukaryotes.","Listing chloroplasts as present in animal cells."],
      examTip: "For label‑the‑diagram questions, always start by locating the nucleus first – it anchors the placement of most other organelles.",
      searchTerms: ["eukaryotic vs prokaryotic","cell organelles functions","microscope magnification calculation","plant cell wall","mitochondria role"],
    },
    {
      id: "cell-division-and-stem-cells",
      title: "Cell division and stem cells",
      tier: "Standard",
      objective: "Explain the stages of mitosis, the cell cycle phases, and describe the types and uses of stem cells.",
      whyMatters: "Mitosis and stem cell knowledge are tested in both written and practical questions, especially in relation to growth, repair and biotechnology.",
      conceptTitle: "Mitosis and stem cell types",
      conceptBullets: ["Interphase comprises G1 (cell growth), S (DNA synthesis) and G2 (pre‑division preparation) phases, forming the bulk of the cell cycle.","Mitosis proceeds through <b style=\"color:#C9A24B\">prophase</b>, metaphase, anaphase and telophase, resulting in two genetically identical daughter cells.","Embryonic <b style=\"color:#C9A24B\">stem cells</b> are pluripotent, can become any cell type, and are used in research on tissue regeneration.","Adult <b style=\"color:#C9A24B\">stem cells</b> are multipotent, found in specialised niches (e.g., bone marrow), and aid repair of specific tissues."],
      conceptNote: "<b>Tip:</b> Sketch a simple mitosis diagram and label each stage; then write a one‑sentence purpose for each stage to cement the sequence.",
      glossary: [{"term":"mitosis","def":"Process of nuclear division producing two identical daughter nuclei."},{"term":"stem cell","def":"Undifferentiated cell capable of dividing and giving rise to specialised cells."},{"term":"pluripotent","def":"Ability of a cell to develop into almost any cell type in the body."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: BiologyCellBiologyCellDivisionAndStemCellsDemo,
      worked: {"question":"A cell in G1 has a diploid number of 46 chromosomes. After S phase, how many chromosomes and chromatids are present?","fastMethod":"Remember S phase duplicates DNA but not chromosome number.","steps":["Chromosome number stays at 46.","Each chromosome now has two sister chromatids.","Total chromatids = 46 × 2 = 92."],"answer":"46 chromosomes and 92 chromatids"},
      selfCheck: {"prompt":"True or false: Adult stem cells can differentiate into any cell type in the body.","answer":"False – adult stem cells are multipotent, not pluripotent."},
      questions: [{"id":"cell-division-and-stem-cells-q1","prompt":"List the four stages of mitosis in order.","accept":["prophase, metaphase, anaphase, telophase","prophase metaphase anaphase telophase"],"hint":"Think of the alphabetic sequence P‑M‑A‑T."},{"id":"cell-division-and-stem-cells-q2","prompt":"What is the main function of meristematic stem cells in plants?","accept":["growth","growth of new tissues"],"hint":"They enable primary growth at tips."},{"id":"cell-division-and-stem-cells-q3","prompt":"If a cell spends 6 h in G1, 8 h in S, 4 h in G2 and 1 h in mitosis, what is the total length of one cell cycle?","accept":["19 h","19 hours"],"hint":"Add all phase durations."}],
      mistakes: ["Mixing up the number of chromosomes with the number of chromatids after S phase.","Stating that adult stem cells are pluripotent rather than multipotent."],
      examTip: "When asked to label a mitosis diagram, start at prophase (condensed chromosomes) and work clockwise – the order is always the same.",
      searchTerms: ["mitosis stages","cell cycle phases","embryonic stem cells uses","adult stem cell definition","plant meristem function"],
    },
    {
      id: "transport-and-surface-area",
      title: "Transport and surface area",
      tier: "Extension",
      objective: "Analyse how diffusion, osmosis and active transport operate and evaluate the impact of surface‑area‑to‑volume ratio on cell function.",
      whyMatters: "Transport mechanisms are core to many exam scenarios, and the SA:V ratio explains why cells are small – a key point for higher‑tier questions.",
      conceptTitle: "Membrane transport and SA:V",
      conceptBullets: ["Diffusion is the passive movement of particles from an area of high to low concentration until equilibrium is reached.","Osmosis is the diffusion of water across a semi‑permeable membrane, driven by differences in solute concentration.","Active transport uses ATP to move ions or molecules against their concentration gradient via carrier proteins.","A high <b style=\"color:#C9A24B\">surface‑area‑to‑volume ratio</b> allows faster exchange of materials, limiting cell size."],
      conceptNote: "<b>Tip:</b> Compare two cubes (2 mm vs 4 mm) – calculate SA and volume to see how the ratio changes and why small cells are advantageous.",
      glossary: [{"term":"diffusion","def":"Passive movement of particles down their concentration gradient."},{"term":"osmosis","def":"Passive movement of water through a semi‑permeable membrane toward higher solute concentration."},{"term":"active transport","def":"Energy‑requiring movement of substances against a concentration gradient."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyCellBiologyTransportAndSurfaceAreaDemo,
      worked: {"question":"A cube cell has side length 10 µm. Calculate its surface‑area‑to‑volume ratio (SA:V).","fastMethod":"SA = 6a², V = a³; then divide.","steps":["Surface area = 6 × (10 µm)² = 6 × 100 = 600 µm².","Volume = (10 µm)³ = 1000 µm³.","SA:V = 600 ÷ 1000 = 0.6 µm⁻¹."],"answer":"0.6 µm⁻¹"},
      selfCheck: {"prompt":"True or false: Active transport can occur without any energy input.","answer":"False – it requires ATP."},
      questions: [{"id":"transport-and-surface-area-q1","prompt":"Define osmosis in one sentence.","accept":["movement of water through a semi-permeable membrane from low to high solute concentration","water diffusion across a membrane towards higher solute concentration"],"hint":"Mention the membrane and concentration gradient."},{"id":"transport-and-surface-area-q2","prompt":"What happens to a plant cell placed in a hypertonic solution?","accept":["plasmolysis","cell shrinks"],"hint":"Think of water loss."},{"id":"transport-and-surface-area-q3","prompt":"If a cell’s SA:V ratio is 0.3 µm⁻¹, is it larger or smaller than a cell with a ratio of 0.6 µm⁻¹?","accept":["larger","bigger"],"hint":"Higher ratio = smaller cell."}],
      mistakes: ["Confusing the direction of water movement in hypertonic vs hypotonic solutions.","Using the same formula for surface area of a sphere when the question specifies a cube."],
      examTip: "When a question asks which transport method is used, look for key words: 'requires energy' = active transport; 'through channel protein' = facilitated diffusion.",
      searchTerms: ["diffusion definition","osmosis hypertonic hypotonic","active transport ATP","surface area to volume ratio calculation","cell size limitation"],
    }
  ],
};
