import type { TopicContent } from "../types";
import { BiologyBioenergeticsPhotosynthesisBasicsDemo, BiologyBioenergeticsUsesOfGlucoseRespirationDemo, BiologyBioenergeticsMetabolismAndEnergyFlowDemo } from "../notes-diagrams/biology-bioenergetics-demos";

export const biologyBioenergeticsTopic: TopicContent = {
  slug: "biology-bioenergetics",
  subject: "Biology",
  subjectSlug: "gcse-science/biology",
  title: "GCSE Biology: Bioenergetics",
  description: "AQA GCSE Biology — Bioenergetics. Covers photosynthesis (word/symbol equation, limiting factors — light, CO2, temperature), uses of glucose in plants, aerobic and anaerobic respiration (equations, differences, oxygen debt), and metabolism.",
  glyphs: ["🧬","🔬","🌱","🫀"],
  subtopics: [
    {
      id: "photosynthesis-basics",
      title: "Photosynthesis basics",
      tier: "Foundation",
      objective: "Explain the overall equation for photosynthesis and identify the main factors that limit its rate.",
      whyMatters: "Photosynthesis is the source of all food and oxygen; exam questions often ask for the equation and limiting factors.",
      conceptTitle: "Core concept",
      conceptBullets: ["The overall <b style=\"color:#C9A24B\">photosynthesis</b> reaction is 6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂.","The <b style=\"color:#C9A24B\">light intensity</b> determines the rate of the light‑dependent reactions; low light slows the whole process.","<b style=\"color:#C9A24B\">Carbon dioxide</b> concentration limits the Calvin cycle; if CO₂ falls, glucose production drops.","Temperature affects enzyme activity; rates increase up to about 30 °C then fall sharply as enzymes denature."],
      conceptNote: "<b>Tip:</b> Memorise the word equation first, then convert to the symbol equation – the extra O₂ and H₂O terms are easy to forget.",
      glossary: [{"term":"photosynthesis","def":"Process by which green plants use light energy to convert CO₂ and H₂O into glucose and O₂."},{"term":"light intensity","def":"Amount of light energy falling on a leaf per unit area, measured in lux or µmol m⁻² s⁻¹."},{"term":"carbon dioxide","def":"A gas taken up through stomata that provides carbon for the Calvin cycle."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyBioenergeticsPhotosynthesisBasicsDemo,
      worked: {"question":"A leaf is exposed to 8 000 lux light and a CO₂ concentration of 0.04%. If the light intensity is increased to 12 000 lux while CO₂ stays the same, what happens to the rate of photosynthesis?","fastMethod":"Compare light intensity to the saturation point; if below saturation, rate increases.","steps":["Check the saturation point (~10 000 lux).","Current light (8 000 lux) is below saturation.","Increasing to 12 000 lux moves above saturation.","Rate will increase until other factors become limiting."],"answer":"The rate will increase because the light intensity moves from below to above the saturation point."},
      selfCheck: {"prompt":"True or false: Adding more CO₂ always increases the rate of photosynthesis, even at very high light levels.","answer":"False – once CO₂ is no longer limiting, further increase has no effect."},
      questions: [{"id":"photosynthesis-basics-q1","prompt":"Write the word equation for photosynthesis.","accept":["carbon dioxide + water + light energy → glucose + oxygen","co2 + h2o + light → glucose + o2"],"hint":"Remember the reactants are CO₂, H₂O and light."},{"id":"photosynthesis-basics-q2","prompt":"Name one factor that can limit the rate of photosynthesis.","accept":["light intensity","co2 concentration","temperature"],"hint":"Think about what the plant needs to carry out the reaction."},{"id":"photosynthesis-basics-q3","prompt":"If a plant is kept at 40 °C, what is likely to happen to its photosynthetic rate?","accept":["decrease","drop"],"hint":"Consider enzyme activity at high temperatures."}],
      mistakes: ["Writing the equation as CO₂ + O₂ → C₆H₁₂O₆ + H₂O (reversing reactants and products).","Assuming more light always increases rate, ignoring the saturation point."],
      examTip: "When asked for limiting factors, list them in order: light, CO₂, temperature – this matches the way examiners mark.",
      searchTerms: ["photosynthesis equation","limiting factors photosynthesis","light intensity saturation","co2 effect photosynthesis","optimal temperature photosynthesis"],
    },
    {
      id: "uses-of-glucose-respiration",
      title: "Uses of glucose & respiration",
      tier: "Standard",
      objective: "Describe how plants use glucose and compare aerobic and anaerobic respiration, including equations and oxygen debt.",
      whyMatters: "Understanding energy flow is central to many exam scenarios; respiration equations are frequently tested.",
      conceptTitle: "Core concept",
      conceptBullets: ["Glucose is broken down in <b style=\"color:#C9A24B\">cellular respiration</b> to release energy for growth, transport and maintenance.","In <b style=\"color:#C9A24B\">aerobic respiration</b> glucose + 6O₂ → 6CO₂ + 6H₂O + ≈ 30 ATP, occurring in mitochondria.","<b style=\"color:#C9A24B\">Anaerobic respiration</b> (fermentation) in plants yields glucose → ethanol + CO₂ + 2 ATP, occurring when O₂ is scarce.","The <b style=\"color:#C9A24B\">oxygen debt</b> is the extra O₂ required after anaerobic activity to oxidise accumulated lactic acid back to CO₂ and H₂O."],
      conceptNote: "<b>Tip:</b> Keep the ATP yields (≈30 vs 2) in mind – they are a quick way to spot which pathway the question refers to.",
      glossary: [{"term":"cellular respiration","def":"Series of metabolic reactions that convert glucose and O₂ into CO₂, H₂O and ATP."},{"term":"aerobic respiration","def":"Respiration that uses oxygen; produces about 30 ATP per glucose molecule."},{"term":"oxygen debt","def":"Extra oxygen needed after anaerobic metabolism to restore the cell to its aerobic state."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: BiologyBioenergeticsUsesOfGlucoseRespirationDemo,
      worked: {"question":"A plant cell produces 60 ATP in a minute. Assuming only aerobic respiration is occurring, how many molecules of glucose were broken down?","fastMethod":"Divide total ATP by the ATP yield per glucose (~30).","steps":["Aerobic respiration gives ≈30 ATP per glucose.","60 ATP ÷ 30 ATP per glucose = 2.","Therefore 2 glucose molecules were used."],"answer":"2 molecules of glucose"},
      selfCheck: {"prompt":"True or false: Anaerobic respiration produces more ATP than aerobic respiration.","answer":"False – anaerobic yields only about 2 ATP per glucose."},
      questions: [{"id":"uses-of-glucose-respiration-q1","prompt":"Write the balanced equation for aerobic respiration.","accept":["c6h12o6 + 6o2 → 6co2 + 6h2o + 30atp","glucose + oxygen → carbon dioxide + water + atp"],"hint":"Include 6 O₂ on the reactant side."},{"id":"uses-of-glucose-respiration-q2","prompt":"What is the main product of plant anaerobic respiration?","accept":["ethanol","alcohol"],"hint":"Think of fermentation."},{"id":"uses-of-glucose-respiration-q3","prompt":"If a plant experiences an oxygen debt of 5 mmol O₂ after flooding, how many mmol of CO₂ will be produced when the debt is repaid?","accept":["5","5mmol"],"hint":"One O₂ molecule ultimately yields one CO₂ in the aerobic pathway."}],
      mistakes: ["Confusing the products of anaerobic respiration – forgetting CO₂ is also released with ethanol.","Using the 2 ATP figure for aerobic respiration."],
      examTip: "When a question mentions ‘low oxygen’ or ‘fermentation’, automatically switch to the anaerobic equation and the 2 ATP figure.",
      searchTerms: ["plant respiration equation","aerobic vs anaerobic","oxygen debt definition","glucose uses plant","ATP yield respiration"],
    },
    {
      id: "metabolism-and-energy-flow",
      title: "Metabolism and energy flow",
      tier: "Extension",
      objective: "Analyse how photosynthesis and respiration interlink in plant metabolism and evaluate factors that affect overall energy efficiency.",
      whyMatters: "Higher‑tier questions require synthesis of both processes and quantitative comparison of energy yields.",
      conceptTitle: "Core concept",
      conceptBullets: ["The <b style=\"color:#C9A24B\">metabolic pathway</b> links photosynthesis (energy capture) to respiration (energy release), forming a cycle of carbon and energy.","Energy efficiency is low because photosynthesis stores only ≈ 5 % of incident light as chemical energy, while respiration recovers ≈ 30 ATP per glucose.","Environmental stresses (e.g., drought) can shift the balance toward <b style=\"color:#C9A24B\">anaerobic respiration</b>, reducing overall ATP yield.","The net ATP gain for a plant over a day can be estimated by: (glucose produced × 30 ATP) – (glucose used for growth × 2 ATP if anaerobic)."],
      conceptNote: "<b>Tip:</b> Sketch a simple flow diagram (light → glucose → ATP) to visualise the cycle and spot where losses occur.",
      glossary: [{"term":"metabolism","def":"All the chemical reactions occurring in a living organism to maintain life."},{"term":"energy efficiency","def":"Proportion of absorbed light energy that is stored as usable chemical energy."},{"term":"net ATP gain","def":"Total ATP produced minus ATP used in other processes, useful for evaluating overall energy balance."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyBioenergeticsMetabolismAndEnergyFlowDemo,
      worked: {"question":"A plant produces 10 mmol of glucose in daylight. At night it uses 8 mmol for growth (aerobically) and 1 mmol for fermentation. Calculate the net ATP produced over 24 h.","fastMethod":"Calculate ATP from each pathway and subtract the ATP used in fermentation.","steps":["Aerobic ATP = 8 mmol × 30 ATP = 240 mmol ATP.","Anaerobic ATP = 1 mmol × 2 ATP = 2 mmol ATP (produced, not used).","Total ATP produced = (10 mmol × 30) = 300 mmol.","Net ATP = 300 – (8 mmol×30 – 2) = 300 – 238 = 62 mmol ATP."],"answer":"62 mmol ATP net gain"},
      selfCheck: {"prompt":"True or false: A plant that only performs anaerobic respiration can achieve the same net ATP gain as one that performs aerobic respiration.","answer":"False – anaerobic yields far fewer ATP per glucose."},
      questions: [{"id":"metabolism-and-energy-flow-q1","prompt":"State one reason why the overall energy efficiency of photosynthesis is low.","accept":["heat loss","reflection of light","photoinhibition"],"hint":"Think about what happens to most of the light energy."},{"id":"metabolism-and-energy-flow-q2","prompt":"If stomata close, which part of the photosynthesis equation is directly affected?","accept":["co2","carbon dioxide"],"hint":"Look at the reactants."},{"id":"metabolism-and-energy-flow-q3","prompt":"Calculate the ATP produced if 5 mmol of glucose is respired anaerobically.","accept":["10","10mmol"],"hint":"Use 2 ATP per glucose."}],
      mistakes: ["Adding ATP from anaerobic respiration twice – once as production and again as loss.","Confusing the direction of the net ATP equation, subtracting aerobic ATP instead of adding."],
      examTip: "When asked for a net energy calculation, write a quick table showing glucose amount, pathway, ATP per glucose and total – it keeps numbers organised.",
      searchTerms: ["plant metabolism energy","photosynthesis respiration efficiency","net atp calculation plant","anaerobic stress plants","energy loss photosynthesis"],
    }
  ],
};
