import type { TopicContent } from "../types";
import { BiologyHomeostasisResponseControlSystemsAndNegativeFeedbackDemo, BiologyHomeostasisResponseNervousSystemAndReflexArcsDemo, BiologyHomeostasisResponseEndocrineControlGlucoseRegulationContraceptionDemo } from "../notes-diagrams/biology-homeostasis-response-demos";

export const biologyHomeostasisResponseTopic: TopicContent = {
  slug: "biology-homeostasis-response",
  subject: "Biology",
  subjectSlug: "gcse-science/biology",
  title: "GCSE Biology: Homeostasis and Response",
  description: "AQA GCSE Biology — Homeostasis and Response. Covers homeostasis and control systems (negative feedback), the nervous system and reflex arcs, the endocrine system and hormones, control of blood glucose (insulin, glucagon, diabetes), the menstrual cycle and hormonal/non-hormonal contraception.",
  glyphs: ["🧬","🔬","🌱","🫀"],
  subtopics: [
    {
      id: "control-systems-and-negative-feedback",
      title: "Control systems and negative feedback",
      tier: "Foundation",
      objective: "Explain how negative feedback maintains homeostasis in the body.",
      whyMatters: "Understanding feedback loops is essential for answering many AQA exam questions on regulation and disease.",
      conceptTitle: "Negative feedback control",
      conceptBullets: ["A <b style=\"color:#C9A24B\">receptor</b> detects a change in a physiological variable and sends information to the control centre.","The <b style=\"color:#C9A24B\">control centre</b> compares the input with the set point and activates an effector if needed.","An <b style=\"color:#C9A24B\">effector</b> produces a response that reverses the original change, bringing the variable back towards the set point.","The whole loop is called <b style=\"color:#C9A24B\">negative feedback</b> because the response reduces the initial stimulus."],
      conceptNote: "<b>Tip:</b> Draw a simple three‑box diagram (receptor‑control centre‑effector) and label the direction of the signal for quick recall.",
      glossary: [{"term":"receptor","def":"Structure that senses a change in the internal environment."},{"term":"control centre","def":"Usually the brain; processes information and decides on a response."},{"term":"negative feedback","def":"A regulatory mechanism that counteracts a deviation from the set point."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyHomeostasisResponseControlSystemsAndNegativeFeedbackDemo,
      worked: {"question":"A person’s body temperature rises to 38 °C. Explain the negative feedback response that will return it to normal.","fastMethod":"Identify the receptor, control centre and effector and state the action they take.","steps":["Skin temperature receptors detect the rise.","Hypothalamus (control centre) signals sweat glands (effector).","Sweating evaporates, removing heat and lowering temperature."],"answer":"Sweating increases, heat is lost, and temperature falls back towards 37 °C."},
      selfCheck: {"prompt":"True or false: In negative feedback the response amplifies the original change.","answer":"False – the response works to reduce the original change."},
      questions: [{"id":"control-systems-and-negative-feedback-q1","prompt":"Name the three main parts of a negative feedback loop.","accept":["receptor, control centre, effector","sensor, integrator, response organ"],"hint":"Think of the flow of information from detection to action."},{"id":"control-systems-and-negative-feedback-q2","prompt":"What organ acts as the control centre for body temperature?","accept":["hypothalamus"],"hint":"It lies in the brain and regulates many homeostatic processes."},{"id":"control-systems-and-negative-feedback-q3","prompt":"If blood glucose falls, which hormone is released and what does it do?","accept":["glucagon, raises blood glucose","glucagon raises blood glucose"],"hint":"Consider the liver’s role."}],
      mistakes: ["Confusing the direction of the response – saying effectors increase the stimulus instead of reducing it.","Mixing up the terms receptor and effector in diagrams."],
      examTip: "When a question asks ‘explain the response’, always write the three‑step sequence: receptor → control centre → effector.",
      searchTerms: ["negative feedback loop","homeostasis GCSE","receptor control centre effector","body temperature regulation","AQA biology feedback"],
    },
    {
      id: "nervous-system-and-reflex-arcs",
      title: "Nervous system and reflex arcs",
      tier: "Standard",
      objective: "Describe how a reflex arc enables a rapid response without brain involvement.",
      whyMatters: "Reflexes illustrate the speed of neural control and are frequently tested in AQA practical and theory questions.",
      conceptTitle: "Structure of a reflex arc",
      conceptBullets: ["A <b style=\"color:#C9A24B\">sensory neuron</b> carries the impulse from the receptor to the spinal cord.","An <b style=\"color:#C9A24B\">interneuron</b> in the spinal cord processes the signal and links to a motor neuron.","The <b style=\"color:#C9A24B\">motor neuron</b> transmits the impulse to an effector muscle.","The result is a rapid <b style=\"color:#C9A24B\">reflex action</b> that occurs without conscious brain input."],
      conceptNote: "<b>Tip:</b> Sketch the five‑part diagram (receptor‑sensory‑interneuron‑motor‑effector) and label each part to lock it in memory.",
      glossary: [{"term":"sensory neuron","def":"Carries information from a receptor towards the CNS."},{"term":"interneuron","def":"Connects sensory and motor neurons within the CNS."},{"term":"reflex action","def":"An automatic, rapid response to a stimulus."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: BiologyHomeostasisResponseNervousSystemAndReflexArcsDemo,
      worked: {"question":"A student touches a hot metal rod and pulls away in 0.07 s. Identify the part of the nervous system that allows this rapid response.","fastMethod":"State that the response is a spinal reflex and name the spinal cord as the control centre.","steps":["Hot stimulus activates skin receptors.","Signal travels via sensory neuron to spinal cord.","Interneuron activates motor neuron to flexor muscles.","Muscle contracts, withdrawing the hand."],"answer":"The spinal cord (via a reflex arc) enables the rapid withdrawal."},
      selfCheck: {"prompt":"True or false: All reflexes involve the brain.","answer":"False – most simple reflexes are mediated entirely by the spinal cord."},
      questions: [{"id":"nervous-system-and-reflex-arcs-q1","prompt":"What type of neuron carries the impulse from the receptor to the spinal cord?","accept":["sensory neuron"],"hint":"It brings information into the CNS."},{"id":"nervous-system-and-reflex-arcs-q2","prompt":"Name the effector in the withdrawal reflex.","accept":["flexor muscle","flexor muscles"],"hint":"It pulls the body part away from the stimulus."},{"id":"nervous-system-and-reflex-arcs-q3","prompt":"Why are reflexes faster than voluntary movements?","accept":["no brain processing","they bypass the brain"],"hint":"Consider the pathway length."}],
      mistakes: ["Stating that the brain initiates the reflex instead of the spinal cord.","Confusing interneurons with motor neurons in the diagram."],
      examTip: "When asked to label a reflex diagram, always start at the receptor and work outward – it prevents mis‑ordering labels.",
      searchTerms: ["reflex arc GCSE","nervous system AQA","sensory neuron function","spinal reflex explanation","fastest neural response"],
    },
    {
      id: "endocrine-control-glucose-regulation-contraception",
      title: "Endocrine control, glucose regulation & contraception",
      tier: "Extension",
      objective: "Integrate knowledge of hormonal control of blood glucose and the menstrual cycle to explain contraception methods.",
      whyMatters: "These topics combine endocrine feedback, disease (diabetes) and reproductive health – high‑yield areas for AQA's extended questions.",
      conceptTitle: "Hormonal regulation and contraception",
      conceptBullets: ["<b style=\"color:#C9A24B\">Insulin</b> released by pancreatic β‑cells lowers blood glucose by promoting cellular uptake and glycogen synthesis.","<b style=\"color:#C9A24B\">Glucagon</b> from α‑cells raises blood glucose by stimulating glycogenolysis and gluconeogenesis.","In the <b style=\"color:#C9A24B\">menstrual cycle</b>, estrogen peaks trigger the LH surge, causing ovulation; progesterone maintains the luteal phase.","<b style=\"color:#C9A24B\">Hormonal contraception</b> (e.g., combined pill) supplies synthetic estrogen and progestogen to suppress the LH surge and prevent ovulation."],
      conceptNote: "<b>Tip:</b> Use a two‑column table: one side for glucose hormones, the other for menstrual hormones, then add a third column for contraceptive actions – this visual links the concepts.",
      glossary: [{"term":"LH surge","def":"A rapid increase in luteinising hormone that triggers ovulation."},{"term":"type 1 diabetes","def":"Autoimmune destruction of β‑cells leading to insufficient insulin."},{"term":"combined oral contraceptive","def":"A pill containing synthetic estrogen and progestogen that prevents ovulation."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyHomeostasisResponseEndocrineControlGlucoseRegulationContraceptionDemo,
      worked: {"question":"A patient with type 1 diabetes has a fasting blood glucose of 9 mmol L⁻¹. Explain why insulin therapy will lower this value.","fastMethod":"Link insulin to increased cellular uptake and glycogen storage.","steps":["Insulin binds to receptors on muscle and adipose cells.","Triggers GLUT‑4 translocation to the membrane.","Glucose enters cells and is stored as glycogen, reducing blood level."],"answer":"Insulin increases glucose uptake and glycogen synthesis, bringing fasting glucose back towards normal (<5.5 mmol L⁻¹)."},
      selfCheck: {"prompt":"True or false: The combined pill prevents ovulation by mimicking the LH surge.","answer":"False – it suppresses the LH surge."},
      questions: [{"id":"endocrine-control-glucose-regulation-contraception-q1","prompt":"What hormone is released when blood glucose falls?","accept":["glucagon"],"hint":"It is produced by pancreatic α‑cells."},{"id":"endocrine-control-glucose-regulation-contraception-q2","prompt":"Which phase of the menstrual cycle is characterised by high progesterone?","accept":["luteal phase","luteal"],"hint":"It follows ovulation."},{"id":"endocrine-control-glucose-regulation-contraception-q3","prompt":"Calculate the percentage decrease in blood glucose if a diabetic patient’s level falls from 12 mmol L⁻¹ to 9 mmol L⁻¹ after insulin.","accept":["25","25%"],"hint":"Use ((initial‑final)/initial)×100."}],
      mistakes: ["Confusing the actions of insulin and glucagon, especially regarding glycogen synthesis vs breakdown.","Stating that hormonal contraception works by destroying the ovum rather than preventing ovulation."],
      examTip: "When a question links two systems (e.g., glucose control and contraception), write a brief linking sentence before listing details to show integrated understanding.",
      searchTerms: ["blood glucose regulation GCSE","insulin glucagon diagram","menstrual cycle hormones","combined oral contraceptive mechanism","type 1 diabetes exam question"],
    }
  ],
};
