import type { TopicContent } from "../types";
import { BiologyOrganisationHumanDigestiveSystemDemo, BiologyOrganisationHumanCirculatorySystemDemo, BiologyOrganisationPlantTissuesTranspirationTranslocationDemo } from "../notes-diagrams/biology-organisation-demos";

export const biologyOrganisationTopic: TopicContent = {
  slug: "biology-organisation",
  subject: "Biology",
  subjectSlug: "gcse-science/biology",
  title: "GCSE Biology: Organisation",
  description: "AQA GCSE Biology — Organisation. Covers the human digestive system (organs, enzymes — amylase/protease/lipase, bile), the circulatory system (heart, blood vessels, blood components), coronary heart disease and health, and plant tissues/organs including transpiration and translocation.",
  glyphs: ["🧬","🔬","🌱","🫀"],
  subtopics: [
    {
      id: "human-digestive-system",
      title: "Human digestive system",
      tier: "Foundation",
      objective: "Identify the main digestive organs and explain the role of key enzymes and bile.",
      whyMatters: "Understanding digestion is essential for questions on nutrient breakdown and is frequently tested in multiple‑choice and short‑answer items.",
      conceptTitle: "How food is broken down",
      conceptBullets: ["The <b style=\"color:#C9A24B\">mouth</b> uses mechanical chewing and <b style=\"color:#C9A24B\">salivary amylase</b> to start starch digestion.","In the <b style=\"color:#C9A24B\">stomach</b>, gastric juices contain <b style=\"color:#C9A24B\">protease</b> (pepsin) that begins protein breakdown.","The <b style=\"color:#C9A24B\">small intestine</b> receives pancreatic <b style=\"color:#C9A24B\">lipase</b> and further amylase to digest fats and carbohydrates.","Bile, stored in the <b style=\"color:#C9A24B\">gallbladder</b>, emulsifies fats, increasing surface area for lipase action."],
      conceptNote: "<b>Tip:</b> Link each enzyme to the nutrient type it acts on – this makes recall faster in exams.",
      glossary: [{"term":"amylase","def":"Enzyme that hydrolyses starch into maltose."},{"term":"protease","def":"Enzyme that breaks peptide bonds in proteins."},{"term":"bile","def":"A watery fluid containing bile salts that emulsifies lipids."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyOrganisationHumanDigestiveSystemDemo,
      worked: {"question":"A 70 kg adult eats a meal containing 60 g of starch. If salivary amylase converts 80 % of the starch to maltose before the food reaches the stomach, how many grams of maltose are formed?","fastMethod":"Calculate 0.8 × 60 g.","steps":["Convert percentage to decimal: 80 % = 0.8.","Multiply: 0.8 × 60 g = 48 g.","State the result."],"answer":"48 g of maltose is formed."},
      selfCheck: {"prompt":"True or false: Lipase works best in the highly acidic environment of the stomach.","answer":"False – lipase works best in the slightly alkaline environment of the small intestine."},
      questions: [{"id":"human-digestive-system-q1","prompt":"Name the organ that stores bile.","accept":["gallbladder"],"hint":"It is a small sac attached to the liver."},{"id":"human-digestive-system-q2","prompt":"Which enzyme breaks down proteins in the stomach?","accept":["pepsin","protease"],"hint":"It is activated by low pH."},{"id":"human-digestive-system-q3","prompt":"If 30 g of fat is emulsified by bile, how many grams of fat can be digested if lipase efficiency is 70 %?","accept":["21 g"],"hint":"Multiply 30 g by 0.7."}],
      mistakes: ["Confusing the site of bile production (liver) with its storage (gallbladder).","Assuming all enzymes act throughout the whole GI tract rather than at specific locations."],
      examTip: "When a question lists several digestive processes, map each to its organ and enzyme – a quick table saves time.",
      searchTerms: ["human digestion enzymes","where is bile stored","amylase function","stomach pH","lipase activity"],
    },
    {
      id: "human-circulatory-system",
      title: "Human circulatory system",
      tier: "Standard",
      objective: "Describe the structure of the heart, blood vessels and blood components and their roles in transport.",
      whyMatters: "Circulatory knowledge underpins many A‑level questions and is a core component of the AQA exam, especially for diagram labeling and function explanations.",
      conceptTitle: "Transport of nutrients and gases",
      conceptBullets: ["The <b style=\"color:#C9A24B\">heart</b> has four chambers – two atria and two ventricles – that pump blood in a double circuit.","Arteries carry blood <b style=\"color:#C9A24B\">away from the heart</b> under high pressure; veins return blood <b style=\"color:#C9A24B\">to the heart</b> at lower pressure.","<b style=\"color:#C9A24B\">Capillaries</b> are thin‑walled vessels where exchange of O₂, CO₂, nutrients and waste occurs by diffusion.","Blood consists of <b style=\"color:#C9A24B\">plasma</b>, <b style=\"color:#C9A24B\">red cells</b> (carry O₂), <b style=\"color:#C9A24B\">white cells</b> (defence) and <b style=\"color:#C9A24B\">platelets</b> (clotting)."],
      conceptNote: "<b>Tip:</b> Use the ‘pump‑pipe‑exchange’ mental model: heart pumps, vessels transport, capillaries exchange.",
      glossary: [{"term":"artery","def":"Blood vessel that carries blood away from the heart."},{"term":"capillary","def":"Microscopic vessel where material exchange occurs."},{"term":"plasma","def":"Liquid component of blood containing water, proteins and dissolved nutrients."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: BiologyOrganisationHumanCirculatorySystemDemo,
      worked: {"question":"A student measures a systolic blood pressure of 130 mmHg and a diastolic pressure of 80 mmHg. What is the pulse pressure?","fastMethod":"Subtract diastolic from systolic.","steps":["130 mmHg – 80 mmHg = 50 mmHg.","State the pulse pressure."],"answer":"The pulse pressure is 50 mmHg."},
      selfCheck: {"prompt":"True or false: Veins contain valves to stop backflow of blood.","answer":"True – especially in the limbs where blood must travel against gravity."},
      questions: [{"id":"human-circulatory-system-q1","prompt":"Name the vessel type that carries oxygen‑rich blood from the lungs to the heart.","accept":["pulmonary vein"],"hint":"It returns blood to the left atrium."},{"id":"human-circulatory-system-q2","prompt":"What component of blood is primarily responsible for clotting?","accept":["platelets"],"hint":"They are cell fragments."},{"id":"human-circulatory-system-q3","prompt":"If cardiac output is 5 L/min and stroke volume is 70 mL, calculate heart rate (beats per minute).","accept":["71.4 bpm","71 bpm"],"hint":"Heart rate = cardiac output ÷ stroke volume."}],
      mistakes: ["Mixing up pulmonary and systemic circuits when labeling arteries and veins.","Confusing the function of white blood cells with red blood cells."],
      examTip: "When drawing the heart diagram, label the four chambers first, then add the major vessels – this order matches the marking scheme.",
      searchTerms: ["heart chambers diagram","blood vessel types","pulse pressure calculation","blood components function","artery vs vein pressure"],
    },
    {
      id: "plant-tissues-transpiration-translocation",
      title: "Plant tissues, transpiration & translocation",
      tier: "Extension",
      objective: "Explain how specialised plant tissues enable water movement, gas exchange and nutrient transport, and relate this to disease risk.",
      whyMatters: "These concepts link to AQA's higher‑tier questions on plant adaptations and are often examined through labelled diagrams and scenario analysis.",
      conceptTitle: "Movement of water and nutrients in plants",
      conceptBullets: ["<b style=\"color:#C9A24B\">Xylem</b> transports water and dissolved minerals from roots to leaves using cohesion‑tension and root pressure.","<b style=\"color:#C9A24B\">Phloem</b> distributes sugars from source (leaf) to sink (roots, fruits) by pressure‑flow driven by osmosis.","Transpiration occurs mainly through <b style=\"color:#C9A24B\">stomata</b>; opening increases water loss but also CO₂ uptake for photosynthesis.","Guard cells regulate stomatal aperture by changing turgor pressure, which is controlled by potassium ion fluxes.","Coronary heart disease risk factors (e.g., high cholesterol) are analogous to plant blockages such as embolisms that stop xylem flow."],
      conceptNote: "<b>Tip:</b> Compare xylem and phloem as ‘up‑hill’ vs ‘down‑hill’ transport – this visual cue helps recall mechanisms.",
      glossary: [{"term":"transpiration","def":"Loss of water vapour from plant surfaces, mainly through stomata."},{"term":"phloem","def":"Living tissue that conducts organic nutrients, especially sucrose, from sources to sinks."},{"term":"embolism","def":"Air bubble blockage in xylem that stops water transport."}],
      diagramLabel: "Try it: Key facts",
      Diagram: BiologyOrganisationPlantTissuesTranspirationTranslocationDemo,
      worked: {"question":"A plant loses 5 mL of water per hour through transpiration. Over a 12‑hour daylight period, how much water is lost?","fastMethod":"Multiply rate by time.","steps":["5 mL × 12 h = 60 mL.","State the total loss."],"answer":"The plant loses 60 mL of water."},
      selfCheck: {"prompt":"True or false: Phloem transport requires energy at both source and sink.","answer":"True – active loading at the source and active unloading at the sink both use ATP."},
      questions: [{"id":"plant-tissues-transpiration-translocation-q1","prompt":"What tissue conducts water from roots to leaves?","accept":["xylem"],"hint":"It is non‑living at maturity."},{"id":"plant-tissues-transpiration-translocation-q2","prompt":"Name the leaf opening that controls gas exchange.","accept":["stomata"],"hint":"Each opening is surrounded by two guard cells."},{"id":"plant-tissues-transpiration-translocation-q3","prompt":"If a leaf’s stomata are closed, what happens to transpiration and photosynthesis?","accept":["transpiration decreases, photosynthesis decreases"],"hint":"Both processes depend on open pores."}],
      mistakes: ["Thinking phloem moves only downwards; it can move in any direction depending on source‑sink arrangement.","Assuming embolisms are caused by pathogens rather than physical air bubbles."],
      examTip: "When asked about water movement, start with the cohesion‑tension theory, then mention root pressure and capillary action – this covers all marks.",
      searchTerms: ["xylem vs phloem function","transpiration factors","guard cell mechanism","plant embolism causes","pressure flow hypothesis"],
    }
  ],
};
