import type { TopicContent } from "../types";
import { ChemistryChemistryOfTheAtmosphereCompositionAndEvolutionOfTheAtmosphereDemo, ChemistryChemistryOfTheAtmosphereGreenhouseEffectAndGlobalClimateChangeDemo, ChemistryChemistryOfTheAtmosphereAtmosphericPollutantsFromFuelsDemo } from "../notes-diagrams/chemistry-chemistry-of-the-atmosphere-demos";

export const chemistryChemistryOfTheAtmosphereTopic: TopicContent = {
  slug: "chemistry-chemistry-of-the-atmosphere",
  subject: "Chemistry",
  subjectSlug: "gcse-science/chemistry",
  title: "GCSE Chemistry: Chemistry of the Atmosphere",
  description: "AQA GCSE Chemistry — Chemistry of the Atmosphere. Covers the composition and evolution of the Earth's atmosphere, the greenhouse effect and global climate change, and atmospheric pollutants from fuels.",
  glyphs: ["⚗️","🧪","⚛️","🔥"],
  subtopics: [
    {
      id: "composition-and-evolution-of-the-atmosphere",
      title: "Composition and evolution of the atmosphere",
      tier: "Foundation",
      objective: "identify the main gases in the modern atmosphere and describe how it has changed over geological time",
      whyMatters: "Understanding atmospheric composition underpins questions on gases, climate and pollution; it is frequently tested in multiple‑choice and short‑answer items.",
      conceptTitle: "What the atmosphere is made of",
      conceptBullets: ["The modern atmosphere is ~78% <b style=\"color:#C9A24B\">nitrogen</b> and ~21% <b style=\"color:#C9A24B\">oxygen</b>, with trace amounts of other gases.","The main trace gases are <b style=\"color:#C9A24B\">argon</b>, <b style=\"color:#C9A24B\">carbon dioxide</b> and <b style=\"color:#C9A24B\">water vapour</b>, the latter varying with temperature and location.","Early Earth had a <b style=\"color:#C9A24B\">reducing atmosphere</b> rich in methane, ammonia and hydrogen, produced by volcanic outgassing.","Photosynthetic organisms released <b style=\"color:#C9A24B\">oxygen</b> about 2.4 billion years ago, creating the modern oxidising atmosphere.","Human activity now adds ~0.04% extra <b style=\"color:#C9A24B\">CO₂</b> to the atmosphere, a measurable rise since the Industrial Revolution."],
      conceptNote: "<b>Tip:</b> Memorise the 78‑21‑1% split for N₂, O₂ and other gases; it is a quick recall fact for many questions.",
      glossary: [{"term":"reducing atmosphere","def":"An early atmosphere low in oxygen and rich in gases such as methane and ammonia."},{"term":"oxidising atmosphere","def":"The present atmosphere containing abundant oxygen, allowing combustion and respiration."},{"term":"trace gases","def":"Gases present in the atmosphere at less than 1% concentration, e.g., CO₂, Ar, Ne."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryChemistryOfTheAtmosphereCompositionAndEvolutionOfTheAtmosphereDemo,
      worked: {"question":"If the volume of dry air in a classroom is 120 m³, how many litres of nitrogen does it contain? (Assume 1 m³ = 1000 L)","fastMethod":"Use the 78% proportion directly.","steps":["Convert 120 m³ to litres: 120 × 1000 = 120 000 L.","Calculate 78% of 120 000 L: 0.78 × 120 000 = 93 600 L.","State the answer."],"answer":"93 600 L of nitrogen"},
      selfCheck: {"prompt":"True or false: Argon is a reactive gas that contributes to the greenhouse effect.","answer":"False – argon is inert and does not absorb infrared radiation."},
      questions: [{"id":"composition-and-evolution-of-the-atmosphere-q1","prompt":"Name the two most abundant gases in the modern atmosphere.","accept":["nitrogen, oxygen","oxygen, nitrogen"],"hint":"Think of the 78% and 21% figures."},{"id":"composition-and-evolution-of-the-atmosphere-q2","prompt":"What term describes the atmosphere before oxygen became abundant?","accept":["reducing atmosphere"],"hint":"It is low in O₂ and high in CH₄ and NH₃."},{"id":"composition-and-evolution-of-the-atmosphere-q3","prompt":"Calculate the mass of CO₂ in 1 m³ of air at 25 °C and 1 atm, given CO₂ is 0.04% by volume and its molar mass is 44 g mol⁻¹. (Use 1 mol gas ≈ 24 L).","accept":["0.018 g","0.018g"],"hint":"Find moles of CO₂ then multiply by molar mass."}],
      mistakes: ["Confusing the percentage of argon with that of carbon dioxide.","Using the total volume of moist air for calculations that require dry air."],
      examTip: "When a question asks for the amount of a specific gas, always convert the total volume to litres first; the percentage can then be applied directly.",
      searchTerms: ["atmosphere composition","nitrogen oxygen percentages","reducing atmosphere","great oxidation event","trace gases ppm"],
    },
    {
      id: "greenhouse-effect-and-global-climate-change",
      title: "Greenhouse effect and global climate change",
      tier: "Standard",
      objective: "explain how greenhouse gases trap heat and evaluate the impact of rising CO₂ on global temperature",
      whyMatters: "The greenhouse effect links directly to climate‑change questions; examiners test understanding of energy transfer and data interpretation.",
      conceptTitle: "How the greenhouse effect works",
      conceptBullets: ["Solar radiation reaches Earth as short‑wave <b style=\"color:#C9A24B\">infrared</b> and visible light, which is largely absorbed by the surface.","The warmed surface re‑emits energy as <b style=\"color:#C9A24B\">long‑wave infrared radiation</b>.","Greenhouse gases such as <b style=\"color:#C9A24B\">CO₂</b>, <b style=\"color:#C9A24B\">CH₄</b> and <b style=\"color:#C9A24B\">H₂O vapour</b> absorb some of this infrared, re‑radiating it in all directions.","Re‑radiation back towards the surface reduces net heat loss, raising the average temperature – the <b style=\"color:#C9A24B\">greenhouse effect</b>.","Increasing concentrations of greenhouse gases amplify this effect, leading to <b style=\"color:#C9A24B\">global warming</b> and associated climate changes."],
      conceptNote: "<b>Tip:</b> Sketch a simple diagram of the energy flow; visualising the upward and downward infrared arrows helps answer diagram‑label questions.",
      glossary: [{"term":"greenhouse effect","def":"The warming of Earth's surface caused by atmospheric gases absorbing and re‑emitting infrared radiation."},{"term":"global warming","def":"The long‑term rise in average global temperatures due to increased greenhouse gas concentrations."},{"term":"radiative forcing","def":"The change in energy balance of the Earth caused by factors such as greenhouse gases or aerosols."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: ChemistryChemistryOfTheAtmosphereGreenhouseEffectAndGlobalClimateChangeDemo,
      worked: {"question":"If atmospheric CO₂ doubles, the radiative forcing increases by 3.7 W m⁻². Using the climate sensitivity parameter of 0.8 °C per W m⁻², estimate the expected temperature rise.","fastMethod":"Multiply forcing by sensitivity.","steps":["Multiply 3.7 W m⁻² by 0.8 °C W⁻¹ m² = 2.96 °C.","Round to 3 °C.","State the result."],"answer":"≈ 3 °C temperature increase"},
      selfCheck: {"prompt":"True or false: Water vapour is a greenhouse gas that can be directly controlled by legislation.","answer":"False – water vapour concentration depends on temperature, not direct emissions control."},
      questions: [{"id":"greenhouse-effect-and-global-climate-change-q1","prompt":"List two greenhouse gases besides CO₂.","accept":["methane, nitrous oxide","ch4, n2o","methane, n2o"],"hint":"Think of common gases mentioned in the syllabus."},{"id":"greenhouse-effect-and-global-climate-change-q2","prompt":"What is the main reason that increasing CO₂ leads to higher global temperatures?","accept":["more infrared absorption","increased infrared absorption"],"hint":"Consider the interaction with outgoing radiation."},{"id":"greenhouse-effect-and-global-climate-change-q3","prompt":"Calculate the percentage increase in CO₂ concentration from 280 ppm to 420 ppm.","accept":["50","50%"],"hint":"Use (new‑old)/old × 100."}],
      mistakes: ["Treating water vapour as a directly emitted pollutant rather than a feedback.","Confusing radiative forcing (W m⁻²) with temperature change without applying the sensitivity factor."],
      examTip: "When given a graph of temperature vs. CO₂, identify the slope to obtain the climate sensitivity; avoid using the raw temperature change without the factor.",
      searchTerms: ["greenhouse effect explanation","global warming data","CO2 radiative forcing","climate sensitivity calculation","greenhouse gases list"],
    },
    {
      id: "atmospheric-pollutants-from-fuels",
      title: "Atmospheric pollutants from fuels",
      tier: "Extension",
      objective: "analyse how combustion of fossil fuels produces pollutants, calculate emissions and evaluate mitigation methods",
      whyMatters: "Pollutant calculations and mitigation strategies are high‑weight, data‑interpretation topics in the AQA exam, testing both knowledge and quantitative skills.",
      conceptTitle: "Pollutants produced by fuel combustion",
      conceptBullets: ["Complete combustion of a hydrocarbon yields <b style=\"color:#C9A24B\">CO₂</b> and <b style=\"color:#C9A24B\">H₂O</b>; incomplete combustion forms <b style=\"color:#C9A24B\">CO</b> and <b style=\"color:#C9A24B\">C (soot)</b>.","Sulphur present in coal forms <b style=\"color:#C9A24B\">SO₂</b> on burning, a major cause of acid rain.","Nitrogen oxides (<b style=\"color:#C9A24B\">NOₓ</b>) arise from high‑temperature oxidation of atmospheric N₂ during combustion.","Particulate matter (PM₁₀, PM₂.₅) includes unburnt carbon particles and sulphates, posing respiratory health risks.","Catalytic converters reduce CO, HC and NOₓ emissions by promoting oxidation/reduction reactions at lower temperatures."],
      conceptNote: "<b>Tip:</b> Memorise the stoichiometric equation for methane combustion; it is the basis for many emission‑mass calculations.",
      glossary: [{"term":"incomplete combustion","def":"Combustion that does not consume all fuel, producing carbon monoxide and soot."},{"term":"NOₓ","def":"Collective term for nitrogen oxides (NO and NO₂) formed at high temperatures."},{"term":"particulate matter","def":"Tiny solid or liquid particles suspended in air, classified by aerodynamic diameter (PM₁₀, PM₂.₅)."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryChemistryOfTheAtmosphereAtmosphericPollutantsFromFuelsDemo,
      worked: {"question":"A car burns 6 L of petrol per 100 km. How much CO₂ is emitted when it travels 150 km? (Use 2.3 kg CO₂ per litre of petrol.)","fastMethod":"Find total litres used, then multiply by CO₂ per litre.","steps":["Litres used = (6 L/100 km) × 150 km = 9 L.","CO₂ emitted = 9 L × 2.3 kg L⁻¹ = 20.7 kg.","State the answer."],"answer":"20.7 kg of CO₂"},
      selfCheck: {"prompt":"True or false: Catalytic converters increase NOₓ emissions.","answer":"False – they are designed to reduce NOₓ (as well as CO and hydrocarbons)."},
      questions: [{"id":"atmospheric-pollutants-from-fuels-q1","prompt":"Write the balanced equation for complete combustion of methane.","accept":["ch4 + 2o2 -> co2 + 2h2o","ch4+2o2→co2+2h2o"],"hint":"Count atoms of C, H and O on both sides."},{"id":"atmospheric-pollutants-from-fuels-q2","prompt":"What pollutant is primarily responsible for acid rain from coal power stations?","accept":["so2","sulphur dioxide"],"hint":"Look for the sulphur content of coal."},{"id":"atmospheric-pollutants-from-fuels-q3","prompt":"If 500 kg of coal containing 2% sulphur is burnt, calculate the mass of SO₂ produced (atomic masses: S=32, O=16).","accept":["31.2 kg","31.2kg"],"hint":"First find mass of S, then convert to SO₂ using molar masses."}],
      mistakes: ["Using the mass of coal directly for SO₂ without accounting for the 2% sulphur fraction.","Confusing the CO₂ per litre of petrol with per kilogram; the exam uses the litre figure."],
      examTip: "When a question gives fuel mass and a percentage impurity, always calculate the impurity mass first before converting to the pollutant using stoichiometry.",
      searchTerms: ["fuel combustion pollutants","CO2 emissions petrol","SO2 from coal","NOx formation temperature","catalytic converter function"],
    }
  ],
};
