import type { TopicContent } from "../types";
import { ChemistryUsingResourcesEarthSResourcesAndSustainableUseDemo, ChemistryUsingResourcesPotableWaterProductionAndWasteWaterTreatmentDemo, ChemistryUsingResourcesLifeCycleAssessmentAndRecyclingDemo } from "../notes-diagrams/chemistry-using-resources-demos";

export const chemistryUsingResourcesTopic: TopicContent = {
  slug: "chemistry-using-resources",
  subject: "Chemistry",
  subjectSlug: "gcse-science/chemistry",
  title: "GCSE Chemistry: Using Resources",
  description: "AQA GCSE Chemistry — Using Resources. Covers using the Earth's resources, potable water production, waste water treatment, life cycle assessments, and recycling.",
  glyphs: ["⚗️","🧪","⚛️","🔥"],
  subtopics: [
    {
      id: "earth-s-resources-and-sustainable-use",
      title: "Earth's resources and sustainable use",
      tier: "Foundation",
      objective: "identify main Earth resources used in chemistry and explain why sustainable use is important",
      whyMatters: "Understanding resource limits underpins many exam questions on environmental impact and is a recurring AQA topic.",
      conceptTitle: "Key resources and sustainability",
      conceptBullets: ["The most common <b style=\"color:#C9A24B\">non‑renewable</b> resources are fossil fuels and minerals, which cannot be replenished on human timescales.","<b style=\"color:#C9A24B\">Renewable</b> resources such as water and biomass can be replenished, but over‑use can still cause depletion.","Sustainable practice means using resources at a rate that does not exceed the Earth's capacity to regenerate them, often expressed as a <b style=\"color:#C9A24B\">carbon footprint</b>.","AQA expects students to link resource use to the three pillars of sustainability: environmental, economic and social impacts."],
      conceptNote: "<b>Tip:</b> When revising, colour‑code each resource as renewable or non‑renewable to visualise the balance.",
      glossary: [{"term":"non‑renewable","def":"Resources that exist in finite amounts and are not replenished within a human lifetime."},{"term":"renewable","def":"Resources that can be naturally replenished on a timescale relevant to human use."},{"term":"carbon footprint","def":"Total greenhouse gas emissions caused directly or indirectly by an activity or product."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryUsingResourcesEarthSResourcesAndSustainableUseDemo,
      worked: {"question":"If the UK uses 1.5 × 10⁹ L of water per day and 30% is recycled, how much fresh water is required each day?","fastMethod":"Calculate 70% of total usage.","steps":["Convert percentage to decimal: 0.70.","Multiply total volume by 0.70.","Result = 1.5 × 10⁹ L × 0.70."],"answer":"1.05 × 10⁹ L of fresh water per day."},
      selfCheck: {"prompt":"True or false: All minerals are non‑renewable resources.","answer":"False – some minerals can be recycled, reducing the need for new extraction."},
      questions: [{"id":"earth-s-resources-and-sustainable-use-q1","prompt":"Name one non‑renewable resource used in the chemical industry.","accept":["oil","coal","natural gas","uranium"],"hint":"Think of fuels that cannot be replenished quickly."},{"id":"earth-s-resources-and-sustainable-use-q2","prompt":"What term describes the total greenhouse gases from a product’s life?","accept":["carbon footprint"],"hint":"Two words, starts with ‘c’."},{"id":"earth-s-resources-and-sustainable-use-q3","prompt":"If 40 % of a metal is recovered by recycling, what fraction is lost?","accept":["3/5","0.6"],"hint":"Subtract the recovered proportion from 1."}],
      mistakes: ["Confusing renewable with inexhaustible – renewable resources can still be over‑used.","Leaving percentages as whole numbers in calculations (e.g., using 30 instead of 0.30)."],
      examTip: "When a question asks for ‘sustainable’, always mention the three pillars: environmental, economic and social.",
      searchTerms: ["non renewable resources","renewable resources chemistry","sustainability GCSE","carbon footprint definition","resource limits exam"],
    },
    {
      id: "potable-water-production-and-waste-water-treatment",
      title: "Potable water production and waste‑water treatment",
      tier: "Standard",
      objective: "explain the main stages of turning raw water into drinking water and how waste water is treated",
      whyMatters: "AQA frequently tests the chemistry of water treatment, including filtration, chlorination and the removal of contaminants.",
      conceptTitle: "Treatment processes",
      conceptBullets: ["Raw water first undergoes <b style=\"color:#C9A24B\">coagulation and flocculation</b> where chemicals form larger particles that settle out.","After sedimentation, water passes through <b style=\"color:#C9A24B\">sand filtration</b> to remove remaining suspended matter.","Disinfection is achieved by adding <b style=\"color:#C9A24B\">chlorine</b> or using UV light to kill pathogens.","Waste‑water treatment mirrors the steps in reverse: primary sedimentation, biological treatment (activated sludge) and final disinfection."],
      conceptNote: "<b>Tip:</b> Sketch a simple flow diagram and label each stage – visual memory aids exam recall.",
      glossary: [{"term":"coagulation","def":"Addition of chemicals to neutralise charges and allow particles to clump together."},{"term":"flocculation","def":"Gentle mixing that encourages the formation of larger flocs from coagulated particles."},{"term":"activated sludge","def":"A biological treatment where microorganisms break down organic waste in aerated tanks."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: ChemistryUsingResourcesPotableWaterProductionAndWasteWaterTreatmentDemo,
      worked: {"question":"A water plant adds 1.2 mg L⁻¹ of chlorine to 250 000 L of water. How many grams of chlorine are required?","fastMethod":"Convert mg L⁻¹ to total mg then to grams.","steps":["Multiply concentration by volume: 1.2 mg L⁻¹ × 250 000 L = 300 000 mg.","Convert mg to g: 300 000 mg ÷ 1000 = 300 g."],"answer":"300 g of chlorine."},
      selfCheck: {"prompt":"True or false: UV light adds chemicals to the water.","answer":"False – UV disinfects by damaging microbial DNA, no chemicals are added."},
      questions: [{"id":"potable-water-production-and-waste-water-treatment-q1","prompt":"What is the purpose of flocculation in water treatment?","accept":["to form larger particles","increase particle size for settling"],"hint":"Think of making particles easier to remove."},{"id":"potable-water-production-and-waste-water-treatment-q2","prompt":"Name one biological process used in waste‑water treatment.","accept":["activated sludge","aerobic digestion"],"hint":"It involves microbes breaking down organic matter."},{"id":"potable-water-production-and-waste-water-treatment-q3","prompt":"If the BOD of a sample is 200 mg L⁻¹, how many mg of O₂ are needed for 500 L?","accept":["100000 mg","100 g"],"hint":"Multiply concentration by volume."}],
      mistakes: ["Mixing up the order of treatment steps – coagulation comes before filtration.","Using mg L⁻¹ directly as grams without converting."],
      examTip: "When asked for a treatment stage, write the name and one key purpose (e.g., ‘coagulation – forms flocs for sedimentation’).",
      searchTerms: ["water treatment stages","potable water chlorine dosage","waste water activated sludge","coagulation flocculation GCSE","BOD calculation"],
    },
    {
      id: "life-cycle-assessment-and-recycling",
      title: "Life‑cycle assessment and recycling",
      tier: "Extension",
      objective: "analyse a product’s life‑cycle, calculate material savings from recycling and evaluate environmental impact",
      whyMatters: "AQA includes LCA questions that require quantitative comparison of raw‑material extraction versus recycling – a high‑scoring skill.",
      conceptTitle: "Assessing impact and material loops",
      conceptBullets: ["A <b style=\"color:#C9A24B\">life‑cycle assessment (LCA)</b> examines raw material extraction, manufacture, use, disposal and recycling for a product.","Recycling saves <b style=\"color:#C9A24B\">embodied energy</b> because fewer processes such as mining and refining are required.","The <b style=\"color:#C9A24B\">recycling rate</b> is the proportion of a material recovered after use; higher rates reduce landfill and resource demand.","Environmental impact is often expressed as CO₂‑equivalent emissions per kilogram of product, allowing comparison across materials."],
      conceptNote: "<b>Tip:</b> Create a table with stages (extraction, manufacture, etc.) and fill in energy or CO₂ values – it speeds up LCA calculations.",
      glossary: [{"term":"life‑cycle assessment","def":"A systematic analysis of the environmental impacts of a product from cradle to grave."},{"term":"embodied energy","def":"Total energy used to produce a material, including extraction, processing and transport."},{"term":"recycling rate","def":"The percentage of a material that is recovered and re‑processed after its first use."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryUsingResourcesLifeCycleAssessmentAndRecyclingDemo,
      worked: {"question":"A product uses 2 kg of aluminium. Manufacturing virgin aluminium emits 70 MJ kg⁻¹, while recycling emits 10 MJ kg⁻¹. How much energy is saved by recycling the aluminium?","fastMethod":"Find the difference in energy per kg and multiply by mass.","steps":["Energy difference = 70 MJ kg⁻¹ – 10 MJ kg⁻¹ = 60 MJ kg⁻¹.","Multiply by 2 kg: 60 MJ kg⁻¹ × 2 kg = 120 MJ saved."],"answer":"120 MJ of energy is saved."},
      selfCheck: {"prompt":"True or false: Recycling always reduces CO₂ emissions compared with virgin production.","answer":"False – for some materials (e.g., certain plastics) recycling can be energy‑intensive and may not lower emissions."},
      questions: [{"id":"life-cycle-assessment-and-recycling-q1","prompt":"Define ‘embodied energy’ in one sentence.","accept":["total energy used to produce a material","energy required for extraction, processing and transport"],"hint":"Think of all steps before the product reaches you."},{"id":"life-cycle-assessment-and-recycling-q2","prompt":"If the recycling rate of steel is 30 % and a city uses 500 t per year, how many tonnes are recycled?","accept":["150 t","150 tonnes"],"hint":"Multiply total use by the recycling percentage."},{"id":"life-cycle-assessment-and-recycling-q3","prompt":"Which material typically has the highest energy saving when recycled: aluminium, steel, or glass?","accept":["aluminium"],"hint":"Recall the percentage energy saved."}],
      mistakes: ["Adding energy values for each stage instead of using the provided total per kg.","Confusing recycling rate with the proportion of material that is *re‑used* in the same product."],
      examTip: "When an LCA question gives several stage values, add them once to get total embodied energy, then compare raw vs recycled using the same units.",
      searchTerms: ["life cycle assessment GCSE","embodied energy calculation","recycling energy savings","aluminium recycling energy","circular economy exam"],
    }
  ],
};
