import type { TopicContent } from "../types";
import { ChemistryBondingStructurePropertiesIonicBondingAndGiantIonicLatticesDemo, ChemistryBondingStructurePropertiesCovalentBondingAndGiantCovalentStructuresDemo, ChemistryBondingStructurePropertiesMetallicBondingAlloysAndStatesOfMatterDemo } from "../notes-diagrams/chemistry-bonding-structure-properties-demos";

export const chemistryBondingStructurePropertiesTopic: TopicContent = {
  slug: "chemistry-bonding-structure-properties",
  subject: "Chemistry",
  subjectSlug: "gcse-science/chemistry",
  title: "GCSE Chemistry: Bonding, Structure and the Properties of Matter",
  description: "AQA GCSE Chemistry — Bonding, Structure and the Properties of Matter. Covers ionic bonding and giant ionic lattices, covalent bonding (simple molecules and giant covalent structures - diamond, graphite, silicon dioxide, graphene, fullerenes), metallic bonding and alloys, states of matter and changes of state, and nanoparticles.",
  glyphs: ["⚗️","🧪","⚛️","🔥"],
  subtopics: [
    {
      id: "ionic-bonding-and-giant-ionic-lattices",
      title: "Ionic bonding and giant ionic lattices",
      tier: "Foundation",
      objective: "Student will be able to describe how ions form a giant lattice and predict basic properties of ionic compounds",
      whyMatters: "Understanding ionic structures explains why salts have high melting points and conduct electricity when molten, which is tested in multiple choice and short answer questions",
      conceptTitle: "Core ideas of ionic bonding",
      conceptBullets: ["Ions are formed when atoms gain or lose electrons to achieve a full outer shell and become <b style=color:#C9A24B>cations</b> or <b style=color:#C9A24B>anions</b>","Opposite charges attract and arrange in a repeating three‑dimensional pattern called a <b style=color:#C9A24B>giant ionic lattice</b>","Strong electrostatic forces between ions give ionic solids high <b style=color:#C9A24B>melting points</b> and hardness","Ionic compounds conduct electricity only when ions are free to move, so they conduct in the molten state or in aqueous solution"],
      conceptNote: "<b>Tip:</b> Remember that lattice energy increases with charge magnitude and decreases with ionic radius; this helps predict melting points",
      glossary: [{"term":"cation","def":"positively charged ion formed by loss of electrons"},{"term":"anion","def":"negatively charged ion formed by gain of electrons"},{"term":"lattice energy","def":"energy released when gaseous ions combine to form a solid lattice"}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryBondingStructurePropertiesIonicBondingAndGiantIonicLatticesDemo,
      worked: {"question":"Calculate the lattice energy of NaCl using the Born Lande equation approximated as 2.3x10^9 J mol-1 for a 1:1 ionic solid","fastMethod":"Use the given value directly for a 1:1 lattice","steps":["Identify charge magnitude: +1 and -1","Recognise that the question provides the lattice energy for a 1:1 solid","State the lattice energy as 2.3x10^9 J per mole"],"answer":"2.3x10^9 J mol-1"},
      selfCheck: {"prompt":"True or false: NaCl conducts electricity as a solid crystal","answer":"false because ions are fixed in the lattice and cannot move"},
      questions: [{"id":"ionic-bonding-and-giant-ionic-lattices-q1","prompt":"What type of bond holds the ions together in NaCl?","accept":["ionic bond","ionic"],"hint":"Consider the attraction between opposite charges"},{"id":"ionic-bonding-and-giant-ionic-lattices-q2","prompt":"Name one property that results from the strong forces in a giant ionic lattice","accept":["high melting point","hardness"],"hint":"Think about what happens when you heat an ionic solid"},{"id":"ionic-bonding-and-giant-ionic-lattices-q3","prompt":"Why does NaCl dissolve readily in water?","accept":["water molecules hydrate ions","hydration of ions"],"hint":"Water is polar and can surround ions"}],
      mistakes: ["Confusing lattice energy with enthalpy of solution","Assuming all ionic compounds conduct electricity in the solid state"],
      examTip: "When a question asks for a property of an ionic solid, recall the three key features: high melting point, brittleness, and conductivity only when molten or aqueous",
      searchTerms: ["ionic bonding","giant ionic lattice","lattice energy","ionic compound properties","conductivity ionic solid"],
    },
    {
      id: "covalent-bonding-and-giant-covalent-structures",
      title: "Covalent bonding and giant covalent structures",
      tier: "Standard",
      objective: "Student will be able to differentiate simple covalent molecules from giant covalent networks and predict their physical properties",
      whyMatters: "Examiners test the ability to link bonding type to properties such as hardness, melting point and conductivity, especially for carbon allotropes and silicon dioxide",
      conceptTitle: "Covalent structures explained",
      conceptBullets: ["Simple covalent molecules consist of a limited number of atoms held together by <b style=color:#C9A24B>shared electron pairs</b>","Giant covalent structures have each atom covalently bonded to many neighbours, forming a continuous network such as <b style=color:#C9A24B>diamond</b> or <b style=color:#C9A24B>silicon dioxide</b>","In graphite each carbon atom is bonded to three others in layers; weak forces between layers give it softness and lubricating properties","Graphene is a single layer of graphite and fullerenes are closed cages of carbon atoms, both showing exceptional strength and conductivity"],
      conceptNote: "<b>Tip:</b> Link the number of bonds per atom to hardness – more bonds per atom usually means a harder material",
      glossary: [{"term":"covalent bond","def":"bond formed by sharing of electron pairs between atoms"},{"term":"network solid","def":"a giant covalent structure where atoms are linked in a continuous three‑dimensional lattice"},{"term":"allotrope","def":"different structural forms of the same element"}],
      diagramLabel: "Try it: Quick reference",
      Diagram: ChemistryBondingStructurePropertiesCovalentBondingAndGiantCovalentStructuresDemo,
      worked: {"question":"Calculate the energy required to break all the covalent bonds in a 1 mol sample of methane (CH4) if each C–H bond energy is 413 kJ mol-1","fastMethod":"Multiply bond energy by number of bonds and by Avogadro's number (implicitly 1 mol)","steps":["Identify number of C–H bonds in CH4: 4","Multiply 4 bonds by 413 kJ mol-1","Result is 1652 kJ for 1 mol of CH4"],"answer":"1652 kJ mol-1"},
      selfCheck: {"prompt":"True or false: Graphite is a good electrical conductor because of its metallic bonding","answer":"false because conductivity arises from delocalised electrons in covalent layers"},
      questions: [{"id":"covalent-bonding-and-giant-covalent-structures-q1","prompt":"Which allotrope of carbon is the hardest natural material?","accept":["diamond"],"hint":"Consider the number of bonds each carbon atom has"},{"id":"covalent-bonding-and-giant-covalent-structures-q2","prompt":"Name the type of bonding present in silicon dioxide","accept":["covalent network","giant covalent"],"hint":"Look at how each Si atom is linked to oxygen atoms"},{"id":"covalent-bonding-and-giant-covalent-structures-q3","prompt":"Why does graphite feel slippery?","accept":["weak interlayer forces","van der waals forces between layers"],"hint":"Think about the forces holding the layers together"}],
      mistakes: ["Mixing up the properties of diamond and graphite","Treating fullerenes as simple molecules rather than giant covalent structures"],
      examTip: "When a question mentions hardness or high melting point, check if the structure is a giant covalent network rather than a simple molecule",
      searchTerms: ["covalent bonding","giant covalent structures","diamond graphite properties","silicon dioxide lattice","fullerenes GCSE"],
    },
    {
      id: "metallic-bonding-alloys-and-states-of-matter",
      title: "Metallic bonding, alloys and states of matter",
      tier: "Extension",
      objective: "Student will be able to analyse metallic structures, explain alloy behaviour and relate changes of state to intermolecular forces",
      whyMatters: "Higher tier questions require linking bonding to macroscopic properties and to calculate energy changes during phase transitions, a common exam requirement",
      conceptTitle: "Metallic and state concepts",
      conceptBullets: ["Metal atoms release some electrons to form a sea of delocalised <b style=color:#C9A24B>electron cloud</b> that holds the positively charged nuclei together","The strength of metallic bonding depends on the number of delocalised electrons and the size of the metal ions, influencing <b style=color:#C9A24B>melting point</b> and conductivity","Alloys are mixtures of two or more metals (or a metal and a non‑metal) that form a solid solution, often giving a higher <b style=color:#C9A24B>strength</b> or lower melting point than the pure metal","Changes of state involve breaking or forming <b style=color:#C9A24B>intermolecular forces</b>; the energy required is expressed as enthalpy of fusion or vapourisation"],
      conceptNote: "<b>Tip:</b> Compare the number of delocalised electrons per atom when predicting which metal has the highest melting point",
      glossary: [{"term":"metallic bond","def":"attraction between positive metal ions and a sea of delocalised electrons"},{"term":"alloy","def":"solid mixture of two or more elements, at least one of which is a metal"},{"term":"enthalpy of vapourisation","def":"energy required to convert one mole of liquid to gas at its boiling point"}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryBondingStructurePropertiesMetallicBondingAlloysAndStatesOfMatterDemo,
      worked: {"question":"A metal has a molar enthalpy of fusion of 13 kJ mol-1. How much energy is required to melt 0.250 mol of the metal?","fastMethod":"Multiply moles by enthalpy of fusion","steps":["Identify enthalpy of fusion: 13 kJ per mol","Multiply 0.250 mol by 13 kJ mol-1","Energy required = 3.25 kJ"],"answer":"3.25 kJ"},
      selfCheck: {"prompt":"True or false: Adding a small amount of carbon to iron always lowers its melting point","answer":"false because carbon forms steel which can have a higher melting point depending on composition"},
      questions: [{"id":"metallic-bonding-alloys-and-states-of-matter-q1","prompt":"What property of metals is explained by the electron sea model?","accept":["conductivity","electrical conductivity","thermal conductivity"],"hint":"Think about movement of electrons"},{"id":"metallic-bonding-alloys-and-states-of-matter-q2","prompt":"Name one reason why an alloy might have a higher strength than its constituent metals","accept":["grain boundary strengthening","solid solution strengthening"],"hint":"Consider disruption of regular lattice"},{"id":"metallic-bonding-alloys-and-states-of-matter-q3","prompt":"State the term for the energy change when a liquid becomes a gas","accept":["enthalpy of vapourisation","heat of vapourisation"],"hint":"It is larger than the enthalpy of fusion"}],
      mistakes: ["Confusing enthalpy of fusion with enthalpy of vapourisation values","Assuming all alloys have higher melting points than the pure metals"],
      examTip: "When a question gives mass and enthalpy data, always convert mass to moles first; this avoids unit errors in energy calculations",
      searchTerms: ["metallic bonding GCSE","alloy properties","enthalpy of fusion calculation","state changes energy","electron sea model exam"],
    }
  ],
};
