import type { TopicContent } from "../types";
import { ChemistryEnergyChangesExothermicAndEndothermicReactionsDemo, ChemistryEnergyChangesReactionProfilesAndActivationEnergyDemo, ChemistryEnergyChangesSimpleCellsAndBatteriesDemo } from "../notes-diagrams/chemistry-energy-changes-demos";

export const chemistryEnergyChangesTopic: TopicContent = {
  slug: "chemistry-energy-changes",
  subject: "Chemistry",
  subjectSlug: "gcse-science/chemistry",
  title: "GCSE Chemistry: Energy Changes",
  description: "AQA GCSE Chemistry — Energy Changes. Covers exothermic and endothermic reactions, reaction profiles/activation energy, and simple cells and batteries.",
  glyphs: ["⚗️","🧪","⚛️","🔥"],
  subtopics: [
    {
      id: "exothermic-and-endothermic-reactions",
      title: "Exothermic and Endothermic Reactions",
      tier: "Foundation",
      objective: "Identify whether a reaction is exothermic or endothermic and explain the energy change.",
      whyMatters: "Understanding energy flow is essential for predicting temperature changes in experiments and appears in many AQA exam questions.",
      conceptTitle: "Energy change in reactions",
      conceptBullets: ["An <b style=\"color:#C9A24B\">exothermic</b> reaction releases energy to the surroundings, causing the temperature to rise.","An <b style=\"color:#C9A24B\">endothermic</b> reaction absorbs energy, so the surroundings become cooler.","The sign of <b style=\"color:#C9A24B\">ΔH</b> indicates the direction of energy flow: negative for exothermic, positive for endothermic.","Energy changes are measured per mole of reaction and are listed in kJ mol⁻¹ on the specification.","In the lab, a thermometer or calorimeter can be used to observe the temperature change."],
      conceptNote: "<b>Tip:</b> Remember that a rise in temperature means the reaction gave off heat – it is exothermic.",
      glossary: [{"term":"exothermic","def":"A reaction that releases heat to the surroundings."},{"term":"endothermic","def":"A reaction that absorbs heat from the surroundings."},{"term":"ΔH","def":"Enthalpy change; negative for exothermic, positive for endothermic."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryEnergyChangesExothermicAndEndothermicReactionsDemo,
      worked: {"question":"When 2.0 g of a metal reacts with excess acid, the temperature of the solution rises from 20 °C to 27 °C. The solution mass is 100 g and its specific heat capacity is 4.18 J g⁻¹ K⁻¹. Calculate the heat released (kJ) to the solution.","fastMethod":"Use q = mcΔT and convert to kJ.","steps":["ΔT = 27 °C – 20 °C = 7 K.","q = 100 g × 4.18 J g⁻¹ K⁻¹ × 7 K = 2926 J.","Convert to kJ: 2926 J ÷ 1000 = 2.93 kJ.","The reaction released 2.9 kJ (exothermic)."],"answer":"2.9 kJ released"},
      selfCheck: {"prompt":"True or false: A reaction that cools the surroundings is exothermic.","answer":"False – it is endothermic because heat is absorbed from the surroundings."},
      questions: [{"id":"exothermic-and-endothermic-reactions-q1","prompt":"Define an exothermic reaction.","accept":["releases heat","gives off energy"],"hint":"Think about what happens to the surroundings."},{"id":"exothermic-and-endothermic-reactions-q2","prompt":"What sign does ΔH have for an endothermic process?","accept":["positive","+"],"hint":"Recall the convention for enthalpy."},{"id":"exothermic-and-endothermic-reactions-q3","prompt":"If a reaction has ΔH = –150 kJ mol⁻¹, is it exothermic or endothermic?","accept":["exothermic","exo"],"hint":"Look at the sign."}],
      mistakes: ["Confusing a temperature rise with an endothermic reaction.","Leaving ΔH in joules instead of converting to kJ for exam answers."],
      examTip: "Always state the sign of ΔH in your answer; examiners award marks for correct sign as well as magnitude.",
      searchTerms: ["exothermic definition","endothermic sign","ΔH meaning","temperature change reaction","calorimetry GCSE"],
    },
    {
      id: "reaction-profiles-and-activation-energy",
      title: "Reaction Profiles and Activation Energy",
      tier: "Standard",
      objective: "Interpret reaction profile diagrams and calculate activation energy.",
      whyMatters: "Reaction profiles are used in AQA questions to test understanding of energy barriers and rate concepts, a common exam topic.",
      conceptTitle: "Energy diagram basics",
      conceptBullets: ["The vertical axis shows <b style=\"color:#C9A24B\">potential energy</b> of the system.","The peak of the curve represents the <b style=\"color:#C9A24B\">activation energy (Ea)</b> required to start the reaction.","The difference between reactants and products on the energy axis is the <b style=\"color:#C9A24B\">ΔH</b> of the reaction.","A higher Ea means the reaction proceeds more slowly at a given temperature.","Exothermic reactions have products lower than reactants; endothermic have products higher."],
      conceptNote: "<b>Tip:</b> When reading a diagram, the height from reactants to the peak is Ea, not the total height of the curve.",
      glossary: [{"term":"activation energy","def":"Minimum energy required for reactants to form the transition state."},{"term":"transition state","def":"High‑energy, unstable arrangement of atoms at the peak of the profile."},{"term":"reaction coordinate","def":"Horizontal axis representing progress of the reaction."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: ChemistryEnergyChangesReactionProfilesAndActivationEnergyDemo,
      worked: {"question":"A reaction profile shows reactants at 120 kJ mol⁻¹, the transition state at 210 kJ mol⁻¹ and products at 80 kJ mol⁻¹. Calculate the activation energy and ΔH.","fastMethod":"Subtract reactant energy from peak for Ea; subtract reactants from products for ΔH.","steps":["Ea = 210 kJ mol⁻¹ – 120 kJ mol⁻¹ = 90 kJ mol⁻¹.","ΔH = 80 kJ mol⁻¹ – 120 kJ mol⁻¹ = –40 kJ mol⁻¹.","State Ea = 90 kJ mol⁻¹, ΔH = –40 kJ mol⁻¹ (exothermic)."],"answer":"Ea = 90 kJ mol⁻¹; ΔH = –40 kJ mol⁻¹"},
      selfCheck: {"prompt":"True or false: The activation energy is the same as ΔH.","answer":"False – Ea is the energy to reach the transition state, ΔH is the overall energy change."},
      questions: [{"id":"reaction-profiles-and-activation-energy-q1","prompt":"What does the peak of a reaction profile represent?","accept":["activation energy","energy barrier","transition state"],"hint":"It is the highest point on the diagram."},{"id":"reaction-profiles-and-activation-energy-q2","prompt":"If a reaction is endothermic, where are the products relative to the reactants on the energy axis?","accept":["higher","above","greater energy"],"hint":"Think about ΔH sign."},{"id":"reaction-profiles-and-activation-energy-q3","prompt":"Calculate ΔH for a profile where reactants are 50 kJ mol⁻¹ and products are 130 kJ mol⁻¹.","accept":["+80 kj mol-1","+80 kj/mol","80 kj mol-1","80 kj/mol"],"hint":"Subtract reactant energy from product energy."}],
      mistakes: ["Mixing up Ea with the total energy change shown on the diagram.","Reading the vertical axis as temperature rather than potential energy."],
      examTip: "Label the diagram in your answer – write Ea and ΔH on the sketch to earn marks for correct interpretation.",
      searchTerms: ["reaction profile GCSE","activation energy definition","ΔH on energy diagram","exothermic diagram shape","calculate Ea"],
    },
    {
      id: "simple-cells-and-batteries",
      title: "Simple Cells and Batteries",
      tier: "Extension",
      objective: "Explain how a simple galvanic cell works and calculate the cell potential using standard reduction potentials.",
      whyMatters: "Cells link chemistry to real‑world applications; AQA often asks for cell diagrams, electrode reactions and E° calculations.",
      conceptTitle: "Galvanic cell operation",
      conceptBullets: ["A <b style=\"color:#C9A24B\">galvanic cell</b> converts chemical energy to electrical energy via a spontaneous redox reaction.","The <b style=\"color:#C9A24B\">anode</b> is where oxidation occurs and electrons flow out to the external circuit.","The <b style=\"color:#C9A24B\">cathode</b> is where reduction occurs; electrons return from the circuit.","Cell potential (E°cell) = E°cathode – E°anode (use standard reduction potentials).","A salt bridge maintains charge balance by allowing ion flow without mixing the solutions."],
      conceptNote: "<b>Tip:</b> Always write the half‑reactions as reductions; then subtract the anode potential to get E°cell.",
      glossary: [{"term":"galvanic cell","def":"A device that produces electricity from a spontaneous redox reaction."},{"term":"anode","def":"Electrode where oxidation occurs; negative in a galvanic cell."},{"term":"cell potential","def":"Voltage produced by the cell, calculated from standard reduction potentials."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryEnergyChangesSimpleCellsAndBatteriesDemo,
      worked: {"question":"Calculate the standard cell potential for the cell: Zn(s) | Zn²⁺(1 M) || Cu²⁺(1 M) | Cu(s). Standard reduction potentials: E°(Cu²⁺/Cu) = +0.34 V, E°(Zn²⁺/Zn) = –0.76 V.","fastMethod":"E°cell = E°cathode – E°anode.","steps":["Identify cathode: Cu²⁺ + 2e⁻ → Cu, E° = +0.34 V.","Identify anode: Zn → Zn²⁺ + 2e⁻, use reduction potential –0.76 V.","E°cell = +0.34 V – (–0.76 V) = +1.10 V.","State the cell is spontaneous with E°cell = 1.10 V."],"answer":"E°cell = +1.10 V (spontaneous)"},
      selfCheck: {"prompt":"True or false: In a galvanic cell the anode is positively charged.","answer":"False – the anode is negative because electrons leave it."},
      questions: [{"id":"simple-cells-and-batteries-q1","prompt":"What is the role of the salt bridge?","accept":["maintains charge balance","allows ion flow","completes circuit"],"hint":"Think about preventing charge buildup."},{"id":"simple-cells-and-batteries-q2","prompt":"Write the cell notation for a Daniell cell (Zn|Zn²⁺||Cu²⁺|Cu).","accept":["zn|zn2+||cu2+|cu","zn|zn2+||cu2+|cu"],"hint":"Use vertical bars and double bars."},{"id":"simple-cells-and-batteries-q3","prompt":"Calculate E°cell for Fe(s) | Fe²⁺(1 M) || Ag⁺(1 M) | Ag(s) given E°(Ag⁺/Ag)=+0.80 V, E°(Fe²⁺/Fe)=–0.44 V.","accept":["+1.24 v","+1.24 v","1.24 v"],"hint":"Subtract the Fe reduction potential from the Ag potential."}],
      mistakes: ["Using the oxidation potential directly instead of converting to reduction potential for the anode.","Omitting the sign of E°cell, leading to a negative answer for a spontaneous cell."],
      examTip: "When calculating E°cell, write both half‑reactions as reductions first; this avoids sign errors.",
      searchTerms: ["galvanic cell GCSE","cell potential calculation","anode cathode definition","salt bridge purpose","standard reduction potentials table"],
    }
  ],
};
