import type { TopicContent } from "../types";
import { ChemistryAtomicStructurePeriodicTableSubatomicParticlesAndAtomicNotationDemo, ChemistryAtomicStructurePeriodicTableIsotopesAndRelativeAtomicMassDemo, ChemistryAtomicStructurePeriodicTableElectronicStructureAndPeriodicTrendsDemo } from "../notes-diagrams/chemistry-atomic-structure-periodic-table-demos";

export const chemistryAtomicStructurePeriodicTableTopic: TopicContent = {
  slug: "chemistry-atomic-structure-periodic-table",
  subject: "Chemistry",
  subjectSlug: "gcse-science/chemistry",
  title: "GCSE Chemistry: Atomic Structure and the Periodic Table",
  description: "AQA GCSE Chemistry — Atomic Structure and the Periodic Table. Covers subatomic particles (protons, neutrons, electrons), atomic number/mass number, isotopes and relative atomic mass calculations, the historical development of the atomic model (Dalton to Chadwick), electronic structure, and the periodic table (Groups 1, 7, 0 and their reactivity trends).",
  glyphs: ["⚗️","🧪","⚛️","🔥"],
  subtopics: [
    {
      id: "subatomic-particles-and-atomic-notation",
      title: "Subatomic particles and atomic notation",
      tier: "Foundation",
      objective: "Identify protons, neutrons and electrons and write correct atomic symbols.",
      whyMatters: "Understanding particles underpins all later chemistry and appears in every AQA exam question on formulas and reactions.",
      conceptTitle: "Basic atomic structure",
      conceptBullets: ["The <b style=\"color:#C9A24B\">proton</b> carries a +1 charge and defines the element’s identity (atomic number).","The <b style=\"color:#C9A24B\">neutron</b> is neutral and contributes to the atomic mass but not to chemical behaviour.","The <b style=\"color:#C9A24B\">electron</b> has a –1 charge, orbits the nucleus and determines reactivity.","An atomic symbol is written as ^<b style=\"color:#C9A24B\">A</b>_ZX where Z is the atomic number, A the mass number and X the element symbol."],
      conceptNote: "<b>Tip:</b> Memorise the order of sub‑scripts – mass number top left, atomic number bottom left – to avoid mixing them up in exam writing.",
      glossary: [{"term":"atomic number","def":"Number of protons in the nucleus; unique to each element."},{"term":"mass number","def":"Total of protons and neutrons in the nucleus."},{"term":"electron","def":"Negatively charged particle orbiting the nucleus."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryAtomicStructurePeriodicTableSubatomicParticlesAndAtomicNotationDemo,
      worked: {"question":"Write the atomic symbol for an element with 15 protons, 16 neutrons and the symbol P.","fastMethod":"Add protons and neutrons for A, use Z = 15, then format ^A_ZP.","steps":["Calculate mass number: 15 + 16 = 31.","Atomic number is the number of protons: 15.","Place A as superscript and Z as subscript left of P."],"answer":"^31_15P"},
      selfCheck: {"prompt":"True or false: The atomic number tells you how many neutrons are in an atom.","answer":"False – it tells you the number of protons."},
      questions: [{"id":"subatomic-particles-and-atomic-notation-q1","prompt":"What is the charge of an electron?","accept":["-1","-1 elementary charge","negative one"],"hint":"Think of the sign opposite to the proton."},{"id":"subatomic-particles-and-atomic-notation-q2","prompt":"How many protons are in an atom of chlorine (Cl) with atomic number 17?","accept":["17","seventeen"],"hint":"Atomic number equals number of protons."},{"id":"subatomic-particles-and-atomic-notation-q3","prompt":"Calculate the mass number of an atom that has 12 protons and 13 neutrons.","accept":["25","twenty‑five"],"hint":"Add protons and neutrons."}],
      mistakes: ["Writing the mass number as a subscript and the atomic number as a superscript.","Confusing neutrons with electrons when counting total particles."],
      examTip: "Always check the position of the superscript and subscript before moving to the next question – a simple mis‑placement loses marks.",
      searchTerms: ["atomic number definition","mass number calculation","write atomic symbol","proton neutron electron","AQA atomic notation"],
    },
    {
      id: "isotopes-and-relative-atomic-mass",
      title: "Isotopes and relative atomic mass",
      tier: "Standard",
      objective: "Calculate relative atomic mass from isotopic abundances and distinguish isotopes.",
      whyMatters: "Isotope calculations are a common AQA exam task and underpin the concept of average atomic mass used in formulas.",
      conceptTitle: "Isotopes and weighted averages",
      conceptBullets: ["Isotopes are atoms of the same element with different <b style=\"color:#C9A24B\">neutron</b> numbers, giving different mass numbers.","The <b style=\"color:#C9A24B\">relative atomic mass (Ar)</b> is the weighted average of all naturally occurring isotopes.","To calculate Ar, multiply each isotope’s mass number by its <b style=\"color:#C9A24B\">abundance</b> (as a decimal) and sum the results.","Rounded Ar values are given in the periodic table and are used in stoichiometric calculations.","Natural abundance is expressed as a percentage of the total atoms of that element."],
      conceptNote: "<b>Tip:</b> Convert percentages to decimals before multiplying; keep extra decimal places until the final answer to avoid rounding errors.",
      glossary: [{"term":"isotope","def":"Atoms of the same element with different numbers of neutrons."},{"term":"relative atomic mass","def":"Weighted average mass of an element’s isotopes, expressed in atomic mass units."},{"term":"abundance","def":"The proportion of a particular isotope in a natural sample, usually given as a percent."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: ChemistryAtomicStructurePeriodicTableIsotopesAndRelativeAtomicMassDemo,
      worked: {"question":"Chlorine has two isotopes: ^35Cl (75.8%) and ^37Cl (24.2%). Calculate its relative atomic mass (Ar) to one decimal place.","fastMethod":"Convert percentages to decimals, multiply each mass by its fraction, add.","steps":["75.8% → 0.758; 24.2% → 0.242.","35 × 0.758 = 26.53.","37 × 0.242 = 8.95.","Add: 26.53 + 8.95 = 35.48 → 35.5 (1 d.p.)."],"answer":"35.5"},
      selfCheck: {"prompt":"True or false: The relative atomic mass of an element is always a whole number.","answer":"False – it is a weighted average and often a decimal."},
      questions: [{"id":"isotopes-and-relative-atomic-mass-q1","prompt":"What term describes atoms of the same element with different neutron numbers?","accept":["isotope","isotopes"],"hint":"Think of chlorine’s ^35Cl and ^37Cl."},{"id":"isotopes-and-relative-atomic-mass-q2","prompt":"If an element has isotopes ^10X (20%) and ^11X (80%), what is its Ar to two decimal places?","accept":["10.8","10.80"],"hint":"Use 0.20 and 0.80 as fractions."},{"id":"isotopes-and-relative-atomic-mass-q3","prompt":"Convert a 33% natural abundance to a decimal fraction.","accept":["0.33","0.33"],"hint":"Divide by 100."}],
      mistakes: ["Using percentages directly without converting to decimals.","Rounding each isotope contribution before summing, leading to a wrong final Ar."],
      examTip: "Write the decimal fractions beside the percentages in the margin; this visual cue prevents accidental use of the wrong numbers.",
      searchTerms: ["isotope calculation","relative atomic mass formula","AQA isotope question","weighted average atomic mass","chlorine isotopes ar"],
    },
    {
      id: "electronic-structure-and-periodic-trends",
      title: "Electronic structure and periodic trends",
      tier: "Extension",
      objective: "Explain electron configuration, relate it to group properties and predict reactivity trends for Groups 1, 7 and 0.",
      whyMatters: "Electronic structure links the periodic table to chemical behaviour; exam questions often ask for trends or why a group is reactive.",
      conceptTitle: "Electrons, shells and group reactivity",
      conceptBullets: ["Electrons occupy <b style=\"color:#C9A24B\">energy levels</b> (shells) labelled 1, 2, 3… with a maximum 2n² electrons per level.","The outermost electrons are the <b style=\"color:#C9A24B\">valence electrons</b>; their number determines group chemistry.","Group 1 elements have 1 valence electron and are highly <b style=\"color:#C9A24B\">reactive metals</b>, losing that electron to form +1 ions.","Group 7 (halogens) have 7 valence electrons, are very <b style=\"color:#C9A24B\">reactive non‑metals</b>, gaining one electron to form –1 ions.","Group 0 (noble gases) have full outer shells (8 valence electrons, except He) and are <b style=\"color:#C9A24B\">inert</b> under normal conditions."],
      conceptNote: "<b>Tip:</b> When writing electron configurations, use the noble‑gas shorthand to save time and avoid mistakes in long shells.",
      glossary: [{"term":"valence electron","def":"Electron(s) in the outermost energy level that participate in bonding."},{"term":"electron configuration","def":"Notation showing how electrons are distributed among energy levels and subshells."},{"term":"reactivity trend","def":"The systematic change in how readily elements react, usually down a group or across a period."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryAtomicStructurePeriodicTableElectronicStructureAndPeriodicTrendsDemo,
      worked: {"question":"Write the electron configuration for chlorine (Z = 17) using noble‑gas notation.","fastMethod":"Start from the nearest preceding noble gas (Ne, Z=10) then add remaining electrons.","steps":["Neon configuration: [He] 2s² 2p⁶.","Add 3 electrons to the 3s subshell: 3s² 3p⁵.","Combine: [Ne] 3s² 3p⁵."],"answer":"[Ne] 3s² 3p⁵"},
      selfCheck: {"prompt":"True or false: All Group 0 elements have exactly eight valence electrons.","answer":"False – helium has only two valence electrons."},
      questions: [{"id":"electronic-structure-and-periodic-trends-q1","prompt":"How many valence electrons does sodium (Na) have?","accept":["1","one"],"hint":"Sodium is in Group 1."},{"id":"electronic-structure-and-periodic-trends-q2","prompt":"Which group is most reactive: Group 1 metals or Group 7 halogens?","accept":["group 1","group 1 metals","group 1 metals are more reactive"],"hint":"Consider electron loss vs gain."},{"id":"electronic-structure-and-periodic-trends-q3","prompt":"Give the noble‑gas electron configuration for argon (Z = 18).","accept":["[Ne] 3s² 3p⁶","[ne] 3s2 3p6"],"hint":"Argon is a noble gas itself."}],
      mistakes: ["Writing the full configuration for a noble gas instead of using the shorthand.","Confusing the trend: reactivity of Group 1 increases down the group, while for Group 7 it decreases."],
      examTip: "When an exam asks for reactivity, state the number of valence electrons first, then link to the tendency to lose or gain electrons – this gives a complete answer.",
      searchTerms: ["electron configuration GCSE","valence electrons groups","group 1 reactivity trend","halogen electron config","noble gas shorthand"],
    }
  ],
};
