import type { TopicContent } from "../types";
import { ChemistryQuantitativeChemistryConservationOfMassBalancingEquationsDemo, ChemistryQuantitativeChemistryRelativeFormulaMassMolesAvogadroConstantDemo, ChemistryQuantitativeChemistryConcentrationPercentageYieldAtomEconomyDemo } from "../notes-diagrams/chemistry-quantitative-chemistry-demos";

export const chemistryQuantitativeChemistryTopic: TopicContent = {
  slug: "chemistry-quantitative-chemistry",
  subject: "Chemistry",
  subjectSlug: "gcse-science/chemistry",
  title: "GCSE Chemistry: Quantitative Chemistry",
  description: "AQA GCSE Chemistry — Quantitative Chemistry. Covers conservation of mass and balancing equations, relative formula mass, moles and the Avogadro constant, concentration of solutions, and percentage yield/atom economy.",
  glyphs: ["⚗️","🧪","⚛️","🔥"],
  subtopics: [
    {
      id: "conservation-of-mass-balancing-equations",
      title: "Conservation of mass & balancing equations",
      tier: "Foundation",
      objective: "Balance chemical equations and explain why mass is conserved in a reaction.",
      whyMatters: "Understanding conservation of mass is fundamental for writing correct equations, a frequent exam requirement.",
      conceptTitle: "Balancing chemical equations",
      conceptBullets: ["The <b style=\"color:#C9A24B\">law of conservation of mass</b> states that atoms are neither created nor destroyed during a chemical reaction.","A balanced equation has the same number of each type of atom on both sides of the arrow.","Coefficients are used to adjust the number of molecules, never the subscripts, to achieve balance.","Balancing is checked by counting atoms of each element on both sides after coefficients are applied."],
      conceptNote: "<b>Tip:</b> Start with the element that appears in the fewest formulas and work towards the most common elements like O and H.",
      glossary: [{"term":"reactants","def":"Substances present at the start of a chemical reaction."},{"term":"products","def":"Substances formed as a result of the reaction."},{"term":"coefficient","def":"A whole number placed before a formula to indicate the number of molecules."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryQuantitativeChemistryConservationOfMassBalancingEquationsDemo,
      worked: {"question":"Balance the equation: Fe + O₂ → Fe₂O₃","fastMethod":"Balance Fe first, then O.","steps":["Place a 2 in front of Fe to give 2 Fe atoms.","Place a 3/2 in front of O₂ to give 3 O atoms.","Multiply all coefficients by 2 to remove the fraction.","Resulting balanced equation: 4 Fe + 3 O₂ → 2 Fe₂O₃."],"answer":"4 Fe + 3 O₂ → 2 Fe₂O₃"},
      selfCheck: {"prompt":"True or false: Changing subscripts in a formula is a valid way to balance an equation.","answer":"False – only coefficients may be altered when balancing."},
      questions: [{"id":"conservation-of-mass-balancing-equations-q1","prompt":"What does the law of conservation of mass state?","accept":["mass is conserved","atoms are neither created nor destroyed"],"hint":"Think about what happens to atoms during a reaction."},{"id":"conservation-of-mass-balancing-equations-q2","prompt":"In the equation 2 H₂ + O₂ → 2 H₂O, how many oxygen atoms are on each side?","accept":["2","two"],"hint":"Count O atoms in each formula."},{"id":"conservation-of-mass-balancing-equations-q3","prompt":"Balance: C₃H₈ + O₂ → CO₂ + H₂O","accept":["1c3h8 + 5o2 → 3co2 + 4h2o","c3h8 + 5o2 → 3co2 + 4h2o"],"hint":"Balance C, then H, then O."}],
      mistakes: ["Altering subscripts instead of using coefficients.","Forgetting to multiply all coefficients to remove fractions."],
      examTip: "Write the unbalanced equation clearly, then list each element and tick them off as you adjust coefficients.",
      searchTerms: ["balance chemical equation","law of conservation of mass","coefficients vs subscripts","GCSE chemistry balancing","mass conserved reaction"],
    },
    {
      id: "relative-formula-mass-moles-avogadro-constant",
      title: "Relative formula mass, moles & Avogadro constant",
      tier: "Standard",
      objective: "Calculate relative formula mass, convert between moles, mass and number of particles.",
      whyMatters: "Mole calculations underpin most quantitative questions in the exam, from yields to solution concentrations.",
      conceptTitle: "Mole concept and calculations",
      conceptBullets: ["The <b style=\"color:#C9A24B\">relative formula mass (Mr)</b> is the sum of the atomic masses of all atoms in a formula, expressed in g mol⁻¹.","One mole contains <b style=\"color:#C9A24B\">Avogadro's constant (6.02×10²³)</b> particles, linking mass to number of entities.","Moles are calculated by dividing the given mass by the Mr of the substance.","The number of particles is found by multiplying the amount in moles by Avogadro's constant."],
      conceptNote: "<b>Tip:</b> Keep a tidy table of atomic masses and use it to quickly sum Mr values.",
      glossary: [{"term":"relative formula mass","def":"Total mass of one mole of a compound, in g mol⁻¹."},{"term":"mole","def":"The amount of substance containing 6.02×10²³ particles."},{"term":"Avogadro constant","def":"6.02×10²³, the number of entities in one mole."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: ChemistryQuantitativeChemistryRelativeFormulaMassMolesAvogadroConstantDemo,
      worked: {"question":"Calculate the number of moles in 18.0 g of H₂O (Mr = 18.0 g mol⁻¹).","fastMethod":"Divide mass by Mr directly.","steps":["Mass = 18.0 g, Mr = 18.0 g mol⁻¹.","Moles = 18.0 g ÷ 18.0 g mol⁻¹.","Moles = 1.00 mol."],"answer":"1.00 mol"},
      selfCheck: {"prompt":"True or false: 0.5 mol of CO₂ contains 3.01×10²³ molecules.","answer":"True – 0.5 × 6.02×10²³ = 3.01×10²³."},
      questions: [{"id":"relative-formula-mass-moles-avogadro-constant-q1","prompt":"What is the relative formula mass of NaCl?","accept":["58.5","58.44"],"hint":"Add atomic masses of Na (23) and Cl (35.5)."},{"id":"relative-formula-mass-moles-avogadro-constant-q2","prompt":"How many molecules are in 2 mol of O₂?","accept":["1.204×10²⁴","1.204e24"],"hint":"Multiply moles by Avogadro's constant."},{"id":"relative-formula-mass-moles-avogadro-constant-q3","prompt":"A sample contains 3.01×10²³ atoms of carbon. How many moles is this?","accept":["0.5","0.5 mol"],"hint":"Divide the number of atoms by 6.02×10²³."}],
      mistakes: ["Using the atomic mass unit (amu) value directly without converting to g mol⁻¹.","Forgetting to keep significant figures when dividing mass by Mr."],
      examTip: "Write the formula mass calculation on a separate line; it saves time and reduces errors when the same compound recurs.",
      searchTerms: ["relative formula mass","mole calculation GCSE","Avogadro constant","how many moles","GCSE chemistry Mr"],
    },
    {
      id: "concentration-percentage-yield-atom-economy",
      title: "Concentration, percentage yield & atom economy",
      tier: "Extension",
      objective: "Determine solution concentrations, calculate percentage yield and assess atom economy of reactions.",
      whyMatters: "These calculations test real‑world application of quantitative chemistry and appear in both written and practical exam sections.",
      conceptTitle: "Quantitative analysis of reactions",
      conceptBullets: ["The <b style=\"color:#C9A24B\">concentration (c)</b> of a solution is expressed as moles of solute per litre of solution (mol L⁻¹).","Percentage yield = (actual yield ÷ theoretical yield) × 100 %, showing experimental efficiency.","Atom economy = (molar mass of desired product ÷ total molar mass of all reactants) × 100 %, indicating how ‘green’ a synthesis is.","All calculations require careful unit conversion and correct use of significant figures."],
      conceptNote: "<b>Tip:</b> When calculating percentage yield, always find the theoretical yield first using stoichiometry.",
      glossary: [{"term":"concentration","def":"Amount of solute per unit volume of solution, expressed in mol L⁻¹."},{"term":"percentage yield","def":"Ratio of actual to theoretical yield, expressed as a percentage."},{"term":"atom economy","def":"Measure of how much of the reactants end up in the desired product."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryQuantitativeChemistryConcentrationPercentageYieldAtomEconomyDemo,
      worked: {"question":"A reaction should produce 5.00 g of NaCl but only 4.20 g is obtained. Calculate the percentage yield.","fastMethod":"Divide actual by theoretical and multiply by 100.","steps":["Actual yield = 4.20 g, theoretical yield = 5.00 g.","% yield = (4.20 ÷ 5.00) × 100.","% yield = 84 %."],"answer":"84 %"},
      selfCheck: {"prompt":"True or false: A solution containing 0.250 mol of solute in 0.500 L has a concentration of 0.125 mol L⁻¹.","answer":"True – c = 0.250 ÷ 0.500 = 0.125 mol L⁻¹."},
      questions: [{"id":"concentration-percentage-yield-atom-economy-q1","prompt":"What is the concentration of a solution made by dissolving 0.500 mol of glucose in 250 mL of water?","accept":["2.0","2 mol/l","2 mol l⁻¹"],"hint":"Convert mL to L first."},{"id":"concentration-percentage-yield-atom-economy-q2","prompt":"Calculate the atom economy for the reaction: 2 C₂H₆ + 7 O₂ → 4 CO₂ + 6 H₂O.","accept":["66.7","66.7%"],"hint":"Find total molar mass of reactants and mass of CO₂ produced."},{"id":"concentration-percentage-yield-atom-economy-q3","prompt":"If 12.0 g of product is obtained from a theoretical yield of 15.0 g, what is the percentage yield?","accept":["80","80%"],"hint":"Use (actual ÷ theoretical) × 100."}],
      mistakes: ["Mixing up volume units (mL vs L) when calculating concentration.","Using mass of reactants instead of molar mass of product in atom economy."],
      examTip: "For atom economy, write a quick table of molar masses; it speeds up the ratio calculation and avoids forgetting any reactant.",
      searchTerms: ["solution concentration GCSE","percentage yield calculation","atom economy exam","molarity formula","GCSE chemistry yield"],
    }
  ],
};
