import type { TopicContent } from "../types";
import { ChemistryOrganicChemistryCrudeOilHydrocarbonsFractionalDistillationDemo, ChemistryOrganicChemistryAlkanesAndAlkenesStructuresReactionsDemo, ChemistryOrganicChemistryCrackingPolymersAndExtensionConceptsDemo } from "../notes-diagrams/chemistry-organic-chemistry-demos";

export const chemistryOrganicChemistryTopic: TopicContent = {
  slug: "chemistry-organic-chemistry",
  subject: "Chemistry",
  subjectSlug: "gcse-science/chemistry",
  title: "GCSE Chemistry: Organic Chemistry",
  description: "AQA GCSE Chemistry — Organic Chemistry. Covers crude oil and hydrocarbons, fractional distillation, alkanes and alkenes, cracking, and an introduction to polymers.",
  glyphs: ["⚗️","🧪","⚛️","🔥"],
  subtopics: [
    {
      id: "crude-oil-hydrocarbons-fractional-distillation",
      title: "Crude oil, hydrocarbons & fractional distillation",
      tier: "Foundation",
      objective: "Identify the main types of hydrocarbons in crude oil and explain how fractional distillation separates them.",
      whyMatters: "Understanding crude oil is the basis for all organic chemistry in the exam and appears in many context questions.",
      conceptTitle: "What crude oil contains and how it is separated",
      conceptBullets: ["Crude oil is a mixture of <b style=\"color:#C9A24B\">hydrocarbons</b> of varying chain lengths and structures, plus small amounts of sulphur and nitrogen compounds.","The main groups are <b style=\"color:#C9A24B\">alkanes</b> (saturated) and <b style=\"color:#C9A24B\">alkenes</b> (unsaturated) which differ in bonding and reactivity.","During <b style=\"color:#C9A24B\">fractional distillation</b> the mixture is heated; components with lower boiling points rise higher in the column and are collected first.","The column is divided into zones (e.g., petrol, diesel, kerosene) that correspond to specific boiling‑point ranges used in exam tables.","The process is a physical separation; no chemical change occurs, so the hydrocarbons retain their original formulas."],
      conceptNote: "<b>Tip:</b> Memorise the order of fractions and their typical boiling‑point ranges – a quick lookup table saves marks in context questions.",
      glossary: [{"term":"hydrocarbon","def":"A compound containing only hydrogen and carbon atoms."},{"term":"alkane","def":"A saturated hydrocarbon with only single C–C bonds, formula CₙH₂ₙ₊₂."},{"term":"fractional distillation","def":"A technique that separates liquids based on differing boiling points using a tall column."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryOrganicChemistryCrudeOilHydrocarbonsFractionalDistillationDemo,
      worked: {"question":"A sample of crude oil yields 30 g of petrol (boiling 40‑200 °C) and 20 g of diesel (boiling 200‑350 °C). What percentage of the original sample is petrol?","fastMethod":"Use (mass of petrol ÷ total mass) × 100.","steps":["Add masses: 30 g + 20 g = 50 g (total).","Divide petrol mass by total: 30 g ÷ 50 g = 0.6.","Multiply by 100: 0.6 × 100 = 60%."],"answer":"60 % of the original sample is petrol."},
      selfCheck: {"prompt":"True or false: Fractional distillation changes the chemical formula of the hydrocarbons.","answer":"False – it is a physical separation only."},
      questions: [{"id":"crude-oil-hydrocarbons-fractional-distillation-q1","prompt":"Name the two main families of hydrocarbons found in crude oil.","accept":["alkanes and alkenes","alkanes, alkenes"],"hint":"One is saturated, the other unsaturated."},{"id":"crude-oil-hydrocarbons-fractional-distillation-q2","prompt":"What is the main purpose of the fractionating column?","accept":["separate components by boiling point","separate liquids by boiling point"],"hint":"Think of how vapour rises."},{"id":"crude-oil-hydrocarbons-fractional-distillation-q3","prompt":"If a hydrocarbon has the formula C₈H₁₈, what type of hydrocarbon is it?","accept":["alkane","saturated hydrocarbon"],"hint":"Check the general formula for alkanes."}],
      mistakes: ["Confusing boiling‑point order and assuming heavier fractions boil at lower temperatures.","Writing the alkane formula as CₙH₂ₙ instead of CₙH₂ₙ₊₂."],
      examTip: "When a question gives a boiling‑point range, match it to the correct fraction table – this instantly tells you the likely carbon‑number range.",
      searchTerms: ["crude oil hydrocarbons","fractional distillation GCSE","alkane definition","petrol boiling point range","hydrocarbon separation"],
    },
    {
      id: "alkanes-and-alkenes-structures-reactions",
      title: "Alkanes and alkenes: structures & reactions",
      tier: "Standard",
      objective: "Draw structural formulas for simple alkanes and alkenes and predict the products of combustion and addition reactions.",
      whyMatters: "These reactions are core to many GCSE exam questions, especially for calculating masses of gases produced.",
      conceptTitle: "Key properties and typical reactions",
      conceptBullets: ["Alkanes are <b style=\"color:#C9A24B\">saturated</b> hydrocarbons; they undergo <b style=\"color:#C9A24B\">combustion</b> producing CO₂ and H₂O.","Alkenes contain a carbon‑carbon <b style=\"color:#C9A24B\">double bond</b>; they are unsaturated and can undergo <b style=\"color:#C9A24B\">addition</b> reactions such as hydrogenation.","Combustion of an alkane follows: CₙH₂ₙ₊₂ + (3n+1)O₂ → nCO₂ + (n+1)H₂O.","Addition of H₂ to an alkene (hydrogenation) converts the double bond to a single bond, giving an alkane with the same carbon number.","Both families are non‑polar, so they are insoluble in water and soluble in non‑polar solvents."],
      conceptNote: "<b>Tip:</b> Memorise the generic combustion equation; plug in n to avoid re‑deriving each time.",
      glossary: [{"term":"saturated","def":"Contains only single bonds; cannot add more hydrogen without breaking bonds."},{"term":"double bond","def":"A covalent bond where two pairs of electrons are shared between two carbon atoms."},{"term":"addition reaction","def":"A reaction where atoms add across a double bond, removing unsaturation."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: ChemistryOrganicChemistryAlkanesAndAlkenesStructuresReactionsDemo,
      worked: {"question":"When 2 mol of ethene (C₂H₄) is completely hydrogenated, how many moles of H₂ are required?","fastMethod":"One mole H₂ adds to each double bond.","steps":["Ethene has one C=C bond per molecule.","Each mole of ethene needs 1 mol H₂.","Multiply by 2 mol ethene: 2 mol × 1 mol H₂ = 2 mol H₂."],"answer":"2 mol of H₂ are required."},
      selfCheck: {"prompt":"True or false: Combustion of an alkane produces only CO₂ and H₂O.","answer":"True – complete combustion yields only those gases."},
      questions: [{"id":"alkanes-and-alkenes-structures-reactions-q1","prompt":"Write the structural formula for propane.","accept":["CH3-CH2-CH3","c3h8","propane"],"hint":"Three carbon atoms in a chain, each saturated with H."},{"id":"alkanes-and-alkenes-structures-reactions-q2","prompt":"What type of reaction does ethene undergo with Br₂?","accept":["addition","halogen addition"],"hint":"Think of adding across the double bond."},{"id":"alkanes-and-alkenes-structures-reactions-q3","prompt":"Calculate the volume of CO₂ produced at STP when 1 mol of butane combusts completely.","accept":["2 mol","2"],"hint":"Butane (C₄H₁₀) gives 4 mol CO₂ per mole."}],
      mistakes: ["Using the alkene formula CₙH₂ₙ₊₂ for alkenes.","Assuming combustion of alkenes needs the same O₂ amount as alkanes."],
      examTip: "When asked for products of combustion, always write CO₂ and H₂O on the right side of the arrow; then balance O₂ last.",
      searchTerms: ["alkane combustion equation","alkene addition reaction","hydrogenation of ethene","propane structure GCSE","C n H 2n formula"],
    },
    {
      id: "cracking-polymers-and-extension-concepts",
      title: "Cracking, polymers and extension concepts",
      tier: "Extension",
      objective: "Explain catalytic cracking, describe how monomers form polymers, and calculate degree of polymerisation for a simple polymer.",
      whyMatters: "Cracking links petroleum processing to useful products, and polymer knowledge is tested in both recall and calculation questions.",
      conceptTitle: "From small hydrocarbons to large polymers",
      conceptBullets: ["Catalytic <b style=\"color:#C9A24B\">cracking</b> breaks large alkanes into smaller alkanes and alkenes using heat and a catalyst such as zeolite.","The main products are useful fuels (e.g., gasoline) and feed‑stock alkenes for polymer manufacture.","A <b style=\"color:#C9A24B\">monomer</b> is a small molecule that can join with others via <b style=\"color:#C9A24B\">addition polymerisation</b> to form a polymer chain.","In addition polymerisation each double bond opens, linking monomers; the degree of polymerisation (DP) = number of repeat units.","The mass of a polymer = DP × molar mass of the repeat unit; this relationship is often tested in GCSE calculations."],
      conceptNote: "<b>Tip:</b> When given mass of polymer and monomer, divide the polymer mass by the monomer’s repeat‑unit mass to find DP quickly.",
      glossary: [{"term":"cracking","def":"Thermal or catalytic process that breaks large hydrocarbon molecules into smaller ones."},{"term":"monomer","def":"A small molecule that can join covalently with identical or similar units to form a polymer."},{"term":"degree of polymerisation","def":"The number of repeat units in a polymer chain."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryOrganicChemistryCrackingPolymersAndExtensionConceptsDemo,
      worked: {"question":"A sample of polyethylene weighs 5.6 g. The repeat unit –CH₂–CH₂– has a molar mass of 28 g mol⁻¹. How many repeat units are present?","fastMethod":"Divide polymer mass by repeat‑unit mass.","steps":["Mass of polymer = 5.6 g.","Molar mass of repeat unit = 28 g mol⁻¹.","DP = 5.6 g ÷ 28 g mol⁻¹ = 0.20 mol repeat units.","Convert to number of units: 0.20 mol × Avogadro’s number ≈ 1.2 × 10²³ units."],"answer":"0.20 mol of repeat units (≈1.2 × 10²³ units)."},
      selfCheck: {"prompt":"True or false: Cracking produces only alkanes.","answer":"False – it also produces alkenes such as ethene."},
      questions: [{"id":"cracking-polymers-and-extension-concepts-q1","prompt":"Name the catalyst commonly used in catalytic cracking.","accept":["zeolite","solid acid zeolite"],"hint":"It is a porous aluminosilicate."},{"id":"cracking-polymers-and-extension-concepts-q2","prompt":"What is the repeat unit of polypropylene?","accept":["–CH2–CH(CH3)–","ch2-ch(ch3)"],"hint":"One carbon bears a methyl group."},{"id":"cracking-polymers-and-extension-concepts-q3","prompt":"If 0.05 mol of ethene is polymerised, what mass of polyethylene is formed? (Molar mass of repeat unit = 28 g mol⁻¹)","accept":["1.4 g","1.40 g"],"hint":"Mass = moles × molar mass."}],
      mistakes: ["Confusing the repeat‑unit mass with the monomer’s molecular mass (e.g., using C₂H₄ = 28 g mol⁻¹ incorrectly for polyethylene which uses –CH₂–CH₂–).","Assuming cracking always yields a single product rather than a mixture of alkanes and alkenes."],
      examTip: "When a question asks for the number of repeat units, work in moles first; the conversion to actual number of units is rarely required at GCSE level.",
      searchTerms: ["catalytic cracking zeolite","polyethylene repeat unit","degree of polymerisation calculation","addition polymerisation GCSE","ethylene monomer polymer"],
    }
  ],
};
