import type { TopicContent } from "../types";
import { ChemistryChemicalAnalysisPureSubstancesAndFormulationsDemo, ChemistryChemicalAnalysisChromatographyDemo, ChemistryChemicalAnalysisTestsForCommonGasesDemo } from "../notes-diagrams/chemistry-chemical-analysis-demos";

export const chemistryChemicalAnalysisTopic: TopicContent = {
  slug: "chemistry-chemical-analysis",
  subject: "Chemistry",
  subjectSlug: "gcse-science/chemistry",
  title: "GCSE Chemistry: Chemical Analysis",
  description: "AQA GCSE Chemistry — Chemical Analysis. Covers pure substances and formulations, chromatography, and tests for common gases (hydrogen, oxygen, carbon dioxide, chlorine).",
  glyphs: ["⚗️","🧪","⚛️","🔥"],
  subtopics: [
    {
      id: "pure-substances-and-formulations",
      title: "Pure substances and formulations",
      tier: "Foundation",
      objective: "Identify pure substances, mixtures and write correct formulations for common compounds.",
      whyMatters: "Understanding purity and formulation underpins all later analysis techniques and is frequently tested in written and practical questions.",
      conceptTitle: "Key ideas",
      conceptBullets: ["A <b style=\"color:#C9A24B\">pure substance</b> has a fixed composition and consistent properties, e.g., distilled water or sodium chloride.","A <b style=\"color:#C9A24B\">mixture</b> contains two or more substances that retain their individual identities and can be separated by physical means.","The <b style=\"color:#C9A24B\">empirical formula</b> shows the simplest whole‑number ratio of atoms in a compound, useful for identification.","The <b style=\"color:#C9A24B\">molecular formula</b> gives the actual number of atoms in a molecule and is derived from the empirical formula and molar mass.","A <b style=\"color:#C9A24B\">homogeneous mixture</b> (solution) appears uniform, whereas a <b style=\"color:#C9A24B\">heterogeneous mixture</b> shows distinct parts."],
      conceptNote: "<b>Tip:</b> When asked for a formula, first decide if the question expects empirical or molecular – check the given molar mass.",
      glossary: [{"term":"pure substance","def":"A material with a fixed composition and consistent properties."},{"term":"mixture","def":"A combination of two or more substances that are not chemically bonded."},{"term":"empirical formula","def":"The simplest whole‑number ratio of atoms in a compound."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryChemicalAnalysisPureSubstancesAndFormulationsDemo,
      worked: {"question":"A compound contains 40.0% C, 6.7% H and 53.3% O by mass. Its molar mass is 180 g mol⁻¹. Write its molecular formula.","fastMethod":"Find empirical formula, then multiply by (Molar mass ÷ empirical mass).","steps":["Assume 100 g sample → 40.0 g C, 6.7 g H, 53.3 g O.","Convert to moles: C 3.33 mol, H 6.65 mol, O 3.33 mol.","Divide by smallest (3.33) → C1 H2 O1 → empirical C H₂ O.","Empirical mass = 12 + 2×1 + 16 = 30 g mol⁻¹; multiplier = 180 ÷ 30 = 6.","Molecular formula = C₆H₁₂O₆."],"answer":"C₆H₁₂O₆"},
      selfCheck: {"prompt":"True or false: A homogeneous mixture can be separated by simple filtration.","answer":"False – filtration only separates heterogeneous mixtures with solid particles."},
      questions: [{"id":"pure-substances-and-formulations-q1","prompt":"Define a pure substance.","accept":["a material with fixed composition","substance with consistent composition and properties"],"hint":"Think about composition and properties."},{"id":"pure-substances-and-formulations-q2","prompt":"What is the empirical formula of a compound containing 52.14% C, 34.73% O and 13.13% H?","accept":["CH2O","ch2o"],"hint":"Convert percentages to moles and find the simplest whole‑number ratio."},{"id":"pure-substances-and-formulations-q3","prompt":"Give one example of a heterogeneous mixture.","accept":["sand in water","soil","salad","granite"],"hint":"Look for a mixture where components are visible."}],
      mistakes: ["Confusing empirical and molecular formulas and using the wrong molar mass multiplier.","Assuming all mixtures can be separated by filtration."],
      examTip: "When a question asks for a formula, always check whether the given mass matches the empirical or molecular mass before writing the answer.",
      searchTerms: ["pure substance definition","empirical formula calculation","homogeneous vs heterogeneous","molecular formula from empirical","mixture separation methods"],
    },
    {
      id: "chromatography",
      title: "Chromatography",
      tier: "Standard",
      objective: "Explain how paper chromatography separates components and interpret Rf values.",
      whyMatters: "Chromatography is a core practical skill; exam questions often ask you to predict or explain separation results.",
      conceptTitle: "Core principles",
      conceptBullets: ["In <b style=\"color:#C9A24B\">paper chromatography</b> the solvent (mobile phase) moves up the paper by capillary action, carrying solutes at different rates.","The distance travelled by a solute relative to the solvent front is its <b style=\"color:#C9A24B\">Rf value</b>, a constant for a given system.","A higher <b style=\"color:#C9A24B\">polarity</b> of the solute relative to the solvent means it travels a shorter distance.","The solvent choice (polar vs non‑polar) determines which components will move further up the paper.","Rf values are reproducible under identical conditions, allowing identification of unknowns by comparison with standards."],
      conceptNote: "<b>Tip:</b> Always measure from the original spot line, not from the edge of the paper, when calculating Rf.",
      glossary: [{"term":"Rf value","def":"Ratio of distance travelled by solute to distance travelled by solvent front."},{"term":"mobile phase","def":"The solvent that moves up the chromatography paper."},{"term":"stationary phase","def":"The paper (or other medium) that remains fixed during the separation."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: ChemistryChemicalAnalysisChromatographyDemo,
      worked: {"question":"In a chromatography experiment the solvent front moved 8.0 cm and a pigment spot moved 3.2 cm. Calculate its Rf value.","fastMethod":"Divide the spot distance by the solvent distance.","steps":["Distance solute = 3.2 cm.","Distance solvent = 8.0 cm.","Rf = 3.2 ÷ 8.0 = 0.40."],"answer":"Rf = 0.40"},
      selfCheck: {"prompt":"True or false: An Rf value can be greater than 1.","answer":"False – Rf is always ≤ 1 because the solute cannot travel further than the solvent front."},
      questions: [{"id":"chromatography-q1","prompt":"What does a low Rf value indicate about a solute’s polarity in a polar solvent system?","accept":["high polarity","more polar"],"hint":"Compare solute‑solvent interactions."},{"id":"chromatography-q2","prompt":"Name the two phases in paper chromatography.","accept":["mobile phase and stationary phase","solvent and paper"],"hint":"One moves, one stays."},{"id":"chromatography-q3","prompt":"If pigment A has Rf 0.25 and pigment B has Rf 0.75 on the same plate, which is more non‑polar?","accept":["pigment b","b"],"hint":"Higher Rf means less interaction with polar stationary phase."}],
      mistakes: ["Measuring Rf from the edge of the paper instead of the original spot line.","Assuming Rf values are the same with different solvents or paper types."],
      examTip: "When asked to compare two substances, state the Rf values first and then relate the difference to polarity or solvent choice.",
      searchTerms: ["paper chromatography Rf","how to calculate Rf","chromatography polarity","mobile stationary phase","chromatography exam technique"],
    },
    {
      id: "tests-for-common-gases",
      title: "Tests for common gases",
      tier: "Extension",
      objective: "Perform and interpret qualitative tests for H₂, O₂, CO₂ and Cl₂ gases.",
      whyMatters: "Gas identification is a staple of practical exams; knowing the correct reagents and observations earns marks for method and conclusion.",
      conceptTitle: "Test principles",
      conceptBullets: ["Hydrogen is confirmed by a <b style=\"color:#C9A24B\">pop test</b> – a squeaky pop when a burning splint is held near the gas.","Oxygen supports combustion; a glowing splint reignites brightly, indicating <b style=\"color:#C9A24B\">oxygen</b>.","Carbon dioxide turns limewater milky due to formation of <b style=\"color:#C9A24B\">calcium carbonate</b>.","Chlorine gas bleaches damp red litmus paper pink to colourless and gives a characteristic pungent smell.","Safety note: chlorine is toxic – always work in a fume hood and wear gloves."],
      conceptNote: "<b>Tip:</b> Write the observation exactly as the exam expects (e.g., “limewater turns milky” not just “cloudy”).",
      glossary: [{"term":"pop test","def":"A test where hydrogen ignites with a small popping sound."},{"term":"glowing splint","def":"A splint that has been lit and then blown out; it reignites in oxygen."},{"term":"limewater","def":"A dilute solution of calcium hydroxide used to detect carbon dioxide."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryChemicalAnalysisTestsForCommonGasesDemo,
      worked: {"question":"A gas sample turns limewater milky and a damp red litmus paper colourless. Which gases are present?","fastMethod":"Match each observation to its specific gas test.","steps":["Milky limewater → carbon dioxide present.","Litmus turns colourless → chlorine present.","Both observations together indicate a mixture of CO₂ and Cl₂."],"answer":"Carbon dioxide and chlorine gases are present."},
      selfCheck: {"prompt":"True or false: A glowing splint will reignite in hydrogen gas.","answer":"False – hydrogen gives a pop, not a sustained flame."},
      questions: [{"id":"tests-for-common-gases-q1","prompt":"What observation confirms the presence of oxygen?","accept":["glowing splint reignites","splint reignites brightly"],"hint":"Think about combustion support."},{"id":"tests-for-common-gases-q2","prompt":"Which gas gives a pungent smell and bleaches litmus?","accept":["chlorine","cl2"],"hint":"Look for bleaching and odor."},{"id":"tests-for-common-gases-q3","prompt":"A gas produces a pop with a burning splint and no colour change on litmus. Identify the gas.","accept":["hydrogen","h2"],"hint":"Pop test is characteristic."}],
      mistakes: ["Confusing the limewater test (CO₂) with the acid test (HCl) which also turns it milky.","Describing chlorine’s effect on litmus as “turns red” instead of “bleaches to colourless”."],
      examTip: "When a question asks for a gas identification, list the reagent used, the observation and the gas name in a single concise sentence.",
      searchTerms: ["hydrogen pop test","oxygen glowing splint","carbon dioxide limewater test","chlorine litmus test","gas identification GCSE"],
    }
  ],
};
