import type { TopicContent } from "../types";
import { ChemistryChemicalChangesReactivitySeriesAndMetalReactionsDemo, ChemistryChemicalChangesExtractionAndReductionOfMetalsDemo, ChemistryChemicalChangesAcidBaseReactionsPhAndElectrolysisOfSolutionsDemo } from "../notes-diagrams/chemistry-chemical-changes-demos";

export const chemistryChemicalChangesTopic: TopicContent = {
  slug: "chemistry-chemical-changes",
  subject: "Chemistry",
  subjectSlug: "gcse-science/chemistry",
  title: "GCSE Chemistry: Chemical Changes",
  description: "AQA GCSE Chemistry — Chemical Changes. Covers reactivity series of metals, extraction of metals (reduction, electrolysis), reactions of acids with metals/bases/carbonates, pH scale and neutralisation, and electrolysis of molten/aqueous compounds.",
  glyphs: ["⚗️","🧪","⚛️","🔥"],
  subtopics: [
    {
      id: "reactivity-series-and-metal-reactions",
      title: "Reactivity series and metal reactions",
      tier: "Foundation",
      objective: "Identify the reactivity series and predict simple reactions of metals with acids and water.",
      whyMatters: "Understanding reactivity helps predict which metals will displace others in reactions, a common exam topic.",
      conceptTitle: "Reactivity series basics",
      conceptBullets: ["The <b style=\"color:#C9A24B\">reactivity series</b> orders metals from most to least reactive, e.g., K > Na > Ca > Mg > Al > Zn > Fe > Cu > Ag > Au.","A metal higher in the series will <b style=\"color:#C9A24B\">displace</b> a lower metal from its compound solution.","Metals above hydrogen in the series react with <b style=\"color:#C9A24B\">acids</b> to produce a salt and hydrogen gas.","Only the most reactive metals (e.g., K, Na, Ca) react vigorously with <b style=\"color:#C9A24B\">cold water</b>.","Metals below hydrogen do not react with acids or water under normal conditions."],
      conceptNote: "<b>Tip:</b> Memorise the series in order and note the position of hydrogen to decide if a metal reacts with acid.",
      glossary: [{"term":"reactivity series","def":"A list ranking metals by their tendency to lose electrons and react."},{"term":"displacement","def":"A reaction where a more reactive metal replaces a less reactive one in a compound."},{"term":"hydrogen displacement","def":"When a metal reacts with acid to release H₂ gas."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryChemicalChangesReactivitySeriesAndMetalReactionsDemo,
      worked: {"question":"Zinc metal is added to a solution of copper(II) sulphate. Write the balanced equation and state which metal is displaced.","fastMethod":"Check the series: Zn is above Cu, so Zn will displace Cu.","steps":["Write Zn + CuSO₄ → ?","Swap the metals: ZnSO₄ + Cu","Balance: Zn + CuSO₄ → ZnSO₄ + Cu","State that copper is displaced."],"answer":"Zn + CuSO₄ → ZnSO₄ + Cu; copper is displaced."},
      selfCheck: {"prompt":"True or false: Iron will react with dilute hydrochloric acid to produce hydrogen gas.","answer":"True – iron is above hydrogen in the series."},
      questions: [{"id":"reactivity-series-and-metal-reactions-q1","prompt":"Which metal will react with dilute HCl to give hydrogen gas: copper or magnesium?","accept":["magnesium","mg"],"hint":"Check their positions relative to hydrogen."},{"id":"reactivity-series-and-metal-reactions-q2","prompt":"State what happens when aluminium is placed in copper(II) nitrate solution.","accept":["aluminium displaces copper","aluminium metal is oxidised and copper precipitates"],"hint":"Use the reactivity series."},{"id":"reactivity-series-and-metal-reactions-q3","prompt":"Why does gold not react with acids?","accept":["gold is below hydrogen","gold is least reactive"],"hint":"Look at its position in the series."}],
      mistakes: ["Confusing the direction of displacement (thinking lower metals replace higher ones).","Including metals below hydrogen as reacting with acids."],
      examTip: "When asked which metal will react, always compare their positions in the reactivity series first.",
      searchTerms: ["reactivity series","metal displacement","acid metal reaction","hydrogen displacement","water reacting metals"],
    },
    {
      id: "extraction-and-reduction-of-metals",
      title: "Extraction and reduction of metals",
      tier: "Standard",
      objective: "Explain how metals are extracted by reduction and electrolysis and identify suitable methods for different metals.",
      whyMatters: "Extraction methods are tested in both written and practical questions, requiring knowledge of when to use reduction versus electrolysis.",
      conceptTitle: "Extraction techniques",
      conceptBullets: ["Metals high in the series (e.g., K, Na) are extracted by <b style=\"color:#C9A24B\">electrolysis of molten salts</b> because they are too reactive for chemical reduction.","Metals lower in the series (e.g., Fe, Cu) are extracted by <b style=\"color:#C9A24B\">reduction with carbon</b> or carbon monoxide in a blast furnace.","Very unreactive metals (e.g., Au, Ag) are obtained by <b style=\"color:#C9A24B\">electrolysis of aqueous solutions</b> or by chemical precipitation.","The choice of method depends on the metal's position in the series and the stability of its oxide or ore.","During electrolysis, the metal cation moves to the <b style=\"color:#C9A24B\">cathode</b> and gains electrons to form the pure metal."],
      conceptNote: "<b>Tip:</b> Link the metal’s reactivity to the energy required for reduction – the more reactive, the more energy‑intensive the method.",
      glossary: [{"term":"electrolysis","def":"Using electricity to drive a non‑spontaneous redox reaction."},{"term":"reduction","def":"Gain of electrons; in extraction, metal ions gain electrons to become metal."},{"term":"blast furnace","def":"A high‑temperature furnace where iron ore is reduced by carbon."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: ChemistryChemicalChangesExtractionAndReductionOfMetalsDemo,
      worked: {"question":"Calculate the mass of iron produced when 100 g of Fe₂O₃ is reduced by carbon according to: Fe₂O₃ + 3C → 2Fe + 3CO. (MFe = 56 g mol⁻¹, MFe₂O₃ = 160 g mol⁻¹)","fastMethod":"Use mole ratio 1 mol Fe₂O₃ → 2 mol Fe, then convert to mass.","steps":["Moles Fe₂O₃ = 100 g ÷ 160 g mol⁻¹ = 0.625 mol.","Moles Fe produced = 0.625 mol × 2 = 1.25 mol.","Mass Fe = 1.25 mol × 56 g mol⁻¹ = 70 g."],"answer":"70 g of iron"},
      selfCheck: {"prompt":"True or false: Aluminium is extracted by electrolysis of its molten oxide.","answer":"False – aluminium is extracted by electrolysis of molten aluminium oxide (cryolite mixture), not by simple reduction."},
      questions: [{"id":"extraction-and-reduction-of-metals-q1","prompt":"Which extraction method is used for copper?","accept":["reduction with carbon","carbon reduction"],"hint":"Consider its position in the reactivity series."},{"id":"extraction-and-reduction-of-metals-q2","prompt":"Name the electrode where metal is deposited during electrolysis.","accept":["cathode"],"hint":"Think of reduction."},{"id":"extraction-and-reduction-of-metals-q3","prompt":"Why can't iron be extracted by molten‑salt electrolysis?","accept":["too low reactivity","iron is less reactive than carbon"],"hint":"Compare reactivity with carbon."}],
      mistakes: ["Mixing up the products of carbon reduction (CO vs CO₂).","Assuming all metals are extracted by the same method regardless of reactivity."],
      examTip: "When a question asks for the most suitable extraction method, always start by locating the metal on the reactivity series.",
      searchTerms: ["metal extraction","blast furnace reduction","molten salt electrolysis","gold refining","cathode deposition"],
    },
    {
      id: "acid-base-reactions-ph-and-electrolysis-of-solutions",
      title: "Acid‑base reactions, pH and electrolysis of solutions",
      tier: "Extension",
      objective: "Analyse acid‑base reactions, calculate pH, and describe electrolysis of aqueous compounds including gas evolution.",
      whyMatters: "These concepts integrate quantitative pH work, gas collection, and electrolysis – all appear in higher‑tier exam questions.",
      conceptTitle: "Acid‑base and electrolysis fundamentals",
      conceptBullets: ["Acids react with <b style=\"color:#C9A24B\">metals</b> to give a salt and H₂ gas; bases react with acids to form a salt and H₂O.","The <b style=\"color:#C9A24B\">pH scale</b> runs from 0 (strong acid) to 14 (strong base); pH = –log[H⁺].","Neutralisation is the reaction <b style=\"color:#C9A24B\">acid + base → salt + water</b>, often accompanied by heat.","Electrolysis of aqueous solutions can produce <b style=\"color:#C9A24B\">different products at each electrode</b> depending on ion reduction potentials.","For water electrolysis, H₂ forms at the cathode and O₂ at the anode; in salts, the more easily reduced ion is discharged."],
      conceptNote: "<b>Tip:</b> When calculating pH, first find [H⁺] from the acid concentration, then apply the log formula; remember to consider dilution if required.",
      glossary: [{"term":"pH","def":"Negative logarithm of the hydrogen ion concentration, indicating acidity."},{"term":"neutralisation","def":"Reaction between an acid and a base producing a salt and water."},{"term":"electrolysis","def":"Use of electricity to cause a non‑spontaneous redox reaction in a solution or melt."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryChemicalChangesAcidBaseReactionsPhAndElectrolysisOfSolutionsDemo,
      worked: {"question":"A 0.025 M solution of HCl is prepared. Calculate its pH and state whether it is acidic, neutral or basic.","fastMethod":"Use pH = –log[H⁺] directly for a strong acid.","steps":["Identify [H⁺] = 0.025 M (since HCl fully dissociates).","pH = –log(0.025) ≈ 1.60.","pH < 7, so the solution is acidic."],"answer":"pH ≈ 1.6; the solution is acidic."},
      selfCheck: {"prompt":"True or false: During electrolysis of copper(II) sulphate solution, copper metal deposits at the cathode.","answer":"True – Cu²⁺ is reduced to Cu at the cathode."},
      questions: [{"id":"acid-base-reactions-ph-and-electrolysis-of-solutions-q1","prompt":"Write the balanced equation for the reaction of magnesium with dilute sulphuric acid.","accept":["mg + h2so4 → mgso4 + h2","mg + h2so4 -> mgso4 + h2"],"hint":"Mg is above hydrogen in the series."},{"id":"acid-base-reactions-ph-and-electrolysis-of-solutions-q2","prompt":"What gas is produced at the anode when aqueous NaCl is electrolysed?","accept":["chlorine","cl2"],"hint":"Consider the oxidation of chloride ions."},{"id":"acid-base-reactions-ph-and-electrolysis-of-solutions-q3","prompt":"Calculate the volume of H₂ gas formed at STP when 0.5 mol of HCl reacts with excess Zn.","accept":["11.2 l","11.2 litres"],"hint":"Use 1 mol gas = 22.4 L and the stoichiometry Zn + 2HCl → ZnCl₂ + H₂."}],
      mistakes: ["Using pOH instead of pH when asked for acidity.","Assuming the anode always produces O₂ in aqueous electrolysis, ignoring halide oxidation."],
      examTip: "For electrolysis questions, first list possible ions, then decide which has the highest reduction potential for the cathode and which is oxidised at the anode.",
      searchTerms: ["pH calculation","acid metal reaction","neutralisation heat","electrolysis products","gas evolution electrolysis"],
    }
  ],
};
