import type { TopicContent } from "../types";
import { ChemistryRateExtentOfChangeFactorsThatAffectReactionRateDemo, ChemistryRateExtentOfChangeCollisionTheoryInDetailDemo, ChemistryRateExtentOfChangeReversibleReactionsAndDynamicEquilibriumDemo } from "../notes-diagrams/chemistry-rate-extent-of-change-demos";

export const chemistryRateExtentOfChangeTopic: TopicContent = {
  slug: "chemistry-rate-extent-of-change",
  subject: "Chemistry",
  subjectSlug: "gcse-science/chemistry",
  title: "GCSE Chemistry: Rate and Extent of Chemical Change",
  description: "AQA GCSE Chemistry — Rate and Extent of Chemical Change. Covers factors affecting rate of reaction (concentration, temperature, surface area, catalysts), collision theory, and reversible reactions and dynamic equilibrium.",
  glyphs: ["⚗️","🧪","⚛️","🔥"],
  subtopics: [
    {
      id: "factors-that-affect-reaction-rate",
      title: "Factors that affect reaction rate",
      tier: "Foundation",
      objective: "Identify how concentration, temperature, surface area and catalysts influence the speed of a chemical reaction.",
      whyMatters: "Understanding these factors helps predict how quickly reactions occur, a common exam scenario in AQA.",
      conceptTitle: "What changes the rate?",
      conceptBullets: ["Increasing the <b style=\"color:#C9A24B\">concentration</b> of reactants raises the number of effective collisions per unit time.","Raising the <b style=\"color:#C9A24B\">temperature</b> gives particles more kinetic energy, increasing both collision frequency and the proportion with energy above the activation energy.","A larger <b style=\"color:#C9A24B\">surface area</b> exposes more particles to collide, especially important for solids.","A <b style=\"color:#C9A24B\">catalyst</b> provides an alternative pathway with a lower activation energy, speeding the reaction without being consumed."],
      conceptNote: "<b>Tip:</b> When answering exam questions, link each factor to the collision theory language of frequency and energy.",
      glossary: [{"term":"collision theory","def":"Explains that reactions occur when particles collide with sufficient energy and proper orientation."},{"term":"activation energy","def":"The minimum energy required for a collision to lead to a successful reaction."},{"term":"catalyst","def":"A substance that increases reaction rate by lowering activation energy, remaining unchanged after the reaction."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryRateExtentOfChangeFactorsThatAffectReactionRateDemo,
      worked: {"question":"If the concentration of reactant A is increased from 0.5 mol dm⁻³ to 1.0 mol dm⁻³, how does the rate of a first‑order reaction change?","fastMethod":"For a first‑order reaction, rate is directly proportional to concentration.","steps":["Identify the reaction order (first‑order → rate ∝ [A]).","Calculate the ratio of new to original concentration: 1.0 / 0.5 = 2.","Conclude the rate doubles."],"answer":"The rate doubles."},
      selfCheck: {"prompt":"True or false: Adding a catalyst changes the equilibrium constant of a reaction.","answer":"False – a catalyst speeds the approach to equilibrium but does not alter K."},
      questions: [{"id":"factors-that-affect-reaction-rate-q1","prompt":"Name one way temperature influences reaction rate.","accept":["increases kinetic energy","more particles have energy above activation energy"],"hint":"Think about particle motion."},{"id":"factors-that-affect-reaction-rate-q2","prompt":"What term describes the minimum energy needed for a successful collision?","accept":["activation energy","ea"],"hint":"Often written as Ea."},{"id":"factors-that-affect-reaction-rate-q3","prompt":"A powdered solid reacts faster than a block of the same material. Explain using collision theory.","accept":["greater surface area gives more collisions","more particles exposed"],"hint":"Consider number of particles available to collide."}],
      mistakes: ["Confusing a catalyst with a reactant and assuming it appears in the balanced equation.","Treating temperature increase as always doubling the rate, rather than recognising the approximate 2‑fold increase in particles with energy ≥ Ea for a 10 °C rise."],
      examTip: "When a question lists several changes, mark each with ‘↑ frequency’ or ‘↑ energy’ to avoid missing a factor.",
      searchTerms: ["reaction rate factors","collision theory GCSE","catalyst effect","temperature and rate","surface area reaction"],
    },
    {
      id: "collision-theory-in-detail",
      title: "Collision theory in detail",
      tier: "Standard",
      objective: "Explain how frequency, orientation and energy of collisions determine whether a reaction occurs.",
      whyMatters: "AQA frequently asks students to apply collision theory to predict the effect of experimental changes.",
      conceptTitle: "When do collisions work?",
      conceptBullets: ["Effective collisions must have energy ≥ <b style=\"color:#C9A24B\">activation energy</b>.","Molecules must adopt the correct <b style=\"color:#C9A24B\">orientation</b> for bonds to break and form.","Increasing <b style=\"color:#C9A24B\">frequency</b> of collisions raises the chance of effective collisions.","A <b style=\"color:#C9A24B\">catalyst</b> provides an alternative pathway, changing the orientation requirement and lowering Ea."],
      conceptNote: "<b>Tip:</b> In exam diagrams, label arrows showing increased frequency or energy to earn marks.",
      glossary: [{"term":"effective collision","def":"A collision that has both sufficient energy and proper orientation to lead to reaction."},{"term":"orientation factor","def":"The proportion of collisions that have the correct alignment of reacting particles."},{"term":"frequency of collisions","def":"Number of collisions per unit time, influenced by concentration, temperature and surface area."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: ChemistryRateExtentOfChangeCollisionTheoryInDetailDemo,
      worked: {"question":"At 25 °C, 5 % of collisions have energy ≥ Ea. If the temperature is raised so that 10 % of collisions meet this criterion, how does the rate change, assuming orientation remains constant?","fastMethod":"Rate change ≈ change in the proportion of effective collisions.","steps":["Identify initial effective fraction = 0.05.","Identify new effective fraction = 0.10.","Calculate ratio: 0.10 / 0.05 = 2.","State the rate doubles."],"answer":"The reaction rate doubles."},
      selfCheck: {"prompt":"True or false: All collisions at high temperature are effective.","answer":"False – collisions still need correct orientation."},
      questions: [{"id":"collision-theory-in-detail-q1","prompt":"What two conditions must a collision meet to be effective?","accept":["sufficient energy and correct orientation","energy ≥ activation energy and proper orientation"],"hint":"Think of the two words in the term ‘effective collision’."},{"id":"collision-theory-in-detail-q2","prompt":"How does a catalyst affect the orientation requirement?","accept":["it may change the required orientation","different orientation needed on the new pathway"],"hint":"Consider the alternative pathway."},{"id":"collision-theory-in-detail-q3","prompt":"If concentration is quadrupled, what happens to collision frequency (all else equal)?","accept":["quadruples","increases fourfold"],"hint":"Frequency is directly proportional to concentration."}],
      mistakes: ["Assuming higher temperature automatically improves orientation.","Treating the catalyst as changing the overall equilibrium constant rather than just Ea."],
      examTip: "When asked why a change speeds a reaction, explicitly mention both increased frequency and increased proportion of collisions with energy ≥ Ea.",
      searchTerms: ["effective collisions","orientation factor","collision frequency","catalyst pathway","activation energy GCSE"],
    },
    {
      id: "reversible-reactions-and-dynamic-equilibrium",
      title: "Reversible reactions and dynamic equilibrium",
      tier: "Extension",
      objective: "Analyse how forward and reverse rates balance and predict how changes shift the equilibrium position.",
      whyMatters: "AQA exam questions often require applying Le Chatelier’s principle to reversible reactions, a key extension skill.",
      conceptTitle: "Balancing forward and reverse",
      conceptBullets: ["In a <b style=\"color:#C9A24B\">reversible reaction</b>, forward and reverse reactions occur simultaneously.","When rates are equal, the system is at <b style=\"color:#C9A24B\">dynamic equilibrium</b>; concentrations remain constant but reactions continue.","Changing <b style=\"color:#C9A24B\">concentration, temperature or pressure</b> disturbs the balance, and the system shifts to restore equilibrium (Le Chatelier).","A <b style=\"color:#C9A24B\">catalyst</b> speeds both forward and reverse reactions equally, so it does not shift the equilibrium position."],
      conceptNote: "<b>Tip:</b> Draw the reaction arrow both ways and label ‘↑ rate’ on the side that is favoured after a change.",
      glossary: [{"term":"dynamic equilibrium","def":"State where forward and reverse reaction rates are equal, giving constant concentrations."},{"term":"Le Chatelier’s principle","def":"When a stress is applied to a system at equilibrium, the system adjusts to minimise that stress."},{"term":"reaction quotient (Q)","def":"Ratio of product and reactant concentrations at any moment; compared with K to predict shift direction."}],
      diagramLabel: "Try it: Key facts",
      Diagram: ChemistryRateExtentOfChangeReversibleReactionsAndDynamicEquilibriumDemo,
      worked: {"question":"For the exothermic reaction N₂(g) + 3H₂(g) ⇌ 2NH₃(g), what will happen to the equilibrium position if the system is heated?","fastMethod":"Identify reaction as exothermic; heat adds stress to the product side.","steps":["Recognise forward reaction releases heat (exothermic).","Adding heat is equivalent to adding product.","Le Chatelier predicts shift towards reactants.","Thus, NH₃ concentration decreases, N₂ and H₂ increase."],"answer":"Equilibrium shifts to the left (towards N₂ and H₂)."},
      selfCheck: {"prompt":"True or false: Adding a catalyst to a system at equilibrium changes the value of K.","answer":"False – a catalyst speeds both directions equally, leaving K unchanged."},
      questions: [{"id":"reversible-reactions-and-dynamic-equilibrium-q1","prompt":"Define dynamic equilibrium in one sentence.","accept":["forward and reverse rates equal, concentrations constant","rates equal, no net change"],"hint":"Mention rates and concentrations."},{"id":"reversible-reactions-and-dynamic-equilibrium-q2","prompt":"If pressure is increased on a gaseous equilibrium with more moles of gas on the reactant side, which direction does the system shift?","accept":["towards products","right"],"hint":"Fewer gas moles are favoured."},{"id":"reversible-reactions-and-dynamic-equilibrium-q3","prompt":"Calculate the reaction quotient Q for the reaction A ⇌ B when [A]=0.2 M and [B]=0.5 M, given K=2.0. Will the reaction proceed forward or reverse?","accept":["forward","to the right"],"hint":"Q = [B]/[A]; compare with K."}],
      mistakes: ["Confusing the effect of temperature on K with the direction of shift; heating an exothermic reaction lowers K and shifts left.","Assuming a catalyst changes the position of equilibrium rather than just the rate of attainment."],
      examTip: "Always compare Q with K first; if Q<K the reaction will proceed forward to reach equilibrium.",
      searchTerms: ["dynamic equilibrium GCSE","Le Chatelier principle","equilibrium shift temperature","pressure effect equilibrium","reaction quotient vs K"],
    }
  ],
};
