import type { TopicContent } from "../types";
import {
  WhatIsACodeQuestionDemo,
  AlphabetPositionShiftDemo,
  TwoWayCodeTranslationDemo,
  LetterValueSumDemo,
  CombinedRuleCodeDemo,
  CodeSpeedDrillDemo,
} from "../notes-diagrams/codes-essentials-demos";

export const codesEssentialsTopic: TopicContent = {
  slug: "codes-essentials",
  subject: "VR",
  subjectSlug: "verbal-reasoning",
  title: "Codes Essentials",
  glyphs: ["A", "=", "1", "→", "?", "#"],
  description:
    "Letter-and-number code questions test a completely different skill from word relationships — not vocabulary, but calm, systematic working. Most students already know the techniques; what usually goes wrong is doing the steps in your head under time pressure instead of on paper. This module builds the core code formats from the ground up, then finishes with a dedicated working-method module aimed at making codes feel fast and mechanical instead of fiddly.",
  subtopics: [
    {
      id: "what-is-a-code-question",
      title: "What Is a Code Question?",
      tier: "Foundation",
      objective: "Recognise the two core code-question formats and the one habit that makes both of them reliable.",
      whyMatters: "code questions are some of the most reliably correct marks on a GL Verbal Reasoning paper once you stop trying to do them from memory — but they're also where a rushed, in-your-head guess costs an easy mark.",
      conceptTitle: "Two formats, one shared foundation",
      conceptBullets: [
        '<b style="color:#C9A24B">Letter-position codes</b> assign each letter a fixed number, almost always A=1, B=2, C=3... up to Z=26.',
        '<b style="color:#C9A24B">Letter-shift codes</b> move every letter a fixed number of places along the alphabet (for example, every letter coded as the one 3 places later).',
        "Every code question — however complicated it looks — is built from these two basic ideas, sometimes combined or applied more than once.",
        "The single biggest difference between students who find codes quick and students who find them annoying isn't knowledge — it's whether they write the alphabet key down before starting, every single time.",
      ],
      conceptNote: "<b>Golden rule:</b> before answering, write A B C D E F G H I J... along the margin (with numbers underneath if needed). This takes five seconds and turns every code question into a lookup instead of a mental calculation.",
      glossary: [
        { term: "letter-position code", def: "a code where each letter is assigned a fixed number, usually A=1...Z=26" },
        { term: "letter-shift code", def: "a code where every letter is moved a fixed number of places along the alphabet" },
        { term: "key", def: "the written-out alphabet (with positions/numbers) you build before answering, so you're reading, not recalculating" },
        { term: "decode", def: "to work out the original letter/word/number from its coded form" },
      ],
      diagramLabel: "Interactive · Codes & Ciphers",
      Diagram: WhatIsACodeQuestionDemo,
      worked: {
        question: "If A=1, B=2, C=3... what number codes the letter 'G'?",
        fastMethod: "Write out A to G with numbers underneath, then read off G's number directly.",
        steps: [
          "Write the alphabet from A, stopping once you reach the letter you need: A B C D E F G.",
          "Write the position number under each letter, starting at 1: 1 2 3 4 5 6 7.",
          "Read the number written under G.",
          "G sits in position 7.",
        ],
        answer: 'The answer is <b>7</b>.',
      },
      selfCheck: { prompt: "True or false: it's faster to count a letter's alphabet position in your head than to write the key out first.", answer: "<b>False</b> — it feels faster, but it's where most careless code mistakes happen; writing the key first is barely slower and far more reliable, especially past letter M." },
      questions: [
        { id: "wiacq-q1", prompt: "If A=1, B=2, C=3... what number codes the letter 'D'?", accept: ["4"], hint: "count A, B, C, D on paper — don't guess from memory." },
        { id: "wiacq-q2", prompt: "If A=1, B=2, C=3... what number codes the letter 'K'?", accept: ["11"], hint: "write out the alphabet in groups of 5 (A-E, F-J, K-O) so you don't lose count past J." },
        { id: "wiacq-q3", prompt: "If every letter is coded as the one 1 place later in the alphabet (A→B, B→C...), what does 'M' become?", accept: ["N"], hint: "this is a shift code, not a position-number code — find the next letter, not a number." },
      ],
      mistakes: [
        "Counting a letter's alphabet position in your head and losing count somewhere past J or M.",
        "Mixing up a position-number code (A=1) with a shift code (A→B) because both use 'A' and both feel similar under time pressure.",
      ],
      examTip: "Write the full alphabet with position numbers underneath in the margin the moment you see a code question — even if the first question feels easy enough to skip it.",
      searchTerms: ["codes", "ciphers", "letter code", "alphabet position", "verbal reasoning", "A=1"],
    },
    {
      id: "alphabet-position-shift-codes",
      title: "Alphabet-Position Shift Codes",
      tier: "Foundation",
      objective: "Apply a fixed forward or backward shift to any letter, quickly and accurately.",
      whyMatters: "shift codes appear constantly across GL papers, and once you can apply a shift without recounting from A every time, they become some of the fastest marks available.",
      conceptTitle: "Moving along the alphabet by a fixed number of places",
      conceptBullets: [
        '<b style="color:#C9A24B">Shift codes</b> move every letter the same number of places forward or backward along the alphabet.',
        "Always check the direction first — 'later in the alphabet' means forward (A→B→C...), 'earlier in the alphabet' means backward (C→B→A...).",
        "For small shifts (1-4 places), write out the letters between the start and end point one at a time rather than jumping straight to an answer.",
        "For larger shifts, use position numbers instead: find the starting letter's number, add or subtract the shift, then convert the new number back to a letter.",
      ],
      conceptNote: "<b>Two methods, pick by shift size:</b> for a shift of 1-4, count letter by letter; for a shift of 5+, convert to numbers, do the sum, then convert back — trying to count 7 letters forward in your head is exactly where mistakes creep in.",
      glossary: [
        { term: "shift", def: "the fixed number of places every letter moves along the alphabet" },
        { term: "forward shift", def: "moving later in the alphabet, e.g. A→B→C" },
        { term: "backward shift", def: "moving earlier in the alphabet, e.g. C→B→A" },
        { term: "wrap-around", def: "when a shift passes Z and continues from A again (rare on GL papers, but worth knowing)" },
      ],
      diagramLabel: "Interactive · Codes & Ciphers",
      Diagram: AlphabetPositionShiftDemo,
      worked: {
        question: "Each letter is coded as the letter 5 places later in the alphabet. What is the code for 'C'?",
        fastMethod: "Convert C to its position number (3), add the shift (5) to get 8, then convert 8 back to a letter (H).",
        steps: [
          "Find C's position number: C is the 3rd letter.",
          "Add the shift: 3 + 5 = 8.",
          "Convert position 8 back to a letter by counting or using a written key: the 8th letter is H.",
          "Check the direction was 'later' (forward) — it was, so adding was correct.",
        ],
        answer: 'The answer is <b>H</b>.',
      },
      selfCheck: { prompt: "True or false: for a shift of 6 or more places, counting letter by letter is the fastest reliable method.", answer: "<b>False</b> — past about 4 places, converting to numbers and doing simple addition/subtraction is both faster and far less error-prone than counting one letter at a time." },
      questions: [
        { id: "apsc-q1", prompt: "Each letter is coded as the letter 3 places later in the alphabet. What is the code for 'F'?", accept: ["I"], hint: "count F, G, H, I one place at a time — a shift of 3 is small enough to count directly." },
        { id: "apsc-q2", prompt: "Each letter is coded as the letter 4 places earlier in the alphabet. What is the code for 'J'?", accept: ["F"], hint: "the direction is backward here — check you're moving earlier in the alphabet, not later." },
        { id: "apsc-q3", prompt: "Each letter is coded as the letter 6 places later in the alphabet. What is the code for 'L'?", accept: ["R"], hint: "convert L to its position number first, add 6, then convert the result back to a letter." },
      ],
      mistakes: [
        "Shifting in the wrong direction because the question says 'earlier'/'later' and it's misread as the opposite.",
        "Counting a large shift (6+) letter by letter in the head and landing one or two letters off.",
      ],
      examTip: "For any shift of 5 or more, convert to numbers and do the sum on paper rather than counting letters — it's the single biggest speed-and-accuracy fix for this question type.",
      searchTerms: ["shift code", "cipher", "alphabet shift", "forward shift", "backward shift", "verbal reasoning"],
    },
    {
      id: "two-way-code-translation",
      title: "Word-to-Code and Code-to-Word",
      tier: "Standard",
      objective: "Use a worked example in the question itself to confirm a code's rule, then apply that rule to a new word in either direction.",
      whyMatters: "GL code questions almost always give you one solved example to work out the rule from — reading it correctly, rather than copying its numbers, is what actually earns the mark on the new word.",
      conceptTitle: "Using the example to find the rule, not the answer",
      conceptBullets: [
        "Most code questions give a worked example (e.g. 'CAT is coded 3-1-20') purely to show you what kind of code is being used.",
        "Your first job is to work out the rule from that example — is it A=1...Z=26? A shift? Something else?",
        "Once you know the rule, apply it fresh to the new word — never try to reuse or adapt the example's actual numbers.",
        "Working can go either direction: word→code (encoding) or code→word (decoding) — the rule works exactly the same way both ways round.",
      ],
      conceptNote: "<b>Common trap:</b> a coded word and the word you're asked about don't share any letters — for example, CAT tells you nothing directly about DOG's individual letters, only about which rule is being used.",
      glossary: [
        { term: "encode", def: "to convert a word into its coded form" },
        { term: "decode", def: "to convert a coded form back into the original word" },
        { term: "worked example", def: "the one solved word/code pair the question gives you, used only to find the rule" },
        { term: "rule", def: "the fixed method (position, shift, or value) that links every letter to its code" },
      ],
      diagramLabel: "Interactive · Codes & Ciphers",
      Diagram: TwoWayCodeTranslationDemo,
      worked: {
        question: "If DOG is coded 4-15-7 (using A=1...Z=26), what is the code for CAT?",
        fastMethod: "Confirm the rule is a straight A=1...Z=26 key from the example, then apply it fresh to C, A, T.",
        steps: [
          "Check the example: D=4, O=15, G=7 — these match A=1...Z=26 exactly, confirming the rule.",
          "Apply the same rule to each letter of CAT separately: C=3, A=1, T=20.",
          "Write the three numbers in the same left-to-right order as the letters.",
          "Combine into the final code.",
        ],
        answer: 'The answer is <b>3-1-20</b>.',
      },
      selfCheck: { prompt: "True or false: if DOG codes to 4-15-7, then any word sharing a letter with DOG must share a number with 4-15-7 in the same position.", answer: "<b>True, but only because this is a fixed A=1...Z=26 rule</b> — every 'D' anywhere always codes to 4 under this rule; the example just proves the rule, it isn't a special case that only applies to DOG." },
      questions: [
        { id: "twct-q1", prompt: "If BAT is coded 2-1-20 (using A=1...Z=26), what is the code for CAP?", accept: ["3-1-16"], hint: "confirm the rule from BAT first (B=2, A=1, T=20 matches A=1...Z=26), then apply it fresh to C, A, P." },
        { id: "twct-q2", prompt: "If the code 5-15-14 stands for SON (using A=1...Z=26), what word does the code 20-15-14 stand for?", accept: ["TON"], hint: "only the first number changed, from 5 to 20 — decode just that one letter and keep the other two." },
        { id: "twct-q3", prompt: "If FOX is coded 6-15-24 (using A=1...Z=26), what is the code for BOX?", accept: ["2-15-24"], hint: "FOX and BOX share two letters — you only need to work out the code for the one letter that's different." },
      ],
      mistakes: [
        "Trying to reuse or adjust the example word's exact numbers instead of applying the rule fresh to the new word.",
        "Decoding every letter of a code when only one letter has actually changed from a word already given.",
      ],
      examTip: "When two words in the same question share letters (like FOX and BOX), only work out the code for the letters that are different — it's faster and there's less to get wrong.",
      searchTerms: ["encode", "decode", "code to word", "word to code", "worked example", "verbal reasoning"],
    },
    {
      id: "letter-value-number-codes",
      title: "Letter-Value Number Codes",
      tier: "Standard",
      objective: "Calculate a word's code by summing the A=1...Z=26 values of its letters, without losing track mid-calculation.",
      whyMatters: "letter-sum codes combine a Verbal Reasoning skill with a small piece of arithmetic — exactly the kind of two-part question where writing your working down, rather than adding in your head, prevents a silly slip.",
      conceptTitle: "Turning a word into a single number",
      conceptBullets: [
        '<b style="color:#C9A24B">Letter-value codes</b> assign each letter its A=1...Z=26 value, then add every letter\'s value together to make one total.',
        "Always write each letter of the word in a row, then write its value directly underneath, before adding anything up.",
        "Add the values in a sensible order (e.g. left to right, or pairing a small number with a large one) rather than trying to hold a running total in your head.",
        "Double-check your total by re-adding once, especially on longer words where one slipped digit changes the whole answer.",
      ],
      conceptNote: "<b>Working layout:</b> letter row on top, value row underneath, running total written to the side — this exact layout is what stops a rushed mental sum from going wrong.",
      glossary: [
        { term: "letter value", def: "the A=1...Z=26 number assigned to a single letter" },
        { term: "letter-value code", def: "a code formed by adding together the values of every letter in a word" },
        { term: "running total", def: "the sum so far as you add each new letter's value" },
      ],
      diagramLabel: "Interactive · Codes & Ciphers",
      Diagram: LetterValueSumDemo,
      worked: {
        question: "Using A=1, B=2, C=3... what is the letter-value code for the word 'CAB'?",
        fastMethod: "Write C, A, B in a row with their values underneath (3, 1, 2), then add.",
        steps: [
          "Write the letters: C A B.",
          "Write each value underneath: 3 1 2.",
          "Add the values in order: 3 + 1 = 4, then 4 + 2 = 6.",
          "Check the total by re-adding: 3 + 1 + 2 = 6.",
        ],
        answer: 'The answer is <b>6</b>.',
      },
      selfCheck: { prompt: "True or false: adding letter values in your head is just as reliable as writing each value underneath its letter first.", answer: "<b>False</b> — a word of 4+ letters holds several numbers in your head at once, which is exactly where a running total slips; writing values underneath removes that memory load entirely." },
      questions: [
        { id: "lvnc-q1", prompt: "Using A=1, B=2, C=3... what is the letter-value code for the word 'DAD'?", accept: ["9"], hint: "write D, A, D in a row with 4, 1, 4 underneath, then add all three." },
        { id: "lvnc-q2", prompt: "Using A=1, B=2, C=3... what is the letter-value code for the word 'FIG'?", accept: ["20"], hint: "F=6, I=9, G=7 — write all three underneath their letters before adding." },
        { id: "lvnc-q3", prompt: "Using A=1, B=2, C=3... the word 'BED' codes to 11. What single-letter change to 'BED' would make its code 12 instead?", accept: ["change D to E", "D to E", "change the D to an E"], hint: "only one letter needs to change — find the letter whose value is exactly 1 more than D's value." },
      ],
      mistakes: [
        "Adding letter values in your head and losing track of the running total partway through a longer word.",
        "Miscounting a letter's alphabet position when working out its value, especially for letters past M.",
      ],
      examTip: "Never add more than two numbers at once in your head — write every letter's value down first, then add them in pairs.",
      searchTerms: ["letter value", "letter sum code", "A=1", "number code", "verbal reasoning", "arithmetic code"],
    },
    {
      id: "combined-rule-codes",
      title: "Multi-Step & Combined-Rule Codes",
      tier: "Extension",
      objective: "Apply two code rules in sequence, treating each step as a separate, written calculation.",
      whyMatters: "these are usually the hardest code questions on a GL paper, and where a strong student's dislike of 'fiddly' codes tends to peak — the fix isn't more practice with the rules, it's refusing to skip the written middle step.",
      conceptTitle: "One step at a time, with the middle result written down",
      conceptBullets: [
        '<b style="color:#C9A24B">Combined-rule codes</b> apply two separate operations in sequence — most often a shift followed by a value lookup, or two shifts in a row.',
        "Read the rule carefully to find the exact order the steps happen in — doing them in the wrong order gives a different, wrong answer.",
        "Do the first step completely and write down its result as a real letter or number before starting the second step.",
        "Resist the urge to combine both steps into one mental leap — it feels faster but is exactly where marks are lost on combined-rule questions.",
      ],
      conceptNote: "<b>Why these feel more annoying:</b> combined-rule codes force you to hold two rules in mind at once, which is genuinely more tiring than a single-rule code — treating it as two small, separate, written steps (rather than one big mental one) is what makes it feel manageable again.",
      glossary: [
        { term: "combined-rule code", def: "a code built from two or more operations applied in sequence" },
        { term: "intermediate result", def: "the answer to the first step, used as the input to the second step" },
        { term: "operation order", def: "the fixed sequence the two rules must be applied in" },
      ],
      diagramLabel: "Interactive · Codes & Ciphers",
      Diagram: CombinedRuleCodeDemo,
      worked: {
        question: "Rule: shift each letter forward by 2, then convert to its A=1...Z=26 value. What is the code for 'H' under this rule?",
        fastMethod: "Do the shift first and write the resulting letter down, then look up that letter's value separately.",
        steps: [
          "Step 1 — shift: H moves forward 2 places to J. Write down: H → J.",
          "Step 2 — value: find J's position number.",
          "J is the 10th letter of the alphabet.",
          "Confirm the order matches the rule (shift, then value) — it does.",
        ],
        answer: 'The answer is <b>10</b>.',
      },
      selfCheck: { prompt: "True or false: for a two-step code rule, it's fine to do both steps together as long as you're confident with each rule individually.", answer: "<b>False</b> — confidence with each rule doesn't prevent the two from blurring together mid-calculation; writing the intermediate letter down is what actually prevents the error, regardless of skill level." },
      questions: [
        { id: "crc-q1", prompt: "Rule: shift each letter back by 1, then convert to its A=1...Z=26 value. What is the code for 'E' under this rule?", accept: ["4"], hint: "shift E back by 1 to get D first, write that down, then look up D's value separately." },
        { id: "crc-q2", prompt: "Rule: convert each letter to its A=1...Z=26 value, then add 3 to that value. What is the code for 'G' under this rule?", accept: ["10"], hint: "find G's value first (write it down), then add 3 to that number as a separate step." },
        { id: "crc-q3", prompt: "Rule: shift each letter forward by 3, then shift that result forward by 2. What single letter does 'A' become?", accept: ["F"], hint: "do the two shifts one at a time, writing down the letter you land on after the first shift before starting the second." },
      ],
      mistakes: [
        "Applying the two rules in the wrong order because the question's wording wasn't read carefully enough.",
        "Skipping the written middle step and combining both operations into one mental jump, losing accuracy on the way.",
      ],
      examTip: "Split combined-rule codes into two lines of working: 'Step 1: ___ → ___' then 'Step 2: ___ → ___' — writing it exactly like that removes almost all of the difficulty.",
      searchTerms: ["combined code", "multi-step code", "two-step cipher", "operation order", "verbal reasoning"],
    },
    {
      id: "working-fast-without-losing-accuracy",
      title: "Working Fast Without Losing Accuracy",
      tier: "Extension",
      objective: "Use a small set of habits to make code questions feel quick and mechanical instead of slow and irritating.",
      whyMatters: "code questions are worth exactly the same marks as every other Verbal Reasoning question — the goal here isn't to enjoy them, it's to stop them draining time and focus that's needed for the rest of the paper.",
      conceptTitle: "Five habits that make codes faster, not slower",
      conceptBullets: [
        '<b style="color:#C9A24B">Write the key, don\'t hold it in your head</b> — a written A=1...Z=26 key turns every code question into a lookup, which is faster over a whole paper than repeatedly recounting from memory.',
        "<b style=\"color:#C9A24B\">Batch code questions together</b> — if a section mixes question types, doing all the code questions in a row (rather than switching in and out) keeps the working rhythm going instead of re-starting it each time.",
        "<b style=\"color:#C9A24B\">Tackle codes early in a practice session</b>, while concentration is freshest — irritation with a question type tends to spike once focus starts to dip, not at the start.",
        "Treat a timed set of code questions as a personal-best challenge rather than a chore — a stopwatch and a target time turns repetitive practice into something worth beating, not just repeating.",
      ],
      conceptNote: "<b>None of this is about knowing the rules better</b> — if the techniques are already solid, what actually moves the needle is the working method: external (on paper), one step at a time, and practiced in short, focused bursts rather than long, tired ones.",
      glossary: [
        { term: "external working", def: "writing every step down on paper instead of calculating in your head" },
        { term: "batching", def: "grouping the same question type together instead of switching between types" },
        { term: "personal best", def: "your own fastest accurate time on a set of questions, used as a target to beat" },
      ],
      diagramLabel: "Interactive · Codes & Ciphers",
      Diagram: CodeSpeedDrillDemo,
      worked: {
        question: "Timed drill: using a pre-written A=1...Z=26 key, what is the code for 'P'?",
        fastMethod: "Read the value straight off your written key instead of recalculating it.",
        steps: [
          "Locate P on the alphabet key already written down the margin.",
          "Read the number directly underneath P.",
          "P is the 16th letter.",
          "No recalculation needed — the key does the work.",
        ],
        answer: 'The answer is <b>16</b>.',
      },
      selfCheck: { prompt: "True or false: the students who find code questions fastest are usually the ones who've memorised the alphabet positions of every letter.", answer: "<b>False</b> — the fastest reliable approach is a written key used as a lookup, not memorisation; memorising invites the exact same recall errors as counting from A each time, just with more false confidence." },
      questions: [
        { id: "wfwla-q1", prompt: "You have 8 code questions in a row on a paper. Should you answer them in order as they appear, or is there a better approach if some are mixed with other question types nearby?", accept: ["answer the code questions together", "do them in a batch", "group the code questions and do them together", "batch them"], hint: "think about what keeps your working rhythm going rather than restarting it each time you switch question type." },
        { id: "wfwla-q2", prompt: "True or false (one word): writing a key first is a waste of time on a code question you find easy.", accept: ["false"], hint: "the key takes seconds and prevents exactly the kind of slip that happens on 'easy' questions done from memory." },
        { id: "wfwla-q3", prompt: "Under time pressure and getting frustrated with a code question, what's the single most useful physical habit to fall back on?", accept: ["write it down", "write out the working", "write the key", "write the steps down on paper"], hint: "the fix here is physical, not mental — think about what to put on the page, not what to think harder about." },
      ],
      mistakes: [
        "Treating dislike of a question type as a sign to rush through it faster, when slowing down by writing the key is what actually speeds up the whole set.",
        "Practising code questions only in long, tired blocks, which reinforces the feeling that they're a slog rather than a quick, repeatable skill.",
      ],
      examTip: "In practice sessions, time yourself on a small batch of code questions (5-6) and try to beat your own previous time — treating it as a beatable challenge changes how it feels far more than more repetition of the same untimed drills.",
      searchTerms: ["working method", "exam technique", "speed and accuracy", "timed practice", "verbal reasoning strategy", "code questions"],
    },
  ],
};
