import type { TopicContent } from "../types";
import {
  TheirThereTheyreDemo,
  YourYoureDemo,
  AffectEffectDemo,
  FewerLessDemo,
  PracticePractiseDemo,
  IntensivePurposesDemo,
  GonnaFormalDemo,
  LooseLoseDemo,
  ComplementComplimentDemo,
  MixedReviewDemo,
} from "../notes-diagrams/confused-words-demos";

const CLICK_INSTRUCTION = "Click the word used incorrectly.";

export const commonlyConfusedWordsTopic: TopicContent = {
  slug: "commonly-confused-words",
  subject: "English",
  subjectSlug: "english",
  title: "Grammar: Commonly Confused Words",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "GL and CSSE-style “spot the mistake” questions love word-choice traps: words that sound identical, look almost identical, or simply get muddled in everyday speech. This module works through homophones, near-homophones, subtle meaning differences, spelling look-alikes and formal word choice — training you to hear the difference an exam wants you to see.",
  subtopics: [
    {
      id: "homophones-there-to",
      title: "Homophones: their / there / they're, to / too / two",
      tier: "Foundation",
      objective: "Tell apart the three spellings of “there” and the three spellings of “to”, and choose the right one for the job it's doing.",
      whyMatters: "these six words are among the most frequently tested word-choice errors on GL-style papers because they sound completely identical when read aloud.",
      conceptTitle: "Same sound, different job",
      conceptBullets: [
        'A <b style="color:#C9A24B">homophone</b> is a word that sounds exactly like another word but has a different spelling and meaning.',
        '<b>their</b> shows ownership (<i>their coats</i>); <b>there</b> shows place (<i>over there</i>); <b>they\'re</b> is short for “they are” (<i>they\'re late</i>).',
        '<b>to</b> shows direction or comes before a verb (<i>go to school</i>, <i>to run</i>); <b>too</b> means “also” or “excessively” (<i>me too</i>, <i>too loud</i>); <b>two</b> is the number 2.',
        "Because these words sound identical, spot-the-mistake questions can only be solved by checking the job the word is doing, never by how it sounds.",
      ],
      conceptNote: "<b>Test it:</b> try replacing “they're” with “they are” in the sentence — if it still makes sense, “they're” is correct; if not, try “their” or “there” instead.",
      glossary: [
        { term: "homophone", def: "a word that sounds the same as another but differs in spelling and meaning" },
        { term: "possessive", def: "shows ownership (their)" },
        { term: "contraction", def: "a shortened form of two words (they're = they are)" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: TheirThereTheyreDemo,
      worked: {
        question: "Spot the error: “The players collected there kit bags before boarding the coach.”",
        fastMethod: 'Test it with "they are": "collected they are kit bags" makes no sense, and the word is showing ownership, so it needs "their".',
        steps: [
          "Find the word that sounds like “their/there/they're”: “there”.",
          "Ask what job it's doing — here it shows who the kit bags belong to.",
          "“There” shows place, not ownership; the possessive form is “their”.",
          "Corrected: “The players collected their kit bags…”",
        ],
        answer: "The error is <b>there</b> — it should be <b>their</b>.",
      },
      selfCheck: { prompt: "True or false: in “Put the box over their”, “their” is correct.", answer: "<b>False</b> — the sentence describes a place, so it needs “there”. “Their” shows ownership, which doesn't fit here." },
      kind: "click-error",
      questions: [
        {
          id: "hom1-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "boys", "left", "there", "lunches", "on", "the", "bus", "by", "accident."],
          errorIdx: 3,
          correction: '"there" shows place, but this sentence shows ownership — it needs "their": their lunches.',
          hint: "Check who the lunches belong to.",
        },
        {
          id: "hom1-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Their", "going", "to", "the", "museum", "after", "lunch", "today."],
          errorIdx: 0,
          correction: '"Their" shows ownership, but here the word means "they are" before the verb "going" — it needs "They\'re": They\'re going.',
          hint: "Try replacing the first word with “they are” and see if it still makes sense.",
        },
        {
          id: "hom1-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["He", "wanted", "to", "go", "to", "the", "party", "to."],
          errorIdx: 7,
          correction: '"to" cannot mean "also" — the final word should be "too": …the party too.',
          hint: "The very last word should mean “as well”, not show direction.",
        },
      ],
      mistakes: [
        "Choosing between their/there/they're by how the sentence sounds rather than by testing “they are” or checking for ownership.",
        "Using “to” at the end of a sentence when the intended meaning is “also” — that always needs “too”.",
      ],
      examTip: "For there/their/they're, silently swap in “they are” — if that works, it's “they're”; if not, decide between place (“there”) and ownership (“their”).",
      searchTerms: ["homophone", "their", "there", "they're", "to", "too", "two", "spot the mistake"],
    },
    {
      id: "homophones-your-its-here",
      title: "Homophones: your / you're, its / it's, here / hear",
      tier: "Foundation",
      objective: "Extend the same possessive-vs-contraction test to your/you're and its/it's, and tell here (place) apart from hear (sound).",
      whyMatters: "its/it's is one of the single most commonly misused word pairs in English, tripping up even confident writers under exam time pressure.",
      conceptTitle: "More sound-alike traps",
      conceptBullets: [
        '<b>your</b> shows ownership (<i>your book</i>); <b>you\'re</b> is short for “you are” (<i>you\'re late</i>).',
        '<b>its</b> shows ownership with <i>no apostrophe</i> (<i>the dog wagged its tail</i>); <b>it\'s</b> is short for “it is” or “it has” (<i>it\'s raining</i>).',
        '<b>here</b> means “in this place” (<i>come here</i>); <b>hear</b> means “to perceive sound” (<i>I can hear you</i>).',
        "The your/you're and its/it's pairs follow exactly the same possessive-vs-contraction pattern as their/they're — apostrophe words are always a shortened phrase.",
      ],
      conceptNote: "<b>Remember:</b> a possessive pronoun (your, its, their) never takes an apostrophe — if you see one, the word is a contraction instead.",
      glossary: [
        { term: "possessive pronoun", def: "shows ownership, never has an apostrophe (your, its)" },
        { term: "contraction", def: "a shortened pair of words joined with an apostrophe (you're, it's)" },
        { term: "homophone", def: "sounds the same, spelled differently, different meaning" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: YourYoureDemo,
      worked: {
        question: "Spot the error: “The cat licked it's paw before curling up on the chair.”",
        fastMethod: 'Test it: "the cat licked it is paw" makes no sense — the word shows ownership, so it needs "its" with no apostrophe.',
        steps: [
          "Find the word that sounds like “its/it's”: “it's”.",
          "Test it by expanding the apostrophe: “it is paw” doesn't make sense.",
          "Since the word shows ownership of the paw, it needs the possessive form, which has no apostrophe.",
          "Corrected: “The cat licked its paw…”",
        ],
        answer: "The error is <b>it's</b> — it should be <b>its</b>.",
      },
      selfCheck: { prompt: "Which is correct: “Come and sit hear” or “Come and sit here”?", answer: "<b>“Come and sit here”</b> — the sentence describes a place, and “hear” means to perceive sound, which doesn't fit." },
      kind: "click-error",
      questions: [
        {
          id: "hom2-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Your", "going", "to", "love", "this", "present."],
          errorIdx: 0,
          correction: '"Your" shows ownership, but here it means "you are" before the verb "going" — it needs "You\'re": You\'re going.',
          hint: "Try replacing the first word with “you are”.",
        },
        {
          id: "hom2-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Its", "raining", "again", "so", "bring", "an", "umbrella."],
          errorIdx: 0,
          correction: '"Its" shows ownership, but here the word means "it is" before "raining" — it needs "It\'s": It\'s raining.',
          hint: "Try expanding the first word to “it is” and check if it still makes sense.",
        },
        {
          id: "hom2-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Please", "come", "and", "sit", "hear", "next", "to", "me."],
          errorIdx: 4,
          correction: '"hear" means to perceive sound, but this sentence describes a place — it needs "here": sit here.',
          hint: "Is this word about sound, or about where to sit?",
        },
      ],
      mistakes: [
        "Adding an apostrophe to “its” out of habit, even when the word is showing ownership, not a contraction.",
        "Confusing “here” (place) and “hear” (sound) because they are pronounced identically.",
      ],
      examTip: "If a possessive word (your, its) has an apostrophe in the sentence you're checking, that's almost always the error.",
      searchTerms: ["homophone", "your", "you're", "its", "it's", "here", "hear", "apostrophe"],
    },
    {
      id: "often-confused-pairs",
      title: "Often-Confused Word Pairs: affect / effect, accept / except",
      tier: "Foundation",
      objective: "Distinguish near-homophones that are not spelled or pronounced identically but are still routinely swapped, using their grammatical job as the test.",
      whyMatters: "affect/effect and accept/except are two of the most frequently confused word pairs in formal English, and both appear regularly in 11+ “complete the sentence” questions.",
      conceptTitle: "Close but not identical",
      conceptBullets: [
        '<b>affect</b> is almost always a <i>verb</i> meaning “to influence” (<i>the weather affected the match</i>).',
        '<b>effect</b> is almost always a <i>noun</i> meaning “a result” (<i>the effect was obvious</i>).',
        '<b>accept</b> means “to agree to receive or believe” (<i>accept the invitation</i>); <b>except</b> means “leaving out” (<i>everyone except Sam</i>).',
        "Unlike true homophones, these pairs sound slightly different when spoken carefully — but under exam pressure they're just as easy to mix up.",
      ],
      conceptNote: "<b>Quick test:</b> if the word needs an “-ing” or comes straight after a subject as the main verb, it should almost always be “affect”, not “effect”.",
      glossary: [
        { term: "affect", def: "verb: to influence or change something" },
        { term: "effect", def: "noun: a result or outcome" },
        { term: "accept", def: "to agree to receive or believe" },
        { term: "except", def: "leaving something out; excluding" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: AffectEffectDemo,
      worked: {
        question: "Spot the error: “Everyone accept Priya remembered their homework.”",
        fastMethod: 'The sentence means Priya was left out of the group who remembered — that meaning needs "except", not "accept".',
        steps: [
          "Read the sentence for meaning: one person is being excluded from the group described.",
          "“Accept” means to agree to receive something — that doesn't fit here.",
          "“Except” means “leaving out”, which matches the intended meaning.",
          "Corrected: “Everyone except Priya remembered their homework.”",
        ],
        answer: "The error is <b>accept</b> — it should be <b>except</b>.",
      },
      selfCheck: { prompt: "True or false: “effect” can sometimes be used as a verb.", answer: "<b>True, rarely</b> — “to effect change” means “to bring change about” — but at 11+ level, treat “affect” as the verb and “effect” as the noun unless told otherwise." },
      kind: "click-error",
      questions: [
        {
          id: "ocp-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "heavy", "rain", "will", "effect", "the", "football", "match", "tomorrow."],
          errorIdx: 4,
          correction: '"effect" is normally a noun, but this word is acting as a verb meaning "to influence" — it needs "affect": will affect the match.',
          hint: "Check whether this word is the main verb of the sentence.",
        },
        {
          id: "ocp-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "medicine", "had", "an", "immediate", "affect", "on", "her", "headache."],
          errorIdx: 5,
          correction: '"affect" is normally a verb, but here the word is a noun meaning "result" — it needs "effect": an immediate effect.',
          hint: "This word is being described by “an immediate” — what part of speech does that suggest?",
        },
        {
          id: "ocp-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["I", "am", "happy", "to", "except", "your", "kind", "invitation", "to", "the", "party."],
          errorIdx: 4,
          correction: '"except" means "leaving out" — the sentence needs "accept", meaning "to agree to receive": happy to accept.',
          hint: "Is the invitation being excluded, or agreed to?",
        },
      ],
      mistakes: [
        "Defaulting to “effect” whenever the word sounds vaguely like it, without checking whether a verb or a noun is needed.",
        "Swapping accept and except because they share several letters, without checking whether the meaning is “include” or “exclude”.",
      ],
      examTip: "For affect/effect, ask “is this word the action, or the result of the action?” — action needs affect, result needs effect.",
      searchTerms: ["affect", "effect", "accept", "except", "word pairs", "near-homophone"],
    },
    {
      id: "subtle-meaning-differences",
      title: "Subtle Meaning Differences: fewer / less, amount / number",
      tier: "Standard",
      objective: "Apply the countable-vs-uncountable test to choose correctly between fewer/less and amount/number.",
      whyMatters: "the fewer/less rule is broken constantly in everyday speech and signage, which makes it a favourite trap for testing whether students know the formal rule.",
      conceptTitle: "Can you count it?",
      conceptBullets: [
        '<b style="color:#C9A24B">Countable nouns</b> can be counted one by one (three <i>students</i>, five <i>cars</i>); <b>uncountable nouns</b> cannot (<i>traffic</i>, <i>rainfall</i>, <i>homework</i>).',
        'Use <b>fewer</b> and <b>number</b> for countable nouns: <i>fewer students</i>, <i>a large number of cars</i>.',
        'Use <b>less</b> and <b>amount</b> for uncountable nouns: <i>less traffic</i>, <i>a large amount of rainfall</i>.',
        "The test is always the same: ask “can I count these one by one?” before choosing the word.",
      ],
      conceptNote: "<b>Quick test:</b> if you could say “one ___, two ___, three ___” about the noun, use fewer/number; if not, use less/amount.",
      glossary: [
        { term: "countable noun", def: "can be counted individually (students, cars)" },
        { term: "uncountable noun", def: "cannot be split into individual units (traffic, rainfall)" },
        { term: "fewer", def: "used with countable nouns" },
        { term: "less", def: "used with uncountable nouns" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: FewerLessDemo,
      worked: {
        question: "Spot the error: “This recipe uses less eggs than the last one.”",
        fastMethod: 'Eggs can be counted one by one (one egg, two eggs), so the sentence needs "fewer", not "less".',
        steps: [
          "Identify the noun being described: “eggs”.",
          "Ask: can eggs be counted individually? Yes — one egg, two eggs, three eggs.",
          "Countable nouns need “fewer”, not “less”.",
          "Corrected: “This recipe uses fewer eggs than the last one.”",
        ],
        answer: "The error is <b>less</b> — it should be <b>fewer</b>.",
      },
      selfCheck: { prompt: "Which is correct: “a large amount of visitors” or “a large number of visitors”?", answer: "<b>“A large number of visitors”</b> — visitors can be counted one by one, so “number” is correct, not “amount”." },
      kind: "click-error",
      questions: [
        {
          id: "smd-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["There", "were", "less", "cars", "on", "the", "road", "this", "morning", "than", "usual."],
          errorIdx: 2,
          correction: '"cars" can be counted one by one, so the sentence needs "fewer", not "less": fewer cars.',
          hint: "Can the noun right after this word be counted individually?",
        },
        {
          id: "smd-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["A", "large", "amount", "of", "students", "attended", "the", "assembly."],
          errorIdx: 2,
          correction: '"students" is a countable noun, so the sentence needs "number", not "amount": a large number of students.',
          hint: "Students can be counted one by one — which word matches that?",
        },
        {
          id: "smd-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["There", "was", "a", "surprising", "number", "of", "rainfall", "this", "year."],
          errorIdx: 4,
          correction: '"rainfall" cannot be counted individually, so the sentence needs "amount", not "number": a surprising amount of rainfall.',
          hint: "Can you say “one rainfall, two rainfalls”? What does that tell you?",
        },
      ],
      mistakes: [
        "Using “less” with a countable noun out of habit (e.g. supermarket signs saying “10 items or less”, which should read “fewer”).",
        "Choosing amount/number based on how large the quantity sounds, rather than whether the noun is actually countable.",
      ],
      examTip: "Say “one, two, three” in front of the noun in your head — if it sounds natural, use fewer/number; if it sounds strange, use less/amount.",
      searchTerms: ["fewer", "less", "amount", "number", "countable noun", "uncountable noun"],
    },
    {
      id: "sound-similar-spelling",
      title: "Sound-Similar, Spelled Differently: practice / practise, licence / license, stationary / stationery",
      tier: "Standard",
      objective: "Apply the UK noun/verb spelling distinction for practice/practise and licence/license, and tell stationary apart from stationery.",
      whyMatters: "the practice/practise and licence/license noun-verb spelling rule is a distinctly UK English point that GL and CSSE papers test precisely because it trips up students used to seeing only one spelling.",
      conceptTitle: "Noun with a c, verb with an s",
      conceptBullets: [
        'In UK English, <b>practice</b> (with a <i>c</i>) is the <i>noun</i> — <i>football practice</i>; <b>practise</b> (with an <i>s</i>) is the <i>verb</i> — <i>to practise the piano</i>.',
        'The same pattern applies to <b>licence</b> (noun, with a <i>c</i>) — <i>a driving licence</i> — and <b>license</b> (verb, with an <i>s</i>) — <i>to license a driver</i>.',
        '<b>stationary</b> means “not moving” (<i>the stationary car</i>); <b>stationery</b> means paper and writing materials (<i>a stationery shop</i>).',
        "A useful memory trick: “c comes before s” in the alphabet, just as the noun form often comes before the verb form when you look the word up.",
      ],
      conceptNote: "<b>Memory trick:</b> “advice/advise” follows the exact same noun/verb pattern and is easier to hear — if you'd say “advice” or “advise”, apply the same c/s choice to practice/practise.",
      glossary: [
        { term: "practice", def: "the noun spelling (UK): football practice" },
        { term: "practise", def: "the verb spelling (UK): to practise daily" },
        { term: "licence / license", def: "noun/verb pair with the same c/s pattern as practice/practise" },
        { term: "stationary / stationery", def: "not moving / paper and writing materials" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: PracticePractiseDemo,
      worked: {
        question: "Spot the error: “Our football practise starts at four o'clock on Thursdays.”",
        fastMethod: 'The word follows "football" and names a thing (a session), so it\'s a noun — it needs the c spelling: "practice".',
        steps: [
          "Identify whether the word is naming a thing (noun) or describing an action (verb).",
          "“Our football practise” — the word names the training session itself, a noun.",
          "UK English uses the c spelling for the noun: “practice”.",
          "Corrected: “Our football practice starts at four o'clock…”",
        ],
        answer: "The error is <b>practise</b> — it should be <b>practice</b>.",
      },
      selfCheck: { prompt: "Which is correct: “a stationary shop” or “a stationery shop”, for a shop selling pens and paper?", answer: "<b>“A stationery shop”</b> — “stationery” (with an e) means paper and writing materials; “stationary” means not moving." },
      kind: "click-error",
      questions: [
        {
          id: "ssd-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "team", "will", "practice", "their", "routine", "every", "day", "before", "the", "show."],
          errorIdx: 3,
          correction: '"practice" is the UK noun spelling, but this word is a verb (an action they will do) — it needs "practise": will practise their routine.',
          hint: "Is this word naming a thing, or describing an action the team will do?",
        },
        {
          id: "ssd-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["You", "must", "carry", "your", "driving", "license", "at", "all", "times."],
          errorIdx: 5,
          correction: '"license" is the UK verb spelling, but this word is a noun (a document) — it needs "licence": driving licence.',
          hint: "Is this word a document you carry, or an action?",
        },
        {
          id: "ssd-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "bought", "some", "new", "stationary", "for", "the", "school", "term."],
          errorIdx: 4,
          correction: '"stationary" means "not moving" — the sentence needs "stationery", meaning paper and writing materials: new stationery.',
          hint: "Is the sentence about something standing still, or something you buy for writing?",
        },
      ],
      mistakes: [
        "Using the same spelling for both the noun and verb forms of practice/practise or licence/license instead of switching the c/s.",
        "Confusing stationary and stationery because they differ by only one letter.",
      ],
      examTip: "Ask “is this word naming a thing, or naming an action?” first — that tells you whether to reach for the c spelling or the s spelling.",
      searchTerms: ["practice", "practise", "licence", "license", "stationary", "stationery", "uk spelling"],
    },
    {
      id: "idiomatic-phrases",
      title: "Commonly Misused Idiomatic Phrases",
      tier: "Standard",
      objective: "Recognise well-known idioms that are frequently misheard or misquoted, and identify the single word that has been substituted incorrectly.",
      whyMatters: "idiom errors are a distinctive 11+ trap because the sentence sounds completely familiar — the wrong word has simply been repeated so often in casual speech that it sounds correct.",
      conceptTitle: "Idioms that get misheard",
      conceptBullets: [
        'An <b style="color:#C9A24B">idiom</b> is a fixed phrase whose meaning isn\'t obvious from the individual words — which is exactly why one wrong word can slip in unnoticed.',
        'The correct idiom is “for all <i>intents and purposes</i>”, meaning “in every practical sense” — not “intensive purposes”.',
        'The correct idiom is “<i>couldn\'t</i> care less”, meaning you care so little that you couldn\'t care any less — “could care less” actually implies the opposite.',
        'The correct idiom is “nip it in the <i>bud</i>”, comparing stopping a problem early to pruning a plant bud — not “nip it in the butt”.',
      ],
      conceptNote: "<b>Why this happens:</b> these misquoted versions are common in everyday speech precisely because they sound almost identical to the original — always check the idiom actually makes logical sense.",
      glossary: [
        { term: "idiom", def: "a fixed phrase whose overall meaning differs from its individual words" },
        { term: "eggcorn", def: "a misheard phrase that replaces a word with a similar-sounding one (intensive for intents)" },
        { term: "malapropism", def: "the mistaken use of a word in place of a similar-sounding one" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: IntensivePurposesDemo,
      worked: {
        question: "Spot the error: “The old bridge was, for all intensive purposes, no longer safe to use.”",
        fastMethod: 'The real idiom is "intents and purposes" — "intensive" is a mishearing that has crept into casual speech.',
        steps: [
          "Recognise the idiom being used: “for all intensive purposes”.",
          "Recall the correct wording: “for all intents and purposes”, meaning “in every practical sense”.",
          "“Intensive” doesn't logically fit this meaning — it's a common mishearing of “intents”.",
          "Corrected: “…for all intents and purposes, no longer safe…”",
        ],
        answer: "The error is <b>intensive</b> — it should be <b>intents (and purposes)</b>.",
      },
      selfCheck: { prompt: "Which is the correct idiom: “I could care less” or “I couldn't care less”, to mean you don't care at all?", answer: "<b>“I couldn't care less”</b> — saying you “could” care less means you do care at least a little, which is the opposite of the intended meaning." },
      kind: "click-error",
      questions: [
        {
          id: "idm-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["For", "all", "intensive", "purposes,", "the", "meeting", "was", "over", "by", "three", "o'clock."],
          errorIdx: 2,
          correction: 'the idiom is "for all intents and purposes" — "intensive" is a common mishearing of "intents".',
          hint: "This phrase is often misheard — one word here isn't the one used in the real idiom.",
        },
        {
          id: "idm-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["He", "said", "he", "could", "care", "less", "about", "the", "football", "results."],
          errorIdx: 3,
          correction: 'saying "could care less" implies he does care a little — the intended meaning needs "couldn\'t": he couldn\'t care less.',
          hint: "Think carefully about what this phrase actually says versus what it's supposed to mean.",
        },
        {
          id: "idm-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "teacher", "wanted", "to", "nip", "the", "bad", "behaviour", "in", "the", "butt", "before", "it", "got", "worse."],
          errorIdx: 10,
          correction: 'the idiom is "nip it in the bud" (stopping a problem while it\'s still small, like pruning a plant) — "butt" is a common mishearing of "bud".',
          hint: "The real idiom is about gardening, not any other meaning of this word.",
        },
      ],
      mistakes: [
        "Writing down an idiom exactly as it's commonly mispronounced in speech, without checking the words actually make logical sense together.",
        "Assuming a very familiar-sounding phrase must be correct just because you've heard it often.",
      ],
      examTip: "If an idiom uses a word that seems oddly out of place once you think about its literal meaning, that's the sign of a misheard idiom.",
      searchTerms: ["idiom", "intents and purposes", "could not care less", "nip in the bud", "misquoted phrase"],
    },
    {
      id: "formal-informal-word-choice",
      title: "Formal vs. Informal Word Choice",
      tier: "Standard",
      objective: "Recognise informal words and contractions that don't belong in formal written English, and identify the formal equivalent.",
      whyMatters: "GL and CSSE comprehension and writing sections both reward — and sometimes directly test — the ability to spot register mismatches between casual speech and formal writing.",
      conceptTitle: "Match the word to the setting",
      conceptBullets: [
        'The same idea can usually be expressed in <b style="color:#C9A24B">formal</b> or <b>informal</b> language — the right choice depends on who is writing and why.',
        'Informal words like <i>gonna</i>, <i>kinda</i> and <i>stuff</i> belong in casual speech, not in a formal letter, report or exam answer.',
        'Formal writing uses precise, complete alternatives: <i>gonna</i> → <i>going to</i>; <i>kinda</i> → <i>somewhat</i>/<i>rather</i>; <i>stuff</i> → a specific noun like <i>equipment</i>.',
        "This error type is about the whole sentence's tone, not grammar — the informal word is often grammatically fine, just in the wrong context.",
      ],
      conceptNote: "<b>Test it:</b> imagine reading the sentence aloud to a head teacher in a meeting — an informal word will immediately sound out of place.",
      glossary: [
        { term: "register", def: "the level of formality in language, matched to its audience and purpose" },
        { term: "formal English", def: "precise, complete language used in official or written contexts" },
        { term: "informal English", def: "casual language used in everyday speech" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: GonnaFormalDemo,
      worked: {
        question: "Spot the error: “The council confirmed that the new library was gonna open in September.”",
        fastMethod: 'This is a formal, official announcement — "gonna" is a casual spoken contraction and doesn\'t match: "going to".',
        steps: [
          "Identify the tone of the sentence: an official council announcement, which should be formal.",
          "Find the word that clashes with this formal tone: “gonna”.",
          "“Gonna” is an informal contraction of “going to” used in casual speech.",
          "Corrected: “…the new library was going to open in September.”",
        ],
        answer: "The error is <b>gonna</b> — it should be <b>going to</b>.",
      },
      selfCheck: { prompt: "In a formal letter, which is correct: “I need some stuff for the trip” or “I need some equipment for the trip”?", answer: "<b>“I need some equipment for the trip”</b> — “stuff” is vague and informal; formal writing uses a specific, precise noun." },
      kind: "click-error",
      questions: [
        {
          id: "fic-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "scientist", "explained", "that", "the", "experiment", "was", "gonna", "take", "several", "hours", "to", "complete."],
          errorIdx: 7,
          correction: '"gonna" is informal spoken English, but this is a formal explanation — it needs "going to": was going to take.',
          hint: "One word here belongs in casual speech, not a scientist's formal explanation.",
        },
        {
          id: "fic-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "head", "teacher's", "report", "stated", "that", "attendance", "had", "been", "kinda", "disappointing", "this", "term."],
          errorIdx: 9,
          correction: '"kinda" is informal for "kind of" — a formal report needs "somewhat" or "rather": had been somewhat disappointing.',
          hint: "This word is a casual shortening that wouldn't appear in an official report.",
        },
        {
          id: "fic-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "letter", "explained", "that", "the", "school", "needed", "more", "stuff", "for", "the", "new", "science", "block."],
          errorIdx: 8,
          correction: '"stuff" is vague and informal — a formal letter needs a precise word like "equipment": needed more equipment.',
          hint: "One word here is too vague and casual for a formal letter.",
        },
      ],
      mistakes: [
        "Writing spoken contractions like “gonna” or “kinda” directly into formal written answers without noticing the mismatch.",
        "Using a vague, casual word like “stuff” or “things” where a formal piece of writing needs a precise noun.",
      ],
      examTip: "Read the sentence in the voice of a formal letter or news report — an informal word will jump out immediately by comparison.",
      searchTerms: ["formal", "informal", "register", "gonna", "kinda", "word choice", "tone"],
    },
    {
      id: "false-friends",
      title: "False Friends / Look-Alike Words",
      tier: "Extension",
      objective: "Tell apart words that look or sound very similar but have entirely different meanings: loose/lose, quiet/quite, though/through/thorough.",
      whyMatters: "look-alike word errors are especially easy to miss when reading quickly, because the eye often registers the shape of the word rather than each individual letter.",
      conceptTitle: "One letter, one sound — different word entirely",
      conceptBullets: [
        '<b>loose</b> means “not tight” (<i>a loose thread</i>); <b>lose</b> means “to be defeated” or “to misplace” (<i>lose the match</i>) — only one letter apart, but very different meanings.',
        '<b>quiet</b> means “making little or no noise” (<i>a quiet room</i>); <b>quite</b> means “fairly” or “completely” (<i>quite tired</i>).',
        '<b>though</b> means “despite the fact that” (<i>though it rained</i>); <b>through</b> means “from one side to the other” (<i>through the tunnel</i>); <b>thorough</b> means “careful and complete” (<i>a thorough check</i>).',
        "These words are called “false friends” because their similar appearance tempts you to assume they mean the same thing — they don't.",
      ],
      conceptNote: "<b>Test it:</b> read the word letter by letter rather than by its overall shape — “loose” has a double o, “lose” has just one, and that single letter changes the whole meaning.",
      glossary: [
        { term: "false friend", def: "a word that looks or sounds like another but has a different meaning" },
        { term: "loose / lose", def: "not tight / to be defeated or misplace" },
        { term: "quiet / quite", def: "making no noise / fairly or completely" },
        { term: "though / through / thorough", def: "despite / from side to side / careful and complete" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: LooseLoseDemo,
      worked: {
        question: "Spot the error: “The dog slipped through its collar because it was too lose.”",
        fastMethod: 'The word describes the collar — not being tight — so it needs the adjective "loose", not the verb "lose".',
        steps: [
          "Identify what the final word is describing: the fit of the collar.",
          "“Lose” means to be defeated or to misplace something — that doesn't describe a fit.",
          "“Loose” means “not tight”, which matches the intended meaning.",
          "Corrected: “…because it was too loose.”",
        ],
        answer: "The error is <b>lose</b> — it should be <b>loose</b>.",
      },
      selfCheck: { prompt: "Which is correct: “She walked though the tunnel” or “She walked through the tunnel”?", answer: "<b>“She walked through the tunnel”</b> — “through” means from one side to the other; “though” means “despite the fact that” and doesn't fit here." },
      kind: "click-error",
      questions: [
        {
          id: "ff-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["If", "you", "don't", "tie", "your", "shoelaces,", "you", "might", "loose", "your", "shoe."],
          errorIdx: 8,
          correction: '"loose" means not tight — the sentence needs "lose", meaning to no longer have something: might lose your shoe.',
          hint: "Is the sentence describing a fit, or the shoe going missing?",
        },
        {
          id: "ff-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "library", "was", "quite", "at", "lunchtime,", "so", "I", "could", "concentrate", "on", "my", "reading."],
          errorIdx: 3,
          correction: '"quite" means "fairly" or "completely" — the sentence describes silence, so it needs "quiet": the library was quiet.',
          hint: "Is this word describing an amount, or the level of noise?",
        },
        {
          id: "ff-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "gave", "the", "essay", "a", "though", "check", "before", "handing", "it", "in."],
          errorIdx: 5,
          correction: '"though" means "despite the fact that" — the sentence needs "thorough", meaning careful and complete: a thorough check.',
          hint: "Does this word show contrast, or describe how carefully something was done?",
        },
      ],
      mistakes: [
        "Misreading “loose” for “lose” (or vice versa) because they differ by only one letter and look almost identical at a glance.",
        "Using “though” when the sentence actually needs “through” or “thorough” — three very different meanings hidden in similar-looking words.",
      ],
      examTip: "When two words look almost identical, read each letter deliberately rather than skimming the shape of the word — that's where these errors hide.",
      searchTerms: ["false friend", "loose", "lose", "quiet", "quite", "though", "through", "thorough", "look-alike words"],
    },
    {
      id: "near-synonyms",
      title: "Choosing the Correct Word from Near-Synonyms",
      tier: "Extension",
      objective: "Select the correct word from classic 11+ near-synonym pairs — complement/compliment, principal/principle, desert/dessert — using precise meaning, not general sense.",
      whyMatters: "these are some of the most frequently examined confusable pairs at 11+ level precisely because they sound alike but belong to completely different meaning categories.",
      conceptTitle: "Sounds the same, means something different",
      conceptBullets: [
        '<b>complement</b> means “something that completes or goes well with another thing” (<i>the scarf complements the coat</i>); <b>compliment</b> means “a polite remark of praise” (<i>a lovely compliment</i>).',
        '<b>principal</b> means “the head of an organisation” or “most important” (<i>the school principal</i>); <b>principle</b> means “a fundamental rule or belief” (<i>a principle to live by</i>).',
        '<b>desert</b> means “a dry, sandy area” or “to abandon” (<i>the Sahara desert</i>); <b>dessert</b> means “a sweet course after a meal” (<i>chocolate dessert</i>) — spelled with a double s.',
        "Each pair sounds close enough to be genuinely confusing, but the two words belong to entirely unrelated ideas — there is no shortcut except knowing the precise meaning.",
      ],
      conceptNote: "<b>Memory trick:</b> the school \"principal\" is your \"pal\" — both end in <i>-pal</i>, which helps you remember it's the person, not the rule.",
      glossary: [
        { term: "complement", def: "something that completes or goes well with another thing" },
        { term: "compliment", def: "a polite remark of praise" },
        { term: "principal", def: "the head of an organisation; most important" },
        { term: "principle", def: "a fundamental rule or belief" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: ComplementComplimentDemo,
      worked: {
        question: "Spot the error: “Fairness is a principle character in the way she treats her friends.”",
        fastMethod: 'The sentence means fairness is a fundamental belief guiding her behaviour — that meaning needs "principal", meaning "most important".',
        steps: [
          "Read the sentence for meaning: fairness is described as the most important trait in her behaviour.",
          "“Principle” means a fundamental rule or belief — it can't directly describe “character” as an adjective here.",
          "“Principal” meaning “most important” fits: a principal character trait.",
          "Corrected: “Fairness is a principal part of the way she treats her friends.”",
        ],
        answer: "The error is <b>principle</b> — it should be <b>principal</b>.",
      },
      selfCheck: { prompt: "Which is correct: “She thanked him for the kind complement” or “…the kind compliment”?", answer: "<b>“…the kind compliment”</b> — a polite remark of praise is a “compliment”; “complement” means something that completes another thing." },
      kind: "click-error",
      questions: [
        {
          id: "ns-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "scarf", "really", "complimented", "her", "blue", "coat", "perfectly."],
          errorIdx: 3,
          correction: '"complimented" means praised — the sentence means the scarf went well with the coat, so it needs "complemented": really complemented her coat.',
          hint: "Is the scarf praising the coat, or going well with it?",
        },
        {
          id: "ns-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "school", "principle", "announced", "the", "new", "uniform", "policy."],
          errorIdx: 2,
          correction: '"principle" means a fundamental rule or belief — the head of the school is the "principal": the school principal.',
          hint: "Is this word naming a person, or a belief?",
        },
        {
          id: "ns-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["After", "dinner,", "everyone", "was", "excited", "for", "the", "chocolate", "desert."],
          errorIdx: 8,
          correction: '"desert" is a dry, sandy area (or to abandon) — the sweet course after a meal is "dessert": chocolate dessert.',
          hint: "Is this word about a landscape, or a sweet course after a meal?",
        },
      ],
      mistakes: [
        "Confusing complement and compliment because they are pronounced identically, despite meaning completely different things.",
        "Misspelling “dessert” with only one s, mixing it up with the unrelated word “desert”.",
      ],
      examTip: "Learn these classic pairs as fixed facts rather than trying to reason them out mid-exam — complement/compliment, principal/principle and desert/dessert come up repeatedly.",
      searchTerms: ["complement", "compliment", "principal", "principle", "desert", "dessert", "near-synonyms"],
    },
    {
      id: "best-fit-mixed-review",
      title: "\"Best Fit\" Word Choice — Mixed Review",
      tier: "Extension",
      objective: "Apply everything from this module together, spotting the confusable-word error in varied sentences without being told which category it belongs to.",
      whyMatters: "real exam papers never label the error type in advance — the final skill is scanning a sentence cold and knowing instantly which single word doesn't fit.",
      conceptTitle: "Bringing it all together",
      conceptBullets: [
        "By this point you've met homophones (their/there), near-homophones (affect/effect), countable/uncountable pairs (fewer/less), spelling look-alikes (practice/practise) and formal/informal choices (gonna/going to).",
        "A mixed-review sentence gives no hint about which category the error belongs to — you have to scan the whole sentence and test each confusable word in turn.",
        "The fastest method is always the same: read for meaning first, then check any word that “sounds right but looks slightly off” against its true job in the sentence.",
        "On a real paper, expect exactly one error per sentence — resist the urge to “fix” a second word that's simply written in a style you wouldn't personally choose.",
      ],
      conceptNote: "<b>Exam strategy:</b> read the whole sentence once for meaning before touching any individual word — the error is almost always the one word that breaks that meaning.",
      glossary: [
        { term: "best fit", def: "choosing the one word that correctly matches both sound and meaning" },
        { term: "register", def: "how formal or informal a word choice is" },
        { term: "countable noun", def: "can be counted individually — takes fewer/number" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: MixedReviewDemo,
      worked: {
        question: "Spot the error: “Its always quiet exciting when the school fete takes less time to set up then usual.”",
        fastMethod: 'Several words here could be tested — but read for meaning first: "quiet" is describing "exciting" (an amount), so it should be "quite".',
        steps: [
          "Scan the sentence and mentally test each confusable-looking word: “Its”, “quiet”, “less”, “then”.",
          "“Its” correctly shows possession here (no contraction needed) and “less time” is fine, since time is uncountable — both are correct.",
          "“Quiet” is describing the degree of “exciting”, which needs “quite” (fairly/very), not “quiet” (silent).",
          "Corrected: “…always quite exciting…” — the rest of the sentence is correct.",
        ],
        answer: "The error is <b>quiet</b> — it should be <b>quite</b>.",
      },
      selfCheck: { prompt: "In a mixed-review sentence with no hint given, what should you check first: spelling of every word, or the overall meaning?", answer: "<b>Overall meaning first</b> — the word that breaks the sentence's sense is almost always the error; only then test its spelling or form." },
      kind: "click-error",
      questions: [
        {
          id: "mix-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "teacher's", "advice", "had", "a", "positive", "affect", "on", "the", "whole", "class."],
          errorIdx: 6,
          correction: '"affect" is normally a verb — here the word is a noun meaning "result", described by "positive", so it needs "effect": a positive effect.',
          hint: "This word is being described by “a positive” — what part of speech does that suggest?",
        },
        {
          id: "mix-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["By", "the", "time", "we", "arrived,", "there", "house", "was", "already", "full", "of", "guests."],
          errorIdx: 5,
          correction: '"there" shows place, but the sentence shows ownership of the house — it needs "their": their house.',
          hint: "Who does the house belong to?",
        },
        {
          id: "mix-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "instructions", "were", "quiet", "clear", "once", "she", "read", "them", "a", "second", "time."],
          errorIdx: 3,
          correction: '"quiet" means making no noise — the sentence needs "quite", meaning "fairly", to describe how clear the instructions were: quite clear.',
          hint: "Is this word about noise, or about degree?",
        },
      ],
      mistakes: [
        "Fixating on the first unusual-looking word instead of reading the whole sentence for meaning before deciding.",
        "Trying to correct a word that's merely informal in tone when the actual grammatical or meaning error lies elsewhere in the sentence.",
      ],
      examTip: "Give the sentence one full read for meaning before hunting for the error — knowing what the sentence is trying to say makes the wrong word obvious.",
      searchTerms: ["mixed review", "best fit", "word choice", "confusable words", "spot the mistake"],
    },
  ],
};
