import type { TopicContent } from "../types";
import {
  WhatMakesBestFitAnswerDemo,
  GrammaticalFitVsMeaningFitDemo,
  BestFitConnectiveDemo,
  BestFitVerbPrecisionDemo,
  RegisterToneMatchingDemo,
  CollocationNaturalPhrasingDemo,
  BestFitSentenceCombiningDemo,
  AlmostRightDistractorDemo,
  NarrowingDownByEliminationDemo,
} from "../notes-diagrams/complete-the-sentence-demos";

const CLICK_INSTRUCTION = "Click the word that best completes the sentence.";

export const completeTheSentenceTopic: TopicContent = {
  slug: "complete-the-sentence",
  subject: "English",
  subjectSlug: "english",
  title: "Grammar: Complete the Sentence & Best-Fit Word Choice",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "A different question style from “spot the mistake”: here every option is grammatically correct, but only one is the best fit for meaning, tone or logic. This module covers choosing the right connective for the logical relationship, picking a precise verb over a vague one, combining two short sentences smoothly, and recognising the “almost right” distractor that examiners plant deliberately.",
  subtopics: [
    {
      id: "what-makes-best-fit-answer",
      title: "What Makes a Best-Fit Answer?",
      tier: "Foundation",
      objective: "Understand that in a best-fit gap question, several options may look plausible but only one is both grammatically correct and the best match for meaning.",
      whyMatters: "many marks are lost not to grammar errors but to picking a word that “sounds fine” without checking it actually fits the sentence's meaning — knowing there are two separate checks stops that.",
      conceptTitle: "Two checks, not one",
      conceptBullets: [
        '<b style="color:#C9A24B">best-fit question</b>: a sentence with one gap and a bank of options, where more than one option might be a real, correctly spelled word that could go in the gap.',
        "Check 1 — grammar fit: does the word's type (noun, verb, adjective) and form (tense, singular/plural) actually work in that slot?",
        "Check 2 — meaning fit: once the grammar works, does the word's meaning make sense with the rest of the sentence?",
        'Example: in "The dog ___ loudly at the postman", "barked" fits both checks, but "bark" fails the grammar check (wrong verb form) and "sang" fails the meaning check (fits grammar, wrong meaning).',
      ],
      conceptNote: "<b>Test it:</b> read the completed sentence back in full for each option — if either the grammar or the meaning feels even slightly off, that option is not the best fit.",
      glossary: [
        { term: "best-fit question", def: "a sentence with one gap and several options, where only one option is both grammatically correct and the best match for meaning" },
        { term: "gap", def: "the missing word or phrase in the sentence that needs to be filled" },
        { term: "option bank", def: "the small set of words offered to choose from to fill the gap" },
        { term: "grammatical fit", def: "whether a word's type and form work correctly in the sentence's structure" },
        { term: "meaning fit", def: "whether a word's meaning makes sense given the rest of the sentence" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: WhatMakesBestFitAnswerDemo,
      worked: {
        question: "Choose the best fit: “After the long queue, the customers ___ relieved when the doors finally opened.” (options: relieve, relieved, relieving, annoyed)",
        fastMethod: "Check the grammar first (only one option is a correctly formed past-tense/adjective form), then check that its meaning matches the queue finally ending.",
        steps: [
          "Rule out “relieve” and “relieving” — neither is the correct past-tense adjective form needed after “the customers ___”.",
          "Between “relieved” and “annoyed”, both are grammatically fine in that slot.",
          "Check meaning: the doors finally opening after a long queue should bring relief, not annoyance, so “annoyed” fails the meaning check.",
          "“Relieved” passes both the grammar check and the meaning check.",
        ],
        answer: "The best fit is <b>relieved</b> — it passes both the grammar check and the meaning check, unlike “annoyed”, which is grammatically fine but the wrong meaning.",
      },
      selfCheck: { prompt: "True or false: if an option is grammatically correct in the gap, it must be the best-fit answer.", answer: "<b>False</b> — a grammatically correct option can still be wrong if its meaning doesn't match the rest of the sentence; both checks must pass." },
      kind: "cloze-fill",
      questions: [
        {
          id: "wmbfa-q1",
          instruction: CLICK_INSTRUCTION,
          before: "After weeks of rain, the farmers were",
          options: ["relieved", "relieve", "relieving", "annoyed"],
          correctIdx: 0,
          after: "when the sun finally came out.",
          correction: "“relieved” passes both checks — it is the correct past-tense adjective form and matches the positive meaning of the sun finally appearing after rain. “annoyed” is grammatically fine but the wrong meaning; “relieve”/“relieving” fail the grammar check.",
          hint: "Check the grammar form first, then ask whether the meaning matches good news or bad news.",
        },
        {
          id: "wmbfa-q2",
          instruction: CLICK_INSTRUCTION,
          before: "The old bridge finally",
          options: ["collapse", "collapsed", "collapsing", "strengthened"],
          correctIdx: 1,
          after: "under the weight of the lorry.",
          correction: "“collapsed” is the correctly formed past-tense verb and matches the meaning of a bridge failing under weight. “strengthened” is grammatically fine but the wrong meaning; “collapse”/“collapsing” fail the grammar check for this simple past-tense sentence.",
          hint: "Check the verb form fits a completed past action first, then check whether the meaning matches a bridge failing, not holding up.",
        },
        {
          id: "wmbfa-q3",
          instruction: CLICK_INSTRUCTION,
          before: "The audience",
          options: ["applaud", "applauded", "applauding", "booed"],
          correctIdx: 1,
          after: "warmly as the final curtain fell.",
          correction: "“applauded” is the correct past-tense verb and matches “warmly”, a positive reaction. “booed” is grammatically fine but the wrong meaning, since “warmly” signals approval; “applaud”/“applauding” fail the grammar check.",
          hint: "Check which option is a correctly formed simple past-tense verb, then check whether its meaning matches “warmly”.",
        },
      ],
      mistakes: [
        "Stopping at the grammar check and picking the first option that fits the sentence structure, without also checking its meaning against the rest of the sentence.",
        "Assuming every option in the bank is a serious contender, rather than quickly ruling out the ones that fail the grammar check outright.",
      ],
      examTip: "Run the grammar check and the meaning check as two separate steps, in that order — grammar first to narrow the field, then meaning to find the single best fit.",
      searchTerms: ["best fit", "grammar fit", "meaning fit", "gap fill", "option bank", "complete the sentence"],
    },
    {
      id: "grammatical-fit-vs-meaning-fit",
      title: "Grammatical Fit vs Meaning Fit",
      tier: "Foundation",
      objective: "Tell apart two different ways a best-fit option can go wrong: sounding fine grammatically but carrying the wrong meaning, or carrying the right idea but in the wrong word form.",
      whyMatters: "many students only check one of these two failure types and get caught out by the other — training yourself to check both independently closes off a whole category of exam traps.",
      conceptTitle: "Two separate ways to go wrong",
      conceptBullets: [
        '<b style="color:#C9A24B">word class</b>: whether a word is being used as a noun, verb, adjective or adverb — an option can be the "right idea" but in the wrong word class for its slot.',
        "Failure type 1 — right grammar, wrong meaning: the option slots in perfectly (right tense, right word class) but its dictionary meaning clashes with the sentence, e.g. the wrong tense/time-frame or the wrong shade of meaning.",
        "Failure type 2 — right idea, wrong form: the option carries roughly the correct idea but is the wrong word class or form for the slot, e.g. an adjective offered where the sentence needs a noun.",
        'Example of failure type 1: "She will ___ the letter tomorrow" with option "posted" — grammatically a real verb form, but the wrong tense for "tomorrow".',
        'Example of failure type 2: "The teacher praised her ___" with option "creative" — the right idea (creativity) but the wrong word class (adjective, not noun) for the slot after "her".',
      ],
      conceptNote: "<b>Failure diagnosis:</b> before ruling an option out, decide whether it failed on tense/meaning (type 1) or on word class/form (type 2) — naming the failure makes it much faster to spot the pattern next time.",
      glossary: [
        { term: "word class", def: "the grammatical category of a word — noun, verb, adjective or adverb" },
        { term: "tense", def: "the form of a verb that shows when an action happens — past, present or future" },
        { term: "word form", def: "a variant of a word (e.g. creative/creativity/create) built for a particular word class" },
        { term: "shade of meaning", def: "a small but important difference in meaning between similar words" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: GrammaticalFitVsMeaningFitDemo,
      worked: {
        question: "Choose the best fit: “The scientist hoped her ___ would be published soon.” (options: discover, discovery, discovering, discovered)",
        fastMethod: "Look at the slot straight after “her” — it needs a noun, which immediately rules out every verb form.",
        steps: [
          "Identify the word class needed: after “her ___ would be published”, the gap needs a noun (a thing that gets published).",
          "Rule out “discover”, “discovering” and “discovered” — all are verb forms, the wrong word class for this slot.",
          "“discovery” is the noun form and fits the slot correctly.",
          "Check meaning: “discovery” makes sense as something that gets published — the fit is confirmed.",
        ],
        answer: "The best fit is <b>discovery</b> — the only noun form among the options.",
      },
      selfCheck: { prompt: "True or false: an option that carries the right general idea must be the best fit, even if it's the wrong word class.", answer: "<b>False</b> — an option can capture the right idea but still be wrong if it's in the wrong word class or form for its slot in the sentence." },
      kind: "cloze-fill",
      questions: [
        {
          id: "gfvmf-q1",
          instruction: CLICK_INSTRUCTION,
          before: "The coach admired the players'",
          options: ["determine", "determined", "determination", "determining"],
          correctIdx: 2,
          after: "throughout the final.",
          correction: "“determination” is the noun form needed after “the players'” — the other options are verb forms and fail the word-class check even though they share the same root idea.",
          hint: "Work out what word class the gap needs after “the players'”, then check which option matches that word class.",
        },
        {
          id: "gfvmf-q2",
          instruction: CLICK_INSTRUCTION,
          before: "By next Friday, the builders will have",
          options: ["finish", "finished", "finishing", "finishes"],
          correctIdx: 1,
          after: "the extension.",
          correction: "“finished” correctly completes the future-perfect form “will have finished” — this is a tense/form check, not a meaning problem, since all the options relate to the same idea of completing work.",
          hint: "Look at “will have ___” — only one option correctly completes that verb form.",
        },
        {
          id: "gfvmf-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Her explanation was",
          options: ["convince", "convincing", "convinced", "convincingly"],
          correctIdx: 1,
          after: "and cleared up all our confusion.",
          correction: "“convincing” is the correct adjective form describing “her explanation” — “convinced” describes a person's state (not an explanation), and “convince”/“convincingly” are the wrong word class for this slot.",
          hint: "Check what the gap is describing (the explanation itself), and find the option in matching adjective form.",
        },
      ],
      mistakes: [
        "Spotting that an option 'sounds like the right idea' and stopping there, without checking whether it's actually the correct word class for that exact slot.",
        "Only checking word class and missing a subtler failure where the grammar and word class are both fine but the tense or shade of meaning is wrong.",
      ],
      examTip: "When an option feels wrong, name which failure type it is — wrong word class/form, or wrong tense/meaning — it trains you to spot both categories automatically under exam pressure.",
      searchTerms: ["word class", "tense", "grammatical fit", "meaning fit", "word form", "best fit"],
    },
    {
      id: "best-fit-connective",
      title: "Choosing the Best-Fit Connective",
      tier: "Standard",
      objective: "Select the connective (however, therefore, moreover, meanwhile) that correctly signals the logical relationship between two ideas.",
      whyMatters: "every connective option in a best-fit question is a real, correctly spelled word — only the logic of the sentence tells you which one actually fits.",
      conceptTitle: "The relationship between ideas decides the word",
      conceptBullets: [
        'A <b style="color:#C9A24B">connective</b> signals how one idea relates to the next: contrast (however, yet), cause/result (therefore, so), addition (moreover, furthermore), or time (meanwhile, afterwards).',
        "Before choosing, work out the relationship in plain English first: does the second half agree, contradict, add to, or follow on from the first?",
        'Example: "The path was steep; <i>however</i>, they reached the summit" — signals a contrast between difficulty and success.',
        "Swapping in the wrong category of connective (e.g. “therefore” where a contrast is needed) makes the sentence read as if it doesn't quite make sense, even though every word is spelled correctly.",
      ],
      conceptNote: "<b>Test it:</b> say the relationship out loud in your own words first — “these two ideas disagree” or “this one caused that one” — then find the connective that matches.",
      glossary: [
        { term: "connective", def: "a linking word or phrase that shows how two ideas relate" },
        { term: "contrast connective", def: "signals disagreement between ideas (however, yet, although)" },
        { term: "cause/result connective", def: "signals one idea led to another (therefore, so, consequently)" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: BestFitConnectiveDemo,
      worked: {
        question: "Choose the best fit: “The instructions were confusing; ___, most of the class finished the task correctly.”",
        fastMethod: 'The second half contradicts the expectation set up by "confusing" — a contrast connective is needed.',
        steps: [
          "Work out the relationship: confusing instructions, but the class still succeeded — a contrast.",
          "Rule out addition connectives (moreover) and cause/result connectives (therefore) — neither signals contrast.",
          "“Nevertheless” or “however” both correctly signal contrast here.",
          "The best fit is a contrast connective, matching the surprising outcome.",
        ],
        answer: "The best fit is a <b>contrast connective</b> such as <b>however</b> or <b>nevertheless</b>.",
      },
      selfCheck: { prompt: "True or false: “therefore” is a good fit for linking two ideas that contradict each other.", answer: "<b>False</b> — “therefore” signals cause and result, not contrast; a contradicting pair of ideas needs a contrast connective like “however”." },
      kind: "cloze-fill",
      questions: [
        {
          id: "bfc-q1",
          instruction: CLICK_INSTRUCTION,
          before: "The team trained every day for a month;",
          options: ["however", "consequently", "meanwhile", "otherwise"],
          correctIdx: 1,
          after: ", they won the tournament with ease.",
          correction: "“consequently” signals that the win was a direct result of the month of training — a cause/result connective, not a contrast.",
          hint: "Decide whether the second half of the sentence contradicts the first half, or follows naturally from it.",
        },
        {
          id: "bfc-q2",
          instruction: CLICK_INSTRUCTION,
          before: "The recipe looked simple enough;",
          options: ["furthermore", "similarly", "in fact", "it proved surprisingly difficult to get right"],
          correctIdx: 2,
          after: ", it proved surprisingly difficult to get right.",
          correction: "“in fact” introduces a surprising correction to what was just said — the recipe seemed simple, but the truth was the opposite.",
          hint: "Look for the connective that signals the second half is correcting or sharpening the first half's claim.",
        },
        {
          id: "bfc-q3",
          instruction: CLICK_INSTRUCTION,
          before: "She practised her lines every evening;",
          options: ["moreover", "on the other hand", "as a result", "beforehand"],
          correctIdx: 2,
          after: ", she felt confident on stage.",
          correction: "“as a result” signals that her confidence came directly from the practice — a cause/result relationship.",
          hint: "Work out whether the second clause is a consequence of the first, an added extra point, or a contrast.",
        },
      ],
      mistakes: [
        "Picking a connective that sounds formal or impressive without checking whether its actual logical category (contrast, cause, addition, time) fits the sentence.",
        "Confusing addition connectives (moreover, furthermore) with cause/result connectives (therefore, consequently) because both sound similarly formal.",
      ],
      examTip: "State the relationship between the two halves of the sentence in your own plain words first, then match it to a connective — never choose by “sounds right” alone.",
      searchTerms: ["connective", "however", "therefore", "moreover", "best fit", "complete the sentence"],
    },
    {
      id: "best-fit-verb-precision",
      title: "Choosing the Best-Fit Verb for Precision",
      tier: "Standard",
      objective: "Choose the most precise verb for a sentence's meaning and tone, rather than a vague, general-purpose verb that could technically fit almost anywhere.",
      whyMatters: "best-fit questions often include a vague, all-purpose verb (went, did, got) as a tempting safe option — but exams reward the option that shows the most exact match to the sentence's meaning.",
      conceptTitle: "Vague verbs vs. precise verbs",
      conceptBullets: [
        'A <b style="color:#C9A24B">precise verb</b> carries specific meaning that matches the details already given in the sentence.',
        'A <b>vague verb</b> like "went", "did", "got" or "moved" is grammatically correct almost everywhere, which is exactly why it is rarely the best fit.',
        'Example: "exhausted… she <i>collapsed</i>" is a stronger, more precise match than "exhausted… she <i>went</i>" — collapsing specifically fits exhaustion.',
        "Look at the surrounding clues (an adjective, an adverb, the overall scene) — they usually point to one clearly best verb.",
      ],
      conceptNote: "<b>Test it:</b> if a verb option could just as easily slot into a completely unrelated sentence with no loss of meaning, it is probably too vague to be the best fit.",
      glossary: [
        { term: "precise verb", def: "carries specific meaning matched to the sentence's details" },
        { term: "vague verb", def: "a general-purpose verb that could fit almost any sentence" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: BestFitVerbPrecisionDemo,
      worked: {
        question: "Choose the best fit: “Furious at the decision, the coach ___ off the pitch.”",
        fastMethod: 'Look at "furious" — the verb needs to reflect anger, not just plain movement.',
        steps: [
          "Identify the clue word: “furious”, describing the coach's emotion.",
          "Rule out vague movement verbs like “walked” or “went”, which carry no emotional charge.",
          "“Stormed” carries the sense of angry, forceful movement that matches “furious”.",
          "The most precise fit reflects both the movement and the emotion.",
        ],
        answer: "The best fit is a precise verb such as <b>stormed</b>, not a vague verb like “went”.",
      },
      selfCheck: { prompt: "True or false: “did” is usually the best-fit verb choice in a sentence with a specific, vivid scene.", answer: "<b>False</b> — “did” is one of the vaguest possible verbs and is rarely the best fit when a sentence has vivid, specific details to match." },
      kind: "cloze-fill",
      questions: [
        {
          id: "bfv-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Starving after the long hike, the boys",
          options: ["ate", "devoured", "had", "did"],
          correctIdx: 1,
          after: "every last crumb of the picnic.",
          correction: "“devoured” precisely matches “starving” — it carries the sense of eating hungrily and quickly, unlike the vaguer “ate”, “had” or “did”.",
          hint: "Look at the clue word describing how hungry the boys were, and find the verb that matches that intensity.",
        },
        {
          id: "bfv-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Terrified by the thunder, the kitten",
          options: ["went", "moved", "scrambled", "did"],
          correctIdx: 2,
          after: "under the sofa.",
          correction: "“scrambled” precisely captures a frightened, hurried movement, matching “terrified” — the other options are too vague to carry that meaning.",
          hint: "Look at the clue word describing the kitten's fear, and find the verb that matches a frightened, hurried movement.",
        },
        {
          id: "bfv-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Delighted with her results, Priya",
          options: ["went", "beamed", "did", "had"],
          correctIdx: 1,
          after: "at her parents from the stage.",
          correction: "“beamed” precisely captures a delighted smile, matching “delighted” — the other options carry no expression of joy at all.",
          hint: "Look at the clue word describing Priya's happiness, and find the verb that matches that specific expression.",
        },
      ],
      mistakes: [
        "Defaulting to a safe, vague verb because it is grammatically correct everywhere, rather than checking which option matches the sentence's specific clues.",
        "Ignoring adjectives or adverbs elsewhere in the sentence that point clearly to one precise verb.",
      ],
      examTip: "Underline any emotion or intensity word already in the sentence first — it almost always points straight to the one precise verb that best matches it.",
      searchTerms: ["precise verb", "vague verb", "best fit", "word choice", "complete the sentence"],
    },
    {
      id: "register-tone-matching",
      title: "Register and Tone Matching",
      tier: "Standard",
      objective: "Spot when a best-fit option is grammatically correct and even close in meaning, but clashes with the formality or tone of the rest of the sentence.",
      whyMatters: "GL best-fit questions plant register mismatches as a distractor type of their own — a word that is technically correct can still be the wrong answer if it doesn't match the passage's level of formality.",
      conceptTitle: "Formality has to match, too",
      conceptBullets: [
        '<b style="color:#C9A24B">register</b> is how formal or informal a word or phrase sounds — a word can be grammatically fine and roughly the right meaning, yet still clash in register with the rest of the sentence.',
        "A formal, descriptive passage calls for formal vocabulary (dwelling, magnificent, departed) — dropping in a casual, everyday word (place, huge, left) can feel jarringly out of place even though it isn't wrong.",
        'Example: "The ancient ___ stood silent against the skyline" fits better with "citadel" than with the casual "place", even though "place" is not ungrammatical.',
        "The reverse also happens: an overly formal or old-fashioned word dropped into a casual, conversational sentence can feel stiff and out of place.",
      ],
      conceptNote: "<b>Test it:</b> read the whole sentence (or passage, if you have more context) and ask whether the option's level of formality matches everything around it, not just whether its dictionary meaning is close enough.",
      glossary: [
        { term: "register", def: "how formal or informal a word or phrase sounds" },
        { term: "formal register", def: "vocabulary suited to serious, descriptive or official writing" },
        { term: "informal register", def: "everyday, casual vocabulary suited to conversation" },
        { term: "tone", def: "the overall feeling or attitude a piece of writing creates" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: RegisterToneMatchingDemo,
      worked: {
        question: "Choose the best fit: “The ancient cathedral's ___ spires pierced the low winter cloud.” (options: huge, colossal, big, giant)",
        fastMethod: "All four options mean roughly 'very large' — the difference is register, not meaning, so match the word to the formal, descriptive tone of the sentence.",
        steps: [
          "Notice all four options are close in meaning — this is a register question, not a grammar or basic meaning question.",
          "Rule out “huge” and “big” — both are everyday, casual words that clash with the formal, literary description of a cathedral.",
          "Between “colossal” and “giant”, “colossal” carries the more formal, elevated register that matches “ancient cathedral” and “pierced”.",
          "“Colossal” is the best fit for both meaning and register.",
        ],
        answer: "The best fit is <b>colossal</b> — it matches the passage's formal, descriptive register, unlike the casual “huge”, “big” or the slightly informal “giant”.",
      },
      selfCheck: { prompt: "True or false: if an option's meaning is close enough to correct, register doesn't matter.", answer: "<b>False</b> — an option can be close in meaning and still be the wrong best-fit answer if its level of formality clashes with the rest of the sentence." },
      kind: "cloze-fill",
      questions: [
        {
          id: "rtm-q1",
          instruction: CLICK_INSTRUCTION,
          before: "The elderly professor delivered a",
          options: ["dead good", "brilliant", "top-notch", "ace"],
          correctIdx: 1,
          after: "lecture on medieval history.",
          correction: "“brilliant” fits the formal, academic tone of a professor's lecture — “dead good”, “top-notch” and “ace” are all casual, conversational register that clashes with the formal setting.",
          hint: "Think about which option matches the formal setting of a professor's lecture, not just which means “very good”.",
        },
        {
          id: "rtm-q2",
          instruction: CLICK_INSTRUCTION,
          before: "In her diary, she wrote that the mountain view had left her utterly",
          options: ["awestruck", "gobsmacked", "well chuffed", "made up"],
          correctIdx: 0,
          after: ".",
          correction: "“awestruck” matches the reflective, formal register of a diary entry describing a mountain view — “gobsmacked”, “well chuffed” and “made up” are all casual slang that clash with that tone.",
          hint: "Picture the formal, reflective tone of a diary entry, and find the option that matches that register rather than sounding like spoken slang.",
        },
        {
          id: "rtm-q3",
          instruction: CLICK_INSTRUCTION,
          before: "The report concluded that the company's profits had",
          options: ["gone up loads", "increased significantly", "shot up big time", "really boomed"],
          correctIdx: 1,
          after: "over the previous year.",
          correction: "“increased significantly” matches the formal register of an official report — the other options are all casual phrasings that would be out of place in that context.",
          hint: "Think about the formal, official tone of a written report, and find the option that matches that register.",
        },
      ],
      mistakes: [
        "Choosing an option purely because its meaning is close enough, without checking whether its formality matches the rest of the sentence or passage.",
        "Missing a register clash in the opposite direction — an overly formal or old-fashioned word dropped into a casual, conversational sentence.",
      ],
      examTip: "Read the sentence (or passage) and ask yourself: is this formal or informal writing? Then check that your chosen option matches that register, not just its meaning.",
      searchTerms: ["register", "tone", "formal", "informal", "best fit", "word choice"],
    },
    {
      id: "collocation-natural-phrasing",
      title: "Collocation and Natural Phrasing",
      tier: "Standard",
      objective: "Recognise natural word pairings (collocations) so you can rule out options that are grammatically fine and close in meaning but simply don't 'go together' by convention.",
      whyMatters: "collocation questions trip up students who only check grammar and meaning — some wrong options are perfectly correct words that just aren't the ones native speakers naturally pair together.",
      conceptTitle: "Some words just go together",
      conceptBullets: [
        'A <b style="color:#C9A24B">collocation</b> is a pair or group of words that are conventionally used together, even though other, similar words would be just as grammatically correct.',
        'Example: we "make a decision", not "do a decision" — both "make" and "do" are real verbs, but only one is the natural collocation with "decision".',
        'Example: "heavy rain" is the natural collocation, while "strong rain" is grammatically fine but simply not how the phrase is conventionally used.',
        "Collocation mistakes don't break grammar or clearly change meaning — they just sound slightly 'off' to a fluent ear, which is exactly why they make a good distractor.",
      ],
      conceptNote: "<b>Test it:</b> say the option paired with its neighbouring word out loud — if it sounds like an unusual pairing you've never actually heard before, it is probably not the natural collocation.",
      glossary: [
        { term: "collocation", def: "a pair or group of words that are conventionally used together" },
        { term: "natural phrasing", def: "wording that matches how the language is actually, conventionally used" },
        { term: "idiom", def: "a fixed phrase whose meaning isn't guessable from the individual words alone" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: CollocationNaturalPhrasingDemo,
      worked: {
        question: "Choose the best fit: “Before the exam, she took a ___ breath to calm her nerves.” (options: deep, strong, heavy, thick)",
        fastMethod: "Say each option paired with “breath” out loud — only one is a phrase you've actually heard before.",
        steps: [
          "Check each option's grammar and rough meaning: all four are real adjectives that could describe an amount of air.",
          "Say each pairing aloud: “deep breath”, “strong breath”, “heavy breath”, “thick breath” — only “deep breath” is a phrase in everyday natural use.",
          "“Strong”, “heavy” and “thick” are not ungrammatical, but they simply aren't how this idea is conventionally phrased.",
          "“Deep breath” is the natural collocation.",
        ],
        answer: "The best fit is <b>deep</b> — “deep breath” is the natural collocation, even though the other options are not grammatically wrong.",
      },
      selfCheck: { prompt: "True or false: if an option is grammatically correct and roughly the right meaning, it must be the best fit.", answer: "<b>False</b> — an option can be grammatically fine and close in meaning yet still be wrong if it isn't the natural collocation conventionally used with the neighbouring word." },
      kind: "cloze-fill",
      questions: [
        {
          id: "cnp-q1",
          instruction: CLICK_INSTRUCTION,
          before: "The teacher asked the class to",
          options: ["make an effort", "do an effort", "take an effort", "have an effort"],
          correctIdx: 0,
          after: "to finish the project on time.",
          correction: "“make an effort” is the natural collocation — “do”, “take” and “have” an effort are all grammatically possible combinations but not how this phrase is conventionally used.",
          hint: "Say each option paired with “effort” out loud — only one is a phrase you've actually heard people use.",
        },
        {
          id: "cnp-q2",
          instruction: CLICK_INSTRUCTION,
          before: "The storm brought",
          options: ["strong wind", "heavy wind", "thick wind", "big wind"],
          correctIdx: 0,
          after: "that brought down several trees.",
          correction: "“strong wind” is the natural collocation — “heavy”, “thick” and “big” wind are grammatically possible but not how the phrase is conventionally used (compare “heavy rain”, not “heavy wind”).",
          hint: "Compare this to “heavy rain” — wind uses a different natural pairing word, even though the meaning is similar.",
        },
        {
          id: "cnp-q3",
          instruction: CLICK_INSTRUCTION,
          before: "It's important to",
          options: ["pay attention", "give attention", "make attention", "do attention"],
          correctIdx: 0,
          after: "during the safety briefing.",
          correction: "“pay attention” is the natural collocation — “give”, “make” and “do” attention are all grammatically possible but not conventionally used this way.",
          hint: "Say each option paired with “attention” out loud — only one is the phrase used in everyday natural English.",
        },
      ],
      mistakes: [
        "Assuming that because an option is grammatically correct and roughly the right meaning, it must be an acceptable best fit.",
        "Not reading the option paired with its neighbouring word out loud, which is usually the fastest way to catch an unnatural collocation.",
      ],
      examTip: "When two options both seem to work, say each one paired with its neighbouring word out loud — the natural collocation will be the one that sounds instantly familiar.",
      searchTerms: ["collocation", "natural phrasing", "word pairing", "make a decision", "best fit"],
    },
    {
      id: "best-fit-sentence-combining",
      title: "Combining Two Sentences Smoothly",
      tier: "Extension",
      objective: "Choose the option that combines two short, related sentences into one smooth sentence without clumsy repetition or incorrect punctuation.",
      whyMatters: "sentence-combining questions test whether you can spot the option that reads most naturally — a skill that also improves your own writing style.",
      conceptTitle: "Smooth combination, not just any combination",
      conceptBullets: [
        'When combining two short sentences, look for the option that uses a single, correctly placed <b style="color:#C9A24B">connective or conjunction</b> rather than repeating the same noun twice.',
        'Options that simply glue the two original sentences together with "and" often sound clumsy and repetitive compared to a properly subordinated version.',
        'Example: "The bridge was old. It held firm." combines more smoothly as "Although old, the bridge held firm" than as "The bridge was old and it held firm."',
        "Watch for options with a missing or misplaced comma, or a conjunction used incorrectly — these should be ruled out even if the overall idea is right.",
      ],
      conceptNote: "<b>Test it:</b> read each option aloud — the smoothest, least repetitive version that keeps every original idea is almost always the best fit.",
      glossary: [
        { term: "sentence combining", def: "joining two short sentences into one smooth, well-punctuated sentence" },
        { term: "subordination", def: "turning one idea into a dependent clause to link it smoothly to another" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: BestFitSentenceCombiningDemo,
      worked: {
        question: "Which combines these two ideas most smoothly: “The rain was heavy.” and “The match went ahead.”",
        fastMethod: "Look for the option that uses one clean connective instead of repeating “the match” or “the rain” twice.",
        steps: [
          "Identify the relationship between the two ideas: a contrast — heavy rain, yet the match still happened.",
          "Rule out any option that clumsily repeats a noun or strings the sentences together with a plain “and”.",
          "“Despite the heavy rain, the match went ahead” uses one connective and keeps both ideas intact.",
          "This is the smoothest, most natural combination.",
        ],
        answer: "The best fit is <b>“Despite the heavy rain, the match went ahead.”</b>",
      },
      selfCheck: { prompt: "True or false: joining two sentences with “and” is always the smoothest way to combine them.", answer: "<b>False</b> — “and” can work, but a connective that reflects the actual relationship between the ideas (contrast, cause, time) usually reads more smoothly and precisely." },
      kind: "cloze-fill",
      questions: [
        {
          id: "bfsc-q1",
          instruction: "Click the option that most smoothly combines the two ideas: 'The alarm rang loudly.' and 'No one in the house woke up.'",
          before: "",
          options: [
            "Despite the alarm ringing loudly, no one in the house woke up.",
            "The alarm rang loudly and no one in the house woke up.",
            "The alarm rang loudly, no one in the house, woke up.",
            "Ringing loudly the alarm, no one in the house woke up.",
          ],
          correctIdx: 0,
          after: "",
          correction: "“Despite the alarm ringing loudly, no one in the house woke up” cleanly signals the surprising contrast between a loud alarm and nobody waking, in one smooth clause.",
          hint: "Look for the option that signals the surprising contrast between a loud alarm and no one waking up.",
        },
        {
          id: "bfsc-q2",
          instruction: "Click the option that most smoothly combines the two ideas: 'The museum was free to enter.' and 'Very few visitors came that day.'",
          before: "",
          options: [
            "The museum, being free to enter, but very few visitors came that day.",
            "Although the museum was free to enter, very few visitors came that day.",
            "The museum was free to enter and very few visitors came that day, they did.",
            "Free the museum was to enter, very few visitors came that day.",
          ],
          correctIdx: 1,
          after: "",
          correction: "“Although the museum was free to enter, very few visitors came that day” combines the ideas smoothly, signalling the surprising contrast with one correctly placed connective.",
          hint: "Look for the option that signals the surprising contrast without repeating words awkwardly.",
        },
        {
          id: "bfsc-q3",
          instruction: "Click the option that most smoothly combines the two ideas: 'The path was narrow.' and 'The hikers walked single file.'",
          before: "",
          options: [
            "Because the path was narrow, the hikers walked single file.",
            "The path was narrow, the hikers walked single file, they did.",
            "Narrow the path, the hikers walked single file.",
            "The path was narrow and the hikers, single file, they walked.",
          ],
          correctIdx: 0,
          after: "",
          correction: "“Because the path was narrow, the hikers walked single file” shows the cause-and-result relationship clearly, in one smooth, correctly punctuated sentence.",
          hint: "Look for the option that shows the narrow path caused the hikers to walk single file, without any repetition.",
        },
      ],
      mistakes: [
        "Choosing an option purely because it is grammatically valid, without checking whether it is also the smoothest and least repetitive version.",
        "Missing an awkward repeated noun or a misplaced comma in an otherwise plausible-looking option.",
      ],
      examTip: "Read every option aloud in your head — clumsy repetition or a stumble in the rhythm is usually the fastest way to rule an option out.",
      searchTerms: ["sentence combining", "best fit", "subordination", "complete the sentence", "connective"],
    },
    {
      id: "almost-right-distractor",
      title: "Spotting the Almost-Right Distractor",
      tier: "Extension",
      objective: "Recognise when a best-fit option looks and sounds similar to the correct answer but has a subtly different precise meaning, and rule it out using the exact wording of the sentence.",
      whyMatters: "the hardest best-fit questions plant a near-synonym that looks almost identical to the right answer — spotting the precise difference in meaning is what separates a top mark from a near miss.",
      conceptTitle: "Similar-sounding is not the same as correct",
      conceptBullets: [
        'A <b style="color:#C9A24B">distractor</b> is a wrong option deliberately included because it looks tempting, not because it is correct.',
        'The "almost-right" distractor usually shares a root, sound or general feel with the correct answer, but carries a subtly different precise meaning.',
        'Example: "momentarily" (for a brief moment) is often confused with "shortly" (soon) — they sound like they should mean the same thing, but strictly don\'t.',
        "Always check the option against the exact clue given in the sentence, not just against how similar it sounds to what you expect.",
      ],
      conceptNote: "<b>Test it:</b> substitute the dictionary meaning of each close option back into the sentence — the almost-right distractor usually stops making precise sense once you do.",
      glossary: [
        { term: "distractor", def: "a deliberately tempting wrong answer option" },
        { term: "near-synonym", def: "a word that seems to mean the same as another but differs in a precise detail" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: AlmostRightDistractorDemo,
      worked: {
        question: "Choose the best fit: “The medicine should ___ the pain within a few minutes.” (options: alleviate, eliminate, alter, allocate)",
        fastMethod: "Check each option's precise meaning against “within a few minutes” — the medicine reduces pain, it doesn't necessarily remove it completely.",
        steps: [
          "Rule out “allocate” (to assign) and “alter” (to change) — neither fits pain relief at all.",
          "Compare the two closest options: “alleviate” (to ease/reduce) and “eliminate” (to remove entirely).",
          "The sentence only claims the pain improves “within a few minutes”, not that it vanishes completely — a stronger claim than the sentence supports.",
          "“Alleviate” is the more precisely supported fit.",
        ],
        answer: "The best fit is <b>alleviate</b>, not the near-synonym “eliminate”.",
      },
      selfCheck: { prompt: "True or false: two options that sound similar and are both real words must both be equally correct in a best-fit question.", answer: "<b>False</b> — a best-fit question usually has exactly one option whose precise meaning matches the sentence; a similar-sounding near-synonym is often included specifically as a trap." },
      kind: "cloze-fill",
      questions: [
        {
          id: "ard-q1",
          instruction: CLICK_INSTRUCTION,
          before: "The scientist's theory was later",
          options: ["disproved", "disapproved", "improved", "approved"],
          correctIdx: 0,
          after: "by new evidence.",
          correction: "“disproved” means shown to be false, matching “by new evidence” — “disapproved” is a tempting near-miss that actually means to object to something, not to prove it wrong.",
          hint: "Two of these options look and sound almost identical — check their precise dictionary meanings against “by new evidence”.",
        },
        {
          id: "ard-q2",
          instruction: CLICK_INSTRUCTION,
          before: "The new policy will",
          options: ["affect", "effect", "infect", "reflect"],
          correctIdx: 0,
          after: "how the whole school organises its timetable.",
          correction: "“affect” (a verb meaning to influence) is needed here — “effect” is a tempting near-miss, but it is usually a noun (a result), not a verb meaning to influence.",
          hint: "Two of these options sound identical when spoken — check which one is the verb meaning “to influence”.",
        },
        {
          id: "ard-q3",
          instruction: CLICK_INSTRUCTION,
          before: "The guide book gave a brief",
          options: ["historic", "historical", "history", "historically"],
          correctIdx: 1,
          after: "overview of the castle before the tour began.",
          correction: "“historical” (relating to history) correctly describes the overview — “historic” is a tempting near-miss, but it specifically means “important in history”, not simply “about history”.",
          hint: "Two of these options look almost identical — check which one means “relating to history” rather than “important in history”.",
        },
      ],
      mistakes: [
        "Picking the option that sounds most familiar or similar to the expected word, without checking its precise dictionary meaning.",
        "Assuming any grammatically valid, real-word option must be equally acceptable as the best fit.",
      ],
      examTip: "Whenever two options look almost identical, stop and define each one in your own words before picking — that single check catches most almost-right distractors.",
      searchTerms: ["distractor", "near-synonym", "best fit", "affect effect", "historic historical"],
    },
    {
      id: "narrowing-down-by-elimination",
      title: "Narrowing Down by Elimination",
      tier: "Extension",
      objective: "Apply a systematic elimination method for the hardest best-fit questions, where two or more options still look equally plausible after a first read.",
      whyMatters: "the toughest best-fit questions are deliberately designed so that a quick read leaves two options in contention — a careful, repeatable elimination method is what closes the gap between a good guess and a certain answer.",
      conceptTitle: "A method for when nothing obvious rules an option out",
      conceptBullets: [
        'When a first read leaves two or more options looking equally plausible, switch to a systematic <b style="color:#C9A24B">elimination method</b> rather than guessing.',
        "Step 1 — re-read the whole sentence with each surviving option substituted in fully, out loud in your head, not just glancing at the gap in isolation.",
        "Step 2 — check the option against the rest of the paragraph, not just the single sentence: does it still make sense with details mentioned earlier or later?",
        "Step 3 — check for subtler tense or number agreement clashes that a first read can miss, e.g. an option that agrees with a singular noun when the subject is actually plural.",
        "This method takes slightly longer than a single instinctive read, but it is the only reliable way to separate two options that are both superficially convincing.",
      ],
      conceptNote: "<b>Method:</b> re-read fully, then check the paragraph, then check agreement — apply the three steps in that order and stop as soon as one step rules an option out.",
      glossary: [
        { term: "elimination method", def: "a step-by-step process of ruling out options one at a time until only one remains" },
        { term: "paragraph context", def: "the sentences surrounding the gap, which can confirm or rule out an option even when the single sentence alone cannot" },
        { term: "agreement", def: "grammatical matching between words, e.g. a verb matching a singular or plural subject" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: NarrowingDownByEliminationDemo,
      worked: {
        question: "Choose the best fit: “The twins, who had trained together for years, ___ certain of victory.” (options: was, were, is, being) — the paragraph goes on to mention their coach had never seen either of them so confident.",
        fastMethod: "Check subject-verb agreement first: 'the twins' is plural, which immediately narrows the field before meaning is even considered.",
        steps: [
          "A first read might tempt you toward “was” if you only look at the nearby word “who”, but the true subject is “the twins” — plural.",
          "Rule out “was” and “is” — both are singular verb forms that don't agree with a plural subject; rule out “being” — the wrong word form for a main verb here.",
          "“were” is the only option that agrees with the plural subject “the twins”.",
          "Checking agreement, not just meaning, was what separated the correct option from the tempting “was”.",
        ],
        answer: "The best fit is <b>were</b> — the only option that correctly agrees with the plural subject “the twins”.",
      },
      selfCheck: { prompt: "True or false: when two options both seem to fit a sentence, checking the surrounding paragraph or subtler agreement clashes is a waste of time and pure guessing is just as reliable.", answer: "<b>False</b> — checking the paragraph context and subtler agreement clashes is a genuine method that reliably separates two equally plausible-looking options; it is not the same as guessing." },
      kind: "cloze-fill",
      questions: [
        {
          id: "ndbe-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Each of the students in the group",
          options: ["were required", "was required", "are required", "being required"],
          correctIdx: 1,
          after: "to submit their own report, not a shared one.",
          correction: "“was required” agrees with “Each”, which is grammatically singular even though it refers to a group — a subtler agreement clash that a quick read of “the students” can miss.",
          hint: "Look at the word directly before “of the students” to work out whether the true subject is singular or plural, not just the nearest noun.",
        },
        {
          id: "ndbe-q2",
          instruction: CLICK_INSTRUCTION,
          before: "The committee, having reviewed every application carefully,",
          options: ["has announced its decision", "have announced their decision", "announcing its decision", "had announce its decision"],
          correctIdx: 0,
          after: "to the whole school.",
          correction: "“has announced its decision” treats “the committee” as a single, singular body, which agrees with “its” — re-reading the full sentence with each option shows the others break either verb form or pronoun agreement.",
          hint: "Read each full option back into the sentence and check both the verb form and whether the pronoun matches a singular or plural subject.",
        },
        {
          id: "ndbe-q3",
          instruction: CLICK_INSTRUCTION,
          before: "None of the answers on the test",
          options: ["was correct", "were correct", "is correct", "being correct"],
          correctIdx: 0,
          after: ", which surprised the whole class.",
          correction: "“was correct” agrees with “None”, which is traditionally treated as singular in formal writing — checking this subtler agreement clash, not just the nearby plural “answers”, is what separates the correct option.",
          hint: "Focus on whether “None” itself is treated as singular or plural in formal writing, not the nearby plural noun “answers”.",
        },
      ],
      mistakes: [
        "Picking the first option that sounds acceptable on a single quick read, instead of substituting each surviving option back in fully and re-reading.",
        "Checking only the immediate sentence and missing a detail earlier or later in the paragraph that would rule an option in or out.",
      ],
      examTip: "When two options survive your first read, slow down deliberately: substitute each one in fully, check it against the wider paragraph, and check subject-verb agreement one more time before deciding.",
      searchTerms: ["elimination method", "agreement", "paragraph context", "narrowing down", "best fit", "complete the sentence"],
    },
  ],
};
