import type { TopicContent } from "../types";
import {
  BestFitConnectiveDemo,
  BestFitVerbPrecisionDemo,
  BestFitSentenceCombiningDemo,
  AlmostRightDistractorDemo,
} from "../notes-diagrams/complete-the-sentence-demos";

const CLICK_INSTRUCTION = "Click the word that best completes the sentence.";

export const completeTheSentenceTopic: TopicContent = {
  slug: "complete-the-sentence",
  subject: "English",
  subjectSlug: "english",
  title: "Grammar: Complete the Sentence & Best-Fit Word Choice",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "A different question style from “spot the mistake”: here every option is grammatically correct, but only one is the best fit for meaning, tone or logic. This module covers choosing the right connective for the logical relationship, picking a precise verb over a vague one, combining two short sentences smoothly, and recognising the “almost right” distractor that examiners plant deliberately.",
  subtopics: [
    {
      id: "best-fit-connective",
      title: "Choosing the Best-Fit Connective",
      tier: "Standard",
      objective: "Select the connective (however, therefore, moreover, meanwhile) that correctly signals the logical relationship between two ideas.",
      whyMatters: "every connective option in a best-fit question is a real, correctly spelled word — only the logic of the sentence tells you which one actually fits.",
      conceptTitle: "The relationship between ideas decides the word",
      conceptBullets: [
        'A <b style="color:#C9A24B">connective</b> signals how one idea relates to the next: contrast (however, yet), cause/result (therefore, so), addition (moreover, furthermore), or time (meanwhile, afterwards).',
        "Before choosing, work out the relationship in plain English first: does the second half agree, contradict, add to, or follow on from the first?",
        'Example: "The path was steep; <i>however</i>, they reached the summit" — signals a contrast between difficulty and success.',
        "Swapping in the wrong category of connective (e.g. “therefore” where a contrast is needed) makes the sentence read as if it doesn't quite make sense, even though every word is spelled correctly.",
      ],
      conceptNote: "<b>Test it:</b> say the relationship out loud in your own words first — “these two ideas disagree” or “this one caused that one” — then find the connective that matches.",
      glossary: [
        { term: "connective", def: "a linking word or phrase that shows how two ideas relate" },
        { term: "contrast connective", def: "signals disagreement between ideas (however, yet, although)" },
        { term: "cause/result connective", def: "signals one idea led to another (therefore, so, consequently)" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: BestFitConnectiveDemo,
      worked: {
        question: "Choose the best fit: “The instructions were confusing; ___, most of the class finished the task correctly.”",
        fastMethod: 'The second half contradicts the expectation set up by "confusing" — a contrast connective is needed.',
        steps: [
          "Work out the relationship: confusing instructions, but the class still succeeded — a contrast.",
          "Rule out addition connectives (moreover) and cause/result connectives (therefore) — neither signals contrast.",
          "“Nevertheless” or “however” both correctly signal contrast here.",
          "The best fit is a contrast connective, matching the surprising outcome.",
        ],
        answer: "The best fit is a <b>contrast connective</b> such as <b>however</b> or <b>nevertheless</b>.",
      },
      selfCheck: { prompt: "True or false: “therefore” is a good fit for linking two ideas that contradict each other.", answer: "<b>False</b> — “therefore” signals cause and result, not contrast; a contradicting pair of ideas needs a contrast connective like “however”." },
      kind: "cloze-fill",
      questions: [
        {
          id: "bfc-q1",
          instruction: CLICK_INSTRUCTION,
          before: "The team trained every day for a month;",
          options: ["however", "consequently", "meanwhile", "otherwise"],
          correctIdx: 1,
          after: ", they won the tournament with ease.",
          correction: "“consequently” signals that the win was a direct result of the month of training — a cause/result connective, not a contrast.",
          hint: "Decide whether the second half of the sentence contradicts the first half, or follows naturally from it.",
        },
        {
          id: "bfc-q2",
          instruction: CLICK_INSTRUCTION,
          before: "The recipe looked simple enough;",
          options: ["furthermore", "similarly", "in fact", "it proved surprisingly difficult to get right"],
          correctIdx: 2,
          after: ", it proved surprisingly difficult to get right.",
          correction: "“in fact” introduces a surprising correction to what was just said — the recipe seemed simple, but the truth was the opposite.",
          hint: "Look for the connective that signals the second half is correcting or sharpening the first half's claim.",
        },
        {
          id: "bfc-q3",
          instruction: CLICK_INSTRUCTION,
          before: "She practised her lines every evening;",
          options: ["moreover", "on the other hand", "as a result", "beforehand"],
          correctIdx: 2,
          after: ", she felt confident on stage.",
          correction: "“as a result” signals that her confidence came directly from the practice — a cause/result relationship.",
          hint: "Work out whether the second clause is a consequence of the first, an added extra point, or a contrast.",
        },
      ],
      mistakes: [
        "Picking a connective that sounds formal or impressive without checking whether its actual logical category (contrast, cause, addition, time) fits the sentence.",
        "Confusing addition connectives (moreover, furthermore) with cause/result connectives (therefore, consequently) because both sound similarly formal.",
      ],
      examTip: "State the relationship between the two halves of the sentence in your own plain words first, then match it to a connective — never choose by “sounds right” alone.",
      searchTerms: ["connective", "however", "therefore", "moreover", "best fit", "complete the sentence"],
    },
    {
      id: "best-fit-verb-precision",
      title: "Choosing the Best-Fit Verb for Precision",
      tier: "Standard",
      objective: "Choose the most precise verb for a sentence's meaning and tone, rather than a vague, general-purpose verb that could technically fit almost anywhere.",
      whyMatters: "best-fit questions often include a vague, all-purpose verb (went, did, got) as a tempting safe option — but exams reward the option that shows the most exact match to the sentence's meaning.",
      conceptTitle: "Vague verbs vs. precise verbs",
      conceptBullets: [
        'A <b style="color:#C9A24B">precise verb</b> carries specific meaning that matches the details already given in the sentence.',
        'A <b>vague verb</b> like "went", "did", "got" or "moved" is grammatically correct almost everywhere, which is exactly why it is rarely the best fit.',
        'Example: "exhausted… she <i>collapsed</i>" is a stronger, more precise match than "exhausted… she <i>went</i>" — collapsing specifically fits exhaustion.',
        "Look at the surrounding clues (an adjective, an adverb, the overall scene) — they usually point to one clearly best verb.",
      ],
      conceptNote: "<b>Test it:</b> if a verb option could just as easily slot into a completely unrelated sentence with no loss of meaning, it is probably too vague to be the best fit.",
      glossary: [
        { term: "precise verb", def: "carries specific meaning matched to the sentence's details" },
        { term: "vague verb", def: "a general-purpose verb that could fit almost any sentence" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: BestFitVerbPrecisionDemo,
      worked: {
        question: "Choose the best fit: “Furious at the decision, the coach ___ off the pitch.”",
        fastMethod: 'Look at "furious" — the verb needs to reflect anger, not just plain movement.',
        steps: [
          "Identify the clue word: “furious”, describing the coach's emotion.",
          "Rule out vague movement verbs like “walked” or “went”, which carry no emotional charge.",
          "“Stormed” carries the sense of angry, forceful movement that matches “furious”.",
          "The most precise fit reflects both the movement and the emotion.",
        ],
        answer: "The best fit is a precise verb such as <b>stormed</b>, not a vague verb like “went”.",
      },
      selfCheck: { prompt: "True or false: “did” is usually the best-fit verb choice in a sentence with a specific, vivid scene.", answer: "<b>False</b> — “did” is one of the vaguest possible verbs and is rarely the best fit when a sentence has vivid, specific details to match." },
      kind: "cloze-fill",
      questions: [
        {
          id: "bfv-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Starving after the long hike, the boys",
          options: ["ate", "devoured", "had", "did"],
          correctIdx: 1,
          after: "every last crumb of the picnic.",
          correction: "“devoured” precisely matches “starving” — it carries the sense of eating hungrily and quickly, unlike the vaguer “ate”, “had” or “did”.",
          hint: "Look at the clue word describing how hungry the boys were, and find the verb that matches that intensity.",
        },
        {
          id: "bfv-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Terrified by the thunder, the kitten",
          options: ["went", "moved", "scrambled", "did"],
          correctIdx: 2,
          after: "under the sofa.",
          correction: "“scrambled” precisely captures a frightened, hurried movement, matching “terrified” — the other options are too vague to carry that meaning.",
          hint: "Look at the clue word describing the kitten's fear, and find the verb that matches a frightened, hurried movement.",
        },
        {
          id: "bfv-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Delighted with her results, Priya",
          options: ["went", "beamed", "did", "had"],
          correctIdx: 1,
          after: "at her parents from the stage.",
          correction: "“beamed” precisely captures a delighted smile, matching “delighted” — the other options carry no expression of joy at all.",
          hint: "Look at the clue word describing Priya's happiness, and find the verb that matches that specific expression.",
        },
      ],
      mistakes: [
        "Defaulting to a safe, vague verb because it is grammatically correct everywhere, rather than checking which option matches the sentence's specific clues.",
        "Ignoring adjectives or adverbs elsewhere in the sentence that point clearly to one precise verb.",
      ],
      examTip: "Underline any emotion or intensity word already in the sentence first — it almost always points straight to the one precise verb that best matches it.",
      searchTerms: ["precise verb", "vague verb", "best fit", "word choice", "complete the sentence"],
    },
    {
      id: "best-fit-sentence-combining",
      title: "Combining Two Sentences Smoothly",
      tier: "Extension",
      objective: "Choose the option that combines two short, related sentences into one smooth sentence without clumsy repetition or incorrect punctuation.",
      whyMatters: "sentence-combining questions test whether you can spot the option that reads most naturally — a skill that also improves your own writing style.",
      conceptTitle: "Smooth combination, not just any combination",
      conceptBullets: [
        'When combining two short sentences, look for the option that uses a single, correctly placed <b style="color:#C9A24B">connective or conjunction</b> rather than repeating the same noun twice.',
        'Options that simply glue the two original sentences together with "and" often sound clumsy and repetitive compared to a properly subordinated version.',
        'Example: "The bridge was old. It held firm." combines more smoothly as "Although old, the bridge held firm" than as "The bridge was old and it held firm."',
        "Watch for options with a missing or misplaced comma, or a conjunction used incorrectly — these should be ruled out even if the overall idea is right.",
      ],
      conceptNote: "<b>Test it:</b> read each option aloud — the smoothest, least repetitive version that keeps every original idea is almost always the best fit.",
      glossary: [
        { term: "sentence combining", def: "joining two short sentences into one smooth, well-punctuated sentence" },
        { term: "subordination", def: "turning one idea into a dependent clause to link it smoothly to another" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: BestFitSentenceCombiningDemo,
      worked: {
        question: "Which combines these two ideas most smoothly: “The rain was heavy.” and “The match went ahead.”",
        fastMethod: "Look for the option that uses one clean connective instead of repeating “the match” or “the rain” twice.",
        steps: [
          "Identify the relationship between the two ideas: a contrast — heavy rain, yet the match still happened.",
          "Rule out any option that clumsily repeats a noun or strings the sentences together with a plain “and”.",
          "“Despite the heavy rain, the match went ahead” uses one connective and keeps both ideas intact.",
          "This is the smoothest, most natural combination.",
        ],
        answer: "The best fit is <b>“Despite the heavy rain, the match went ahead.”</b>",
      },
      selfCheck: { prompt: "True or false: joining two sentences with “and” is always the smoothest way to combine them.", answer: "<b>False</b> — “and” can work, but a connective that reflects the actual relationship between the ideas (contrast, cause, time) usually reads more smoothly and precisely." },
      kind: "cloze-fill",
      questions: [
        {
          id: "bfsc-q1",
          instruction: "Click the option that most smoothly combines the two ideas: 'The alarm rang loudly.' and 'No one in the house woke up.'",
          before: "",
          options: [
            "Despite the alarm ringing loudly, no one in the house woke up.",
            "The alarm rang loudly and no one in the house woke up.",
            "The alarm rang loudly, no one in the house, woke up.",
            "Ringing loudly the alarm, no one in the house woke up.",
          ],
          correctIdx: 0,
          after: "",
          correction: "“Despite the alarm ringing loudly, no one in the house woke up” cleanly signals the surprising contrast between a loud alarm and nobody waking, in one smooth clause.",
          hint: "Look for the option that signals the surprising contrast between a loud alarm and no one waking up.",
        },
        {
          id: "bfsc-q2",
          instruction: "Click the option that most smoothly combines the two ideas: 'The museum was free to enter.' and 'Very few visitors came that day.'",
          before: "",
          options: [
            "The museum, being free to enter, but very few visitors came that day.",
            "Although the museum was free to enter, very few visitors came that day.",
            "The museum was free to enter and very few visitors came that day, they did.",
            "Free the museum was to enter, very few visitors came that day.",
          ],
          correctIdx: 1,
          after: "",
          correction: "“Although the museum was free to enter, very few visitors came that day” combines the ideas smoothly, signalling the surprising contrast with one correctly placed connective.",
          hint: "Look for the option that signals the surprising contrast without repeating words awkwardly.",
        },
        {
          id: "bfsc-q3",
          instruction: "Click the option that most smoothly combines the two ideas: 'The path was narrow.' and 'The hikers walked single file.'",
          before: "",
          options: [
            "Because the path was narrow, the hikers walked single file.",
            "The path was narrow, the hikers walked single file, they did.",
            "Narrow the path, the hikers walked single file.",
            "The path was narrow and the hikers, single file, they walked.",
          ],
          correctIdx: 0,
          after: "",
          correction: "“Because the path was narrow, the hikers walked single file” shows the cause-and-result relationship clearly, in one smooth, correctly punctuated sentence.",
          hint: "Look for the option that shows the narrow path caused the hikers to walk single file, without any repetition.",
        },
      ],
      mistakes: [
        "Choosing an option purely because it is grammatically valid, without checking whether it is also the smoothest and least repetitive version.",
        "Missing an awkward repeated noun or a misplaced comma in an otherwise plausible-looking option.",
      ],
      examTip: "Read every option aloud in your head — clumsy repetition or a stumble in the rhythm is usually the fastest way to rule an option out.",
      searchTerms: ["sentence combining", "best fit", "subordination", "complete the sentence", "connective"],
    },
    {
      id: "almost-right-distractor",
      title: "Spotting the Almost-Right Distractor",
      tier: "Extension",
      objective: "Recognise when a best-fit option looks and sounds similar to the correct answer but has a subtly different precise meaning, and rule it out using the exact wording of the sentence.",
      whyMatters: "the hardest best-fit questions plant a near-synonym that looks almost identical to the right answer — spotting the precise difference in meaning is what separates a top mark from a near miss.",
      conceptTitle: "Similar-sounding is not the same as correct",
      conceptBullets: [
        'A <b style="color:#C9A24B">distractor</b> is a wrong option deliberately included because it looks tempting, not because it is correct.',
        'The "almost-right" distractor usually shares a root, sound or general feel with the correct answer, but carries a subtly different precise meaning.',
        'Example: "momentarily" (for a brief moment) is often confused with "shortly" (soon) — they sound like they should mean the same thing, but strictly don\'t.',
        "Always check the option against the exact clue given in the sentence, not just against how similar it sounds to what you expect.",
      ],
      conceptNote: "<b>Test it:</b> substitute the dictionary meaning of each close option back into the sentence — the almost-right distractor usually stops making precise sense once you do.",
      glossary: [
        { term: "distractor", def: "a deliberately tempting wrong answer option" },
        { term: "near-synonym", def: "a word that seems to mean the same as another but differs in a precise detail" },
      ],
      diagramLabel: "Interactive · Best-Fit Word",
      Diagram: AlmostRightDistractorDemo,
      worked: {
        question: "Choose the best fit: “The medicine should ___ the pain within a few minutes.” (options: alleviate, eliminate, alter, allocate)",
        fastMethod: "Check each option's precise meaning against “within a few minutes” — the medicine reduces pain, it doesn't necessarily remove it completely.",
        steps: [
          "Rule out “allocate” (to assign) and “alter” (to change) — neither fits pain relief at all.",
          "Compare the two closest options: “alleviate” (to ease/reduce) and “eliminate” (to remove entirely).",
          "The sentence only claims the pain improves “within a few minutes”, not that it vanishes completely — a stronger claim than the sentence supports.",
          "“Alleviate” is the more precisely supported fit.",
        ],
        answer: "The best fit is <b>alleviate</b>, not the near-synonym “eliminate”.",
      },
      selfCheck: { prompt: "True or false: two options that sound similar and are both real words must both be equally correct in a best-fit question.", answer: "<b>False</b> — a best-fit question usually has exactly one option whose precise meaning matches the sentence; a similar-sounding near-synonym is often included specifically as a trap." },
      kind: "cloze-fill",
      questions: [
        {
          id: "ard-q1",
          instruction: CLICK_INSTRUCTION,
          before: "The scientist's theory was later",
          options: ["disproved", "disapproved", "improved", "approved"],
          correctIdx: 0,
          after: "by new evidence.",
          correction: "“disproved” means shown to be false, matching “by new evidence” — “disapproved” is a tempting near-miss that actually means to object to something, not to prove it wrong.",
          hint: "Two of these options look and sound almost identical — check their precise dictionary meanings against “by new evidence”.",
        },
        {
          id: "ard-q2",
          instruction: CLICK_INSTRUCTION,
          before: "The new policy will",
          options: ["affect", "effect", "infect", "reflect"],
          correctIdx: 0,
          after: "how the whole school organises its timetable.",
          correction: "“affect” (a verb meaning to influence) is needed here — “effect” is a tempting near-miss, but it is usually a noun (a result), not a verb meaning to influence.",
          hint: "Two of these options sound identical when spoken — check which one is the verb meaning “to influence”.",
        },
        {
          id: "ard-q3",
          instruction: CLICK_INSTRUCTION,
          before: "The guide book gave a brief",
          options: ["historic", "historical", "history", "historically"],
          correctIdx: 1,
          after: "overview of the castle before the tour began.",
          correction: "“historical” (relating to history) correctly describes the overview — “historic” is a tempting near-miss, but it specifically means “important in history”, not simply “about history”.",
          hint: "Two of these options look almost identical — check which one means “relating to history” rather than “important in history”.",
        },
      ],
      mistakes: [
        "Picking the option that sounds most familiar or similar to the expected word, without checking its precise dictionary meaning.",
        "Assuming any grammatically valid, real-word option must be equally acceptable as the best fit.",
      ],
      examTip: "Whenever two options look almost identical, stop and define each one in your own words before picking — that single check catches most almost-right distractors.",
      searchTerms: ["distractor", "near-synonym", "best fit", "affect effect", "historic historical"],
    },
  ],
};
