import type { TopicContent } from "../types";
import {
  StoryShapeStagesDemo,
  OpeningHooksDemo,
  ShowDontTellDemo,
  SentenceVarietyDemo,
  DialoguePunctuationDemo,
  FigurativeLanguageDemo,
  VocabularyPrecisionDemo,
  EndingsThatResolveDemo,
  AdaptingToPromptTypeDemo,
} from "../notes-diagrams/core-writing-techniques-demos";

export const coreWritingTechniquesTopic: TopicContent = {
  slug: "core-writing-techniques",
  subject: "English",
  subjectSlug: "english",
  title: "Creative Writing: Core Writing Techniques",
  glyphs: ["✎", "„", "…", "¶", "★", "✒"],
  description:
    "The techniques in this module pay off whatever the actual prompt is — a title, a picture, or a 'continue this opening' task. Rather than practising one prompt format at a time, this module builds the transferable toolkit every strong creative-writing answer relies on: planning a shape under time pressure, opening strongly, showing rather than telling, controlling sentence rhythm, using dialogue and figurative language purposefully, choosing precise vocabulary, resolving the ending properly, and applying all of it confidently to any prompt format.",
  subtopics: [
    {
      id: "story-structure-time-pressure",
      title: "Story Structure Under Time Pressure",
      tier: "Foundation",
      objective: "Learn a simple four-part shape for planning any creative writing piece in under two minutes, whatever the prompt.",
      whyMatters: "a story that loses its shape under time pressure — rushing to write with no plan, or running out of time before an ending — is one of the most common ways strong writers lose marks in the 11+ writing task.",
      conceptTitle: "One shape, four beats, any prompt",
      conceptBullets: [
        '<b style="color:#C9A24B">Story shape</b> is a simple four-part plan — hook, build, turn, resolve — that works whatever the actual prompt is: a title, a picture, or "continue this opening."',
        "Spending two minutes planning these four beats before writing is time well spent: examiners reward a story that clearly goes somewhere over one that wanders without direction.",
        'The <b style="color:#C9A24B">turn</b> is the single most important beat — it\'s the moment something changes, goes wrong, or is discovered, and it\'s what stops a story from being a flat list of events.',
        "Planning the shape doesn't mean planning every sentence — just one short phrase per beat is enough to keep the whole piece on track.",
      ],
      conceptNote: "<b>Two-minute rule:</b> before writing a single sentence, jot down four short phrases — one for each beat of the shape — even in exam conditions this pays for itself.",
      glossary: [
        { term: "story shape", def: "a simple four-part plan: hook, build, turn, resolve" },
        { term: "hook", def: "the opening beat that pulls the reader in immediately" },
        { term: "turn", def: "the beat where something changes, goes wrong, or is discovered" },
        { term: "resolution", def: "the closing beat showing what changes as a result of the turn" },
      ],
      diagramLabel: "Interactive · Explore the Story Shape",
      Diagram: StoryShapeStagesDemo,
      worked: {
        question: 'Prompt: "Write a story about a decision that changed everything." Task: plan the four beats before writing.',
        fastMethod: "Pick the turn first — the single decision — then work outward, choosing what leads up to it and what follows from it.",
        steps: [
          "Decide the turn: what's the actual decision or change? e.g. a character chooses to speak up in class instead of staying silent.",
          "Choose the hook: how does the piece open in a way that pulls a reader in fast, without several fluffy warm-up sentences?",
          "Choose the build: what happens between the hook and the turn that makes the decision matter?",
          "Choose the resolution: what changes because of the decision, and how does the piece end?",
        ],
        answer: "A one-line plan: <b>hook</b> — nervous character in assembly; <b>build</b> — teacher asks a question no one answers; <b>turn</b> — character raises their hand despite the fear; <b>resolve</b> — the room's reaction, and how the character feels differently afterwards.",
      },
      selfCheck: {
        prompt: "True or false: the resolution should always be the longest part of a planned story.",
        answer: "<b>False</b> — the turn usually deserves the most detail; the resolution just needs to close the story properly, not stretch it out.",
      },
      questions: [
        {
          id: "sstp-q1",
          prompt: "In the four-part story shape, what is the name of the beat where something changes, goes wrong, or is discovered?",
          accept: ["turn", "the turn"],
          hint: "It's the beat that stops a story being a flat list of events.",
        },
        {
          id: "sstp-q2",
          prompt: "A student writes a story where five things happen in a row but nothing really changes or is decided. Which beat is missing?",
          accept: ["turn", "the turn"],
          hint: "Think about which beat gives a story its real point.",
        },
        {
          id: "sstp-q3",
          prompt: "Name the first beat of the four-part shape — the one that pulls the reader in at the very start.",
          accept: ["hook", "the hook", "opening hook"],
          hint: "It's the very first thing a reader meets.",
        },
      ],
      mistakes: [
        "Starting to write immediately without deciding the turn first, so the story drifts without a clear moment of change.",
        "Spending so long on the hook and build that there's no time left to write a proper resolution.",
      ],
      examTip: "If you're running low on time mid-story, jump straight to the turn and resolution rather than adding more build — examiners mark a complete, shorter story more kindly than an unfinished longer one.",
      searchTerms: ["story shape", "planning", "story structure", "time pressure", "hook build turn resolve"],
    },
    {
      id: "opening-hooks",
      title: "Opening Hooks That Work for Any Prompt",
      tier: "Foundation",
      objective: "Learn transferable techniques for starting a story strongly, so any prompt type becomes easier to open, not just the ones you already like.",
      whyMatters: "the opening line is often what an examiner's first impression is built on, and a strong hook works the same way whether the prompt is a title, a picture or a story-starter sentence.",
      conceptTitle: "Begin in the moment, not before it",
      conceptBullets: [
        'A strong <b style="color:#C9A24B">hook</b> drops the reader straight into a moment — action, dialogue, or a striking detail — rather than warming up with background information first.',
        'Starting with plain scene-setting ("It was a sunny day and Tom woke up...") delays the interesting part; starting mid-action or mid-feeling gets there immediately.',
        "The same hook techniques (starting with dialogue, starting with a single striking image, starting mid-action) work regardless of whether the prompt gives you a title, a picture or an opening line to continue — because a hook is about how you begin, not what you begin about.",
        "A hook doesn't need to explain everything — leaving a small question in the reader's mind (why is she running? what's in the box?) is often stronger than full explanation up front.",
      ],
      conceptNote: "<b>Test it:</b> read your opening sentence alone — if it could just as easily be sentence five, it isn't hooking hard enough; a true hook could only be sentence one.",
      glossary: [
        { term: "hook", def: "an opening that pulls the reader in immediately" },
        { term: "in medias res", def: "starting a story in the middle of the action" },
        { term: "scene-setting", def: "background description of time and place" },
      ],
      diagramLabel: "Interactive · Spot the Stronger Hook",
      Diagram: OpeningHooksDemo,
      worked: {
        question: 'Prompt: "Write a story titled \'The Last Ticket\'." Task: turn a flat opening into a hook.',
        fastMethod: "Delete the warm-up and start at the moment of tension or action the flat version was building towards.",
        steps: [
          "Flat version: 'It was a busy afternoon at the station and lots of people were waiting for trains.'",
          "Identify what's actually interesting here: presumably a ticket, and something about it being the last one.",
          "Cut straight to that moment: dialogue, action, or a striking detail involving the ticket itself.",
          'Rewrite: "Mo\'s fingers closed around the last ticket just as another hand grabbed for the same one."',
        ],
        answer: "The rewritten hook drops the reader into a <b>conflict already happening</b>, instead of describing the station first.",
      },
      selfCheck: {
        prompt: "True or false: a good hook should explain the whole situation before anything happens, so the reader isn't confused.",
        answer: "<b>False</b> — leaving some detail unexplained at first is a normal, effective hook technique; too much explanation up front usually weakens the opening.",
      },
      kind: "click-evidence",
      questions: [
        {
          id: "oh-q1",
          instruction: "Click the opening that hooks the reader most strongly for a story about a school fire drill.",
          passage: [
            "It was a normal Tuesday morning and everyone was in their usual lessons.",
            "The alarm screamed through the corridor before anyone had even sat down.",
            "Fire drills happened about twice a term at our school.",
            "Miss Ahmed always reminded us where the fire exits were.",
          ],
          correctIdx: 1,
          correction: '"the alarm screamed through the corridor before anyone had even sat down" drops the reader straight into the sudden moment — the others are background or generic information that delay the actual event.',
          hint: "Look for the sentence that starts with something happening, not background information about the school.",
        },
        {
          id: "oh-q2",
          instruction: "Click the opening that hooks the reader most strongly for a story about finding an old letter.",
          passage: [
            "Years ago, people used to write letters instead of texting.",
            "The attic hadn't been opened in a long time.",
            "Something was tucked behind the loose floorboard — an envelope, yellowed and sealed.",
            "Grandma's house was full of interesting old things.",
          ],
          correctIdx: 2,
          correction: '"something was tucked behind the loose floorboard — an envelope, yellowed and sealed" is a striking, specific detail that creates immediate curiosity — the others are vague background.',
          hint: "Look for the sentence with one specific, intriguing physical detail rather than a general statement.",
        },
        {
          id: "oh-q3",
          instruction: "Click the opening that hooks the reader most strongly for a story about a difficult decision in a football match.",
          passage: [
            "Football matches can be very exciting to watch and play.",
            '"Pass it!" someone screamed, but Jess\'s feet wouldn\'t move.',
            "The match had been going on for almost an hour.",
            "Jess had played football since she was six years old.",
          ],
          correctIdx: 1,
          correction: 'starting with shouted dialogue mid-action — "\'Pass it!\' someone screamed, but Jess\'s feet wouldn\'t move" — drops the reader straight into the tense moment; the others are generic background.',
          hint: "Look for the sentence combining dialogue with a character caught in a moment of hesitation.",
        },
      ],
      mistakes: [
        "Opening with generic background information (weather, time, general facts) that could belong to any story.",
        "Trying to explain the whole situation in the first sentence instead of trusting one striking detail or moment to hook the reader.",
      ],
      examTip: "Whatever the prompt type — title, picture or given opening line — plan your very first sentence separately and ask 'does this only work as sentence one?' before writing on.",
      searchTerms: ["opening hook", "hook", "story opening", "in medias res", "first sentence", "engaging opening"],
    },
    {
      id: "show-dont-tell",
      title: "Show, Don't Tell",
      tier: "Foundation",
      objective: "Convey a character's emotion through action, dialogue and detail rather than naming the feeling directly.",
      whyMatters: "'telling' a feeling (she was sad) reads as flat and is one of the most common reasons an otherwise well-planned story scores lower than it could.",
      conceptTitle: "Let the action carry the feeling",
      conceptBullets: [
        '<b style="color:#C9A24B">Showing</b> means conveying an emotion through what a character does, says or notices, instead of naming the feeling outright — that\'s <b style="color:#C9A24B">telling</b>.',
        'Example: "Ali was nervous" tells the feeling directly; "Ali\'s hands wouldn\'t stop shaking as he waited outside the office" shows it through physical detail.',
        "Showing usually takes a few more words than telling, but it lets the reader work the feeling out themselves — which is far more engaging and rewarded more highly.",
        "Telling isn't always wrong — a single 'telling' word can work well after a longer 'showing' passage, as a brief confirmation, rather than as the whole description.",
      ],
      conceptNote: "<b>Quick test:</b> if a sentence names a feeling word directly (happy, sad, angry, nervous), try replacing it with an action or physical detail that implies the same feeling instead.",
      glossary: [
        { term: "showing", def: "conveying feeling through action, dialogue or detail" },
        { term: "telling", def: "stating a feeling directly with a feeling-word" },
        { term: "physical detail", def: "a specific bodily action or reaction used to imply feeling" },
        { term: "body language", def: "physical behaviour that reveals feeling without stating it" },
      ],
      diagramLabel: "Interactive · Find the Telling Word",
      Diagram: ShowDontTellDemo,
      worked: {
        question: 'Turn the telling sentence "Priya was excited about the competition" into a showing sentence.',
        fastMethod: "Replace the feeling word with a specific physical action or detail that only an excited person would do.",
        steps: [
          "Identify the feeling word being told directly: excited.",
          "Think of a physical action that specifically suggests excitement, not just any feeling.",
          "Combine it with a concrete detail (what competition, what she does) to make it specific rather than generic.",
          "Rewrite without the feeling word.",
        ],
        answer: "Priya <b>checked her bag for the fourth time and could barely keep her feet still</b> as she waited for the competition to start.",
      },
      selfCheck: {
        prompt: "True or false: 'showing' a feeling always means using more words than 'telling' it.",
        answer: "<b>True, usually</b> — showing typically needs a specific action or detail, which takes more words than a single feeling word, but the payoff is a stronger, more engaging sentence.",
      },
      kind: "click-error",
      questions: [
        {
          id: "sdt-q1",
          instruction: "This sentence mixes showing and telling. Click the single word that 'tells' the feeling directly instead of showing it.",
          words: ["Zara", "was", "furious", "and", "slammed", "her", "book", "shut."],
          errorIdx: 2,
          correction: '"furious" states the feeling directly — the sentence would be stronger showing it entirely through the action of slamming the book shut, without naming the feeling at all.',
          hint: "Look for the one feeling-word that names an emotion outright, rather than an action.",
        },
        {
          id: "sdt-q2",
          instruction: "This sentence mixes showing and telling. Click the single word that 'tells' the feeling directly instead of showing it.",
          words: ["Sam", "felt", "embarrassed", "as", "his", "cheeks", "turned", "bright", "red."],
          errorIdx: 2,
          correction: '"embarrassed" tells the feeling directly — the rest of the sentence, "his cheeks turned bright red", already shows it, so the telling word is redundant.',
          hint: "Look for the direct feeling-word — the rest of the sentence already shows the same feeling through physical detail.",
        },
        {
          id: "sdt-q3",
          instruction: "This sentence mixes showing and telling. Click the single word that 'tells' the feeling directly instead of showing it.",
          words: ["Grandpa", "looked", "proud", "and", "puffed", "out", "his", "chest", "at", "the", "photo."],
          errorIdx: 2,
          correction: '"proud" states the feeling directly — "puffed out his chest" already shows the same feeling through action, making the telling word unnecessary.',
          hint: "Look for the direct feeling-word sitting right next to the physical action that already shows the same thing.",
        },
      ],
      mistakes: [
        "Naming the feeling directly and assuming that alone is descriptive enough, rather than adding a showing detail.",
        "Overloading a sentence with several feeling-words instead of picking one strong physical action or detail.",
      ],
      examTip: "Read back your first draft and circle every feeling-word (happy, sad, angry, scared, nervous, excited) — for each one, try replacing it with a specific action instead.",
      searchTerms: ["show dont tell", "showing not telling", "physical detail", "emotion", "description technique"],
    },
    {
      id: "sentence-variety-control",
      title: "Sentence Variety and Control",
      tier: "Standard",
      objective: "Vary sentence length and openings deliberately, avoiding repetitive 'then... then... then' structure, to control pace and impact.",
      whyMatters: "repetitive sentence structure is one of the fastest ways to flatten an otherwise strong story, while a short, sharp sentence placed at the right moment can carry real impact.",
      conceptTitle: "Length and openings as deliberate tools",
      conceptBullets: [
        '<b style="color:#C9A24B">Sentence variety</b> means deliberately mixing sentence lengths and openings, rather than writing every sentence the same way ("Then he... Then she... Then it...").',
        "A short sentence — even just two or three words — placed after several longer ones creates real impact at a key moment; length itself becomes a tool, not just a habit.",
        'Varying how sentences start (with a character\'s name, an action, a description, a single word) prevents the repetitive rhythm that comes from starting every sentence the same way — this is called a <b style="color:#C9A24B">sentence opener</b>.',
        "Control matters more than variety for its own sake — a whole paragraph of very short sentences can feel just as flat as one of long ones; the skill is choosing length to match the moment.",
      ],
      conceptNote: "<b>Listen for it:</b> read your own writing back and notice if several sentences in a row start the same way (Then, He, She) — that's the signal to restructure, not just to add more description.",
      glossary: [
        { term: "sentence variety", def: "deliberately mixing sentence lengths and openings" },
        { term: "sentence opener", def: "the word or phrase a sentence begins with" },
        { term: "short sentence for impact", def: "a short sentence placed after longer ones to create emphasis" },
      ],
      diagramLabel: "Interactive · Compare the Openers",
      Diagram: SentenceVarietyDemo,
      worked: {
        question: 'Fix the repetitive passage: "Then Leo opened the door. Then he stepped inside. Then he heard a noise. Then he froze."',
        fastMethod: "Keep the short final sentence for impact, but combine and vary the openings of the earlier ones.",
        steps: [
          "Identify the repeated pattern: every sentence starts with 'Then'.",
          "Combine some of the actions into one longer sentence with a varied opening.",
          "Keep the final short sentence as-is — it earns its impact by contrast with the longer sentence before it.",
          "Rewrite the passage.",
        ],
        answer: "Leo pushed the door open and stepped inside, footsteps echoing on the bare floorboards — until a noise from upstairs stopped him dead. <b>He froze.</b>",
      },
      selfCheck: {
        prompt: "True or false: a short sentence only has impact if every other sentence around it is also short.",
        answer: "<b>False</b> — a short sentence has the most impact when it follows one or more longer sentences, creating contrast.",
      },
      questions: [
        {
          id: "svc-q1",
          prompt: "Name the single word repeated at the start of every sentence in this passage: 'Then the rain started. Then the wind picked up. Then the lights went out.'",
          accept: ["then"],
          hint: "It's a small linking word used four times in a row.",
        },
        {
          id: "svc-q2",
          prompt: "In the pair of sentences 'The door creaked. He froze.' — what effect do the two very short sentences create?",
          accept: ["impact", "tension", "drama", "dramatic effect", "creates impact", "creates tension"],
          hint: "Think about pace — a short sentence right after a tense moment sharpens it.",
        },
        {
          id: "svc-q3",
          prompt: "Which part of speech can you start a sentence with instead of a name or pronoun, to add variety (e.g. 'Quickly, he ran...')?",
          accept: ["adverb"],
          hint: "Words ending in -ly are a common example.",
        },
      ],
      mistakes: [
        "Starting several sentences in a row with the same word (Then, He, She), creating a flat, repetitive rhythm.",
        "Using only short sentences throughout a passage, which loses the contrast that makes a short sentence powerful.",
      ],
      examTip: "In a final read-through, check the first word of each sentence in a paragraph — if three or more in a row match, restructure at least one.",
      searchTerms: ["sentence variety", "sentence openers", "short sentences", "repetitive structure", "sentence control"],
    },
    {
      id: "dialogue-punctuation-purpose",
      title: "Dialogue: Punctuation Rules and Purpose",
      tier: "Standard",
      objective: "Apply the core punctuation rules for dialogue correctly, and judge when dialogue earns its place in a story rather than just padding it out.",
      whyMatters: "dialogue punctuation errors (missing commas, wrong capitalisation, misplaced speech marks) are marked as technical accuracy errors even in an otherwise strong story, and padding dialogue that doesn't move the story on wastes valuable word count.",
      conceptTitle: "Correct on the page, purposeful on the page",
      conceptBullets: [
        '<b style="color:#C9A24B">Dialogue punctuation</b> follows fixed rules: speech marks around the exact words spoken, a comma (not a full stop) before the closing speech mark if a speech tag follows, and a new line for each new speaker.',
        'Example: "I don\'t believe it," she said. — note the comma inside the speech marks, and the lowercase "she" because the sentence continues after the speech.',
        "Dialogue earns its place when it reveals character, moves the plot forward, or creates tension — dialogue that only repeats information the reader already knows is padding.",
        'A useful test: could this line be cut without losing anything the reader needs? If yes, it\'s probably <b style="color:#C9A24B">padding</b> rather than purposeful dialogue.',
      ],
      conceptNote: "<b>Punctuation checklist:</b> speech marks around the spoken words only; comma (not full stop) before the closing speech mark if a tag follows; capital letter to start the spoken words; new speaker, new line.",
      glossary: [
        { term: "speech marks", def: "punctuation wrapped around the exact words spoken" },
        { term: "speech tag", def: "the part of a sentence naming who spoke, e.g. 'she said'" },
        { term: "padding", def: "dialogue or description that adds length without earning its place" },
        { term: "new line convention", def: "starting a new paragraph each time the speaker changes" },
      ],
      diagramLabel: "Interactive · Punctuate the Dialogue",
      Diagram: DialoguePunctuationDemo,
      worked: {
        question: "Punctuate correctly: he said i am not going without you",
        fastMethod: "Wrap the exact spoken words in speech marks, add a comma before the closing mark since a tag follows, and capitalise the first word spoken.",
        steps: [
          "Identify the exact words spoken: I am not going without you.",
          "Add speech marks around just those words.",
          "Add a comma before the closing speech mark, since 'he said' follows.",
          "Capitalise the first word of the spoken sentence.",
        ],
        answer: '"I am not going without you," he said.',
      },
      selfCheck: {
        prompt: "True or false: every line of dialogue should be followed by a speech tag like 'he said' or 'she asked'.",
        answer: "<b>False</b> — dialogue can stand without a tag when it's clear who's speaking, especially in a fast back-and-forth exchange; overusing tags can feel clumsy.",
      },
      kind: "click-error",
      questions: [
        {
          id: "dpp-q1",
          instruction: "Click the token with the punctuation mistake in this line of dialogue.",
          words: ["\"I'm", "ready.\"", "she", "said."],
          errorIdx: 1,
          correction: 'when a speech tag ("she said") follows spoken words in the same sentence, the punctuation before the closing speech mark should be a comma, not a full stop — it should read "I\'m ready," she said.',
          hint: "Look at the punctuation mark right before the closing speech mark.",
        },
        {
          id: "dpp-q2",
          instruction: "Click the token with the punctuation mistake in this line of dialogue.",
          words: ["\"I'm", "leaving,\"", "She", "said."],
          errorIdx: 2,
          correction: 'when a speech tag follows spoken words in the same sentence, it should not start with a capital letter unless it\'s a name — "She" should be lowercase "she" here.',
          hint: "Look at the word starting the speech tag right after the closing speech mark.",
        },
        {
          id: "dpp-q3",
          instruction: "Click the token with the punctuation mistake in this line of dialogue.",
          words: ["Marcus", "whispered,", "\"don't", "move.\""],
          errorIdx: 2,
          correction: 'the first word of the actual spoken words should start with a capital letter — it should read "Don\'t move."',
          hint: "Look at the very first word inside the speech marks.",
        },
      ],
      mistakes: [
        "Using a full stop instead of a comma before the closing speech mark when a speech tag follows.",
        "Adding dialogue purely to fill space, without it revealing character or moving the story forward.",
      ],
      examTip: "Before including a line of dialogue, ask what it does for the story — if the answer is 'nothing', cut it or replace it with a stronger line that reveals something.",
      searchTerms: ["dialogue punctuation", "speech marks", "speech tags", "direct speech", "dialogue purpose"],
    },
    {
      id: "figurative-language-toolkit",
      title: "Figurative Language Toolkit",
      tier: "Standard",
      objective: "Use simile, metaphor and personification purposefully to sharpen a specific image, rather than scattering them in decoratively.",
      whyMatters: "figurative language used with real precision earns marks for vocabulary and imagery, but clichéd or randomly-placed comparisons (as brave as a lion, the wind howled) are noticed by examiners as weak, generic writing.",
      conceptTitle: "One sharp image beats several vague ones",
      conceptBullets: [
        '<b style="color:#C9A24B">Figurative language</b> — simile, metaphor, personification — should sharpen one specific image, not be added just because "descriptive writing needs some."',
        'A <b style="color:#C9A24B">simile</b> compares using "like" or "as" (the fog crept in like a slow grey tide); a <b style="color:#C9A24B">metaphor</b> states one thing as another (the fog was a slow grey tide); <b style="color:#C9A24B">personification</b> gives a non-human thing human qualities (the fog crept, patient and unhurried).',
        "A cliché — a comparison used so often it's lost its power (as brave as a lion, cried a river of tears) — actively weakens writing; an original, specific comparison is worth far more even if it's simpler.",
        "One well-placed, original comparison beats three generic ones — restraint is a skill, not a lack of effort.",
      ],
      conceptNote: "<b>Originality test:</b> if you've heard a comparison before in lots of other writing, it's probably a cliché — try to invent your own specific image instead.",
      glossary: [
        { term: "simile", def: "a comparison using 'like' or 'as'" },
        { term: "metaphor", def: "stating one thing as another, without 'like' or 'as'" },
        { term: "personification", def: "giving a non-human thing human qualities" },
        { term: "cliché", def: "an overused comparison that has lost its power" },
      ],
      diagramLabel: "Interactive · Compare the Images",
      Diagram: FigurativeLanguageDemo,
      worked: {
        question: 'Improve the clichéd sentence: "The old house was as quiet as a mouse."',
        fastMethod: "Replace the cliché with an original image specific to the actual scene.",
        steps: [
          "Identify the cliché: 'as quiet as a mouse' is an overused simile.",
          "Think about what's actually true and specific about this house's silence.",
          "Choose a fresh image — perhaps personification, giving the silence an active quality.",
          "Rewrite with the new, original comparison.",
        ],
        answer: "The old house held its silence <b>like a held breath, waiting for someone to speak first</b>.",
      },
      selfCheck: {
        prompt: "True or false: using as many similes and metaphors as possible in a paragraph will always improve the writing.",
        answer: "<b>False</b> — one purposeful, original comparison is more effective than several crammed in; overuse can feel forced and distracts from the story.",
      },
      questions: [
        {
          id: "flt-q1",
          prompt: "Which type of figurative language uses 'like' or 'as' to compare two things (e.g. 'the rain fell like needles')?",
          accept: ["simile"],
          hint: "Its name comes from the Latin for 'similar'.",
        },
        {
          id: "flt-q2",
          prompt: "Which type of figurative language gives a non-human thing (like the wind or a house) human actions or feelings (e.g. 'the wind whispered through the trees')?",
          accept: ["personification"],
          hint: "Think about giving something non-human a 'person'-like quality — it's in the name.",
        },
        {
          id: "flt-q3",
          prompt: "What word describes an overused comparison that has lost its power, like 'as brave as a lion'?",
          accept: ["cliche", "cliché"],
          hint: "It's a comparison you've almost certainly heard many times before in other writing.",
        },
      ],
      mistakes: [
        "Reaching for a well-known cliché instead of inventing an original comparison specific to the actual scene.",
        "Cramming several similes or metaphors into one paragraph, which feels forced rather than purposeful.",
      ],
      examTip: "Aim for one strong, original comparison per key moment rather than scattering figurative language throughout — quality over quantity is rewarded.",
      searchTerms: ["figurative language", "simile", "metaphor", "personification", "cliche", "descriptive writing"],
    },
    {
      id: "vocabulary-precision",
      title: "Vocabulary Precision",
      tier: "Standard",
      objective: "Replace overused words (said, nice, good, walked) with precise alternatives, and recognise when NOT to over-elaborate.",
      whyMatters: "precise vocabulary is one of the most directly rewarded skills in the 11+ writing mark scheme, but over-elaborating every single word can slow a story down just as much as flat, repetitive vocabulary.",
      conceptTitle: "The word that does the most work",
      conceptBullets: [
        '<b style="color:#C9A24B">Precise vocabulary</b> means choosing the word that most exactly captures an action, feeling or quality — "murmured" instead of "said quietly", "sprinted" instead of "walked fast".',
        "Certain words (said, nice, good, walked, big, small) are so overused they carry almost no specific meaning left — replacing them with a more precise alternative instantly sharpens a sentence.",
        "Precision isn't about using the longest or fanciest word available — a showy synonym is not a better choice than a plain one if it doesn't fit the character or scene naturally.",
        "Not every plain word needs replacing — sometimes a simple word is exactly right, and over-elaborating every sentence with unnecessary synonyms can make writing sound forced rather than precise.",
      ],
      conceptNote: "<b>Balance rule:</b> upgrade a word when a more precise option genuinely adds meaning; leave it plain when the simple word is already doing its job clearly.",
      glossary: [
        { term: "precise vocabulary", def: "the word choice that most exactly captures meaning" },
        { term: "overused word", def: "a word used so often it carries little specific meaning (said, nice, good)" },
        { term: "synonym", def: "a word with a similar meaning to another" },
        { term: "over-elaboration", def: "replacing plain, correct words with unnecessary fancy synonyms" },
      ],
      diagramLabel: "Interactive · Find the Overused Word",
      Diagram: VocabularyPrecisionDemo,
      worked: {
        question: "Improve the sentence: '\"Get out,\" he said angrily.' without changing its meaning.",
        fastMethod: "Replace the generic speech verb with one that already carries the tone, then the adverb becomes unnecessary.",
        steps: [
          "Identify the overused word doing too little work: 'said', propped up by the adverb 'angrily'.",
          "Think of a speech verb that already implies anger on its own.",
          "Replace 'said angrily' with that single precise verb.",
          "Check the sentence still reads naturally, without extra padding.",
        ],
        answer: '"Get out," <b>he snapped</b>.',
      },
      selfCheck: {
        prompt: "True or false: replacing every single 'said' in a passage with a fancier synonym will always improve the writing.",
        answer: "<b>False</b> — a plain 'said' is often exactly right for neutral dialogue; over-elaborating every instance can feel forced rather than precise.",
      },
      kind: "click-error",
      questions: [
        {
          id: "vp-q1",
          instruction: "Click the overused word in this sentence that could be replaced with something more precise.",
          words: ["The", "weather", "was", "really", "nice", "on", "sports", "day."],
          errorIdx: 4,
          correction: '"nice" is vague and overused — a more precise word (mild, bright, crisp) would tell the reader exactly what kind of nice weather it was.',
          hint: "Look for the vague adjective that could describe almost anything.",
        },
        {
          id: "vp-q2",
          instruction: "Click the overused word in this sentence that could be replaced with something more precise.",
          words: ["Dan", "walked", "quickly", "across", "the", "yard", "to", "catch", "the", "bus."],
          errorIdx: 1,
          correction: '"walked" (propped up by "quickly") could be replaced with one precise verb like "hurried" or "dashed", which carries the same meaning in a single word.',
          hint: "Look for the verb that's propped up by an adverb, when one stronger verb could do the same job alone.",
        },
        {
          id: "vp-q3",
          instruction: "Click the overused word in this sentence that could be replaced with something more precise.",
          words: ["The", "cake", "tasted", "good", "and", "everyone", "asked", "for", "more."],
          errorIdx: 3,
          correction: '"good" is one of the most overused words in descriptive writing — a precise alternative (rich, buttery, sickly-sweet) would tell the reader exactly what made it good.',
          hint: "Look for the extremely common, vague adjective that could apply to almost any food.",
        },
      ],
      mistakes: [
        "Leaving heavily overused words (said, nice, good, walked) unreplaced when a more precise alternative was available and natural.",
        "Over-correcting by replacing every plain word with an unnecessarily elaborate synonym, even where the plain word was already the right choice.",
      ],
      examTip: "Keep a short mental list of your most personally overused words (often 'said', 'nice', 'good', 'walked', 'big') and deliberately check for them in a final read-through.",
      searchTerms: ["vocabulary precision", "overused words", "synonyms", "word choice", "said nice good walked"],
    },
    {
      id: "endings-that-resolve",
      title: "Endings That Resolve Properly",
      tier: "Extension",
      objective: "Plan and write an ending that properly resolves the story's central thread, rather than stopping abruptly mid-scene.",
      whyMatters: "a story that simply stops — often because time ran out — loses marks even if everything before it was strong; examiners specifically look for a planned, complete resolution.",
      conceptTitle: "Answer the question the story raised",
      conceptBullets: [
        '<b style="color:#C9A24B">Resolution</b> answers the question the story\'s turn raised — if the turn was a decision, the resolution shows its consequence; if it was a discovery, the resolution shows what changes because of it.',
        "An ending doesn't need to tie up every detail, but it does need to resolve the central thread the reader has been following — leaving that specific thread open reads as unfinished, not artistically ambiguous.",
        "Planning the ending before writing (see Story Structure) is the single most reliable way to avoid running out of time mid-scene — even a short, planned ending beats a longer story that just stops.",
        'A strong final sentence often uses a <b style="color:#C9A24B">mirrored ending</b> — echoing or contrasting with the opening hook — giving the whole piece a sense of shape rather than being just a sequence of events.',
      ],
      conceptNote: "<b>Time-check rule:</b> if you're two-thirds through your allotted time and still building, jump to the resolution — a complete, slightly shorter story scores far better than an unfinished longer one.",
      glossary: [
        { term: "resolution", def: "the closing part of a story that answers the question the turn raised" },
        { term: "central thread", def: "the main question or tension the reader has been following" },
        { term: "open ending", def: "an ending that fails to resolve the central thread, reading as unfinished" },
        { term: "mirrored ending", def: "a final sentence that echoes or contrasts with the opening" },
      ],
      diagramLabel: "Interactive · Which Ending Resolves?",
      Diagram: EndingsThatResolveDemo,
      worked: {
        question: 'A student\'s story ends: "...and just as Alex reached for the door handle, the bell rang for the end of the lesson." Improve this so it properly resolves.',
        fastMethod: "Identify what question the story's turn raised, then write one or two sentences that actually answer it, instead of cutting away at the tense moment.",
        steps: [
          "Identify the central thread: presumably whether Alex goes through the door (perhaps to confess something, or escape something).",
          "Notice the current ending cuts away before that question is answered — it reads as unfinished, not deliberately open.",
          "Decide the outcome: does Alex go through, or not, and what happens as a result?",
          "Write a short resolution that shows the consequence clearly.",
        ],
        answer: "Alex's hand closed around the handle — <b>and this time, they didn't let go. The door opened, and for the first time all week, so did Alex's courage.</b>",
      },
      selfCheck: {
        prompt: "True or false: it's fine to end a story right at the story's turn, without showing any consequence, as long as the turn itself is dramatic.",
        answer: "<b>False</b> — ending right at the turn, with no resolution shown, usually reads as an unfinished story rather than a deliberate stylistic choice.",
      },
      questions: [
        {
          id: "etr-q1",
          prompt: "What is the term for an ending that fails to answer the question the story's turn raised, so the story feels unfinished rather than deliberately open?",
          accept: ["open ending", "unresolved ending", "unfinished ending"],
          hint: "Think about what's missing — an answer to the question the story raised.",
        },
        {
          id: "etr-q2",
          prompt: "Name one technique for making a final sentence feel especially shaped, by connecting back to how the story began.",
          accept: ["mirrored ending", "echoing the opening", "echo the opening", "mirroring the opening"],
          hint: "Think about connecting the very last sentence back to the very first one.",
        },
        {
          id: "etr-q3",
          prompt: "If you notice you're running low on exam time while still in the 'build' stage, which stage should you jump to next?",
          accept: ["resolution", "the resolution", "ending"],
          hint: "Skip ahead to the part of the shape that actually closes the story.",
        },
      ],
      mistakes: [
        "Running out of time and simply stopping mid-scene, without a planned resolution.",
        "Introducing an entirely new, unrelated event in the final sentence instead of resolving the thread the reader has been following.",
      ],
      examTip: "Write your planned final sentence down during the two-minute plan, before starting the story — that way, even under time pressure, you have somewhere concrete to land.",
      searchTerms: ["story ending", "resolution", "conclusion", "closing a story", "mirrored ending"],
    },
    {
      id: "adapting-to-any-prompt-type",
      title: "Adapting the Toolkit to Any Prompt Type",
      tier: "Extension",
      objective: "Apply the same core techniques — shape, hooks, showing, dialogue, endings — confidently to any prompt format, so no single format feels harder than another.",
      whyMatters: "11+ writing tasks vary the prompt format between papers and even between questions on the same paper — students who've only practised one format lose confidence the moment the format changes, even though the underlying skills are identical.",
      conceptTitle: "Only the first step ever changes",
      conceptBullets: [
        'The same core toolkit — <b style="color:#C9A24B">story shape</b>, hooks, showing, sentence variety, purposeful dialogue, figurative language, precise vocabulary, resolved endings — applies whatever the prompt format is.',
        'A <b style="color:#C9A24B">title-based prompt</b> just needs you to invent the whole situation before applying the same shape; a <b style="color:#C9A24B">picture-based prompt</b> gives you a starting image to build the hook and setting from; a "continue this opening" prompt gives you the hook already written, so planning starts from the build.',
        "The technique that differs by format is only the very first planning step (inventing vs. interpreting vs. continuing) — everything after that first step uses exactly the same four-part shape and the same craft techniques.",
        "Practising on the format you find hardest using techniques you already trust (rather than avoiding it) is the fastest way to close a specific weakness, since the underlying skills transfer completely.",
      ],
      conceptNote: "<b>Reframe it:</b> a disliked prompt format isn't a different skill to learn — it's the same shape and toolkit, just with a different first planning step.",
      glossary: [
        { term: "prompt format", def: "the way a writing task is presented — title, picture, or continuation" },
        { term: "title-based prompt", def: "a prompt giving only a title, requiring the whole situation to be invented" },
        { term: "picture-based prompt", def: "a prompt giving an image to build the setting and hook from" },
        { term: "continuation prompt", def: "a prompt giving an opening sentence to continue from" },
      ],
      diagramLabel: "Interactive · Same Toolkit, Different Prompt",
      Diagram: AdaptingToPromptTypeDemo,
      worked: {
        question: "Same student idea (a character who finally stands up to a bully) applied to three different prompt formats. How does the planning step change each time?",
        fastMethod: "Only the very first step changes; the four-part shape and craft techniques stay identical after that.",
        steps: [
          "Title-based (e.g. 'Finding Courage'): invent the whole situation first, then plan hook/build/turn/resolve as normal.",
          "Picture-based (e.g. a photo of an empty corridor): use the image to suggest the setting and mood for the hook, then plan the rest of the shape as normal.",
          "Continuation prompt (given opening sentence about the corridor): the hook is already written for you — start planning from the build onward.",
          "In all three cases, the same turn (standing up to the bully) and the same craft techniques (showing, dialogue, precise vocabulary) apply identically.",
        ],
        answer: "Only the <b>first planning step changes</b> between formats — the shape and toolkit that follow are exactly the same.",
      },
      selfCheck: {
        prompt: "True or false: a student who is confident writing from a title should expect picture-based and continuation prompts to need a completely different set of skills.",
        answer: "<b>False</b> — only the very first planning step differs; the same shape and craft toolkit apply to every prompt format.",
      },
      kind: "click-evidence",
      questions: [
        {
          id: "aapt-q1",
          instruction: "For a picture-based prompt (a photo of a locked gate at dusk), click the planning step that should come FIRST.",
          passage: [
            "Decide what the picture suggests for setting and mood, to build the hook.",
            "Write the resolution.",
            "Choose precise vocabulary for the middle paragraphs.",
            "Plan the figurative language for the final sentence.",
          ],
          correctIdx: 0,
          correction: "for a picture-based prompt, the image itself is the natural starting point for the hook and setting — everything else in the shape follows from there.",
          hint: "Think about what a picture prompt actually gives you that a title prompt doesn't.",
        },
        {
          id: "aapt-q2",
          instruction: "For a 'continue this opening' prompt where the hook sentence is already given, click the planning step that should come FIRST.",
          passage: [
            "Invent an opening hook from scratch.",
            "Decide what happens next (the build), since the hook is already provided.",
            "Choose a title for the piece.",
            "Draw a picture to plan from.",
          ],
          correctIdx: 1,
          correction: "when the opening is already given, planning starts from the build — there's no need to invent a hook that already exists.",
          hint: "Remember that this format gives you one of the four beats already written.",
        },
        {
          id: "aapt-q3",
          instruction: "For a title-based prompt like 'The Empty Chair', click the planning step that should come FIRST.",
          passage: [
            "Invent a specific situation the title could apply to, before planning the four-part shape.",
            "Skip straight to writing the resolution.",
            "Assume the reader already knows the situation.",
            "Copy a structure used for a picture-based prompt without adapting it.",
          ],
          correctIdx: 0,
          correction: "a title gives no situation at all, so the very first step is inventing one specific scenario the title could describe — only then can the usual four-part shape be planned.",
          hint: "Think about what information a bare title actually gives you, compared with a picture or a given opening line.",
        },
      ],
      mistakes: [
        "Assuming a disliked prompt format needs entirely new skills, rather than the same toolkit with a different starting step.",
        "Skipping the format-specific first step (inventing a situation for a title, reading the image for a picture) and jumping straight into writing.",
      ],
      examTip: "Practise the same story idea across all three prompt formats once — you'll see the shape and technique stay identical, and only the opening planning step changes.",
      searchTerms: ["prompt types", "title based prompt", "picture prompt", "continuation prompt", "exam formats", "transferable writing skills"],
    },
  ],
};
