import type { TopicContent } from "../types";
import {
  WordClassCluesDemo,
  ArticleDeterminerCluesDemo,
  VerbTenseCluesDemo,
  SingularPluralAgreementCluesDemo,
  PrepositionCluesDemo,
  ConnectiveLinkingCluesDemo,
  CombinedGrammarMeaningCluesDemo,
  PronounReferenceCluesDemo,
  AmbiguousGapsDemo,
} from "../notes-diagrams/grammatical-cloze-demos";

const CLICK_INSTRUCTION = "Click the word that correctly fills the gap.";

export const grammaticalClozeStrategyTopic: TopicContent = {
  slug: "grammatical-cloze-strategy",
  subject: "English",
  subjectSlug: "english",
  title: "Cloze: Grammatical Gap-Filling Strategy",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "Once you know what a cloze test is, the next skill is using the sentence's own grammar to narrow down the answer before even thinking about meaning. This module covers reading the gap's word class from its position, using verb tense clues that run across a whole passage, checking singular/plural agreement, and combining grammar clues with meaning clues on harder questions.",
  subtopics: [
    {
      id: "word-class-clues",
      title: "Using Word Class Clues",
      tier: "Foundation",
      objective: "Work out what part of speech (noun, verb, adjective, adverb) a gap needs, purely from its position in the sentence, before considering meaning.",
      whyMatters: "narrowing down the word class first instantly rules out at least half of a typical option bank, making the final meaning-based choice much faster and safer.",
      conceptTitle: "The gap's position reveals its job",
      conceptBullets: [
        'The words directly around a <b style="color:#C9A24B">gap</b> — what comes just before and just after it — usually reveal what part of speech is needed.',
        'A gap right after a linking verb like "looked", "seemed" or "felt" almost always needs an adjective, not a noun or adverb.',
        'A gap right before a noun with no verb in between often needs an adjective describing that noun.',
        "Checking word class first is faster than reading every option for meaning — it usually eliminates two or three options immediately.",
      ],
      conceptNote: "<b>Test it:</b> before reading for meaning, ask “does this gap need a thing, an action, a description, or a description-of-an-action?” — that's the word class question.",
      glossary: [
        { term: "word class", def: "the grammatical category of a word (noun, verb, adjective, adverb)" },
        { term: "linking verb", def: "a verb like looked/seemed/felt that connects a subject to a description" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: WordClassCluesDemo,
      worked: {
        question: "Which word class does the gap need? “The music sounded ___ throughout the whole concert.”",
        fastMethod: '"sounded" is a linking verb, so the gap needs a word describing the music — an adjective.',
        steps: [
          "Identify the word right before the gap: “sounded”, a linking verb.",
          "Linking verbs connect a subject to a description, which means an adjective is needed.",
          "Rule out any noun, verb or adverb options immediately.",
          "Only an adjective (e.g. “beautiful”, “harsh”) can correctly fill this gap.",
        ],
        answer: "The gap needs an <b>adjective</b>, because it follows the linking verb “sounded”.",
      },
      selfCheck: { prompt: "True or false: a gap directly after the word “quickly” always needs another adverb.", answer: "<b>False</b> — the word class needed depends on the gap's own position and job in the sentence, not simply on matching the word next to it." },
      kind: "cloze-fill",
      questions: [
        {
          id: "wcc-q1",
          instruction: CLICK_INSTRUCTION,
          before: "The old barn door creaked",
          options: ["loud", "loudness", "loudly", "loudest"],
          correctIdx: 2,
          after: "as the wind pushed it open.",
          correction: "the gap describes how the door creaked (a verb), so it needs an adverb: “loudly” — not the adjective, noun or superlative forms.",
          hint: "Check what job the gap does here — is it describing a noun, or describing how an action was done?",
        },
        {
          id: "wcc-q2",
          instruction: CLICK_INSTRUCTION,
          before: "A sudden",
          options: ["silence", "silent", "silently", "silence's"],
          correctIdx: 0,
          after: "fell across the crowded hall.",
          correction: "the gap sits between an adjective (“sudden”) and a verb (“fell”), which means it needs a noun as the subject of the sentence: “silence”.",
          hint: "Check what part of speech comes right before the gap, and what the sentence needs as its subject.",
        },
        {
          id: "wcc-q3",
          instruction: CLICK_INSTRUCTION,
          before: "The instructions on the box were surprisingly",
          options: ["confuse", "confusion", "confusing", "confusingly"],
          correctIdx: 2,
          after: ", even for the adults.",
          correction: "the gap sits right after the linking verb “were”, so it needs an adjective describing the instructions: “confusing”.",
          hint: "Check what verb comes right before the gap — does it link the subject to a description?",
        },
      ],
      mistakes: [
        "Jumping straight to meaning without first checking what word class the sentence's grammar actually requires.",
        "Confusing similar-looking word-class options (confusing/confusingly, silence/silently) without checking their exact grammatical job in the sentence.",
      ],
      examTip: "Before reading the options for meaning, spend two seconds checking the word directly before and after the gap — that alone usually rules out half the option bank.",
      searchTerms: ["word class", "cloze", "noun", "verb", "adjective", "adverb", "grammar clue"],
    },
    {
      id: "article-determiner-clues",
      title: "Using Article and Determiner Clues",
      tier: "Foundation",
      objective: "Use the sound and specificity signalled by articles and determiners (a/an, the, this/these/that/those) to eliminate gap-fill options that don't match.",
      whyMatters: "articles and determiners are among the simplest, fastest clues in cloze — checking them first can immediately remove options that look plausible but start with the wrong sound or number.",
      conceptTitle: "Small words, big clues",
      conceptBullets: [
        '<b style="color:#C9A24B">Articles</b> ("a", "an", "the") and determiners ("this", "these", "that", "those") sit right next to a gap and rule out options before you even think about meaning.',
        '"a" needs a word starting with a consonant sound; "an" needs a word starting with a vowel sound — this alone can eliminate wrong options in a bank.',
        '"the" points to something specific already known or named; "a"/"an" points to something general or being introduced for the first time.',
        '"this"/"these" go with singular/plural nouns that are near; "that"/"those" go with singular/plural nouns that are further away — a determiner already in the sentence can rule out singular or plural options.',
      ],
      conceptNote: "<b>Test it:</b> read the article or determiner right next to the gap first — it tells you the sound, number, and specificity the correct option must match.",
      glossary: [
        { term: "article", def: "a, an or the — a small word that introduces a noun" },
        { term: "determiner", def: "a word like this/these/that/those that specifies which noun is meant" },
        { term: "vowel sound", def: "the sound a word starts with that needs “an” rather than “a”" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: ArticleDeterminerCluesDemo,
      worked: {
        question: "Which word fits? “She had never seen ___ honest answer like it.” (options: a, an, the, that)",
        fastMethod: '"honest" starts with a vowel sound (the silent h), so only "an" can fit — no need to consider meaning at all.',
        steps: [
          "Look at the word straight after the gap: “honest”.",
          "Check its starting sound: the h is silent, so it starts with a vowel sound.",
          "“a” needs a consonant sound, and “the”/“that” both signal something specific/already known, which doesn't fit a first-time general mention.",
          "Only “an” matches a vowel-sound word being introduced for the first time.",
        ],
        answer: "The gap needs <b>an</b>, because “honest” starts with a vowel sound and is being mentioned for the first time.",
      },
      selfCheck: { prompt: "True or false: “an” is used whenever the following word starts with a vowel letter, regardless of how it sounds.", answer: "<b>False</b> — “an” depends on the vowel *sound*, not the vowel letter; e.g. “a university” uses “a” because “university” starts with a consonant sound (“yoo”)." },
      kind: "cloze-fill",
      questions: [
        {
          id: "adc-q1",
          instruction: CLICK_INSTRUCTION,
          before: "We watched",
          options: ["a", "an", "the", "those"],
          correctIdx: 1,
          after: "umbrella blow away down the street.",
          correction: "“umbrella” starts with a vowel sound, so the gap needs “an”, not “a” — and “the”/“those” would wrongly suggest an umbrella already mentioned, or more than one.",
          hint: "Check the very next word after the gap — what sound does it start with?",
        },
        {
          id: "adc-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Yesterday a strange dog followed us home.",
          options: ["A", "An", "The", "Those"],
          correctIdx: 2,
          after: "dog waited patiently outside our gate all night.",
          correction: "the dog has already been introduced earlier in the sentence, so the gap needs “The” to refer back to that specific, already-known dog, not “A”/“An”, which would introduce a new one.",
          hint: "Has the noun after the gap already been mentioned earlier, or is it being introduced for the first time?",
        },
        {
          id: "adc-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Look at",
          options: ["this", "these", "that", "those"],
          correctIdx: 3,
          after: "mountains in the distance — we won't reach them until tomorrow.",
          correction: "“mountains” is plural and “in the distance” signals something far away, so the gap needs the plural, far determiner “those”, not a near or singular option.",
          hint: "Check whether the noun after the gap is singular or plural, and whether the sentence signals something near or far away.",
        },
      ],
      mistakes: [
        "Choosing “a” or “an” based on the letter a word starts with instead of the sound it actually makes.",
        "Using “the” for something being mentioned for the first time, when only “a”/“an” fits a first, general mention.",
      ],
      examTip: "Read the word immediately next to the gap for its sound and number before anything else — articles and determiners are the fastest clue in the whole cloze toolkit.",
      searchTerms: ["article", "determiner", "a an the", "this these that those", "cloze", "vowel sound"],
    },
    {
      id: "verb-tense-clues",
      title: "Using Verb Tense Clues Across a Passage",
      tier: "Standard",
      objective: "Use tense signals elsewhere in a passage (time words, other verbs) to choose the correct verb form for a gap.",
      whyMatters: "cloze passages are connected prose, so a tense clue set up in one sentence — a time word like “yesterday”, or another verb nearby — usually applies to gaps much later in the same passage too.",
      conceptTitle: "One clue can govern the whole passage",
      conceptBullets: [
        'A single <b style="color:#C9A24B">time word</b> — "yesterday", "last week", "tomorrow" — often sets the tense for an entire passage, not just the sentence it appears in.',
        "Other verbs already in the passage (not in a gap) are reliable evidence for which tense the whole piece is written in.",
        'Example: if a passage starts "Yesterday, the whole class..." every later gap describing an action should also be past tense, even several sentences on.',
        "Check for a tense shift only if the passage explicitly signals one (e.g. moving into dialogue, or a new time word appearing).",
      ],
      conceptNote: "<b>Test it:</b> before filling any verb-shaped gap, scan the passage for time words or other verbs — they tell you which tense every gap should match.",
      glossary: [
        { term: "tense", def: "the verb form that shows when an action happens (past, present, future)" },
        { term: "time word", def: "a word like yesterday, tomorrow, or now that signals the passage's tense" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: VerbTenseCluesDemo,
      worked: {
        question: "Which tense does this gap need? “Last summer, our family ___ to the coast for a fortnight.”",
        fastMethod: '"last summer" is a clear past time word, so a past-tense verb is needed.',
        steps: [
          "Scan the sentence for a time clue: “last summer”.",
          "This signals the whole sentence describes something that already happened.",
          "The gap needs a past-tense verb to match.",
          "“Travelled” or “went” would both correctly fill the gap in the past tense.",
        ],
        answer: "The gap needs a <b>past-tense verb</b>, matching the time clue “last summer”.",
      },
      selfCheck: { prompt: "True or false: a time word at the very start of a passage can only affect the tense of the sentence it appears in, not later sentences.", answer: "<b>False</b> — a tense clue at the start of a passage usually governs every later sentence too, since cloze passages are connected prose describing a single timeframe." },
      kind: "cloze-fill",
      questions: [
        {
          id: "vtc-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Every morning last winter, the postman",
          options: ["arrives", "arrived", "arriving", "will arrive"],
          correctIdx: 1,
          after: "just before eight o'clock.",
          correction: "“last winter” is a past time clue, so the gap needs the past-tense verb “arrived”, not a present or future form.",
          hint: "Check the time clue at the start of the sentence — what tense does it set up for the rest of the sentence?",
        },
        {
          id: "vtc-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Next term, the whole school",
          options: ["moved", "moves", "will move", "was moving"],
          correctIdx: 2,
          after: "to the new building on the high street.",
          correction: "“next term” is a future time clue, so the gap needs a future-tense verb form: “will move”.",
          hint: "Check the time clue at the start of the sentence — does it point to the past, present or future?",
        },
        {
          id: "vtc-q3",
          instruction: CLICK_INSTRUCTION,
          before: "By the time the fire engine arrived, the flames",
          options: ["spread", "were spreading", "will spread", "spreads"],
          correctIdx: 1,
          after: "across the whole roof.",
          correction: "the surrounding clause (“by the time... arrived”) is past tense, and the gap describes an ongoing action happening at that past moment, so it needs the past continuous form: “were spreading”.",
          hint: "Check the verb tense already used elsewhere in the sentence (“arrived”) and whether the gap describes an action still in progress at that moment.",
        },
      ],
      mistakes: [
        "Only checking the words immediately next to a gap and missing a tense clue set up several sentences earlier in the passage.",
        "Defaulting to a present-tense verb because it feels like the “safe” choice, without checking the passage's actual timeframe.",
      ],
      examTip: "Before filling any gap that needs a verb, quickly scan the whole passage (not just the current sentence) for time words — they often govern gaps much later on.",
      searchTerms: ["verb tense", "cloze", "time word", "past tense", "future tense", "passage"],
    },
    {
      id: "singular-plural-agreement-clues",
      title: "Using Singular/Plural Agreement Clues",
      tier: "Standard",
      objective: "Use the number (singular or plural) of a gap's subject to choose the correct verb form, including with tricky quantifiers like “both” and “each”.",
      whyMatters: "cloze gaps that need a verb almost always test agreement alongside tense, and quantifier words like “both”, “each” and “neither” are common exam traps within this skill.",
      conceptTitle: "Find the subject's number first",
      conceptBullets: [
        'Before choosing a verb form for a gap, identify whether its <b style="color:#C9A24B">subject</b> is singular or plural.',
        '"Both" and "several" signal a plural subject; "each", "every" and "neither" signal a singular subject, even when followed by a plural-looking phrase.',
        'Example: "Both of the twins were chosen" is correct because "both" makes the subject plural, even though "of the twins" comes in between.',
        "This clue works alongside tense — a gap can need to be both plural and past tense at once.",
      ],
      conceptNote: "<b>Test it:</b> replace the subject phrase with “they” (plural) or “it”/“he”/“she” (singular) and see which verb form naturally follows.",
      glossary: [
        { term: "subject", def: "who or what is doing the verb in a sentence" },
        { term: "quantifier", def: "a word like both, each, neither that specifies an amount, and affects verb agreement" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: SingularPluralAgreementCluesDemo,
      worked: {
        question: "Which verb form fits? “Neither of the answers ___ correct.”",
        fastMethod: '"neither" is always singular, however plural the phrase after it sounds.',
        steps: [
          "Identify the subject: “neither”, a quantifier.",
          "Recall that “neither”, like “each” and “every”, is always grammatically singular.",
          "The gap needs a singular verb form to match.",
          "“Was” correctly matches the singular subject “neither”.",
        ],
        answer: "The gap needs the singular verb form <b>was</b>, because “neither” is always singular.",
      },
      selfCheck: { prompt: "True or false: “each of the students” takes a plural verb because “students” is plural.", answer: "<b>False</b> — “each” is always singular, regardless of what plural phrase follows it; the verb must be singular too." },
      kind: "cloze-fill",
      questions: [
        {
          id: "spac-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Each of the students",
          options: ["were given", "was given", "have given", "are given"],
          correctIdx: 1,
          after: "a certificate at the end of the course.",
          correction: "“each” is always singular, however plural the phrase “of the students” sounds — the gap needs the singular form “was given”.",
          hint: "Check the quantifier at the start of the sentence — is it one of the words that's always singular?",
        },
        {
          id: "spac-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Several of the paintings",
          options: ["was damaged", "is damaged", "were damaged", "has been damaged"],
          correctIdx: 2,
          after: "in the move to the new gallery.",
          correction: "“several” signals a plural subject, so the gap needs the plural verb form “were damaged”.",
          hint: "Check the quantifier at the start of the sentence — does it signal one thing or many?",
        },
        {
          id: "spac-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Neither of the routes",
          options: ["were suitable", "was suitable", "are suitable", "have been suitable"],
          correctIdx: 1,
          after: "for a wheelchair.",
          correction: "“neither” is always singular, however plural “of the routes” sounds — the gap needs the singular verb form “was suitable”.",
          hint: "Check the quantifier at the start of the sentence — is it one of the words that's always singular, however plural it sounds?",
        },
      ],
      mistakes: [
        "Matching the verb to the nearer plural-sounding noun (“the twins”, “the students”) instead of the true quantifier subject (“each”, “neither”).",
        "Forgetting that “each”, “every” and “neither” are always singular, however plural the rest of the phrase sounds.",
      ],
      examTip: "Whenever a gap's subject starts with “each”, “every”, “neither”, “both” or “several”, check that specific word's fixed number first — it always overrides how plural the rest of the phrase sounds.",
      searchTerms: ["subject-verb agreement", "cloze", "each", "both", "neither", "quantifier", "singular plural"],
    },
    {
      id: "preposition-clues",
      title: "Using Preposition Clues in Cloze Gaps",
      tier: "Standard",
      objective: "Use a preposition already in the sentence — or work out which preposition a gap needs — to identify the one word or fixed phrase that correctly completes the sentence.",
      whyMatters: "many cloze gaps are part of a fixed phrase with one specific preposition, so spotting the preposition already there (or needed) narrows the option bank to the single word that phrase actually demands.",
      conceptTitle: "Fixed phrases pair specific words with specific prepositions",
      conceptBullets: [
        'Many English words are locked into a <b style="color:#C9A24B">fixed pairing</b> with one particular preposition — "interested in", "afraid of", "good at" — and only that pairing sounds right.',
        "If the preposition is already sitting in the sentence, work backwards: which of the gap's options is normally followed by that exact preposition?",
        "If the gap itself needs a preposition, check the word before it — many verbs and adjectives only ever pair with one preposition, not several.",
        'Example: “keen ___ football” only ever takes “on”, never “about” or “for”, however natural those might sound elsewhere.',
      ],
      conceptNote: "<b>Test it:</b> find the preposition nearest the gap (before or after it), then ask which option is the one word that fixed phrase is always paired with.",
      glossary: [
        { term: "preposition", def: "a small word like in, on, at, of that links a noun/pronoun to the rest of the sentence" },
        { term: "fixed phrase", def: "a set combination of a word and a particular preposition that doesn't change (e.g. “afraid of”)" },
        { term: "dependent preposition", def: "the one preposition a specific word is always followed by" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: PrepositionCluesDemo,
      worked: {
        question: "Which word fits? “The twins have always been very ___ of each other's achievements.” (options: proud, pleased, glad, happy)",
        fastMethod: '"of" straight after the gap is the giveaway — only "proud" is fixed to pair with "of" in this sense.',
        steps: [
          "Look at the preposition already in the sentence, right after the gap: “of”.",
          "Check each option's normal fixed pairing: “pleased with”, “glad about”, “happy for” — none pair with “of” in this sense.",
          "“proud of” is the one fixed pairing that matches.",
          "Only “proud” correctly completes this fixed phrase.",
        ],
        answer: "The gap needs <b>proud</b>, because “proud of” is the fixed pairing that matches the preposition already given.",
      },
      selfCheck: { prompt: "True or false: “interested” can correctly pair with either “in” or “about” with no difference in correctness.", answer: "<b>False</b> — “interested” has one fixed dependent preposition, “in” (“interested in”); “interested about” is not a standard fixed phrase." },
      kind: "cloze-fill",
      questions: [
        {
          id: "pc-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Our teacher is extremely keen",
          options: ["on", "for", "with", "about"],
          correctIdx: 0,
          after: "improving classroom recycling this term.",
          correction: "“keen” has one fixed dependent preposition, “on” — “keen on” — not “for”, “with” or “about”, however natural they might sound.",
          hint: "Check the adjective right before the gap — does it always pair with just one particular preposition?",
        },
        {
          id: "pc-q2",
          instruction: CLICK_INSTRUCTION,
          before: "After forgetting his lines twice, the young actor felt deeply",
          options: ["ashamed", "upset", "annoyed", "frustrated"],
          correctIdx: 0,
          after: "of himself in front of the audience.",
          correction: "the preposition “of” is already fixed in the sentence, and only “ashamed” pairs fixedly with “of” in this sense (“ashamed of”) — “upset”, “annoyed” and “frustrated” all pair with different prepositions.",
          hint: "Look at the preposition already sitting after the gap — which option is the one word always paired with that exact preposition?",
        },
        {
          id: "pc-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Marcus has always been remarkably good",
          options: ["at", "in", "for", "with"],
          correctIdx: 0,
          after: "solving tricky maths puzzles.",
          correction: "“good” has one fixed dependent preposition in this sense, “at” — “good at” — not “in”, “for” or “with”.",
          hint: "Check the adjective right before the gap — which single preposition does it always pair with?",
        },
      ],
      mistakes: [
        "Picking a preposition that sounds fine in everyday speech instead of checking the one fixed preposition that word is always paired with in this sense.",
        "Not noticing that a preposition already in the sentence has narrowed the gap to a single fixed-phrase word.",
      ],
      examTip: "Whenever a gap sits right next to a preposition — on either side — check for a fixed phrase first; many words in English only ever pair with one specific preposition.",
      searchTerms: ["preposition", "fixed phrase", "dependent preposition", "cloze", "proud of", "keen on"],
    },
    {
      id: "connective-linking-clues",
      title: "Using Connective and Linking-Word Clues",
      tier: "Standard",
      objective: "Use a connective already in the sentence or passage (however, therefore, in addition, on the other hand) to work out what kind of idea — contrast, consequence, or addition — a gap must supply.",
      whyMatters: "connectives signal the logical relationship between ideas, so spotting one tells you in advance whether the gap needs a contrasting idea, a result, or an extra point — before you even look at the options.",
      conceptTitle: "Connectives announce what's coming",
      conceptBullets: [
        'A <b style="color:#C9A24B">connective</b> — "however", "therefore", "in addition", "on the other hand" — signals the logical relationship between one idea and the next.',
        '"However" and "on the other hand" promise a contrast is coming; the gap must supply an idea that opposes what came before.',
        '"Therefore" and "as a result" promise a consequence; the gap must supply an outcome that logically follows.',
        '"In addition" and "furthermore" promise an extra, similar point; the gap must supply something that supports the same direction as before, not a contrast.',
      ],
      conceptNote: "<b>Test it:</b> find the connective nearest the gap and name its job — contrast, consequence or addition — before reading a single option.",
      glossary: [
        { term: "connective", def: "a word or phrase (however, therefore, in addition) that links ideas and signals their relationship" },
        { term: "contrast", def: "the connective's job when it signals an opposing or unexpected idea is coming" },
        { term: "consequence", def: "the connective's job when it signals a result or outcome is coming" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: ConnectiveLinkingCluesDemo,
      worked: {
        question: "Which word fits? “The forecast promised sunshine all week; however, the campers ___ soaked within an hour.” (options: stayed, remained, got, arrived)",
        fastMethod: '"however" promises a contrast to sunny, dry weather — so the gap needs an idea that clashes with that, pointing straight to "got" (soaked).',
        steps: [
          "Spot the connective: “however”.",
          "“However” signals a contrast is coming — something that opposes the sunny forecast.",
          "Read the rest of the clause: “...soaked within an hour” already tells us the outcome was wet, opposing the forecast.",
          "“got” fits naturally with “soaked” to complete that contrasting outcome.",
        ],
        answer: "The gap needs <b>got</b>, because “however” signals the wet outcome that contrasts with the sunny forecast.",
      },
      selfCheck: { prompt: "True or false: “in addition” signals that a contrasting idea is about to follow.", answer: "<b>False</b> — “in addition” signals an extra, supporting point in the *same* direction as what came before, not a contrast; “however” is the contrast signal." },
      kind: "cloze-fill",
      questions: [
        {
          id: "clc-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Priya had revised every topic on the list; however, she still felt",
          options: ["confident", "nervous", "prepared", "relaxed"],
          correctIdx: 1,
          after: "before walking into the exam hall.",
          correction: "“however” signals a contrast with all that revision, so the gap needs an idea that opposes feeling ready — “nervous”, not a word suggesting confidence.",
          hint: "What relationship does the connective “however” promise between the two halves of the sentence?",
        },
        {
          id: "clc-q2",
          instruction: CLICK_INSTRUCTION,
          before: "The bridge had been closed for repairs for months; therefore, drivers were",
          options: ["delighted", "confused", "forced", "surprised"],
          correctIdx: 2,
          after: "to take the long way round every morning.",
          correction: "“therefore” signals a consequence following logically from the closed bridge, so the gap needs a result word like “forced” — not a word suggesting surprise or pleasure unconnected to that cause.",
          hint: "What relationship does “therefore” promise — a contrast, or a result following from the first idea?",
        },
        {
          id: "clc-q3",
          instruction: CLICK_INSTRUCTION,
          before: "The museum's new gallery is beautifully designed; in addition, it",
          options: ["contradicts", "undermines", "houses", "opposes"],
          correctIdx: 2,
          after: "several rare artefacts never shown before.",
          correction: "“in addition” signals an extra point in the same supportive direction, not a contrast, so the gap needs a word continuing the praise like “houses” — not a word suggesting conflict or opposition.",
          hint: "Does “in addition” promise a contrasting idea, or an extra point in the same direction as before?",
        },
      ],
      mistakes: [
        "Reading only the words right next to the gap and missing a connective a few words earlier that already reveals whether a contrast, consequence, or extra point is needed.",
        "Confusing addition connectives (“in addition”, “furthermore”) with contrast connectives (“however”, “on the other hand”) and choosing the wrong kind of idea for the gap.",
      ],
      examTip: "Before reading any option, name the connective's job out loud — contrast, consequence, or addition — it tells you the *shape* of the idea the gap needs before you judge individual words.",
      searchTerms: ["connective", "however", "therefore", "linking word", "cloze", "contrast consequence addition"],
    },
    {
      id: "combining-grammar-meaning-clues",
      title: "Combining Grammar Clues with Meaning Clues",
      tier: "Extension",
      objective: "Combine word class, tense and agreement clues with the sentence's actual meaning to choose correctly between several grammatically plausible options.",
      whyMatters: "the hardest cloze gaps have two or three options that are all grammatically valid — only checking meaning on top of grammar narrows it to the single best answer.",
      conceptTitle: "Grammar narrows it down; meaning finishes the job",
      conceptBullets: [
        'Grammar clues (<b style="color:#C9A24B">word class</b>, tense, agreement) often narrow an option bank down to two or three plausible candidates, but not always to just one.',
        "Once grammar has done its work, read the whole sentence (and surrounding passage) for meaning to choose between the remaining options.",
        'Example: if both "gave up" and "kept going" are grammatically valid past-tense verbs, only the meaning of the surrounding sentence (mentioning reaching the top) decides which one fits.',
        "Always apply grammar checks first — they're faster and more reliable — then use meaning only to break a remaining tie.",
      ],
      conceptNote: "<b>Test it:</b> if more than one option survives the grammar check, re-read the whole sentence (not just the gap) for the detail that decides meaning.",
      glossary: [
        { term: "grammatically valid", def: "correct in word class, tense and agreement, even if not the best meaning fit" },
        { term: "meaning check", def: "the final step of choosing between grammatically valid options using the sentence's sense" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: CombinedGrammarMeaningCluesDemo,
      worked: {
        question: "Choose the best fit: “The rescue team searched for hours and finally ___ the missing hiker just before dark.” (options: found, finds, finding, will find)",
        fastMethod: "Grammar first rules out three options by tense; meaning then confirms the remaining one fits the story.",
        steps: [
          "Apply the tense clue: the passage is in the past (“searched”), ruling out “finds”, “finding” and “will find”.",
          "Only “found” survives the grammar check.",
          "Confirm with meaning: “found... just before dark” fits a successful end to the search.",
          "The grammar check alone was enough here, with meaning confirming the fit.",
        ],
        answer: "The best fit is <b>found</b>, confirmed by both tense and meaning.",
      },
      selfCheck: { prompt: "True or false: when two options are both grammatically valid for a gap, you should just guess between them.", answer: "<b>False</b> — re-read the sentence (and surrounding passage) for a meaning clue that decides between the remaining valid options; it's never a pure guess." },
      kind: "cloze-fill",
      questions: [
        {
          id: "cgm-q1",
          instruction: CLICK_INSTRUCTION,
          before: "After weeks of practice, the choir finally",
          options: ["performed", "performing", "perform", "will perform"],
          correctIdx: 0,
          after: "confidently in front of the whole school.",
          correction: "grammar narrows it to a single past-tense verb, “performed” — the surrounding meaning (“after weeks of practice… finally”) confirms a completed event, matching the past tense.",
          hint: "First rule out options by tense, then check the surrounding meaning confirms the one option that survives.",
        },
        {
          id: "cgm-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Torn between the two options, Zara eventually",
          options: ["chose", "choosing", "chooses", "will choose"],
          correctIdx: 0,
          after: "the quieter of the two paths.",
          correction: "grammar rules out the non-past forms; “chose” fits both the past tense of the passage and the meaning of eventually making a decision.",
          hint: "Check the tense the rest of the sentence is written in, then confirm the surviving option matches the meaning of finally deciding.",
        },
        {
          id: "cgm-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Despite the freezing wind, the climbers",
          options: ["pressed", "press", "pressing", "will press"],
          correctIdx: 0,
          after: "on towards the summit.",
          correction: "grammar narrows it to the single past-tense form “pressed” — the meaning of “despite the freezing wind... towards the summit” confirms determination continuing in the past.",
          hint: "Check which option matches the past tense already used elsewhere, then confirm it fits the meaning of continuing despite difficulty.",
        },
      ],
      mistakes: [
        "Stopping at the first grammatically valid option without checking whether a second valid option might fit the meaning even better.",
        "Reading only the gap's immediate sentence for meaning and missing a clue placed earlier or later in the passage.",
      ],
      examTip: "Treat grammar and meaning as two separate checks in sequence — grammar first to narrow the field, then meaning to make the final choice — rather than trying to judge both at once.",
      searchTerms: ["cloze", "grammar clue", "meaning clue", "best fit", "combined strategy"],
    },
    {
      id: "pronoun-reference-clues",
      title: "Tracking Pronoun Reference Clues Across Sentences",
      tier: "Extension",
      objective: "Solve a gap that needs a pronoun (he/she/it/they) by tracking back across more than one sentence to identify exactly who or what was introduced earlier.",
      whyMatters: "harder cloze passages deliberately place the noun a pronoun refers to several sentences before the gap, so this is a genuine reading-across-the-passage skill, not just a same-sentence grammar check.",
      conceptTitle: "The referent can be sentences away",
      conceptBullets: [
        'A <b style="color:#C9A24B">pronoun</b> gap ("he", "she", "it", "they") can only be solved by finding its referent — the noun it stands in for — which may be introduced two or more sentences earlier.',
        "Track every person, animal or thing named in the passage before the gap, in order, and check which one still makes sense by the time you reach the gap.",
        "Watch for a second character or object being introduced between the first mention and the gap — it may become the closer, correct referent instead of the original one.",
        "Check number and gender agreement too: a plural referent needs “they”, a single named male character needs “he” — but agreement alone isn't enough if two referents both match.",
      ],
      conceptNote: "<b>Test it:</b> before choosing a pronoun, list every possible referent mentioned earlier in the passage, then check which one the rest of the sentence's meaning actually points to.",
      glossary: [
        { term: "pronoun", def: "a word like he, she, it or they that stands in for a previously named person or thing" },
        { term: "referent", def: "the specific noun a pronoun refers back to" },
        { term: "antecedent", def: "another name for the referent — the noun that comes before the pronoun in the text" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: PronounReferenceCluesDemo,
      worked: {
        question: "Which pronoun fits? “Grandma Rose had packed a small gift for Amir before he left. When the taxi finally arrived, ___ waved until it disappeared around the corner.” (options: he, she, it, they)",
        fastMethod: 'Two people are mentioned — Grandma Rose and Amir — but Amir is the one who "left" in the taxi, so Grandma Rose is the one left behind to wave; only "she" fits.',
        steps: [
          "List everyone named before the gap: “Grandma Rose” and “Amir”.",
          "Work out who is still present to wave as the taxi leaves: the sentence says Amir “left”, so he's in the taxi, not waving from the pavement.",
          "That leaves Grandma Rose as the one waving, so the gap needs a singular female pronoun.",
          "“she” is the only option matching Grandma Rose.",
        ],
        answer: "The gap needs <b>she</b>, referring back to Grandma Rose, who is left waving as Amir leaves in the taxi.",
      },
      selfCheck: { prompt: "True or false: a pronoun gap can only ever refer to the noun in the sentence immediately before it.", answer: "<b>False</b> — a pronoun's referent can be introduced two or more sentences earlier in the passage; you sometimes have to track back further than the previous sentence." },
      kind: "cloze-fill",
      questions: [
        {
          id: "prc-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Tom lent his umbrella to his sister Freya on the way to school. By lunchtime, the rain had stopped, so",
          options: ["he", "she", "it", "they"],
          correctIdx: 0,
          after: "didn't mind that Freya kept hold of it a little longer.",
          correction: "Tom is the one who lent the umbrella and no longer needs it urgently, so the gap needs the singular male pronoun “he”, referring back to Tom rather than Freya.",
          hint: "Track back to work out who lent the umbrella and who is doing the not-needing here — they aren't the same person mentioned right before the gap.",
        },
        {
          id: "prc-q2",
          instruction: CLICK_INSTRUCTION,
          before: "The coach praised the whole squad after training, especially Priya, who had scored twice. Afterwards,",
          options: ["he", "she", "it", "they"],
          correctIdx: 3,
          after: "celebrated together in the changing room.",
          correction: "although Priya was the closest name to the gap, the sentence describes a group celebration, so the gap needs the plural pronoun “they”, referring back to the whole squad, not just Priya alone.",
          hint: "Check whether the action described after the gap belongs to one person mentioned recently, or to a wider group named earlier.",
        },
        {
          id: "prc-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Years ago, someone had carved a small heart into the old oak desk. Nobody had ever explained why",
          options: ["he", "she", "it", "they"],
          correctIdx: 2,
          after: "was still there.",
          correction: "the gap refers back to the carved heart (an object), introduced two sentences earlier, so it needs the pronoun “it”, not a personal pronoun.",
          hint: "What was actually introduced earlier in the passage — a person, or a thing? Track back more than one sentence if needed.",
        },
      ],
      mistakes: [
        "Automatically linking a pronoun to whichever noun was mentioned most recently, without checking whether an earlier-introduced referent actually fits the meaning better.",
        "Forgetting to check number and gender agreement once a referent is found, and picking a pronoun that doesn't actually match it.",
      ],
      examTip: "When a gap needs a pronoun, list every person or thing named earlier in the passage before choosing — the correct referent is sometimes the first one mentioned, not the most recent.",
      searchTerms: ["pronoun", "referent", "antecedent", "cloze", "he she it they", "cross-sentence clue"],
    },
    {
      id: "ambiguous-gaps",
      title: "Ambiguous Gaps — When Two Words Both Fit Grammatically",
      tier: "Extension",
      objective: "Resolve the hardest cloze gaps, where two options are both grammatically correct, using collocation, register and precise meaning rather than grammar alone.",
      whyMatters: "top-tier cloze questions are deliberately designed so that grammar checks alone leave two options standing — this is the skill that decides the final mark on the hardest passages.",
      conceptTitle: "When grammar can't decide, meaning must",
      conceptBullets: [
        'Some gaps have two options that are both correct in <b style="color:#C9A24B">word class</b>, tense and agreement — grammar alone cannot separate them.',
        "Collocation — which words naturally sit together — can decide it: “make an effort” sounds right but “do an effort” doesn't, even though both are verbs.",
        "Register (how formal or informal a word feels) can decide it too: a formal passage about a court case should reject an option that feels casual, even if it's grammatically fine.",
        "Precise shades of meaning matter: “glanced” and “stared” are both past-tense verbs of looking, but only one fits a passage about a brief, nervous look versus a long, fixed one.",
        "Always check grammar first to rule out clearly wrong options, then use collocation, register and precise meaning only for the genuine final tie.",
      ],
      conceptNote: "<b>Test it:</b> if two options both pass every grammar check, read the sentence aloud with each — the one that doesn't naturally collocate, or clashes in register, is the wrong one.",
      glossary: [
        { term: "collocation", def: "words that naturally and habitually sit together (e.g. “make an effort”, not “do an effort”)" },
        { term: "register", def: "how formal, informal, or technical a word or phrase feels" },
        { term: "shade of meaning", def: "a small precise difference in sense between two similar words (e.g. glanced vs stared)" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: AmbiguousGapsDemo,
      worked: {
        question: "Which word fits best? “The headteacher's report ___ that the school had made excellent progress this year.” (options: said, stated, told, spoke)",
        fastMethod: 'All four can follow "report" grammatically, but only one collocates naturally with a formal written report and a "that" clause.',
        steps: [
          "Check grammar: “said”, “stated”, “told” and “spoke” are all past-tense verbs that could follow “report”.",
          "Rule out “told” and “spoke”, which don't naturally take a direct “that” clause in this pattern (“spoke that…” isn't standard English).",
          "Between “said” and “stated”, consider register: a formal, official report collocates more naturally with the more formal “stated”.",
          "“stated” best matches both the collocation pattern and the formal register of a headteacher's report.",
        ],
        answer: "The best fit is <b>stated</b> — grammatically valid like “said”, but a closer collocation and register match for a formal written report.",
      },
      selfCheck: { prompt: "True or false: if two options are both grammatically correct for a gap, either one can be marked correct.", answer: "<b>False</b> — only one option is the intended answer; collocation, register or precise meaning decides which single option the passage actually needs." },
      kind: "cloze-fill",
      questions: [
        {
          id: "ag-q1",
          instruction: CLICK_INSTRUCTION,
          before: "The lawyer's closing statement",
          options: ["said", "claimed", "told", "spoke"],
          correctIdx: 1,
          after: "that the evidence proved her client's innocence.",
          correction: "“told” and “spoke” don't naturally take a direct “that” clause here, and between “said” and “claimed”, the formal courtroom register and the sense of an assertion still to be proven collocates best with “claimed”.",
          hint: "All four can describe speaking, but which one fits the formal courtroom setting and the sense of an assertion, not just a plain statement?",
        },
        {
          id: "ag-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Instead of complaining, the volunteers decided to",
          options: ["make", "do", "take", "have"],
          correctIdx: 0,
          after: "a real difference in the community.",
          correction: "“make a difference” is the fixed, natural collocation in English — “do”, “take” and “have” are all grammatically possible verbs before “a difference” but none collocate naturally the way “make” does.",
          hint: "All four options are grammatically possible verbs here — which one is the one English speakers naturally pair with the noun that follows?",
        },
        {
          id: "ag-q3",
          instruction: CLICK_INSTRUCTION,
          before: "As the head teacher read out the results one by one, Maya",
          options: ["glanced", "peeked", "stared", "looked"],
          correctIdx: 2,
          after: "at the list, unable to look away until her own name was called.",
          correction: "“unable to look away” signals a long, fixed look, not a brief one, so the gap needs “stared” — “glanced” and “peeked” both suggest a quick, brief look that contradicts the rest of the sentence.",
          hint: "All four options are grammatically correct past-tense verbs of looking — which one matches the precise detail “unable to look away” given later in the sentence?",
        },
      ],
      mistakes: [
        "Stopping as soon as one grammatically correct option is found, without checking whether a second option is also grammatically valid and needs a further meaning-based decision.",
        "Choosing the option that sounds most impressive or unusual instead of the one that most naturally collocates with the surrounding words.",
      ],
      examTip: "If two options both survive every grammar check, don't guess — read the full sentence again for a precise detail (formality, duration, natural pairing) that only one option actually matches.",
      searchTerms: ["ambiguous", "collocation", "register", "shade of meaning", "cloze", "two correct answers"],
    },
  ],
};
