import type { TopicContent } from "../types";
import {
  WordClassCluesDemo,
  VerbTenseCluesDemo,
  SingularPluralAgreementCluesDemo,
  CombinedGrammarMeaningCluesDemo,
} from "../notes-diagrams/grammatical-cloze-demos";

const CLICK_INSTRUCTION = "Click the word that correctly fills the gap.";

export const grammaticalClozeStrategyTopic: TopicContent = {
  slug: "grammatical-cloze-strategy",
  subject: "English",
  subjectSlug: "english",
  title: "Cloze: Grammatical Gap-Filling Strategy",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "Once you know what a cloze test is, the next skill is using the sentence's own grammar to narrow down the answer before even thinking about meaning. This module covers reading the gap's word class from its position, using verb tense clues that run across a whole passage, checking singular/plural agreement, and combining grammar clues with meaning clues on harder questions.",
  subtopics: [
    {
      id: "word-class-clues",
      title: "Using Word Class Clues",
      tier: "Foundation",
      objective: "Work out what part of speech (noun, verb, adjective, adverb) a gap needs, purely from its position in the sentence, before considering meaning.",
      whyMatters: "narrowing down the word class first instantly rules out at least half of a typical option bank, making the final meaning-based choice much faster and safer.",
      conceptTitle: "The gap's position reveals its job",
      conceptBullets: [
        'The words directly around a <b style="color:#C9A24B">gap</b> — what comes just before and just after it — usually reveal what part of speech is needed.',
        'A gap right after a linking verb like "looked", "seemed" or "felt" almost always needs an adjective, not a noun or adverb.',
        'A gap right before a noun with no verb in between often needs an adjective describing that noun.',
        "Checking word class first is faster than reading every option for meaning — it usually eliminates two or three options immediately.",
      ],
      conceptNote: "<b>Test it:</b> before reading for meaning, ask “does this gap need a thing, an action, a description, or a description-of-an-action?” — that's the word class question.",
      glossary: [
        { term: "word class", def: "the grammatical category of a word (noun, verb, adjective, adverb)" },
        { term: "linking verb", def: "a verb like looked/seemed/felt that connects a subject to a description" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: WordClassCluesDemo,
      worked: {
        question: "Which word class does the gap need? “The music sounded ___ throughout the whole concert.”",
        fastMethod: '"sounded" is a linking verb, so the gap needs a word describing the music — an adjective.',
        steps: [
          "Identify the word right before the gap: “sounded”, a linking verb.",
          "Linking verbs connect a subject to a description, which means an adjective is needed.",
          "Rule out any noun, verb or adverb options immediately.",
          "Only an adjective (e.g. “beautiful”, “harsh”) can correctly fill this gap.",
        ],
        answer: "The gap needs an <b>adjective</b>, because it follows the linking verb “sounded”.",
      },
      selfCheck: { prompt: "True or false: a gap directly after the word “quickly” always needs another adverb.", answer: "<b>False</b> — the word class needed depends on the gap's own position and job in the sentence, not simply on matching the word next to it." },
      kind: "cloze-fill",
      questions: [
        {
          id: "wcc-q1",
          instruction: CLICK_INSTRUCTION,
          before: "The old barn door creaked",
          options: ["loud", "loudness", "loudly", "loudest"],
          correctIdx: 2,
          after: "as the wind pushed it open.",
          correction: "the gap describes how the door creaked (a verb), so it needs an adverb: “loudly” — not the adjective, noun or superlative forms.",
          hint: "Check what job the gap does here — is it describing a noun, or describing how an action was done?",
        },
        {
          id: "wcc-q2",
          instruction: CLICK_INSTRUCTION,
          before: "A sudden",
          options: ["silence", "silent", "silently", "silence's"],
          correctIdx: 0,
          after: "fell across the crowded hall.",
          correction: "the gap sits between an adjective (“sudden”) and a verb (“fell”), which means it needs a noun as the subject of the sentence: “silence”.",
          hint: "Check what part of speech comes right before the gap, and what the sentence needs as its subject.",
        },
        {
          id: "wcc-q3",
          instruction: CLICK_INSTRUCTION,
          before: "The instructions on the box were surprisingly",
          options: ["confuse", "confusion", "confusing", "confusingly"],
          correctIdx: 2,
          after: ", even for the adults.",
          correction: "the gap sits right after the linking verb “were”, so it needs an adjective describing the instructions: “confusing”.",
          hint: "Check what verb comes right before the gap — does it link the subject to a description?",
        },
      ],
      mistakes: [
        "Jumping straight to meaning without first checking what word class the sentence's grammar actually requires.",
        "Confusing similar-looking word-class options (confusing/confusingly, silence/silently) without checking their exact grammatical job in the sentence.",
      ],
      examTip: "Before reading the options for meaning, spend two seconds checking the word directly before and after the gap — that alone usually rules out half the option bank.",
      searchTerms: ["word class", "cloze", "noun", "verb", "adjective", "adverb", "grammar clue"],
    },
    {
      id: "verb-tense-clues",
      title: "Using Verb Tense Clues Across a Passage",
      tier: "Standard",
      objective: "Use tense signals elsewhere in a passage (time words, other verbs) to choose the correct verb form for a gap.",
      whyMatters: "cloze passages are connected prose, so a tense clue set up in one sentence — a time word like “yesterday”, or another verb nearby — usually applies to gaps much later in the same passage too.",
      conceptTitle: "One clue can govern the whole passage",
      conceptBullets: [
        'A single <b style="color:#C9A24B">time word</b> — "yesterday", "last week", "tomorrow" — often sets the tense for an entire passage, not just the sentence it appears in.',
        "Other verbs already in the passage (not in a gap) are reliable evidence for which tense the whole piece is written in.",
        'Example: if a passage starts "Yesterday, the whole class..." every later gap describing an action should also be past tense, even several sentences on.',
        "Check for a tense shift only if the passage explicitly signals one (e.g. moving into dialogue, or a new time word appearing).",
      ],
      conceptNote: "<b>Test it:</b> before filling any verb-shaped gap, scan the passage for time words or other verbs — they tell you which tense every gap should match.",
      glossary: [
        { term: "tense", def: "the verb form that shows when an action happens (past, present, future)" },
        { term: "time word", def: "a word like yesterday, tomorrow, or now that signals the passage's tense" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: VerbTenseCluesDemo,
      worked: {
        question: "Which tense does this gap need? “Last summer, our family ___ to the coast for a fortnight.”",
        fastMethod: '"last summer" is a clear past time word, so a past-tense verb is needed.',
        steps: [
          "Scan the sentence for a time clue: “last summer”.",
          "This signals the whole sentence describes something that already happened.",
          "The gap needs a past-tense verb to match.",
          "“Travelled” or “went” would both correctly fill the gap in the past tense.",
        ],
        answer: "The gap needs a <b>past-tense verb</b>, matching the time clue “last summer”.",
      },
      selfCheck: { prompt: "True or false: a time word at the very start of a passage can only affect the tense of the sentence it appears in, not later sentences.", answer: "<b>False</b> — a tense clue at the start of a passage usually governs every later sentence too, since cloze passages are connected prose describing a single timeframe." },
      kind: "cloze-fill",
      questions: [
        {
          id: "vtc-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Every morning last winter, the postman",
          options: ["arrives", "arrived", "arriving", "will arrive"],
          correctIdx: 1,
          after: "just before eight o'clock.",
          correction: "“last winter” is a past time clue, so the gap needs the past-tense verb “arrived”, not a present or future form.",
          hint: "Check the time clue at the start of the sentence — what tense does it set up for the rest of the sentence?",
        },
        {
          id: "vtc-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Next term, the whole school",
          options: ["moved", "moves", "will move", "was moving"],
          correctIdx: 2,
          after: "to the new building on the high street.",
          correction: "“next term” is a future time clue, so the gap needs a future-tense verb form: “will move”.",
          hint: "Check the time clue at the start of the sentence — does it point to the past, present or future?",
        },
        {
          id: "vtc-q3",
          instruction: CLICK_INSTRUCTION,
          before: "By the time the fire engine arrived, the flames",
          options: ["spread", "were spreading", "will spread", "spreads"],
          correctIdx: 1,
          after: "across the whole roof.",
          correction: "the surrounding clause (“by the time... arrived”) is past tense, and the gap describes an ongoing action happening at that past moment, so it needs the past continuous form: “were spreading”.",
          hint: "Check the verb tense already used elsewhere in the sentence (“arrived”) and whether the gap describes an action still in progress at that moment.",
        },
      ],
      mistakes: [
        "Only checking the words immediately next to a gap and missing a tense clue set up several sentences earlier in the passage.",
        "Defaulting to a present-tense verb because it feels like the “safe” choice, without checking the passage's actual timeframe.",
      ],
      examTip: "Before filling any gap that needs a verb, quickly scan the whole passage (not just the current sentence) for time words — they often govern gaps much later on.",
      searchTerms: ["verb tense", "cloze", "time word", "past tense", "future tense", "passage"],
    },
    {
      id: "singular-plural-agreement-clues",
      title: "Using Singular/Plural Agreement Clues",
      tier: "Standard",
      objective: "Use the number (singular or plural) of a gap's subject to choose the correct verb form, including with tricky quantifiers like “both” and “each”.",
      whyMatters: "cloze gaps that need a verb almost always test agreement alongside tense, and quantifier words like “both”, “each” and “neither” are common exam traps within this skill.",
      conceptTitle: "Find the subject's number first",
      conceptBullets: [
        'Before choosing a verb form for a gap, identify whether its <b style="color:#C9A24B">subject</b> is singular or plural.',
        '"Both" and "several" signal a plural subject; "each", "every" and "neither" signal a singular subject, even when followed by a plural-looking phrase.',
        'Example: "Both of the twins were chosen" is correct because "both" makes the subject plural, even though "of the twins" comes in between.',
        "This clue works alongside tense — a gap can need to be both plural and past tense at once.",
      ],
      conceptNote: "<b>Test it:</b> replace the subject phrase with “they” (plural) or “it”/“he”/“she” (singular) and see which verb form naturally follows.",
      glossary: [
        { term: "subject", def: "who or what is doing the verb in a sentence" },
        { term: "quantifier", def: "a word like both, each, neither that specifies an amount, and affects verb agreement" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: SingularPluralAgreementCluesDemo,
      worked: {
        question: "Which verb form fits? “Neither of the answers ___ correct.”",
        fastMethod: '"neither" is always singular, however plural the phrase after it sounds.',
        steps: [
          "Identify the subject: “neither”, a quantifier.",
          "Recall that “neither”, like “each” and “every”, is always grammatically singular.",
          "The gap needs a singular verb form to match.",
          "“Was” correctly matches the singular subject “neither”.",
        ],
        answer: "The gap needs the singular verb form <b>was</b>, because “neither” is always singular.",
      },
      selfCheck: { prompt: "True or false: “each of the students” takes a plural verb because “students” is plural.", answer: "<b>False</b> — “each” is always singular, regardless of what plural phrase follows it; the verb must be singular too." },
      kind: "cloze-fill",
      questions: [
        {
          id: "spac-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Each of the students",
          options: ["were given", "was given", "have given", "are given"],
          correctIdx: 1,
          after: "a certificate at the end of the course.",
          correction: "“each” is always singular, however plural the phrase “of the students” sounds — the gap needs the singular form “was given”.",
          hint: "Check the quantifier at the start of the sentence — is it one of the words that's always singular?",
        },
        {
          id: "spac-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Several of the paintings",
          options: ["was damaged", "is damaged", "were damaged", "has been damaged"],
          correctIdx: 2,
          after: "in the move to the new gallery.",
          correction: "“several” signals a plural subject, so the gap needs the plural verb form “were damaged”.",
          hint: "Check the quantifier at the start of the sentence — does it signal one thing or many?",
        },
        {
          id: "spac-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Neither of the routes",
          options: ["were suitable", "was suitable", "are suitable", "have been suitable"],
          correctIdx: 1,
          after: "for a wheelchair.",
          correction: "“neither” is always singular, however plural “of the routes” sounds — the gap needs the singular verb form “was suitable”.",
          hint: "Check the quantifier at the start of the sentence — is it one of the words that's always singular, however plural it sounds?",
        },
      ],
      mistakes: [
        "Matching the verb to the nearer plural-sounding noun (“the twins”, “the students”) instead of the true quantifier subject (“each”, “neither”).",
        "Forgetting that “each”, “every” and “neither” are always singular, however plural the rest of the phrase sounds.",
      ],
      examTip: "Whenever a gap's subject starts with “each”, “every”, “neither”, “both” or “several”, check that specific word's fixed number first — it always overrides how plural the rest of the phrase sounds.",
      searchTerms: ["subject-verb agreement", "cloze", "each", "both", "neither", "quantifier", "singular plural"],
    },
    {
      id: "combining-grammar-meaning-clues",
      title: "Combining Grammar Clues with Meaning Clues",
      tier: "Extension",
      objective: "Combine word class, tense and agreement clues with the sentence's actual meaning to choose correctly between several grammatically plausible options.",
      whyMatters: "the hardest cloze gaps have two or three options that are all grammatically valid — only checking meaning on top of grammar narrows it to the single best answer.",
      conceptTitle: "Grammar narrows it down; meaning finishes the job",
      conceptBullets: [
        'Grammar clues (<b style="color:#C9A24B">word class</b>, tense, agreement) often narrow an option bank down to two or three plausible candidates, but not always to just one.',
        "Once grammar has done its work, read the whole sentence (and surrounding passage) for meaning to choose between the remaining options.",
        'Example: if both "gave up" and "kept going" are grammatically valid past-tense verbs, only the meaning of the surrounding sentence (mentioning reaching the top) decides which one fits.',
        "Always apply grammar checks first — they're faster and more reliable — then use meaning only to break a remaining tie.",
      ],
      conceptNote: "<b>Test it:</b> if more than one option survives the grammar check, re-read the whole sentence (not just the gap) for the detail that decides meaning.",
      glossary: [
        { term: "grammatically valid", def: "correct in word class, tense and agreement, even if not the best meaning fit" },
        { term: "meaning check", def: "the final step of choosing between grammatically valid options using the sentence's sense" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: CombinedGrammarMeaningCluesDemo,
      worked: {
        question: "Choose the best fit: “The rescue team searched for hours and finally ___ the missing hiker just before dark.” (options: found, finds, finding, will find)",
        fastMethod: "Grammar first rules out three options by tense; meaning then confirms the remaining one fits the story.",
        steps: [
          "Apply the tense clue: the passage is in the past (“searched”), ruling out “finds”, “finding” and “will find”.",
          "Only “found” survives the grammar check.",
          "Confirm with meaning: “found... just before dark” fits a successful end to the search.",
          "The grammar check alone was enough here, with meaning confirming the fit.",
        ],
        answer: "The best fit is <b>found</b>, confirmed by both tense and meaning.",
      },
      selfCheck: { prompt: "True or false: when two options are both grammatically valid for a gap, you should just guess between them.", answer: "<b>False</b> — re-read the sentence (and surrounding passage) for a meaning clue that decides between the remaining valid options; it's never a pure guess." },
      kind: "cloze-fill",
      questions: [
        {
          id: "cgm-q1",
          instruction: CLICK_INSTRUCTION,
          before: "After weeks of practice, the choir finally",
          options: ["performed", "performing", "perform", "will perform"],
          correctIdx: 0,
          after: "confidently in front of the whole school.",
          correction: "grammar narrows it to a single past-tense verb, “performed” — the surrounding meaning (“after weeks of practice… finally”) confirms a completed event, matching the past tense.",
          hint: "First rule out options by tense, then check the surrounding meaning confirms the one option that survives.",
        },
        {
          id: "cgm-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Torn between the two options, Zara eventually",
          options: ["chose", "choosing", "chooses", "will choose"],
          correctIdx: 0,
          after: "the quieter of the two paths.",
          correction: "grammar rules out the non-past forms; “chose” fits both the past tense of the passage and the meaning of eventually making a decision.",
          hint: "Check the tense the rest of the sentence is written in, then confirm the surviving option matches the meaning of finally deciding.",
        },
        {
          id: "cgm-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Despite the freezing wind, the climbers",
          options: ["pressed", "press", "pressing", "will press"],
          correctIdx: 0,
          after: "on towards the summit.",
          correction: "grammar narrows it to the single past-tense form “pressed” — the meaning of “despite the freezing wind... towards the summit” confirms determination continuing in the past.",
          hint: "Check which option matches the past tense already used elsewhere, then confirm it fits the meaning of continuing despite difficulty.",
        },
      ],
      mistakes: [
        "Stopping at the first grammatically valid option without checking whether a second valid option might fit the meaning even better.",
        "Reading only the gap's immediate sentence for meaning and missing a clue placed earlier or later in the passage.",
      ],
      examTip: "Treat grammar and meaning as two separate checks in sequence — grammar first to narrow the field, then meaning to make the final choice — rather than trying to judge both at once.",
      searchTerms: ["cloze", "grammar clue", "meaning clue", "best fit", "combined strategy"],
    },
  ],
};
