import type { TopicContent } from "../types";
import {
  WhatAreHomophonesDemo,
  CommonHomophonePairsOneDemo,
  CommonHomophonePairsTwoDemo,
  SilentDifferenceHomophonesDemo,
  HomophonesVsNearHomophonesDemo,
  ContractionPossessiveHomophonesDemo,
  CommonlyMisspelledExamHomophonesDemo,
  FormalHomophoneTrapsDemo,
  HomophonesMultiMeaningWordsDemo,
} from "../notes-diagrams/homophones-demos";

const CLICK_INSTRUCTION = "Click the wrong homophone.";

export const homophonesTopic: TopicContent = {
  slug: "homophones",
  subject: "English",
  subjectSlug: "english",
  title: "Spelling: Homophones",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "Homophones sound identical when spoken but are spelled differently and mean completely different things — which is exactly why they're one of the most tested spelling traps at 11+. This module covers what a homophone is, several high-frequency exam pairs, and the habit of checking meaning rather than sound when a spelling choice comes down to two words that sound the same.",
  subtopics: [
    {
      id: "what-are-homophones",
      title: "What Are Homophones?",
      tier: "Foundation",
      objective: "Define a homophone and understand why spelling — not sound — is what decides which one is correct.",
      whyMatters: "because homophones sound identical, reading a sentence aloud in your head won't reveal the error — only checking meaning against spelling will.",
      conceptTitle: "Same sound, different word entirely",
      conceptBullets: [
        'A <b style="color:#C9A24B">homophone</b> is a word that sounds exactly like another word but has a different spelling and meaning: <i>threw</i>/<i>through</i>, <i>knight</i>/<i>night</i>.',
        "Because homophones sound identical, you cannot rely on how a sentence sounds when read aloud to spot the error — you have to check meaning.",
        'Example: "rode his horse threw the gates" is wrong even though it sounds fine spoken aloud — "threw" (the past tense of throw) makes no sense; "through" (meaning from one side to the other) is needed.',
        "The only reliable test is asking: does this exact word's dictionary meaning fit the sentence, regardless of how it sounds?",
      ],
      conceptNote: "<b>Golden rule:</b> for any homophone pair, silently define the word in your head before accepting it — sound alone will never catch the error.",
      glossary: [
        { term: "homophone", def: "a word that sounds like another but is spelled differently with a different meaning" },
        { term: "meaning check", def: "confirming a word's dictionary sense fits the sentence, regardless of sound" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: WhatAreHomophonesDemo,
      worked: {
        question: "Spot the error: “I can't bare to watch the end of that film.”",
        fastMethod: '"bare" means uncovered or plain — the word needed here, meaning "to endure," is "bear".',
        steps: [
          "Read the sentence for meaning: the writer means they can't endure watching the ending.",
          "Check “bare” against that meaning — “bare” means uncovered or plain, which doesn't fit.",
          "The correct homophone for “to endure” is “bear”.",
          "Corrected: “I can't bear to watch the end of that film.”",
        ],
        answer: "The error is <b>bare</b> — it should be <b>bear</b>.",
      },
      selfCheck: { prompt: "True or false: reading a sentence aloud is a reliable way to catch a homophone error.", answer: "<b>False</b> — homophones sound identical, so reading aloud won't reveal the mistake; only checking the word's meaning will." },
      kind: "click-error",
      questions: [
        {
          id: "wah-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Did", "you", "here", "that", "loud", "bang", "from", "next", "door", "last", "night?"],
          errorIdx: 2,
          correction: '"here" means in this place — the verb meaning "to perceive with your ears" is "hear": did you hear that loud bang.',
          hint: "Find the word about perceiving a sound, and check whether it's spelled as the “in this place” word or the “listen” word.",
        },
        {
          id: "wah-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Please", "right", "your", "name", "clearly", "at", "the", "top", "of", "the", "page."],
          errorIdx: 1,
          correction: '"right" means correct or a direction — the verb meaning "to put words on paper" is "write": please write your name.',
          hint: "Find the verb instructing the reader to put words down on paper.",
        },
        {
          id: "wah-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "sun", "shone", "brightly", "over", "the", "calm", "see", "all", "afternoon."],
          errorIdx: 7,
          correction: '"see" means to view with your eyes — the noun meaning a large body of water is "sea": over the calm sea.',
          hint: "Find the noun naming a large body of water, not the verb meaning “to view.”",
        },
      ],
      mistakes: [
        "Trusting how a sentence sounds when read in your head, when homophones sound identical either way.",
        "Picking the more familiar or frequent spelling of a homophone pair without checking whether its specific meaning actually fits the sentence.",
      ],
      examTip: "Whenever you meet a word that has a common sound-alike twin, pause and silently define it before moving on — this single habit catches almost every homophone trap.",
      searchTerms: ["homophone", "threw through", "bare bear", "right write", "see sea", "spelling"],
    },
    {
      id: "homophones-vs-near-homophones",
      title: "Homophones vs Near-Homophones",
      tier: "Foundation",
      objective: "Tell true homophones (identical sound) apart from near-homophones/commonly confused words that sound similar but not identical.",
      whyMatters: "exam markers penalise both equally, but they need different fixes — true homophones need a meaning check, near-homophones need you to notice the small sound difference itself.",
      conceptTitle: "Same sound, or just similar sound?",
      conceptBullets: [
        '<b style="color:#C9A24B">True homophones</b> sound completely identical when spoken — e.g. <i>their</i>/<i>there</i>/<i>they\'re</i> — so only meaning can tell them apart.',
        '<b>Near-homophones</b> sound similar but not identical — e.g. <i>affect</i>/<i>effect</i>, <i>accept</i>/<i>except</i> — there is a small audible difference if you listen closely.',
        "Near-homophones get confused because they look alike and mean related things, not because they sound exactly the same as each other.",
        "Testing strategy differs: for true homophones, always check meaning; for near-homophones, first try saying both words slowly to hear the difference, then check meaning.",
      ],
      conceptNote: "<b>Key distinction:</b> if swapping the words changes nothing about how the sentence sounds spoken aloud, they're true homophones; if there's a subtle sound difference, it's a near-homophone pair instead.",
      glossary: [
        { term: "true homophone", def: "a word that sounds 100% identical to another but is spelled differently, e.g. their/there" },
        { term: "near-homophone", def: "a word that sounds similar but not identical to another, e.g. affect/effect" },
        { term: "affect", def: "a verb meaning to influence or change something" },
        { term: "effect", def: "usually a noun meaning a result or outcome" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: HomophonesVsNearHomophonesDemo,
      worked: {
        question: "Spot the error: “The new library rules will really effect how much time we get for silent reading.”",
        fastMethod: 'swap in the word "influence" — it fits perfectly, and "influence" is a verb, so you need the verb spelling "affect", not the noun "effect".',
        steps: [
          "Ask whether the sentence needs a verb (an action) or a noun (a thing).",
          "Here the word describes changing how much time is given — that's an action, so a verb is needed.",
          "“Effect” is usually a noun; the verb form is “affect”.",
          "Corrected: “will really affect how much time we get for silent reading.”",
        ],
        answer: "The error is <b>effect</b> — it should be <b>affect</b>.",
      },
      selfCheck: { prompt: "True or false: “accept” and “except” sound completely identical, making them true homophones.", answer: "<b>False</b> — they are near-homophones with a subtle difference in sound, not true homophones like their/there." },
      kind: "click-error",
      questions: [
        {
          id: "hvn-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "twins", "packed", "there", "own", "bags", "before", "the", "school", "trip."],
          errorIdx: 3,
          correction: '"there" means in that place — the possessive needed here is "their": packed their own bags.',
          hint: "Find the word showing ownership of the bags, not the word meaning “in that place.”",
        },
        {
          id: "hvn-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "was", "happy", "to", "except", "the", "award", "on", "behalf", "of", "her", "team."],
          errorIdx: 4,
          correction: '"except" means “apart from” — the verb meaning “to receive willingly” is "accept": happy to accept the award.',
          hint: "Check whether this word means “apart from” or “to receive willingly.”",
        },
        {
          id: "hvn-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "students", "said", "there", "excited", "about", "the", "school", "trip", "next", "week."],
          errorIdx: 3,
          correction: '"there" means in that place — the contraction needed here, short for “they are”, is "they\'re": they\'re excited about the trip.',
          hint: "Expand the word into two words (“they are”) and check whether it fits before “excited.”",
        },
      ],
      mistakes: [
        "Assuming every commonly confused pair sounds exactly identical, when near-homophone pairs like affect/effect have a subtle sound difference worth listening for.",
        "Treating their/there/they're as interchangeable because all three come up so often, instead of checking each one's specific job in the sentence.",
      ],
      examTip: "Before choosing between a confusable pair, decide first whether they're true homophones (check meaning only) or near-homophones (also listen for the subtle sound difference) — this saves time under exam pressure.",
      searchTerms: ["homophone", "near-homophone", "affect effect", "accept except", "their there they're"],
    },
    {
      id: "common-homophone-pairs-one",
      title: "Common Homophone Pairs I",
      tier: "Standard",
      objective: "Correctly distinguish whose/who's, weather/whether, and allowed/aloud, three high-frequency 11+ homophone pairs.",
      whyMatters: "these three pairs turn up constantly in GL and CSSE-style spelling and cloze questions, and each has a simple, reliable test to tell the pair apart.",
      conceptTitle: "Three pairs, three quick tests",
      conceptBullets: [
        '<b style="color:#C9A24B">Whose</b> shows ownership ("whose coat is this?"); <b>who\'s</b> is short for "who is" or "who has".',
        '<b>Weather</b> means atmospheric conditions (rain, sun); <b>whether</b> introduces a choice between options ("whether to stay or go").',
        '<b>Allowed</b> means given permission; <b>aloud</b> means spoken out loud.',
        "Each pair has a simple expansion or substitution test: try replacing “who's” with “who is”, or checking whether the sentence is about permission or volume.",
      ],
      conceptNote: "<b>Test it:</b> expand “who's” into “who is” and see if it still makes sense — if not, you need the possessive “whose” instead.",
      glossary: [
        { term: "whose", def: "shows ownership (whose book is this?)" },
        { term: "who's", def: "short for who is / who has" },
        { term: "weather", def: "atmospheric conditions" },
        { term: "whether", def: "introduces a choice between options" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: CommonHomophonePairsOneDemo,
      worked: {
        question: "Spot the error: “She wasn't sure weather to bring an umbrella or not.”",
        fastMethod: 'the sentence is about a choice between two options, not atmospheric conditions — "whether" is needed.',
        steps: [
          "Read the sentence for meaning: it's about deciding between two options.",
          "Check “weather” — it refers to rain, sun, temperature, which doesn't fit a choice.",
          "The correct homophone for introducing a choice is “whether”.",
          "Corrected: “She wasn't sure whether to bring an umbrella or not.”",
        ],
        answer: "The error is <b>weather</b> — it should be <b>whether</b>.",
      },
      selfCheck: { prompt: "True or false: “The teacher who's classroom is nearest the hall” is correct.", answer: "<b>False</b> — expanding “who's” gives “who is classroom”, which makes no sense; the possessive “whose” is needed: whose classroom." },
      kind: "click-error",
      questions: [
        {
          id: "chp1-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "children", "were", "not", "aloud", "to", "leave", "the", "hall", "early."],
          errorIdx: 4,
          correction: '"aloud" means spoken out loud — the word needed here, about permission, is "allowed": were not allowed to leave.',
          hint: "Check whether this sentence is about permission or about speaking out loud.",
        },
        {
          id: "chp1-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Do", "you", "know", "who's", "umbrella", "was", "left", "outside", "the", "classroom?"],
          errorIdx: 3,
          correction: '"who\'s" expands to "who is umbrella", which makes no sense — the possessive "whose" is needed: whose umbrella.',
          hint: "Expand the apostrophe word into two words and check whether it still makes sense before “umbrella”.",
        },
        {
          id: "chp1-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "forecast", "predicted", "clear", "whether", "for", "the", "whole", "weekend."],
          errorIdx: 4,
          correction: '"whether" introduces a choice, but this sentence is about atmospheric conditions — "weather" is needed: predicted clear weather.',
          hint: "Check whether this sentence is describing atmospheric conditions or introducing a choice between two options.",
        },
      ],
      mistakes: [
        "Confusing “weather” and “whether” because they sound identical and both can appear near words about uncertainty (“not sure”).",
        "Forgetting to expand “who's” into “who is” as a quick check before accepting it.",
      ],
      examTip: "For “who's”, always try the “who is” expansion first — it takes one second and catches this error almost every time.",
      searchTerms: ["whose", "who's", "weather", "whether", "allowed", "aloud", "homophone"],
    },
    {
      id: "common-homophone-pairs-two",
      title: "Common Homophone Pairs II",
      tier: "Standard",
      objective: "Correctly distinguish stationary/stationery, complement/compliment, and principal/principle, three trickier homophone pairs tested at 11+.",
      whyMatters: "these three pairs are less common in everyday speech than the first set, which makes them easy to mix up under exam pressure without a clear memory trick for each.",
      conceptTitle: "Three trickier pairs, three memory tricks",
      conceptBullets: [
        '<b style="color:#C9A24B">Stationary</b> means not moving; <b>stationery</b> means paper and pens (remember: "stationery" and "letter" both have an "e").',
        '<b>Complement</b> means something that completes or goes well with another thing; <b>compliment</b> means a nice remark (remember: "I" like a nice compliment).',
        '<b>Principal</b> means the head of a school, or most important; <b>principle</b> means a rule or belief (remember: the "pal" at the end of "principal" is your school\'s "pal").',
        "Each pair has a small memory hook built into its spelling — learning the hook is far more reliable than guessing from sound.",
      ],
      conceptNote: "<b>Tip:</b> when in doubt, picture the memory trick for each pair rather than trusting how the word sounds in the sentence.",
      glossary: [
        { term: "stationary", def: "not moving" },
        { term: "stationery", def: "paper, pens and other writing materials" },
        { term: "complement", def: "something that completes or goes well with another thing" },
        { term: "compliment", def: "a nice remark about someone" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: CommonHomophonePairsTwoDemo,
      worked: {
        question: "Spot the error: “The car remained stationery at the red light for almost a minute.”",
        fastMethod: 'the sentence describes a car not moving — the "not moving" spelling, "stationary", is needed, not the paper-and-pens spelling.',
        steps: [
          "Read the sentence for meaning: the car isn't moving.",
          "Check “stationery” — that spelling refers to paper and pens, which doesn't fit a car.",
          "The correct homophone for “not moving” is “stationary”.",
          "Corrected: “The car remained stationary at the red light.”",
        ],
        answer: "The error is <b>stationery</b> — it should be <b>stationary</b>.",
      },
      selfCheck: { prompt: "True or false: the head teacher of a school is correctly called the “principle”.", answer: "<b>False</b> — the head of a school is the “principal”; “principle” means a rule or belief, not a person." },
      kind: "click-error",
      questions: [
        {
          id: "chp2-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "shop", "sells", "pens,", "pencils", "and", "other", "stationary", "for", "school."],
          errorIdx: 7,
          correction: '"stationary" means not moving — the word needed for paper and pens is "stationery": other stationery for school.',
          hint: "Check whether this word should mean “not moving” or “paper and pens.”",
        },
        {
          id: "chp2-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Honesty", "is", "one", "of", "the", "school's", "most", "important", "principals."],
          errorIdx: 8,
          correction: '"principals" refers to heads of schools — the word needed for a core belief or rule is "principles": most important principles.',
          hint: "Check whether this word should mean “a rule or belief” or “a person in charge.”",
        },
        {
          id: "chp2-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "scarf", "was", "a", "perfect", "compliment", "to", "her", "winter", "coat."],
          errorIdx: 5,
          correction: '"compliment" means a nice remark about someone — the word needed here, for two things going well together, is "complement": a perfect complement to her coat.',
          hint: "Decide whether this sentence is about the scarf going well with the coat, or about someone giving a nice remark.",
        },
      ],
      mistakes: [
        "Mixing up “stationary” and “stationery” because they differ by only one letter.",
        "Assuming “principal” always refers to a rule, when it usually refers to the head of a school or something of primary importance.",
      ],
      examTip: "Attach each pair's memory hook (stationery has an “e” like letter; principal has “pal” like your school's head) rather than guessing from how the word sounds.",
      searchTerms: ["stationary", "stationery", "complement", "compliment", "principal", "principle", "homophone"],
    },
    {
      id: "contraction-possessive-homophones",
      title: "Contraction vs Possessive Homophones",
      tier: "Standard",
      objective: "Correctly choose between the contraction and possessive forms in the it's/its, they're/their/there's, and who's/whose families using the apostrophe rule.",
      whyMatters: "this exact trap is one of the single most repeated 11+ punctuation-and-spelling errors, and it has one reliable test that resolves nearly every case.",
      conceptTitle: "One test solves the whole family",
      conceptBullets: [
        '<b style="color:#C9A24B">Contractions</b> use an apostrophe to replace missing letters: <i>it\'s</i> = "it is"/"it has", <i>they\'re</i> = "they are", <i>who\'s</i> = "who is"/"who has".',
        '<b>Possessive pronouns</b> show ownership and never use an apostrophe: <i>its</i>, <i>their</i>, <i>whose</i>.',
        "This is one of the most heavily tested spelling traps at 11+ because the rule is the opposite of ordinary possessive nouns, which do use an apostrophe (the dog's bone).",
        "The reliable test: expand the apostrophe word into its two full words — if the sentence still makes sense, the contraction is correct; if not, you need the possessive form instead.",
        '"There\'s" (there is/has) belongs to this same family too, alongside "their" (possessive) and "they\'re" (they are).',
      ],
      conceptNote: "<b>Golden test:</b> expand any apostrophe word into its two full words — “it is”, “they are”, “who is” — and check the sentence still makes sense; if it doesn't, switch to the apostrophe-free possessive.",
      glossary: [
        { term: "contraction", def: "two words shortened into one, with an apostrophe standing in for missing letters" },
        { term: "possessive pronoun", def: "a word showing ownership that never takes an apostrophe, e.g. its, their, whose" },
        { term: "it's / its", def: "it's = it is/it has; its = belonging to it" },
        { term: "they're / their / there's", def: "they're = they are; their = belonging to them; there's = there is/has" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: ContractionPossessiveHomophonesDemo,
      worked: {
        question: "Spot the error: “The dog wagged it's tail happily when it saw it's owner.”",
        fastMethod: 'expand both onto "it is" — "wagged it is tail" makes no sense, so both need the possessive "its".',
        steps: [
          "Find every apostrophe word in the sentence: both are “it's”.",
          "Expand each one into “it is”: “wagged it is tail” — this makes no sense.",
          "Since the expansion fails, the possessive form (no apostrophe) is needed instead: “its”.",
          "Corrected: “The dog wagged its tail happily when it saw its owner.”",
        ],
        answer: "The error is <b>it's</b> (both instances) — it should be <b>its</b>.",
      },
      selfCheck: { prompt: "True or false: “their” can be expanded into “they are” the way “they're” can.", answer: "<b>False</b> — “their” is the possessive pronoun showing ownership; only “they're” expands into “they are”." },
      kind: "click-error",
      questions: [
        {
          id: "cph-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "cat", "cleaned", "it's", "paws", "after", "coming", "in", "from", "the", "rain."],
          errorIdx: 3,
          correction: '"it\'s" expands to "it is paws", which makes no sense — the possessive "its" is needed: cleaned its paws.',
          hint: "Expand the apostrophe word into “it is” and check whether the sentence still makes sense.",
        },
        {
          id: "cph-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "students", "left", "there", "coats", "in", "the", "cloakroom", "before", "assembly."],
          errorIdx: 3,
          correction: '"there" means in that place — the possessive needed here is "their": left their coats.',
          hint: "Check whether this word shows ownership of the coats or means “in that place.”",
        },
        {
          id: "cph-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Nobody", "knew", "who's", "turn", "it", "was", "to", "feed", "the", "class", "hamster."],
          errorIdx: 2,
          correction: '"who\'s" expands to "who is turn", which makes no sense — the possessive "whose" is needed: whose turn it was.',
          hint: "Expand the apostrophe word into “who is” and check whether it still makes sense before “turn.”",
        },
      ],
      mistakes: [
        "Adding an apostrophe to a possessive pronoun (its, their, whose) by copying the pattern from possessive nouns like “the dog's bone”, which do take an apostrophe.",
        "Skipping the expansion test and guessing from habit, especially with the extremely common “it's/its” pair.",
      ],
      examTip: "Whenever you meet it's/its, they're/their/there's, or who's/whose, run the expansion test before writing anything else — it takes two seconds and is almost never wrong.",
      searchTerms: ["it's its", "they're their there's", "who's whose", "contraction", "possessive pronoun", "apostrophe rule"],
    },
    {
      id: "commonly-misspelled-exam-homophones",
      title: "Commonly Misspelled Exam Homophones",
      tier: "Standard",
      objective: "Correctly distinguish practice/practise, guessed/guest, and herd/heard, three everyday homophones that trip up 11+ candidates in exam writing.",
      whyMatters: "these pairs show up constantly in ordinary exam sentences, not just special vocabulary, so mixing them up costs marks in almost every piece of writing you produce.",
      conceptTitle: "Everyday words, easy to trip on",
      conceptBullets: [
        '<b style="color:#C9A24B">Practice</b> is the noun (a football practice); <b>practise</b> is the verb (to practise the piano) — this noun/verb split also matches advice/advise.',
        '<b>Guessed</b> is the past tense of the verb "to guess" (to estimate); <b>guest</b> is a noun for a visitor.',
        '<b>Herd</b> is a noun for a group of animals; <b>heard</b> is the past tense of the verb "to hear".',
        "None of these three pairs shares a spelling pattern with the others — each has to be checked individually by asking which specific meaning, or which noun/verb form, fits the sentence.",
      ],
      conceptNote: "<b>Test it:</b> for practice/practise, ask whether the sentence needs a thing (a noun, “practice”) or a doing-word (a verb, “practise”) — that one question solves this pair every time.",
      glossary: [
        { term: "practice", def: "the noun form: an activity done regularly, e.g. football practice" },
        { term: "practise", def: "the verb form: to do something regularly to improve, e.g. to practise the piano" },
        { term: "guest", def: "a noun for a visitor invited somewhere" },
        { term: "herd", def: "a noun for a group of animals, e.g. a herd of cows" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: CommonlyMisspelledExamHomophonesDemo,
      worked: {
        question: "Spot the error: “She has piano practise every Tuesday after school.”",
        fastMethod: 'the word follows "piano" and names a scheduled activity — a thing, not an action — so the noun spelling "practice" is needed.',
        steps: [
          "Read the sentence for meaning: it names a regular scheduled activity.",
          "Check whether a noun (a thing) or a verb (an action) is needed here — it's a thing, following “piano”.",
          "The noun spelling is “practice”, not the verb spelling “practise”.",
          "Corrected: “She has piano practice every Tuesday after school.”",
        ],
        answer: "The error is <b>practise</b> — it should be <b>practice</b>.",
      },
      selfCheck: { prompt: "True or false: “guest” and “guessed” can always be swapped with no change in meaning.", answer: "<b>False</b> — “guest” is a noun for a visitor, while “guessed” is the past tense of the verb “to guess”; they aren't interchangeable." },
      kind: "click-error",
      questions: [
        {
          id: "cme-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Every", "Saturday", "the", "team", "has", "football", "practise", "at", "the", "local", "park."],
          errorIdx: 6,
          correction: '"practise" is the verb spelling — the noun needed here for a scheduled activity is "practice": football practice at the local park.',
          hint: "Check whether this word should be the noun (a thing) or the verb (an action).",
        },
        {
          id: "cme-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "birthday", "guessed", "arrived", "early", "and", "helped", "set", "up", "the", "chairs."],
          errorIdx: 2,
          correction: '"guessed" is the past tense of "to guess" — the noun needed here for a visitor is "guest": the birthday guest arrived early.',
          hint: "Check whether this word should mean “a visitor” or “estimated something.”",
        },
        {
          id: "cme-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "farmer", "counted", "his", "heard", "of", "sheep", "before", "closing", "the", "gate", "for", "the", "night."],
          errorIdx: 4,
          correction: '"heard" is the past tense of "to hear" — the noun needed here for a group of animals is "herd": counted his herd of sheep.',
          hint: "Check whether this word should name a group of animals or mean “perceived with your ears.”",
        },
      ],
      mistakes: [
        "Writing the verb spelling “practise” where a noun is needed (or vice versa), because the two words sound identical either way.",
        "Assuming an everyday, familiar-looking word can't be a homophone trap, and skipping the meaning check altogether.",
      ],
      examTip: "For practice/practise specifically, remember the pattern also used by advice/advise: the noun ends in -ice, the verb ends in -ise.",
      searchTerms: ["practice practise", "guest guessed", "herd heard", "noun verb homophone", "exam spelling"],
    },
    {
      id: "silent-difference-homophones",
      title: "Homophones with Silent Differences",
      tier: "Extension",
      objective: "Correctly distinguish break/brake, led/lead, and past/passed, homophone pairs where the spelling difference carries no audible clue at all.",
      whyMatters: "these pairs are especially tricky because there's no visible pattern connecting spelling to meaning the way there is with, say, stationery's shared “e” with letter — each one simply has to be individually memorised.",
      conceptTitle: "No pattern to lean on — memorise the meaning directly",
      conceptBullets: [
        '<b style="color:#C9A24B">Break</b> means to split or shatter; <b>brake</b> means to slow down a vehicle, or the device that does it.',
        '<b>Led</b> is the past tense of the verb "to lead" (to guide); <b>lead</b> (rhyming with "led") is also a heavy grey metal — context, not sound, tells them apart.',
        '<b>Past</b> is a noun/adjective meaning a time before now; <b>passed</b> is the past tense of the verb "to pass" (to go by or succeed at something).',
        "Because none of these pairs share an obvious spelling pattern the way stationery/letter do, the only reliable strategy is learning each meaning directly and testing it against the sentence.",
      ],
      conceptNote: "<b>Test it:</b> for led/lead, ask whether the sentence needs a past-tense verb (led) or a noun for the metal (lead) — that distinction alone solves this pair every time.",
      glossary: [
        { term: "break", def: "to split or shatter something" },
        { term: "brake", def: "to slow a vehicle, or the device that does it" },
        { term: "led", def: "past tense of the verb “to lead” (guided)" },
        { term: "passed", def: "past tense of the verb “to pass” (went by, succeeded)" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: SilentDifferenceHomophonesDemo,
      worked: {
        question: "Spot the error: “She lead the team to victory in last year's final.”",
        fastMethod: 'the sentence needs a past-tense verb describing guiding the team — that spelling is "led", not "lead" (the metal).',
        steps: [
          "Read the sentence for meaning: it describes an action that already happened, guiding the team.",
          "Check “lead” — as written, that spelling names the grey metal, which doesn't fit a verb here.",
          "The past-tense verb spelling is “led”.",
          "Corrected: “She led the team to victory in last year's final.”",
        ],
        answer: "The error is <b>lead</b> — it should be <b>led</b>.",
      },
      selfCheck: { prompt: "True or false: “passed” and “past” can always be swapped for each other with no change in meaning.", answer: "<b>False</b> — “passed” is a verb (she passed the shop), while “past” is a noun or adjective (in the past, drove past the shop); they aren't interchangeable." },
      kind: "click-error",
      questions: [
        {
          id: "sdh-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "driver", "forgot", "to", "break", "at", "the", "junction", "and", "nearly", "hit", "a", "cyclist."],
          errorIdx: 4,
          correction: '"break" means to split or shatter something — the word needed here, about slowing a vehicle, is "brake": forgot to brake at the junction.',
          hint: "Find the word describing what a driver does to slow down, and check its spelling against “to shatter.”",
        },
        {
          id: "sdh-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "muddy", "footprints", "lead", "the", "detective", "straight", "to", "the", "hidden", "safe."],
          errorIdx: 3,
          correction: '"lead" (rhyming with "led") names the heavy grey metal — the past-tense verb needed here, describing guiding someone, is "led": footprints led the detective.',
          hint: "Check whether this word should be the past-tense verb for “guided” or the name of a heavy grey metal.",
        },
        {
          id: "sdh-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "cyclist", "past", "the", "finish", "line", "in", "record", "time."],
          errorIdx: 2,
          correction: '"past" is a noun/adjective for a time before now — the verb describing going by the finish line is "passed": passed the finish line.',
          hint: "Check whether this word should be the noun for “a time before now” or the verb for “went by.”",
        },
      ],
      mistakes: [
        "Assuming a familiar-looking spelling must be correct, when these pairs have no pattern connecting spelling to meaning.",
        "Mixing up “led” (the verb) and “lead” (the metal) because they're spelled identically to two different unrelated words.",
      ],
      examTip: "For these especially tricky pairs, learn each meaning as its own separate vocabulary item rather than trying to find a spelling rule — there isn't one.",
      searchTerms: ["break", "brake", "led", "lead", "past", "passed", "homophone"],
    },
    {
      id: "formal-homophone-traps",
      title: "Formal Homophone Traps",
      tier: "Extension",
      objective: "Apply the noun/verb spelling pattern to correctly spell advice/advise, licence/license, and prophecy/prophesy, rather than memorising each pair separately.",
      whyMatters: "recognising this as a generalisable rule — not a list of unrelated pairs — lets you spell new, unfamiliar words in this family correctly under exam conditions.",
      conceptTitle: "One pattern, several word families",
      conceptBullets: [
        'In formal English, several word families follow the same split: the <b style="color:#C9A24B">noun ends in -ce</b>, the <b>verb ends in -se</b> — e.g. <i>advice</i> (noun) / <i>advise</i> (verb).',
        '<b>Licence</b> (noun, a permit) / <b>license</b> (verb, to grant permission) follows the identical pattern.',
        '<b>Practice</b> (noun) / <b>practise</b> (verb) is the same pattern again — it generalises across all three pairs, not just this one.',
        '<b>Prophecy</b> (noun, a prediction) / <b>prophesy</b> (verb, to predict) follows the same c/s split, even though it doesn\'t rhyme with the others.',
        "Once you know the rule — noun ends in -c(e)/-cy, verb ends in -s(e) — you can apply it to a brand-new word in this family instead of memorising each pair from scratch.",
      ],
      conceptNote: "<b>The rule:</b> ask whether the word is naming a thing (noun → -c-) or doing an action (verb → -s-) — this single question generalises across advice/advise, licence/license, practice/practise and prophecy/prophesy.",
      glossary: [
        { term: "noun", def: "a word naming a thing, e.g. advice, licence, practice" },
        { term: "verb", def: "a word naming an action, e.g. advise, license, practise" },
        { term: "advice / advise", def: "advice = the noun (a suggestion); advise = the verb (to suggest)" },
        { term: "licence / license", def: "licence = the noun (a permit); license = the verb (to grant permission)" },
        { term: "prophecy / prophesy", def: "prophecy = the noun (a prediction); prophesy = the verb (to predict)" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: FormalHomophoneTrapsDemo,
      worked: {
        question: "Spot the error: “My uncle works for the council office that licences new taxi drivers.”",
        fastMethod: "the word here describes an action the office performs (granting permission) — that's a verb, so the -se spelling “licenses” is needed, not the noun spelling.",
        steps: [
          "Decide whether the word is naming a thing or describing an action — here it's an action the office does.",
          "Actions in this family take the -se spelling, not -ce.",
          "The verb spelling is “licenses”, not “licences”.",
          "Corrected: “...the council office that licenses new taxi drivers.”",
        ],
        answer: "The error is <b>licences</b> — it should be <b>licenses</b>.",
      },
      selfCheck: { prompt: "Using the noun/verb pattern, which spelling of “prophesy/prophecy” is the verb form?", answer: "<b>Prophesy</b> (ending -se) is the verb, meaning to predict; “prophecy” (ending -cy) is the noun, meaning a prediction." },
      kind: "click-error",
      questions: [
        {
          id: "fht-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "driving", "instructor", "gave", "her", "some", "useful", "advise", "before", "the", "test."],
          errorIdx: 7,
          correction: '"advise" is the verb spelling — the noun needed here for a suggestion is "advice": some useful advice.',
          hint: "Check whether this word should be the noun (a thing) or the verb (an action).",
        },
        {
          id: "fht-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Every", "taxi", "in", "the", "city", "must", "carry", "a", "valid", "license", "at", "all", "times."],
          errorIdx: 9,
          correction: '"license" is the verb spelling — the noun needed here for a permit is "licence": a valid licence.',
          hint: "Check whether this word should name a permit (a thing) or describe granting permission (an action).",
        },
        {
          id: "fht-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "old", "woman's", "prophesy", "about", "the", "storm", "came", "true", "within", "a", "week."],
          errorIdx: 3,
          correction: '"prophesy" is the verb spelling — the noun needed here for a prediction is "prophecy": the old woman\'s prophecy about the storm.',
          hint: "Check whether this word should name a prediction (a thing) or describe the act of predicting (an action).",
        },
      ],
      mistakes: [
        "Memorising each pair separately instead of noticing the shared noun/verb pattern that also applies to practice/practise and advice/advise.",
        "Writing the verb spelling in noun position (or vice versa) because the two spellings sound identical or nearly identical.",
      ],
      examTip: "Whenever you meet an unfamiliar formal word ending in -ce or -se in this family, ask “thing or action?” first — the noun/verb pattern will very often tell you which spelling to use, even for a word you haven't memorised before.",
      searchTerms: ["advice advise", "licence license", "prophecy prophesy", "noun verb spelling", "ce se pattern"],
    },
    {
      id: "homophones-in-multi-meaning-words",
      title: "Homophones Inside Multi-Meaning Words",
      tier: "Extension",
      objective: "Correctly choose between board and bored by first identifying which sense of “board” (plank, committee, or boarding transport) fits, then checking it isn't actually “bored”.",
      whyMatters: "this is the hardest homophone tier — the correct spelling depends on recognising which of several meanings is intended, not just a single meaning check.",
      conceptTitle: "Two layers: which word, and which meaning",
      conceptBullets: [
        '<b style="color:#C9A24B">Board</b> has several unrelated meanings that are all spelled the same way: a flat plank of wood, a group of people who run an organisation (a school board), and the verb "to get on" a train, plane or ship.',
        '<b>Bored</b> only ever means feeling uninterested or having nothing to do — it has just one meaning, unlike "board".',
        "Because “board” covers several meanings, a meaning check alone isn't enough — you first have to work out which sense of “board” the sentence needs before you can even compare it against “bored”.",
        "The two-step test: first ask “does this sentence describe boredom at all?”, and if not, ask which of board's three senses (plank/committee/getting on) applies.",
      ],
      conceptNote: "<b>Two-step test:</b> first rule out “bored” (feeling uninterested) by checking whether the sentence describes boredom at all; then, if not, work out which sense of “board” — plank, committee, or “get on” — the context needs.",
      glossary: [
        { term: "board (plank)", def: "a flat, rigid piece of wood or material" },
        { term: "board (committee)", def: "a group of people responsible for running an organisation, e.g. a school board" },
        { term: "board (verb)", def: "to get on a train, plane, ship or other form of transport" },
        { term: "bored", def: "feeling uninterested or having nothing to do" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: HomophonesMultiMeaningWordsDemo,
      worked: {
        question: "Spot the error: “The passengers began to bored the train as soon as the doors opened.”",
        fastMethod: 'the sentence describes passengers getting on a train, not feeling uninterested — the verb sense of "board" is needed, not "bored".',
        steps: [
          "Check whether the sentence is describing boredom at all — it isn't; it's describing an action (getting on a train).",
          "Since it's not about boredom, the word needed is some sense of “board”.",
          "Here it's the verb sense of “board”, meaning to get on a form of transport.",
          "Corrected: “The passengers began to board the train as soon as the doors opened.”",
        ],
        answer: "The error is <b>bored</b> — it should be <b>board</b>.",
      },
      selfCheck: { prompt: "True or false: “board” always refers to a flat piece of wood, whatever the sentence.", answer: "<b>False</b> — “board” can also mean a committee that runs an organisation, or the verb “to get on” transport; the flat-wood sense is only one of several." },
      kind: "click-error",
      questions: [
        {
          id: "hmw-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "school", "bored", "met", "on", "Tuesday", "to", "discuss", "next", "year's", "budget."],
          errorIdx: 2,
          correction: '"bored" means feeling uninterested — the word needed here for the group who run the school is "board": the school board met on Tuesday.',
          hint: "Check whether this word should name a group of people or describe feeling uninterested.",
        },
        {
          id: "hmw-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Dad", "used", "an", "old", "wooden", "bored", "to", "patch", "the", "hole", "in", "the", "fence."],
          errorIdx: 5,
          correction: '"bored" means feeling uninterested — the word needed here for a flat piece of wood is "board": an old wooden board.',
          hint: "Check whether this word should name a flat piece of wood or describe feeling uninterested.",
        },
        {
          id: "hmw-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "excited", "children", "couldn't", "wait", "to", "bored", "the", "roller", "coaster", "at", "the", "theme", "park."],
          errorIdx: 6,
          correction: '"bored" means feeling uninterested — the verb needed here for getting on a ride is "board": couldn\'t wait to board the roller coaster.',
          hint: "Check whether this word should describe getting on the ride or feeling uninterested.",
        },
      ],
      mistakes: [
        "Assuming “board” only ever means a flat piece of wood, and missing its committee and “get on transport” senses.",
        "Confusing “board” and “bored” because the sentence briefly mentions transport or meetings, without checking whether boredom is actually being described.",
      ],
      examTip: "With board/bored, run a two-step check: first rule out whether the sentence is really about boredom at all, then, if not, work out which specific sense of “board” fits.",
      searchTerms: ["board bored", "multi-meaning homophone", "board committee", "homophone context", "word senses"],
    },
  ],
};
