import type { TopicContent } from "../types";
import {
  WhatAreHomophonesDemo,
  CommonHomophonePairsOneDemo,
  CommonHomophonePairsTwoDemo,
  SilentDifferenceHomophonesDemo,
} from "../notes-diagrams/homophones-demos";

const CLICK_INSTRUCTION = "Click the wrong homophone.";

export const homophonesTopic: TopicContent = {
  slug: "homophones",
  subject: "English",
  subjectSlug: "english",
  title: "Spelling: Homophones",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "Homophones sound identical when spoken but are spelled differently and mean completely different things — which is exactly why they're one of the most tested spelling traps at 11+. This module covers what a homophone is, several high-frequency exam pairs, and the habit of checking meaning rather than sound when a spelling choice comes down to two words that sound the same.",
  subtopics: [
    {
      id: "what-are-homophones",
      title: "What Are Homophones?",
      tier: "Foundation",
      objective: "Define a homophone and understand why spelling — not sound — is what decides which one is correct.",
      whyMatters: "because homophones sound identical, reading a sentence aloud in your head won't reveal the error — only checking meaning against spelling will.",
      conceptTitle: "Same sound, different word entirely",
      conceptBullets: [
        'A <b style="color:#C9A24B">homophone</b> is a word that sounds exactly like another word but has a different spelling and meaning: <i>threw</i>/<i>through</i>, <i>knight</i>/<i>night</i>.',
        "Because homophones sound identical, you cannot rely on how a sentence sounds when read aloud to spot the error — you have to check meaning.",
        'Example: "rode his horse threw the gates" is wrong even though it sounds fine spoken aloud — "threw" (the past tense of throw) makes no sense; "through" (meaning from one side to the other) is needed.',
        "The only reliable test is asking: does this exact word's dictionary meaning fit the sentence, regardless of how it sounds?",
      ],
      conceptNote: "<b>Golden rule:</b> for any homophone pair, silently define the word in your head before accepting it — sound alone will never catch the error.",
      glossary: [
        { term: "homophone", def: "a word that sounds like another but is spelled differently with a different meaning" },
        { term: "meaning check", def: "confirming a word's dictionary sense fits the sentence, regardless of sound" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: WhatAreHomophonesDemo,
      worked: {
        question: "Spot the error: “I can't bare to watch the end of that film.”",
        fastMethod: '"bare" means uncovered or plain — the word needed here, meaning "to endure," is "bear".',
        steps: [
          "Read the sentence for meaning: the writer means they can't endure watching the ending.",
          "Check “bare” against that meaning — “bare” means uncovered or plain, which doesn't fit.",
          "The correct homophone for “to endure” is “bear”.",
          "Corrected: “I can't bear to watch the end of that film.”",
        ],
        answer: "The error is <b>bare</b> — it should be <b>bear</b>.",
      },
      selfCheck: { prompt: "True or false: reading a sentence aloud is a reliable way to catch a homophone error.", answer: "<b>False</b> — homophones sound identical, so reading aloud won't reveal the mistake; only checking the word's meaning will." },
      kind: "click-error",
      questions: [
        {
          id: "wah-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Did", "you", "here", "that", "loud", "bang", "from", "next", "door", "last", "night?"],
          errorIdx: 2,
          correction: '"here" means in this place — the verb meaning "to perceive with your ears" is "hear": did you hear that loud bang.',
          hint: "Find the word about perceiving a sound, and check whether it's spelled as the “in this place” word or the “listen” word.",
        },
        {
          id: "wah-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Please", "right", "your", "name", "clearly", "at", "the", "top", "of", "the", "page."],
          errorIdx: 1,
          correction: '"right" means correct or a direction — the verb meaning "to put words on paper" is "write": please write your name.',
          hint: "Find the verb instructing the reader to put words down on paper.",
        },
        {
          id: "wah-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "sun", "shone", "brightly", "over", "the", "calm", "see", "all", "afternoon."],
          errorIdx: 7,
          correction: '"see" means to view with your eyes — the noun meaning a large body of water is "sea": over the calm sea.',
          hint: "Find the noun naming a large body of water, not the verb meaning “to view.”",
        },
      ],
      mistakes: [
        "Trusting how a sentence sounds when read in your head, when homophones sound identical either way.",
        "Picking the more familiar or frequent spelling of a homophone pair without checking whether its specific meaning actually fits the sentence.",
      ],
      examTip: "Whenever you meet a word that has a common sound-alike twin, pause and silently define it before moving on — this single habit catches almost every homophone trap.",
      searchTerms: ["homophone", "threw through", "bare bear", "right write", "see sea", "spelling"],
    },
    {
      id: "common-homophone-pairs-one",
      title: "Common Homophone Pairs I",
      tier: "Standard",
      objective: "Correctly distinguish whose/who's, weather/whether, and allowed/aloud, three high-frequency 11+ homophone pairs.",
      whyMatters: "these three pairs turn up constantly in GL and CSSE-style spelling and cloze questions, and each has a simple, reliable test to tell the pair apart.",
      conceptTitle: "Three pairs, three quick tests",
      conceptBullets: [
        '<b style="color:#C9A24B">Whose</b> shows ownership ("whose coat is this?"); <b>who\'s</b> is short for "who is" or "who has".',
        '<b>Weather</b> means atmospheric conditions (rain, sun); <b>whether</b> introduces a choice between options ("whether to stay or go").',
        '<b>Allowed</b> means given permission; <b>aloud</b> means spoken out loud.',
        "Each pair has a simple expansion or substitution test: try replacing “who's” with “who is”, or checking whether the sentence is about permission or volume.",
      ],
      conceptNote: "<b>Test it:</b> expand “who's” into “who is” and see if it still makes sense — if not, you need the possessive “whose” instead.",
      glossary: [
        { term: "whose", def: "shows ownership (whose book is this?)" },
        { term: "who's", def: "short for who is / who has" },
        { term: "weather", def: "atmospheric conditions" },
        { term: "whether", def: "introduces a choice between options" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: CommonHomophonePairsOneDemo,
      worked: {
        question: "Spot the error: “She wasn't sure weather to bring an umbrella or not.”",
        fastMethod: 'the sentence is about a choice between two options, not atmospheric conditions — "whether" is needed.',
        steps: [
          "Read the sentence for meaning: it's about deciding between two options.",
          "Check “weather” — it refers to rain, sun, temperature, which doesn't fit a choice.",
          "The correct homophone for introducing a choice is “whether”.",
          "Corrected: “She wasn't sure whether to bring an umbrella or not.”",
        ],
        answer: "The error is <b>weather</b> — it should be <b>whether</b>.",
      },
      selfCheck: { prompt: "True or false: “The teacher who's classroom is nearest the hall” is correct.", answer: "<b>False</b> — expanding “who's” gives “who is classroom”, which makes no sense; the possessive “whose” is needed: whose classroom." },
      kind: "click-error",
      questions: [
        {
          id: "chp1-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "children", "were", "not", "aloud", "to", "leave", "the", "hall", "early."],
          errorIdx: 4,
          correction: '"aloud" means spoken out loud — the word needed here, about permission, is "allowed": were not allowed to leave.',
          hint: "Check whether this sentence is about permission or about speaking out loud.",
        },
        {
          id: "chp1-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Do", "you", "know", "who's", "umbrella", "was", "left", "outside", "the", "classroom?"],
          errorIdx: 3,
          correction: '"who\'s" expands to "who is umbrella", which makes no sense — the possessive "whose" is needed: whose umbrella.',
          hint: "Expand the apostrophe word into two words and check whether it still makes sense before “umbrella”.",
        },
        {
          id: "chp1-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "forecast", "predicted", "clear", "whether", "for", "the", "whole", "weekend."],
          errorIdx: 4,
          correction: '"whether" introduces a choice, but this sentence is about atmospheric conditions — "weather" is needed: predicted clear weather.',
          hint: "Check whether this sentence is describing atmospheric conditions or introducing a choice between two options.",
        },
      ],
      mistakes: [
        "Confusing “weather” and “whether” because they sound identical and both can appear near words about uncertainty (“not sure”).",
        "Forgetting to expand “who's” into “who is” as a quick check before accepting it.",
      ],
      examTip: "For “who's”, always try the “who is” expansion first — it takes one second and catches this error almost every time.",
      searchTerms: ["whose", "who's", "weather", "whether", "allowed", "aloud", "homophone"],
    },
    {
      id: "common-homophone-pairs-two",
      title: "Common Homophone Pairs II",
      tier: "Standard",
      objective: "Correctly distinguish stationary/stationery, complement/compliment, and principal/principle, three trickier homophone pairs tested at 11+.",
      whyMatters: "these three pairs are less common in everyday speech than the first set, which makes them easy to mix up under exam pressure without a clear memory trick for each.",
      conceptTitle: "Three trickier pairs, three memory tricks",
      conceptBullets: [
        '<b style="color:#C9A24B">Stationary</b> means not moving; <b>stationery</b> means paper and pens (remember: "stationery" and "letter" both have an "e").',
        '<b>Complement</b> means something that completes or goes well with another thing; <b>compliment</b> means a nice remark (remember: "I" like a nice compliment).',
        '<b>Principal</b> means the head of a school, or most important; <b>principle</b> means a rule or belief (remember: the "pal" at the end of "principal" is your school\'s "pal").',
        "Each pair has a small memory hook built into its spelling — learning the hook is far more reliable than guessing from sound.",
      ],
      conceptNote: "<b>Tip:</b> when in doubt, picture the memory trick for each pair rather than trusting how the word sounds in the sentence.",
      glossary: [
        { term: "stationary", def: "not moving" },
        { term: "stationery", def: "paper, pens and other writing materials" },
        { term: "complement", def: "something that completes or goes well with another thing" },
        { term: "compliment", def: "a nice remark about someone" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: CommonHomophonePairsTwoDemo,
      worked: {
        question: "Spot the error: “The car remained stationery at the red light for almost a minute.”",
        fastMethod: 'the sentence describes a car not moving — the "not moving" spelling, "stationary", is needed, not the paper-and-pens spelling.',
        steps: [
          "Read the sentence for meaning: the car isn't moving.",
          "Check “stationery” — that spelling refers to paper and pens, which doesn't fit a car.",
          "The correct homophone for “not moving” is “stationary”.",
          "Corrected: “The car remained stationary at the red light.”",
        ],
        answer: "The error is <b>stationery</b> — it should be <b>stationary</b>.",
      },
      selfCheck: { prompt: "True or false: the head teacher of a school is correctly called the “principle”.", answer: "<b>False</b> — the head of a school is the “principal”; “principle” means a rule or belief, not a person." },
      kind: "click-error",
      questions: [
        {
          id: "chp2-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "shop", "sells", "pens,", "pencils", "and", "other", "stationary", "for", "school."],
          errorIdx: 7,
          correction: '"stationary" means not moving — the word needed for paper and pens is "stationery": other stationery for school.',
          hint: "Check whether this word should mean “not moving” or “paper and pens.”",
        },
        {
          id: "chp2-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Honesty", "is", "one", "of", "the", "school's", "most", "important", "principals."],
          errorIdx: 8,
          correction: '"principals" refers to heads of schools — the word needed for a core belief or rule is "principles": most important principles.',
          hint: "Check whether this word should mean “a rule or belief” or “a person in charge.”",
        },
        {
          id: "chp2-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "scarf", "was", "a", "perfect", "compliment", "to", "her", "winter", "coat."],
          errorIdx: 5,
          correction: '"compliment" means a nice remark about someone — the word needed here, for two things going well together, is "complement": a perfect complement to her coat.',
          hint: "Decide whether this sentence is about the scarf going well with the coat, or about someone giving a nice remark.",
        },
      ],
      mistakes: [
        "Mixing up “stationary” and “stationery” because they differ by only one letter.",
        "Assuming “principal” always refers to a rule, when it usually refers to the head of a school or something of primary importance.",
      ],
      examTip: "Attach each pair's memory hook (stationery has an “e” like letter; principal has “pal” like your school's head) rather than guessing from how the word sounds.",
      searchTerms: ["stationary", "stationery", "complement", "compliment", "principal", "principle", "homophone"],
    },
    {
      id: "silent-difference-homophones",
      title: "Homophones with Silent Differences",
      tier: "Extension",
      objective: "Correctly distinguish break/brake, led/lead, and past/passed, homophone pairs where the spelling difference carries no audible clue at all.",
      whyMatters: "these pairs are especially tricky because there's no visible pattern connecting spelling to meaning the way there is with, say, stationery's shared “e” with letter — each one simply has to be individually memorised.",
      conceptTitle: "No pattern to lean on — memorise the meaning directly",
      conceptBullets: [
        '<b style="color:#C9A24B">Break</b> means to split or shatter; <b>brake</b> means to slow down a vehicle, or the device that does it.',
        '<b>Led</b> is the past tense of the verb "to lead" (to guide); <b>lead</b> (rhyming with "led") is also a heavy grey metal — context, not sound, tells them apart.',
        '<b>Past</b> is a noun/adjective meaning a time before now; <b>passed</b> is the past tense of the verb "to pass" (to go by or succeed at something).',
        "Because none of these pairs share an obvious spelling pattern the way stationery/letter do, the only reliable strategy is learning each meaning directly and testing it against the sentence.",
      ],
      conceptNote: "<b>Test it:</b> for led/lead, ask whether the sentence needs a past-tense verb (led) or a noun for the metal (lead) — that distinction alone solves this pair every time.",
      glossary: [
        { term: "break", def: "to split or shatter something" },
        { term: "brake", def: "to slow a vehicle, or the device that does it" },
        { term: "led", def: "past tense of the verb “to lead” (guided)" },
        { term: "passed", def: "past tense of the verb “to pass” (went by, succeeded)" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: SilentDifferenceHomophonesDemo,
      worked: {
        question: "Spot the error: “She lead the team to victory in last year's final.”",
        fastMethod: 'the sentence needs a past-tense verb describing guiding the team — that spelling is "led", not "lead" (the metal).',
        steps: [
          "Read the sentence for meaning: it describes an action that already happened, guiding the team.",
          "Check “lead” — as written, that spelling names the grey metal, which doesn't fit a verb here.",
          "The past-tense verb spelling is “led”.",
          "Corrected: “She led the team to victory in last year's final.”",
        ],
        answer: "The error is <b>lead</b> — it should be <b>led</b>.",
      },
      selfCheck: { prompt: "True or false: “passed” and “past” can always be swapped for each other with no change in meaning.", answer: "<b>False</b> — “passed” is a verb (she passed the shop), while “past” is a noun or adjective (in the past, drove past the shop); they aren't interchangeable." },
      kind: "click-error",
      questions: [
        {
          id: "sdh-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "driver", "forgot", "to", "break", "at", "the", "junction", "and", "nearly", "hit", "a", "cyclist."],
          errorIdx: 4,
          correction: '"break" means to split or shatter something — the word needed here, about slowing a vehicle, is "brake": forgot to brake at the junction.',
          hint: "Find the word describing what a driver does to slow down, and check its spelling against “to shatter.”",
        },
        {
          id: "sdh-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "muddy", "footprints", "lead", "the", "detective", "straight", "to", "the", "hidden", "safe."],
          errorIdx: 3,
          correction: '"lead" (rhyming with "led") names the heavy grey metal — the past-tense verb needed here, describing guiding someone, is "led": footprints led the detective.',
          hint: "Check whether this word should be the past-tense verb for “guided” or the name of a heavy grey metal.",
        },
        {
          id: "sdh-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "cyclist", "past", "the", "finish", "line", "in", "record", "time."],
          errorIdx: 2,
          correction: '"past" is a noun/adjective for a time before now — the verb describing going by the finish line is "passed": passed the finish line.',
          hint: "Check whether this word should be the noun for “a time before now” or the verb for “went by.”",
        },
      ],
      mistakes: [
        "Assuming a familiar-looking spelling must be correct, when these pairs have no pattern connecting spelling to meaning.",
        "Mixing up “led” (the verb) and “lead” (the metal) because they're spelled identically to two different unrelated words.",
      ],
      examTip: "For these especially tricky pairs, learn each meaning as its own separate vocabulary item rather than trying to find a spelling rule — there isn't one.",
      searchTerms: ["break", "brake", "led", "lead", "past", "passed", "homophone"],
    },
  ],
};
