import type { TopicContent } from "../types";
import {
  WhatIsInferenceDemo,
  InferenceFromActionDialogueDemo,
  InferenceFromDescriptiveDetailDemo,
  InferenceVsOverGuessingDemo,
} from "../notes-diagrams/inference-demos";

export const inferenceTopic: TopicContent = {
  slug: "inference",
  subject: "English",
  subjectSlug: "english",
  title: "Comprehension: Inference",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "Once Literal Retrieval is secure, every GL, CEM and CSSE paper moves on to questions that ask what a passage suggests, not just what it states outright. This module covers what inference actually is, reading emotion from action and dialogue, reading atmosphere from descriptive detail, and the crucial exam skill of telling a safe, text-supported inference apart from an unsupported guess.",
  subtopics: [
    {
      id: "what-is-inference",
      title: "What Is Inference?",
      tier: "Foundation",
      objective: "Understand what an inference question asks for, and how it differs from a literal retrieval question.",
      whyMatters: "inference questions make up a large share of every comprehension paper, and losing marks here usually means answering with a guess instead of a text-supported conclusion.",
      conceptTitle: "Reading between the lines, carefully",
      conceptBullets: [
        'An <b style="color:#C9A24B">inference</b> is a sensible conclusion you reach by combining a detail in the text with your own reasoning — the text never states the conclusion outright.',
        "This is different from literal retrieval, where the exact answer is written directly in the passage.",
        'Example: "her hands shook as she read the letter" doesn\'t say she was nervous — but a reader can reasonably infer it.',
        "A good inference is always traceable back to a specific detail in the text, not invented from nothing.",
      ],
      conceptNote: "<b>Golden rule:</b> an inference answer should always be backable up with 'because the text says...' — if you can't point to the clue, it isn't a safe inference.",
      glossary: [
        { term: "inference", def: "a sensible conclusion reached by combining a text detail with reasoning" },
        { term: "literal question", def: "asks about something the text states directly" },
        { term: "clue", def: "the specific detail in the text that supports an inference" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: WhatIsInferenceDemo,
      worked: {
        question: 'Passage excerpt: "Sam kept glancing at the clock and tapping his pen against the desk." Question: "How does Sam seem to be feeling?"',
        fastMethod: "Two small physical details combine to suggest impatience or anxiety, even though no feeling word is used.",
        steps: [
          "Notice the question asks how Sam “seems” to feel — a sign this is inference, not retrieval.",
          "Identify the physical clues: glancing at the clock, tapping his pen.",
          "Combine these clues with reasoning: both actions are common signs of impatience or nervousness.",
          "State the inference and support it with the clue.",
        ],
        answer: 'Sam seems <b>impatient or anxious</b>, inferred from him glancing at the clock and tapping his pen.',
      },
      selfCheck: { prompt: "True or false: an inference answer can be anything plausible, even without pointing to a specific detail in the text.", answer: "<b>False</b> — a safe inference always traces back to a specific clue in the text; an answer with no textual support is just a guess." },
      kind: "click-evidence",
      questions: [
        {
          id: "wii-q1",
          instruction: "Click the sentence that lets you infer Grandpa was nervous about the interview.",
          passage: [
            "Grandpa straightened his tie in the hallway mirror for the third time that morning.",
            "The taxi was booked for half past nine.",
            "He had worked at the newspaper for over twenty years.",
            "The interview was for a feature about local history.",
          ],
          correctIdx: 0,
          correction: 'straightening his tie three times is a physical detail suggesting nervousness — the text never states he was nervous outright.',
          hint: "Look for a small, repeated physical action rather than a plain fact about the interview.",
        },
        {
          id: "wii-q2",
          instruction: "Click the sentence that lets you infer the twins hadn't spoken in a while.",
          passage: [
            "The twins stood awkwardly at opposite ends of the platform, checking their phones.",
            "The train was delayed by six minutes.",
            "Neither one crossed the gap to say hello.",
            "It was a cold morning, with frost still on the benches.",
          ],
          correctIdx: 2,
          correction: '"neither one crossed the gap to say hello" is the detail that lets a reader infer distance or tension between them — it\'s never stated directly.',
          hint: "Look for the detail describing what the twins chose not to do, rather than a neutral fact about the weather or train.",
        },
        {
          id: "wii-q3",
          instruction: "Click the sentence that lets you infer the shopkeeper recognised the customer.",
          passage: [
            "The bell above the door jingled as the customer stepped inside.",
            "The shopkeeper's face broke into a wide smile before a word was spoken.",
            "Rain had been falling steadily since lunchtime.",
            "A queue of three people waited at the till.",
          ],
          correctIdx: 1,
          correction: '"broke into a wide smile before a word was spoken" suggests recognition and familiarity — the text never says the two knew each other.',
          hint: "Look for a reaction that happens before any dialogue, suggesting the shopkeeper already knew something.",
        },
      ],
      mistakes: [
        "Confusing an inference question with a literal one and hunting for a sentence that states the answer outright, when none exists.",
        "Giving an answer that isn't traceable back to any specific detail in the text at all.",
      ],
      examTip: "If a question uses words like “seems”, “suggests”, “what does this tell you”, or “how might X be feeling”, it is asking for an inference — go looking for a supporting clue, not a direct statement.",
      searchTerms: ["inference", "reading between the lines", "comprehension", "clue", "literal vs inference"],
    },
    {
      id: "inference-from-action-dialogue",
      title: "Inferring from Character Actions & Dialogue",
      tier: "Standard",
      objective: "Draw sensible conclusions about a character's feelings or intentions from how they act and speak, not just what they say.",
      whyMatters: "the way a line of dialogue is delivered, or a small gesture a character makes, often carries more meaning than the plain content of what's said — and exams test exactly this skill.",
      conceptTitle: "It's not just what they say — it's how",
      conceptBullets: [
        'The manner of an <b style="color:#C9A24B">action</b> or piece of dialogue (quickly, quietly, without meeting someone\'s eyes) often reveals more than its content.',
        'Example: "Nothing happened," he said quickly, not meeting her eyes" — the content is a denial, but the manner suggests he is hiding something.',
        "Small, repeated or nervous gestures (fidgeting, avoiding eye contact, checking something twice) are common signals writers use instead of stating a feeling directly.",
        "Always link the specific action or manner of speech back to what it plausibly reveals about the character's inner state.",
      ],
      conceptNote: "<b>Test it:</b> ask “would a calm, honest person act or speak this way?” — if not, that gap is usually exactly what the question wants you to notice.",
      glossary: [
        { term: "manner", def: "how something is said or done (quickly, hesitantly, loudly)" },
        { term: "body language", def: "physical behaviour that reveals feeling without stating it" },
        { term: "avoidance", def: "behaviour (like avoiding eye contact) that often signals discomfort or dishonesty" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: InferenceFromActionDialogueDemo,
      worked: {
        question: 'Passage excerpt: "\'I haven\'t seen it,\' Jamal muttered, shoving his hands deep into his pockets." Question: "What might this suggest about Jamal?"',
        fastMethod: "Two behavioural clues — muttering, and hiding his hands — both commonly signal discomfort or dishonesty.",
        steps: [
          "Identify the dialogue's content: a plain denial, “I haven't seen it.”",
          "Notice the manner: muttering (not speaking clearly) and shoving hands into pockets (a defensive gesture).",
          "Combine these clues: both often signal someone is uncomfortable or not telling the full truth.",
          "State the inference, supported by both details.",
        ],
        answer: "Jamal <b>may not be telling the truth</b>, inferred from his muttering and defensive body language.",
      },
      selfCheck: { prompt: "True or false: dialogue delivered “confidently and clearly” usually suggests the same discomfort as dialogue delivered “quietly, avoiding eye contact.”", answer: "<b>False</b> — the manner of delivery matters; confident, clear delivery generally signals the opposite of discomfort or dishonesty." },
      kind: "click-evidence",
      questions: [
        {
          id: "iad-q1",
          instruction: "Click the sentence that suggests the coach was disappointed, without saying so directly.",
          passage: [
            '"Good effort, everyone," the coach said flatly, already turning to gather the cones.',
            "The final score had been three-nil.",
            "Training would resume on Thursday as usual.",
            "Several players sat down to retie their laces.",
          ],
          correctIdx: 0,
          correction: '"said flatly, already turning to gather the cones" suggests the praise was half-hearted and the coach wanted to move on quickly — a sign of disappointment never stated outright.',
          hint: "Look at how the coach's words were delivered, not just what they said.",
        },
        {
          id: "iad-q2",
          instruction: "Click the sentence that suggests Aunt Rosa was excited about the news, without saying so directly.",
          passage: [
            "Aunt Rosa read the letter once, then read it again out loud to the whole kitchen.",
            "The letter had arrived with the second post, just after lunch.",
            "It was addressed in small, neat handwriting.",
            "The kettle had just finished boiling on the stove.",
          ],
          correctIdx: 0,
          correction: '"read it again out loud to the whole kitchen" suggests eagerness to share exciting news — the excitement is shown through her actions, not named directly.',
          hint: "Look for the sentence describing an eager, repeated action rather than a neutral fact about the letter's arrival.",
        },
        {
          id: "iad-q3",
          instruction: "Click the sentence that suggests Dan was trying to avoid a question.",
          passage: [
            '"So, where were you at lunchtime?" his friend asked.',
            '"Around," Dan said, already halfway out of the classroom door.',
            "The bell had rung two minutes earlier.",
            "Most of the class had already left for the canteen.",
          ],
          correctIdx: 1,
          correction: '"already halfway out of the classroom door" while giving a vague one-word answer suggests Dan wants to escape the question rather than answer it properly.',
          hint: "Look at how Dan responds — both the vagueness of his answer and what he's doing while he says it.",
        },
      ],
      mistakes: [
        "Focusing only on the content of dialogue and ignoring the manner it's delivered in, which often carries the real clue.",
        "Inventing a feeling that isn't actually supported by any described action or manner of speech.",
      ],
      examTip: "When a question asks about a character's feelings during a conversation, check the stage directions around the dialogue (how it's said, what the character is doing) as closely as the words themselves.",
      searchTerms: ["inference", "dialogue", "body language", "character feelings", "comprehension"],
    },
    {
      id: "inference-from-descriptive-detail",
      title: "Inferring Atmosphere from Descriptive Detail",
      tier: "Standard",
      objective: "Recognise how a writer builds mood or atmosphere through carefully chosen setting details, without ever stating the mood directly.",
      whyMatters: "atmosphere questions ask what a passage's setting suggests about mood — a skill built entirely on noticing which descriptive details were deliberately chosen to create a feeling.",
      conceptTitle: "Setting details create feeling indirectly",
      conceptBullets: [
        'A writer builds <b style="color:#C9A24B">atmosphere</b> — the overall mood or feeling of a scene — through carefully chosen sensory and setting details, never by simply stating "it was scary" or "it felt peaceful."',
        'Example: "a door creaked and swung slowly shut on its own" builds unease through an unexplained, slightly eerie event, without a single word naming fear.',
        "Look for details involving light and dark, sound (or its absence), temperature, and unexplained movement — these are common atmosphere-building tools.",
        "Neutral background facts (the time, the building's history) don't usually build atmosphere on their own — separate these from the details doing the atmospheric work.",
      ],
      conceptNote: "<b>Test it:</b> ask “does this detail make me feel something, or is it just a plain fact?” — atmosphere clues are the ones that stir a feeling.",
      glossary: [
        { term: "atmosphere", def: "the overall mood or feeling created by a scene's description" },
        { term: "sensory detail", def: "description involving sight, sound, smell, touch or taste" },
        { term: "unexplained detail", def: "a small, unresolved event (a creaking door) that builds tension" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: InferenceFromDescriptiveDetailDemo,
      worked: {
        question: 'Passage excerpt: "The garden was silent except for the slow drip of the broken fountain." Question: "What atmosphere does this sentence create?"',
        fastMethod: "Silence paired with one small, repetitive sound is a classic technique for building an eerie or lonely atmosphere.",
        steps: [
          "Notice the overall silence described — an absence of expected sound.",
          "Notice the single remaining sound: a slow, repetitive drip.",
          "Combine these: near-total silence broken only by one small, repeating noise often signals loneliness or unease.",
          "State the atmosphere and the detail supporting it.",
        ],
        answer: "The sentence creates a <b>lonely, slightly eerie atmosphere</b>, built from the silence and the single repetitive drip.",
      },
      selfCheck: { prompt: "True or false: a sentence stating “it was a peaceful, happy morning” is an example of building atmosphere through description.", answer: "<b>False</b> — that sentence states the mood directly; true atmosphere-building uses indirect sensory or setting detail to suggest a feeling instead of naming it." },
      kind: "click-evidence",
      questions: [
        {
          id: "iad2-q1",
          instruction: "Click the sentence that builds a peaceful, calm atmosphere.",
          passage: [
            "Sunlight spread slowly across the meadow as the last of the mist lifted.",
            "The farmhouse had been built almost a century ago.",
            "A tractor was parked beside the barn.",
            "The nearest village was two miles away.",
          ],
          correctIdx: 0,
          correction: '"sunlight spread slowly... as the last of the mist lifted" uses gentle, slow-moving imagery to build a calm, peaceful mood — the other sentences are neutral background facts.',
          hint: "Look for the sentence built from slow, gentle sensory imagery rather than a plain fact about the farmhouse or its location.",
        },
        {
          id: "iad2-q2",
          instruction: "Click the sentence that builds an uneasy, unsettling atmosphere.",
          passage: [
            "The lighthouse had stood on the headland for over a hundred years.",
            "A single light flickered on somewhere near the top, though no one had climbed the stairs in years.",
            "Ferries ran to the mainland twice a day.",
            "The keeper's cottage had been empty since the 1980s.",
          ],
          correctIdx: 1,
          correction: '"a single light flickered on... though no one had climbed the stairs in years" is an unexplained, faintly eerie detail that builds unease — the rest are plain historical facts.',
          hint: "Look for the detail that describes something happening with no clear explanation, rather than a fact about the lighthouse's history or the ferry schedule.",
        },
        {
          id: "iad2-q3",
          instruction: "Click the sentence that builds a tense, threatening atmosphere.",
          passage: [
            "Dark clouds gathered low over the hill, and the wind dropped to nothing.",
            "The village fete was scheduled for the following weekend.",
            "The bakery on the corner opened at seven each morning.",
            "Several stalls were already being set up in the square.",
          ],
          correctIdx: 0,
          correction: '"dark clouds gathered low... and the wind dropped to nothing" is classic storm-approaching imagery that builds tension and threat — the other sentences are neutral village facts.',
          hint: "Look for the sentence describing changing weather in a way that hints at something ominous approaching.",
        },
      ],
      mistakes: [
        "Picking a neutral factual sentence (dates, distances, schedules) instead of the sentence actually doing the atmospheric work.",
        "Looking only for obviously scary or obviously happy words, and missing subtler atmosphere built through quiet, indirect detail.",
      ],
      examTip: "Atmosphere questions reward you for noticing sensory detail (light, sound, temperature, unexplained movement) — scan for these first before considering plainer factual sentences.",
      searchTerms: ["atmosphere", "mood", "descriptive detail", "setting", "comprehension", "inference"],
    },
    {
      id: "inference-vs-over-guessing",
      title: "Safe Inference vs. Over-Guessing",
      tier: "Extension",
      objective: "Distinguish a safe inference, grounded in a specific text detail, from an unsupported guess that goes beyond what the text can reasonably support.",
      whyMatters: "the highest-scoring inference answers are precise and text-supported — vague or invented answers that sound plausible but aren't traceable to the text lose marks even when they're not technically 'wrong'.",
      conceptTitle: "Grounded in the text, not just plausible",
      conceptBullets: [
        'A <b style="color:#C9A24B">safe inference</b> is traceable to one specific detail in the text and doesn\'t claim more than that detail can support.',
        "An over-guess invents extra detail the text never actually gives — for example, inferring a specific reason for a feeling when the text only supports the feeling itself.",
        'Example: "Leo threw both arms in the air" safely supports "Leo felt triumphant" — but claiming "Leo was proud because he\'d trained for two years" invents information the text never gave.',
        "When multiple details are available, choose the one that most directly and specifically supports the conclusion, not a neutral background fact.",
      ],
      conceptNote: "<b>Test it:</b> after making an inference, check whether every part of your answer can be pointed back to the text — any part that can't is over-guessing.",
      glossary: [
        { term: "safe inference", def: "a conclusion fully supported by a specific detail in the text" },
        { term: "over-guessing", def: "adding detail or reasoning the text doesn't actually support" },
        { term: "textual support", def: "the exact detail an inference can be traced back to" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: InferenceVsOverGuessingDemo,
      worked: {
        question: 'Passage excerpt: "Amara stared at the acceptance letter for a long moment before letting out a breath she hadn\'t realised she\'d been holding." Question: "What can you infer about how Amara felt, and what is your evidence?"',
        fastMethod: "The physical detail of held breath being released is a safe, specific signal of relief — don't add a reason the text doesn't give.",
        steps: [
          "Identify the specific physical detail: letting out a held breath.",
          "This detail safely supports relief (and likely happiness) about the letter's contents.",
          "Avoid adding invented detail, e.g. a specific reason why she applied, which the text doesn't mention.",
          "State the safe inference, tied only to the detail actually given.",
        ],
        answer: "Amara felt <b>relieved</b>, inferred from letting out a breath she hadn't realised she was holding — nothing more specific than that should be claimed.",
      },
      selfCheck: { prompt: "True or false: it's safe to infer a character's entire backstory from one small gesture described in a passage.", answer: "<b>False</b> — a single gesture can safely support a general feeling, but inventing a detailed backstory or specific reason the text never mentions is over-guessing." },
      kind: "click-evidence",
      questions: [
        {
          id: "ivo-q1",
          instruction: "Click the one sentence that safely supports the idea that Ben was relieved, without over-guessing his exact reasons.",
          passage: [
            "Ben let his shoulders drop as the results were read out.",
            "The exam had covered three whole terms of work.",
            "Several other students were still waiting for their names to be called.",
            "The hall clock read a quarter past two.",
          ],
          correctIdx: 0,
          correction: '"let his shoulders drop" is a specific physical detail that safely supports relief — the other sentences are neutral background facts, not evidence of feeling.',
          hint: "Look for the one sentence describing a physical reaction, not a neutral fact about the exam or the time.",
        },
        {
          id: "ivo-q2",
          instruction: "Click the one sentence that safely supports the idea that Nadia was surprised, without over-guessing why.",
          passage: [
            "Nadia's mouth fell open and she nearly dropped her cup.",
            "The kitchen table had been set for breakfast as usual.",
            "It was a Tuesday morning in early spring.",
            "The radio was playing quietly in the background.",
          ],
          correctIdx: 0,
          correction: '"her mouth fell open and she nearly dropped her cup" is a specific, physical reaction that safely supports surprise — the rest are neutral setting details, giving no clue to her feeling.',
          hint: "Look for the sentence describing a sudden physical reaction, not a fact about the day or the kitchen setting.",
        },
        {
          id: "ivo-q3",
          instruction: "Click the one sentence that safely supports the idea that the twins were competitive with each other, without over-guessing further detail.",
          passage: [
            "The twins raced each other to be first through the door every single morning.",
            "Their school was a fifteen-minute walk from home.",
            "Both twins were in the same class this year.",
            "The school day started at nine o'clock.",
          ],
          correctIdx: 0,
          correction: '"raced each other to be first through the door every single morning" is a specific, repeated behaviour that safely supports a competitive relationship — the other sentences are neutral scheduling facts.',
          hint: "Look for the sentence describing a repeated behaviour between the twins, not a fact about the school itself.",
        },
      ],
      mistakes: [
        "Choosing a neutral background sentence as \"evidence\" simply because it's the closest one, rather than the sentence that actually supports the feeling.",
        "Adding invented specifics (a reason, a backstory, an exact thought) that go beyond what the chosen detail can actually support.",
      ],
      examTip: "After forming an inference, try to say only what the text detail directly supports — if you find yourself adding “because…” with information from your imagination rather than the passage, trim it back.",
      searchTerms: ["safe inference", "over-guessing", "textual evidence", "comprehension", "supported answer"],
    },
  ],
};
