import type { TopicContent } from "../types";
import {
  WhatIsInferenceDemo,
  ClueWordsSignalPhrasesDemo,
  InferenceFromActionDialogueDemo,
  InferringCharacterFeelingsDemo,
  InferenceFromDescriptiveDetailDemo,
  InferringSettingAtmosphereDemo,
  InferenceVsOverGuessingDemo,
  InferringWritersAttitudeDemo,
  CombiningMultipleCluesDemo,
} from "../notes-diagrams/inference-demos";

export const inferenceTopic: TopicContent = {
  slug: "inference",
  subject: "English",
  subjectSlug: "english",
  title: "Comprehension: Inference",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "Once Literal Retrieval is secure, every GL, CEM and CSSE paper moves on to questions that ask what a passage suggests, not just what it states outright. This module covers what inference actually is, reading emotion from action and dialogue, reading atmosphere from descriptive detail, and the crucial exam skill of telling a safe, text-supported inference apart from an unsupported guess.",
  subtopics: [
    {
      id: "what-is-inference",
      title: "What Is Inference?",
      tier: "Foundation",
      objective: "Understand what an inference question asks for, and how it differs from a literal retrieval question.",
      whyMatters: "inference questions make up a large share of every comprehension paper, and losing marks here usually means answering with a guess instead of a text-supported conclusion.",
      conceptTitle: "Reading between the lines, carefully",
      conceptBullets: [
        'An <b style="color:#C9A24B">inference</b> is a sensible conclusion you reach by combining a detail in the text with your own reasoning — the text never states the conclusion outright.',
        "This is different from literal retrieval, where the exact answer is written directly in the passage.",
        'Example: "her hands shook as she read the letter" doesn\'t say she was nervous — but a reader can reasonably infer it.',
        "A good inference is always traceable back to a specific detail in the text, not invented from nothing.",
      ],
      conceptNote: "<b>Golden rule:</b> an inference answer should always be backable up with 'because the text says...' — if you can't point to the clue, it isn't a safe inference.",
      glossary: [
        { term: "inference", def: "a sensible conclusion reached by combining a text detail with reasoning" },
        { term: "literal question", def: "asks about something the text states directly" },
        { term: "clue", def: "the specific detail in the text that supports an inference" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: WhatIsInferenceDemo,
      worked: {
        question: 'Passage excerpt: "Sam kept glancing at the clock and tapping his pen against the desk." Question: "How does Sam seem to be feeling?"',
        fastMethod: "Two small physical details combine to suggest impatience or anxiety, even though no feeling word is used.",
        steps: [
          "Notice the question asks how Sam “seems” to feel — a sign this is inference, not retrieval.",
          "Identify the physical clues: glancing at the clock, tapping his pen.",
          "Combine these clues with reasoning: both actions are common signs of impatience or nervousness.",
          "State the inference and support it with the clue.",
        ],
        answer: 'Sam seems <b>impatient or anxious</b>, inferred from him glancing at the clock and tapping his pen.',
      },
      selfCheck: { prompt: "True or false: an inference answer can be anything plausible, even without pointing to a specific detail in the text.", answer: "<b>False</b> — a safe inference always traces back to a specific clue in the text; an answer with no textual support is just a guess." },
      kind: "click-evidence",
      questions: [
        {
          id: "wii-q1",
          instruction: "Click the sentence that lets you infer Grandpa was nervous about the interview.",
          passage: [
            "Grandpa straightened his tie in the hallway mirror for the third time that morning.",
            "The taxi was booked for half past nine.",
            "He had worked at the newspaper for over twenty years.",
            "The interview was for a feature about local history.",
          ],
          correctIdx: 0,
          correction: 'straightening his tie three times is a physical detail suggesting nervousness — the text never states he was nervous outright.',
          hint: "Look for a small, repeated physical action rather than a plain fact about the interview.",
        },
        {
          id: "wii-q2",
          instruction: "Click the sentence that lets you infer the twins hadn't spoken in a while.",
          passage: [
            "The twins stood awkwardly at opposite ends of the platform, checking their phones.",
            "The train was delayed by six minutes.",
            "Neither one crossed the gap to say hello.",
            "It was a cold morning, with frost still on the benches.",
          ],
          correctIdx: 2,
          correction: '"neither one crossed the gap to say hello" is the detail that lets a reader infer distance or tension between them — it\'s never stated directly.',
          hint: "Look for the detail describing what the twins chose not to do, rather than a neutral fact about the weather or train.",
        },
        {
          id: "wii-q3",
          instruction: "Click the sentence that lets you infer the shopkeeper recognised the customer.",
          passage: [
            "The bell above the door jingled as the customer stepped inside.",
            "The shopkeeper's face broke into a wide smile before a word was spoken.",
            "Rain had been falling steadily since lunchtime.",
            "A queue of three people waited at the till.",
          ],
          correctIdx: 1,
          correction: '"broke into a wide smile before a word was spoken" suggests recognition and familiarity — the text never says the two knew each other.',
          hint: "Look for a reaction that happens before any dialogue, suggesting the shopkeeper already knew something.",
        },
      ],
      mistakes: [
        "Confusing an inference question with a literal one and hunting for a sentence that states the answer outright, when none exists.",
        "Giving an answer that isn't traceable back to any specific detail in the text at all.",
      ],
      examTip: "If a question uses words like “seems”, “suggests”, “what does this tell you”, or “how might X be feeling”, it is asking for an inference — go looking for a supporting clue, not a direct statement.",
      searchTerms: ["inference", "reading between the lines", "comprehension", "clue", "literal vs inference"],
    },
    {
      id: "clue-words-signal-phrases",
      title: "Clue Words and Signal Phrases",
      tier: "Foundation",
      objective: "Learn to spot the exact words in a sentence that act as the clue for an inference, rather than treating a whole sentence as equally important.",
      whyMatters: "under exam time pressure, students who scan for clue words work far faster and more accurately than those re-reading the whole passage looking for a feeling to jump out at them.",
      conceptTitle: "Not every word is a clue — some are doing all the work",
      conceptBullets: [
        'A <b style="color:#C9A24B">signal word</b> is a specific verb, adverb or small action within a sentence that carries the real clue to an inference — the rest of the sentence is often just neutral context around it.',
        'Verbs of manner (snapped, mumbled, beamed, snatched) tell you far more than neutral verbs (said, walked, put down) — "she snapped the book shut" signals irritation in a way "she closed the book" never could.',
        "Adverbs attached to an action (quietly, suddenly, reluctantly) often carry the clue on their own, even when the action itself is ordinary.",
        "Small physical actions (a clenched fist, a glance away, a held breath) are frequently the single clue-bearing detail in an otherwise neutral sentence.",
      ],
      conceptNote: "<b>Scan for this:</b> before reading a whole passage for meaning, run your eye over the verbs and adverbs first — they're usually where the clue-bearing words are hiding.",
      glossary: [
        { term: "signal word", def: "a specific word (often a verb or adverb) that carries an inference's clue" },
        { term: "verb of manner", def: "a verb describing how something was done, not just that it was done (snapped vs. said)" },
        { term: "neutral detail", def: "background information in a sentence that carries no emotional clue" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: ClueWordsSignalPhrasesDemo,
      worked: {
        question: 'Passage excerpt: "Ollie mumbled his answer and stared at his shoes." Question: "What does this suggest about how Ollie felt answering the question?"',
        fastMethod: "Scan the verbs first: “mumbled” and “stared at his shoes” are both signal words for discomfort — no need to read anything else in the sentence for a clue.",
        steps: [
          "Identify the verbs in the sentence: mumbled, stared.",
          "Ask whether each is a neutral verb or a verb of manner — “mumbled” (not spoke clearly) and “stared at his shoes” (avoided eye contact) are both signal words.",
          "Combine the two signal words: both point to embarrassment or a lack of confidence.",
          "State the inference, naming the exact signal words as evidence.",
        ],
        answer: "Ollie seems <b>embarrassed or unsure of himself</b>, inferred from the signal words “mumbled” and “stared at his shoes.”",
      },
      selfCheck: { prompt: "True or false: in the sentence “She walked into the room and sat down,” the verbs “walked” and “sat down” are strong signal words for an inference.", answer: "<b>False</b> — “walked” and “sat down” are neutral verbs with no clue about feeling; a signal word would be something like “stormed” or “slumped” instead." },
      kind: "click-evidence",
      questions: [
        {
          id: "cwsp-q1",
          instruction: "Click the sentence containing the clue word (a verb of manner) that suggests Elin was annoyed.",
          passage: [
            "Elin slammed her locker door and marched off down the corridor.",
            "The corridor had just been repainted over the summer.",
            "Lunch was due to start in ten minutes.",
            "Two younger students hurried past towards the hall.",
          ],
          correctIdx: 0,
          correction: '"slammed" and "marched off" are verbs of manner that signal anger or frustration — the other sentences contain only neutral background facts.',
          hint: "Look for the sentence with forceful, sharp verbs rather than a plain fact about the corridor or the time.",
        },
        {
          id: "cwsp-q2",
          instruction: "Click the sentence containing the adverb that is the real clue to how Noah felt about the news.",
          passage: [
            "Noah read the message twice.",
            "He set the phone down slowly, without saying a word.",
            "The message had arrived just after breakfast.",
            "His sister was still upstairs getting ready.",
          ],
          correctIdx: 1,
          correction: '"slowly" combined with saying nothing is the adverb-led clue suggesting Noah was shaken or upset by the news — the surrounding sentences are neutral facts about timing.',
          hint: "Look for the sentence with an adverb describing how an ordinary action was done, rather than a plain fact about when the message arrived.",
        },
        {
          id: "cwsp-q3",
          instruction: "Click the sentence containing the small physical action that is the real clue to how Mrs Patel felt.",
          passage: [
            "Mrs Patel's hand tightened around the mug she was holding.",
            "The staffroom had a large window overlooking the car park.",
            "It was nearly the end of the lunch break.",
            "A stack of exercise books sat unmarked on the table.",
          ],
          correctIdx: 0,
          correction: '"her hand tightened around the mug" is the small physical action carrying the clue to tension or worry — the rest of the sentences are neutral setting details.',
          hint: "Look for the sentence describing a small, tense physical action rather than a fact about the room or the time.",
        },
      ],
      mistakes: [
        "Treating an entire sentence as equally important instead of picking out the specific verb or adverb that actually carries the clue.",
        "Mistaking a neutral verb (walked, said, looked) for a signal word just because it's part of a sentence about a character.",
      ],
      examTip: "When scanning a passage quickly, run your eye over the verbs and adverbs first — clue-bearing words are usually more unusual or vivid than the neutral verbs around them (snapped vs. said, beamed vs. smiled).",
      searchTerms: ["signal words", "clue words", "verbs of manner", "adverbs", "comprehension"],
    },
    {
      id: "inference-from-action-dialogue",
      title: "Inferring from Character Actions & Dialogue",
      tier: "Standard",
      objective: "Draw sensible conclusions about a character's feelings or intentions from how they act and speak, not just what they say.",
      whyMatters: "the way a line of dialogue is delivered, or a small gesture a character makes, often carries more meaning than the plain content of what's said — and exams test exactly this skill.",
      conceptTitle: "It's not just what they say — it's how",
      conceptBullets: [
        'The manner of an <b style="color:#C9A24B">action</b> or piece of dialogue (quickly, quietly, without meeting someone\'s eyes) often reveals more than its content.',
        'Example: "Nothing happened," he said quickly, not meeting her eyes" — the content is a denial, but the manner suggests he is hiding something.',
        "Small, repeated or nervous gestures (fidgeting, avoiding eye contact, checking something twice) are common signals writers use instead of stating a feeling directly.",
        "Always link the specific action or manner of speech back to what it plausibly reveals about the character's inner state.",
      ],
      conceptNote: "<b>Test it:</b> ask “would a calm, honest person act or speak this way?” — if not, that gap is usually exactly what the question wants you to notice.",
      glossary: [
        { term: "manner", def: "how something is said or done (quickly, hesitantly, loudly)" },
        { term: "body language", def: "physical behaviour that reveals feeling without stating it" },
        { term: "avoidance", def: "behaviour (like avoiding eye contact) that often signals discomfort or dishonesty" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: InferenceFromActionDialogueDemo,
      worked: {
        question: 'Passage excerpt: "\'I haven\'t seen it,\' Jamal muttered, shoving his hands deep into his pockets." Question: "What might this suggest about Jamal?"',
        fastMethod: "Two behavioural clues — muttering, and hiding his hands — both commonly signal discomfort or dishonesty.",
        steps: [
          "Identify the dialogue's content: a plain denial, “I haven't seen it.”",
          "Notice the manner: muttering (not speaking clearly) and shoving hands into pockets (a defensive gesture).",
          "Combine these clues: both often signal someone is uncomfortable or not telling the full truth.",
          "State the inference, supported by both details.",
        ],
        answer: "Jamal <b>may not be telling the truth</b>, inferred from his muttering and defensive body language.",
      },
      selfCheck: { prompt: "True or false: dialogue delivered “confidently and clearly” usually suggests the same discomfort as dialogue delivered “quietly, avoiding eye contact.”", answer: "<b>False</b> — the manner of delivery matters; confident, clear delivery generally signals the opposite of discomfort or dishonesty." },
      kind: "click-evidence",
      questions: [
        {
          id: "iad-q1",
          instruction: "Click the sentence that suggests the coach was disappointed, without saying so directly.",
          passage: [
            '"Good effort, everyone," the coach said flatly, already turning to gather the cones.',
            "The final score had been three-nil.",
            "Training would resume on Thursday as usual.",
            "Several players sat down to retie their laces.",
          ],
          correctIdx: 0,
          correction: '"said flatly, already turning to gather the cones" suggests the praise was half-hearted and the coach wanted to move on quickly — a sign of disappointment never stated outright.',
          hint: "Look at how the coach's words were delivered, not just what they said.",
        },
        {
          id: "iad-q2",
          instruction: "Click the sentence that suggests Aunt Rosa was excited about the news, without saying so directly.",
          passage: [
            "Aunt Rosa read the letter once, then read it again out loud to the whole kitchen.",
            "The letter had arrived with the second post, just after lunch.",
            "It was addressed in small, neat handwriting.",
            "The kettle had just finished boiling on the stove.",
          ],
          correctIdx: 0,
          correction: '"read it again out loud to the whole kitchen" suggests eagerness to share exciting news — the excitement is shown through her actions, not named directly.',
          hint: "Look for the sentence describing an eager, repeated action rather than a neutral fact about the letter's arrival.",
        },
        {
          id: "iad-q3",
          instruction: "Click the sentence that suggests Dan was trying to avoid a question.",
          passage: [
            '"So, where were you at lunchtime?" his friend asked.',
            '"Around," Dan said, already halfway out of the classroom door.',
            "The bell had rung two minutes earlier.",
            "Most of the class had already left for the canteen.",
          ],
          correctIdx: 1,
          correction: '"already halfway out of the classroom door" while giving a vague one-word answer suggests Dan wants to escape the question rather than answer it properly.',
          hint: "Look at how Dan responds — both the vagueness of his answer and what he's doing while he says it.",
        },
      ],
      mistakes: [
        "Focusing only on the content of dialogue and ignoring the manner it's delivered in, which often carries the real clue.",
        "Inventing a feeling that isn't actually supported by any described action or manner of speech.",
      ],
      examTip: "When a question asks about a character's feelings during a conversation, check the stage directions around the dialogue (how it's said, what the character is doing) as closely as the words themselves.",
      searchTerms: ["inference", "dialogue", "body language", "character feelings", "comprehension"],
    },
    {
      id: "inferring-character-feelings",
      title: "Inferring Character Feelings",
      tier: "Standard",
      objective: "Combine dialogue, action and body-language details across a passage to work out a character's emotional state when it is never named directly.",
      whyMatters: "\"how does X feel\" is one of the most frequent GL and CEM comprehension question types, and the strongest answers combine several details rather than relying on just one.",
      conceptTitle: "Feelings are built from several small details together",
      conceptBullets: [
        'A <b style="color:#C9A24B">feeling</b> can usually be inferred by combining more than one type of detail — dialogue, action, and body language — rather than relying on a single word.',
        'Example: "she gripped the letter until her knuckles whitened" combines a physical grip detail with visible strain, together suggesting anxiety or anger without the feeling ever being named.',
        "Body-language details (clenched fists, held breath, a fixed stare) are especially reliable clues because they're hard to fake or explain away as neutral.",
        "Where dialogue and action point in the same direction (short, sharp words plus a tense gesture), the combined evidence makes the inference much safer than either detail alone.",
      ],
      conceptNote: "<b>Build it up:</b> don't settle for the first clue you find — check whether a second detail (dialogue, action, or body language) points the same way before naming the feeling.",
      glossary: [
        { term: "emotional state", def: "how a character is feeling at a given moment, often unstated directly" },
        { term: "body language", def: "physical behaviour (posture, gesture, facial expression) that reveals feeling" },
        { term: "combined evidence", def: "two or more details that together support the same inference" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: InferringCharacterFeelingsDemo,
      worked: {
        question: 'Passage excerpt: "She gripped the letter until her knuckles whitened, and her voice, when it came, was barely a whisper." Question: "How does the writer show the character was feeling?"',
        fastMethod: "Two details point the same way: a strained grip and a barely-audible voice both suggest suppressed strong emotion, likely anxiety or anger.",
        steps: [
          "Identify the first detail: gripping the letter until her knuckles whitened — a body-language clue for strain or tension.",
          "Identify the second detail: her voice was barely a whisper — a vocal clue that often signals suppressed emotion.",
          "Check the two details point the same way: both suggest strong, controlled emotion rather than calm.",
          "State the inference, citing both combined details as evidence.",
        ],
        answer: "The character appears <b>tense and anxious (or quietly angry)</b>, inferred from both her whitened-knuckle grip and her barely audible voice.",
      },
      selfCheck: { prompt: "True or false: it's always safer to base a feelings inference on two matching details rather than just one.", answer: "<b>True</b> — combined detail from dialogue, action or body language that all point the same way makes an inference much more secure than relying on a single clue." },
      kind: "click-evidence",
      questions: [
        {
          id: "icf-q1",
          instruction: "Click the sentence that best lets you infer how Isaac was feeling before his turn on stage.",
          passage: [
            "Isaac wiped his palms on his trousers for the third time and swallowed hard.",
            "The hall had been decorated with paper stars for the evening.",
            "His name was fourth on the programme.",
            "The audience had been clapping steadily for each act.",
          ],
          correctIdx: 0,
          correction: '"wiped his palms... for the third time and swallowed hard" combines two physical signs of nervousness — repeated and specific enough to safely infer anxiety.',
          hint: "Look for the sentence combining more than one physical sign of nerves, not a neutral fact about the programme or decorations.",
        },
        {
          id: "icf-q2",
          instruction: "Click the sentence that best lets you infer Grace was hurt by what her friend said.",
          passage: [
            '"It\'s fine," Grace said, her voice suddenly flat, and she turned to look out of the window.',
            "The classroom window looked out over the playground.",
            "It was nearly the end of the school day.",
            "Her friend carried on talking about the weekend.",
          ],
          correctIdx: 0,
          correction: 'the flat voice combined with turning away are two matching clues — dismissive words plus withdrawn body language — that together safely suggest hurt feelings.',
          hint: "Look for the sentence combining a change in how something was said with a physical action that suggests withdrawal.",
        },
        {
          id: "icf-q3",
          instruction: "Click the sentence that best lets you infer how Mr Okafor felt on hearing the results.",
          passage: [
            "Mr Okafor's shoulders sagged and he let out a long, slow breath.",
            "The results had come through by email that morning.",
            "The staffroom noticeboard still had last term's timetable pinned to it.",
            "Two colleagues were discussing the weather by the kettle.",
          ],
          correctIdx: 0,
          correction: '"shoulders sagged" combined with "a long, slow breath" are two matching physical details that together safely suggest disappointment or relief-tinged resignation.',
          hint: "Look for the sentence combining two separate physical signs of feeling, not a fact about how or when the results arrived.",
        },
      ],
      mistakes: [
        "Naming a feeling based on only one weak detail when a stronger, second matching detail is available nearby in the passage.",
        "Picking a detail that describes setting or plot rather than the character's own action, dialogue or body language.",
      ],
      examTip: "For \"how does X feel\" questions, look for a second supporting detail near the first one you notice — examiners often reward answers that combine two matching clues over answers based on just one.",
      searchTerms: ["character feelings", "body language", "combined clues", "emotional state", "comprehension"],
    },
    {
      id: "inference-from-descriptive-detail",
      title: "Inferring Atmosphere from Descriptive Detail",
      tier: "Standard",
      objective: "Recognise how a writer builds mood or atmosphere through carefully chosen setting details, without ever stating the mood directly.",
      whyMatters: "atmosphere questions ask what a passage's setting suggests about mood — a skill built entirely on noticing which descriptive details were deliberately chosen to create a feeling.",
      conceptTitle: "Setting details create feeling indirectly",
      conceptBullets: [
        'A writer builds <b style="color:#C9A24B">atmosphere</b> — the overall mood or feeling of a scene — through carefully chosen sensory and setting details, never by simply stating "it was scary" or "it felt peaceful."',
        'Example: "a door creaked and swung slowly shut on its own" builds unease through an unexplained, slightly eerie event, without a single word naming fear.',
        "Look for details involving light and dark, sound (or its absence), temperature, and unexplained movement — these are common atmosphere-building tools.",
        "Neutral background facts (the time, the building's history) don't usually build atmosphere on their own — separate these from the details doing the atmospheric work.",
      ],
      conceptNote: "<b>Test it:</b> ask “does this detail make me feel something, or is it just a plain fact?” — atmosphere clues are the ones that stir a feeling.",
      glossary: [
        { term: "atmosphere", def: "the overall mood or feeling created by a scene's description" },
        { term: "sensory detail", def: "description involving sight, sound, smell, touch or taste" },
        { term: "unexplained detail", def: "a small, unresolved event (a creaking door) that builds tension" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: InferenceFromDescriptiveDetailDemo,
      worked: {
        question: 'Passage excerpt: "The garden was silent except for the slow drip of the broken fountain." Question: "What atmosphere does this sentence create?"',
        fastMethod: "Silence paired with one small, repetitive sound is a classic technique for building an eerie or lonely atmosphere.",
        steps: [
          "Notice the overall silence described — an absence of expected sound.",
          "Notice the single remaining sound: a slow, repetitive drip.",
          "Combine these: near-total silence broken only by one small, repeating noise often signals loneliness or unease.",
          "State the atmosphere and the detail supporting it.",
        ],
        answer: "The sentence creates a <b>lonely, slightly eerie atmosphere</b>, built from the silence and the single repetitive drip.",
      },
      selfCheck: { prompt: "True or false: a sentence stating “it was a peaceful, happy morning” is an example of building atmosphere through description.", answer: "<b>False</b> — that sentence states the mood directly; true atmosphere-building uses indirect sensory or setting detail to suggest a feeling instead of naming it." },
      kind: "click-evidence",
      questions: [
        {
          id: "iad2-q1",
          instruction: "Click the sentence that builds a peaceful, calm atmosphere.",
          passage: [
            "Sunlight spread slowly across the meadow as the last of the mist lifted.",
            "The farmhouse had been built almost a century ago.",
            "A tractor was parked beside the barn.",
            "The nearest village was two miles away.",
          ],
          correctIdx: 0,
          correction: '"sunlight spread slowly... as the last of the mist lifted" uses gentle, slow-moving imagery to build a calm, peaceful mood — the other sentences are neutral background facts.',
          hint: "Look for the sentence built from slow, gentle sensory imagery rather than a plain fact about the farmhouse or its location.",
        },
        {
          id: "iad2-q2",
          instruction: "Click the sentence that builds an uneasy, unsettling atmosphere.",
          passage: [
            "The lighthouse had stood on the headland for over a hundred years.",
            "A single light flickered on somewhere near the top, though no one had climbed the stairs in years.",
            "Ferries ran to the mainland twice a day.",
            "The keeper's cottage had been empty since the 1980s.",
          ],
          correctIdx: 1,
          correction: '"a single light flickered on... though no one had climbed the stairs in years" is an unexplained, faintly eerie detail that builds unease — the rest are plain historical facts.',
          hint: "Look for the detail that describes something happening with no clear explanation, rather than a fact about the lighthouse's history or the ferry schedule.",
        },
        {
          id: "iad2-q3",
          instruction: "Click the sentence that builds a tense, threatening atmosphere.",
          passage: [
            "Dark clouds gathered low over the hill, and the wind dropped to nothing.",
            "The village fete was scheduled for the following weekend.",
            "The bakery on the corner opened at seven each morning.",
            "Several stalls were already being set up in the square.",
          ],
          correctIdx: 0,
          correction: '"dark clouds gathered low... and the wind dropped to nothing" is classic storm-approaching imagery that builds tension and threat — the other sentences are neutral village facts.',
          hint: "Look for the sentence describing changing weather in a way that hints at something ominous approaching.",
        },
      ],
      mistakes: [
        "Picking a neutral factual sentence (dates, distances, schedules) instead of the sentence actually doing the atmospheric work.",
        "Looking only for obviously scary or obviously happy words, and missing subtler atmosphere built through quiet, indirect detail.",
      ],
      examTip: "Atmosphere questions reward you for noticing sensory detail (light, sound, temperature, unexplained movement) — scan for these first before considering plainer factual sentences.",
      searchTerms: ["atmosphere", "mood", "descriptive detail", "setting", "comprehension", "inference"],
    },
    {
      id: "inferring-setting-atmosphere",
      title: "Inferring Setting and Atmosphere",
      tier: "Standard",
      objective: "Use descriptive detail to work out concrete facts about where and when a scene takes place, not just the mood it creates.",
      whyMatters: "GL and CEM papers regularly ask exactly where or when a scene is set, or what season/time of day it is, and the answer is almost never stated directly — only built from indirect detail.",
      conceptTitle: "Where and when, not just how it feels",
      conceptBullets: [
        'Writers often let readers work out the <b style="color:#C9A24B">setting</b> — the time or place of a scene — through indirect clues, rather than stating it outright.',
        'Example: "long shadows stretched across the yard, and the streetlamps flickered on" never says "it was early evening" — but the light and the streetlamps let a reader work that out.',
        "This is a different skill from atmosphere-building (mood): here you're pinning down a concrete fact — a season, a time of day, an era, a type of place — not just a feeling.",
        "Look for clues about light, temperature, sound, and objects that are period- or season-specific (a bonfire, bare trees, a ringing school bell) to work out where or when.",
      ],
      conceptNote: "<b>Ask the right question:</b> for setting questions, ask “what fact about time or place does this detail pin down?” rather than “what feeling does this create?” — the two skills use similar details but answer different questions.",
      glossary: [
        { term: "setting", def: "the time and place in which a scene occurs" },
        { term: "indirect clue", def: "a detail that implies a fact about time or place without stating it" },
        { term: "period detail", def: "an object or detail tied to a particular time of day, season or era" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: InferringSettingAtmosphereDemo,
      worked: {
        question: 'Passage excerpt: "Frost still clung to the car windscreens, and their breath clouded in front of them as they waited for the bus." Question: "What time of year does this suggest?"',
        fastMethod: "Two seasonal clues — frost on windscreens and visible breath — both point specifically to a cold winter (or very early spring) morning.",
        steps: [
          "Identify the first detail: frost on the windscreens — a clue tied to cold weather.",
          "Identify the second detail: breath clouding in front of them — another cold-weather clue.",
          "Combine the two clues: both point specifically to winter, not just \"cold\" in general.",
          "State the setting fact, supported by both details.",
        ],
        answer: "The scene is set on a <b>cold winter morning</b>, inferred from the frost on the windscreens and the characters' visible breath.",
      },
      selfCheck: { prompt: "True or false: a setting-inference question is answered the same way as a mood/atmosphere question, since both use descriptive detail.", answer: "<b>False</b> — both use descriptive detail, but a setting question asks for a concrete fact (time, place, season), while an atmosphere question asks for a feeling the scene creates." },
      kind: "click-evidence",
      questions: [
        {
          id: "isa-q1",
          instruction: "Click the sentence that lets you infer this scene takes place late at night.",
          passage: [
            "The last bus had long since passed, and the street lay silent under a row of dimmed lamps.",
            "A row of shops lined the street on both sides.",
            "The pavement had been resurfaced the previous year.",
            "A bicycle was chained to a railing outside the bakery.",
          ],
          correctIdx: 0,
          correction: '"the last bus had long since passed" combined with the silent, dimmed street are indirect clues that together pin down late night — no time is stated outright.',
          hint: "Look for the sentence combining a transport detail with a description of light and quiet, rather than a plain fact about the shops or pavement.",
        },
        {
          id: "isa-q2",
          instruction: "Click the sentence that lets you infer this scene takes place in autumn.",
          passage: [
            "Dry leaves skittered across the path and gathered in drifts against the fence.",
            "The park had a small pond near its centre.",
            "A noticeboard listed the times for the weekend fun run.",
            "Several benches were dotted along the main path.",
          ],
          correctIdx: 0,
          correction: '"dry leaves skittered... and gathered in drifts" is a seasonal clue specific to autumn — the other sentences are neutral facts about the park\'s layout.',
          hint: "Look for the sentence describing something happening to leaves, which points to a specific time of year.",
        },
        {
          id: "isa-q3",
          instruction: "Click the sentence that lets you infer this scene is set in a busy, old-fashioned market rather than a modern shopping centre.",
          passage: [
            "Stallholders called out their prices over the clatter of crates being stacked on cobblestones.",
            "The town had a population of around twelve thousand.",
            "It was a Saturday morning in early summer.",
            "A church clock could be seen at the far end of the square.",
          ],
          correctIdx: 0,
          correction: '"stallholders called out... crates... cobblestones" together suggest an old-fashioned outdoor market rather than a modern shopping centre — the other sentences are neutral background facts.',
          hint: "Look for the sentence combining sound and surface details specific to an old-fashioned outdoor market.",
        },
      ],
      mistakes: [
        "Confusing a setting question (a concrete fact about time or place) with an atmosphere question (a feeling), and answering with a mood word instead of a specific fact.",
        "Relying on a single vague detail (\"it was dark\") instead of combining two more specific clues to pin down an exact time or season.",
      ],
      examTip: "When a question asks specifically \"where\" or \"when\", look for period- or season-specific objects and sensory detail (frost, streetlamps, church bells, fallen leaves) rather than reaching for a general mood word.",
      searchTerms: ["setting", "time of day", "season", "place", "descriptive detail", "comprehension"],
    },
    {
      id: "inference-vs-over-guessing",
      title: "Safe Inference vs. Over-Guessing",
      tier: "Extension",
      objective: "Distinguish a safe inference, grounded in a specific text detail, from an unsupported guess that goes beyond what the text can reasonably support.",
      whyMatters: "the highest-scoring inference answers are precise and text-supported — vague or invented answers that sound plausible but aren't traceable to the text lose marks even when they're not technically 'wrong'.",
      conceptTitle: "Grounded in the text, not just plausible",
      conceptBullets: [
        'A <b style="color:#C9A24B">safe inference</b> is traceable to one specific detail in the text and doesn\'t claim more than that detail can support.',
        "An over-guess invents extra detail the text never actually gives — for example, inferring a specific reason for a feeling when the text only supports the feeling itself.",
        'Example: "Leo threw both arms in the air" safely supports "Leo felt triumphant" — but claiming "Leo was proud because he\'d trained for two years" invents information the text never gave.',
        "When multiple details are available, choose the one that most directly and specifically supports the conclusion, not a neutral background fact.",
      ],
      conceptNote: "<b>Test it:</b> after making an inference, check whether every part of your answer can be pointed back to the text — any part that can't is over-guessing.",
      glossary: [
        { term: "safe inference", def: "a conclusion fully supported by a specific detail in the text" },
        { term: "over-guessing", def: "adding detail or reasoning the text doesn't actually support" },
        { term: "textual support", def: "the exact detail an inference can be traced back to" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: InferenceVsOverGuessingDemo,
      worked: {
        question: 'Passage excerpt: "Amara stared at the acceptance letter for a long moment before letting out a breath she hadn\'t realised she\'d been holding." Question: "What can you infer about how Amara felt, and what is your evidence?"',
        fastMethod: "The physical detail of held breath being released is a safe, specific signal of relief — don't add a reason the text doesn't give.",
        steps: [
          "Identify the specific physical detail: letting out a held breath.",
          "This detail safely supports relief (and likely happiness) about the letter's contents.",
          "Avoid adding invented detail, e.g. a specific reason why she applied, which the text doesn't mention.",
          "State the safe inference, tied only to the detail actually given.",
        ],
        answer: "Amara felt <b>relieved</b>, inferred from letting out a breath she hadn't realised she was holding — nothing more specific than that should be claimed.",
      },
      selfCheck: { prompt: "True or false: it's safe to infer a character's entire backstory from one small gesture described in a passage.", answer: "<b>False</b> — a single gesture can safely support a general feeling, but inventing a detailed backstory or specific reason the text never mentions is over-guessing." },
      kind: "click-evidence",
      questions: [
        {
          id: "ivo-q1",
          instruction: "Click the one sentence that safely supports the idea that Ben was relieved, without over-guessing his exact reasons.",
          passage: [
            "Ben let his shoulders drop as the results were read out.",
            "The exam had covered three whole terms of work.",
            "Several other students were still waiting for their names to be called.",
            "The hall clock read a quarter past two.",
          ],
          correctIdx: 0,
          correction: '"let his shoulders drop" is a specific physical detail that safely supports relief — the other sentences are neutral background facts, not evidence of feeling.',
          hint: "Look for the one sentence describing a physical reaction, not a neutral fact about the exam or the time.",
        },
        {
          id: "ivo-q2",
          instruction: "Click the one sentence that safely supports the idea that Nadia was surprised, without over-guessing why.",
          passage: [
            "Nadia's mouth fell open and she nearly dropped her cup.",
            "The kitchen table had been set for breakfast as usual.",
            "It was a Tuesday morning in early spring.",
            "The radio was playing quietly in the background.",
          ],
          correctIdx: 0,
          correction: '"her mouth fell open and she nearly dropped her cup" is a specific, physical reaction that safely supports surprise — the rest are neutral setting details, giving no clue to her feeling.',
          hint: "Look for the sentence describing a sudden physical reaction, not a fact about the day or the kitchen setting.",
        },
        {
          id: "ivo-q3",
          instruction: "Click the one sentence that safely supports the idea that the twins were competitive with each other, without over-guessing further detail.",
          passage: [
            "The twins raced each other to be first through the door every single morning.",
            "Their school was a fifteen-minute walk from home.",
            "Both twins were in the same class this year.",
            "The school day started at nine o'clock.",
          ],
          correctIdx: 0,
          correction: '"raced each other to be first through the door every single morning" is a specific, repeated behaviour that safely supports a competitive relationship — the other sentences are neutral scheduling facts.',
          hint: "Look for the sentence describing a repeated behaviour between the twins, not a fact about the school itself.",
        },
      ],
      mistakes: [
        "Choosing a neutral background sentence as \"evidence\" simply because it's the closest one, rather than the sentence that actually supports the feeling.",
        "Adding invented specifics (a reason, a backstory, an exact thought) that go beyond what the chosen detail can actually support.",
      ],
      examTip: "After forming an inference, try to say only what the text detail directly supports — if you find yourself adding “because…” with information from your imagination rather than the passage, trim it back.",
      searchTerms: ["safe inference", "over-guessing", "textual evidence", "comprehension", "supported answer"],
    },
    {
      id: "inferring-writers-attitude",
      title: "Inferring the Writer's Attitude and Tone",
      tier: "Extension",
      objective: "Move beyond inferring what's happening in the story to inferring the writer's own stance or attitude towards a character or event, shown through word choice.",
      whyMatters: "top-tier comprehension questions often ask what a writer thinks or feels about their subject, not just what a character feels — this viewpoint skill is what separates the highest-scoring answers at Extension level.",
      conceptTitle: "The writer has a viewpoint too, hidden in the wording",
      conceptBullets: [
        'A writer\'s <b style="color:#C9A24B">attitude</b> — their own approval, disapproval, admiration or mockery of a character or event — is shown through deliberate word choice, not stated as an opinion.',
        'Example: putting a word in quotation marks, like a councillor who "graciously" allowed a photo, signals sarcasm — the writer is hinting the man was actually self-important, not gracious.',
        "Loaded adjectives and verbs (a character who 'boasted' rather than 'said', a plan that was 'so-called' rather than named plainly) reveal the writer's stance without ever stating it directly.",
        "This is a step beyond inferring a character's feelings: here the question is what the writer thinks about the character or event, which can be quite different from what the character feels about themselves.",
      ],
      conceptNote: "<b>Separate the layers:</b> first ask what the character feels, then separately ask what the writer seems to think of them — the two answers aren't always the same.",
      glossary: [
        { term: "writer's attitude", def: "the author's own stance (approval, disapproval, mockery) towards a character or event" },
        { term: "loaded word", def: "a word chosen deliberately to carry a positive or negative judgement" },
        { term: "sarcasm/irony", def: "saying or implying the opposite of what is meant, often through quotation marks or exaggeration" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: InferringWritersAttitudeDemo,
      worked: {
        question: 'Passage excerpt: "The manager \'generously\' agreed to let staff take their full lunch break, just this once." Question: "What does this suggest about the writer\'s attitude towards the manager?"',
        fastMethod: "The quotation marks around \"generously\" combined with \"just this once\" are the writer's own loaded wording, signalling criticism rather than genuine praise.",
        steps: [
          "Notice the word in quotation marks: “generously” — this is unusual, since generosity doesn't normally need quotation marks.",
          "Notice the added phrase “just this once”, which undercuts any real generosity.",
          "Combine these: the writer is being sarcastic, suggesting the manager's gesture was grudging, not generous.",
          "State the writer's attitude, citing the loaded wording as evidence.",
        ],
        answer: "The writer seems <b>critical of the manager</b>, using the sarcastic quotation marks around “generously” and the phrase “just this once” to suggest the gesture was grudging rather than kind.",
      },
      selfCheck: { prompt: "True or false: a writer's attitude towards a character is always the same as that character's own feelings about themselves.", answer: "<b>False</b> — a writer can show disapproval of a character (through loaded word choice) even while that character feels proud or pleased with themselves." },
      kind: "click-evidence",
      questions: [
        {
          id: "iwa-q1",
          instruction: "Click the phrase that reveals the writer's mocking attitude towards the announcement, rather than a neutral report of it.",
          passage: [
            'The company\'s "revolutionary" new packaging turned out to be the same box in a slightly different shade of green.',
            "The announcement was made at a press event on Thursday.",
            "Several journalists attended the event.",
            "The company had launched three other products that year.",
          ],
          correctIdx: 0,
          correction: 'putting "revolutionary" in quotation marks, followed by the deflating detail about the box being "the same... in a slightly different shade", is the writer\'s own sarcastic wording, mocking the company\'s claim.',
          hint: "Look for the sentence with a grand-sounding word in quotation marks that is then undercut by what actually happened.",
        },
        {
          id: "iwa-q2",
          instruction: "Click the phrase that reveals the writer admires the volunteer's actions, rather than simply reporting them.",
          passage: [
            "Without a moment's hesitation, she waded into the flooded lane to help the stranded family.",
            "The flooding had been caused by two days of heavy rain.",
            "Local news crews arrived shortly afterwards.",
            "The family were later given emergency accommodation.",
          ],
          correctIdx: 0,
          correction: '"without a moment\'s hesitation" is a loaded phrase choosing to highlight instant courage, revealing the writer\'s admiration rather than simply stating that she helped.',
          hint: "Look for the phrase emphasising how quickly or bravely something was done, rather than a neutral fact about the flooding or the aftermath.",
        },
        {
          id: "iwa-q3",
          instruction: "Click the phrase that reveals the writer's disapproving attitude towards the politician's speech.",
          passage: [
            'The politician "promised", not for the first time, to fix the town\'s roads within the year.',
            "The roads had been in poor condition since the previous winter.",
            "The speech was given outside the town hall.",
            "A small crowd had gathered to listen.",
          ],
          correctIdx: 0,
          correction: 'putting "promised" in quotation marks and adding "not for the first time" are the writer\'s own loaded choices, signalling scepticism about whether the promise will be kept.',
          hint: "Look for the sentence where a normally sincere word is placed in quotation marks and paired with a reminder that this has happened before.",
        },
      ],
      mistakes: [
        "Answering with what a character feels instead of what the writer seems to think about that character or event.",
        "Missing quotation marks around an ordinary-looking word, which is often the single clearest signal of the writer's sarcasm.",
      ],
      examTip: "When a question asks about the writer's \"tone\" or \"attitude\" (rather than a character's feelings), scan for quotation marks around ordinary words and for loaded adjectives or verbs — these are the writer's own fingerprints on the text.",
      searchTerms: ["writer's attitude", "tone", "viewpoint", "sarcasm", "word choice", "comprehension"],
    },
    {
      id: "combining-multiple-clues",
      title: "Combining Multiple Clues Across a Passage",
      tier: "Extension",
      objective: "Piece together two or three separate details from different points in a passage into one fully supported inference, rather than relying on a single sentence.",
      whyMatters: "the hardest-marked inference questions are deliberately built so that no single sentence gives the whole answer — students who stop at the first clue they find lose marks that fuller answers would gain.",
      conceptTitle: "The strongest answer often needs more than one clue",
      conceptBullets: [
        'Some inference questions require <b style="color:#C9A24B">combining clues</b> — two or three separate details scattered across a passage — into a single supported conclusion, rather than pointing to just one sentence.',
        "A common exam trap is a question that looks answerable from one obvious clue, but actually rewards noticing a second, quieter clue elsewhere in the passage that strengthens or changes the answer.",
        'Example: crossing out a date on a calendar the moment an appointment is booked, and rehearsing a conversation "a dozen times" later on, are two separate clues that together support sustained dread — either alone would only suggest a passing nerve.',
        "The safest technique is to jot down every small clue you notice while reading, then check at the end whether they combine into one stronger inference rather than settling for the first one found.",
      ],
      conceptNote: "<b>Technique:</b> note each small clue as you meet it, then ask \"do any of these combine?\" before answering — relying on just one clue when a question needs several is the single most common way marks are lost at this level.",
      glossary: [
        { term: "combining clues", def: "using two or more separate details from different parts of a passage to support one inference" },
        { term: "scattered evidence", def: "clues placed at different points in a passage rather than together in one sentence" },
        { term: "sustained inference", def: "a conclusion (like ongoing dread, not just a moment's nerves) that needs more than one supporting detail" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: CombiningMultipleCluesDemo,
      worked: {
        question: 'Passage excerpt: "Marcus had checked the train times four separate times that week. He packed his bag the night before, then unpacked and repacked it twice more the next morning." Question: "What can you infer about how Marcus felt about the journey, using more than one clue?"',
        fastMethod: "Two separate repeated-checking clues — train times checked four times, and the bag packed and repacked twice — together build a picture of sustained anxiety, stronger than either clue alone.",
        steps: [
          "Identify the first clue: checking the train times four separate times — repeated checking suggests worry.",
          "Identify the second clue, later in the passage: packing and repacking the bag — another repeated, anxious behaviour.",
          "Combine the two: both are separate examples of repeated, anxious checking behaviour, which together support sustained (not just momentary) anxiety.",
          "State the inference, citing both clues together as the fuller evidence.",
        ],
        answer: "Marcus appears to have been <b>anxious about the journey for some time</b>, inferred from both the repeated train-time checks and the repacking of his bag — either clue alone would suggest less than the two combined.",
      },
      selfCheck: { prompt: "True or false: if a question asks you to explain a character's feeling \"fully\", it's usually safe to stop at the first supporting clue you find in the passage.", answer: "<b>False</b> — \"fully\" is often a signal that the question rewards combining two or more clues from different points in the passage, not stopping at the first one found." },
      kind: "click-evidence",
      questions: [
        {
          id: "cmc-q1",
          instruction: "This passage has two separate clues supporting the idea that Anya was determined to succeed. Click the second of the two clues (the one appearing later in the passage).",
          passage: [
            "Anya had rewritten her opening paragraph six times before she was satisfied with it.",
            "The competition deadline was the following Friday.",
            "She stayed behind after everyone else had left the library, still checking her work line by line.",
            "The librarian eventually had to ask her to pack up for the night.",
          ],
          correctIdx: 2,
          correction: 'combined with "rewritten her opening paragraph six times" earlier in the passage, "stayed behind... still checking her work line by line" is the second clue — together they support sustained determination, not just one moment of effort.',
          hint: "One clue on its own only shows a single moment of effort — look for the second detail, later on, that combines with it to show sustained determination.",
        },
        {
          id: "cmc-q2",
          instruction: "This passage has two separate clues supporting the idea that Mr Douglas had been worried about the farm for a long time. Click the second of the two clues (the one appearing later in the passage).",
          passage: [
            "Mr Douglas had stopped mentioning the harvest figures at dinner weeks ago.",
            "The farm had been in his family for three generations.",
            "He now spent long evenings alone in the barn, going over the accounts by lamplight.",
            "The nearest market town was some six miles away.",
          ],
          correctIdx: 2,
          correction: 'combined with "stopped mentioning the harvest figures... weeks ago" earlier in the passage, "long evenings alone in the barn, going over the accounts" is the second clue — together they support ongoing, private worry rather than a single bad day.',
          hint: "One detail alone only hints at a change in conversation — look for the second detail, later on, describing a repeated private habit that confirms sustained worry.",
        },
        {
          id: "cmc-q3",
          instruction: "This passage has two separate clues supporting the idea that the twins had planned the surprise carefully in advance. Click the second of the two clues (the one appearing later in the passage).",
          passage: [
            "The twins had been whispering in the hallway for most of the previous week.",
            "Their grandmother's birthday fell on a Sunday that year.",
            "A carefully wrapped parcel, hidden weeks earlier, had somehow stayed undiscovered under the stairs.",
            "The family usually gathered for a big lunch on birthdays.",
          ],
          correctIdx: 2,
          correction: 'combined with the "whispering in the hallway for most of the previous week" earlier in the passage, "a carefully wrapped parcel, hidden weeks earlier" is the second clue — together they support careful, sustained planning rather than a last-minute idea.',
          hint: "One clue alone only shows secretive behaviour — look for the second detail, later on, showing physical evidence of planning done well in advance.",
        },
      ],
      mistakes: [
        "Stopping at the first supporting clue found and writing an answer that a fuller, two-clue answer would score higher marks than.",
        "Combining two clues that don't actually point the same way, forcing a connection between details that aren't really related.",
      ],
      examTip: "Words like \"fully\", \"in detail\", or a high mark allocation (2-3 marks) next to an inference question are strong signals that the mark scheme expects two or more combined clues, not just one.",
      searchTerms: ["combining clues", "multiple evidence", "scattered detail", "sustained inference", "comprehension"],
    },
  ],
};
