import type { TopicContent } from "../types";
import {
  RetrievalDefinitionDemo,
  FindAndCopyDemo,
  MultipleChoiceRetrievalDemo,
  SkimmingScanningDemo,
  AnnotationTechniqueDemo,
  PEEMethodDemo,
  NumbersDatesNamesDemo,
  MultiPartRetrievalDemo,
  NonFictionFactsDemo,
  SpottingDistractorsDemo,
} from "../notes-diagrams/literal-comprehension-demos";

export const literalComprehensionRetrievalTopic: TopicContent = {
  slug: "literal-comprehension-retrieval",
  subject: "English",
  subjectSlug: "english",
  title: "Comprehension: Literal Retrieval",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "Every GL, CEM and CSSE comprehension paper opens with questions whose answers are written directly in the text — no guessing, no reading between the lines, just careful hunting. This module trains the core retrieval skill from the ground up: how to find the exact sentence that answers a question, copy or explain it precisely, and avoid the tempting decoy sentences examiners plant along the way.",
  subtopics: [
    {
      id: "what-is-literal-comprehension",
      title: "What Is Literal Comprehension?",
      tier: "Foundation",
      objective: "Understand what a literal comprehension question is, and how it differs from an inference question.",
      whyMatters: "every comprehension paper starts with literal questions — they're worth easy, guaranteed marks if you know exactly what the examiner wants: words that are already sitting in the text.",
      conceptTitle: "The answer is already on the page",
      conceptBullets: [
        'A <b style="color:#C9A24B">literal question</b> asks about something the text states directly — a fact, a name, an action, a detail.',
        "You never need to guess, work anything out, or read between the lines — the exact answer is written somewhere in the passage.",
        "This is different from an <b>inference question</b>, which asks what a character or writer <i>suggests</i> without saying it outright.",
        'Test: if you can point at one sentence and say "there, that\'s the answer," it\'s literal.',
      ],
      conceptNote: "<b>Golden rule:</b> for a literal question, your job is to find, not to think — the words you need are already there.",
      glossary: [
        { term: "literal comprehension", def: "understanding what a text directly states" },
        { term: "inference", def: "working out something the text only suggests" },
        { term: "retrieval", def: "the skill of locating a stated fact in a text" },
        { term: "evidence", def: "the exact words in the text that support an answer" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: RetrievalDefinitionDemo,
      worked: {
        question: 'Passage excerpt: "Ben tied his laces twice, checked his watch, and sprinted the last stretch to the school gates just as the bell stopped ringing." Question: "How did Ben get to the school gates?"',
        fastMethod: "Scan for a verb of movement — the passage names the action directly, so simply lift it.",
        steps: [
          "Read the question carefully: it asks how Ben moved, not why he was late.",
          "Scan the sentence for a verb describing movement.",
          '"Sprinted" is the exact word the text uses — no working-out needed.',
          "The answer is stated directly, so this is a literal question.",
        ],
        answer: 'Ben <b>sprinted</b> the last stretch to the school gates.',
      },
      selfCheck: { prompt: "True or false: a literal question can be answered by pointing at one exact sentence in the text.", answer: "<b>True</b> — that's the defining feature of a literal question; the answer is stated, not implied." },
      kind: "click-evidence",
      questions: [
        {
          id: "lit-def-q1",
          instruction: "Click the sentence that tells you where Sam hid the key.",
          passage: [
            "Sam checked over his shoulder before slipping through the garden gate.",
            "He pushed the loose brick aside and dropped the key into the gap behind it.",
            "His heart was still racing from the run across the field.",
            "Nobody had seen him, or so he hoped.",
          ],
          correctIdx: 1,
          correction: 'the exact hiding place is stated: "dropped the key into the gap behind it" — this is a literal fact, directly written in the text.',
          hint: "Find the sentence that names an exact place, not just Sam's feelings.",
        },
        {
          id: "lit-def-q2",
          instruction: "Click the sentence that tells you what the weather was like.",
          passage: [
            "The coach pulled away from the school car park at exactly nine o'clock.",
            "Thick fog pressed against the windows, hiding the fields outside.",
            "Inside, the children chattered excitedly about the trip ahead.",
            "Miss Patel counted heads for the third time that morning.",
          ],
          correctIdx: 1,
          correction: 'the weather is described directly: "thick fog pressed against the windows" — a literal detail stated outright, not something you need to infer.',
          hint: "Look for the sentence describing conditions outside the coach.",
        },
        {
          id: "lit-def-q3",
          instruction: "Click the sentence that tells you what Ellie was carrying.",
          passage: [
            "Ellie hurried down the corridor, late for assembly again.",
            "She clutched a stack of library books against her chest.",
            "Mr Owusu held the door open and gave her a small smile.",
            "The hall was already full of quiet, waiting students.",
          ],
          correctIdx: 1,
          correction: 'the object is named directly: "clutched a stack of library books" — the answer is written into the text, not implied by her actions.',
          hint: "Find the sentence naming an object, not just Ellie's speed or lateness.",
        },
      ],
      mistakes: [
        "Answering with an assumption or a guess instead of quoting or pointing to what the text actually says.",
        "Confusing a literal question with an inference question and explaining a character's feelings when the question only asked for a stated fact.",
      ],
      examTip: "If a question starts with 'what', 'who', 'where' or 'when' and asks about something concrete, it is very likely literal — go hunting for the exact words.",
      searchTerms: ["literal comprehension", "retrieval", "inference", "reading comprehension", "find the answer", "11+ english"],
    },
    {
      id: "find-and-copy-vs-explain",
      title: "‘Find and Copy’ vs. ‘Find and Explain’",
      tier: "Foundation",
      objective: "Recognise the difference between a question that wants exact words copied out and one that wants the idea explained in your own words.",
      whyMatters: "using your own words when a question demands an exact quotation (or vice versa) is one of the most common ways students lose easy marks on retrieval questions.",
      conceptTitle: "Copy exactly, or explain in your own words?",
      conceptBullets: [
        '<b style="color:#C9A24B">"Find and copy"</b> questions want the exact words from the text — lifted precisely, with correct spelling and punctuation.',
        '<b>"Find and explain"</b> (or "in your own words") questions want the idea restated using different vocabulary, showing you understood it.',
        "Look closely at the instruction wording — phrases like 'quote', 'copy', or 'write down the exact words' mean lift it directly.",
        "Phrases like 'in your own words' or 'explain' mean you must not just copy — paraphrase the idea instead.",
      ],
      conceptNote: "<b>Common trap:</b> copying word-for-word when the question says 'in your own words' usually loses the mark, even if the copied section is correct.",
      glossary: [
        { term: "find and copy", def: "lift the exact words from the text" },
        { term: "find and explain", def: "restate the idea in your own words" },
        { term: "quotation", def: "text copied word-for-word from the passage" },
        { term: "paraphrase", def: "the same idea expressed in different words" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: FindAndCopyDemo,
      worked: {
        question: 'Passage: "The old lighthouse keeper had grown weary of the endless grey sea and the howling wind that never seemed to stop." Question: "Find and copy one word that shows the keeper was tired of his life."',
        fastMethod: "This says 'find and copy', so lift the exact word — do not rephrase it.",
        steps: [
          "The instruction says 'find and copy', which means the exact original word is required.",
          "Scan for a word describing tiredness or being fed up.",
          '"Weary" is the precise word used in the text.',
          "Copy it exactly: weary — not a synonym like 'tired' or 'exhausted'.",
        ],
        answer: 'The word is <b>weary</b>.',
      },
      selfCheck: { prompt: "If a question says 'explain in your own words why the boy was upset', is it safe to just copy a sentence from the text?", answer: "<b>No</b> — copying instead of paraphrasing usually loses the mark, even if the copied sentence is the right evidence." },
      kind: "click-evidence",
      questions: [
        {
          id: "copy-explain-q1",
          instruction: "Find and copy: click the exact sentence that names what frightened the horse.",
          passage: [
            "The horse had been calm all morning, grazing quietly in the paddock.",
            "A sudden clap of thunder sent it bolting towards the far fence.",
            "Farmer Grey ran after it, calling its name.",
            "By the time he caught up, the horse had calmed down again.",
          ],
          correctIdx: 1,
          correction: 'the exact cause is written in the text: "a sudden clap of thunder" — for a "find and copy" question, this phrase should be lifted word for word.',
          hint: "Find and copy the exact sentence naming the loud noise, rather than describing the horse's reaction.",
        },
        {
          id: "copy-explain-q2",
          instruction: "In your own words: click the sentence you would use as the basis to explain why the shop was closing early.",
          passage: [
            "Mrs Kowalski flipped the sign on the door to 'Closed' an hour earlier than usual.",
            "A burst pipe had flooded the stockroom overnight.",
            "Customers peered through the window, disappointed.",
            "She promised to reopen as soon as the mess was cleared.",
          ],
          correctIdx: 1,
          correction: 'the underlying reason is here — "a burst pipe had flooded the stockroom" — for "in your own words" you would rephrase this, e.g. "there had been a flood inside the shop."',
          hint: "Find the sentence stating the reason, which you would then rephrase rather than quote directly.",
        },
        {
          id: "copy-explain-q3",
          instruction: "Find and copy: click the exact sentence naming what Aisha won at the fair.",
          passage: [
            "Aisha lined up three shots in a row at the coconut shy.",
            "The stallholder cheered and handed her a giant stuffed elephant.",
            "She could barely carry it back to her friends.",
            "They all laughed at how ridiculous it looked next to her.",
          ],
          correctIdx: 1,
          correction: 'the prize is named exactly: "a giant stuffed elephant" — this should be copied precisely, not paraphrased, since the question asks you to find and copy.',
          hint: "Look for the sentence naming the exact prize, ready to copy word for word.",
        },
      ],
      mistakes: [
        "Paraphrasing when the question explicitly says 'copy' or 'quote' — exact wording is required, including correct spelling.",
        "Copying a whole sentence when only one or two words were asked for, which can lose marks for imprecision.",
      ],
      examTip: "Underline the instruction word itself ('copy' or 'explain') before you even look at the passage — it tells you exactly how to phrase your answer.",
      searchTerms: ["find and copy", "own words", "paraphrase", "quotation", "exact words", "retrieval"],
    },
    {
      id: "multiple-choice-vs-short-written",
      title: "Multiple-Choice vs. Short-Written Retrieval",
      tier: "Standard",
      objective: "Understand the different demands of GL-style multiple-choice retrieval and CEM/CSSE-style short-written retrieval.",
      whyMatters: "GL and CEM/CSSE papers test the same skill in different formats — knowing which one you're facing changes how carefully you need to write your answer.",
      conceptTitle: "Same skill, two different formats",
      conceptBullets: [
        '<b style="color:#C9A24B">GL-style papers</b> usually give multiple-choice retrieval questions — you match the text to one of four or five given options.',
        '<b>CEM and CSSE-style papers</b> more often use short-written retrieval — you write the answer yourself, sometimes as a single word or a full sentence.',
        "With multiple-choice, wrong options are often close paraphrases or half-true statements designed to catch a careless reader.",
        "With short-written retrieval, precision matters more — you must choose your own words carefully rather than simply recognising the right one.",
      ],
      conceptNote: "<b>Strategy:</b> for multiple-choice, find your own answer in the text first, then match it to the closest option — don't just read the options and guess.",
      glossary: [
        { term: "multiple-choice retrieval", def: "selecting the correct answer from given options" },
        { term: "short-written retrieval", def: "writing the answer yourself, unaided by options" },
        { term: "distractor option", def: "a wrong multiple-choice answer designed to look plausible" },
        { term: "GL/CEM/CSSE", def: "the main 11+ exam board styles used across the UK" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: MultipleChoiceRetrievalDemo,
      worked: {
        question: 'Passage: "Only fourteen of the original thirty-two competitors reached the final round." Multiple-choice question: "How many competitors reached the final round? A) 32 B) 14 C) 18 D) 46"',
        fastMethod: "Find your own answer in the text before glancing at the options, so the wrong ones can't mislead you.",
        steps: [
          "Read the passage and identify the number relating to the final round, ignoring the original total for now.",
          'The text says "fourteen of the original thirty-two competitors reached the final round."',
          "Fourteen is the number who reached the final; thirty-two is a distractor referring to the starting number.",
          "Match your own answer, 14, to option B.",
        ],
        answer: 'The answer is <b>B) 14</b>.',
      },
      selfCheck: { prompt: "In multiple-choice retrieval, should you read the options before or after finding your own answer in the text?", answer: "<b>After</b> — find your own answer first, so you aren't tempted by a plausible-looking wrong option." },
      kind: "click-evidence",
      questions: [
        {
          id: "mc-written-q1",
          instruction: "Click the sentence that gives the exact number of pages in Noah's notebook.",
          passage: [
            "Noah had filled his notebook with sketches of every bird he'd seen that year.",
            "It contained ninety-six pages, and he had used every single one.",
            "His favourite drawing was of a kingfisher, caught mid-dive.",
            "He planned to start a second notebook the following week.",
          ],
          correctIdx: 1,
          correction: 'the exact figure is stated in the second sentence: "ninety-six pages" — whether the question format is multiple-choice or short-written, this is the precise fact to retrieve.',
          hint: "Find the sentence stating the number of pages, not the subject of the sketches.",
        },
        {
          id: "mc-written-q2",
          instruction: "Click the sentence that tells you exactly how far the hikers walked.",
          passage: [
            "The group set off from the car park just after sunrise.",
            "By early afternoon, tired legs were slowing everyone down.",
            "In total they covered eighteen kilometres of steep, winding trail.",
            "They reached the summit café just before it closed.",
          ],
          correctIdx: 2,
          correction: 'the precise distance is given: "eighteen kilometres" — a short-written answer would state this figure exactly; a multiple-choice answer would match it to the closest option.',
          hint: "Scan for the sentence containing a specific distance in kilometres.",
        },
        {
          id: "mc-written-q3",
          instruction: "Click the sentence that tells you which prize Zara actually won.",
          passage: [
            "Zara had entered the poetry competition hoping for third place at best.",
            "Judges praised her use of imagery during the ceremony.",
            "To her astonishment, she was announced as the overall winner.",
            "Her older brother had come second the previous year.",
          ],
          correctIdx: 2,
          correction: 'the actual result is stated clearly: "announced as the overall winner" — the mention of hoping for third place is a distractor that a multiple-choice option might exploit.',
          hint: "Find the sentence that states the actual result, not what Zara was hoping for beforehand.",
        },
      ],
      mistakes: [
        "In multiple-choice questions, picking an option that 'sounds right' without checking it against the actual text.",
        "In short-written retrieval, writing a vague or general answer instead of the precise fact the question asked for.",
      ],
      examTip: "For multiple-choice papers, cover the options with your hand, answer the question in your head first, then reveal the options and match.",
      searchTerms: ["multiple choice", "short written", "GL", "CEM", "CSSE", "retrieval", "distractor"],
    },
    {
      id: "skimming-vs-scanning",
      title: "Skimming vs. Scanning",
      tier: "Standard",
      objective: "Understand the difference between skimming for overall meaning and scanning for a specific detail, and know when to use each.",
      whyMatters: "using the wrong reading technique wastes precious minutes on a timed paper — scanning when you should skim, or skimming when you need a precise fact, both cost marks.",
      conceptTitle: "Two different reading speeds for two different jobs",
      conceptBullets: [
        '<b style="color:#C9A24B">Skimming</b> means reading quickly to get the general gist of a passage — its topic, structure and overall feel.',
        '<b>Scanning</b> means running your eyes down the text hunting for one specific piece of information — a name, number or word.',
        "Skim first, right at the start, to understand what the passage is broadly about before you read any questions closely.",
        "Then scan for each individual retrieval question, using keywords from the question to guide your eyes.",
      ],
      conceptNote: "<b>Timing tip:</b> a 30-second skim at the start often saves minutes later, because you already know roughly where different topics sit in the passage.",
      glossary: [
        { term: "skimming", def: "reading quickly for general gist or overview" },
        { term: "scanning", def: "searching quickly for one specific detail" },
        { term: "keyword", def: "a word from the question used to guide scanning" },
        { term: "gist", def: "the overall sense or main idea of a text" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: SkimmingScanningDemo,
      worked: {
        question: 'Passage: a five-paragraph article about volcanoes, covering their formation, famous eruptions, warning signs, evacuation procedures, and modern monitoring technology. Question: "In which paragraph is the reader told how scientists currently detect an eruption before it happens?"',
        fastMethod: "Skim the paragraph topics first, then scan only the monitoring paragraph for the specific detail.",
        steps: [
          "Skim each paragraph's opening sentence to identify its general topic.",
          "The final paragraph's opening mentions modern technology — likely the monitoring paragraph.",
          "Scan that paragraph specifically for words like 'detect', 'sensors' or 'warning'.",
          "Locate the exact sentence describing detection methods within that paragraph.",
        ],
        answer: "The answer is found by <b>skimming to locate the right paragraph, then scanning within it</b>.",
      },
      selfCheck: { prompt: "Which technique should you use first when you open a new comprehension passage: skimming or scanning?", answer: "<b>Skimming</b> — get the overall gist first, then scan for individual details once you know the questions." },
      kind: "click-evidence",
      questions: [
        {
          id: "skim-scan-q1",
          instruction: "Scan for the answer: click the sentence that tells you the exact opening time of the swimming pool.",
          passage: [
            "The new leisure centre has quickly become popular with local families.",
            "Its main pool opens at 6.30 a.m. on weekdays for early swimmers.",
            "There is also a smaller pool designed for young children.",
            "Membership prices vary depending on age and how often you plan to visit.",
          ],
          correctIdx: 1,
          correction: 'scanning for a time detail leads straight to "opens at 6.30 a.m. on weekdays" — you don\'t need to read every sentence carefully, just hunt for the number.',
          hint: "Scan specifically for a clock time rather than reading the whole passage in order.",
        },
        {
          id: "skim-scan-q2",
          instruction: "Skim first to find the general topic, then click the sentence that names the author of the mural.",
          passage: [
            "A huge new mural now covers the side wall of the community centre.",
            "It shows scenes from the town's fishing history, painted in bright blues and golds.",
            "Local artist Farah Osei spent three weeks completing the work.",
            "Residents have already started calling it the best addition to the high street in years.",
          ],
          correctIdx: 2,
          correction: 'once you know the passage is generally about a mural, scanning quickly finds the name: "local artist Farah Osei" in the third sentence.',
          hint: "After skimming to confirm the topic is the mural, scan for a proper noun — a person's name.",
        },
        {
          id: "skim-scan-q3",
          instruction: "Scan for the answer: click the sentence that tells you how many students attended the science fair.",
          passage: [
            "The school hall buzzed with excitement on the morning of the science fair.",
            "Stalls lined every wall, each with a different experiment on show.",
            "Over four hundred students from three different schools attended.",
            "Prizes were awarded for the most original project at the end of the day.",
          ],
          correctIdx: 2,
          correction: 'scanning for a number quickly locates "over four hundred students" — this is the precise detail the question asks for.',
          hint: "Scan for a number rather than reading about the stalls or the prizes.",
        },
      ],
      mistakes: [
        "Reading every word of a long passage carefully before even looking at the questions, which wastes valuable time.",
        "Scanning too narrowly for one exact keyword and missing a synonym the text actually used instead.",
      ],
      examTip: "Turn the question into a keyword or two before you scan — for 'how many students', scan for numbers, not the word 'students' itself.",
      searchTerms: ["skimming", "scanning", "reading technique", "gist", "keyword", "timed reading"],
    },
    {
      id: "annotation-technique",
      title: "Annotation Technique",
      tier: "Standard",
      objective: "Use underlining, circling and ticking to mark evidence in a passage as you read, making retrieval questions faster to answer.",
      whyMatters: "annotating as you read means you don't have to reread the whole passage for every question — the evidence is already marked and ready to use.",
      conceptTitle: "Mark the text as you go",
      conceptBullets: [
        '<b style="color:#C9A24B">Underlining</b> is best for marking a phrase or sentence that answers a specific question.',
        "<b>Circling</b> works well for single important words — names, numbers, dates or key vocabulary.",
        "<b>Ticking</b> in the margin flags a whole section as relevant, so you can find it again quickly without rereading everything.",
        "Annotate on your first read-through, not just when you reach a question — some details answer questions you haven't seen yet.",
      ],
      conceptNote: "<b>Habit to build:</b> every time you read a name, date, number or strong description, give it a quick circle — future-you will thank present-you.",
      glossary: [
        { term: "annotation", def: "marking a text while reading to highlight key information" },
        { term: "underlining", def: "marking a phrase or sentence with a line beneath it" },
        { term: "margin note", def: "a brief note written beside the text" },
        { term: "key detail", def: "a fact likely to be asked about later" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: AnnotationTechniqueDemo,
      worked: {
        question: 'Passage: "The expedition set out from Base Camp at dawn on 3 June, led by the experienced climber Nadia Voss." Question: "Who led the expedition?"',
        fastMethod: "If you'd already circled the proper noun on your first read, you could answer instantly without rereading.",
        steps: [
          "On a first read, a proper noun like a person's name should be circled immediately.",
          '"Nadia Voss" is the name circled as a likely-important detail.',
          "When the question asks who led the expedition, the circled name is already marked and easy to find.",
          "No rereading of the whole sentence is needed — just glance at your annotation.",
        ],
        answer: "The expedition was led by <b>Nadia Voss</b>.",
      },
      selfCheck: { prompt: "Should you annotate a text only after reading the questions, or while reading the passage the first time?", answer: "<b>While reading the passage the first time</b> — marking names, numbers and key details early saves time later." },
      kind: "click-evidence",
      questions: [
        {
          id: "annotate-q1",
          instruction: "Click the sentence you would underline to answer: 'What did the coach say to the team at half-time?'",
          passage: [
            "The players trudged off the pitch, heads down, trailing by two goals.",
            "In the changing room, the coach told them simply to trust their training.",
            "Nobody spoke as they towelled off and drank some water.",
            "Ten minutes later they walked back out, ready to fight for a comeback.",
          ],
          correctIdx: 1,
          correction: 'the exact words are reported in the sentence "the coach told them simply to trust their training" — this is what you would underline as your evidence.',
          hint: "Find the sentence reporting what the coach actually said, not the players' reaction.",
        },
        {
          id: "annotate-q2",
          instruction: "Click the sentence you would circle a number in to answer: 'How many volunteers helped clean the beach?'",
          passage: [
            "Grey clouds threatened rain over the seafront that Saturday morning.",
            "Despite the weather, thirty-five volunteers turned up with bags and gloves.",
            "They worked for three hours, filling bag after bag with litter.",
            "By lunchtime, the beach looked cleaner than it had in years.",
          ],
          correctIdx: 1,
          correction: 'the number to circle is in the second sentence: "thirty-five volunteers" — annotating this on first read makes the question instant to answer.',
          hint: "Look for the sentence containing an exact number of people.",
        },
        {
          id: "annotate-q3",
          instruction: "Click the sentence you would tick as the key evidence for: 'Why did the concert start late?'",
          passage: [
            "Fans had queued outside the venue since early afternoon.",
            "A technical fault with the main speakers delayed the sound check.",
            "Engineers worked frantically backstage to fix the problem.",
            "The band finally walked on stage forty minutes behind schedule.",
          ],
          correctIdx: 1,
          correction: 'the reason for the delay is stated here: "a technical fault with the main speakers delayed the sound check" — this is the sentence worth ticking as key evidence.',
          hint: "Find the sentence explaining the cause of the delay, not its length.",
        },
      ],
      mistakes: [
        "Annotating too much, underlining nearly every sentence, which defeats the purpose of highlighting what's actually important.",
        "Waiting until after reading all the questions to annotate, meaning the passage has to be reread from scratch.",
      ],
      examTip: "Develop a simple, consistent code — circle names and numbers, underline key actions — and stick to it on every paper so it becomes automatic.",
      searchTerms: ["annotation", "underlining", "circling", "margin notes", "active reading", "evidence marking"],
    },
    {
      id: "pee-method",
      title: "The PEE Method",
      tier: "Standard",
      objective: "Structure a written retrieval answer using Point, Evidence, Explain to give a complete, well-supported response.",
      whyMatters: "on CEM and CSSE-style papers, a bare fact without evidence or explanation often loses marks — PEE guarantees a complete answer every time.",
      conceptTitle: "Point, Evidence, Explain",
      conceptBullets: [
        '<b style="color:#C9A24B">Point</b>: state your answer clearly in one sentence, directly answering the question.',
        "<b>Evidence</b>: back it up with a short quotation or specific detail lifted from the text.",
        "<b>Explain</b>: briefly say how the evidence proves your point, linking it back to the question.",
        "Even for a short retrieval answer, a quick PEE structure shows the examiner exactly why your answer is correct.",
      ],
      conceptNote: "<b>Quick version:</b> for one-mark questions, Point and Evidence alone are often enough — save full Explain for longer-answer questions.",
      glossary: [
        { term: "Point", def: "your direct answer to the question" },
        { term: "Evidence", def: "a quotation or detail from the text supporting your point" },
        { term: "Explain", def: "how the evidence proves your point" },
        { term: "structured answer", def: "a response organised into clear, logical parts" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: PEEMethodDemo,
      worked: {
        question: 'Passage: "Leo\'s hands shook as he unfolded the letter, and he had to read the first line three times before it made sense." Question: "How do we know Leo was nervous about the letter?"',
        fastMethod: "State the point first, then quote the exact evidence, then explain why it proves nervousness.",
        steps: [
          "Point: Leo was clearly nervous about opening the letter.",
          'Evidence: the text says "his hands shook" and he "had to read the first line three times."',
          "Explain: shaking hands and struggling to focus are physical signs of nervousness or anxiety.",
          "Combine all three into one flowing answer for full marks.",
        ],
        answer: 'Leo was nervous, shown by <b>"his hands shook"</b> and having to reread the line — physical signs of anxiety.',
      },
      selfCheck: { prompt: "In PEE, which part actually contains the quotation from the text?", answer: "<b>Evidence</b> — the Point states the answer, and Explain links the quotation back to the question." },
      kind: "click-evidence",
      questions: [
        {
          id: "pee-q1",
          instruction: "Click the sentence you would use as Evidence for the point 'Freya was proud of her painting.'",
          passage: [
            "Freya stepped back from the easel and studied her work for a long moment.",
            "She had spent every free afternoon that week on the painting.",
            "A small, satisfied smile spread across her face as she signed the corner.",
            "Her teacher had not seen the finished piece yet.",
          ],
          correctIdx: 2,
          correction: 'the sentence "a small, satisfied smile spread across her face as she signed the corner" is the clearest piece of Evidence showing pride — a signature and a smile both suggest ownership and satisfaction.',
          hint: "Find the sentence showing a physical sign of pride, not just time spent working.",
        },
        {
          id: "pee-q2",
          instruction: "Click the sentence you would use as Evidence for the point 'The storm caused serious damage to the village.'",
          passage: [
            "The storm had raged through the night, rattling every window in the village.",
            "By morning, three roofs had been torn off and the old oak tree lay across the road.",
            "Neighbours gathered in the square, comparing stories from the night before.",
            "The council promised repairs would begin within the week.",
          ],
          correctIdx: 1,
          correction: 'the clearest Evidence of serious damage is "three roofs had been torn off and the old oak tree lay across the road" — specific, concrete proof rather than general description.',
          hint: "Find the sentence listing specific, concrete damage rather than the storm's noise or the aftermath conversation.",
        },
        {
          id: "pee-q3",
          instruction: "Click the sentence you would use as Evidence for the point 'Mr Hale was a strict teacher.'",
          passage: [
            "Mr Hale's classroom was famous across the school for its silence.",
            "He insisted that homework be handed in exactly on time, with no exceptions.",
            "Some students found his lessons the most useful of the week.",
            "He rarely raised his voice, but nobody ever tested him.",
          ],
          correctIdx: 1,
          correction: 'the strongest Evidence of strictness is "insisted that homework be handed in exactly on time, with no exceptions" — a specific, quotable rule showing his approach.',
          hint: "Find the sentence describing a specific rule he enforced, not students' opinions of his lessons.",
        },
      ],
      mistakes: [
        "Giving a Point with no Evidence — an unsupported answer, even if correct, often loses marks.",
        "Quoting Evidence but never explaining how it connects back to the Point, leaving the link to the examiner to work out.",
      ],
      examTip: "For any question worth more than one mark, always check whether you've included a short quotation — Point alone is rarely enough.",
      searchTerms: ["PEE method", "point evidence explain", "structured answer", "written retrieval", "quotation", "explain"],
    },
    {
      id: "numbers-dates-names-vs-descriptive",
      title: "Retrieving Numbers, Dates & Names vs. Descriptive Detail",
      tier: "Extension",
      objective: "Distinguish between retrieving precise facts (numbers, dates, names) and retrieving descriptive detail (how something looked, felt or sounded).",
      whyMatters: "precise facts and descriptive detail need different scanning strategies — mixing them up means searching the wrong part of the passage for the wrong kind of clue.",
      conceptTitle: "Precise facts vs. descriptive language",
      conceptBullets: [
        '<b style="color:#C9A24B">Precise facts</b> — numbers, dates, names, times — are usually stated in a short, exact phrase and are easy to scan for.',
        "<b>Descriptive detail</b> — how something looked, sounded, felt — is often spread across adjectives and imagery rather than one exact word.",
        "When scanning for a precise fact, look for digits, capital letters (names) or units (kilometres, o'clock, years).",
        "When retrieving descriptive detail, you may need to gather several describing words from across a sentence, not just one.",
      ],
      conceptNote: "<b>Tip:</b> precise facts rarely need paraphrasing — descriptive detail almost always does, since it's about capturing an impression, not a single fact.",
      glossary: [
        { term: "precise fact", def: "an exact number, date, time or name stated in the text" },
        { term: "descriptive detail", def: "language describing how something looked, sounded or felt" },
        { term: "imagery", def: "descriptive language that creates a picture in the reader's mind" },
        { term: "unit", def: "a word showing measurement, e.g. kilometres, hours" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: NumbersDatesNamesDemo,
      worked: {
        question: 'Passage: "The old clock tower, its stone worn smooth by two centuries of weather, struck eleven just as the last shop closed its shutters." Question A: "What time did the clock strike?" Question B: "How does the text describe the clock tower\'s appearance?"',
        fastMethod: "Split the sentence into its factual half (the time) and its descriptive half (the stone worn smooth).",
        steps: [
          "For the precise fact question, scan for a number word: 'eleven'.",
          "For the descriptive question, look instead at the adjectives and imagery: 'stone worn smooth by two centuries of weather'.",
          "Notice the two answers come from different parts of the same sentence, needing different reading strategies.",
          "Answer each question using the matching type of detail.",
        ],
        answer: "The clock struck <b>eleven</b>; its appearance is described as <b>stone worn smooth by two centuries of weather</b>.",
      },
      selfCheck: { prompt: "Which is more likely to require paraphrasing in your own words: a date, or a description of a character's expression?", answer: "<b>A description of a character's expression</b> — dates and numbers are precise facts usually copied exactly, while descriptions are often explained in your own words." },
      kind: "click-evidence",
      questions: [
        {
          id: "facts-desc-q1",
          instruction: "Click the sentence that gives the exact year the lighthouse was built.",
          passage: [
            "The lighthouse has guided ships safely past the rocks for generations.",
            "It was built in 1887 by a team of local stonemasons.",
            "Its white tower gleams brightly against the grey cliffs behind it.",
            "Today it operates automatically, with no keeper living inside.",
          ],
          correctIdx: 1,
          correction: 'the exact year is a precise fact stated directly: "built in 1887" — a straightforward number to scan for and copy exactly.',
          hint: "Scan for a four-digit year rather than a description of the tower's appearance.",
        },
        {
          id: "facts-desc-q2",
          instruction: "Click the sentence that describes what the forest sounded like.",
          passage: [
            "Mia stepped off the path and into the shadow of the old trees.",
            "Somewhere above, a woodpecker began its rhythmic knocking.",
            "The air smelled of damp moss and fallen leaves.",
            "She had walked this way at least a hundred times before.",
          ],
          correctIdx: 1,
          correction: 'the descriptive sound detail is here: "a woodpecker began its rhythmic knocking" — this kind of detail is gathered from imagery, not from a number or name.',
          hint: "Look for the sentence appealing to hearing, rather than smell or a specific number.",
        },
        {
          id: "facts-desc-q3",
          instruction: "Click the sentence that names the exact person who discovered the fossil.",
          passage: [
            "The dusty quarry had been searched many times before without success.",
            "It was young geologist Daniel Reyes who finally spotted the curved shape in the rock.",
            "The find was later confirmed as an ancient sea creature.",
            "News of the discovery spread quickly through the scientific community.",
          ],
          correctIdx: 1,
          correction: 'the exact name is stated directly: "young geologist Daniel Reyes" — a precise fact you would scan for and copy exactly, unlike a description.',
          hint: "Scan for a proper noun naming a person, not a general description of the discovery.",
        },
      ],
      mistakes: [
        "Trying to paraphrase a precise fact like a date or number, when it should simply be copied exactly.",
        "Only picking out a single word for a descriptive-detail question when the fuller image is spread across several words in the sentence.",
      ],
      examTip: "Before scanning, decide whether the question wants a fact (scan for digits, capitals, units) or a description (scan for adjectives and sensory words).",
      searchTerms: ["numbers and dates", "names", "descriptive detail", "precise facts", "imagery", "scanning strategy"],
    },
    {
      id: "multi-part-retrieval",
      title: "Multi-Part Retrieval",
      tier: "Extension",
      objective: "Combine two separate pieces of evidence from different parts of a passage to build one complete answer.",
      whyMatters: "some retrieval questions can't be answered from a single sentence — missing the second piece of evidence means only a half-correct, part-marked answer.",
      conceptTitle: "When one sentence isn't the whole answer",
      conceptBullets: [
        '<b style="color:#C9A24B">Multi-part retrieval</b> questions need two (or more) separate details from different points in the passage, combined into a single answer.',
        "These questions often use plural wording — 'give two reasons', 'name both', 'what two things' — a strong signal more than one piece of evidence is needed.",
        "Read the whole passage before finalising your answer — the second clue is sometimes several sentences away from the first.",
        "Even when one sentence carries the key decisive evidence, checking the surrounding text ensures you haven't missed a second required detail.",
      ],
      conceptNote: "<b>Warning sign:</b> if a question is worth two marks but you've only found one piece of evidence, keep reading — a second detail is almost certainly still out there.",
      glossary: [
        { term: "multi-part question", def: "a question requiring more than one piece of evidence" },
        { term: "combined evidence", def: "two or more details drawn together into one answer" },
        { term: "plural wording", def: "question phrasing like 'two reasons' signalling multiple answers needed" },
        { term: "decisive evidence", def: "the single sentence that states the key outcome or fact" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: MultiPartRetrievalDemo,
      worked: {
        question: 'Passage: "Rehearsals had been chaotic all week, with two actors down with flu. On the morning of the show, the lead singer lost her voice completely." Question: "Give two reasons the performance nearly didn\'t go ahead."',
        fastMethod: "Spot the plural wording 'two reasons' and read the whole passage for both clues before answering.",
        steps: [
          "Notice the question asks for 'two reasons', signalling more than one piece of evidence is required.",
          "First reason, from the first sentence: two actors were ill with flu.",
          "Second reason, from the second sentence: the lead singer lost her voice on the morning of the show.",
          "Combine both details into a single complete answer.",
        ],
        answer: "Two actors had flu, <b>and</b> the lead singer lost her voice on the morning of the show.",
      },
      selfCheck: { prompt: "What kind of question wording is a strong signal that more than one piece of evidence is needed?", answer: "<b>Plural wording</b>, such as 'give two reasons' or 'name both things'." },
      kind: "click-evidence",
      questions: [
        {
          id: "multipart-q1",
          instruction: "Click the sentence that gives the key decisive evidence for: 'Why was the school trip cancelled?'",
          passage: [
            "Excitement had been building for weeks ahead of the museum trip.",
            "Two coaches had already been booked for the whole year group.",
            "A sudden strike on the rail network meant one coach driver couldn't get to work.",
            "With only one coach available, the headteacher decided to postpone the trip until next term.",
          ],
          correctIdx: 3,
          correction: 'the decisive outcome is stated here: "the headteacher decided to postpone the trip" — a fuller answer would also mention the coach driver being unable to work, but this sentence carries the key evidence for the question asked.',
          hint: "The question asks why the trip was cancelled — find the sentence stating the actual decision.",
        },
        {
          id: "multipart-q2",
          instruction: "Click the sentence that gives the key decisive evidence for: 'Why did the bakery run out of bread early?'",
          passage: [
            "The bakery on the corner usually stayed open until five o'clock.",
            "That morning, the delivery van had broken down two streets away.",
            "A local football match had also brought unusually large crowds into town.",
            "By eleven o'clock, every loaf on the shelves had already been sold.",
          ],
          correctIdx: 3,
          correction: 'the decisive evidence stating the actual outcome is "by eleven o\'clock, every loaf on the shelves had already been sold" — a complete answer would combine this with the earlier causes (the broken van and the crowds), but this sentence is the key result.',
          hint: "Find the sentence stating that the bread had actually sold out, not just the possible causes.",
        },
        {
          id: "multipart-q3",
          instruction: "Click the sentence that gives the key decisive evidence for: 'Why did the football match finish early?'",
          passage: [
            "Dark clouds had been gathering over the stadium since kick-off.",
            "One player had picked up a knock in the opening minutes.",
            "A sudden downpour flooded the pitch just after half-time.",
            "The referee blew the final whistle ten minutes early, unable to let play continue.",
          ],
          correctIdx: 3,
          correction: 'the decisive evidence for the actual early finish is "the referee blew the final whistle ten minutes early" — the flooding a sentence earlier is the cause, but this sentence states the outcome the question is asking about.',
          hint: "Find the sentence describing the actual early finish, not just the weather that caused it.",
        },
      ],
      mistakes: [
        "Stopping after finding the first piece of evidence when the question's plural wording asks for two.",
        "Combining unrelated details from the passage instead of the two that specifically answer the question asked.",
      ],
      examTip: "Count the marks available — if a question is worth two marks, expect to need two separate pieces of evidence, not just one.",
      searchTerms: ["multi-part retrieval", "two reasons", "combined evidence", "plural wording", "two marks"],
    },
    {
      id: "nonfiction-retrieval",
      title: "Retrieval From Non-Fiction Texts",
      tier: "Extension",
      objective: "Locate facts efficiently in non-fiction texts using headings, captions, tables and bullet-style facts as navigation tools.",
      whyMatters: "non-fiction passages are structured differently from stories — knowing how to use headings and layout features speeds up retrieval considerably.",
      conceptTitle: "Use the structure, not just the sentences",
      conceptBullets: [
        '<b style="color:#C9A24B">Headings and subheadings</b> tell you what topic each section covers before you read a single sentence of it.',
        "<b>Captions</b> under images or diagrams often contain a precise fact that isn't repeated anywhere else in the main text.",
        "<b>Tables and bullet points</b> present facts in short, exact form — ideal for scanning quickly for a specific figure.",
        "Always check the whole page layout, not just the paragraphs — the answer might be sitting in a caption or table, not the running text.",
      ],
      conceptNote: "<b>Habit:</b> before reading a non-fiction passage in detail, glance at every heading, caption and table first to build a mental map of where facts live.",
      glossary: [
        { term: "heading", def: "a short title introducing a section's topic" },
        { term: "caption", def: "text explaining an image, diagram or photograph" },
        { term: "table", def: "information organised into rows and columns" },
        { term: "non-fiction", def: "writing based on real facts, not an invented story" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: NonFictionFactsDemo,
      worked: {
        question: 'Passage: a non-fiction page about the Great Barrier Reef, with a heading "Size and Location", a photo captioned "Aerial view of coral formations, 2019", and a bullet list of facts including "Length: approximately 2,300 kilometres". Question: "How long is the Great Barrier Reef?"',
        fastMethod: "Skip straight to the bullet list under the relevant heading rather than reading the running text.",
        steps: [
          "Notice the heading 'Size and Location' signals this is the right section for a length question.",
          "Check the bullet-point facts beneath it, since they present exact figures clearly.",
          "Locate 'Length: approximately 2,300 kilometres' directly in the bullet list.",
          "No need to read the caption or the main paragraph text at all — the bullet list already had the answer.",
        ],
        answer: "The reef is approximately <b>2,300 kilometres</b> long.",
      },
      selfCheck: { prompt: "In a non-fiction text, where might a precise fact appear that isn't repeated anywhere in the main paragraphs?", answer: "<b>In a caption under an image or diagram</b>, or within a table or bullet-point list." },
      kind: "click-evidence",
      questions: [
        {
          id: "nonfic-q1",
          instruction: "Click the sentence that gives the exact height of Mount Kilimanjaro.",
          passage: [
            "Mount Kilimanjaro is the tallest mountain on the African continent.",
            "It stands at 5,895 metres above sea level.",
            "Despite being near the equator, its summit is capped with snow.",
            "Thousands of climbers attempt the ascent every year.",
          ],
          correctIdx: 1,
          correction: 'the precise figure is stated directly: "5,895 metres above sea level" — non-fiction texts often present this kind of fact in a short, exact sentence.',
          hint: "Scan for the sentence containing an exact figure in metres.",
        },
        {
          id: "nonfic-q2",
          instruction: "Click the sentence that gives the exact recommended daily amount of water.",
          passage: [
            "Staying hydrated is essential for concentration and physical health.",
            "Experts generally recommend around two litres of water a day for adults.",
            "This amount can vary depending on exercise levels and the weather.",
            "Fruit and vegetables also contribute to daily water intake.",
          ],
          correctIdx: 1,
          correction: 'the exact recommended amount is given directly: "around two litres of water a day" — a fact-style sentence typical of non-fiction writing.',
          hint: "Scan for the sentence stating a specific measurement in litres.",
        },
        {
          id: "nonfic-q3",
          instruction: "Click the sentence that gives the exact number of bones in the human hand.",
          passage: [
            "The human hand is one of the most complex parts of the skeleton.",
            "Each hand contains twenty-seven individual bones.",
            "These bones allow for an extraordinary range of movement.",
            "Doctors study hand bones closely when diagnosing certain injuries.",
          ],
          correctIdx: 1,
          correction: 'the precise number is stated in the second sentence: "twenty-seven individual bones" — exactly the kind of fact that non-fiction retrieval questions target.',
          hint: "Scan for the sentence containing an exact number of bones.",
        },
      ],
      mistakes: [
        "Reading only the main body paragraphs and missing a key fact hidden in a caption, table or bullet list.",
        "Ignoring headings entirely and reading a whole non-fiction page in order, when the heading could have pointed straight to the right section.",
      ],
      examTip: "Treat headings like a map — read them all first, decide which section is relevant to the question, then go straight there.",
      searchTerms: ["non-fiction", "headings", "captions", "tables", "bullet points", "fact retrieval"],
    },
    {
      id: "spotting-distractors",
      title: "Spotting Distractors",
      tier: "Extension",
      objective: "Identify sentences that look plausible but do not actually answer the question, and choose the genuinely correct evidence instead.",
      whyMatters: "examiners deliberately place plausible-but-wrong details near the real answer — falling for a distractor is one of the most common ways students lose marks on retrieval questions.",
      conceptTitle: "Not every promising-looking sentence is the answer",
      conceptBullets: [
        '<b style="color:#C9A24B">A distractor</b> is a sentence that seems related to the question but does not actually state the answer.',
        "Distractors are often placed just before or after the real evidence, so a rushed reader picks the wrong one.",
        "A distractor may describe something similar, mention the right topic, or create a false impression — without giving the actual fact asked for.",
        "Always check that your chosen sentence answers the exact question, word for word — not just that it 'feels' related.",
      ],
      conceptNote: "<b>Test:</b> ask 'does this sentence literally state the answer, or does it just seem connected?' before committing to it.",
      glossary: [
        { term: "distractor", def: "a plausible-looking sentence that doesn't actually answer the question" },
        { term: "red herring", def: "a detail designed to mislead the reader" },
        { term: "false impression", def: "an idea a sentence seems to suggest without stating it directly" },
        { term: "precise match", def: "evidence that answers the exact question asked, not just a related one" },
      ],
      diagramLabel: "Interactive · Find the Evidence",
      Diagram: SpottingDistractorsDemo,
      worked: {
        question: 'Passage: "Owen had trained harder than anyone else on the team all season. On the day of the trials, however, it was quiet, steady Amir who was selected for the county squad." Question: "Who was selected for the county squad?"',
        fastMethod: "Notice the first sentence about Owen is a distractor — the real answer is in the second sentence.",
        steps: [
          "The first sentence about Owen training hard creates the impression he might be the answer.",
          "Read on before answering — the question asks who was selected, not who trained hardest.",
          'The second sentence states directly: "it was quiet, steady Amir who was selected."',
          "Amir, not Owen, is the genuinely correct answer — the first sentence was a distractor.",
        ],
        answer: "It was <b>Amir</b> who was selected, not Owen.",
      },
      selfCheck: { prompt: "Where are distractor sentences often placed in a passage relative to the real evidence?", answer: "<b>Just before or after the real evidence</b>, so a reader who stops too early picks the wrong sentence." },
      kind: "click-evidence",
      questions: [
        {
          id: "distractor-q1",
          instruction: "Click the sentence that tells you who actually solved the puzzle first.",
          passage: [
            "Ravi had been staring at the puzzle for almost an hour, muttering to himself.",
            "His sister Nina wandered over, glanced at it for a moment, and pointed out the missing piece.",
            "Ravi insisted he had nearly worked it out himself.",
            "Their mum laughed and told them both to tidy up for dinner.",
          ],
          correctIdx: 1,
          correction: 'Ravi\'s hour of effort is a distractor suggesting he might be the answer, but the genuine evidence is "Nina wandered over... and pointed out the missing piece" — she solved it first, not him.',
          hint: "One character spent a long time trying without success — look instead for who actually solved it.",
        },
        {
          id: "distractor-q2",
          instruction: "Click the sentence that tells you which team actually won the quiz.",
          passage: [
            "The Rockets had led on points for almost the entire evening.",
            "Excitement grew as the final round approached.",
            "A last, tricky bonus question saw the Falcons overtake them in the closing seconds.",
            "Both teams shook hands warmly at the end.",
          ],
          correctIdx: 2,
          correction: 'the Rockets leading "for almost the entire evening" is a distractor — the genuine evidence is that "the Falcons overtake them in the closing seconds," making the Falcons the actual winners.',
          hint: "One team led for most of the evening, but the result changed right at the end — find the sentence stating who actually won.",
        },
        {
          id: "distractor-q3",
          instruction: "Click the sentence that tells you where the missing dog was actually found.",
          passage: [
            "Posters of the missing dog had been pinned up all around the park.",
            "Several neighbours reported seeing a similar dog near the railway station.",
            "It turned out the dog had been sheltering under a neighbour's garden shed the whole time.",
            "The family was overjoyed to have him home safely.",
          ],
          correctIdx: 2,
          correction: 'the sightings near the railway station are a distractor that turned out to be wrong — the genuine evidence is "sheltering under a neighbour\'s garden shed," which is where the dog actually was.',
          hint: "One location was only a reported sighting; another sentence states where the dog truly was found.",
        },
      ],
      mistakes: [
        "Selecting the first plausible-looking sentence instead of reading on to check whether a later sentence contradicts or corrects it.",
        "Assuming a sentence mentioning the right topic must be the answer, without checking it states the specific fact asked for.",
      ],
      examTip: "Whenever a sentence seems to answer the question a little too easily right at the start of a paragraph, read on — the real answer, or a correction, is often just a sentence or two away.",
      searchTerms: ["distractors", "red herring", "false impression", "misleading evidence", "careful reading", "exam traps"],
    },
  ],
};
