import type { TopicContent } from "../types";
import {
  NounsDemo,
  VerbsDemo,
  AdjectivesDemo,
  AdverbsDemo,
  PronounsDemo,
  PrepositionsDemo,
  ConjunctionsDemo,
  DeterminersDemo,
  ConfusedPartsDemo,
  OddOneOutDemo,
} from "../notes-diagrams/grammar-demos";

const CLICK_INSTRUCTION = "Click the word with the error.";

export const partsOfSpeechErrorsTopic: TopicContent = {
  slug: "parts-of-speech-errors",
  subject: "English",
  subjectSlug: "english",
  title: "Grammar: Parts of Speech Errors",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "GL and CSSE-style “spot the mistake” and “complete the sentence” questions hinge on knowing what each part of speech is for and how it can go wrong. This module works through nouns, verbs, adjectives, adverbs, pronouns, prepositions, conjunctions and determiners — then trains you to spot a word doing the wrong job.",
  subtopics: [
    {
      id: "nouns",
      title: "Nouns",
      tier: "Foundation",
      objective: "Recognise common, proper, collective and abstract nouns — and spot when one has been used or written incorrectly.",
      whyMatters: "“spot the mistake” questions on GL-style papers frequently hinge on noun errors — a missing capital letter or the wrong collective noun is one of the most common traps.",
      conceptTitle: "What is a noun?",
      conceptBullets: [
        'Every <b style="color:#C9A24B">noun</b> falls into one of four families, and each behaves differently in a sentence.',
        '<b>Common noun</b>: a general name, not capitalised — e.g. <i>city</i>, <i>dog</i>.',
        '<b>Proper noun</b>: a specific name, always capitalised — e.g. <i>London</i>, <i>Mara</i>.',
        '<b>Collective noun</b>: names a group of things — e.g. a <i>flock</i> of birds, a <i>team</i> of players.',
        '<b>Abstract noun</b>: names an idea or feeling you can’t touch — e.g. <i>courage</i>, <i>happiness</i>.',
      ],
      conceptNote: "<b>Remember:</b> if you can put “the” or “a” in front of a word and it names something, it’s very likely a noun.",
      glossary: [
        { term: "common noun", def: "a general name, lowercase" },
        { term: "proper noun", def: "a specific name, capitalised" },
        { term: "collective noun", def: "names a group" },
        { term: "abstract noun", def: "names an idea or feeling" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: NounsDemo,
      worked: {
        question: "Spot the noun error: “The herd of geese flew south as autumn arrived, led by an old bird the flock trusted.”",
        fastMethod: 'Check every collective noun against what it’s grouping — "herd" is for cattle or deer, not geese, so it’s the error.',
        steps: [
          "Read the sentence and check every noun in turn — not just the obvious ones.",
          "“Herd” names a group — a collective noun — but “herd” is used for cattle or deer, not geese.",
          "“Flock” is the correct collective noun for geese and birds in general.",
          "The error is the first word: the sentence should read “the flock of geese…”",
        ],
        answer: "The error is <b>herd</b> — it should be <b>flock</b>.",
      },
      selfCheck: { prompt: "True or false: “happiness” is a collective noun.", answer: "<b>False</b> — “happiness” is an abstract noun. It names a feeling, not a group." },
      kind: "click-error",
      questions: [
        {
          id: "nouns-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "committee", "announced", "the", "winner", "of", "the", "competition", "at", "the", "town", "hall", "on", "monday."],
          errorIdx: 13,
          correction: '"monday" should be "Monday" — days of the week are proper nouns and always take a capital letter.',
          hint: "Look for a specific day of the week near the end of the sentence.",
        },
        {
          id: "nouns-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["A", "swarm", "of", "wolves", "howled", "in", "the", "distance", "as", "night", "fell", "over", "the", "forest."],
          errorIdx: 1,
          correction: '"swarm" is used for insects like bees, not wolves — the correct collective noun here is "pack".',
          hint: "Check the collective noun used to describe the group of wolves.",
        },
        {
          id: "nouns-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "felt", "a", "deep", "sense", "of", "Courage", "before", "stepping", "onto", "the", "stage."],
          errorIdx: 6,
          correction: '"Courage" is an abstract noun, not a proper noun — it should not be capitalised: "courage".',
          hint: "One noun in this sentence has been given a capital letter it shouldn’t have.",
        },
      ],
      mistakes: [
        "Mistaking a missing capital letter on a proper noun for a simple spelling error — it’s a noun-type error, not a spelling one.",
        "Assuming any word for a group is correct — collective nouns are often specific (a “pride” of lions, not a “herd”).",
      ],
      examTip: "Read the sentence aloud in your head — a wrong collective noun, or a proper noun missing its capital, often sounds off before you can explain why.",
      searchTerms: ["noun", "common noun", "proper noun", "collective noun", "abstract noun", "capital letter"],
    },
    {
      id: "verbs",
      title: "Verbs: Main vs. Helping Verbs",
      tier: "Foundation",
      objective: "Identify the main verb in a sentence and the helping (auxiliary) verbs that support it, and spot when the wrong verb form has been used.",
      whyMatters: "verb-form errors — especially after helping verbs like “had”, “has” and “was” — are one of the most common “spot the mistake” traps on 11+ papers.",
      conceptTitle: "What is a verb?",
      conceptBullets: [
        'A <b style="color:#C9A24B">verb</b> is a doing, being or having word — it tells you what happens in a sentence.',
        '<b>Main verb</b>: carries the core meaning — e.g. <i>run</i>, <i>think</i>, <i>arrive</i>.',
        '<b>Helping (auxiliary) verb</b>: supports the main verb to show tense or mood — e.g. <i>is</i>, <i>had</i>, <i>will</i>, <i>can</i>.',
        "Helping verbs demand a specific form of the main verb — “had” wants a past participle (had <i>started</i>), not the base form (had <i>start</i>).",
      ],
      conceptNote: "<b>Common mistake:</b> using the base form of a verb after a helping verb that needs the past participle, e.g. “had went” instead of “had gone”.",
      glossary: [
        { term: "main verb", def: "carries the core action or state" },
        { term: "auxiliary verb", def: "supports the main verb (is, had, will)" },
        { term: "past participle", def: "the form used after have/had (gone, started)" },
        { term: "base form", def: "the plain, dictionary form of a verb" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: VerbsDemo,
      worked: {
        question: "Spot the verb error: “She has already ate breakfast before the bus arrived.”",
        fastMethod: '"has" is a helping verb that needs a past participle — "ate" is the simple past, not the past participle "eaten".',
        steps: [
          "Find the helping verb — “has” — and check what form it expects to follow it.",
          "“Has” always pairs with a past participle, not the simple past tense.",
          "“Ate” is simple past (I ate); the past participle is “eaten” (I have eaten).",
          "Correct: “She has already eaten breakfast…”",
        ],
        answer: "The error is <b>ate</b> — it should be <b>eaten</b>.",
      },
      selfCheck: { prompt: "True or false: in “they were laughing”, “laughing” is a helping verb.", answer: "<b>False</b> — “laughing” is the main verb; “were” is the helping verb showing the tense." },
      kind: "click-error",
      questions: [
        {
          id: "verbs-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["By", "the", "end", "of", "the", "match,", "the", "crowd", "had", "already", "leave."],
          errorIdx: 10,
          correction: '"had" needs a past participle — "leave" should be "left": had already left.',
          hint: "Check what form the main verb takes after the helping verb “had”.",
        },
        {
          id: "verbs-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "children", "was", "playing", "in", "the", "garden", "when", "it", "started", "to", "rain."],
          errorIdx: 2,
          correction: '"children" is plural, so the helping verb must be "were", not "was": the children were playing.',
          hint: "Check whether the helping verb agrees with a singular or plural subject.",
        },
        {
          id: "verbs-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["I", "should", "of", "known", "the", "bridge", "would", "be", "closed", "for", "repairs."],
          errorIdx: 2,
          correction: '"should of" is a common mishearing of "should have" — "of" is a preposition, not a helping verb, and cannot follow "should".',
          hint: "One word here sounds right when spoken but is the wrong part of speech entirely.",
        },
      ],
      mistakes: [
        "Writing “should of / could of / would of” instead of “should have / could have / would have” — they sound alike but “of” is never a verb.",
        "Using the simple past instead of the past participle after “have/has/had” (e.g. “had went” instead of “had gone”).",
      ],
      examTip: "If you can swap the sentence into a different tense and the verb form still sounds wrong, that’s a strong sign you’ve found the error.",
      searchTerms: ["verb", "main verb", "helping verb", "auxiliary verb", "past participle", "tense"],
    },
    {
      id: "adjectives",
      title: "Adjectives: Usage & Order",
      tier: "Standard",
      objective: "Use adjectives correctly to describe nouns, and apply the standard order adjectives follow when more than one is used together.",
      whyMatters: "adjective-order errors are subtle but common in “spot the mistake” questions — native speakers instinctively feel the wrong order without always knowing the rule.",
      conceptTitle: "What is an adjective?",
      conceptBullets: [
        'An <b style="color:#C9A24B">adjective</b> describes a noun — e.g. <i>tall</i>, <i>red</i>, <i>ancient</i>.',
        "When several adjectives describe one noun, English speakers follow a set order: opinion, size, age, shape, colour, origin, material, purpose, then the noun.",
        'Example: "a <i>beautiful</i> (opinion) <i>small</i> (size) <i>old</i> (age) <i>brown</i> (colour) <i>leather</i> (material) bag."',
        "Breaking this order doesn’t make a sentence ungrammatical exactly — but it sounds noticeably wrong, which is exactly what “spot the mistake” questions test.",
      ],
      conceptNote: "<b>Memory trick:</b> Opinion Size Age Shape Colour Origin Material Purpose — “OSASCOMP”, worked left to right toward the noun.",
      glossary: [
        { term: "adjective", def: "a word that describes a noun" },
        { term: "opinion adjective", def: "a judgement word (beautiful, boring)" },
        { term: "adjective order", def: "the standard sequence adjectives follow before a noun" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: AdjectivesDemo,
      worked: {
        question: "Spot the error: “He drove a fast red small car around the track.”",
        fastMethod: "Size adjectives come before colour adjectives — “small” should sit before “red”, not after.",
        steps: [
          "List the adjectives in order of appearance: fast (opinion/quality), red (colour), small (size).",
          "The correct order is opinion, size, then colour — not opinion, colour, size.",
          "Rearranged correctly: “a fast small red car”.",
          "The error is that “small” appears after “red” instead of before it.",
        ],
        answer: "The order should be <b>fast, small, red</b> — not fast, red, small.",
      },
      selfCheck: { prompt: "Which comes first in standard adjective order: size or age?", answer: "<b>Size</b> comes before age — e.g. “a small old house”, not “an old small house”." },
      kind: "click-error",
      questions: [
        {
          id: "adj-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["We", "stayed", "in", "a", "wooden", "charming", "cottage", "by", "the", "lake."],
          errorIdx: 5,
          correction: '"charming" (opinion) should come before "wooden" (material): a charming wooden cottage.',
          hint: "Opinion adjectives always come before material adjectives.",
        },
        {
          id: "adj-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "museum", "displayed", "an", "ancient", "Egyptian", "enormous", "statue."],
          errorIdx: 6,
          correction: '"enormous" describes size, which should come before age and origin: an enormous ancient Egyptian statue.',
          hint: "Size adjectives belong near the front of the group, not the end.",
        },
        {
          id: "adj-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "bought", "a", "square", "beautiful", "silver", "picture", "frame."],
          errorIdx: 4,
          correction: '"beautiful" is an opinion adjective and should come first: a beautiful square silver picture frame.',
          hint: "Opinion words always lead the group of adjectives, before shape or colour.",
        },
      ],
      mistakes: [
        "Placing an opinion adjective (beautiful, lovely, ugly) after a fact adjective (size, colour, material) instead of before it.",
        "Assuming adjective order doesn’t matter because a sentence is still understandable — exams test the standard order specifically.",
      ],
      examTip: "Say the phrase both ways in your head — the correct order almost always sounds smoother, even before you can name the rule.",
      searchTerms: ["adjective", "adjective order", "opinion", "size", "colour", "describing words"],
    },
    {
      id: "adverbs",
      title: "Adverbs: -ly Formation & Misuse",
      tier: "Standard",
      objective: "Form adverbs correctly from adjectives and recognise when an adjective has wrongly been used in place of an adverb.",
      whyMatters: "confusing adjectives and adverbs (“ran quick” instead of “ran quickly”) is one of the single most common grammar errors tested at 11+.",
      conceptTitle: "What is an adverb?",
      conceptBullets: [
        'An <b style="color:#C9A24B">adverb</b> describes a verb, an adjective, or another adverb — it usually tells you <i>how</i>, <i>when</i>, or <i>to what extent</i>.',
        "Most adverbs are formed by adding <b>-ly</b> to an adjective: quick → quickly, careful → carefully.",
        "Adjectives describe nouns; adverbs describe actions — mixing them up is the single most common error in this category.",
        "Not every adverb ends in -ly (e.g. <i>fast</i>, <i>well</i>), and not every -ly word is an adverb (e.g. <i>friendly</i> is an adjective).",
      ],
      conceptNote: "<b>Test it:</b> ask what the describing word is attached to — a noun (needs an adjective) or an action (needs an adverb).",
      glossary: [
        { term: "adverb", def: "describes a verb, adjective or adverb" },
        { term: "adjective", def: "describes a noun" },
        { term: "-ly suffix", def: "the most common way to form an adverb" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: AdverbsDemo,
      worked: {
        question: "Spot the error: “He answered the teacher’s question correct.”",
        fastMethod: '"correct" describes how he answered (an action), so it needs the adverb form "correctly".',
        steps: [
          "Find the word being described by “correct” — it’s the verb “answered”, an action.",
          "Words describing actions need the adverb form, not the adjective form.",
          "“Correct” is an adjective (a correct answer); “correctly” is the adverb.",
          "Corrected: “He answered the teacher’s question correctly.”",
        ],
        answer: "The error is <b>correct</b> — it should be <b>correctly</b>.",
      },
      selfCheck: { prompt: "True or false: in “a friendly smile”, “friendly” is an adverb because it ends in -ly.", answer: "<b>False</b> — “friendly” describes the noun “smile”, so it’s an adjective despite the -ly ending." },
      kind: "click-error",
      questions: [
        {
          id: "adv-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "waiter", "carried", "the", "tray", "careful", "through", "the", "crowded", "restaurant."],
          errorIdx: 5,
          correction: '"careful" describes how the tray was carried, so it must be the adverb "carefully".',
          hint: "Find the word describing the manner of carrying, not the tray itself.",
        },
        {
          id: "adv-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "sang", "beautiful", "at", "the", "concert", "last", "night."],
          errorIdx: 2,
          correction: '"beautiful" describes how she sang (the action), so it needs the adverb form "beautifully".',
          hint: "Check whether the describing word is attached to the singer or to the singing.",
        },
        {
          id: "adv-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "results", "arrived", "surprising", "early", "this", "year."],
          errorIdx: 3,
          correction: '"surprising" is describing the adverb "early" (how early?), so it needs the adverb form "surprisingly".',
          hint: "An adverb can also describe another adverb — check what “surprising” is attached to here.",
        },
      ],
      mistakes: [
        "Dropping the -ly and using the adjective form after a verb (e.g. “ran quick” instead of “ran quickly”).",
        "Assuming any -ly word is an adverb — words like “friendly”, “lovely” and “silly” are adjectives.",
      ],
      examTip: "Ask “what is this word describing?” — a noun needs an adjective, an action or another describing word needs an adverb.",
      searchTerms: ["adverb", "adjective", "-ly", "manner", "describing words"],
    },
    {
      id: "pronouns",
      title: "Pronouns: Personal, Possessive & Reflexive",
      tier: "Standard",
      objective: "Use subject, object, possessive and reflexive pronouns correctly, and spot common substitution errors.",
      whyMatters: "pronoun errors — especially “me and X” as a subject, and its/it’s confusion — appear constantly in both the grammar and the writing sections of 11+ papers.",
      conceptTitle: "Types of pronoun",
      conceptBullets: [
        'A <b style="color:#C9A24B">pronoun</b> stands in for a noun so you don’t have to keep repeating it.',
        "<b>Subject pronouns</b> (I, he, she, we, they) do the action: “<i>She</i> ran.”",
        "<b>Object pronouns</b> (me, him, her, us, them) receive the action: “They saw <i>her</i>.”",
        "<b>Possessive pronouns</b> (mine, yours, his, hers, ours, theirs) show ownership and never take an apostrophe.",
        "<b>Reflexive pronouns</b> (myself, yourself, himself) refer back to the subject: “I hurt <i>myself</i>.”",
      ],
      conceptNote: "<b>Common mistake:</b> using an object pronoun as a subject, e.g. “Me and my brother went…” instead of “My brother and I went…”.",
      glossary: [
        { term: "subject pronoun", def: "does the action (I, she, they)" },
        { term: "object pronoun", def: "receives the action (me, her, them)" },
        { term: "possessive pronoun", def: "shows ownership, no apostrophe (mine, hers)" },
        { term: "reflexive pronoun", def: "refers back to the subject (myself, himself)" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: PronounsDemo,
      worked: {
        question: "Spot the error: “The teacher gave the prize to Sam and I.”",
        fastMethod: 'Remove "Sam and" to test it: "gave the prize to I" sounds wrong — it should be "me", an object pronoun.',
        steps: [
          "“Sam and I” follows the preposition “to”, so it needs an object pronoun.",
          "Test by removing “Sam and”: “gave the prize to I” sounds clearly wrong.",
          "The object pronoun is “me”, not “I”.",
          "Corrected: “The teacher gave the prize to Sam and me.”",
        ],
        answer: "The error is <b>I</b> — it should be <b>me</b>.",
      },
      selfCheck: { prompt: "True or false: “its” with no apostrophe is a possessive pronoun.", answer: "<b>True</b> — “its” shows ownership (the dog wagged its tail). “It’s” with an apostrophe means “it is”." },
      kind: "click-error",
      questions: [
        {
          id: "pro-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Between", "you", "and", "I,", "this", "cake", "is", "delicious."],
          errorIdx: 3,
          correction: '"between" is a preposition and needs an object pronoun after it — "I" should be "me": between you and me.',
          hint: "Check the pronoun right after the preposition “between”.",
        },
        {
          id: "pro-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "dog", "wagged", "it's", "tail", "when", "we", "came", "home."],
          errorIdx: 3,
          correction: '"it\'s" (with an apostrophe) means "it is" — the possessive form needed here has no apostrophe: its tail.',
          hint: "Check whether the word shows ownership or is short for “it is”.",
        },
        {
          id: "pro-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["I", "hurt", "myself", "climbing", "the", "wall,", "but", "him", "was", "fine."],
          errorIdx: 7,
          correction: '"him" cannot be the subject of "was fine" — it needs the subject pronoun "he": but he was fine.',
          hint: "Find the pronoun acting as the subject of the second part of the sentence.",
        },
      ],
      mistakes: [
        "Using “me and [name]” or “[name] and I” as a subject/object without testing which pronoun sounds right on its own.",
        "Mixing up “it’s” (it is) with “its” (belonging to it) — possessive pronouns never take an apostrophe.",
      ],
      examTip: "Remove the other person from the sentence and read the pronoun on its own — “me went” and “gave it to I” both sound instantly wrong.",
      searchTerms: ["pronoun", "subject pronoun", "object pronoun", "possessive", "reflexive", "its", "it's"],
    },
    {
      id: "prepositions",
      title: "Prepositions",
      tier: "Standard",
      objective: "Choose the correct preposition to show position, direction, or relationship, and spot when the wrong one has been used.",
      whyMatters: "preposition errors are a favourite “complete the sentence” trap because several options can look plausible until you picture the scene precisely.",
      conceptTitle: "What is a preposition?",
      conceptBullets: [
        'A <b style="color:#C9A24B">preposition</b> shows how a noun relates to another word — usually position, direction or time.',
        "Position: <i>in</i>, <i>on</i>, <i>under</i>, <i>between</i>, <i>behind</i>.",
        "Direction: <i>into</i>, <i>onto</i>, <i>towards</i>, <i>through</i>.",
        "Time: <i>at</i>, <i>in</i>, <i>on</i>, <i>during</i>, <i>since</i>.",
        "The right preposition depends on the exact picture the sentence is describing — “in” and “on” are not interchangeable.",
      ],
      conceptNote: "<b>Tip:</b> picture the scene literally — a cat jumping “in” a table would be inside a hollow table, which is rarely what’s meant.",
      glossary: [
        { term: "preposition", def: "shows position, direction or time" },
        { term: "position preposition", def: "in, on, under, between" },
        { term: "direction preposition", def: "into, onto, towards, through" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: PrepositionsDemo,
      worked: {
        question: "Spot the error: “The plane landed in the runway just before sunset.”",
        fastMethod: 'Planes land on a surface, not inside it — "in" should be "on".',
        steps: [
          "Picture the scene: a plane touching down on a flat runway surface.",
          "“In” suggests being enclosed inside something, which doesn’t match landing on a surface.",
          "“On” is the correct preposition for something resting on a surface.",
          "Corrected: “The plane landed on the runway…”",
        ],
        answer: "The error is <b>in</b> — it should be <b>on</b>.",
      },
      selfCheck: { prompt: "Which preposition fits: “the cat is hiding ___ the sofa and the wall”?", answer: "<b>Between</b> — it shows a position with two things on either side." },
      kind: "click-error",
      questions: [
        {
          id: "prep-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["We", "arrived", "in", "the", "station", "just", "as", "the", "train", "was", "leaving."],
          errorIdx: 2,
          correction: '"arrived in the station" should be "arrived at the station" — "at" is used for a specific point or building.',
          hint: "Check the preposition describing where they arrived.",
        },
        {
          id: "prep-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "picture", "was", "hanging", "in", "the", "wall", "above", "the", "fireplace."],
          errorIdx: 4,
          correction: '"hanging in the wall" suggests it\'s embedded inside the wall — the correct preposition is "on": hanging on the wall.',
          hint: "Picture exactly where the picture is attached.",
        },
        {
          id: "prep-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["School", "starts", "in", "nine", "o’clock", "every", "morning."],
          errorIdx: 2,
          correction: '"in nine o’clock" is wrong for a precise clock time — the correct preposition is "at": at nine o’clock.',
          hint: "Precise clock times use a specific time-preposition, different from days or months.",
        },
      ],
      mistakes: [
        "Confusing “in” (enclosed within) and “on” (resting on a surface) — always picture the scene literally.",
        "Using “in” for a precise clock time instead of “at” (at nine o’clock, not in nine o’clock).",
      ],
      examTip: "If a preposition sentence feels 50/50, picture the scene as a photograph — the wrong preposition usually creates an image that doesn’t make sense.",
      searchTerms: ["preposition", "in", "on", "at", "position", "direction"],
    },
    {
      id: "conjunctions",
      title: "Conjunctions: Coordinating vs. Subordinating",
      tier: "Standard",
      objective: "Distinguish coordinating from subordinating conjunctions and spot when the wrong one — or a redundant pair — has been used.",
      whyMatters: "conjunction errors, especially pairing two conjunctions that do the same job (“although…but”), are a classic “spot the mistake” trap.",
      conceptTitle: "What is a conjunction?",
      conceptBullets: [
        'A <b style="color:#C9A24B">conjunction</b> joins words, phrases or clauses together.',
        '<b>Coordinating conjunctions</b> (FANBOYS: for, and, nor, but, or, yet, so) join two equal ideas.',
        "<b>Subordinating conjunctions</b> (although, because, since, if, when) join a main clause to a dependent clause.",
        "A subordinating conjunction already signals contrast or cause on its own — pairing it with a coordinating conjunction that repeats the job (e.g. “although…but”) is redundant.",
      ],
      conceptNote: "<b>Common mistake:</b> using “although” and “but” in the same sentence — pick one, not both.",
      glossary: [
        { term: "coordinating conjunction", def: "joins two equal ideas (FANBOYS)" },
        { term: "subordinating conjunction", def: "joins a main and dependent clause" },
        { term: "clause", def: "a group of words with a subject and a verb" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: ConjunctionsDemo,
      worked: {
        question: "Spot the error: “Because it was late, so we decided to head home.”",
        fastMethod: '"because" already explains the cause — pairing it with "so" repeats the job. Remove "so".',
        steps: [
          "“Because” is a subordinating conjunction that already signals cause and effect.",
          "“So” is a coordinating conjunction that also signals a result — using both is redundant.",
          "Only one conjunction is needed to link the clauses.",
          "Corrected: “Because it was late, we decided to head home.”",
        ],
        answer: "The error is the extra <b>so</b> — it should be removed.",
      },
      selfCheck: { prompt: "Is “but” a coordinating or subordinating conjunction?", answer: "<b>Coordinating</b> — it’s one of the FANBOYS conjunctions joining two equal ideas." },
      kind: "click-error",
      questions: [
        {
          id: "conj-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Even", "though", "she", "practised", "every", "day,", "but", "she", "still", "lost", "the", "match."],
          errorIdx: 6,
          correction: '"even though" already signals the contrast — the extra "but" is redundant and should be removed.',
          hint: "Two words in this sentence are both doing the job of showing contrast.",
        },
        {
          id: "conj-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["I", "like", "both", "swimming", "or", "cycling", "at", "the", "weekend."],
          errorIdx: 4,
          correction: '"both" pairs with "and", not "or": both swimming and cycling.',
          hint: "Check which conjunction correctly pairs with the word “both”.",
        },
        {
          id: "conj-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "was", "tired", "and", "she", "kept", "working", "until", "the", "project", "was", "finished."],
          errorIdx: 3,
          correction: '"and" simply adds ideas, but the meaning here is a contrast — the correct conjunction is "but": tired but she kept working.',
          hint: "Think about whether the two halves of the sentence agree or contrast with each other.",
        },
      ],
      mistakes: [
        "Pairing a subordinating conjunction with a coordinating one that repeats its job (“although…but”, “because…so”).",
        "Using “or” after “both”, or “nor” after “either” — correlative conjunctions must be paired correctly (both…and, either…or).",
      ],
      examTip: "If a sentence has two words that both seem to be doing the same linking job, one of them is very likely the error.",
      searchTerms: ["conjunction", "coordinating conjunction", "subordinating conjunction", "fanboys", "although", "but"],
    },
    {
      id: "determiners",
      title: "Determiners: a/an/the Errors",
      tier: "Foundation",
      objective: "Choose correctly between “a”, “an” and “the”, based on sound and specificity.",
      whyMatters: "a/an errors are one of the easiest marks to lose on a rushed paper — the rule is simple but easy to overlook under time pressure.",
      conceptTitle: "What is a determiner?",
      conceptBullets: [
        'A <b style="color:#C9A24B">determiner</b> comes before a noun to show which one, or how many, you mean.',
        'Use <b>"a"</b> before a word that starts with a consonant <i>sound</i>: a dog, a university (starts with a "yoo" sound).',
        'Use <b>"an"</b> before a word that starts with a vowel <i>sound</i>: an apple, an hour (the "h" is silent).',
        'Use <b>"the"</b> when you mean one specific thing the reader already knows about.',
      ],
      conceptNote: "<b>Remember:</b> it’s the sound that matters, not the letter — “a university” (sounds like “yoo”) but “an umbrella” (sounds like “uh”).",
      glossary: [
        { term: "determiner", def: "a word that introduces a noun (a, an, the)" },
        { term: "indefinite article", def: "a or an — any one example" },
        { term: "definite article", def: "the — one specific example" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: DeterminersDemo,
      worked: {
        question: "Spot the error: “It took an hour to finish a essay for homework.”",
        fastMethod: '"essay" starts with a vowel sound, so it needs "an", not "a": an essay.',
        steps: [
          "Check each determiner against the sound of the word that follows it.",
          "“An hour” is correct — the “h” is silent, so “hour” starts with a vowel sound.",
          "“A essay” is wrong — “essay” starts with a vowel sound and needs “an”.",
          "Corrected: “…a essay” becomes “…an essay”.",
        ],
        answer: "The error is <b>a</b> (before essay) — it should be <b>an</b>.",
      },
      selfCheck: { prompt: "Which is correct: “a honest mistake” or “an honest mistake”?", answer: '<b>"An honest mistake"</b> — the "h" in "honest" is silent, so the word starts with a vowel sound.' },
      kind: "click-error",
      questions: [
        {
          id: "det-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "is", "training", "to", "become", "an", "doctor", "at", "the", "hospital."],
          errorIdx: 5,
          correction: '"doctor" starts with a consonant sound, so it needs "a", not "an": a doctor.',
          hint: "Say the word right after the gap out loud — does it start with a vowel sound?",
        },
        {
          id: "det-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["We", "waited", "for", "a", "hour", "before", "the", "shop", "finally", "opened."],
          errorIdx: 3,
          correction: '"hour" has a silent "h", so it starts with a vowel sound and needs "an": an hour.',
          hint: "The letter at the start of this word is silent — focus on the sound, not the spelling.",
        },
        {
          id: "det-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["He", "gave", "a", "excellent", "speech", "at", "the", "prize-giving."],
          errorIdx: 2,
          correction: '"excellent" starts with a vowel sound, so it needs "an", not "a": an excellent speech.',
          hint: "Check the sound of the word immediately following the determiner.",
        },
      ],
      mistakes: [
        "Choosing a/an based on the spelling of the next word instead of its sound (e.g. “a hour” instead of “an hour”).",
        "Forgetting that words like “university” and “useful” start with a consonant sound (“yoo”) despite starting with the vowel letter U.",
      ],
      examTip: "Always say the next word aloud in your head before choosing a or an — sound beats spelling every time.",
      searchTerms: ["determiner", "a", "an", "the", "article", "vowel sound"],
    },
    {
      id: "confusing-parts-of-speech",
      title: "Confusing One Part of Speech for Another",
      tier: "Extension",
      objective: "Recognise when a word from one part of speech (often an adjective) has been wrongly used in the role of another (often an adverb).",
      whyMatters: "this is the error type behind many of the trickiest “spot the mistake” questions — the word itself is spelled correctly, but it’s doing the wrong job.",
      conceptTitle: "Same word, wrong job",
      conceptBullets: [
        "A word can be spelled perfectly correctly and still be the error — because it’s being used as the wrong part of speech.",
        "The most common swap: an <b>adjective</b> used where an <b>adverb</b> is needed (describing an action instead of a noun).",
        "Other swaps to watch for: a noun used as a verb, or a verb form used as an adjective.",
        "To catch this error type, ask: “what is this word attached to — a thing, or an action?”",
      ],
      conceptNote: "<b>Test:</b> if the describing word is attached to a verb (an action), it needs the adverb form, even if the adjective form “looks” fine on its own.",
      glossary: [
        { term: "part of speech", def: "the grammatical role a word plays" },
        { term: "adjective", def: "describes a noun" },
        { term: "adverb", def: "describes a verb, adjective or adverb" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: ConfusedPartsDemo,
      worked: {
        question: "Spot the error: “The team played bad in the second half.”",
        fastMethod: '"bad" describes how the team played (an action), so it needs the adverb "badly".',
        steps: [
          "Identify what “bad” is attached to — the verb “played”, an action.",
          "Words describing an action need the adverb form.",
          "“Bad” is an adjective (a bad day); “badly” is the adverb.",
          "Corrected: “The team played badly in the second half.”",
        ],
        answer: "The error is <b>bad</b> — it should be <b>badly</b>.",
      },
      selfCheck: { prompt: "In “this cake tastes good”, is “good” correct, even though it doesn’t end in -ly?", answer: "<b>Yes</b> — “tastes” is a linking verb here, describing the cake itself, so the adjective “good” is correct (not “well”)." },
      kind: "click-error",
      questions: [
        {
          id: "confuse-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "singer", "performed", "brilliant", "in", "front", "of", "the", "whole", "school."],
          errorIdx: 3,
          correction: '"brilliant" describes how the singer performed (an action), so it needs the adverb "brilliantly".',
          hint: "Ask what the describing word is attached to — the singer, or the performing.",
        },
        {
          id: "confuse-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["He", "shut", "the", "door", "sudden", "and", "walked", "away."],
          errorIdx: 4,
          correction: '"sudden" describes how he shut the door (an action), so it needs the adverb "suddenly".',
          hint: "Check whether the describing word is attached to a noun or a verb.",
        },
        {
          id: "confuse-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "instructions", "were", "written", "clear", "so", "everyone", "understood", "them."],
          errorIdx: 4,
          correction: '"clear" describes how the instructions were written (an action), so it needs the adverb "clearly".',
          hint: "The describing word here is attached to a past-tense verb, not directly to a noun.",
        },
      ],
      mistakes: [
        "Assuming a word is correct just because it’s spelled right — the error is about its job in the sentence, not its spelling.",
        "Missing adjective-for-adverb swaps after linking verbs like “look”, “taste” and “seem”, where the adjective is often actually correct.",
      ],
      examTip: "This error type hides in plain sight because the word is spelled correctly — always ask “what is this word describing?” before moving on.",
      searchTerms: ["parts of speech", "adjective", "adverb", "wrong word class", "confusing words"],
    },
    {
      id: "odd-one-out",
      title: "Spotting the Odd One Out",
      tier: "Extension",
      objective: "Compare a group of words to identify the one that belongs to a different part of speech, even when surface features (like spelling patterns) suggest otherwise.",
      whyMatters: "“odd one out” questions test whether you understand a word’s true grammatical role, not just a spelling pattern — a favourite CSSE-style trap.",
      conceptTitle: "Looks can be deceiving",
      conceptBullets: [
        "Some words share a spelling pattern (like ending in -ly) but belong to different parts of speech.",
        "Most -ly words are adverbs (quickly, quietly), but some are adjectives (friendly, lovely, silly, lonely).",
        "To find the true odd one out, check each word’s job in a sentence, not just how it’s spelled.",
        "This skill combines everything from this topic: knowing nouns, verbs, adjectives and adverbs well enough to classify a word instantly.",
      ],
      conceptNote: "<b>Trick to remember:</b> “friendly” answers “what kind?” (a friendly dog) like an adjective, not “how?” like a true -ly adverb.",
      glossary: [
        { term: "word class", def: "another name for part of speech" },
        { term: "-ly adjective", def: "an adjective that happens to end in -ly (friendly, lovely)" },
        { term: "classification", def: "sorting words by their grammatical role" },
      ],
      diagramLabel: "Interactive · Click the Odd One Out",
      Diagram: OddOneOutDemo,
      worked: {
        question: "Which is the odd one out: happily, sadly, lonely, quietly?",
        fastMethod: '"lonely" describes a noun (a lonely child), so it’s an adjective — the other three describe actions and are true adverbs.',
        steps: [
          "Test each word in a sentence: “she smiled happily”, “he spoke sadly”, “they waited quietly” — all describe actions.",
          "“a lonely child” — “lonely” describes the noun “child”, not an action.",
          "Three of the four words are adverbs; “lonely” is an adjective despite its -ly ending.",
          "“Lonely” is the odd one out.",
        ],
        answer: "The odd one out is <b>lonely</b> — it’s an adjective, not an adverb.",
      },
      selfCheck: { prompt: "Which is the odd one out: bravely, ugly, calmly, gently?", answer: "<b>Ugly</b> — it describes a noun (an ugly vase) and is an adjective; the others describe actions and are adverbs." },
      kind: "click-error",
      questions: [
        {
          id: "odd-q1",
          instruction: "Four of these five words are the same part of speech. Click the odd one out.",
          words: ["silently,", "boldly,", "elderly,", "swiftly,", "gladly."],
          errorIdx: 2,
          correction: '"elderly" describes a noun (an elderly man), so it’s an adjective — the odd one out among these adverbs.',
          hint: "One of these words describes a person, not an action.",
        },
        {
          id: "odd-q2",
          instruction: "Four of these five words are the same part of speech. Click the odd one out.",
          words: ["run", "jump", "table", "swim", "dance"],
          errorIdx: 2,
          correction: '"table" is a noun — the other four words are all verbs describing an action.',
          hint: "One word names a thing rather than an action.",
        },
        {
          id: "odd-q3",
          instruction: "Four of these five words are the same part of speech. Click the odd one out.",
          words: ["quick", "bright", "lovely", "quickly", "kind"],
          errorIdx: 3,
          correction: '"quickly" is an adverb — the other four (quick, bright, lovely, kind) are all adjectives that describe a noun.',
          hint: "Four of these words could all sit directly in front of a noun; one cannot.",
        },
      ],
      mistakes: [
        "Sorting words by spelling pattern alone (e.g. “ends in -ly”) instead of checking what each word actually describes.",
        "Rushing past the instruction and treating this as a normal “find the error” question rather than a “find the different one” question.",
      ],
      examTip: "Build a one-word test sentence for each option in your head — the odd one out will refuse to fit the same sentence pattern as the others.",
      searchTerms: ["odd one out", "word class", "part of speech", "classify", "adverb", "adjective"],
    },
  ],
};
