import type { TopicContent } from "../types";
import { PhysicsParticleModelOfMatterDensityAndMassCalculationsDemo, PhysicsParticleModelOfMatterChangesOfStateAndSpecificLatentHeatDemo, PhysicsParticleModelOfMatterParticleMotionInGasesPressureAndInternalEnergyDemo } from "../notes-diagrams/physics-particle-model-of-matter-demos";

export const physicsParticleModelOfMatterTopic: TopicContent = {
  slug: "physics-particle-model-of-matter",
  subject: "Physics",
  subjectSlug: "gcse-science/physics",
  title: "GCSE Physics: Particle Model of Matter",
  description: "AQA GCSE Physics — Particle Model of Matter. Covers density calculations, changes of state and specific latent heat, particle motion in gases and pressure, and internal energy.",
  glyphs: ["⚡","🔭","🧲","🌀"],
  subtopics: [
    {
      id: "density-and-mass-calculations",
      title: "Density and mass calculations",
      tier: "Foundation",
      objective: "Calculate density, mass or volume of a substance using the formula ρ = m/V.",
      whyMatters: "Density links the particle model to measurable quantities and appears in many AQA exam questions on solids and liquids.",
      conceptTitle: "Understanding density",
      conceptBullets: ["The <b style=\"color:#C9A24B\">density</b> of a material is its mass per unit volume and is expressed in kg m⁻³ or g cm⁻³.","The formula <b style=\"color:#C9A24B\">ρ = m ÷ V</b> can be rearranged to find mass or volume when the other two values are known.","When a substance changes state its <b style=\"color:#C9A24B\">mass remains constant</b>, so density changes only because volume changes.","A <b style=\"color:#C9A24B\">solid</b> usually has a higher density than its liquid or gaseous form because particles are packed more closely."],
      conceptNote: "<b>Tip:</b> Keep track of units; convert cm³ to m³ or vice‑versa before using the density formula.",
      glossary: [{"term":"density","def":"mass per unit volume of a material."},{"term":"mass","def":"amount of matter in an object, measured in kilograms or grams."},{"term":"volume","def":"space occupied by an object, measured in cubic metres or cubic centimetres."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsParticleModelOfMatterDensityAndMassCalculationsDemo,
      worked: {"question":"A metal block has a mass of 540 g and a volume of 0.0002 m³. Calculate its density in kg m⁻³.","fastMethod":"Convert mass to kg then divide by volume.","steps":["Convert 540 g to kg: 0.540 kg.","Use ρ = m ÷ V.","ρ = 0.540 kg ÷ 0.0002 m³.","ρ = 2700 kg m⁻³."],"answer":"2700 kg m⁻³"},
      selfCheck: {"prompt":"True or false: If the volume of a substance doubles while its mass stays the same, its density halves.","answer":"True – density is inversely proportional to volume when mass is constant."},
      questions: [{"id":"density-and-mass-calculations-q1","prompt":"State the units used for density in the AQA GCSE.","accept":["kg m^-3","kg/m^3","g cm^-3","g/cm^3"],"hint":"Think of mass per unit volume."},{"id":"density-and-mass-calculations-q2","prompt":"A liquid has a density of 0.8 g cm⁻³ and a volume of 250 cm³. What is its mass?","accept":["200 g","0.2 kg"],"hint":"Use m = ρ × V."},{"id":"density-and-mass-calculations-q3","prompt":"Why does the density of ice differ from liquid water?","accept":["particles are further apart in ice","ice expands on freezing"],"hint":"Consider particle arrangement in the solid state."}],
      mistakes: ["Using cm³ with kg without converting to m³ first.","Assuming mass changes when a substance melts."],
      examTip: "Write the rearranged density formula on the margin before starting the calculation to avoid algebra errors.",
      searchTerms: ["density formula","mass volume relationship","gcse density units","calculate density","density exam tip"],
    },
    {
      id: "changes-of-state-and-specific-latent-heat",
      title: "Changes of state and specific latent heat",
      tier: "Standard",
      objective: "Use Q = m L to calculate energy required for melting or boiling and explain why temperature stays constant during a phase change.",
      whyMatters: "Specific latent heat questions are common in AQA papers and test understanding of energy transfer in the particle model.",
      conceptTitle: "Energy and phase changes",
      conceptBullets: ["During a phase change the <b style=\"color:#C9A24B\">temperature remains constant</b> because added energy is used to overcome intermolecular forces.","The energy required is given by <b style=\"color:#C9A24B\">Q = m L</b>, where L is the specific latent heat of fusion or vaporisation.","<b style=\"color:#C9A24B\">Latent heat of fusion</b> applies to melting/freezing, while <b style=\"color:#C9A24B\">latent heat of vaporisation</b> applies to boiling/condensation.","The particle model shows that in a solid particles vibrate, in a liquid they move past each other, and in a gas they travel freely; energy input changes these motions.","Energy absorbed or released during a phase change does not change the average kinetic energy of particles, hence no temperature change."],
      conceptNote: "<b>Tip:</b> Keep the correct L value (fusion vs vaporisation) separate in a quick reference table.",
      glossary: [{"term":"specific latent heat","def":"Energy per kilogram required for a phase change at constant temperature."},{"term":"fusion","def":"The process of melting; solid to liquid."},{"term":"vaporisation","def":"The process of boiling; liquid to gas."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: PhysicsParticleModelOfMatterChangesOfStateAndSpecificLatentHeatDemo,
      worked: {"question":"How much energy is needed to melt 250 g of ice at 0 °C? (L_fusion = 334 kJ kg⁻¹)","fastMethod":"Convert mass to kg then multiply by L.","steps":["Convert 250 g to kg: 0.250 kg.","Q = m L = 0.250 kg × 334 kJ kg⁻¹.","Q = 83.5 kJ."],"answer":"83.5 kJ"},
      selfCheck: {"prompt":"True or false: The temperature of water rises while it is boiling at 100 °C.","answer":"False – temperature stays at 100 °C until all water has vaporised."},
      questions: [{"id":"changes-of-state-and-specific-latent-heat-q1","prompt":"Define specific latent heat.","accept":["energy per kilogram for a phase change","energy required to change state per unit mass"],"hint":"Think of energy needed without temperature change."},{"id":"changes-of-state-and-specific-latent-heat-q2","prompt":"What is the term for the energy released when steam condenses?","accept":["latent heat of condensation","latent heat of vaporisation released"],"hint":"It's the reverse of vaporisation."},{"id":"changes-of-state-and-specific-latent-heat-q3","prompt":"Calculate the energy released when 0.5 kg of steam at 100 °C condenses to water (L_vap = 2260 kJ kg⁻¹).","accept":["1130 kJ","1.13 × 10^3 kJ"],"hint":"Use Q = m L, note condensation releases energy."}],
      mistakes: ["Using the latent heat of fusion when the question is about boiling.","Forgetting to convert grams to kilograms before using Q = m L."],
      examTip: "Write the appropriate L value (fusion or vaporisation) next to the question stem to avoid mixing them up.",
      searchTerms: ["latent heat formula","melting energy gcse","boiling latent heat","phase change temperature","gcse specific latent heat"],
    },
    {
      id: "particle-motion-in-gases-pressure-and-internal-energy",
      title: "Particle motion in gases, pressure and internal energy",
      tier: "Extension",
      objective: "Explain how particle collisions produce pressure and relate internal energy to temperature and kinetic energy of gas particles.",
      whyMatters: "Understanding pressure links the particle model to the ideal gas equation, a high‑scoring AQA topic that integrates several concepts.",
      conceptTitle: "Gas particles and pressure",
      conceptBullets: ["Gas particles move rapidly in straight lines and collide elastically with container walls, creating <b style=\"color:#C9A24B\">pressure</b>.","Pressure is the <b style=\"color:#C9A24B\">force per unit area</b> exerted by these collisions; more frequent or harder collisions increase pressure.","The <b style=\"color:#C9A24B\">average kinetic energy</b> of gas particles is directly proportional to the absolute temperature (KE ∝ T).","Internal energy of a gas is the total kinetic energy of all its particles; for an ideal gas it depends only on temperature, not on volume or pressure.","Increasing temperature raises particle speed, leading to higher pressure if volume is constant (Gay‑Lussac’s law)."],
      conceptNote: "<b>Tip:</b> Visualise particles as tiny billiard balls; each bounce on the wall contributes a tiny force.",
      glossary: [{"term":"pressure","def":"Force exerted per unit area by gas particles on container walls."},{"term":"internal energy","def":"Total kinetic energy of all particles in a substance."},{"term":"kinetic energy","def":"Energy of motion; for particles, ½ mv²."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsParticleModelOfMatterParticleMotionInGasesPressureAndInternalEnergyDemo,
      worked: {"question":"A sealed container holds 0.020 mol of an ideal gas at 300 K. Calculate the internal energy (U) of the gas. (Use U = 3/2 nRT, R = 8.31 J mol⁻¹ K⁻¹)","fastMethod":"Plug values directly into U = 3/2 nRT.","steps":["U = 3/2 × n × R × T.","U = 1.5 × 0.020 mol × 8.31 J mol⁻¹ K⁻¹ × 300 K.","U = 1.5 × 0.020 × 8.31 × 300 = 74.8 J (≈ 75 J)."],"answer":"≈ 75 J"},
      selfCheck: {"prompt":"True or false: Doubling the temperature of an ideal gas (in Kelvin) at constant volume doubles its pressure.","answer":"True – pressure is directly proportional to absolute temperature when volume is fixed."},
      questions: [{"id":"particle-motion-in-gases-pressure-and-internal-energy-q1","prompt":"What causes pressure in a gas according to the particle model?","accept":["particle collisions with walls","collisions of gas particles with container"],"hint":"Think about the direction of motion."},{"id":"particle-motion-in-gases-pressure-and-internal-energy-q2","prompt":"State the relationship between internal energy and temperature for an ideal gas.","accept":["U ∝ T","internal energy increases with temperature"],"hint":"Only temperature matters for an ideal gas."},{"id":"particle-motion-in-gases-pressure-and-internal-energy-q3","prompt":"If the volume of a gas is halved while temperature stays the same, what happens to the pressure?","accept":["pressure doubles","pressure increases by factor of 2"],"hint":"Use Boyle’s law."}],
      mistakes: ["Confusing absolute temperature (K) with Celsius when applying P ∝ T.","Including potential energy in internal energy for an ideal gas."],
      examTip: "When using PV = nRT, always check that temperature is in Kelvin and pressure in Pa to avoid unit errors.",
      searchTerms: ["gas pressure particle model","internal energy gcse","kinetic energy temperature relation","ideal gas equation","gay lussac law"],
    }
  ],
};
