import type { TopicContent } from "../types";
import { PhysicsElectricityCurrentPotentialDifferenceAndResistanceDemo, PhysicsElectricitySeriesAndParallelCircuitsDemo, PhysicsElectricityMainsElectricityPowerAndTheNationalGridDemo } from "../notes-diagrams/physics-electricity-demos";

export const physicsElectricityTopic: TopicContent = {
  slug: "physics-electricity",
  subject: "Physics",
  subjectSlug: "gcse-science/physics",
  title: "GCSE Physics: Electricity",
  description: "AQA GCSE Physics — Electricity. Covers current, potential difference and resistance (V=IR), series and parallel circuits, mains electricity (AC/DC, UK plug wiring), power calculations (P=IV), and the National Grid.",
  glyphs: ["⚡","🔭","🧲","🌀"],
  subtopics: [
    {
      id: "current-potential-difference-and-resistance",
      title: "Current, potential difference and resistance",
      tier: "Foundation",
      objective: "Calculate current, voltage and resistance using V=IR and interpret simple circuit diagrams.",
      whyMatters: "These are core concepts tested in every GCSE physics paper and form the basis for understanding all electrical phenomena.",
      conceptTitle: "Ohm’s law and basic quantities",
      conceptBullets: ["The <b style=\"color:#C9A24B\">current</b> I is the rate of charge flow, measured in amperes (A).","The <b style=\"color:#C9A24B\">potential difference</b> V drives the current and is measured in volts (V).","The <b style=\"color:#C9A24B\">resistance</b> R opposes current flow, measured in ohms (Ω).","<b style=\"color:#C9A24B\">Ohm’s law</b> relates them: V = I × R."],
      conceptNote: "<b>Tip:</b> Rearrange V=IR quickly: I = V/R or R = V/I, and keep the units straight.",
      glossary: [{"term":"current","def":"Flow of electric charge, measured in amperes."},{"term":"potential difference","def":"Energy per unit charge between two points, measured in volts."},{"term":"resistance","def":"Opposition to current flow, measured in ohms."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsElectricityCurrentPotentialDifferenceAndResistanceDemo,
      worked: {"question":"A lamp is connected to a 12 V supply and draws a current of 0.5 A. What is the resistance of the lamp?","fastMethod":"Use R = V ÷ I.","steps":["Identify V = 12 V and I = 0.5 A.","Apply R = V ÷ I.","Calculate 12 ÷ 0.5 = 24.","State R = 24 Ω."],"answer":"24 Ω"},
      selfCheck: {"prompt":"True or false: If the voltage across a resistor is doubled, the current also doubles (resistance unchanged).","answer":"True – because I = V/R."},
      questions: [{"id":"current-potential-difference-and-resistance-q1","prompt":"What is the unit of resistance?","accept":["ohm","Ω"],"hint":"Look at the symbol on the circuit diagram."},{"id":"current-potential-difference-and-resistance-q2","prompt":"A circuit has a potential difference of 9 V and a resistance of 3 Ω. What is the current?","accept":["3 a","3 a","3 amperes"],"hint":"Use I = V ÷ R."},{"id":"current-potential-difference-and-resistance-q3","prompt":"Name the law that relates V, I and R.","accept":["ohm's law","ohms law"],"hint":"It is named after a German physicist."}],
      mistakes: ["Confusing voltage with current and swapping the symbols V and I.","Forgetting to convert units (e.g., mA to A) before using V=IR."],
      examTip: "Always write the rearranged form of V=IR you need before plugging numbers – it saves time and avoids algebra errors.",
      searchTerms: ["ohms law","current voltage resistance","v=ir example","calculate resistance","gcse electricity basics"],
    },
    {
      id: "series-and-parallel-circuits",
      title: "Series and parallel circuits",
      tier: "Standard",
      objective: "Analyse series and parallel circuits to find total resistance, current distribution and voltage drops.",
      whyMatters: "Understanding circuit configuration is essential for many exam questions and for interpreting real‑world wiring diagrams.",
      conceptTitle: "How components combine",
      conceptBullets: ["In a <b style=\"color:#C9A24B\">series</b> circuit the same current flows through each component.","Total resistance in series is the sum: Rₜ = R₁ + R₂ + ….","In a <b style=\"color:#C9A24B\">parallel</b> circuit the voltage across each branch is the same.","Total resistance in parallel is given by 1/Rₜ = 1/R₁ + 1/R₂ + …."],
      conceptNote: "<b>Tip:</b> Sketch a quick diagram and label I and V for each branch before calculating.",
      glossary: [{"term":"series circuit","def":"Components connected end‑to‑end, same current flows through all."},{"term":"parallel circuit","def":"Components connected across the same two points, same voltage across each."},{"term":"total resistance","def":"Equivalent resistance of the whole circuit."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: PhysicsElectricitySeriesAndParallelCircuitsDemo,
      worked: {"question":"Three resistors of 2 Ω, 3 Ω and 6 Ω are connected in parallel across a 12 V supply. Find the total current drawn from the supply.","fastMethod":"First find Rₜ using 1/Rₜ = Σ1/R, then I = V ÷ Rₜ.","steps":["Calculate 1/Rₜ = 1/2 + 1/3 + 1/6 = 0.5 + 0.333 + 0.167 = 1.0.","Thus Rₜ = 1 Ω.","Use I = V ÷ Rₜ = 12 V ÷ 1 Ω.","I = 12 A."],"answer":"12 A"},
      selfCheck: {"prompt":"True or false: In a series circuit the total resistance is always less than the smallest individual resistor.","answer":"False – it is the sum of all resistances."},
      questions: [{"id":"series-and-parallel-circuits-q1","prompt":"Two resistors, 4 Ω and 6 Ω, are in series. What is the total resistance?","accept":["10 Ω","10 ohm","10"],"hint":"Add them."},{"id":"series-and-parallel-circuits-q2","prompt":"If a 5 Ω resistor is placed in parallel with a 10 Ω resistor, what is the equivalent resistance (to 1 dp)?","accept":["3.3 Ω","3.33 ohm","3.33"],"hint":"Use 1/Rₜ = 1/5 + 1/10."},{"id":"series-and-parallel-circuits-q3","prompt":"In a series circuit the current is 2 A. What is the voltage across a 3 Ω resistor?","accept":["6 V","6 volts"],"hint":"V = I × R."}],
      mistakes: ["Treating parallel branches as if they share the same current instead of the same voltage.","Using the series formula for resistance on a parallel network."],
      examTip: "When a diagram shows both series and parallel parts, reduce one section at a time to a single equivalent resistor before tackling the whole circuit.",
      searchTerms: ["series parallel resistance","gcse circuit analysis","total resistance parallel","voltage drop series","gcse electricity worked example"],
    },
    {
      id: "mains-electricity-power-and-the-national-grid",
      title: "Mains electricity, power and the National Grid",
      tier: "Extension",
      objective: "Explain AC mains supply, calculate electrical power, and describe how the National Grid delivers electricity safely.",
      whyMatters: "These topics appear in higher‑tier papers and in practical questions about household safety and energy consumption.",
      conceptTitle: "From generation to the plug",
      conceptBullets: ["UK mains supply is <b style=\"color:#C9A24B\">alternating current (AC)</b> at 230 V, 50 Hz.","A UK plug has a live (brown), neutral (blue) and earth (green‑yellow) wire, each with specific safety functions.","Electrical <b style=\"color:#C9A24B\">power</b> is P = V × I; for AC the RMS values are used.","The <b style=\"color:#C9A24B\">National Grid</b> transmits high‑voltage electricity, steps it down via transformers to safe domestic levels."],
      conceptNote: "<b>Tip:</b> When calculating power from mains, always use RMS voltage (230 V) not peak voltage.",
      glossary: [{"term":"alternating current","def":"Current that changes direction periodically, characterised by frequency."},{"term":"RMS voltage","def":"Root‑mean‑square value; for sinusoidal AC it equals the DC equivalent voltage."},{"term":"transformer","def":"Device that changes voltage levels by electromagnetic induction."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsElectricityMainsElectricityPowerAndTheNationalGridDemo,
      worked: {"question":"A kettle rated at 3 kW is connected to a 230 V mains supply. What current does it draw?","fastMethod":"Rearrange P = V × I to I = P ÷ V.","steps":["Convert power: 3 kW = 3000 W.","I = 3000 W ÷ 230 V.","I ≈ 13.04 A.","Round to 13 A (typical UK fuse rating)."],"answer":"≈13 A"},
      selfCheck: {"prompt":"True or false: The earth wire in a UK plug carries current during normal operation.","answer":"False – it only carries current if a fault occurs."},
      questions: [{"id":"mains-electricity-power-and-the-national-grid-q1","prompt":"What does RMS stand for in electrical terms?","accept":["root mean square","root-mean-square"],"hint":"It is a type of average."},{"id":"mains-electricity-power-and-the-national-grid-q2","prompt":"If a 60 W light bulb is connected to the UK mains, what is the current drawn?","accept":["0.26 a","0.26 a","0.26 amperes"],"hint":"Use I = P ÷ V."},{"id":"mains-electricity-power-and-the-national-grid-q3","prompt":"Why are high voltages used for transmission on the National Grid?","accept":["reduce current","lower i²r losses","minimise losses"],"hint":"Think about the power equation."}],
      mistakes: ["Using peak voltage (≈325 V) instead of RMS 230 V in power calculations.","Assuming the earth wire always carries current."],
      examTip: "When a question gives power and voltage for a mains appliance, instantly write I = P ÷ V – this gives the current needed for safety/fuse checks.",
      searchTerms: ["uk mains voltage","ac power calculation","national grid explanation","gcse earth wire","rms vs peak voltage"],
    }
  ],
};
