import type { TopicContent } from "../types";
import { PhysicsEnergyEnergyStoresAndTransfersDemo, PhysicsEnergyCalculatingEnergyChangesDemo, PhysicsEnergyEnergyEfficiencyDissipationAndResourcesDemo } from "../notes-diagrams/physics-energy-demos";

export const physicsEnergyTopic: TopicContent = {
  slug: "physics-energy",
  subject: "Physics",
  subjectSlug: "gcse-science/physics",
  title: "GCSE Physics: Energy",
  description: "AQA GCSE Physics — Energy. Covers energy stores and transfers, kinetic/gravitational potential/elastic potential energy calculations, specific heat capacity, conservation of energy and dissipation, efficiency calculations, and renewable/non-renewable energy resources.",
  glyphs: ["⚡","🔭","🧲","🌀"],
  subtopics: [
    {
      id: "energy-stores-and-transfers",
      title: "Energy stores and transfers",
      tier: "Foundation",
      objective: "Identify common energy stores and describe how energy is transferred between them.",
      whyMatters: "Understanding stores and transfers underpins all later energy calculations and is frequently tested in multiple‑choice and short‑answer questions.",
      conceptTitle: "Energy stores and transfers",
      conceptBullets: ["The main <b style=\"color:#C9A24B\">energy stores</b> in GCSE physics are kinetic, gravitational potential, elastic potential and thermal (internal) energy.","Energy is transferred by <b style=\"color:#C9A24B\">work</b>, heat flow or radiation, each described by a simple formula.","When an object falls, <b style=\"color:#C9A24B\">gravitational potential energy</b> is converted into kinetic energy and some into thermal energy due to air resistance.","A stretched spring stores <b style=\"color:#C9A24B\">elastic potential energy</b> which is released as kinetic energy when the spring returns to its original shape."],
      conceptNote: "<b>Tip:</b> Draw a quick energy bar diagram for any situation – it helps visualise which stores increase or decrease.",
      glossary: [{"term":"energy store","def":"A form in which energy is held, e.g., kinetic or potential."},{"term":"work","def":"Energy transferred when a force moves an object through a distance (W = F × d)."},{"term":"heat flow","def":"Transfer of thermal energy from a hotter to a cooler body."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsEnergyEnergyStoresAndTransfersDemo,
      worked: {"question":"A 2 kg ball is dropped from a height of 5 m. Ignoring air resistance, calculate its speed just before it hits the ground.","fastMethod":"Use conservation of energy: mgh = ½ mv², solve for v.","steps":["Calculate initial gravitational PE: mgh = 2 × 9.8 × 5 = 98 J.","Set this equal to kinetic energy: ½ mv² = 98 J.","Solve for v: v = √(2 × 98 / 2) = √98 ≈ 9.9 m s⁻¹."],"answer":"v ≈ 9.9 m s⁻¹"},
      selfCheck: {"prompt":"True or false: When a spring is compressed, its elastic potential energy decreases.","answer":"False – compressing a spring stores elastic potential energy."},
      questions: [{"id":"energy-stores-and-transfers-q1","prompt":"Name the four main energy stores examined in GCSE physics.","accept":["kinetic, gravitational potential, elastic potential, thermal","kinetic, gravitational, elastic, thermal"],"hint":"Think of motion, height, springs and heat."},{"id":"energy-stores-and-transfers-q2","prompt":"What is the formula for work done when a constant force moves an object 3 m?","accept":["work = force × distance","w = f d"],"hint":"Use W = F × d."},{"id":"energy-stores-and-transfers-q3","prompt":"If a 0.5 kg object moves at 4 m s⁻¹, what is its kinetic energy?","accept":["4 j","4 joules"],"hint":"Ek = ½ mv²."}],
      mistakes: ["Confusing the direction of energy flow – forgetting that energy leaves one store and enters another.","Using the wrong symbol for spring constant (k) or mixing up m and g in formulas."],
      examTip: "When a question lists several processes, underline the word ‘converted’ to spot which energy store is increasing or decreasing.",
      searchTerms: ["energy stores","energy transfer GCSE","kinetic energy formula","gravitational potential energy","elastic potential energy"],
    },
    {
      id: "calculating-energy-changes",
      title: "Calculating energy changes",
      tier: "Standard",
      objective: "Perform calculations for kinetic, gravitational and elastic potential energy, and apply specific heat capacity.",
      whyMatters: "Accurate calculations are required in many exam questions, especially in the non‑multiple‑choice section where marks are awarded for method and correct units.",
      conceptTitle: "Energy change calculations",
      conceptBullets: ["Kinetic energy depends on <b style=\"color:#C9A24B\">mass and speed</b>; doubling the speed quadruples the energy.","Gravitational potential energy varies with <b style=\"color:#C9A24B\">mass, height and the local g‑value</b> (9.8 m s⁻²).","Elastic potential energy is stored in a spring and is calculated using <b style=\"color:#C9A24B\">spring constant and extension</b>.","Specific heat capacity links the amount of heat added to a substance with its <b style=\"color:#C9A24B\">mass and temperature change</b>."],
      conceptNote: "<b>Tip:</b> Keep a personal formula sheet; write each equation with its symbols and units for quick recall.",
      glossary: [{"term":"specific heat capacity","def":"Energy required to raise 1 kg of a substance by 1 °C (J kg⁻¹ °C⁻¹)."},{"term":"spring constant","def":"A measure of a spring's stiffness (N m⁻¹)."},{"term":"conservation of energy","def":"Total energy in an isolated system remains constant."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: PhysicsEnergyCalculatingEnergyChangesDemo,
      worked: {"question":"A 0.2 kg spring with k = 150 N m⁻¹ is compressed 0.05 m. Find the elastic potential energy stored.","fastMethod":"Apply Epe = ½ kx² directly.","steps":["Square the extension: x² = (0.05)² = 0.0025 m².","Multiply by k: 150 × 0.0025 = 0.375 J.","Take half: 0.5 × 0.375 = 0.1875 J."],"answer":"Epe = 0.19 J (to 2 sf)"},
      selfCheck: {"prompt":"True or false: Doubling the mass of an object while keeping speed constant doubles its kinetic energy.","answer":"True – Ek = ½ mv², so Ek is directly proportional to mass."},
      questions: [{"id":"calculating-energy-changes-q1","prompt":"Calculate the gravitational potential energy of a 3 kg mass lifted 2 m.","accept":["117.6 j","117.6 joules","118 j","118 joules"],"hint":"Use Epg = mgh with g = 9.8."},{"id":"calculating-energy-changes-q2","prompt":"A 500 g metal block (c = 900 J kg⁻¹ °C⁻¹) is heated from 20 °C to 70 °C. How much heat is added?","accept":["22500 j","22500 joules","22.5 kJ"],"hint":"Convert mass to kg and apply Q = mcΔT."},{"id":"calculating-energy-changes-q3","prompt":"If a car of mass 800 kg increases its speed from 5 m s⁻¹ to 15 m s⁻¹, what is the change in kinetic energy?","accept":["112000 j","112000 joules","1.12×10^5 j"],"hint":"Find final and initial Ek and subtract."}],
      mistakes: ["Leaving the ½ factor out of the kinetic or elastic energy formulas.","Mixing up ΔT (final‑initial) with the absolute temperature in the Q = mcΔT equation."],
      examTip: "Always write the units next to each number in your working; exam markers award marks for correct units as well as numbers.",
      searchTerms: ["gcse kinetic energy calculation","gravitational potential energy example","elastic potential energy formula","specific heat capacity problem","energy calculation tips"],
    },
    {
      id: "energy-efficiency-dissipation-and-resources",
      title: "Energy efficiency, dissipation and resources",
      tier: "Extension",
      objective: "Analyse energy efficiency, identify sources of loss, and compare renewable and non‑renewable energy resources.",
      whyMatters: "Higher‑tier questions test understanding of real‑world applications, efficiency calculations and the sustainability agenda, all of which appear in the written and practical papers.",
      conceptTitle: "Efficiency, dissipation and energy resources",
      conceptBullets: ["The <b style=\"color:#C9A24B\">efficiency</b> of a system is the ratio of useful output energy to input energy, expressed as a percentage.","Energy is <b style=\"color:#C9A24B\">dissipated</b> mainly as thermal energy due to friction, resistance or non‑ideal processes.","Renewable resources, such as <b style=\"color:#C9A24B\">solar, wind and tidal</b>, are naturally replenished on a human timescale.","Non‑renewable resources, like <b style=\"color:#C9A24B\">coal, oil and natural gas</b>, exist in finite quantities and release CO₂ when burned.","The <b style=\"color:#C9A24B\">energy density</b> of a fuel influences its suitability for transport or electricity generation."],
      conceptNote: "<b>Tip:</b> When comparing resources, create a two‑column table (renewable vs non‑renewable) and list key properties – this is quick to recall in exams.",
      glossary: [{"term":"efficiency","def":"Useful energy output ÷ total energy input × 100%."},{"term":"dissipation","def":"Loss of useful energy, usually as heat, due to non‑ideal processes."},{"term":"energy density","def":"Energy stored per unit mass or volume of a fuel."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsEnergyEnergyEfficiencyDissipationAndResourcesDemo,
      worked: {"question":"A 1500 W electric kettle heats 0.5 kg of water from 20 °C to 100 °C. Assuming the kettle is 80 % efficient, how long does it take to bring the water to boil? (Specific heat capacity of water = 4200 J kg⁻¹ °C⁻¹)","fastMethod":"Find useful power (0.8 × 1500 W) then use Q = mcΔT to get time = Q ÷ useful power.","steps":["Calculate heat needed: Q = 0.5 × 4200 × (100‑20) = 0.5 × 4200 × 80 = 168 000 J.","Useful power = 0.8 × 1500 = 1200 W (J s⁻¹).","Time = Q ÷ power = 168 000 ÷ 1200 = 140 s."],"answer":"t = 140 s (≈ 2 min 20 s)"},
      selfCheck: {"prompt":"True or false: A wind turbine with an efficiency of 35 % converts 35 % of the wind's kinetic energy into electrical energy.","answer":"True – efficiency is defined as useful output ÷ input."},
      questions: [{"id":"energy-efficiency-dissipation-and-resources-q1","prompt":"State one reason why renewable energy sources are considered more sustainable than fossil fuels.","accept":["they are replenished naturally","they do not deplete finite resources","they produce little or no CO₂"],"hint":"Think about supply over time."},{"id":"energy-efficiency-dissipation-and-resources-q2","prompt":"A hydroelectric plant receives 5 × 10⁶ J of water energy each hour and generates 1.5 × 10⁶ J of electricity. What is its efficiency?","accept":["30%","0.30","30 percent"],"hint":"η = (output ÷ input) × 100."},{"id":"energy-efficiency-dissipation-and-resources-q3","prompt":"Which energy resource has the highest energy density: coal, gasoline, or wind?","accept":["gasoline","petrol"],"hint":"Compare per kilogram values."}],
      mistakes: ["Treating efficiency as a factor of 100 rather than a decimal when multiplying.","Confusing energy density with power output; density is per unit mass/volume, not per time."],
      examTip: "When a question asks for ‘overall efficiency’, multiply the efficiencies of each stage (as decimals) rather than adding them.",
      searchTerms: ["energy efficiency calculation","energy dissipation GCSE","renewable vs non renewable energy","energy density fuel","hydroelectric efficiency"],
    }
  ],
};
