import type { TopicContent } from "../types";
import { PhysicsForcesScalarsVectorsAndResultantForcesDemo, PhysicsForcesNewtonSLawsAndFMaDemo, PhysicsForcesMomentsMomentumAndStoppingDistancesDemo } from "../notes-diagrams/physics-forces-demos";

export const physicsForcesTopic: TopicContent = {
  slug: "physics-forces",
  subject: "Physics",
  subjectSlug: "gcse-science/physics",
  title: "GCSE Physics: Forces",
  description: "AQA GCSE Physics — Forces. Covers scalar vs vector quantities, resultant forces, Newton's three laws of motion, F=ma calculations, moments/levers, momentum, and stopping distances.",
  glyphs: ["⚡","🔭","🧲","🌀"],
  subtopics: [
    {
      id: "scalars-vectors-and-resultant-forces",
      title: "Scalars, Vectors and Resultant Forces",
      tier: "Foundation",
      objective: "Identify scalar and vector quantities and calculate a simple resultant force using a vector diagram.",
      whyMatters: "Understanding vectors is essential for all later force calculations and is directly tested in multiple choice and short answer questions.",
      conceptTitle: "Basic force quantities",
      conceptBullets: ["A <b style=\"color:#C9A24B\">scalar</b> has magnitude only, e.g., mass or speed, and no direction.","A <b style=\"color:#C9A24B\">vector</b> has both magnitude and direction, e.g., force or velocity.","Resultant force is the <b style=\"color:#C9A24B\">vector sum</b> of all forces acting on an object.","Use a <b style=\"color:#C9A24B\">parallelogram</b> or tip‑to‑tail method to draw vectors and find the resultant."],
      conceptNote: "<b>Tip:</b> When drawing vectors, keep the scale consistent and use a protractor for accurate angles.",
      glossary: [{"term":"scalar","def":"A quantity described by magnitude alone, no direction."},{"term":"vector","def":"A quantity described by both magnitude and direction."},{"term":"resultant force","def":"The single force that has the same effect as all the individual forces combined."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsForcesScalarsVectorsAndResultantForcesDemo,
      worked: {"question":"Two forces act on a crate: 5 N east and 12 N north. Find the magnitude of the resultant force.","fastMethod":"Use Pythagoras on the perpendicular components.","steps":["Square each force: 5² = 25, 12² = 144.","Add the squares: 25 + 144 = 169.","Take the square root: √169 = 13.","Resultant = 13 N."],"answer":"13 N"},
      selfCheck: {"prompt":"True or false: Speed is a vector quantity.","answer":"False – speed is a scalar; velocity is the vector."},
      questions: [{"id":"scalars-vectors-and-resultant-forces-q1","prompt":"Give one example of a scalar quantity used in physics.","accept":["mass","temperature"],"hint":"Think of a property that has no direction."},{"id":"scalars-vectors-and-resultant-forces-q2","prompt":"What is the term for the single force that replaces several forces acting on an object?","accept":["resultant force","resultant"],"hint":"It is the vector sum."},{"id":"scalars-vectors-and-resultant-forces-q3","prompt":"Two forces of 8 N north and 6 N east act on an object. What is the magnitude of the resultant (to 1 dp)?","accept":["10.0","10"],"hint":"Use Pythagoras."}],
      mistakes: ["Adding magnitudes directly without considering direction.","Confusing speed with velocity when identifying vectors."],
      examTip: "Always label the direction on your vector diagram; examiners award marks for clear representation.",
      searchTerms: ["scalar vs vector","resultant force calculation","vector diagram GCSE","force magnitude direction","parallelogram method"],
    },
    {
      id: "newton-s-laws-and-f-ma",
      title: "Newton's Laws and F = ma",
      tier: "Standard",
      objective: "Apply Newton’s three laws to predict motion and calculate acceleration or force using F = ma.",
      whyMatters: "These laws underpin all motion questions; the formula F = ma is a high‑frequency calculation in the exam.",
      conceptTitle: "Newtonian mechanics",
      conceptBullets: ["Newton’s <b style=\"color:#C9A24B\">first law</b> states an object at rest stays at rest and a moving object stays in uniform motion unless acted on by an unbalanced force.","The <b style=\"color:#C9A24B\">second law</b> gives the relationship F = ma, linking net force, mass and acceleration.","Newton’s <b style=\"color:#C9A24B\">third law</b> says for every action force there is an equal and opposite reaction force.","When forces are unbalanced, the object’s <b style=\"color:#C9A24B\">acceleration</b> is in the direction of the net force."],
      conceptNote: "<b>Tip:</b> Write down the known values and the required quantity before rearranging F = ma.",
      glossary: [{"term":"Newton's first law","def":"Law of inertia; objects maintain their state of motion unless acted on by a net force."},{"term":"Newton's second law","def":"Relates net force to mass and acceleration (F = ma)."},{"term":"Newton's third law","def":"Every action has an equal and opposite reaction."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: PhysicsForcesNewtonSLawsAndFMaDemo,
      worked: {"question":"A 2.0 kg cart accelerates at 3.5 m s⁻². Calculate the net force acting on it.","fastMethod":"Multiply mass by acceleration directly.","steps":["Identify mass = 2.0 kg, acceleration = 3.5 m s⁻².","Apply F = ma: 2.0 × 3.5 = 7.0.","Resulting force = 7.0 N.","State direction is the same as acceleration."],"answer":"7.0 N"},
      selfCheck: {"prompt":"If the net force on an object is zero, what can be said about its acceleration?","answer":"Acceleration is zero; the object moves at constant velocity (including rest)."},
      questions: [{"id":"newton-s-laws-and-f-ma-q1","prompt":"State Newton’s second law in formula form.","accept":["f = ma","force = mass times acceleration"],"hint":"Think of the relationship between force, mass and acceleration."},{"id":"newton-s-laws-and-f-ma-q2","prompt":"A 10 kg object is pulled with a 40 N force. What is its acceleration?","accept":["4","4.0"],"hint":"Rearrange a = F/m."},{"id":"newton-s-laws-and-f-ma-q3","prompt":"True or false: The reaction force acts on the same object as the action force.","accept":["false"],"hint":"Consider which objects the forces act upon."}],
      mistakes: ["Mixing up action and reaction forces as acting on the same object.","Forgetting to include the direction of acceleration when stating the answer."],
      examTip: "When a question gives two of the three variables (F, m, a), always rearrange the formula rather than memorising separate equations.",
      searchTerms: ["newton's laws GCSE","f = ma calculation","net force direction","unbalanced force example","acceleration formula"],
    },
    {
      id: "moments-momentum-and-stopping-distances",
      title: "Moments, Momentum and Stopping Distances",
      tier: "Extension",
      objective: "Analyse levers, calculate moments, use momentum (p = mv) and determine stopping distances using kinetic energy concepts.",
      whyMatters: "These topics appear in higher‑tier papers and in practical questions; they link forces to real‑world scenarios like brakes and seesaws.",
      conceptTitle: "Advanced force applications",
      conceptBullets: ["A <b style=\"color:#C9A24B\">moment</b> is the product of force and its perpendicular distance from the pivot (M = F d).","For a lever in equilibrium, the clockwise moments equal the anticlockwise moments (ΣM = 0).","Momentum <b style=\"color:#C9A24B\">p = mv</b> is a vector; the change in momentum equals impulse (FΔt).","Stopping distance can be found from the work‑energy principle: work done by brakes (force × distance) equals the initial kinetic energy (½ mv²)."],
      conceptNote: "<b>Tip:</b> Keep units consistent – convert cm to m for distance and use N·m for moments.",
      glossary: [{"term":"moment","def":"Rotational effect of a force, calculated as force times perpendicular distance from the pivot."},{"term":"momentum","def":"Product of mass and velocity (p = mv); a measure of motion."},{"term":"stopping distance","def":"Distance required for a moving object to come to rest under a given braking force."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsForcesMomentsMomentumAndStoppingDistancesDemo,
      worked: {"question":"A 1500 kg car travelling at 20 m s⁻¹ brakes with a constant force of 6000 N. Calculate the stopping distance.","fastMethod":"Use ½ mv² = F d and solve for d.","steps":["Calculate kinetic energy: ½ × 1500 × 20² = 300,000 J.","Set 300,000 = 6000 × d.","Divide: d = 300,000 / 6000 = 50.","Stopping distance = 50 m."],"answer":"50 m"},
      selfCheck: {"prompt":"If a 2 kg ball moving at 5 m s⁻¹ collides and stops in 0.1 s, what average force acted on it?","answer":"100 N (Impulse = Δp = 10 kg·m s⁻¹; F = Δp/Δt = 10/0.1)."},
      questions: [{"id":"moments-momentum-and-stopping-distances-q1","prompt":"A 10 N force is applied 0.3 m from a pivot. What moment does it produce?","accept":["3","3.0"],"hint":"Multiply force by distance."},{"id":"moments-momentum-and-stopping-distances-q2","prompt":"State the condition for a lever to be in equilibrium.","accept":["clockwise moments equal anticlockwise moments","sum of moments = 0"],"hint":"Think of balancing moments."},{"id":"moments-momentum-and-stopping-distances-q3","prompt":"A 0.5 kg ball moving at 4 m s⁻¹ hits a wall and rebounds at 2 m s⁻¹ opposite direction. Find the change in momentum.","accept":["3","3.0"],"hint":"Δp = m(v_final - v_initial)."}],
      mistakes: ["Using distance in cm directly in moment calculations without converting to metres.","Treating momentum as a scalar and ignoring direction when calculating change."],
      examTip: "When a question asks for stopping distance, write the energy equation first (½ mv² = Fd) to avoid forgetting the factor ½.",
      searchTerms: ["moment calculation GCSE","lever equilibrium","momentum change formula","stopping distance physics","work energy brake problem"],
    }
  ],
};
