import type { TopicContent } from "../types";
import { PhysicsSpacePhysicsTheSolarSystemAndLifeCycleOfStarsDemo, PhysicsSpacePhysicsOrbitalMotionOfPlanetsAndSatellitesDemo, PhysicsSpacePhysicsRedShiftExpandingUniverseAndTheBigBangDemo } from "../notes-diagrams/physics-space-physics-demos";

export const physicsSpacePhysicsTopic: TopicContent = {
  slug: "physics-space-physics",
  subject: "Physics",
  subjectSlug: "gcse-science/physics",
  title: "GCSE Physics: Space Physics",
  description: "AQA GCSE Physics — Space Physics. Covers the solar system and life cycle of stars, orbital motion of planets/satellites, red-shift and the expanding universe (Big Bang theory).",
  glyphs: ["⚡","🔭","🧲","🌀"],
  subtopics: [
    {
      id: "the-solar-system-and-life-cycle-of-stars",
      title: "The Solar System and Life Cycle of Stars",
      tier: "Foundation",
      objective: "Identify the main parts of the solar system and describe the basic stages in a star’s life cycle.",
      whyMatters: "Understanding the solar system provides context for all later space physics questions and the life‑cycle is a core exam topic.",
      conceptTitle: "Solar system layout and stellar evolution",
      conceptBullets: ["The <b style=\"color:#C9A24B\">solar system</b> consists of the Sun, eight planets, dwarf planets, moons, asteroids and comets, ordered by distance from the Sun.","A <b style=\"color:#C9A24B\">main‑sequence star</b> fuses hydrogen into helium in its core and remains stable for most of its life.","When hydrogen is exhausted, a star expands into a <b style=\"color:#C9A24B\">red giant</b>, then sheds outer layers to form a planetary nebula.","Stars with mass < 8 M☉ end as a <b style=\"color:#C9A24B\">white dwarf</b>; more massive stars undergo supernovae and leave neutron stars or black holes.","The Sun is a G‑type main‑sequence star, about 4.6 billion years old, and will become a red giant in ~5 billion years."],
      conceptNote: "<b>Tip:</b> Sketch a simple diagram of the solar system and a flow‑chart of the star life cycle; visualising order helps recall facts quickly.",
      glossary: [{"term":"main‑sequence","def":"Phase where a star fuses hydrogen in its core and is in hydrostatic equilibrium."},{"term":"red giant","def":"A luminous, expanded star that has exhausted core hydrogen and is fusing helium or heavier elements."},{"term":"white dwarf","def":"A dense, Earth‑size stellar remnant composed mostly of electron‑degenerate matter."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsSpacePhysicsTheSolarSystemAndLifeCycleOfStarsDemo,
      worked: {"question":"A Sun‑like star has a main‑sequence lifetime of 10 billion years. If it is currently 4.6 billion years old, what fraction of its main‑sequence life remains?","fastMethod":"Subtract current age from total lifetime and divide by total lifetime.","steps":["Total lifetime = 10 billion years.","Remaining time = 10 – 4.6 = 5.4 billion years.","Fraction remaining = 5.4 / 10 = 0.54."],"answer":"0.54 (or 54 % of its main‑sequence life remains)."},
      selfCheck: {"prompt":"True or false: All stars end their lives as black holes.","answer":"False – only very massive stars (>20 M☉) can become black holes; most end as white dwarfs."},
      questions: [{"id":"the-solar-system-and-life-cycle-of-stars-q1","prompt":"Name the three types of stellar remnant.","accept":["white dwarf, neutron star, black hole","white dwarf; neutron star; black hole"],"hint":"Think of the end‑states for low, medium and high mass stars."},{"id":"the-solar-system-and-life-cycle-of-stars-q2","prompt":"Which planet is the largest in the solar system?","accept":["jupiter"],"hint":"It is a gas giant with many moons."},{"id":"the-solar-system-and-life-cycle-of-stars-q3","prompt":"Calculate the percentage of the Sun’s mass that is helium (given 24 % helium).","accept":["24%","24"],"hint":"The figure is given directly; just express it as a percentage."}],
      mistakes: ["Confusing the order of stellar remnants – e.g., thinking a white dwarf becomes a neutron star.","Mixing up the number of planets with dwarf planets."],
      examTip: "When a question asks for a stage in a star’s life, always check the star’s mass first – it determines the correct end‑state.",
      searchTerms: ["solar system planets","star life cycle","main sequence star","white dwarf definition","red giant formation"],
    },
    {
      id: "orbital-motion-of-planets-and-satellites",
      title: "Orbital Motion of Planets and Satellites",
      tier: "Standard",
      objective: "Explain why planets and satellites stay in orbit using centripetal force and calculate orbital speed.",
      whyMatters: "Orbit concepts are tested in both multiple‑choice and calculation questions; they underpin satellite technology and space missions.",
      conceptTitle: "Forces and equations of orbital motion",
      conceptBullets: ["An object in circular orbit experiences a <b style=\"color:#C9A24B\">centripetal force</b> directed towards the centre of the orbit.","The required centripetal force is provided by <b style=\"color:#C9A24B\">gravity</b>, so F_gravity = m v² / r.","Orbital speed v can be found from v = √(GM / r), where G is the gravitational constant and M the mass of the central body.","The period T of an orbit relates to speed by T = 2πr / v, leading to Kepler’s third law T² ∝ r³ for circular orbits."],
      conceptNote: "<b>Tip:</b> Memorise the formula v = √(GM/r); plug numbers into the calculator in one step to avoid algebra errors.",
      glossary: [{"term":"centripetal force","def":"A force directed towards the centre of a circular path that keeps an object moving in that path."},{"term":"gravitational constant","def":"G = 6.67×10⁻¹¹ N m² kg⁻², used in Newton’s law of gravitation."},{"term":"orbital period","def":"The time taken for one complete revolution around the central body."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: PhysicsSpacePhysicsOrbitalMotionOfPlanetsAndSatellitesDemo,
      worked: {"question":"A satellite orbits Earth at an altitude of 300 km. Calculate its orbital speed (use r = 6.67×10⁶ m).","fastMethod":"Use v = √(GM/r) with GM = 3.986×10¹⁴ m³ s⁻².","steps":["r = Earth radius + altitude = 6.37×10⁶ m + 3.0×10⁵ m = 6.67×10⁶ m.","v = √(3.986×10¹⁴ / 6.67×10⁶).","v = √(5.98×10⁷) ≈ 7.73×10³ m s⁻¹."],"answer":"7.7 km s⁻¹ (approximately)."},
      selfCheck: {"prompt":"True or false: Increasing the orbital radius always decreases the orbital speed.","answer":"True – because v = √(GM/r), speed is inversely proportional to the square root of radius."},
      questions: [{"id":"orbital-motion-of-planets-and-satellites-q1","prompt":"What force provides the centripetal force for a planet orbiting the Sun?","accept":["gravity","gravitational force"],"hint":"Think of the universal attraction between masses."},{"id":"orbital-motion-of-planets-and-satellites-q2","prompt":"State Kepler’s third law in words.","accept":["the square of the period is proportional to the cube of the orbital radius","T squared proportional to r cubed"],"hint":"Relate period and distance."},{"id":"orbital-motion-of-planets-and-satellites-q3","prompt":"Calculate the period of a satellite at 20 000 km altitude (r = 2.57×10⁷ m).","accept":["5.6×10⁴ s","56000 s","15.6 h","15.6 hours"],"hint":"Find speed with v = √(GM/r) then use T = 2πr/v."}],
      mistakes: ["Using Earth’s surface radius instead of the orbital radius when applying v = √(GM/r).","Confusing orbital speed with escape speed (v_escape = √2 v_orbit)."],
      examTip: "When given altitude, always add Earth’s radius first; the combined value is the r you use in all orbital formulas.",
      searchTerms: ["orbital speed formula","centripetal force gravity","satellite period calculation","Kepler's third law GCSE","geostationary orbit altitude"],
    },
    {
      id: "red-shift-expanding-universe-and-the-big-bang",
      title: "Red‑Shift, Expanding Universe and the Big Bang",
      tier: "Extension",
      objective: "Interpret red‑shift data to explain the expanding universe and describe the evidence supporting the Big Bang model.",
      whyMatters: "Red‑shift is a high‑weight exam topic; it links observations to cosmology and appears in data‑analysis questions.",
      conceptTitle: "Cosmological red‑shift and the Big Bang evidence",
      conceptBullets: ["When light from a galaxy is stretched, its wavelength increases – this is called <b style=\"color:#C9A24B\">red‑shift</b> and indicates the galaxy is moving away.","Hubble’s law states v = H₀ d, where v is recession speed, d distance and H₀ ≈ 70 km s⁻¹ Mpc⁻¹.","A linear v‑d relationship shows the universe is <b style=\"color:#C9A24B\">expanding uniformly</b> from an earlier dense state.","Key Big Bang evidence includes the <b style=\"color:#C9A24B\">cosmic microwave background</b> (CMB) and the observed abundance of light elements.","The CMB is a uniform 2.7 K radiation field, a relic of the hot early universe."],
      conceptNote: "<b>Tip:</b> When converting red‑shift (z) to speed, use v ≈ cz for small z (c = 3.0×10⁵ km s⁻¹).",
      glossary: [{"term":"red‑shift","def":"Increase in wavelength of light due to the source moving away, quantified by z = (λ_observed‑λ_rest)/λ_rest."},{"term":"Hubble’s constant","def":"The proportionality constant (≈70 km s⁻¹ Mpc⁻¹) linking recession speed to distance."},{"term":"cosmic microwave background","def":"Residual thermal radiation from ~380 000 years after the Big Bang, observed as a near‑uniform 2.7 K glow."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsSpacePhysicsRedShiftExpandingUniverseAndTheBigBangDemo,
      worked: {"question":"A galaxy has a measured red‑shift of z = 0.02. Estimate its recession speed and distance using Hubble’s law (H₀ = 70 km s⁻¹ Mpc⁻¹).","fastMethod":"Convert z to v with v ≈ cz, then d = v / H₀.","steps":["v ≈ c z = 3.0×10⁵ km s⁻¹ × 0.02 = 6.0×10³ km s⁻¹.","d = v / H₀ = 6000 / 70 ≈ 86 Mpc.","Convert to light‑years if required (1 Mpc ≈ 3.26×10⁶ ly)."],"answer":"Recession speed ≈ 6 000 km s⁻¹; distance ≈ 86 Mpc (≈ 2.8×10⁸ ly)."},
      selfCheck: {"prompt":"True or false: A higher red‑shift always means a galaxy is farther away.","answer":"True for the standard cosmological model where red‑shift correlates with distance via Hubble’s law."},
      questions: [{"id":"red-shift-expanding-universe-and-the-big-bang-q1","prompt":"What does the cosmic microwave background represent?","accept":["remnant radiation from the early universe","big bang relic radiation"],"hint":"Think of the universe when it became transparent."},{"id":"red-shift-expanding-universe-and-the-big-bang-q2","prompt":"If H₀ = 70 km s⁻¹ Mpc⁻¹, what is the approximate age of the universe?","accept":["14 billion years","1.4×10¹⁰ years","≈14 Gyr"],"hint":"Age ≈ 1 / H₀ (convert units)."},{"id":"red-shift-expanding-universe-and-the-big-bang-q3","prompt":"A galaxy 150 Mpc away recedes at what speed?","accept":["10500 km/s","1.05×10⁴ km/s","10 500 km s⁻¹"],"hint":"Use v = H₀ d directly."}],
      mistakes: ["Using v = cz for large red‑shifts where relativistic corrections are needed.","Mixing up the units of Hubble’s constant (km s⁻¹ Mpc⁻¹) and forgetting to convert distance to Mpc."],
      examTip: "When a question gives red‑shift, first decide if z is small (<0.1); if so, use v ≈ cz, otherwise note that the exam will usually keep z small to avoid relativity.",
      searchTerms: ["red shift calculation","hubble's law GCSE","cosmic microwave background evidence","big bang age of universe","expanding universe explanation"],
    }
  ],
};
