import type { TopicContent } from "../types";
import { PhysicsWavesTypesOfMechanicalWavesDemo, PhysicsWavesWaveSpeedFrequencyAndWavelengthDemo, PhysicsWavesElectromagneticSpectrumAndWaveBehaviourDemo } from "../notes-diagrams/physics-waves-demos";

export const physicsWavesTopic: TopicContent = {
  slug: "physics-waves",
  subject: "Physics",
  subjectSlug: "gcse-science/physics",
  title: "GCSE Physics: Waves",
  description: "AQA GCSE Physics — Waves. Covers transverse and longitudinal waves, wave speed/frequency/wavelength (v=fλ), the electromagnetic spectrum and its uses/dangers, and reflection/refraction of waves.",
  glyphs: ["⚡","🔭","🧲","🌀"],
  subtopics: [
    {
      id: "types-of-mechanical-waves",
      title: "Types of mechanical waves",
      tier: "Foundation",
      objective: "Identify and describe transverse and longitudinal waves and their particle motion.",
      whyMatters: "Understanding wave types underpins all later wave questions and appears in multiple choice and short answer exam items.",
      conceptTitle: "Mechanical wave classification",
      conceptBullets: ["A <b style=\"color:#C9A24B\">transverse wave</b> has particle motion perpendicular to the direction of travel, e.g., waves on a string.","A <b style=\"color:#C9A24B\">longitudinal wave</b> has particle motion parallel to the direction of travel, e.g., sound in air.","Both wave types transmit energy without permanent displacement of the medium.","The speed of a mechanical wave depends on the medium’s properties such as tension and density."],
      conceptNote: "<b>Tip:</b> Sketch the particle motion arrows for each wave type – it’s quick to recall during exams.",
      glossary: [{"term":"transverse wave","def":"Wave where particles move at right angles to the direction of wave travel."},{"term":"longitudinal wave","def":"Wave where particles move parallel to the direction of wave travel."},{"term":"medium","def":"Material through which a mechanical wave propagates."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsWavesTypesOfMechanicalWavesDemo,
      worked: {"question":"A pulse travels along a stretched string at 2.5 m s⁻¹. If the string’s tension is 100 N, calculate the linear mass density of the string.","fastMethod":"Use v = √(T/μ) → μ = T/v².","steps":["Square the speed: (2.5)² = 6.25.","Divide tension by this value: 100 ÷ 6.25 = 16.","Result is μ = 16 kg m⁻¹."],"answer":"μ = 16 kg m⁻¹"},
      selfCheck: {"prompt":"True or false: In a longitudinal wave the particles move up and down.","answer":"False – particles move back and forth along the direction of travel."},
      questions: [{"id":"types-of-mechanical-waves-q1","prompt":"Name the particle motion direction for a transverse wave.","accept":["perpendicular","at right angles"],"hint":"Think of a rope being shaken side‑to‑side."},{"id":"types-of-mechanical-waves-q2","prompt":"Give one everyday example of a longitudinal wave.","accept":["sound","sound wave"],"hint":"Consider what you hear."},{"id":"types-of-mechanical-waves-q3","prompt":"If a wave’s speed doubles while the frequency stays the same, what happens to its wavelength?","accept":["doubles","increases"],"hint":"Use v = fλ."}],
      mistakes: ["Confusing particle motion direction with wave travel direction.","Using v = f/λ instead of v = fλ."],
      examTip: "When a diagram is given, look for arrows on the medium – they tell you instantly if it’s transverse or longitudinal.",
      searchTerms: ["transverse wave definition","longitudinal wave example","wave particle motion","string wave speed formula","mechanical wave types"],
    },
    {
      id: "wave-speed-frequency-and-wavelength",
      title: "Wave speed, frequency and wavelength",
      tier: "Standard",
      objective: "Apply v = fλ to calculate any one of speed, frequency or wavelength and interpret graphs.",
      whyMatters: "These relationships are tested in both calculation and data‑analysis questions across the exam.",
      conceptTitle: "The v = fλ relationship",
      conceptBullets: ["The equation <b style=\"color:#C9A24B\">v = fλ</b> links wave speed, frequency and wavelength.","<b style=\"color:#C9A24B\">Frequency</b> (f) is the number of cycles per second, measured in hertz (Hz).","<b style=\"color:#C9A24B\">Wavelength</b> (λ) is the distance between successive crests or compressions.","If two of the three variables are known, rearrange the formula to find the third."],
      conceptNote: "<b>Tip:</b> Memorise the three rearrangements: v = fλ, f = v/λ, λ = v/f.",
      glossary: [{"term":"frequency","def":"Number of wave cycles passing a point each second (Hz)."},{"term":"wavelength","def":"Distance between two consecutive points in phase on a wave."},{"term":"wave speed","def":"Rate at which a wave crest travels through a medium (m s⁻¹)."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: PhysicsWavesWaveSpeedFrequencyAndWavelengthDemo,
      worked: {"question":"A radio station broadcasts at 100 MHz. Calculate the wavelength of the radio waves in vacuum.","fastMethod":"Use λ = c/f with c = 3.0×10⁸ m s⁻¹.","steps":["Convert frequency: 100 MHz = 1.0×10⁸ Hz.","Divide c by f: 3.0×10⁸ ÷ 1.0×10⁸ = 3.","Result λ = 3 m."],"answer":"λ = 3 m"},
      selfCheck: {"prompt":"If the frequency of a wave is doubled while its speed stays the same, the wavelength is:","answer":"halved – because λ = v/f."},
      questions: [{"id":"wave-speed-frequency-and-wavelength-q1","prompt":"State the unit for frequency.","accept":["hz","hertz"],"hint":"One cycle per second."},{"id":"wave-speed-frequency-and-wavelength-q2","prompt":"A wave travels at 20 m s⁻¹ and has a wavelength of 0.5 m. What is its frequency?","accept":["40 hz","40 hertz","40"],"hint":"Use f = v/λ."},{"id":"wave-speed-frequency-and-wavelength-q3","prompt":"True or false: In a distance‑time graph the gradient gives the wavelength.","accept":["false"],"hint":"Gradient gives speed, not λ."}],
      mistakes: ["Mixing up which variable goes on the numerator when rearranging v = fλ.","Failing to convert MHz or kHz to Hz before using the formula."],
      examTip: "Write the rearranged formula on the margin before plugging numbers – it prevents algebra slips.",
      searchTerms: ["v = f lambda","calculate wavelength","frequency unit hertz","wave speed formula","gcse wave calculations"],
    },
    {
      id: "electromagnetic-spectrum-and-wave-behaviour",
      title: "Electromagnetic spectrum and wave behaviour",
      tier: "Extension",
      objective: "Analyse the EM spectrum, its applications, hazards, and explain reflection and refraction of waves.",
      whyMatters: "These concepts appear in multi‑step questions and data‑analysis tasks, testing deeper understanding beyond pure calculation.",
      conceptTitle: "EM spectrum, uses, dangers and wave behaviour",
      conceptBullets: ["The <b style=\"color:#C9A24B\">electromagnetic (EM) spectrum</b> covers all wavelengths from gamma rays to radio waves, all travelling at c in vacuum.","<b style=\"color:#C9A24B\">Reflection</b> occurs when a wave bounces off a surface; the angle of incidence equals the angle of reflection.","<b style=\"color:#C9A24B\">Refraction</b> is the change in direction when a wave passes into a medium with a different speed, described by Snell’s law.","Uses: <b style=\"color:#C9A24B\">X‑rays</b> for imaging, <b style=\"color:#C9A24B\">microwaves</b> for cooking, <b style=\"color:#C9A24B\">radio waves</b> for communication; Dangers: ionising radiation (gamma, X‑ray) can damage DNA."],
      conceptNote: "<b>Tip:</b> Sketch a ray diagram for reflection and refraction – the picture often earns marks even if the maths is shaky.",
      glossary: [{"term":"electromagnetic spectrum","def":"Range of all EM wave types ordered by wavelength or frequency."},{"term":"refraction","def":"Bending of a wave due to a change in its speed when entering a new medium."},{"term":"ionising radiation","def":"High‑energy EM radiation capable of removing electrons from atoms, causing biological damage."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsWavesElectromagneticSpectrumAndWaveBehaviourDemo,
      worked: {"question":"A light beam passes from air (n=1.00) into glass (n=1.50) at an incidence angle of 30°. Calculate the angle of refraction.","fastMethod":"Use Snell’s law: sinθ₂ = n₁ sinθ₁ / n₂.","steps":["Calculate sinθ₁: sin30° = 0.5.","Compute sinθ₂ = (1.00 × 0.5) / 1.50 = 0.333.","Find θ₂ = arcsin(0.333) ≈ 19.5°."],"answer":"θ₂ ≈ 19.5°"},
      selfCheck: {"prompt":"True or false: Radio waves are ionising and can damage DNA.","answer":"False – radio waves are non‑ionising low‑energy radiation."},
      questions: [{"id":"electromagnetic-spectrum-and-wave-behaviour-q1","prompt":"Which part of the EM spectrum is used for medical imaging and is ionising?","accept":["x‑ray","xray"],"hint":"High frequency, short wavelength."},{"id":"electromagnetic-spectrum-and-wave-behaviour-q2","prompt":"State the law governing the angle of reflection.","accept":["angle of incidence equals angle of reflection","angle of incidence = angle of reflection"],"hint":"Think mirror behaviour."},{"id":"electromagnetic-spectrum-and-wave-behaviour-q3","prompt":"If the wavelength of a microwave is 12 cm, what is its frequency? (c = 3.0×10⁸ m s⁻¹)","accept":["2.5 ghz","2.5 ghz","2.5×10⁹ hz","2.5×10⁹"],"hint":"Use f = c/λ; convert cm to m."}],
      mistakes: ["Confusing refractive index with speed; forgetting n = c/v.","Using the wrong sign for angle when applying Snell’s law."],
      examTip: "When asked about hazards, always link ionising radiation to its ability to remove electrons and cause DNA breaks.",
      searchTerms: ["electromagnetic spectrum uses","refraction formula","snell's law gcse","danger of x rays","reflection angle law"],
    }
  ],
};
