import type { TopicContent } from "../types";
import { PhysicsMagnetismElectromagnetismPermanentAndInducedMagnetsDemo, PhysicsMagnetismElectromagnetismElectromagnetsAndSolenoidsDemo, PhysicsMagnetismElectromagnetismMotorAndGeneratorEffectsDemo } from "../notes-diagrams/physics-magnetism-electromagnetism-demos";

export const physicsMagnetismElectromagnetismTopic: TopicContent = {
  slug: "physics-magnetism-electromagnetism",
  subject: "Physics",
  subjectSlug: "gcse-science/physics",
  title: "GCSE Physics: Magnetism and Electromagnetism",
  description: "AQA GCSE Physics — Magnetism and Electromagnetism. Covers permanent and induced magnets, magnetic fields, electromagnets and solenoids, the motor effect (Fleming's left-hand rule, F=BIl), and the generator effect/transformers.",
  glyphs: ["⚡","🔭","🧲","🌀"],
  subtopics: [
    {
      id: "permanent-and-induced-magnets",
      title: "Permanent and induced magnets",
      tier: "Foundation",
      objective: "Identify how permanent and induced magnets work and predict their behaviour in simple situations.",
      whyMatters: "Understanding magnet types underpins all later questions about magnetic fields and forces, and appears in multiple-choice and short-answer questions.",
      conceptTitle: "How magnets produce and respond to magnetic fields",
      conceptBullets: ["A <b style=\"color:#C9A24B\">permanent magnet</b> has aligned domains that give it a constant magnetic field without external influence.","An <b style=\"color:#C9A24B\">induced magnet</b> becomes magnetic only while it is inside another magnetic field, aligning its domains temporarily.","The <b style=\"color:#C9A24B\">magnetic field</b> lines exit the north pole and enter the south pole, showing direction and strength.","Two unlike poles attract and like poles repel; the force is strongest where the field lines are closest together."],
      conceptNote: "<b>Tip:</b> When drawing field lines, make them denser where the field is stronger – this helps you visualise force direction quickly.",
      glossary: [{"term":"permanent magnet","def":"A magnet that retains its magnetic field without an external field."},{"term":"induced magnet","def":"A material that becomes magnetic only while in a magnetic field."},{"term":"magnetic field","def":"The region around a magnet where magnetic forces can be observed, represented by field lines."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsMagnetismElectromagnetismPermanentAndInducedMagnetsDemo,
      worked: {"question":"A piece of iron is placed between the poles of a bar magnet. Explain what happens to the iron.","fastMethod":"State that the iron becomes an induced magnet and is attracted to the magnet.","steps":["Identify the iron as a ferromagnetic material.","Recognise the external magnetic field from the bar magnet.","Explain that the field aligns domains in the iron, making it an induced magnet.","Conclude that the induced north pole is attracted to the bar magnet's south pole (and vice‑versa)."],"answer":"The iron becomes an induced magnet with its domains aligned by the bar magnet’s field, so it is attracted to the magnet."},
      selfCheck: {"prompt":"True or false: An induced magnet will retain its magnetism after being removed from a magnetic field.","answer":"False – it loses the induced magnetism once the external field is removed."},
      questions: [{"id":"permanent-and-induced-magnets-q1","prompt":"Name the two poles of a permanent magnet.","accept":["north and south","south and north"],"hint":"Think of the direction field lines leave and enter."},{"id":"permanent-and-induced-magnets-q2","prompt":"What happens to a piece of iron when it is placed in a magnetic field?","accept":["it becomes an induced magnet","it is attracted"],"hint":"Consider domain alignment."},{"id":"permanent-and-induced-magnets-q3","prompt":"If two identical bar magnets are placed with like poles facing, what is the force between them?","accept":["repulsion","they repel each other"],"hint":"Recall the rule for like poles."}],
      mistakes: ["Confusing induced magnetism with permanent magnetism, claiming the iron stays magnetic after removal.","Drawing field lines that go from south to north instead of north to south."],
      examTip: "When a question asks for the direction of force, always start by drawing the field lines and then apply the north‑to‑south convention.",
      searchTerms: ["permanent magnet definition","induced magnet explanation","magnetic field lines","north south poles","ferromagnetic materials"],
    },
    {
      id: "electromagnets-and-solenoids",
      title: "Electromagnets and solenoids",
      tier: "Standard",
      objective: "Explain how a current‑carrying coil creates a magnetic field and predict the effect of changing coil parameters.",
      whyMatters: "Electromagnets are tested in practical questions and in calculations of field strength, a core part of the specification.",
      conceptTitle: "Creating magnetic fields with electricity",
      conceptBullets: ["A <b style=\"color:#C9A24B\">solenoid</b> is a coil of wire; when current flows, it produces a magnetic field similar to a bar magnet.","The field direction follows the <b style=\"color:#C9A24B\">right‑hand rule</b>: thumb points to the north pole when fingers curl with current.","Increasing the number of turns (<b style=\"color:#C9A24B\">N</b>) or the current (<b style=\"color:#C9A24B\">I</b>) makes the field stronger (B ∝ NI).","Inserting a soft iron core concentrates the field, creating a powerful <b style=\"color:#C9A24B\">electromagnet</b>.","When the current stops, the induced magnet loses its field, unlike a permanent magnet."],
      conceptNote: "<b>Tip:</b> Sketch a simple solenoid and label current direction, then use the right‑hand rule to quickly find the north pole.",
      glossary: [{"term":"solenoid","def":"A coil of wire that produces a magnetic field when current passes through it."},{"term":"right‑hand rule","def":"A mnemonic to determine the direction of the magnetic field around a current‑carrying conductor."},{"term":"electromagnet","def":"A magnet whose field is produced by electric current, often enhanced with an iron core."}],
      diagramLabel: "Try it: Quick reference",
      Diagram: PhysicsMagnetismElectromagnetismElectromagnetsAndSolenoidsDemo,
      worked: {"question":"A solenoid has 200 turns and carries a current of 0.5 A. If the number of turns is increased to 400 while the current stays the same, how does the magnetic field change?","fastMethod":"Field is directly proportional to turns; doubling N doubles B.","steps":["Identify original B ∝ N × I = 200 × 0.5.","New N = 400, so new B ∝ 400 × 0.5.","Compare: 400 × 0.5 is twice 200 × 0.5.","State that the magnetic field doubles."],"answer":"The magnetic field becomes twice as strong."},
      selfCheck: {"prompt":"True or false: Adding an iron core to a solenoid reduces the magnetic field strength.","answer":"False – the iron core concentrates the field and increases its strength."},
      questions: [{"id":"electromagnets-and-solenoids-q1","prompt":"What rule tells you the direction of the north pole of a solenoid?","accept":["right hand rule","right‑hand rule"],"hint":"Think of thumb and fingers."},{"id":"electromagnets-and-solenoids-q2","prompt":"If the current in a solenoid is halved, what happens to its magnetic field?","accept":["halved","it is reduced by half"],"hint":"Recall the proportionality."},{"id":"electromagnets-and-solenoids-q3","prompt":"Name one advantage of using an electromagnet over a permanent magnet in a crane.","accept":["can be switched off","it can be turned on and off","control of strength"],"hint":"Consider practical use."}],
      mistakes: ["Confusing the right‑hand rule for current direction with the left‑hand rule for force.","Assuming the magnetic field stays the same when only the core material is changed without considering its permeability."],
      examTip: "When a question gives N and I, write “B ∝ NI” first; it saves time and avoids algebra errors.",
      searchTerms: ["solenoid magnetic field","right hand rule current","electromagnet core effect","magnetic field proportional to turns","how electromagnets work"],
    },
    {
      id: "motor-and-generator-effects",
      title: "Motor and generator effects",
      tier: "Extension",
      objective: "Apply Fleming’s left‑hand rule and the formula F = B I L to solve motor‑type problems and explain how generators and transformers work.",
      whyMatters: "These concepts link forces, energy conversion and AC/DC technology; they appear in multi‑step calculations and diagram questions in the exam.",
      conceptTitle: "Force on a current‑carrying conductor and electromagnetic induction",
      conceptBullets: ["Fleming’s <b style=\"color:#C9A24B\">left‑hand rule</b> gives the direction of force on a conductor: thumb = motion, forefinger = field, middle finger = current.","The magnitude of that force is given by <b style=\"color:#C9A24B\">F = B I L sinθ</b>, where θ is the angle between field and current.","When a conductor moves through a magnetic field, an emf is induced – the <b style=\"color:#C9A24B\">generator effect</b> (Faraday’s law).","A transformer works on the principle of mutual induction, with primary and secondary coils linked by a changing magnetic field.","The voltage ratio in a transformer is V₁/V₂ = N₁/N₂, assuming ideal conditions."],
      conceptNote: "<b>Tip:</b> Sketch the three‑finger diagram first; it instantly tells you the direction of motion, field and current.",
      glossary: [{"term":"Fleming’s left‑hand rule","def":"A mnemonic to determine the direction of force on a current‑carrying conductor in a magnetic field."},{"term":"Faraday’s law","def":"The induced emf in a coil equals the rate of change of magnetic flux through it."},{"term":"transformer","def":"A device that transfers electrical energy between two circuits via electromagnetic induction."}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsMagnetismElectromagnetismMotorAndGeneratorEffectsDemo,
      worked: {"question":"A 0.2 m long conductor carries 3 A perpendicular to a magnetic field of 0.5 T. Calculate the force on the conductor.","fastMethod":"Use F = B I L directly because sinθ = 1.","steps":["Write the formula F = B I L.","Substitute B = 0.5 T, I = 3 A, L = 0.2 m.","Calculate: F = 0.5 × 3 × 0.2 = 0.3 N.","State the force magnitude."],"answer":"0.3 N"},
      selfCheck: {"prompt":"True or false: In a generator, increasing the speed of the coil always increases the induced emf.","answer":"True – emf is proportional to the rate of change of flux, which rises with speed."},
      questions: [{"id":"motor-and-generator-effects-q1","prompt":"State Fleming’s left‑hand rule.","accept":["thumb motion, forefinger field, middle finger current","thumb = motion, forefinger = field, middle = current"],"hint":"Three fingers, three directions."},{"id":"motor-and-generator-effects-q2","prompt":"A transformer has 100 turns on the primary and 250 turns on the secondary. If 120 V is applied to the primary, what is the secondary voltage (ideal)?","accept":["300 v","300 volts"],"hint":"Use V₁/V₂ = N₁/N₂."},{"id":"motor-and-generator-effects-q3","prompt":"What happens to the direction of the induced current if the magnetic field direction is reversed?","accept":["it reverses","current direction reverses"],"hint":"Lenz’s law – induced emf opposes change."}],
      mistakes: ["Using the right‑hand rule instead of the left‑hand rule for motor force direction.","Forgetting the sinθ term when the field and current are not perpendicular."],
      examTip: "When a question gives a diagram, label the three fingers first; this prevents sign errors in the force or emf direction.",
      searchTerms: ["flemings left hand rule","force on current carrying wire","generator emf formula","transformer turns ratio","faraday induction gcse"],
    }
  ],
};
