import type { TopicContent } from "../types";
import { PhysicsAtomicStructureTheStructureOfTheAtomDemo, PhysicsAtomicStructureIsotopesAndTheNuclearModelDemo, PhysicsAtomicStructureRadioactiveDecayHalfLifeAndRadiationUsesDemo } from "../notes-diagrams/physics-atomic-structure-demos";

export const physicsAtomicStructureTopic: TopicContent = {
  slug: "physics-atomic-structure",
  subject: "Physics",
  subjectSlug: "gcse-science/physics",
  title: "GCSE Physics: Atomic Structure (Physics)",
  description: "AQA GCSE Physics — Atomic Structure (Physics). Covers the structure of the atom, isotopes, development of the nuclear model, radioactive decay and nuclear equations, half-life calculations, and uses/dangers of radiation.",
  glyphs: ["⚡","🔭","🧲","🌀"],
  subtopics: [
    {
      id: "the-structure-of-the-atom",
      title: "The structure of the atom",
      tier: "Foundation",
      objective: "Identify the parts of an atom and their relative charges and masses.",
      whyMatters: "Understanding atomic structure underpins all later topics and appears in multiple choice and short answer questions.",
      conceptTitle: "Basic atomic model",
      conceptBullets: ["The <b style=\"color:#C9A24B\">nucleus</b> contains protons and neutrons and accounts for >99% of an atom's mass.","Protons carry a positive <b style=\"color:#C9A24B\">charge</b> (+1e) and define the element's atomic number.","Neutrons are neutral <b style=\"color:#C9A24B\">particles</b> and add to the atomic mass but not the charge.","Electrons are negatively <b style=\"color:#C9A24B\">charged</b> (-1e) and occupy electron shells around the nucleus."],
      conceptNote: "<b>Tip:</b> Memorise the charge and relative mass of each sub‑atomic particle; they are constant across all elements.",
      glossary: [{"term":"proton","def":"positively charged particle in the nucleus, mass ≈1 u"},{"term":"neutron","def":"neutral particle in the nucleus, mass ≈1 u"},{"term":"electron","def":"negatively charged particle outside the nucleus, mass ≈0.0005 u"}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsAtomicStructureTheStructureOfTheAtomDemo,
      worked: {"question":"Write the nuclear symbol for a carbon‑12 atom.","fastMethod":"Place mass number 12 above, atomic number 6 below, and the symbol C.","steps":["Identify atomic number (6) and mass number (12).","Write as ^12_6C.","Check that protons + neutrons = 12."],"answer":"^12_6C"},
      selfCheck: {"prompt":"True or false: An atom with 8 protons must have 8 electrons when neutral.","answer":"True – charge neutrality requires equal numbers of protons and electrons."},
      questions: [{"id":"the-structure-of-the-atom-q1","prompt":"What is the charge of a neutron?","accept":["0","neutral","no charge"],"hint":"Neutrons have no electrical charge."},{"id":"the-structure-of-the-atom-q2","prompt":"How many protons are in an atom of sodium (Na)?","accept":["11","eleven"],"hint":"Atomic number of Na is 11."},{"id":"the-structure-of-the-atom-q3","prompt":"Write the symbol for an isotope with 20 protons and 22 neutrons.","accept":["^42_20ca","^42_20ca"],"hint":"Mass number = protons + neutrons."}],
      mistakes: ["Confusing mass number with atomic number.","Giving the electron charge as +1e instead of –1e."],
      examTip: "Always write the nuclear symbol in the format ^A_ZX; examiners deduct marks for missing superscripts or subscripts.",
      searchTerms: ["atomic structure basics","proton neutron electron charges","nuclear symbol notation","mass number vs atomic number","AQA atom model"],
    },
    {
      id: "isotopes-and-the-nuclear-model",
      title: "Isotopes and the nuclear model",
      tier: "Standard",
      objective: "Explain isotopes, calculate mass numbers and describe the development of the nuclear model.",
      whyMatters: "Isotopes appear in data interpretation and nuclear equations; the model’s history is tested in short answer questions.",
      conceptTitle: "Isotopes and model evolution",
      conceptBullets: ["Isotopes are atoms of the same element with different <b style=\"color:#C9A24B\">neutron numbers</b>.","The <b style=\"color:#C9A24B\">Rutherford scattering</b> experiment showed a tiny, dense nucleus.","The <b style=\"color:#C9A24B\">Bohr model</b> added quantised electron shells to the nuclear model.","Isotopic notation uses ^A_ZX where A varies while Z stays constant for a given element."],
      conceptNote: "<b>Tip:</b> When given an isotope, focus on neutrons = mass number – atomic number.",
      glossary: [{"term":"isotope","def":"atoms with same Z but different A"},{"term":"Rutherford experiment","def":"gold foil scattering that revealed the nucleus"},{"term":"mass number","def":"total protons + neutrons in the nucleus"}],
      diagramLabel: "Try it: Quick reference",
      Diagram: PhysicsAtomicStructureIsotopesAndTheNuclearModelDemo,
      worked: {"question":"An atom has 15 protons and 16 neutrons. Write its nuclear symbol and name the element.","fastMethod":"Atomic number 15 → phosphorus (P); mass number = 15+16 = 31.","steps":["Calculate mass number: 15 + 16 = 31.","Identify element with Z=15 → phosphorus (P).","Write symbol ^31_15P."],"answer":"^31_15P"},
      selfCheck: {"prompt":"True or false: Isotopes of the same element have different chemical properties.","answer":"False – they have almost identical chemical behaviour; only nuclear properties differ."},
      questions: [{"id":"isotopes-and-the-nuclear-model-q1","prompt":"How many neutrons are in ^23_11Na?","accept":["12","twelve"],"hint":"Subtract atomic number from mass number."},{"id":"isotopes-and-the-nuclear-model-q2","prompt":"Name the experiment that first demonstrated the existence of a nucleus.","accept":["rutherford scattering","rutherford experiment"],"hint":"Gold foil and α‑particles."},{"id":"isotopes-and-the-nuclear-model-q3","prompt":"Calculate the mass number of an isotope with 82 protons and 126 neutrons.","accept":["208","two hundred eight"],"hint":"Add protons and neutrons."}],
      mistakes: ["Mixing up atomic number with neutron number when writing isotopes.","Assuming isotopes have different chemical reactivity."],
      examTip: "When a question asks for an isotope’s symbol, always give both superscript (mass) and subscript (atomic) numbers; missing one loses marks.",
      searchTerms: ["isotopes definition","rutherford gold foil experiment","bohr model vs nuclear model","calculate neutrons","AQA isotope notation"],
    },
    {
      id: "radioactive-decay-half-life-and-radiation-uses",
      title: "Radioactive decay, half‑life and radiation uses",
      tier: "Extension",
      objective: "Interpret decay equations, calculate half‑life problems and evaluate applications and hazards of radiation.",
      whyMatters: "Half‑life calculations are a common GCSE exam task; understanding risks is required for extended‑answer questions.",
      conceptTitle: "Decay, half‑life and applications",
      conceptBullets: ["Alpha (α) decay emits a <b style=\"color:#C9A24B\">helium nucleus</b> (2 protons, 2 neutrons).","Beta (β) decay converts a neutron to a <b style=\"color:#C9A24B\">proton + electron</b>, increasing Z by 1.","Half‑life is the time for <b style=\"color:#C9A24B\">half the nuclei</b> in a sample to decay, following exponential decay.","Radiation is used in <b style=\"color:#C9A24B\">medical imaging, sterilisation and power generation</b>, but can cause cell damage."],
      conceptNote: "<b>Tip:</b> Write the decay equation first; the change in Z and A tells you whether it is α or β decay.",
      glossary: [{"term":"half‑life","def":"time for 50% of a radioactive sample to decay"},{"term":"alpha decay","def":"emission of a ^4_2He nucleus"},{"term":"beta decay","def":"emission of an electron, neutron → proton"}],
      diagramLabel: "Try it: Key facts",
      Diagram: PhysicsAtomicStructureRadioactiveDecayHalfLifeAndRadiationUsesDemo,
      worked: {"question":"A sample contains 80 g of a radioactive isotope with a half‑life of 5 years. How much remains after 15 years?","fastMethod":"Three half‑lives → (½)³ = 1/8 of the original.","steps":["Determine number of half‑lives: 15 ÷ 5 = 3.","Calculate remaining fraction: (½)^3 = 1/8.","Multiply: 80 g × 1/8 = 10 g."],"answer":"10 g"},
      selfCheck: {"prompt":"True or false: In β‑decay the mass number of the nucleus changes.","answer":"False – A stays the same; only the atomic number increases by 1."},
      questions: [{"id":"radioactive-decay-half-life-and-radiation-uses-q1","prompt":"Write the nuclear equation for the α‑decay of ^226_88Ra.","accept":["^222_86Rn + ^4_2He","^222_86Rn + α"],"hint":"Subtract 4 from A and 2 from Z."},{"id":"radioactive-decay-half-life-and-radiation-uses-q2","prompt":"What is the remaining fraction after 2 half‑lives?","accept":["0.25","one quarter"],"hint":"Use (½)^2."},{"id":"radioactive-decay-half-life-and-radiation-uses-q3","prompt":"Name one advantage and one disadvantage of using radiation in medicine.","accept":["targeted treatment, cell damage","diagnostic imaging, radiation risk"],"hint":"Think of radiotherapy vs side effects."}],
      mistakes: ["Treating β‑decay as loss of mass number instead of change in Z.","Using linear decay instead of exponential when calculating half‑life."],
      examTip: "When asked for the amount remaining, always express the answer to the required significant figures and include units (g, Bq, etc.).",
      searchTerms: ["alpha beta decay equations","half life calculation GCSE","radioactive decay applications","radiation safety AQA","exponential decay formula"],
    }
  ],
};
