import type { TopicContent } from "../types";
import {
  DependentPrepositionsDemo,
  EndOfSentencePrepositionDemo,
  CoordinatingSubordinatingDemo,
  CorrelativeConjunctionsDemo,
  WhatArePrepositionsDemo,
  WhatAreConjunctionsDemo,
  PrepositionsTimePlaceMovementDemo,
  PrepositionOrPhrasalVerbParticleDemo,
  ConjunctiveAdverbsDemo,
} from "../notes-diagrams/prepositions-conjunctions-demos";

const CLICK_INSTRUCTION = "Click the word with the error.";

export const prepositionsConjunctionsTopic: TopicContent = {
  slug: "prepositions-conjunctions",
  subject: "English",
  subjectSlug: "english",
  title: "Grammar: Prepositions & Conjunctions",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "Parts of Speech Errors introduced prepositions and conjunctions as word classes — this module goes deeper: the fixed preposition partnerships that just have to be learned, the sentence-ending-preposition myth, the difference between coordinating and subordinating conjunctions, and the correlative conjunction pairs that must always match.",
  subtopics: [
    {
      id: "what-are-prepositions",
      title: "What Are Prepositions?",
      tier: "Foundation",
      objective: "Recognise a preposition as a word that links a noun or pronoun to the rest of the sentence, showing place, time, direction or relationship.",
      whyMatters: "GL papers lean on prepositions to test fixed grammatical relationships rather than vocabulary, so knowing what job a preposition does is the first step before spotting when the wrong one has been used.",
      conceptTitle: "A linking word, not a naming word",
      conceptBullets: [
        'A <b style="color:#C9A24B">preposition</b> is a word that links a noun or pronoun to the rest of the sentence, showing where, when, or how something relates to something else.',
        "Common prepositions include in, on, at, under, before, after, between, through.",
        "Prepositions usually show place (under the table), time (before lunch), direction (through the tunnel), or relationship (with her friend).",
        "Unlike most vocabulary questions, preposition questions test a fixed grammatical relationship — usually only one preposition correctly fits, not several interchangeable near-synonyms.",
      ],
      conceptNote: "<b>Spot it:</b> if a short word sits between a noun and the rest of the sentence and answers where, when, or how, it's almost always a preposition.",
      glossary: [
        { term: "preposition", def: "a linking word showing place, time, direction or relationship (in, on, at, before)" },
        { term: "preposition of place", def: "shows where something is (under, on, between)" },
        { term: "preposition of time", def: "shows when something happens (before, after, at)" },
        { term: "preposition of direction", def: "shows movement towards or through somewhere (through, towards, into)" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: WhatArePrepositionsDemo,
      worked: {
        question: "Identify the prepositions and their jobs: “The cat hid under the stairs before dinner.”",
        fastMethod: "scan for short linking words, then ask what job each one is doing — place, time, direction, or relationship.",
        steps: [
          "Find the short linking words: “under” and “before”.",
          "“under the stairs” answers where — a preposition of place.",
          "“before dinner” answers when — a preposition of time.",
          "Each preposition links a noun (the stairs, dinner) back to the rest of the sentence.",
        ],
        answer: "“Under” shows <b>place</b> and “before” shows <b>time</b>.",
      },
      selfCheck: { prompt: "True or false: a preposition can show place, time, direction, or relationship, but always links to a noun or pronoun.", answer: "<b>True</b> — that linking job is exactly what makes a word a preposition." },
      kind: "click-error",
      questions: [
        {
          id: "wap-q1",
          instruction: "Click the word with the error.",
          words: ["The", "keys", "are", "in", "the", "table."],
          errorIdx: 3,
          correction: '"in" suggests the keys are inside the table — resting on its surface needs "on": the keys are on the table.',
          hint: "Check whether the keys are inside the table or resting on top of its surface.",
        },
        {
          id: "wap-q2",
          instruction: "Click the word with the error.",
          words: ["School", "starts", "on", "9", "o'clock."],
          errorIdx: 2,
          correction: '"on" is used for days and dates — a precise clock time needs "at": starts at 9 o\'clock.',
          hint: "Check the size of the time period — a precise clock time needs a different preposition than a day or date does.",
        },
        {
          id: "wap-q3",
          instruction: "Click the word with the error.",
          words: ["She", "walked", "in", "the", "room", "and", "sat", "down."],
          errorIdx: 2,
          correction: '"in" shows a fixed position, not movement — walking towards and inside a room needs "into": walked into the room.',
          hint: "Decide whether this describes a journey happening now, or a position already reached.",
        },
      ],
      mistakes: [
        "Treating every short word before a noun as automatically correct without checking whether it actually fits the place, time, or direction being described.",
        "Confusing a preposition of position (in, on) with a preposition of movement (into, onto) when the sentence describes a journey.",
      ],
      examTip: "Before anything else, ask what job the small linking word is doing — place, time, direction, or relationship — then check it's the one preposition that fits that job.",
      searchTerms: ["preposition", "linking word", "place time direction", "in on at", "basic grammar"],
    },
    {
      id: "what-are-conjunctions",
      title: "What Are Conjunctions?",
      tier: "Foundation",
      objective: "Recognise a conjunction as a word that joins words, phrases, or clauses, and learn the seven basic coordinating conjunctions (FANBOYS).",
      whyMatters: "spotting a conjunction and knowing its basic job is the foundation for every later question about joining clauses correctly, including the more advanced coordinating/subordinating distinction tested later.",
      conceptTitle: "A joining word, not a naming word",
      conceptBullets: [
        'A <b style="color:#C9A24B">conjunction</b> is a word that joins two words, phrases, or clauses together.',
        "The seven coordinating conjunctions are easy to remember with the acronym FANBOYS: for, and, nor, but, or, yet, so.",
        'Example: "I wanted to play outside, but it was raining" — "but" joins two complete ideas.',
        "At this basic level, all that matters is spotting that a conjunction is doing a joining job somewhere in the sentence — the deeper coordinating vs subordinating distinction comes later.",
      ],
      conceptNote: "<b>Remember:</b> FANBOYS — for, and, nor, but, or, yet, so — are the seven basic joining words to learn first.",
      glossary: [
        { term: "conjunction", def: "a word that joins words, phrases, or clauses" },
        { term: "FANBOYS", def: "the seven coordinating conjunctions: for, and, nor, but, or, yet, so" },
        { term: "clause", def: "a group of words containing a subject and a verb" },
        { term: "phrase", def: "a group of words without a full subject-and-verb clause" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: WhatAreConjunctionsDemo,
      worked: {
        question: "Find the conjunction and its job: “I packed my bag and left for school.”",
        fastMethod: "scan the sentence for one of the FANBOYS words joining two ideas together.",
        steps: [
          "Check each word against the FANBOYS list: for, and, nor, but, or, yet, so.",
          "“and” appears, joining “I packed my bag” to “left for school”.",
          "Confirm it's doing a joining job, not naming or describing anything.",
          "“And” is the conjunction, linking the two actions into one sentence.",
        ],
        answer: "The conjunction is <b>and</b>.",
      },
      selfCheck: { prompt: "True or false: the word “quickly” in “she ran quickly” is a conjunction.", answer: "<b>False</b> — “quickly” describes how she ran; it doesn't join two words, phrases, or clauses, so it isn't a conjunction." },
      kind: "click-error",
      questions: [
        {
          id: "wac-q1",
          instruction: "Click the word with the error.",
          words: ["I", "like", "tea", "nor", "coffee."],
          errorIdx: 3,
          correction: '"nor" only follows a negative word like "neither" — a simple choice here needs "or": tea or coffee.',
          hint: "Check whether this sentence contains a negative word like “neither” earlier on — if not, this word doesn't fit.",
        },
        {
          id: "wac-q2",
          instruction: "Click the word with the error.",
          words: ["It", "was", "cold,", "or", "I", "wore", "a", "coat."],
          errorIdx: 3,
          correction: '"or" doesn\'t show a result — the cold caused the coat-wearing, so the joining word should be "so": It was cold, so I wore a coat.',
          hint: "Think about whether the second half of the sentence is offering a choice, or showing the result of the first half.",
        },
        {
          id: "wac-q3",
          instruction: "Click the word with the error.",
          words: ["She", "wanted", "pizza", "but", "pasta", "for", "dinner."],
          errorIdx: 3,
          correction: '"but" signals a contrast — this sentence is offering a choice between two foods, which needs "or": pizza or pasta.',
          hint: "Decide whether the sentence is contrasting two ideas or offering a choice between them.",
        },
      ],
      mistakes: [
        "Confusing a conjunction with a preposition, since both can be short, easily-overlooked words.",
        "Assuming only “and” counts as a conjunction and missing the other six FANBOYS words.",
      ],
      examTip: "Learn FANBOYS as a fixed list — for, and, nor, but, or, yet, so — so you can spot a coordinating conjunction instantly, whichever one appears.",
      searchTerms: ["conjunction", "fanboys", "joining word", "coordinating conjunction", "clause"],
    },
    {
      id: "prepositions-time-place-movement",
      title: "Prepositions of Time, Place, and Movement",
      tier: "Standard",
      objective: "Apply the three functional categories of prepositions — time, place, and movement — using at/in/on and to/into/onto/through correctly in each.",
      whyMatters: "mixing up in/on/at for time and place is one of the most common preposition errors on GL papers, and movement prepositions like into/onto are frequently swapped for the static in/on by mistake.",
      conceptTitle: "Three jobs, three rules",
      conceptBullets: [
        'Prepositions of <b style="color:#C9A24B">time</b> follow a size pattern: <i>at</i> for a precise time (at 3 o\'clock), <i>on</i> for a day or date (on Tuesday), <i>in</i> for a longer period (in July, in 2020).',
        "Prepositions of place follow the same size pattern: at for a point (at the bus stop), on for a surface (on the shelf), in for an enclosed space (in the box).",
        "Prepositions of movement show a journey towards or through somewhere: to a place, into/onto a space or surface, through a space you pass across.",
        "The exam trap is using a place preposition (in/on/at) where a movement preposition is needed, or vice versa: “jumped in the pool” (already inside) vs “jumped into the pool” (movement towards).",
      ],
      conceptNote: "<b>Test it:</b> ask whether the sentence describes a fixed position (use in/on/at) or a journey towards/onto/into something (use to/into/onto/through).",
      glossary: [
        { term: "preposition of time", def: "at a precise time, on a day/date, in a longer period" },
        { term: "preposition of place", def: "at a point, on a surface, in an enclosed space" },
        { term: "preposition of movement", def: "shows a journey: to, into, onto, through" },
        { term: "static preposition", def: "describes a fixed position rather than movement (in, on, at)" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: PrepositionsTimePlaceMovementDemo,
      worked: {
        question: "Spot the error: “The children jumped in the swimming pool from the diving board.”",
        fastMethod: "check whether the sentence describes movement (jumping from the board towards the pool) or a fixed position — movement needs “into”, not “in”.",
        steps: [
          "Identify the verb of movement: “jumped … from the diving board”.",
          "“in” only shows a fixed position, not the journey being described.",
          "A journey towards and inside the pool needs the movement preposition “into”.",
          "Corrected: “The children jumped into the swimming pool from the diving board.”",
        ],
        answer: "The error is <b>in</b> — it should be <b>into</b>.",
      },
      selfCheck: { prompt: "True or false: “in” and “into” can always be swapped without changing the meaning of a sentence.", answer: "<b>False</b> — “in” shows a fixed position, while “into” shows movement towards and inside somewhere; swapping them changes the meaning." },
      kind: "click-error",
      questions: [
        {
          id: "tpm-q1",
          instruction: "Click the word with the error.",
          words: ["The", "exam", "starts", "in", "9am", "sharp."],
          errorIdx: 3,
          correction: '"in" is used for longer periods — a precise clock time needs "at": starts at 9am.',
          hint: "Check the size of the time period — a precise clock time needs the smallest preposition in the pattern.",
        },
        {
          id: "tpm-q2",
          instruction: "Click the word with the error.",
          words: ["The", "trophy", "is", "sitting", "in", "the", "shelf."],
          errorIdx: 4,
          correction: '"in" suggests an enclosed space — a shelf is a flat surface, which needs "on": sitting on the shelf.',
          hint: "Decide whether a shelf is an enclosed space or a flat surface.",
        },
        {
          id: "tpm-q3",
          instruction: "Click the word with the error.",
          words: ["The", "birds", "were", "sitting", "into", "the", "tall", "oak", "tree."],
          errorIdx: 4,
          correction: '"into" shows movement — the birds are already positioned there, which needs the static preposition "in": sitting in the tall oak tree.',
          hint: "Check whether this describes a journey happening now, or a fixed position already reached.",
        },
      ],
      mistakes: [
        "Mixing up the size pattern for time and place — using “on” for a precise clock time or “at” for a whole month.",
        "Using a static preposition (in/on/at) for a sentence that actually describes movement, or the reverse.",
      ],
      examTip: "Ask two questions in order: is this time or place, then is this a fixed position or a movement — the answer decides which of at/in/on/into/onto/through fits.",
      searchTerms: ["prepositions of time", "prepositions of place", "prepositions of movement", "at in on", "into onto"],
    },
    {
      id: "dependent-prepositions",
      title: "Dependent Prepositions & Fixed Phrases",
      tier: "Standard",
      objective: "Recognise that many adjectives and verbs are always followed by one specific preposition, and spot when the wrong one has been used.",
      whyMatters: "dependent prepositions can't be worked out from logic alone — each pairing has to be learned, and GL papers test exactly these fixed partnerships.",
      conceptTitle: "Some words only ever take one partner",
      conceptBullets: [
        'A <b style="color:#C9A24B">dependent preposition</b> is the one preposition that fixed idiom always uses after a particular adjective or verb.',
        'Examples: <i>interested in</i>, <i>afraid of</i>, <i>different from</i>, <i>good at</i>, <i>depend on</i>, <i>arrive at</i>.',
        "There is no single rule that predicts which preposition a word takes — these pairings have to be learned individually, the way vocabulary is learned.",
        "Swapping in a preposition that seems logical (like “interested on” instead of “interested in”) still reads as wrong to a fluent ear, even without a rule to point to.",
      ],
      conceptNote: "<b>Remember:</b> when in doubt, say the phrase aloud — a wrong dependent preposition almost always sounds instantly odd, even if you can't explain the rule.",
      glossary: [
        { term: "dependent preposition", def: "the one fixed preposition a word always takes (afraid of, good at)" },
        { term: "fixed phrase", def: "a word pairing that doesn't change, however logical an alternative might seem" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: DependentPrepositionsDemo,
      worked: {
        question: "Spot the error: “The results were different than what we expected.”",
        fastMethod: '"different" is a fixed pairing with "from" in careful written English, not "than".',
        steps: [
          "Identify the adjective with a dependent preposition: “different”.",
          "Recall its fixed partner: “different from”, not “different than”.",
          "Swap in the correct preposition.",
          "Corrected: “The results were different from what we expected.”",
        ],
        answer: "The error is <b>than</b> — it should be <b>from</b>.",
      },
      selfCheck: { prompt: "True or false: “good in maths” is the correct fixed phrase.", answer: "<b>False</b> — the dependent preposition for “good” is “at”: good at maths." },
      kind: "click-error",
      questions: [
        {
          id: "dp-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Ali", "was", "afraid", "from", "the", "dark", "corridor", "at", "the", "back", "of", "the", "school."],
          errorIdx: 3,
          correction: '"afraid" pairs with "of", not "from": afraid of the dark corridor.',
          hint: "Check the fixed preposition that always follows this adjective for fear.",
        },
        {
          id: "dp-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "whole", "trip", "depends", "in", "the", "weather", "staying", "dry", "this", "weekend."],
          errorIdx: 4,
          correction: '"depends" pairs with "on", not "in": depends on the weather.',
          hint: "Check the fixed preposition that always follows this verb about relying on something.",
        },
        {
          id: "dp-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["We", "finally", "arrived", "to", "the", "station", "with", "two", "minutes", "to", "spare."],
          errorIdx: 3,
          correction: '"arrived" pairs with "at" (for a place) or "in" (for a city/country), not "to": arrived at the station.',
          hint: "Check the fixed preposition this verb of arrival takes before a place.",
        },
      ],
      mistakes: [
        "Choosing a preposition that seems logical rather than learning the one fixed partner each word actually takes.",
        "Mixing up near-synonyms that take different prepositions, like “different from” vs “similar to”.",
      ],
      examTip: "Keep a running list of adjective/verb + preposition pairs as you meet them — these can't be reasoned out, only memorised.",
      searchTerms: ["dependent preposition", "fixed phrase", "interested in", "afraid of", "different from"],
    },
    {
      id: "sentence-ending-prepositions",
      title: "Ending a Sentence with a Preposition",
      tier: "Standard",
      objective: "Recognise that ending a sentence with a preposition is grammatically acceptable in modern English, and spot when avoiding it makes writing stiff or unnatural.",
      whyMatters: "some students learn the old myth that a sentence must never end in a preposition and awkwardly rewrite perfectly good sentences to avoid it, losing marks for unnatural style.",
      conceptTitle: "A myth worth unlearning",
      conceptBullets: [
        'The idea that a sentence can never end with a <b style="color:#C9A24B">preposition</b> is a long-standing myth, not a real grammar rule.',
        'Example: "What are you looking for?" is completely correct — rewriting it as "For what are you looking?" is stiff and old-fashioned, not more correct.',
        "The rule matters when moving the preposition creates genuine ambiguity or clumsiness, not simply because it lands at the end.",
        "GL-style “complete the sentence” questions sometimes offer an artificially rearranged option as a trap — the natural, sentence-ending version is often the better fit.",
      ],
      conceptNote: "<b>Test it:</b> read both versions aloud — if moving the preposition earlier sounds forced or old-fashioned, the natural sentence-ending version is usually the better choice.",
      glossary: [
        { term: "preposition", def: "a word like to, at, with, about that links a noun to the rest of a sentence" },
        { term: "register", def: "how formal or natural a piece of writing sounds" },
      ],
      diagramLabel: "Interactive · Spot the Stiff Rewrite",
      Diagram: EndOfSentencePrepositionDemo,
      worked: {
        question: "Which is the more natural sentence: “Who did you go with?” or “With whom did you go?”",
        fastMethod: "Both are grammatically correct — but one matches how confident modern writers actually write.",
        steps: [
          "Check whether either version breaks a real grammar rule — neither does.",
          "“With whom did you go?” follows the old myth about never ending on a preposition.",
          "“Who did you go with?” is natural and entirely acceptable in modern written English.",
          "Either can be correct, but exam “best fit” questions usually reward the natural-sounding option unless told to write formally.",
        ],
        answer: "Both are grammatically valid; <b>“Who did you go with?”</b> is the more natural modern choice.",
      },
      selfCheck: { prompt: "True or false: a sentence is always wrong if it ends with a preposition.", answer: "<b>False</b> — this is a myth; ending a sentence with a preposition is accepted in modern English and often sounds more natural than the alternative." },
      kind: "click-error",
      questions: [
        {
          id: "eosp-q1",
          instruction: "Click the word that has been moved purely to avoid ending the sentence on a preposition, making it sound stiff.",
          words: ["This", "is", "the", "friend", "with", "whom", "I", "went", "camping."],
          errorIdx: 4,
          correction: '"with" has been dragged forward purely to dodge ending on a preposition — "this is the friend I went camping with" is the natural, equally correct version.',
          hint: "Look for the preposition sitting earlier than it needs to, right before “whom”.",
        },
        {
          id: "eosp-q2",
          instruction: "Click the word that has been moved purely to avoid ending the sentence on a preposition, making it sound stiff.",
          words: ["That", "is", "the", "shop", "at", "which", "I", "bought", "my", "shoes."],
          errorIdx: 4,
          correction: '"at" has been dragged forward — "that\'s the shop I bought my shoes at" is the natural, equally correct version.',
          hint: "Look for the preposition sitting earlier than it needs to, right before “which”.",
        },
        {
          id: "eosp-q3",
          instruction: "Click the word that has been moved purely to avoid ending the sentence on a preposition, making it sound stiff.",
          words: ["I", "don't", "know", "for", "what", "reason", "she", "left", "so", "suddenly."],
          errorIdx: 3,
          correction: '"for" has been dragged forward unnaturally — "I don\'t know what reason she left so suddenly for" (or better, "why she left so suddenly") reads more naturally.',
          hint: "Look for the preposition placed earlier than it needs to be, before “what reason”.",
        },
      ],
      mistakes: [
        "Believing ending a sentence with a preposition is always a grammar error — it isn't, and forcing an awkward rewrite can actually cost style marks.",
        "Over-applying the fix even when it makes a sentence sound far stiffer than the natural version.",
      ],
      examTip: "If a “best fit” option sounds like it's been rearranged just to avoid ending on a preposition, the natural sentence-ending version is usually the better answer.",
      searchTerms: ["preposition", "end of sentence", "myth", "natural English", "style"],
    },
    {
      id: "coordinating-subordinating-conjunctions",
      title: "Coordinating vs. Subordinating Conjunctions",
      tier: "Standard",
      objective: "Tell apart coordinating conjunctions (joining equal ideas) and subordinating conjunctions (joining a dependent clause to a main clause), and spot when both have been used redundantly together.",
      whyMatters: "pairing a subordinating and a coordinating conjunction together (“because… so…”) is one of the most common conjunction errors, since each already does the linking job alone.",
      conceptTitle: "Two different jobs",
      conceptBullets: [
        'A <b style="color:#C9A24B">coordinating conjunction</b> (and, but, or, so, yet, for, nor) joins two equal, independent ideas.',
        'A <b>subordinating conjunction</b> (because, although, since, while, if) joins a dependent clause to a main clause, and already does the linking job by itself.',
        'Using both together — "because it was raining, so we stayed in" — repeats the same job twice; only one conjunction is needed.',
        "Remove either the subordinating conjunction or the coordinating one, whichever makes the sentence read more naturally.",
      ],
      conceptNote: "<b>Test it:</b> if a sentence starts with because/although/since and also has and/so/but part-way through joining the same two ideas, one of them is redundant.",
      glossary: [
        { term: "coordinating conjunction", def: "joins two equal ideas (and, but, or, so)" },
        { term: "subordinating conjunction", def: "joins a dependent clause to a main clause (because, although, since)" },
        { term: "redundant", def: "unnecessary because the same job is already being done elsewhere" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: CoordinatingSubordinatingDemo,
      worked: {
        question: "Spot the error: “Although the shop was closed, but we still peered through the window.”",
        fastMethod: '"although" already sets up the contrast on its own — "but" repeats the same job and should be removed.',
        steps: [
          "Identify the subordinating conjunction: “although”, which already links the two ideas.",
          "Spot the coordinating conjunction “but”, doing the same linking job again.",
          "Only one is needed — remove the redundant one.",
          "Corrected: “Although the shop was closed, we still peered through the window.”",
        ],
        answer: "The error is <b>but</b> — it should be removed.",
      },
      selfCheck: { prompt: "True or false: “and” and “because” can be correctly used to join the same two clauses in one sentence.", answer: "<b>False, if they repeat the same link</b> — “because” already joins the ideas by itself; adding a coordinating conjunction on top usually creates a redundant repeat of the same job." },
      kind: "click-error",
      questions: [
        {
          id: "cs-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Since", "the", "bus", "was", "late,", "so", "we", "decided", "to", "walk", "instead."],
          errorIdx: 5,
          correction: '"since" already links the two ideas — "so" repeats the job and should be removed.',
          hint: "This sentence starts with a subordinating conjunction — check whether a coordinating one repeats the same link later on.",
        },
        {
          id: "cs-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["While", "she", "practised", "the", "piano,", "but", "her", "brother", "did", "his", "homework."],
          errorIdx: 5,
          correction: '"while" already links the two ideas — "but" repeats the job and should be removed.',
          hint: "Check whether the linking word at the start is being echoed unnecessarily part-way through.",
        },
        {
          id: "cs-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["If", "it", "rains", "tomorrow,", "then", "so", "the", "match", "will", "be", "postponed."],
          errorIdx: 5,
          correction: '"if… then" already links the condition to its result — the extra "so" is redundant and should be removed.',
          hint: "This conditional sentence has one linking word too many part-way through.",
        },
      ],
      mistakes: [
        "Pairing a subordinating conjunction at the start of a sentence with a coordinating conjunction that repeats the link.",
        "Assuming more linking words always make a sentence clearer, when in fact one is doing the job on its own.",
      ],
      examTip: "If a sentence opens with because, although, since, while or if, check whether a second conjunction later on is quietly repeating the same job — it should be removed.",
      searchTerms: ["coordinating conjunction", "subordinating conjunction", "because so", "although but", "redundant"],
    },
    {
      id: "correlative-conjunctions",
      title: "Correlative Conjunctions",
      tier: "Extension",
      objective: "Recognise correlative conjunction pairs (either/or, neither/nor, not only/but also, both/and) and spot when the wrong second half has been used.",
      whyMatters: "correlative conjunctions always travel as a fixed matching pair, and mismatching them — especially “neither… or” instead of “neither… nor” — is a frequent and easy-to-spot exam trap once you know the pairs.",
      conceptTitle: "Fixed pairs that must match",
      conceptBullets: [
        'A <b style="color:#C9A24B">correlative conjunction</b> is a linking word that always comes with a matching partner: <i>either… or</i>, <i>neither… nor</i>, <i>not only… but also</i>, <i>both… and</i>.',
        "Each pair is fixed — “either” always needs “or”, and “neither” always needs “nor”, never “or”.",
        'Example: "neither the cat nor the dog was hungry" — swapping "nor" for "or" breaks the fixed pairing.',
        "These pairs should also join grammatically matching parts of a sentence, keeping the structure balanced on both sides.",
      ],
      conceptNote: "<b>Memory trick:</b> “neither” and “nor” both start with n — they belong together, never “neither… or”.",
      glossary: [
        { term: "correlative conjunction", def: "a linking word that always comes with a fixed matching partner" },
        { term: "either… or", def: "presents a choice between two positive options" },
        { term: "neither… nor", def: "rules out both of two options" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: CorrelativeConjunctionsDemo,
      worked: {
        question: "Spot the error: “Either the twins or her sister are collecting the trophy.”",
        fastMethod: 'the correlative pair "either… or" is used correctly here — this sentence actually tests subject-verb agreement instead: check "are" against the nearer subject "her sister".',
        steps: [
          "Confirm the correlative pair itself: “either… or” is correctly matched.",
          "With “either… or”, the verb usually agrees with the nearer subject, “her sister” (singular).",
          "A singular nearer subject needs a singular verb.",
          "Corrected: “Either the twins or her sister is collecting the trophy.”",
        ],
        answer: "The error is <b>are</b> — it should be <b>is</b>.",
      },
      selfCheck: { prompt: "True or false: “not only… or also” is a correctly matched correlative pair.", answer: "<b>False</b> — the fixed pairing is “not only… but also”, never “not only… or also”." },
      kind: "click-error",
      questions: [
        {
          id: "cc-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "recipe", "needs", "either", "butter", "and", "margarine", "to", "work", "properly."],
          errorIdx: 5,
          correction: '"either" is always paired with "or", never "and": either butter or margarine.',
          hint: "Check the fixed second half that always accompanies “either”.",
        },
        {
          id: "cc-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "is", "not", "only", "the", "captain", "but", "also", "or", "the", "top", "scorer."],
          errorIdx: 8,
          correction: '"not only… but also" is the fixed pairing — the extra "or" doesn\'t belong and should be removed.',
          hint: "Check whether an extra linking word has crept in after the fixed pair “but also”.",
        },
        {
          id: "cc-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Both", "the", "teacher", "or", "the", "headteacher", "signed", "the", "letter."],
          errorIdx: 3,
          correction: '"both" is always paired with "and", never "or": both the teacher and the headteacher.',
          hint: "Check the fixed second half that always accompanies “both”.",
        },
      ],
      mistakes: [
        "Mixing halves of two different correlative pairs, especially “neither… or” instead of “neither… nor”.",
        "Forgetting that with “either… or” and “neither… nor”, the verb agrees with whichever subject is nearer to it.",
      ],
      examTip: "Learn the four fixed pairs by heart — either/or, neither/nor, not only/but also, both/and — and treat any mismatched combination as an automatic error.",
      searchTerms: ["correlative conjunction", "either or", "neither nor", "not only but also", "both and"],
    },
    {
      id: "preposition-or-phrasal-verb-particle",
      title: "Preposition or Phrasal Verb Particle?",
      tier: "Extension",
      objective: "Distinguish a true preposition, which links to the noun that follows it, from a particle that is part of a phrasal verb and behaves differently.",
      whyMatters: "GL papers sometimes disguise a phrasal verb particle as if it were a broken preposition link, and misreading it that way leads to marking a perfectly correct sentence as wrong.",
      conceptTitle: "Same word, different job",
      conceptBullets: [
        'A true <b style="color:#C9A24B">preposition</b> links to the noun or pronoun that follows it, showing place, time, direction or relationship — e.g. "sat on the chair."',
        'A <b>phrasal verb particle</b> looks identical to a preposition but is actually part of the verb itself, changing its meaning — e.g. "look up the word" ("look up" = to search for, not "up" linking to "the word" the way a preposition would).',
        "One test: many phrasal verb particles can move after the object (look the word up), which a true preposition never can (a preposition always stays directly before its noun).",
        "Another test: ask whether the verb's meaning actually changes because of the small word — if it does (look vs look up), it's a particle; if the verb's meaning stays the same, it's a preposition doing its usual linking job.",
      ],
      conceptNote: "<b>Test it:</b> ask whether the small word is linking to the noun after it (preposition) or glued to the verb before it to create a new meaning (particle).",
      glossary: [
        { term: "preposition", def: "a word linking to the following noun, showing place, time, direction or relationship" },
        { term: "phrasal verb", def: "a verb plus a particle that together create a new meaning (look up, give away)" },
        { term: "particle", def: "the small word attached to a phrasal verb, not linking to a noun the way a preposition does" },
        { term: "separable phrasal verb", def: "a phrasal verb whose particle can move after the object (turn the light off)" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: PrepositionOrPhrasalVerbParticleDemo,
      worked: {
        question: "Is “up” a preposition or a particle here: “She climbed up the ladder carefully”?",
        fastMethod: "check whether the small word links to the noun after it showing direction, or whether it's glued to the verb to form a brand-new meaning.",
        steps: [
          "Identify the verb: “climbed”.",
          "Ask whether “climbed up” means something different from “climbed” alone — it doesn't; “up” still just shows direction.",
          "Since “up” links to “the ladder” to show direction, without changing the verb's meaning, it is behaving as a preposition here.",
          "Compare with “look up the word”, where “look up” means “to search for” — a genuinely new meaning, so “up” is a particle there instead.",
        ],
        answer: "“Up” is a <b>preposition</b> here, linking to “the ladder” — not a phrasal verb particle.",
      },
      selfCheck: { prompt: "True or false: a small word like “up” or “off” always does the same job wherever it appears.", answer: "<b>False</b> — the same word can be a true preposition in one sentence and a phrasal verb particle in another, depending on whether it changes the verb's meaning." },
      kind: "click-error",
      questions: [
        {
          id: "popvp-q1",
          instruction: "Click the word with the error.",
          words: ["He", "got", "the", "illness", "over", "quickly."],
          errorIdx: 4,
          correction: '"get over" is an inseparable phrasal verb — its particle "over" can\'t be split from the verb by the object: he got over the illness quickly.',
          hint: "This phrasal verb's particle isn't allowed to split away from its verb — check where it's been moved to.",
        },
        {
          id: "popvp-q2",
          instruction: "Click the word with the error.",
          words: ["She", "sat", "the", "chair", "on."],
          errorIdx: 4,
          correction: '"on" here is a true preposition linking to "chair", not a separable phrasal-verb particle like the "up" in "look up" — it must stay directly before its noun: sat on the chair.',
          hint: "This preposition has been dragged to the end as if it were a separable phrasal-verb particle — but it isn't one.",
        },
        {
          id: "popvp-q3",
          instruction: "Click the word with the error.",
          words: ["She", "looks", "the", "baby", "after", "every", "day."],
          errorIdx: 4,
          correction: '"look after" (meaning to take care of) is an inseparable phrasal verb — its particle "after" can\'t be split from the verb by the object: she looks after the baby every day.',
          hint: "This phrasal verb meaning “to take care of” doesn't allow its two halves to be pulled apart by the object — check where the second half has been moved to.",
        },
      ],
      mistakes: [
        "Assuming every small word directly before a noun must be a true preposition, without checking whether it's actually a phrasal verb particle.",
        "Treating an inseparable phrasal verb's particle as if it could be moved after the object like a separable one can.",
      ],
      examTip: "If moving the small word changes whether the sentence still makes sense, or the verb's meaning shifts completely without it, you're looking at a phrasal verb particle, not a preposition.",
      searchTerms: ["phrasal verb", "particle", "preposition or particle", "separable verb", "look up"],
    },
    {
      id: "conjunctive-adverbs-vs-coordinating-conjunctions",
      title: "Conjunctive Adverbs vs. Coordinating Conjunctions",
      tier: "Extension",
      objective: "Recognise that words like however, therefore, moreover and nevertheless are conjunctive adverbs, not coordinating conjunctions, and need a semicolon or full stop — not a comma — before them when joining two independent clauses.",
      whyMatters: "joining two independent clauses with just a comma before however/therefore is one of the most common punctuation errors at this level, and GL papers reward knowing exactly which punctuation mark such linking adverbs require.",
      conceptTitle: "They look like conjunctions, but they aren't",
      conceptBullets: [
        'A <b style="color:#C9A24B">conjunctive adverb</b> — words like <i>however, therefore, moreover, nevertheless, consequently</i> — links two independent clauses in meaning, but is grammatically an adverb, not a conjunction.',
        "Unlike a true coordinating conjunction (and, but, so), a conjunctive adverb cannot join two independent clauses with just a comma in front of it.",
        'Correct punctuation needs a semicolon or a full stop before it, and usually a comma straight after: "I was tired; however, I carried on." or "I was tired. However, I carried on."',
        'Incorrect: "I was tired, however I carried on." — a comma alone before "however" is too weak to join two independent clauses (a comma splice).',
      ],
      conceptNote: "<b>Test it:</b> if you can replace the linking word with “but” or “so” and the sentence still only needs a comma before it, it's a true coordinating conjunction; if it actually needs a semicolon or full stop instead, it's a conjunctive adverb.",
      glossary: [
        { term: "conjunctive adverb", def: "a linking adverb (however, therefore, moreover) needing a semicolon or full stop before it, not a comma" },
        { term: "comma splice", def: "wrongly joining two independent clauses with only a comma" },
        { term: "semicolon", def: "a punctuation mark strong enough to join two independent clauses" },
        { term: "independent clause", def: "a clause that could stand alone as a complete sentence" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: ConjunctiveAdverbsDemo,
      worked: {
        question: "Spot the punctuation error: “The bus was late, therefore we missed the start of the film.”",
        fastMethod: "check whether “therefore” is joining two independent clauses with only a comma — that's always too weak; it needs a semicolon or full stop.",
        steps: [
          "Identify the two independent clauses either side of “therefore”: “the bus was late” and “we missed the start of the film”.",
          "Notice only a comma separates them.",
          "Recall that conjunctive adverbs need a semicolon or full stop before them, not just a comma.",
          "Corrected: “The bus was late; therefore, we missed the start of the film.”",
        ],
        answer: "The error is the comma before <b>therefore</b> — it should be a semicolon.",
      },
      selfCheck: { prompt: "True or false: “however” can join two independent clauses with just a comma before it, the way “and” can.", answer: "<b>False</b> — “however” is a conjunctive adverb and needs a semicolon or full stop before it, not a comma, when joining two independent clauses." },
      kind: "click-error",
      questions: [
        {
          id: "cavc-q1",
          instruction: "Click the word with the error.",
          words: ["The", "bus", "was", "late,", "therefore", "we", "missed", "the", "start", "of", "the", "film."],
          errorIdx: 3,
          correction: '"however/therefore"-type conjunctive adverbs need a semicolon or full stop before them, not just a comma: "The bus was late; therefore, we missed the start of the film."',
          hint: "Check whether the punctuation right before “therefore” is strong enough to join two complete sentences.",
        },
        {
          id: "cavc-q2",
          instruction: "Click the word with the error.",
          words: ["I", "was", "tired,", "however", "I", "carried", "on."],
          errorIdx: 2,
          correction: '"however" is a conjunctive adverb, not a coordinating conjunction — a comma alone can\'t join two independent clauses in front of it: "I was tired; however, I carried on."',
          hint: "Check whether the comma before “however” is strong enough to link two complete sentences, or whether it creates a comma splice.",
        },
        {
          id: "cavc-q3",
          instruction: "Click the word with the error.",
          words: ["The", "forecast", "was", "poor,", "nevertheless", "the", "match", "went", "ahead", "as", "planned."],
          errorIdx: 3,
          correction: '"nevertheless" needs a semicolon or full stop before it, not a single comma, since it is joining two independent clauses: "The forecast was poor; nevertheless, the match went ahead as planned."',
          hint: "Check whether the punctuation before “nevertheless” is strong enough to separate two independent clauses.",
        },
      ],
      mistakes: [
        "Treating conjunctive adverbs the same as coordinating conjunctions and joining two independent clauses with only a comma before them (a comma splice).",
        "Forgetting the comma that usually follows the conjunctive adverb itself, even once the semicolon or full stop before it is correct.",
      ],
      examTip: "Whenever you see however, therefore, moreover, or nevertheless sitting between two complete sentences, check for a semicolon or full stop before it — a comma alone is never strong enough.",
      searchTerms: ["conjunctive adverb", "however therefore", "comma splice", "semicolon", "nevertheless"],
    },
  ],
};
