import type { TopicContent } from "../types";
import {
  DependentPrepositionsDemo,
  EndOfSentencePrepositionDemo,
  CoordinatingSubordinatingDemo,
  CorrelativeConjunctionsDemo,
} from "../notes-diagrams/prepositions-conjunctions-demos";

const CLICK_INSTRUCTION = "Click the word with the error.";

export const prepositionsConjunctionsTopic: TopicContent = {
  slug: "prepositions-conjunctions",
  subject: "English",
  subjectSlug: "english",
  title: "Grammar: Prepositions & Conjunctions",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "Parts of Speech Errors introduced prepositions and conjunctions as word classes — this module goes deeper: the fixed preposition partnerships that just have to be learned, the sentence-ending-preposition myth, the difference between coordinating and subordinating conjunctions, and the correlative conjunction pairs that must always match.",
  subtopics: [
    {
      id: "dependent-prepositions",
      title: "Dependent Prepositions & Fixed Phrases",
      tier: "Standard",
      objective: "Recognise that many adjectives and verbs are always followed by one specific preposition, and spot when the wrong one has been used.",
      whyMatters: "dependent prepositions can't be worked out from logic alone — each pairing has to be learned, and GL papers test exactly these fixed partnerships.",
      conceptTitle: "Some words only ever take one partner",
      conceptBullets: [
        'A <b style="color:#C9A24B">dependent preposition</b> is the one preposition that fixed idiom always uses after a particular adjective or verb.',
        'Examples: <i>interested in</i>, <i>afraid of</i>, <i>different from</i>, <i>good at</i>, <i>depend on</i>, <i>arrive at</i>.',
        "There is no single rule that predicts which preposition a word takes — these pairings have to be learned individually, the way vocabulary is learned.",
        "Swapping in a preposition that seems logical (like “interested on” instead of “interested in”) still reads as wrong to a fluent ear, even without a rule to point to.",
      ],
      conceptNote: "<b>Remember:</b> when in doubt, say the phrase aloud — a wrong dependent preposition almost always sounds instantly odd, even if you can't explain the rule.",
      glossary: [
        { term: "dependent preposition", def: "the one fixed preposition a word always takes (afraid of, good at)" },
        { term: "fixed phrase", def: "a word pairing that doesn't change, however logical an alternative might seem" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: DependentPrepositionsDemo,
      worked: {
        question: "Spot the error: “The results were different than what we expected.”",
        fastMethod: '"different" is a fixed pairing with "from" in careful written English, not "than".',
        steps: [
          "Identify the adjective with a dependent preposition: “different”.",
          "Recall its fixed partner: “different from”, not “different than”.",
          "Swap in the correct preposition.",
          "Corrected: “The results were different from what we expected.”",
        ],
        answer: "The error is <b>than</b> — it should be <b>from</b>.",
      },
      selfCheck: { prompt: "True or false: “good in maths” is the correct fixed phrase.", answer: "<b>False</b> — the dependent preposition for “good” is “at”: good at maths." },
      kind: "click-error",
      questions: [
        {
          id: "dp-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Ali", "was", "afraid", "from", "the", "dark", "corridor", "at", "the", "back", "of", "the", "school."],
          errorIdx: 3,
          correction: '"afraid" pairs with "of", not "from": afraid of the dark corridor.',
          hint: "Check the fixed preposition that always follows this adjective for fear.",
        },
        {
          id: "dp-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "whole", "trip", "depends", "in", "the", "weather", "staying", "dry", "this", "weekend."],
          errorIdx: 4,
          correction: '"depends" pairs with "on", not "in": depends on the weather.',
          hint: "Check the fixed preposition that always follows this verb about relying on something.",
        },
        {
          id: "dp-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["We", "finally", "arrived", "to", "the", "station", "with", "two", "minutes", "to", "spare."],
          errorIdx: 3,
          correction: '"arrived" pairs with "at" (for a place) or "in" (for a city/country), not "to": arrived at the station.',
          hint: "Check the fixed preposition this verb of arrival takes before a place.",
        },
      ],
      mistakes: [
        "Choosing a preposition that seems logical rather than learning the one fixed partner each word actually takes.",
        "Mixing up near-synonyms that take different prepositions, like “different from” vs “similar to”.",
      ],
      examTip: "Keep a running list of adjective/verb + preposition pairs as you meet them — these can't be reasoned out, only memorised.",
      searchTerms: ["dependent preposition", "fixed phrase", "interested in", "afraid of", "different from"],
    },
    {
      id: "sentence-ending-prepositions",
      title: "Ending a Sentence with a Preposition",
      tier: "Standard",
      objective: "Recognise that ending a sentence with a preposition is grammatically acceptable in modern English, and spot when avoiding it makes writing stiff or unnatural.",
      whyMatters: "some students learn the old myth that a sentence must never end in a preposition and awkwardly rewrite perfectly good sentences to avoid it, losing marks for unnatural style.",
      conceptTitle: "A myth worth unlearning",
      conceptBullets: [
        'The idea that a sentence can never end with a <b style="color:#C9A24B">preposition</b> is a long-standing myth, not a real grammar rule.',
        'Example: "What are you looking for?" is completely correct — rewriting it as "For what are you looking?" is stiff and old-fashioned, not more correct.',
        "The rule matters when moving the preposition creates genuine ambiguity or clumsiness, not simply because it lands at the end.",
        "GL-style “complete the sentence” questions sometimes offer an artificially rearranged option as a trap — the natural, sentence-ending version is often the better fit.",
      ],
      conceptNote: "<b>Test it:</b> read both versions aloud — if moving the preposition earlier sounds forced or old-fashioned, the natural sentence-ending version is usually the better choice.",
      glossary: [
        { term: "preposition", def: "a word like to, at, with, about that links a noun to the rest of a sentence" },
        { term: "register", def: "how formal or natural a piece of writing sounds" },
      ],
      diagramLabel: "Interactive · Spot the Stiff Rewrite",
      Diagram: EndOfSentencePrepositionDemo,
      worked: {
        question: "Which is the more natural sentence: “Who did you go with?” or “With whom did you go?”",
        fastMethod: "Both are grammatically correct — but one matches how confident modern writers actually write.",
        steps: [
          "Check whether either version breaks a real grammar rule — neither does.",
          "“With whom did you go?” follows the old myth about never ending on a preposition.",
          "“Who did you go with?” is natural and entirely acceptable in modern written English.",
          "Either can be correct, but exam “best fit” questions usually reward the natural-sounding option unless told to write formally.",
        ],
        answer: "Both are grammatically valid; <b>“Who did you go with?”</b> is the more natural modern choice.",
      },
      selfCheck: { prompt: "True or false: a sentence is always wrong if it ends with a preposition.", answer: "<b>False</b> — this is a myth; ending a sentence with a preposition is accepted in modern English and often sounds more natural than the alternative." },
      kind: "click-error",
      questions: [
        {
          id: "eosp-q1",
          instruction: "Click the word that has been moved purely to avoid ending the sentence on a preposition, making it sound stiff.",
          words: ["This", "is", "the", "friend", "with", "whom", "I", "went", "camping."],
          errorIdx: 4,
          correction: '"with" has been dragged forward purely to dodge ending on a preposition — "this is the friend I went camping with" is the natural, equally correct version.',
          hint: "Look for the preposition sitting earlier than it needs to, right before “whom”.",
        },
        {
          id: "eosp-q2",
          instruction: "Click the word that has been moved purely to avoid ending the sentence on a preposition, making it sound stiff.",
          words: ["That", "is", "the", "shop", "at", "which", "I", "bought", "my", "shoes."],
          errorIdx: 4,
          correction: '"at" has been dragged forward — "that\'s the shop I bought my shoes at" is the natural, equally correct version.',
          hint: "Look for the preposition sitting earlier than it needs to, right before “which”.",
        },
        {
          id: "eosp-q3",
          instruction: "Click the word that has been moved purely to avoid ending the sentence on a preposition, making it sound stiff.",
          words: ["I", "don't", "know", "for", "what", "reason", "she", "left", "so", "suddenly."],
          errorIdx: 3,
          correction: '"for" has been dragged forward unnaturally — "I don\'t know what reason she left so suddenly for" (or better, "why she left so suddenly") reads more naturally.',
          hint: "Look for the preposition placed earlier than it needs to be, before “what reason”.",
        },
      ],
      mistakes: [
        "Believing ending a sentence with a preposition is always a grammar error — it isn't, and forcing an awkward rewrite can actually cost style marks.",
        "Over-applying the fix even when it makes a sentence sound far stiffer than the natural version.",
      ],
      examTip: "If a “best fit” option sounds like it's been rearranged just to avoid ending on a preposition, the natural sentence-ending version is usually the better answer.",
      searchTerms: ["preposition", "end of sentence", "myth", "natural English", "style"],
    },
    {
      id: "coordinating-subordinating-conjunctions",
      title: "Coordinating vs. Subordinating Conjunctions",
      tier: "Standard",
      objective: "Tell apart coordinating conjunctions (joining equal ideas) and subordinating conjunctions (joining a dependent clause to a main clause), and spot when both have been used redundantly together.",
      whyMatters: "pairing a subordinating and a coordinating conjunction together (“because… so…”) is one of the most common conjunction errors, since each already does the linking job alone.",
      conceptTitle: "Two different jobs",
      conceptBullets: [
        'A <b style="color:#C9A24B">coordinating conjunction</b> (and, but, or, so, yet, for, nor) joins two equal, independent ideas.',
        'A <b>subordinating conjunction</b> (because, although, since, while, if) joins a dependent clause to a main clause, and already does the linking job by itself.',
        'Using both together — "because it was raining, so we stayed in" — repeats the same job twice; only one conjunction is needed.',
        "Remove either the subordinating conjunction or the coordinating one, whichever makes the sentence read more naturally.",
      ],
      conceptNote: "<b>Test it:</b> if a sentence starts with because/although/since and also has and/so/but part-way through joining the same two ideas, one of them is redundant.",
      glossary: [
        { term: "coordinating conjunction", def: "joins two equal ideas (and, but, or, so)" },
        { term: "subordinating conjunction", def: "joins a dependent clause to a main clause (because, although, since)" },
        { term: "redundant", def: "unnecessary because the same job is already being done elsewhere" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: CoordinatingSubordinatingDemo,
      worked: {
        question: "Spot the error: “Although the shop was closed, but we still peered through the window.”",
        fastMethod: '"although" already sets up the contrast on its own — "but" repeats the same job and should be removed.',
        steps: [
          "Identify the subordinating conjunction: “although”, which already links the two ideas.",
          "Spot the coordinating conjunction “but”, doing the same linking job again.",
          "Only one is needed — remove the redundant one.",
          "Corrected: “Although the shop was closed, we still peered through the window.”",
        ],
        answer: "The error is <b>but</b> — it should be removed.",
      },
      selfCheck: { prompt: "True or false: “and” and “because” can be correctly used to join the same two clauses in one sentence.", answer: "<b>False, if they repeat the same link</b> — “because” already joins the ideas by itself; adding a coordinating conjunction on top usually creates a redundant repeat of the same job." },
      kind: "click-error",
      questions: [
        {
          id: "cs-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Since", "the", "bus", "was", "late,", "so", "we", "decided", "to", "walk", "instead."],
          errorIdx: 5,
          correction: '"since" already links the two ideas — "so" repeats the job and should be removed.',
          hint: "This sentence starts with a subordinating conjunction — check whether a coordinating one repeats the same link later on.",
        },
        {
          id: "cs-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["While", "she", "practised", "the", "piano,", "but", "her", "brother", "did", "his", "homework."],
          errorIdx: 5,
          correction: '"while" already links the two ideas — "but" repeats the job and should be removed.',
          hint: "Check whether the linking word at the start is being echoed unnecessarily part-way through.",
        },
        {
          id: "cs-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["If", "it", "rains", "tomorrow,", "then", "so", "the", "match", "will", "be", "postponed."],
          errorIdx: 5,
          correction: '"if… then" already links the condition to its result — the extra "so" is redundant and should be removed.',
          hint: "This conditional sentence has one linking word too many part-way through.",
        },
      ],
      mistakes: [
        "Pairing a subordinating conjunction at the start of a sentence with a coordinating conjunction that repeats the link.",
        "Assuming more linking words always make a sentence clearer, when in fact one is doing the job on its own.",
      ],
      examTip: "If a sentence opens with because, although, since, while or if, check whether a second conjunction later on is quietly repeating the same job — it should be removed.",
      searchTerms: ["coordinating conjunction", "subordinating conjunction", "because so", "although but", "redundant"],
    },
    {
      id: "correlative-conjunctions",
      title: "Correlative Conjunctions",
      tier: "Extension",
      objective: "Recognise correlative conjunction pairs (either/or, neither/nor, not only/but also, both/and) and spot when the wrong second half has been used.",
      whyMatters: "correlative conjunctions always travel as a fixed matching pair, and mismatching them — especially “neither… or” instead of “neither… nor” — is a frequent and easy-to-spot exam trap once you know the pairs.",
      conceptTitle: "Fixed pairs that must match",
      conceptBullets: [
        'A <b style="color:#C9A24B">correlative conjunction</b> is a linking word that always comes with a matching partner: <i>either… or</i>, <i>neither… nor</i>, <i>not only… but also</i>, <i>both… and</i>.',
        "Each pair is fixed — “either” always needs “or”, and “neither” always needs “nor”, never “or”.",
        'Example: "neither the cat nor the dog was hungry" — swapping "nor" for "or" breaks the fixed pairing.',
        "These pairs should also join grammatically matching parts of a sentence, keeping the structure balanced on both sides.",
      ],
      conceptNote: "<b>Memory trick:</b> “neither” and “nor” both start with n — they belong together, never “neither… or”.",
      glossary: [
        { term: "correlative conjunction", def: "a linking word that always comes with a fixed matching partner" },
        { term: "either… or", def: "presents a choice between two positive options" },
        { term: "neither… nor", def: "rules out both of two options" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: CorrelativeConjunctionsDemo,
      worked: {
        question: "Spot the error: “Either the twins or her sister are collecting the trophy.”",
        fastMethod: 'the correlative pair "either… or" is used correctly here — this sentence actually tests subject-verb agreement instead: check "are" against the nearer subject "her sister".',
        steps: [
          "Confirm the correlative pair itself: “either… or” is correctly matched.",
          "With “either… or”, the verb usually agrees with the nearer subject, “her sister” (singular).",
          "A singular nearer subject needs a singular verb.",
          "Corrected: “Either the twins or her sister is collecting the trophy.”",
        ],
        answer: "The error is <b>are</b> — it should be <b>is</b>.",
      },
      selfCheck: { prompt: "True or false: “not only… or also” is a correctly matched correlative pair.", answer: "<b>False</b> — the fixed pairing is “not only… but also”, never “not only… or also”." },
      kind: "click-error",
      questions: [
        {
          id: "cc-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "recipe", "needs", "either", "butter", "and", "margarine", "to", "work", "properly."],
          errorIdx: 5,
          correction: '"either" is always paired with "or", never "and": either butter or margarine.',
          hint: "Check the fixed second half that always accompanies “either”.",
        },
        {
          id: "cc-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "is", "not", "only", "the", "captain", "but", "also", "or", "the", "top", "scorer."],
          errorIdx: 8,
          correction: '"not only… but also" is the fixed pairing — the extra "or" doesn\'t belong and should be removed.',
          hint: "Check whether an extra linking word has crept in after the fixed pair “but also”.",
        },
        {
          id: "cc-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Both", "the", "teacher", "or", "the", "headteacher", "signed", "the", "letter."],
          errorIdx: 3,
          correction: '"both" is always paired with "and", never "or": both the teacher and the headteacher.',
          hint: "Check the fixed second half that always accompanies “both”.",
        },
      ],
      mistakes: [
        "Mixing halves of two different correlative pairs, especially “neither… or” instead of “neither… nor”.",
        "Forgetting that with “either… or” and “neither… nor”, the verb agrees with whichever subject is nearer to it.",
      ],
      examTip: "Learn the four fixed pairs by heart — either/or, neither/nor, not only/but also, both/and — and treat any mismatched combination as an automatic error.",
      searchTerms: ["correlative conjunction", "either or", "neither nor", "not only but also", "both and"],
    },
  ],
};
