import type { TopicContent } from "../types";
import {
  SubjectObjectPronounDemo,
  PossessiveContractionDemo,
  PronounAntecedentNumberDemo,
  AmbiguousPronounReferenceDemo,
  ReflexivePronounMisuseDemo,
  WhoWhomDemo,
  RelativePronounChoiceDemo,
  DemonstrativePronounAgreementDemo,
  IndefinitePronounAgreementDemo,
  HypercorrectionPronounDemo,
} from "../notes-diagrams/pronoun-errors-demos";

const CLICK_INSTRUCTION = "Click the word with the error.";

export const pronounErrorsTopic: TopicContent = {
  slug: "pronoun-errors",
  subject: "English",
  subjectSlug: "english",
  title: "Grammar: Pronoun Errors",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "Pronouns stand in for nouns so a sentence doesn't repeat itself — but swap the wrong one in and the sentence quietly breaks. This module works through subject and object pronouns, possessives and contractions, agreement, ambiguous reference, reflexives, who/whom, relative and demonstrative pronouns, indefinite pronouns, and the “sounds formal so it must be right” trap of hypercorrection.",
  subtopics: [
    {
      id: "subject-object-pronouns",
      title: "Subject vs. Object Pronouns",
      tier: "Foundation",
      objective: "Choose the correct subject pronoun (I, he, she, we, they) or object pronoun (me, him, her, us, them) depending on the pronoun's job in the sentence.",
      whyMatters: "using an object pronoun as a subject — “me and my brother went” — is one of the most common everyday speech habits that slips into writing, and GL papers test it constantly.",
      conceptTitle: "Doing the action vs. receiving it",
      conceptBullets: [
        'A <b style="color:#C9A24B">subject pronoun</b> (I, he, she, we, they) does the action: "<i>She</i> ran to the shop."',
        'An <b>object pronoun</b> (me, him, her, us, them) receives the action: "They saw <i>her</i>."',
        "When a pronoun is paired with a name (“Sam and I”, “me and Sam”), test the pronoun alone — remove the other person's name and read it back.",
        '"I" is never correct straight after a preposition like "to", "with" or "between" — those always take an object pronoun.',
      ],
      conceptNote: "<b>Test it:</b> cross out the other person's name and read the pronoun on its own — “me went to the shop” sounds instantly wrong.",
      glossary: [
        { term: "subject pronoun", def: "does the action (I, he, she, we, they)" },
        { term: "object pronoun", def: "receives the action (me, him, her, us, them)" },
        { term: "preposition", def: "a word like to, with, between that is always followed by an object pronoun" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: SubjectObjectPronounDemo,
      worked: {
        question: "Spot the error: “Me and my sister baked a cake for the school fair.”",
        fastMethod: 'Remove "and my sister" to test it: "me baked a cake" sounds wrong — it should be "I", a subject pronoun.',
        steps: [
          "The pronoun is doing the action “baked”, so it needs a subject pronoun.",
          "Test by removing “and my sister”: “me baked a cake” is clearly wrong.",
          "The subject pronoun is “I”, not “me”.",
          "Corrected: “My sister and I baked a cake for the school fair.”",
        ],
        answer: "The error is <b>Me</b> — it should be <b>I</b>.",
      },
      selfCheck: { prompt: "True or false: “The prize was given to she and her friend” is correct.", answer: "<b>False</b> — “to” is a preposition, so it needs the object pronoun “her”, not the subject pronoun “she”: given to her and her friend." },
      kind: "click-error",
      questions: [
        {
          id: "sop-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Him", "and", "his", "friends", "walked", "to", "school", "together", "every", "morning."],
          errorIdx: 0,
          correction: '"him" cannot be the subject of "walked" — the subject pronoun "he" is needed: he and his friends walked.',
          hint: "Find the pronoun doing the action of walking, right at the start of the sentence.",
        },
        {
          id: "sop-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "teacher", "asked", "Priya", "and", "I", "to", "collect", "the", "books."],
          errorIdx: 5,
          correction: '"Priya and I" is the object of "asked", so it needs an object pronoun — "I" should be "me": asked Priya and me.',
          hint: "Remove “Priya and” and read the pronoun on its own — does it still sound right?",
        },
        {
          id: "sop-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Us", "girls", "practised", "the", "song", "every", "day", "before", "the", "concert."],
          errorIdx: 0,
          correction: '"us" cannot be the subject of "practised" — the subject pronoun "we" is needed: we girls practised.',
          hint: "Check whether this pronoun is doing the action or receiving it.",
        },
      ],
      mistakes: [
        "Using an object pronoun (“me”, “us”, “him”) as the subject of a sentence, especially when paired with another name.",
        "Assuming “I” always sounds more correct than “me” — after a preposition like “to” or “between”, “me” is the right choice.",
      ],
      examTip: "Remove the other person from the sentence and read the pronoun alone — the wrong choice will sound obviously off once the distraction is gone.",
      searchTerms: ["pronoun", "subject pronoun", "object pronoun", "me and i", "preposition"],
    },
    {
      id: "possessive-contractions",
      title: "Possessive Pronouns vs. Contractions",
      tier: "Foundation",
      objective: "Tell apart possessive pronouns (its, their) and their contraction look-alikes (it's, they're, there), and spot when the wrong one has been used.",
      whyMatters: "its/it's and their/they're/there are among the most frequently tested confusions on 11+ papers, precisely because they sound identical when spoken.",
      conceptTitle: "Ownership word, or two words squashed together?",
      conceptBullets: [
        'A <b style="color:#C9A24B">possessive pronoun</b> shows ownership and never takes an apostrophe: <i>its</i>, <i>their</i>, <i>your</i>, <i>whose</i>.',
        'A <b>contraction</b> is two words squashed together with an apostrophe standing in for missing letters: <i>it\'s</i> = it is, <i>they\'re</i> = they are.',
        '<i>There</i> is neither — it points to a place ("over <i>there</i>") or starts a sentence ("<i>there</i> is a cat").',
        "Test any apostrophe pronoun by expanding it: if “it is” or “they are” doesn't make sense in the sentence, the apostrophe is wrong.",
      ],
      conceptNote: "<b>Test it:</b> read the sentence back with “it is” or “they are” in place of the apostrophe word — if it sounds silly, you need the possessive instead.",
      glossary: [
        { term: "possessive pronoun", def: "shows ownership, no apostrophe (its, their)" },
        { term: "contraction", def: "two words shortened with an apostrophe (it's, they're)" },
        { term: "there", def: "points to a place, or starts a sentence about existence" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: PossessiveContractionDemo,
      worked: {
        question: "Spot the error: “The birds built there nest in the old oak tree.”",
        fastMethod: 'Expand it: "built they are nest" makes no sense, and this isn\'t pointing to a place — the possessive "their" is needed.',
        steps: [
          "Check the apostrophe-free word “there” against its two jobs: place, or starting a sentence about existence.",
          "Neither job fits here — the birds own the nest, so a possessive pronoun is needed.",
          "The possessive pronoun for “belonging to them” is “their”.",
          "Corrected: “The birds built their nest in the old oak tree.”",
        ],
        answer: "The error is <b>there</b> — it should be <b>their</b>.",
      },
      selfCheck: { prompt: "True or false: “The dog buried it's bone in the garden” is correct.", answer: "<b>False</b> — expanding “it's” gives “buried it is bone”, which makes no sense; the possessive “its” (no apostrophe) is needed." },
      kind: "click-error",
      questions: [
        {
          id: "pc-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["They're", "bags", "were", "left", "by", "the", "front", "door", "all", "morning."],
          errorIdx: 0,
          correction: '"they\'re" expands to "they are", which makes no sense before "bags" — the possessive "their" is needed: their bags.',
          hint: "Expand the first word into two words and check whether it still makes sense.",
        },
        {
          id: "pc-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Its", "raining", "again,", "so", "the", "match", "has", "been", "cancelled."],
          errorIdx: 0,
          correction: '"its" shows ownership, but nothing is being owned here — the sentence means "it is raining", so it needs the contraction "It\'s".',
          hint: "Expand the first word into two words and see if the sentence still makes sense.",
        },
        {
          id: "pc-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "students", "left", "there", "coats", "in", "the", "cloakroom", "before", "assembly."],
          errorIdx: 3,
          correction: '"there" points to a place, but this word is showing ownership of the coats — the possessive "their" is needed: their coats.',
          hint: "Check whether this word is pointing to a place or showing who owns something.",
        },
      ],
      mistakes: [
        "Adding an apostrophe to a possessive pronoun because it “looks” like it should have one — possessive pronouns never take an apostrophe.",
        "Confusing “there” (a place) with “their” (ownership) because they sound identical when spoken.",
      ],
      examTip: "Whenever you see “it's”, “they're” or a possessive pronoun, mentally expand it into two words — if the expansion doesn't make sense, you've found the error.",
      searchTerms: ["its", "it's", "their", "they're", "there", "possessive pronoun", "contraction"],
    },
    {
      id: "pronoun-antecedent-agreement",
      title: "Pronoun-Antecedent Agreement",
      tier: "Standard",
      objective: "Match a pronoun to the number (singular or plural) of the noun it replaces, even when that noun is a collective noun that looks singular but acts as a group.",
      whyMatters: "collective nouns like “team”, “class” and “family” tempt writers into pairing them with a singular pronoun even when the sentence really means the individuals within the group.",
      conceptTitle: "The pronoun must match its noun",
      conceptBullets: [
        'The noun a <b style="color:#C9A24B">pronoun</b> replaces is called its <b>antecedent</b> — the pronoun must match that noun in number.',
        "A singular antecedent needs a singular pronoun (he, she, it); a plural antecedent needs a plural pronoun (they, their, them).",
        'Collective nouns (team, class, family, crowd) are grammatically singular when acting as one unit, so they usually take a singular pronoun — but this can trip writers into the wrong choice under pressure.',
        'Example: "the <b>team</b> celebrated <b>its</b> win" is correct when the team acts as one unit; a plural pronoun would wrongly suggest separate individuals.',
      ],
      conceptNote: "<b>Test it:</b> ask whether the noun is acting as one single unit or as many separate individuals — that decides singular or plural.",
      glossary: [
        { term: "antecedent", def: "the noun a pronoun replaces" },
        { term: "collective noun", def: "names a group, usually singular (team, class, family)" },
        { term: "agreement", def: "matching a pronoun's number to its antecedent" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: PronounAntecedentNumberDemo,
      worked: {
        question: "Spot the error: “The class finished their test and handed it in on time.”",
        fastMethod: 'The class is acting as one unit sitting one test — the singular pronoun "its" fits better than the plural "their".',
        steps: [
          "Identify the antecedent: “the class”, a collective noun.",
          "Decide whether the class is acting as one unit or as separate individuals — here, one test, one unit.",
          "A singular antecedent acting as one unit needs a singular pronoun.",
          "Corrected: “The class finished its test and handed it in on time.”",
        ],
        answer: "The error is <b>their</b> — it should be <b>its</b>.",
      },
      selfCheck: { prompt: "True or false: “Everyone brought their own lunch” always needs a singular pronoun instead of “their”.", answer: "<b>False, in modern usage</b> — “their” is widely accepted as a singular pronoun after “everyone” when the individual's gender is unknown; the stricter Foundation rule tested here is collective nouns like “team” acting as one unit." },
      kind: "click-error",
      questions: [
        {
          id: "paa-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "team", "lost", "his", "match", "in", "the", "final", "minute", "of", "play."],
          errorIdx: 3,
          correction: '"team" is a group of players, not one person, so the pronoun should be plural: the team lost their match.',
          hint: "Check whether the pronoun matches one person or a whole group of players.",
        },
        {
          id: "paa-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Each", "of", "the", "boys", "packed", "their", "own", "bag", "for", "camp."],
          errorIdx: 5,
          correction: '"each" is a singular pronoun, even though it\'s followed by "of the boys" — the matching pronoun should be singular: each packed his own bag.',
          hint: "The word “each” at the start of the sentence is always singular, however many boys follow it.",
        },
        {
          id: "paa-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "audience", "rose", "to", "its", "feet", "and", "began", "clapping", "loudly."],
          errorIdx: 4,
          correction: '"audience" is acting as many separate people clapping, not one single body, so the pronoun should be plural: the audience rose to their feet.',
          hint: "Decide whether the audience is acting as one single thing or as many individual people here.",
        },
      ],
      mistakes: [
        "Automatically pairing collective nouns with plural pronouns, without checking whether the group is acting as one unit or as individuals.",
        "Treating “each”, “every” and “neither” as plural because they're followed by a plural-sounding phrase — they are always singular.",
      ],
      examTip: "Ask “is this noun acting as one thing, or as many separate things?” — that single question decides the correct pronoun almost every time.",
      searchTerms: ["antecedent", "agreement", "collective noun", "singular", "plural", "each"],
    },
    {
      id: "ambiguous-pronoun-reference",
      title: "Ambiguous Pronoun Reference",
      tier: "Standard",
      objective: "Spot a pronoun that could sensibly refer to more than one noun in the sentence, making the meaning unclear.",
      whyMatters: "an ambiguous pronoun doesn't break any grammar rule on its own — the sentence still reads smoothly — but it leaves the reader guessing who or what is actually meant.",
      conceptTitle: "Which noun does it point back to?",
      conceptBullets: [
        'A <b style="color:#C9A24B">pronoun</b> should point back to exactly one clear noun, called its antecedent.',
        "When a sentence names two people or things of the same type before using a pronoun, the reader can no longer be sure which one it means.",
        'Example: "When Jack met his uncle, <i>he</i> was already late" — does "he" mean Jack, or the uncle? Both are grammatically possible.',
        "The fix is usually to replace the unclear pronoun with the specific name it was meant to stand in for.",
      ],
      conceptNote: "<b>Test it:</b> try substituting each possible noun back in for the pronoun — if more than one makes sense, the reference is ambiguous.",
      glossary: [
        { term: "ambiguous reference", def: "a pronoun that could point to more than one noun" },
        { term: "antecedent", def: "the noun a pronoun is meant to replace" },
        { term: "clarity", def: "writing that leaves only one possible meaning" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: AmbiguousPronounReferenceDemo,
      worked: {
        question: "Spot the error: “Leo told his coach that he had won the trophy.”",
        fastMethod: 'Substitute both people back in: "Leo had won" and "the coach had won" both make sense — "he" is ambiguous.',
        steps: [
          "Identify the two people named before the pronoun: “Leo” and “his coach”.",
          "Try substituting each one back in for “he” — both readings are grammatically possible.",
          "Because the reader can't be sure which one is meant, the pronoun is ambiguous.",
          "Corrected: “Leo told his coach that Leo had won the trophy.”",
        ],
        answer: "The pronoun <b>he</b> is ambiguous — it should be replaced with a specific name.",
      },
      selfCheck: { prompt: "Why is “Maya passed the recipe to her sister because she loved baking” unclear?", answer: "Because <b>she</b> could mean either Maya or her sister — both readings make sense, so the sentence needs a specific name instead." },
      kind: "click-error",
      questions: [
        {
          id: "apr-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["When", "the", "vase", "hit", "the", "table,", "it", "smashed", "into", "pieces."],
          errorIdx: 6,
          correction: '"it" could mean either "the vase" or "the table" — the sentence needs a specific noun in its place: the vase smashed into pieces.',
          hint: "Two things are named before this pronoun — either could plausibly be what smashed.",
        },
        {
          id: "apr-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Dad", "told", "my", "brother", "that", "he", "had", "left", "the", "oven", "on."],
          errorIdx: 5,
          correction: '"he" could mean either "Dad" or "my brother" — the sentence needs a specific name in its place: that Dad had left the oven on.',
          hint: "Two people are named before this pronoun — check which one it's actually meant to point to.",
        },
        {
          id: "apr-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Grandma", "put", "the", "photo", "next", "to", "the", "clock", "because", "it", "was", "old."],
          errorIdx: 9,
          correction: '"it" could mean either "the photo" or "the clock" — the sentence needs a specific noun in its place: because the clock was old.',
          hint: "Two objects are named before this pronoun — either could plausibly be described as old.",
        },
      ],
      mistakes: [
        "Assuming a sentence is fine because it's grammatically correct — ambiguous reference is a clarity error, not a grammar error.",
        "Missing the ambiguity because the intended meaning feels obvious to the writer, even though a reader has no way to be sure.",
      ],
      examTip: "Whenever a sentence names two people or things of the same type, check every pronoun that follows — could it honestly point to either one?",
      searchTerms: ["ambiguous", "pronoun reference", "antecedent", "clarity", "unclear pronoun"],
    },
    {
      id: "reflexive-pronoun-misuse",
      title: "Reflexive Pronoun Misuse",
      tier: "Standard",
      objective: "Use reflexive pronouns (myself, yourself, himself) only when they refer back to the subject of the same clause, and recognise when a plain pronoun is needed instead.",
      whyMatters: "using “myself” to sound more polite or formal instead of the plain pronoun “me” is an extremely common error in both speech and writing.",
      conceptTitle: "Reflexive pronouns need a matching subject",
      conceptBullets: [
        'A <b style="color:#C9A24B">reflexive pronoun</b> (myself, yourself, himself, herself, ourselves, themselves) refers back to the subject of the same clause.',
        'Correct: "I hurt <i>myself</i>" — the subject "I" and the reflexive pronoun match.',
        'Incorrect: "Please contact <i>myself</i>" — there is no matching "I" earlier in the sentence, so the plain object pronoun "me" is needed.',
        "Reflexive pronouns are never a more formal or polite substitute for “me” or “I” — that use is always wrong, however common it sounds.",
      ],
      conceptNote: "<b>Test it:</b> find the subject of the clause — if it doesn't match the reflexive pronoun exactly, swap the reflexive for a plain pronoun.",
      glossary: [
        { term: "reflexive pronoun", def: "refers back to the subject of the clause (myself, himself)" },
        { term: "clause", def: "a group of words with a subject and a verb" },
        { term: "object pronoun", def: "the plain form used when no reflexive is needed (me, him)" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: ReflexivePronounMisuseDemo,
      worked: {
        question: "Spot the error: “If you have any questions, speak to myself after the lesson.”",
        fastMethod: 'There is no "I" earlier in the sentence for "myself" to refer back to — the plain object pronoun "me" is needed.',
        steps: [
          "Look for the subject of the clause containing “myself” — it's “you”, not “I”.",
          "A reflexive pronoun needs a matching subject in the same clause; “myself” has none here.",
          "Without a matching subject, the plain object pronoun is correct instead.",
          "Corrected: “…speak to me after the lesson.”",
        ],
        answer: "The error is <b>myself</b> — it should be <b>me</b>.",
      },
      selfCheck: { prompt: "True or false: “She baked the cake herself” is correct.", answer: "<b>True</b> — the subject “she” matches the reflexive pronoun “herself”, so it correctly refers back to the same person." },
      kind: "click-error",
      questions: [
        {
          id: "rpm-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "manager", "asked", "John", "and", "myself", "to", "close", "the", "shop."],
          errorIdx: 5,
          correction: '"myself" has no matching "I" as the subject of this clause — the plain object pronoun "me" is needed: John and me.',
          hint: "Check whether the subject of this sentence is “I” — if not, the reflexive pronoun is wrong.",
        },
        {
          id: "rpm-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Please", "return", "the", "form", "to", "myself", "by", "Friday."],
          errorIdx: 5,
          correction: '"myself" has no matching "I" earlier in the sentence — the plain object pronoun "me" is needed: return the form to me.',
          hint: "Look for a subject “I” earlier in the sentence for this reflexive pronoun to match.",
        },
        {
          id: "rpm-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["My", "cousin", "and", "myself", "built", "a", "treehouse", "last", "summer."],
          errorIdx: 3,
          correction: '"myself" cannot be part of the subject of "built" — the subject pronoun "I" is needed: my cousin and I built.',
          hint: "Check whether this word is meant to be doing the action, not just reflecting back on it.",
        },
      ],
      mistakes: [
        "Using “myself” instead of “me” to sound more polite or formal — reflexive pronouns are never a substitute for a plain pronoun.",
        "Using a reflexive pronoun as part of the subject of a sentence, where a subject pronoun like “I” is needed instead.",
      ],
      examTip: "Check for a matching “I” (or the relevant subject) earlier in the same clause — no match means the reflexive pronoun is wrong.",
      searchTerms: ["reflexive pronoun", "myself", "yourself", "me", "hypercorrection"],
    },
    {
      id: "who-vs-whom",
      title: "Who vs. Whom",
      tier: "Extension",
      objective: "Choose between “who” (subject) and “whom” (object of a verb or preposition) based on the pronoun's job in its clause.",
      whyMatters: "who/whom is one of the trickiest pronoun distinctions at 11+ level because “whom” has almost disappeared from casual speech, making it easy to misuse or avoid entirely.",
      conceptTitle: "Subject or object?",
      conceptBullets: [
        '<b style="color:#C9A24B">Who</b> is a subject pronoun — it does the action: "<i>Who</i> ate the last biscuit?"',
        '<b>Whom</b> is an object pronoun — it receives the action or follows a preposition: "To <i>whom</i> should I address the letter?"',
        'Test it by answering the question with "he" or "him": if "he" fits, use "who"; if "him" fits, use "whom" (both end in "m").',
        "Whom almost always follows a preposition (to, with, for, by) or comes right before a verb whose subject is someone else.",
      ],
      conceptNote: "<b>Memory trick:</b> “whom” and “him” both end in -m — if you'd answer the question with “him”, the question needs “whom”.",
      glossary: [
        { term: "who", def: "subject pronoun — does the action" },
        { term: "whom", def: "object pronoun — receives the action or follows a preposition" },
        { term: "relative clause", def: "a clause introduced by who/whom that describes a noun" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: WhoWhomDemo,
      worked: {
        question: "Spot the error: “The scientist who the prize was awarded to gave a speech.”",
        fastMethod: 'Test it: "awarded to him" fits, not "awarded to he" — so the object pronoun "whom" is needed.',
        steps: [
          "Find the pronoun's clause: “who the prize was awarded to”.",
          "Ask who received the action — the prize was awarded to the scientist, an object relationship.",
          "Test with he/him: “awarded to him” fits, confirming the object pronoun is needed.",
          "Corrected: “The scientist whom the prize was awarded to gave a speech.”",
        ],
        answer: "The error is <b>who</b> — it should be <b>whom</b>.",
      },
      selfCheck: { prompt: "Which is correct: “Who / Whom is coming to the party?”", answer: "<b>Who</b> — it's the subject doing the action of coming (“he is coming” fits, not “him is coming”)." },
      kind: "click-error",
      questions: [
        {
          id: "ww-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "man", "whom", "lives", "next", "door", "waved", "to", "us", "this", "morning."],
          errorIdx: 2,
          correction: '"whom" is doing the action of "lives", so it needs the subject pronoun "who": the man who lives next door.',
          hint: "Test with he/him — does “he lives” or “him lives” sound right?",
        },
        {
          id: "ww-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["To", "who", "should", "I", "give", "the", "completed", "form?"],
          errorIdx: 1,
          correction: '"who" follows the preposition "to" and receives the action, so it needs the object pronoun "whom": to whom should I give.',
          hint: "This pronoun comes right after a preposition — test it with he/him.",
        },
        {
          id: "ww-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "author", "whom", "wrote", "this", "book", "visited", "our", "school", "yesterday."],
          errorIdx: 2,
          correction: '"whom" is doing the action of "wrote", so it needs the subject pronoun "who": the author who wrote this book.',
          hint: "Test with he/him — does “he wrote” or “him wrote” sound right?",
        },
      ],
      mistakes: [
        "Using “whom” automatically to sound formal, even when the pronoun is actually doing the action and needs “who”.",
        "Avoiding “whom” altogether and defaulting to “who” even after a preposition like “to” or “for”.",
      ],
      examTip: "Answer the clause with “he” or “him” — whichever one fits tells you instantly whether you need “who” or “whom”.",
      searchTerms: ["who", "whom", "subject pronoun", "object pronoun", "preposition"],
    },
    {
      id: "relative-pronouns",
      title: "Relative Pronouns: Who, Which, That",
      tier: "Extension",
      objective: "Choose the correct relative pronoun — who for people, which for things, that for either — and spot when the wrong one has been used.",
      whyMatters: "using “which” for a person, or overusing “that” where “who” is clearly better, is a frequent trap in GL-style “complete the sentence” questions.",
      conceptTitle: "People, things, or either",
      conceptBullets: [
        'A <b style="color:#C9A24B">relative pronoun</b> introduces a clause that describes a noun just before it.',
        '<b>Who</b> is used only for people: "the girl <i>who</i> won the race."',
        '<b>Which</b> is used only for things, animals or ideas, never for people: "the trophy <i>which</i> she won."',
        '<b>That</b> can refer to either people or things, but exams usually expect "who" for a clearly named person rather than "that".',
      ],
      conceptNote: "<b>Rule of thumb:</b> if the noun being described is a person, reach for “who” first — “which” is reserved strictly for things.",
      glossary: [
        { term: "relative pronoun", def: "introduces a clause describing a noun (who, which, that)" },
        { term: "relative clause", def: "the descriptive clause introduced by a relative pronoun" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: RelativePronounChoiceDemo,
      worked: {
        question: "Spot the error: “The dentist which treated me was very gentle.”",
        fastMethod: 'A dentist is a person, and "which" is never used for people — it should be "who".',
        steps: [
          "Identify the noun being described: “the dentist”, a person.",
          "“Which” is reserved for things, animals or ideas, never people.",
          "The correct relative pronoun for a person is “who”.",
          "Corrected: “The dentist who treated me was very gentle.”",
        ],
        answer: "The error is <b>which</b> — it should be <b>who</b>.",
      },
      selfCheck: { prompt: "True or false: “which” can correctly describe a pet dog.", answer: "<b>True</b> — animals take “which” (or “that”), not “who”, since “who” is reserved for people." },
      kind: "click-error",
      questions: [
        {
          id: "rp-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "librarian", "which", "helped", "me", "find", "the", "book", "was", "very", "kind."],
          errorIdx: 2,
          correction: '"which" cannot describe a person — the librarian needs "who": the librarian who helped me.',
          hint: "Check whether the noun being described is a person or a thing.",
        },
        {
          id: "rp-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "bicycle", "who", "I", "borrowed", "had", "a", "flat", "tyre."],
          errorIdx: 2,
          correction: '"who" is reserved for people — a bicycle is a thing, so it needs "which" or "that": the bicycle which I borrowed.',
          hint: "Check whether this relative pronoun is describing a person or an object.",
        },
        {
          id: "rp-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "coach", "which", "trained", "our", "team", "used", "to", "play", "professionally."],
          errorIdx: 2,
          correction: '"which" cannot describe a person — the coach needs "who": the coach who trained our team.',
          hint: "Check whether the noun being described is capable of coaching, i.e. a person.",
        },
      ],
      mistakes: [
        "Using “which” to describe a person instead of “who” — this is never correct, however casual the sentence.",
        "Overusing “that” for a clearly named person when “who” reads more naturally and is usually expected on exams.",
      ],
      examTip: "Ask “is the noun just before this pronoun a person?” — if yes, “which” is automatically wrong.",
      searchTerms: ["relative pronoun", "who", "which", "that", "relative clause"],
    },
    {
      id: "demonstrative-pronouns",
      title: "Demonstrative Pronouns: This, That, These, Those",
      tier: "Extension",
      objective: "Match demonstrative pronouns to the number of the noun they point to — this/that for singular, these/those for plural.",
      whyMatters: "demonstrative pronoun agreement errors (“this apples”, “those book”) are an easy mark to lose because the mismatch is often missed when reading quickly.",
      conceptTitle: "Near or far, singular or plural",
      conceptBullets: [
        'A <b style="color:#C9A24B">demonstrative pronoun</b> points to a specific noun: <i>this</i>, <i>that</i>, <i>these</i>, <i>those</i>.',
        '<b>This</b> and <b>that</b> point to one thing — this is singular near, that is singular far.',
        '<b>These</b> and <b>those</b> point to more than one thing — these is plural near, those is plural far.',
        'Example: "<i>this</i> book" (one, nearby) vs. "<i>those</i> books" (several, further away) — the demonstrative must match the noun\'s number.',
      ],
      conceptNote: "<b>Test it:</b> check the noun right after the demonstrative pronoun for a plural -s ending — that decides which form is needed.",
      glossary: [
        { term: "demonstrative pronoun", def: "points to a specific noun (this, that, these, those)" },
        { term: "singular demonstrative", def: "this, that — points to one thing" },
        { term: "plural demonstrative", def: "these, those — points to more than one thing" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: DemonstrativePronounAgreementDemo,
      worked: {
        question: "Spot the error: “Those jacket belongs to my brother.”",
        fastMethod: '"jacket" is singular, so the demonstrative pronoun should be singular too — "those" should be "that".',
        steps: [
          "Check the noun right after the demonstrative pronoun: “jacket”, singular.",
          "“Those” is a plural demonstrative pronoun and doesn't match a singular noun.",
          "The singular equivalent of “those” is “that”.",
          "Corrected: “That jacket belongs to my brother.”",
        ],
        answer: "The error is <b>Those</b> — it should be <b>That</b>.",
      },
      selfCheck: { prompt: "True or false: “these” can correctly be used with a singular noun.", answer: "<b>False</b> — “these” is always plural; it must be followed by a plural noun, e.g. “these shoes”, not “these shoe”." },
      kind: "click-error",
      questions: [
        {
          id: "dp-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["These", "cake", "looks", "delicious", "on", "the", "kitchen", "table."],
          errorIdx: 0,
          correction: '"cake" (here meaning one cake) is singular, so the demonstrative pronoun should be singular: this cake.',
          hint: "Check whether the noun right after this pronoun is singular or plural.",
        },
        {
          id: "dp-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Can", "you", "carry", "that", "boxes", "to", "the", "car,", "please?"],
          errorIdx: 3,
          correction: '"boxes" is plural, so the demonstrative pronoun should be plural too: carry those boxes.',
          hint: "Check the ending of the noun that follows this demonstrative pronoun.",
        },
        {
          id: "dp-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["This", "trainers", "are", "far", "too", "muddy", "to", "wear", "inside."],
          errorIdx: 0,
          correction: '"trainers" is plural, so the demonstrative pronoun should be plural: these trainers.',
          hint: "Check whether the noun right after this pronoun ends in a plural -s.",
        },
      ],
      mistakes: [
        "Using a singular demonstrative pronoun (this, that) before a plural noun, or a plural one (these, those) before a singular noun.",
        "Focusing only on near/far meaning and forgetting to check the number of the noun that follows.",
      ],
      examTip: "Always check the very next noun's ending before choosing a demonstrative pronoun — a plural -s decides the form instantly.",
      searchTerms: ["demonstrative pronoun", "this", "that", "these", "those", "agreement"],
    },
    {
      id: "indefinite-pronoun-errors",
      title: "Indefinite Pronoun Errors",
      tier: "Extension",
      objective: "Recognise that indefinite pronouns like everyone, somebody and nobody are singular, and match them to singular verbs and pronouns.",
      whyMatters: "indefinite pronouns describe groups of people but are grammatically singular — this mismatch between meaning and grammar is a classic 11+ trap.",
      conceptTitle: "Sounds like many, counts as one",
      conceptBullets: [
        'An <b style="color:#C9A24B">indefinite pronoun</b> refers to an unspecified person or thing: <i>everyone</i>, <i>somebody</i>, <i>nobody</i>, <i>anyone</i>, <i>each</i>.',
        "Despite referring to a group or an unknown person, most indefinite pronouns ending in -one, -body or -thing are grammatically singular.",
        'Example: "<i>Everybody</i> <b>needs</b> a ticket" — not "need a ticket" — because "everybody" counts as one grammatical unit.',
        "This affects both the verb that follows and any pronoun used later in the sentence to refer back to it.",
      ],
      conceptNote: "<b>Test it:</b> mentally swap the indefinite pronoun for “one person” — if the verb still needs to agree with “one”, it must be singular.",
      glossary: [
        { term: "indefinite pronoun", def: "refers to an unspecified person or thing (everyone, somebody)" },
        { term: "singular verb", def: "the verb form matching a singular subject (has, needs, is)" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: IndefinitePronounAgreementDemo,
      worked: {
        question: "Spot the error: “Somebody have left their umbrella in the hall.”",
        fastMethod: '"somebody" is singular, even though it\'s vague about who — the verb should be "has", not "have".',
        steps: [
          "Identify the subject: “somebody”, an indefinite pronoun.",
          "Indefinite pronouns ending in -body are grammatically singular.",
          "A singular subject needs a singular verb: “has”, not “have”.",
          "Corrected: “Somebody has left their umbrella in the hall.”",
        ],
        answer: "The error is <b>have</b> — it should be <b>has</b>.",
      },
      selfCheck: { prompt: "True or false: “Nobody know the answer” is correct.", answer: "<b>False</b> — “nobody” is singular, so the verb should be “knows”: nobody knows the answer." },
      kind: "click-error",
      questions: [
        {
          id: "ipe-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Everyone", "in", "the", "class", "were", "given", "a", "certificate", "for", "trying."],
          errorIdx: 4,
          correction: '"everyone" is singular, even though it means many people — the verb should be "was": everyone was given a certificate.',
          hint: "Check whether this indefinite pronoun counts as one grammatical unit or many.",
        },
        {
          id: "ipe-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Nobody", "want", "to", "go", "outside", "in", "this", "cold", "weather."],
          errorIdx: 1,
          correction: '"nobody" is singular, so the verb should be "wants": nobody wants to go outside.',
          hint: "This indefinite pronoun always takes a singular verb, even though it refers to a group of people.",
        },
        {
          id: "ipe-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Someone", "have", "left", "the", "classroom", "light", "on", "again."],
          errorIdx: 1,
          correction: '"someone" is singular, so the verb should be "has": someone has left the light on.',
          hint: "Check whether this indefinite pronoun is grammatically singular or plural.",
        },
      ],
      mistakes: [
        "Pairing an indefinite pronoun with a plural verb because its meaning feels like “many people”.",
        "Forgetting that everyone, everybody, somebody, nobody, anybody and each are all grammatically singular.",
      ],
      examTip: "Mentally replace the indefinite pronoun with “one person” — whatever verb form fits “one person” is the one you need.",
      searchTerms: ["indefinite pronoun", "everyone", "somebody", "nobody", "singular", "agreement"],
    },
    {
      id: "hypercorrection-errors",
      title: "Hypercorrection Errors",
      tier: "Extension",
      objective: "Recognise when a subject pronoun (I, he, she) has been wrongly used in an object position because it sounds more formal or polite.",
      whyMatters: "hypercorrection — swapping a correct object pronoun for a subject pronoun to sound “proper” — is an advanced but very common trap, especially after “between” and “and”.",
      conceptTitle: "Sounding formal isn't the same as being correct",
      conceptBullets: [
        '<b style="color:#C9A24B">Hypercorrection</b> happens when someone avoids a pronoun they think sounds too casual, and “corrects” it into the wrong form.',
        'Because "me" is often (wrongly) corrected in speech, writers start avoiding it even in places where it\'s actually correct.',
        'Example: "between you and <i>I</i>" is a hypercorrection — "between" is a preposition, and prepositions always take an object pronoun: between you and <i>me</i>.',
        "Test it exactly as with any subject/object pronoun question: remove the other person and read the pronoun alone.",
      ],
      conceptNote: "<b>Remember:</b> “I” is not automatically more correct or more formal than “me” — the pronoun's job in the sentence, not how it sounds, decides which is right.",
      glossary: [
        { term: "hypercorrection", def: "wrongly “fixing” a correct pronoun because it sounds too informal" },
        { term: "preposition", def: "a word like between, to, with, always followed by an object pronoun" },
      ],
      diagramLabel: "Interactive · Click the Error",
      Diagram: HypercorrectionPronounDemo,
      worked: {
        question: "Spot the error: “Grandma made a special cake for my brother and I.”",
        fastMethod: 'Remove "my brother and" to test it: "made a cake for I" sounds wrong — the object pronoun "me" is needed.',
        steps: [
          "“For” is a preposition, so the pronoun following it needs to be an object pronoun.",
          "Test by removing “my brother and”: “made a cake for I” is clearly wrong.",
          "The object pronoun is “me”, not “I” — “I” has been used here purely to sound more formal.",
          "Corrected: “Grandma made a special cake for my brother and me.”",
        ],
        answer: "The error is <b>I</b> — it should be <b>me</b>.",
      },
      selfCheck: { prompt: "True or false: “Give the tickets to Ali and I” is correct because “I” sounds more polite than “me”.", answer: "<b>False</b> — “to” is a preposition and always takes an object pronoun; “Ali and me” is correct, however formal “I” might sound." },
      kind: "click-error",
      questions: [
        {
          id: "hc-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "invitation", "was", "sent", "to", "my", "parents", "and", "I", "last", "week."],
          errorIdx: 8,
          correction: '"to" is a preposition and needs an object pronoun — "I" should be "me": sent to my parents and me.',
          hint: "Remove “my parents and” and read the pronoun alone — does it still sound right after “to”?",
        },
        {
          id: "hc-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Just", "between", "you", "and", "I,", "the", "surprise", "party", "is", "tomorrow."],
          errorIdx: 4,
          correction: '"between" is a preposition and needs an object pronoun after it — "I" should be "me": between you and me.',
          hint: "Check the pronoun right after “and”, following the preposition “between”.",
        },
        {
          id: "hc-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "coach", "picked", "Amir", "and", "I", "for", "the", "relay", "team."],
          errorIdx: 5,
          correction: '"Amir and I" is the object of "picked", so it needs an object pronoun — "I" should be "me": picked Amir and me.',
          hint: "Remove “Amir and” and read the pronoun on its own — does “picked I” sound right?",
        },
      ],
      mistakes: [
        "Assuming “I” always sounds more correct or polite than “me” — the pronoun's grammatical job decides which is right, not formality.",
        "Missing hypercorrection because it disguises itself as careful, “proper” English rather than an obvious mistake.",
      ],
      examTip: "Whenever you see “…and I” at the end of a phrase, remove the other name and test the pronoun alone — hypercorrection collapses instantly under that test.",
      searchTerms: ["hypercorrection", "between you and i", "object pronoun", "preposition", "me"],
    },
  ],
};
