import type { TopicContent } from "../types";
import {
  IBeforeEDemo,
  TionSionDemo,
  AbleIbleDemo,
  AnceEnceDemo,
  DoublingConsonantDemo,
  SilentEDemo,
  YToIDemo,
  AryEryDemo,
  CeedCedeSedeDemo,
  ExceptionWordsDemo,
} from "../notes-diagrams/spelling-patterns-demos";

const CLICK_INSTRUCTION = "Click the misspelled word.";

export const spellingPatternsRulesTopic: TopicContent = {
  slug: "spelling-patterns-rules",
  subject: "English",
  subjectSlug: "english",
  title: "Spelling: Common Patterns & Rules",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "GL and CSSE-style “find the misspelt word” questions test exactly the patterns covered here — from i-before-e to the tiny exception lists like -ceed/-cede/-sede. This module works through ten of the most exam-relevant spelling rules, then trains you to spot a misspelling hiding in an otherwise ordinary sentence.",
  subtopics: [
    {
      id: "i-before-e",
      title: "“I Before E, Except After C”",
      tier: "Foundation",
      objective: "Apply the i-before-e rule correctly, and recognise that several very common words are exceptions to it.",
      whyMatters: "this is the first spelling rule most students learn, and it's tested constantly — but relying on it blindly, without knowing the exceptions, is a common trap.",
      conceptTitle: "The rule, and its limits",
      conceptBullets: [
        'The classic rule: write <b style="color:#C9A24B">i before e</b>, except after <b>c</b> — e.g. <i>believe</i>, <i>friend</i>, but <i>receive</i>, <i>ceiling</i>.',
        "After a <b>c</b>, the pattern flips to e-before-i, because that spelling matches the sound the c makes there.",
        "With no c in sight, the default is i-before-e — but this rule has real exceptions that simply have to be memorised.",
        'Famous exceptions: <i>weird</i>, <i>seize</i>, <i>their</i>, <i>height</i> — none of these follow the rule despite having no c nearby.',
      ],
      conceptNote: "<b>Remember:</b> the rule is a useful first guess, not a guarantee — always double-check high-frequency exception words like “weird”.",
      glossary: [
        { term: "i-before-e rule", def: "write i before e except directly after the letter c" },
        { term: "exception word", def: "a word that breaks a spelling rule and must be memorised" },
        { term: "vowel pair", def: "two vowels written next to each other, like ie or ei" },
      ],
      diagramLabel: "Interactive · Click the Misspelling",
      Diagram: IBeforeEDemo,
      worked: {
        question: "Spot the misspelling: “The theif was caught on camera near the school gates.”",
        fastMethod: 'No "c" comes before the vowel pair, so the standard rule applies: i before e.',
        steps: [
          "Read the sentence and check each word with an ie/ei vowel pair.",
          "The word “theif” has no c in front of it, so the standard rule applies.",
          "I before e except after c means this word should be spelled with i first: “thief.”",
          "Corrected: “The thief was caught on camera near the school gates.”",
        ],
        answer: "The error is <b>theif</b> — it should be <b>thief</b>.",
      },
      selfCheck: {
        prompt: "True or false: “weird” follows the i-before-e rule.",
        answer: "<b>False</b> — “weird” is one of the well-known exceptions; it keeps e before i even though there's no c in sight.",
      },
      kind: "click-error",
      questions: [
        {
          id: "ie-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Our", "teacher", "gave", "us", "a", "peice", "of", "paper", "each", "for", "the", "art", "project."],
          errorIdx: 5,
          correction: '"peice" breaks the i-before-e rule — with no c before it, i comes before e: "piece."',
          hint: "Look for a common noun meaning “a part of something.”",
        },
        {
          id: "ie-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "football", "coach", "was", "pleased", "to", "recieve", "the", "trophy", "on", "behalf", "of", "the", "whole", "team."],
          errorIdx: 6,
          correction: '"recieve" puts i before e, but this word follows a c, so the rule flips: e before i: "receive."',
          hint: "This word for “to get something” follows the letter c — check which way round the vowels go.",
        },
        {
          id: "ie-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Meera", "was", "determined", "to", "be", "a", "beleiver", "in", "her", "own", "ability", "before", "the", "audition."],
          errorIdx: 6,
          correction: 'no "c" comes before this vowel pair, so the standard rule applies — i before e: "believer."',
          hint: "This word for “someone who believes” has its vowels the wrong way round.",
        },
      ],
      mistakes: [
        "Applying the rule automatically without checking for a c right before the vowel pair — “receive” follows c, so it flips to e-before-i.",
        "Assuming the rule has no exceptions — high-frequency words like “weird”, “their” and “seize” simply have to be memorised.",
      ],
      examTip: "Say the word aloud, check for a c directly before the vowel pair, then check whether the word is a known exception before committing to your answer.",
      searchTerms: ["i before e", "spelling rule", "receive", "believe", "weird", "exception"],
    },
    {
      id: "tion-sion",
      title: "-tion vs. -sion Endings",
      tier: "Foundation",
      objective: "Choose correctly between -tion and -sion by listening for the sound and tracing the word back to its root.",
      whyMatters: "these endings sound almost identical when spoken, so exam questions rely on you knowing which spelling pattern the root word signals.",
      conceptTitle: "Same sound, different spelling",
      conceptBullets: [
        'Both <b style="color:#C9A24B">-tion</b> and <b>-sion</b> make the same “shun” sound at the end of a word.',
        "<b>-tion</b> is by far the most common ending — e.g. <i>station</i>, <i>invitation</i>, <i>action</i>.",
        "<b>-sion</b> usually follows a root ending in -d, -de or -s — e.g. <i>decide</i> → <i>decision</i>, <i>discuss</i> → <i>discussion</i>.",
        "When unsure, trace the word back to its root — the root's final letters usually reveal the correct ending.",
      ],
      conceptNote: "<b>Tip:</b> if the root ends in -ss, the noun form often doubles the s and adds -ion, not a fresh -sion or -tion suffix (discuss → discussion).",
      glossary: [
        { term: "root word", def: "the base word before a suffix is added" },
        { term: "suffix", def: "letters added to the end of a word to change its meaning or form" },
        { term: "-tion ending", def: "the more common “shun” spelling, e.g. station" },
        { term: "-sion ending", def: "the less common “shun” spelling, e.g. decision, television" },
      ],
      diagramLabel: "Interactive · Click the Misspelling",
      Diagram: TionSionDemo,
      worked: {
        question: "Spot the misspelling: “The teacher's decission surprised the whole class.”",
        fastMethod: '"decide" ends in -de, and roots ending in -d or -de usually become -sion, with a single s: "decision."',
        steps: [
          "Say the word aloud — it ends in the “zhun” sound shared by both -tion and -sion.",
          "Trace it back to its root: “decide” ends in -de.",
          "Roots ending in -d or -de almost always take -sion, not -tion, and never double the s.",
          "Corrected: “The teacher's decision surprised the whole class.”",
        ],
        answer: "The error is <b>decission</b> — it should be <b>decision</b>.",
      },
      selfCheck: {
        prompt: "Which ending does “television” take: -tion or -sion?",
        answer: "<b>-sion</b> — “television.”",
      },
      kind: "click-error",
      questions: [
        {
          id: "ts-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["After", "a", "long", "discusion,", "the", "students", "agreed", "on", "a", "plan", "for", "the", "project."],
          errorIdx: 3,
          correction: '"discuss" ends in -ss, so its noun form doubles the s before -ion: "discussion."',
          hint: "This word for “a talk about something” is missing a letter.",
        },
        {
          id: "ts-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "was", "thrilled", "to", "receive", "an", "invitasion", "to", "her", "cousin's", "wedding."],
          errorIdx: 6,
          correction: 'the “shun” sound here follows the pattern from “invite” — most words like this take -tion, not -sion: "invitation."',
          hint: "This word for a request to attend an event has the wrong ending.",
        },
        {
          id: "ts-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["We", "watched", "the", "football", "final", "on", "the", "new", "televition", "in", "the", "living", "room."],
          errorIdx: 8,
          correction: 'the “zhun” sound after “vi” is spelled -sion, not -tion: "television."',
          hint: "This word for the screen in the living room has the wrong ending sound spelled out.",
        },
      ],
      mistakes: [
        "Defaulting to -tion for every word, since it's the more common ending, and missing the smaller -sion group.",
        "Doubling or dropping letters at the join between the root and the suffix (e.g. writing “discusion” instead of “discussion”).",
      ],
      examTip: "Say the word slowly and trace it back to its simplest root — the root's final letters are usually the strongest clue to the correct ending.",
      searchTerms: ["tion", "sion", "suffix", "decision", "discussion", "television"],
    },
    {
      id: "able-ible",
      title: "-able vs. -ible Endings",
      tier: "Foundation",
      objective: "Choose correctly between -able and -ible by checking whether the root is a complete word on its own.",
      whyMatters: "these two endings sound identical, so exam questions test whether you know the pattern that predicts which one a word takes.",
      conceptTitle: "Complete word or not?",
      conceptBullets: [
        'Both <b style="color:#C9A24B">-able</b> and <b>-ible</b> mean roughly “able to be” — e.g. <i>enjoyable</i>, <i>visible</i>.',
        "<b>-able</b> is more common, and usually attaches to a root that is a complete word by itself — e.g. <i>enjoy</i> + able = <i>enjoyable</i>.",
        "<b>-ible</b> usually attaches to a root that is <i>not</i> a complete word alone — e.g. <i>vis</i> + ible = <i>visible</i>, <i>poss</i> + ible = <i>possible</i>.",
        "This is a strong pattern, not an absolute rule — a handful of words simply have to be learned by heart.",
      ],
      conceptNote: "<b>Quick test:</b> remove the ending — if what's left is a real word on its own, it's very likely -able.",
      glossary: [
        { term: "complete root", def: "a root that is a real word on its own, e.g. “use” in “usable”" },
        { term: "-able ending", def: "attaches to complete root words, e.g. enjoyable" },
        { term: "-ible ending", def: "attaches to incomplete roots, e.g. visible, possible" },
      ],
      diagramLabel: "Interactive · Click the Misspelling",
      Diagram: AbleIbleDemo,
      worked: {
        question: "Spot the misspelling: “The handwriting was barely legable in the old letter.”",
        fastMethod: '"leg" (as used here) is not a complete word on its own, which is a strong sign the word takes -ible: "legible."',
        steps: [
          "Check whether the letters before the ending form a complete word on their own.",
          "“Leg” in this sense is not a stand-alone word — that points to -ible.",
          "Words like this — visible, possible, legible — nearly always take -ible.",
          "Corrected: “The handwriting was barely legible in the old letter.”",
        ],
        answer: "The error is <b>legable</b> — it should be <b>legible</b>.",
      },
      selfCheck: {
        prompt: "Does “enjoy” take -able or -ible in its adjective form?",
        answer: "<b>-able</b> — “enjoyable,” because “enjoy” is a complete word on its own.",
      },
      kind: "click-error",
      questions: [
        {
          id: "ai-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["It", "was", "almost", "impossable", "to", "hear", "the", "announcement", "over", "the", "noise", "of", "the", "crowd."],
          errorIdx: 3,
          correction: '"possible" takes -ible, not -able, so its opposite is "impossible."',
          hint: "This word means “cannot happen” and has the wrong ending.",
        },
        {
          id: "ai-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Grandad", "said", "the", "old", "shed", "was", "still", "perfectly", "usible", "for", "storing", "tools."],
          errorIdx: 8,
          correction: '"use" is a complete word on its own, so it takes -able: "usable."',
          hint: "This word means “able to be used” and has the wrong ending.",
        },
        {
          id: "ai-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "old", "armchair", "by", "the", "fire", "was", "warm", "and", "comfortible", "after", "a", "long", "walk."],
          errorIdx: 9,
          correction: '"comfort" is a complete root word, so it takes -able: "comfortable."',
          hint: "This word describing the armchair has the wrong ending.",
        },
      ],
      mistakes: [
        "Guessing purely by sound, since -able and -ible sound identical when spoken.",
        "Forgetting that a handful of common words (like “legible” and “possible”) simply break the “complete word” pattern and must be memorised.",
      ],
      examTip: "Cover the ending and check whether what's left is a real word by itself — that single test resolves most -able/-ible questions.",
      searchTerms: ["able", "ible", "suffix", "possible", "visible", "comfortable"],
    },
    {
      id: "ance-ence",
      title: "-ance vs. -ence Endings",
      tier: "Standard",
      objective: "Choose correctly between -ance and -ence by linking the noun back to its related adjective form.",
      whyMatters: "these endings are easy to mix up under time pressure, and exam papers frequently test high-frequency words like “confidence” and “performance”.",
      conceptTitle: "Follow the adjective",
      conceptBullets: [
        'Both <b style="color:#C9A24B">-ance</b> and <b>-ence</b> turn a word into a noun describing a state or quality.',
        "A useful pattern: if the related adjective ends in <i>-ant</i>, the noun usually takes <b>-ance</b> — e.g. <i>important</i> → <i>importance</i>.",
        "If the related adjective ends in <i>-ent</i>, the noun usually takes <b>-ence</b> — e.g. <i>confident</i> → <i>confidence</i>.",
        "There's no completely foolproof rule, so learning the most common exam words by sight is essential.",
      ],
      conceptNote: "<b>Tip:</b> say the related -ant/-ent adjective in your head first — the noun ending usually mirrors it.",
      glossary: [
        { term: "-ance ending", def: "pairs with adjectives ending in -ant, e.g. important → importance" },
        { term: "-ence ending", def: "pairs with adjectives ending in -ent, e.g. confident → confidence" },
        { term: "related adjective", def: "the describing-word form linked to a noun" },
      ],
      diagramLabel: "Interactive · Click the Misspelling",
      Diagram: AnceEnceDemo,
      worked: {
        question: "Spot the misspelling: “The dancer's performence at the school concert amazed everyone.”",
        fastMethod: '"perform" pairs with the -ance ending here: "performance."',
        steps: [
          "Say the word aloud and isolate the root before the ending.",
          "“Perform” is the root — check which ending it conventionally pairs with.",
          "“Performance” is the correct, commonly used spelling, with -ance.",
          "Corrected: “The dancer's performance at the school concert amazed everyone.”",
        ],
        answer: "The error is <b>performence</b> — it should be <b>performance</b>.",
      },
      selfCheck: {
        prompt: "“Independent” ends in -ent — which ending does its noun form “independ____” take?",
        answer: "<b>-ence</b> — “independence,” following the adjective “independent.”",
      },
      kind: "click-error",
      questions: [
        {
          id: "ae-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "fire", "alarm", "test", "caused", "a", "brief", "disturbence", "during", "the", "maths", "lesson."],
          errorIdx: 7,
          correction: '"disturb" pairs with the -ance ending here: "disturbance."',
          hint: "This word for an interruption has the wrong ending.",
        },
        {
          id: "ae-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "scientist's", "experiment", "required", "great", "patience", "and", "total", "independance", "from", "outside", "help."],
          errorIdx: 8,
          correction: '"independent" ends in -ent, so its noun form takes -ence: "independence."',
          hint: "This word meaning “freedom from others” has the wrong ending.",
        },
        {
          id: "ae-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Scientists", "have", "found", "evidence", "of", "the", "existance", "of", "water", "on", "the", "planet."],
          errorIdx: 6,
          correction: '"exist" pairs with the -ence ending here: "existence."',
          hint: "This word meaning “the state of being real” has the wrong ending.",
        },
      ],
      mistakes: [
        "Picking the ending that “looks right” without checking the related -ant/-ent adjective first.",
        "Mixing up common exam pairs like “performance/performence” and “existence/existance” under time pressure.",
      ],
      examTip: "If you know the related adjective (confident, important, independent), the noun ending almost always mirrors its final letters.",
      searchTerms: ["ance", "ence", "suffix", "confidence", "performance", "existence"],
    },
    {
      id: "doubling-consonant",
      title: "Doubling the Final Consonant Before a Suffix",
      tier: "Standard",
      objective: "Decide when to double a word's final consonant before adding a suffix like -ing or -ed, and when not to.",
      whyMatters: "doubling errors (or missing a needed double) are one of the most common spelling mistakes in fast, exam-style writing.",
      conceptTitle: "Short vowel, single consonant, double it",
      conceptBullets: [
        'Double the final consonant before adding <b style="color:#C9A24B">-ing</b> or <b>-ed</b> when a one-syllable word has a short vowel before a single final consonant — e.g. <i>run</i> → <i>running</i>, <i>stop</i> → <i>stopped</i>.',
        "<b>Do not</b> double when two vowels come before the consonant — e.g. <i>rain</i> → <i>raining</i>, not “rainning.”",
        "<b>Do not</b> double when the word already ends in two consonants — e.g. <i>jump</i> → <i>jumping</i>.",
        "In longer words, only double if the stress falls on the final syllable — e.g. <i>preFER</i> → <i>preferred</i>, but <i>VISit</i> → <i>visiting</i> (no double).",
      ],
      conceptNote: "<b>Quick test:</b> say the word aloud — one short, stressed syllable ending in a single consonant almost always means double it.",
      glossary: [
        { term: "short vowel", def: "a quick vowel sound, as in “run” or “stop”" },
        { term: "final consonant", def: "the last consonant letter in a word" },
        { term: "stressed syllable", def: "the syllable said with the most emphasis" },
      ],
      diagramLabel: "Interactive · Click the Misspelling",
      Diagram: DoublingConsonantDemo,
      worked: {
        question: "Spot the misspelling: “She was swiming at the local pool every Saturday morning.”",
        fastMethod: '"swim" is a one-syllable word with a short vowel before a single final consonant, so the m doubles before -ing.',
        steps: [
          "Break the word down: “swim” — one syllable, short vowel “i,” single final consonant “m.”",
          "This pattern (short vowel + single consonant) means the final consonant doubles before a vowel suffix.",
          "The correct spelling doubles the m: “swimming.”",
          "Corrected: “She was swimming at the local pool every Saturday morning.”",
        ],
        answer: "The error is <b>swiming</b> — it should be <b>swimming</b>.",
      },
      selfCheck: {
        prompt: "Should “visit” double its final t before -ing?",
        answer: "<b>No</b> — the stress falls on the first syllable (“VIS-it”), so it stays as “visiting,” not “visitting.”",
      },
      kind: "click-error",
      questions: [
        {
          id: "db-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "puppy", "kept", "diging", "holes", "all", "over", "the", "back", "garden."],
          errorIdx: 3,
          correction: '"dig" is a one-syllable word with a short vowel and a single final consonant, so the g doubles before -ing: "digging."',
          hint: "This word for what the puppy was doing to the garden is missing a doubled letter.",
        },
        {
          id: "db-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["He", "enjoyed", "visitting", "his", "grandparents", "in", "Cornwall", "every", "summer."],
          errorIdx: 2,
          correction: '"visit" is stressed on the first syllable, so the final t does not double before -ing: "visiting."',
          hint: "This word for going to see family has an extra letter that shouldn't be doubled.",
        },
        {
          id: "db-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "gardener", "was", "planing", "to", "trim", "the", "hedges", "before", "the", "rain", "arrived."],
          errorIdx: 3,
          correction: '"plan" has a short vowel before a single final consonant, so the n doubles before -ing: "planning."',
          hint: "This word for what the gardener was doing is missing a doubled letter.",
        },
      ],
      mistakes: [
        "Doubling a consonant that shouldn't be doubled in multi-syllable words where the stress isn't on the final syllable (e.g. “visitting”).",
        "Forgetting to double a short one-syllable word's final consonant (e.g. writing “stoping” instead of “stopping”).",
      ],
      examTip: "Say the word aloud and listen for the stress — a single, sharply stressed syllable ending in one consonant is the clearest sign to double it.",
      searchTerms: ["doubling consonant", "suffix", "running", "stopped", "short vowel", "visiting"],
    },
    {
      id: "silent-e-drop",
      title: "Dropping the Silent E Before a Suffix",
      tier: "Standard",
      objective: "Know when to drop a word's silent final e before adding a suffix, and when to keep it.",
      whyMatters: "silent-e errors are extremely common in fast writing, and the rule has a handful of well-tested exceptions.",
      conceptTitle: "Vowel suffix drops it, consonant suffix keeps it",
      conceptBullets: [
        'When a word ends in a silent <b style="color:#C9A24B">e</b> and the suffix begins with a <b>vowel</b>, drop the e — e.g. <i>hope</i> → <i>hoping</i>, <i>care</i> → <i>caring</i>.',
        "When the suffix begins with a <b>consonant</b>, the silent e usually stays — e.g. <i>hope</i> → <i>hopeful</i>, <i>care</i> → <i>careless</i>.",
        'Exception: some words keep the silent e even before a vowel suffix, to protect a soft "c" or "g" sound — e.g. <i>notice</i> → <i>noticeable</i>, <i>courage</i> → <i>courageous</i>.',
        "This exception only applies before -able and -ous, not before -ing.",
      ],
      conceptNote: "<b>Remember:</b> vowel suffix, drop the e; consonant suffix, keep the e — except for the soft c/g words like “noticeable.”",
      glossary: [
        { term: "silent e", def: "a final e that isn't pronounced, e.g. in “hope”" },
        { term: "vowel suffix", def: "a suffix beginning with a vowel, e.g. -ing, -able" },
        { term: "consonant suffix", def: "a suffix beginning with a consonant, e.g. -ful, -less" },
        { term: "soft c/g exception", def: "words that keep the e to protect a soft sound, e.g. noticeable" },
      ],
      diagramLabel: "Interactive · Click the Misspelling",
      Diagram: SilentEDemo,
      worked: {
        question: "Spot the misspelling: “She was carefully writeing her name at the top of the exam paper.”",
        fastMethod: '"write" ends in a silent e, which is dropped before the vowel suffix -ing.',
        steps: [
          "Identify the root word: “write,” which ends in a silent e.",
          "The suffix being added, -ing, begins with a vowel.",
          "When a suffix starts with a vowel, the silent e is dropped: “writing.”",
          "Corrected: “She was carefully writing her name at the top of the exam paper.”",
        ],
        answer: "The error is <b>writeing</b> — it should be <b>writing</b>.",
      },
      selfCheck: {
        prompt: "Does “notice” keep or drop its e before -able?",
        answer: "<b>Keeps it</b> — “noticeable,” to preserve the soft c sound. This is an exception to the usual rule.",
      },
      kind: "click-error",
      questions: [
        {
          id: "se-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["My", "little", "brother", "is", "learning", "how", "to", "rideing", "his", "new", "bike", "without", "stabilisers."],
          errorIdx: 7,
          correction: '"ride" ends in a silent e, which is dropped before the vowel suffix -ing: "riding."',
          hint: "This word for what her brother is learning to do keeps a letter that should be dropped.",
        },
        {
          id: "se-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Dad", "was", "busy", "makeing", "sandwiches", "for", "our", "picnic", "in", "the", "park."],
          errorIdx: 3,
          correction: '"make" ends in a silent e, which is dropped before -ing: "making."',
          hint: "This word for what Dad was doing with the sandwiches has an extra letter.",
        },
        {
          id: "se-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "town", "was", "known", "for", "its", "noticable", "church", "spire,", "visible", "from", "miles", "away."],
          errorIdx: 6,
          correction: '"notice" keeps its silent e before -able to preserve the soft "c" sound: "noticeable" — an exception to the usual drop-the-e rule.',
          hint: "This word describing the church spire is missing a letter that protects a soft sound.",
        },
      ],
      mistakes: [
        "Dropping the e even before a consonant suffix (e.g. writing “hopeful” as “hopful”).",
        "Forgetting the soft c/g exception and dropping the e in words like “noticeable” and “courageous.”",
      ],
      examTip: "Check the first letter of the suffix first — vowel means drop the e, consonant means keep it, unless it's a soft c/g exception.",
      searchTerms: ["silent e", "suffix", "hoping", "writing", "noticeable", "drop the e"],
    },
    {
      id: "y-to-i",
      title: "The Y-to-I Rule Before Suffixes",
      tier: "Standard",
      objective: "Apply the rule for changing a final y to i before a suffix, and know the key exception before -ing.",
      whyMatters: "this rule governs extremely common words (happy, carry, try), and the -ing exception is a frequent trap.",
      conceptTitle: "Consonant + y changes; vowel + y doesn't",
      conceptBullets: [
        'When a word ends in a consonant followed by <b style="color:#C9A24B">y</b>, change the y to <b>i</b> before most suffixes — e.g. <i>happy</i> → <i>happiness</i>, <i>carry</i> → <i>carried</i>.',
        'When a word ends in a <b>vowel</b> followed by y, the y stays the same — e.g. <i>play</i> → <i>played</i>, not “plaied.”',
        "<b>Exception:</b> before the suffix -ing, the y never changes, even after a consonant — e.g. <i>carry</i> → <i>carrying</i>, not “carriing.”",
        "This exception exists to avoid an awkward double i in the middle of a word.",
      ],
      conceptNote: "<b>Remember:</b> consonant + y changes to i everywhere except before -ing, where it always stays as y.",
      glossary: [
        { term: "consonant + y", def: "a word ending in a consonant then y, e.g. “happy”" },
        { term: "vowel + y", def: "a word ending in a vowel then y, e.g. “play”" },
        { term: "-ing exception", def: "the y never changes to i before -ing" },
      ],
      diagramLabel: "Interactive · Click the Misspelling",
      Diagram: YToIDemo,
      worked: {
        question: "Spot the misspelling: “The little girl cryed all afternoon after losing her toy.”",
        fastMethod: '"cry" follows a consonant, so the y changes to i before -ed: "cried."',
        steps: [
          "Find the root word: “cry,” which ends in a consonant followed by y.",
          "Before most suffixes (like -ed), a consonant + y changes to i.",
          "The correct spelling changes y to i: “cried.”",
          "Corrected: “The little girl cried all afternoon after losing her toy.”",
        ],
        answer: "The error is <b>cryed</b> — it should be <b>cried</b>.",
      },
      selfCheck: {
        prompt: "Does “carry” change its y to i before -ing?",
        answer: "<b>No</b> — before -ing the y stays the same to avoid a double i: “carrying,” not “carriing.”",
      },
      kind: "click-error",
      questions: [
        {
          id: "yi-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "postman", "carryed", "the", "heavy", "parcels", "up", "three", "flights", "of", "stairs."],
          errorIdx: 2,
          correction: '"carry" follows a consonant, so the y changes to i before -ed: "carried."',
          hint: "This word for what the postman did with the parcels has the wrong letter before the ending.",
        },
        {
          id: "yi-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["She", "was", "carriing", "her", "little", "sister's", "school", "bag", "as", "well", "as", "her", "own."],
          errorIdx: 2,
          correction: 'before -ing, the y does NOT change to i (that would create a double i) — keep the y: "carrying."',
          hint: "This word for what she was doing with the bag wrongly changes a letter that should stay the same before -ing.",
        },
        {
          id: "yi-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "whole", "family", "was", "very", "happyly", "surprised", "by", "the", "news", "of", "the", "new", "baby."],
          errorIdx: 5,
          correction: '"happy" follows a consonant, so the y changes to i before -ly: "happily."',
          hint: "This word describing how the family felt has the wrong letter before the ending.",
        },
      ],
      mistakes: [
        "Forgetting the -ing exception and writing a double i (e.g. “carriing” instead of “carrying”).",
        "Changing the y to i even when it follows a vowel (e.g. writing “plaied” instead of “played”).",
      ],
      examTip: "Before changing y to i, check the very next letter — if it's -ing, the y always stays put.",
      searchTerms: ["y to i", "suffix", "happiness", "carried", "carrying", "consonant y"],
    },
    {
      id: "ary-ery",
      title: "-ary vs. -ery Endings",
      tier: "Extension",
      objective: "Choose correctly between -ary and -ery, recognising -ary as the far more common pattern.",
      whyMatters: "these endings sound identical, and this pair includes one of the most famous confusable words in English: stationary/stationery.",
      conceptTitle: "A common pattern, and a small group of exceptions",
      conceptBullets: [
        'The ending <b style="color:#C9A24B">-ary</b> is far more common — e.g. <i>library</i>, <i>dictionary</i>, <i>necessary</i>, <i>ordinary</i>.',
        "<b>-ery</b> belongs to a much smaller group of words — e.g. <i>bakery</i>, <i>cemetery</i>, <i>stationery</i>, <i>bravery</i>.",
        'The famous confusable pair: <i>stationary</i> (not moving) vs. <i>stationery</i> (paper and pens) — same sound, different spelling and meaning.',
        "When in doubt, -ary is the safer first guess, but the small -ery group has to be learned by sight.",
      ],
      conceptNote: "<b>Memory trick:</b> stationERy has an E for envelopes; stationARy has an A for “at a standstill.”",
      glossary: [
        { term: "-ary ending", def: "the more common “uh-ree” spelling, e.g. library" },
        { term: "-ery ending", def: "the smaller group, e.g. bakery, stationery" },
        { term: "confusable pair", def: "two words that sound alike but differ in spelling and meaning" },
      ],
      diagramLabel: "Interactive · Click the Misspelling",
      Diagram: AryEryDemo,
      worked: {
        question: "Spot the misspelling: “It is not always necessery to bring a calculator to the exam.”",
        fastMethod: '"necessary" is one of the more common words that takes -ary, not -ery.',
        steps: [
          "Say the word aloud and isolate the ending sound — it's the “uh-ree” sound shared by both -ary and -ery.",
          "Most English words with this sound take the far more common ending, -ary.",
          "“Necessary” is one of these -ary words.",
          "Corrected: “It is not always necessary to bring a calculator to the exam.”",
        ],
        answer: "The error is <b>necessery</b> — it should be <b>necessary</b>.",
      },
      selfCheck: {
        prompt: "Which is correct for a shop that sells bread: “bakary” or “bakery”?",
        answer: "<b>Bakery</b> — one of the smaller group of words that take -ery.",
      },
      kind: "click-error",
      questions: [
        {
          id: "ay-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["Every", "classroom", "in", "the", "school", "has", "its", "own", "small", "libery", "of", "books", "to", "borrow."],
          errorIdx: 9,
          correction: '"library" takes the -ary ending, not -ery: "library."',
          hint: "This word for a room full of books has the wrong ending.",
        },
        {
          id: "ay-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["Grandma", "keeps", "a", "small", "dictionery", "on", "the", "kitchen", "shelf", "for", "crossword", "puzzles."],
          errorIdx: 4,
          correction: '"dictionary" takes the -ary ending, not -ery: "dictionary."',
          hint: "This word for a book of word meanings has the wrong ending.",
        },
        {
          id: "ay-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "smell", "of", "fresh", "bread", "drifted", "from", "the", "bakary", "on", "the", "corner", "every", "morning."],
          errorIdx: 8,
          correction: '"bakery" is one of the smaller group of words that take -ery, not -ary: "bakery."',
          hint: "This word for a shop that sells bread has the wrong ending.",
        },
      ],
      mistakes: [
        "Defaulting to -ery because it happens to fit the word being tested, when -ary is statistically far more likely.",
        "Mixing up “stationary” (not moving) and “stationery” (paper and pens) — they sound identical but mean very different things.",
      ],
      examTip: "If you're unsure, -ary is the safer guess — then check the word isn't one of the small, well-known -ery exceptions.",
      searchTerms: ["ary", "ery", "stationary", "stationery", "library", "dictionary", "bakery"],
    },
    {
      id: "ceed-cede-sede",
      title: "-ceed / -cede / -sede Endings",
      tier: "Extension",
      objective: "Correctly spell words ending in this sound by memorising the small, closed list of -ceed and -sede exceptions.",
      whyMatters: "this is one of the smallest, most memorisable exception lists in English spelling, and it's a favourite for testing careful preparation.",
      conceptTitle: "A tiny, closed exception list",
      conceptBullets: [
        'Only <b>three</b> English words end in <b style="color:#C9A24B">-ceed</b>: <i>succeed</i>, <i>proceed</i> and <i>exceed</i>.',
        'Only <b>one</b> English word ends in <b>-sede</b>: <i>supersede</i>.',
        "Every other word with this sound — <i>precede</i>, <i>concede</i>, <i>recede</i>, <i>secede</i> — ends in -cede.",
        "Because the list of -ceed and -sede words is so small, the safest approach is to memorise those four words by heart and default to -cede for everything else.",
      ],
      conceptNote: "<b>Memory trick:</b> “Succeed, proceed and exceed all -ceed; supersede is the only one that -sede.”",
      glossary: [
        { term: "-cede ending", def: "the default spelling for this sound, e.g. precede, concede" },
        { term: "-ceed ending", def: "used only in succeed, proceed, exceed" },
        { term: "-sede ending", def: "used only in supersede" },
      ],
      diagramLabel: "Interactive · Click the Misspelling",
      Diagram: CeedCedeSedeDemo,
      worked: {
        question: "Spot the misspelling: “The runners were told not to preceed past the marked line before the whistle.”",
        fastMethod: "only three words end in -ceed (succeed, proceed, exceed) — everything else with this sound ends in -cede.",
        steps: [
          "Check whether the word is one of the three -ceed exceptions: succeed, proceed, exceed.",
          "“Precede” is not one of them, so it follows the far more common pattern.",
          "The correct spelling ends in -cede: “precede.”",
          "Corrected: “The runners were told not to precede past the marked line before the whistle.”",
        ],
        answer: "The error is <b>preceed</b> — it should be <b>precede</b>.",
      },
      selfCheck: {
        prompt: "How many English words end in -sede?",
        answer: "<b>Just one</b> — “supersede.”",
      },
      kind: "click-error",
      questions: [
        {
          id: "cc-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "head", "teacher", "was", "confident", "the", "students", "would", "succede", "in", "their", "exams."],
          errorIdx: 8,
          correction: '"succeed" is one of only three English words ending in -ceed (succeed, proceed, exceed): "succeed."',
          hint: "This word meaning “to do well” belongs to a very small group of exceptions.",
        },
        {
          id: "cc-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "fire", "marshal", "asked", "everyone", "to", "procede", "calmly", "towards", "the", "nearest", "exit."],
          errorIdx: 6,
          correction: '"proceed" is one of the three -ceed words (succeed, proceed, exceed): "proceed."',
          hint: "This word meaning “to continue” belongs to the small -ceed exception group.",
        },
        {
          id: "cc-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["Nobody", "expected", "the", "new", "phone", "to", "superseed", "the", "old", "model", "so", "quickly."],
          errorIdx: 6,
          correction: '"supersede" is the only English word ending in -sede: "supersede."',
          hint: "This word meaning “to replace” is the single exception in its own ending family.",
        },
      ],
      mistakes: [
        "Assuming any word with this sound could plausibly end in -ceed, instead of checking it against the closed list of three.",
        "Misspelling “supersede” as “superceed” or “supercede” — it is the only -sede word and easy to mix up with the -ceed group.",
      ],
      examTip: "Memorise the four exceptions by heart (succeed, proceed, exceed, supersede) — every other word with this sound ends in -cede.",
      searchTerms: ["ceed", "cede", "sede", "succeed", "proceed", "supersede", "precede"],
    },
    {
      id: "exception-words",
      title: "Common Rule-Breaking Exception Words",
      tier: "Extension",
      objective: "Recognise a set of well-known words that defy the standard spelling rules covered in this topic, and know when a rule simply doesn't apply.",
      whyMatters: "exam papers deliberately test high-frequency exception words, because relying on a rule without checking for exceptions is the most common way marks are lost.",
      conceptTitle: "When the rules don't apply",
      conceptBullets: [
        "Every rule in this topic — i-before-e, silent-e dropping, y-to-i — has at least one commonly tested exception word.",
        '<i>Weird</i> and <i>friend</i> break the i-before-e rule with no c in sight; <i>truly</i> drops its silent e even before a consonant suffix.',
        'Some words are simply misspelled so often that examiners target them directly — e.g. <i>necessary</i> (one c, two s’s) and <i>separate</i> (a-r-a-t-e, not "e-r-a-t-e").',
        "The only reliable strategy for exception words is to learn them individually — no single rule will catch them.",
      ],
      conceptNote: "<b>Strategy:</b> keep a short personal list of exception words you keep getting wrong, and revisit it regularly — rules alone won't cover everything.",
      glossary: [
        { term: "exception word", def: "a word that doesn't follow the expected spelling rule" },
        { term: "high-frequency word", def: "a very commonly used word, often specifically tested for spelling" },
        { term: "rule of thumb", def: "a generally reliable pattern that still has exceptions" },
      ],
      diagramLabel: "Interactive · Click the Misspelling",
      Diagram: ExceptionWordsDemo,
      worked: {
        question: "Spot the misspelling: “It was a wierd coincidence that both friends wore the same jacket.”",
        fastMethod: '"weird" is a famous i-before-e exception with no c in sight — it simply has to be memorised.',
        steps: [
          "Check the vowel pair against the i-before-e rule.",
          "There is no c before this pair, so the rule would predict i before e.",
          "“Weird” is a well-known exception that breaks the rule anyway — e comes before i.",
          "Corrected: “It was a weird coincidence that both friends wore the same jacket.”",
        ],
        answer: "The error is <b>wierd</b> — it should be <b>weird</b>.",
      },
      selfCheck: {
        prompt: "True or false: every spelling rule in this topic has zero exceptions.",
        answer: "<b>False</b> — most of these rules (especially i-before-e) have well-known exception words that must simply be learned by heart.",
      },
      kind: "click-error",
      questions: [
        {
          id: "ex-q1",
          instruction: CLICK_INSTRUCTION,
          words: ["The", "whole", "class", "thought", "it", "was", "truely", "strange", "that", "the", "fire", "alarm", "rang", "twice."],
          errorIdx: 6,
          correction: '"true" is an exception — unlike most words, it drops the silent e even before the consonant suffix -ly: "truly."',
          hint: "This word meaning “genuinely” breaks the usual keep-the-e-before-a-consonant rule.",
        },
        {
          id: "ex-q2",
          instruction: CLICK_INSTRUCTION,
          words: ["My", "best", "freind", "came", "round", "for", "tea", "after", "school", "on", "Friday."],
          errorIdx: 2,
          correction: '"friend" is a well-known exception to the i-before-e rule — there is no c before it, yet e still comes before i: "friend." It simply has to be memorised.',
          hint: "This word for a close companion is one of English's most famous spelling exceptions.",
        },
        {
          id: "ex-q3",
          instruction: CLICK_INSTRUCTION,
          words: ["It", "is", "not", "always", "neccessary", "to", "bring", "a", "packed", "lunch", "on", "a", "school", "trip."],
          errorIdx: 4,
          correction: '"necessary" is a commonly misspelled exception word — one c, two s’s ("one collar, two sleeves"): "necessary."',
          hint: "This word meaning “required” is often written with the wrong number of doubled letters.",
        },
      ],
      mistakes: [
        "Applying a rule confidently without pausing to check whether the specific word is a known exception.",
        "Under-preparing for the small set of extremely high-frequency exception words that exam papers return to again and again.",
      ],
      examTip: "Treat every rule in this topic as “usually true” rather than “always true” — the exception words are exactly what separates a strong speller from a great one.",
      searchTerms: ["exceptions", "weird", "friend", "necessary", "truly", "irregular spelling"],
    },
  ],
};
