import type { TopicContent } from "../types";
import {
  ClozeDefinitionDemo,
  FormatDifferencesDemo,
  McVsOpenClozeDemo,
  GrammarAndComprehensionDemo,
  PassageStructureDemo,
  ClozeMarkingDemo,
  ClozeMisconceptionsDemo,
  ReadPassageFirstDemo,
  CombinedSkillsDemo,
  ClozeExpectationsDemo,
} from "../notes-diagrams/what-is-cloze-demos";

const CLICK_INSTRUCTION = "Click the word that correctly fills the gap.";

export const whatIsClozeTopic: TopicContent = {
  slug: "what-is-cloze",
  subject: "English",
  subjectSlug: "english",
  title: "Cloze: What It Is & How It's Tested",
  glyphs: ["“", ".", ",", "!", "?", "A"],
  description:
    "Cloze questions remove words from a passage and ask you to put the right ones back — testing vocabulary, grammar and comprehension all at once. This module introduces the format itself: how GL, CEM and CSSE papers present it differently, how it’s marked, and the habits that make it feel far less intimidating than it first appears.",
  subtopics: [
    {
      id: "cloze-definition",
      title: "What Is a Cloze Test?",
      tier: "Foundation",
      objective: "Define a cloze test and recognise the basic missing-word passage format used across 11+ exam boards.",
      whyMatters: "every cloze question on every board starts from this same basic idea — understanding it makes every later strategy make sense.",
      conceptTitle: "The basic idea",
      conceptBullets: [
        'A <b style="color:#C9A24B">cloze test</b> is a passage with one or more words removed, each replaced by a blank space or line — called a <i>gap</i>.',
        "Your job is to work out, and supply, the word that belongs in each gap.",
        'The name comes from "closure" — filling a gap correctly restores, or "closes", the sense of the sentence.',
        "Cloze passages are always connected prose — a story, a letter, a description — never a random list of unrelated sentences.",
      ],
      conceptNote: "<b>Remember:</b> a cloze gap is never testing a random guess — there is always one word (or a small set of acceptable words) that the examiner has in mind.",
      glossary: [
        { term: "cloze test", def: "a passage with words removed for you to supply" },
        { term: "gap", def: "the blank space where a word has been removed" },
        { term: "passage", def: "the connected piece of writing the gaps sit within" },
        { term: "closure", def: "the word origin — completing the sense of a sentence" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: ClozeDefinitionDemo,
      worked: {
        question: "Which word best completes: “The kettle began to ___ as the water reached boiling point”?",
        fastMethod: "Picture the scene — a kettle at boiling point makes a specific, recognisable sound.",
        steps: [
          "Read the whole sentence first to understand the scene: water reaching boiling point.",
          "Think about what a kettle actually does at that moment — it whistles or hisses.",
          "Check that your chosen word fits the grammar of “began to ___” — it needs a base-form verb.",
          "“Whistle” fits both the meaning and the grammar: “began to whistle”.",
        ],
        answer: "The missing word is <b>whistle</b> (or a close synonym like <b>hiss</b>, depending on the mark scheme).",
      },
      selfCheck: { prompt: "True or false: a cloze passage can be made up of several unrelated sentences with no connection between them.", answer: "<b>False</b> — a cloze passage is always connected prose, like a story or description, not a random list of sentences." },
      kind: "cloze-fill",
      questions: [
        {
          id: "cloze-def-q1",
          instruction: CLICK_INSTRUCTION,
          before: "In a cloze test, one or more words are removed from a passage, leaving a blank called a",
          options: ["footnote", "heading", "gap", "margin"],
          correctIdx: 2,
          after: "for you to fill in.",
          correction: "“gap” — cloze tests remove words and leave gaps for you to fill back in.",
          hint: "Think about the general word for a blank space left in a sentence.",
        },
        {
          id: "cloze-def-q2",
          instruction: CLICK_INSTRUCTION,
          before: "The word “cloze” comes from the word “closure”, because filling each gap correctly helps",
          options: ["complete", "confuse", "shorten", "translate"],
          correctIdx: 0,
          after: "the meaning of the passage.",
          correction: "“complete” — cloze exercises are about completing the sense of a passage, which is where the name comes from.",
          hint: "Think about what happens to a passage once every gap has been filled correctly.",
        },
        {
          id: "cloze-def-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Unlike a comprehension question, which usually asks about a whole passage, a cloze gap tests understanding at the level of a single",
          options: ["chapter", "word", "book", "author"],
          correctIdx: 1,
          after: "within its sentence.",
          correction: "“word” — cloze questions zoom in on one missing word at a time, rather than the passage as a whole.",
          hint: "Cloze questions are narrower and more specific than general comprehension questions — what’s the smallest unit being tested?",
        },
      ],
      mistakes: [
        "Treating a cloze gap like a totally open-ended question, when the examiner usually has one specific word (or a narrow set of synonyms) in mind.",
        "Forgetting that a cloze passage is connected prose — clues for a gap can come from anywhere in the passage, not just its own sentence.",
      ],
      examTip: "Before answering any gap, read the sentence it sits in at least twice — once for the shape of the sentence, once for its meaning.",
      searchTerms: ["cloze", "cloze test", "missing word", "gap fill", "definition", "closure"],
    },
    {
      id: "format-differences",
      title: "How GL, CEM & CSSE Present Cloze Differently",
      tier: "Foundation",
      objective: "Recognise the different ways exam boards structure cloze questions, including word banks and fixed-interval gaps.",
      whyMatters: "walking into the exam not knowing whether a word bank is coming can cost you time — knowing the format in advance lets you plan your approach.",
      conceptTitle: "Same idea, different formats",
      conceptBullets: [
        'Some boards provide a <b style="color:#C9A24B">word bank</b> — a list of the missing words (sometimes with a few extra decoys) for you to place correctly.',
        "Other boards give no word bank at all, expecting you to think of a suitable word entirely yourself.",
        "Some passages remove words at a regular interval (e.g. every seventh word), which can land on almost any part of speech.",
        "Other passages target specific words — often ones that test a particular skill, like a tricky verb form or connective.",
      ],
      conceptNote: "<b>Always check the instructions first</b> — they tell you whether a word bank exists and whether exact spelling will be marked.",
      glossary: [
        { term: "word bank", def: "a printed list of the missing words to choose from" },
        { term: "fixed-interval cloze", def: "a format that removes every Nth word automatically" },
        { term: "targeted cloze", def: "a format where specific words are deliberately chosen to be removed" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: FormatDifferencesDemo,
      worked: {
        question: "A paper says: “Complete the passage using the word bank below.” What does this tell you about the format?",
        fastMethod: "The phrase “word bank” signals that you are selecting from a given list, not inventing words yourself.",
        steps: [
          "Spot the key phrase “word bank” in the instructions.",
          "This means every missing word is already printed somewhere on the page.",
          "Your task shifts from “think of a word” to “match the right word to the right gap”.",
          "You can use process of elimination across all the gaps, not just one at a time.",
        ],
        answer: "The paper is using a <b>word-bank format</b>, so every answer is provided — the task is matching, not inventing.",
      },
      selfCheck: { prompt: "True or false: every 11+ cloze paper provides a word bank.", answer: "<b>False</b> — some boards, especially CEM-style papers, expect you to supply the word yourself with no list given." },
      kind: "cloze-fill",
      questions: [
        {
          id: "format-q1",
          instruction: CLICK_INSTRUCTION,
          before: "A GL-style cloze passage often provides a",
          options: ["dictionary", "word bank", "answer key", "glossary"],
          correctIdx: 1,
          after: "listing all the missing words, sometimes with extras to choose from.",
          correction: "“word bank” — many GL-style papers list the missing words (sometimes with a few extra distractors) for you to place correctly.",
          hint: "Think about the list of possible answers sometimes printed above or below the passage.",
        },
        {
          id: "format-q2",
          instruction: CLICK_INSTRUCTION,
          before: "A CEM-style cloze passage may instead remove every",
          options: ["punctuation mark", "proper noun", "seventh word", "first letter"],
          correctIdx: 2,
          after: "regardless of what type of word it is.",
          correction: "“seventh word” — some cloze formats remove words at a fixed interval rather than targeting specific ones, which can include almost any part of speech.",
          hint: "This format isn’t about choosing tricky words — it’s about a regular counting pattern.",
        },
        {
          id: "format-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Whether or not a word bank is provided, always check the instructions first, because this changes whether you are",
          options: ["selecting", "reading", "skimming", "translating"],
          correctIdx: 0,
          after: "from a list or supplying the word yourself.",
          correction: "“selecting” — with a word bank you choose from a list; without one, you must think of the word yourself, so the instructions matter.",
          hint: "Think about what a word bank allows you to do that its absence does not.",
        },
      ],
      mistakes: [
        "Assuming every cloze paper works the same way — skipping the instructions and missing a word bank, or expecting one that isn’t there.",
        "Not noticing whether a fixed-interval format is in use, which means grammar words like “the” or “and” can just as easily be gaps as content words.",
      ],
      examTip: "Spend ten seconds reading the instructions before starting — knowing whether a word bank exists changes your entire strategy for the passage.",
      searchTerms: ["gl cloze", "cem cloze", "csse cloze", "word bank", "exam format", "fixed interval"],
    },
    {
      id: "mc-vs-open-cloze",
      title: "Multiple-Choice Cloze vs. Open Cloze",
      tier: "Foundation",
      objective: "Distinguish multiple-choice cloze (choosing from given options) from open cloze (writing the word yourself).",
      whyMatters: "recognising which type you're facing tells you immediately whether to focus on elimination or on recall.",
      conceptTitle: "Choosing vs. supplying",
      conceptBullets: [
        'In <b style="color:#C9A24B">multiple-choice cloze</b>, each gap comes with a short list of options, and you pick the one that fits.',
        'In <b>open cloze</b>, no options are given — you must think of, spell and write the word yourself.',
        "Multiple-choice cloze rewards careful comparison between similar-looking options — the right answer is always in front of you.",
        "Open cloze rewards strong vocabulary and confident spelling, since nothing is provided to jog your memory.",
      ],
      conceptNote: "<b>This module’s exercises are all multiple-choice</b>, so you can practise the comparing-and-eliminating skill directly — but remember real papers may ask for open cloze instead.",
      glossary: [
        { term: "multiple-choice cloze", def: "a gap with several given options to choose from" },
        { term: "open cloze", def: "a gap with no options — you supply the word" },
        { term: "distractor", def: "an incorrect option designed to look plausible" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: McVsOpenClozeDemo,
      worked: {
        question: "A gap is followed by four bracketed options: (arrived / arriving / arrival / arrives). What type of cloze is this?",
        fastMethod: "Bracketed options after a gap are the clearest sign of multiple-choice cloze.",
        steps: [
          "Notice that four words are printed right next to the gap.",
          "This means you are choosing, not inventing, the answer.",
          "Compare the options against both the grammar and the meaning of the sentence.",
          "Only one of the four will fit both tests at once.",
        ],
        answer: "This is <b>multiple-choice cloze</b> — the bracketed options confirm you are selecting an answer, not writing one from scratch.",
      },
      selfCheck: { prompt: "True or false: open cloze is generally harder than multiple-choice cloze.", answer: "<b>True</b> — with no options given, open cloze relies entirely on your own vocabulary and spelling, with nothing to prompt or confirm your answer." },
      kind: "cloze-fill",
      questions: [
        {
          id: "mc-open-q1",
          instruction: CLICK_INSTRUCTION,
          before: "In multiple-choice cloze, several possible words are printed for each gap and you must",
          options: ["invent a new word", "choose the best one", "ignore the gap", "rewrite the sentence"],
          correctIdx: 1,
          after: "from the options given.",
          correction: "“choose the best one” — multiple-choice cloze always gives you a set of options to pick from.",
          hint: "Think about what “multiple-choice” means in any test format.",
        },
        {
          id: "mc-open-q2",
          instruction: CLICK_INSTRUCTION,
          before: "In open cloze, no options are given at all, so you must rely on your own",
          options: ["vocabulary", "calculator", "dictionary", "classmate"],
          correctIdx: 0,
          after: "to supply a suitable word.",
          correction: "“vocabulary” — without a list of options, open cloze depends entirely on the words you already know.",
          hint: "Think about what resource you have to draw on when there’s no list of choices.",
        },
        {
          id: "mc-open-q3",
          instruction: CLICK_INSTRUCTION,
          before: "A key advantage of multiple-choice cloze is that even if you are unsure, the correct word is",
          options: ["hidden elsewhere", "already on the page", "spelled wrong on purpose", "longer than the others"],
          correctIdx: 1,
          after: "somewhere among the options.",
          correction: "“already on the page” — in multiple-choice cloze, you never have to invent the word from nothing, only recognise it among the choices.",
          hint: "Think about what makes multiple-choice questions generally less demanding than open ones.",
        },
      ],
      mistakes: [
        "Wasting time trying to think of a “better” word in multiple-choice cloze instead of comparing the options actually given.",
        "In open cloze, writing a word that fits the meaning but is the wrong part of speech or wrong verb form for the sentence.",
      ],
      examTip: "In multiple-choice cloze, use elimination — cross out any option that fails on grammar first, then check meaning on what’s left.",
      searchTerms: ["multiple-choice cloze", "open cloze", "word bank", "elimination", "distractor"],
    },
    {
      id: "grammar-and-comprehension",
      title: "Why Cloze Tests Grammar AND Comprehension",
      tier: "Standard",
      objective: "Understand that a correct cloze answer must be grammatically correct and make sense in context — both at once.",
      whyMatters: "most wrong answers on cloze questions satisfy only one of these two conditions — knowing to check both is the single biggest accuracy boost.",
      conceptTitle: "Two conditions, both required",
      conceptBullets: [
        'A correct cloze answer must pass <b style="color:#C9A24B">two tests</b>: it must be grammatically correct, and it must make sense in context.',
        "Grammar checks whether the word’s form fits the sentence — its tense, its part of speech, its agreement with other words.",
        "Meaning checks whether the word’s sense actually fits the situation being described.",
        "An answer that passes only one test — grammatically fine but nonsensical, or sensible but the wrong word form — is still wrong.",
      ],
      conceptNote: "<b>Two-step check:</b> first ask “does this word fit the grammar?”, then ask “does this word fit the meaning?”. Only move on once both answers are yes.",
      glossary: [
        { term: "grammar fit", def: "whether a word’s form matches the sentence structure" },
        { term: "meaning fit", def: "whether a word’s sense matches the context" },
        { term: "agreement", def: "when connected words match in number, tense or person" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: GrammarAndComprehensionDemo,
      worked: {
        question: "Which word fits: “The scientists carefully ___ the results before publishing their report”? Options: (recorded / recording / records / record)",
        fastMethod: "Check the tense first — the rest of the sentence uses past tense (“before publishing”), which narrows the options immediately.",
        steps: [
          "Read the whole sentence to find its tense — “before publishing their report” suggests a completed past action.",
          "Eliminate “recording” (wrong form after a subject) and “records”/“record” (present tense, wrong agreement).",
          "“Recorded” is the past-tense form that grammatically fits.",
          "Check the meaning too — scientists recording results before publishing makes complete sense.",
        ],
        answer: "The answer is <b>recorded</b> — it satisfies both the grammar (past tense) and the meaning (a sensible research process).",
      },
      selfCheck: { prompt: "True or false: a cloze answer that is grammatically correct is always the right answer.", answer: "<b>False</b> — several words can be grammatically correct in a gap, but only the one that also makes sense in context is the right answer." },
      kind: "cloze-fill",
      questions: [
        {
          id: "grammar-comp-q1",
          instruction: CLICK_INSTRUCTION,
          before: "A good cloze answer must be grammatically correct and also make sense in context — for example,",
          options: ["Many", "Much", "A", "An"],
          correctIdx: 0,
          after: "animals migrate every winter to find warmer weather.",
          correction: "“Many” agrees grammatically with the plural noun “animals” and makes sense with the idea of migration — both grammar and meaning must line up.",
          hint: "Check whether the word matches the plural noun that follows it, not just whether it sounds like an option.",
        },
        {
          id: "grammar-comp-q2",
          instruction: CLICK_INSTRUCTION,
          before: "The gardener watered the plants",
          options: ["careful", "carefully", "care", "carefulness"],
          correctIdx: 1,
          after: "every evening so they would not wilt in the summer heat.",
          correction: "“carefully” is grammatically correct (an adverb describing how she watered) and fits the meaning of tending plants gently.",
          hint: "The gap describes how an action was done — check both the word’s grammar and whether the idea fits watering plants.",
        },
        {
          id: "grammar-comp-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Even though the answer must fit the grammar of the sentence, it also has to make logical sense — the thirsty hikers were relieved to find a",
          options: ["stream", "stone", "song", "shadow"],
          correctIdx: 0,
          after: "where they could refill their water bottles.",
          correction: "“stream” is grammatically fine as a noun after “a”, but it’s the meaning — a place to refill water — that makes it the only sensible choice.",
          hint: "All options could grammatically follow “a”, but only one makes sense with refilling water bottles.",
        },
      ],
      mistakes: [
        "Picking the first grammatically plausible word without checking whether it actually makes sense in the situation described.",
        "Picking a word that fits the meaning perfectly but is the wrong grammatical form (e.g. wrong tense or wrong part of speech) for the sentence.",
      ],
      examTip: "Always run both checks in order: grammar first to narrow the options, then meaning to pick the final answer.",
      searchTerms: ["grammar", "comprehension", "meaning", "context", "agreement", "cloze answer"],
    },
    {
      id: "passage-structure",
      title: "The Structure of a Cloze Passage",
      tier: "Standard",
      objective: "Understand how a full cloze passage is built from connected sentences with several gaps spread through it.",
      whyMatters: "recognising the passage as one connected whole — not a set of isolated gaps — is what lets you use clues from one part to solve another.",
      conceptTitle: "One passage, many gaps",
      conceptBullets: [
        'A typical cloze passage is a short piece of writing — often <b style="color:#C9A24B">one paragraph</b> — with several gaps spread through it, not just one.',
        "Gaps are usually numbered in the order they appear, so you can work through the passage in sequence.",
        "The sentences around any single gap are still there and readable — only the gap word itself is missing.",
        "Because the passage is connected, information relevant to one gap can appear in a sentence several lines away.",
      ],
      conceptNote: "<b>Treat it as one story, not several puzzles</b> — the passage’s overall topic and tone are clues for every gap within it.",
      glossary: [
        { term: "passage", def: "the connected block of writing containing the gaps" },
        { term: "numbered gap", def: "a gap labelled to match it with its answer space" },
        { term: "context clue", def: "information elsewhere in the passage that helps solve a gap" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: PassageStructureDemo,
      worked: {
        question: "A cloze passage has six numbered gaps across four sentences. What does this tell you about how to approach it?",
        fastMethod: "Read the whole passage first — with six gaps across only four sentences, clues for one gap are very likely sitting in a nearby sentence.",
        steps: [
          "Notice the passage is short but has multiple gaps, meaning the sentences are closely connected.",
          "Read straight through once without stopping at any gap, to understand the overall story.",
          "Go back and answer the gaps you’re confident about first.",
          "Use the words you’ve already filled in as extra context for the gaps you were unsure about.",
        ],
        answer: "Read the <b>whole passage first</b>, then answer confident gaps before returning to harder ones — the passage’s connections help solve them.",
      },
      selfCheck: { prompt: "True or false: each gap in a cloze passage should be treated as a completely separate question with no link to the others.", answer: "<b>False</b> — gaps sit within one connected passage, so information anywhere in it can help solve any individual gap." },
      kind: "cloze-fill",
      questions: [
        {
          id: "structure-q1",
          instruction: CLICK_INSTRUCTION,
          before: "A typical cloze passage is several sentences long and contains",
          options: ["only one gap", "several gaps", "no gaps", "a single paragraph title"],
          correctIdx: 1,
          after: "spread evenly through the text.",
          correction: "“several gaps” — a full cloze passage usually has multiple missing words, not just one, spread across its sentences.",
          hint: "Think about how many words are usually missing across a whole passage, not just in this demo.",
        },
        {
          id: "structure-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Because gaps are spread through the passage, an early gap can sometimes only be filled correctly by first reading",
          options: ["the title only", "later sentences", "the answer key", "a different passage"],
          correctIdx: 1,
          after: "further down the passage.",
          correction: "“later sentences” — clues for an earlier gap are sometimes found further down the passage, so a full read-through helps.",
          hint: "Think about where extra clues might be hiding if not right next to the gap itself.",
        },
        {
          id: "structure-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Each gap in a cloze passage usually replaces just one",
          options: ["sentence", "paragraph", "word", "full stop"],
          correctIdx: 2,
          after: "so the surrounding sentence stays mostly intact.",
          correction: "“word” — cloze passages remove single words at a time, leaving the rest of each sentence readable.",
          hint: "Think about the smallest unit typically removed to create a gap.",
        },
      ],
      mistakes: [
        "Answering gaps strictly in order and never revisiting earlier ones once later sentences reveal more context.",
        "Treating the passage as disconnected fragments instead of one continuous piece of writing with a single topic and tone.",
      ],
      examTip: "Skip a gap you’re unsure about on your first pass — answer the easy ones, then use that filled-in context to solve the harder ones.",
      searchTerms: ["passage structure", "gaps", "connected text", "context clue", "numbered gaps"],
    },
    {
      id: "cloze-marking",
      title: "How Cloze Answers Are Marked",
      tier: "Standard",
      objective: "Understand that different exam boards mark cloze answers differently — some require the exact word, others accept close synonyms.",
      whyMatters: "knowing whether synonyms are accepted changes how confident you can be writing an alternative word when you can’t recall the exact original.",
      conceptTitle: "Exact word vs. accepted synonym",
      conceptBullets: [
        'Some mark schemes require the <b style="color:#C9A24B">exact original word</b> the passage used — anything else, even a close synonym, is marked wrong.',
        "Other mark schemes accept any word that fits both the grammar and the meaning, even if it isn’t the exact original.",
        "Multiple-choice cloze avoids this issue entirely, since the exact word is always one of the printed options.",
        "In open cloze, checking your spelling carefully matters — a correct word spelled wrong can lose the mark under a strict scheme.",
      ],
      conceptNote: "<b>When unsure of the exact word</b>, write the most precise synonym you can think of — it earns the mark under a lenient scheme and loses nothing under a strict one.",
      glossary: [
        { term: "exact-word marking", def: "only the original word earns credit" },
        { term: "synonym marking", def: "any word with a matching meaning earns credit" },
        { term: "mark scheme", def: "the rules an examiner uses to award marks" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: ClozeMarkingDemo,
      worked: {
        question: "The original passage word was “glanced”. Under a synonym-marking scheme, would “peeked” likely earn the mark?",
        fastMethod: "Compare the core meaning of the two words, not just whether they could both fit the sentence.",
        steps: [
          "Check the meaning of “glanced” — a quick, brief look.",
          "Compare it to “peeked” — also a quick, often secretive look.",
          "The meanings are close enough that a synonym-marking scheme would likely accept it.",
          "Under an exact-word scheme, only “glanced” itself would be accepted.",
        ],
        answer: "Under a <b>synonym-marking scheme</b>, “peeked” would likely be accepted; under an <b>exact-word scheme</b>, it would not.",
      },
      selfCheck: { prompt: "True or false: multiple-choice cloze can be affected by exact-word vs. synonym marking rules.", answer: "<b>False</b> — since the exact original word is always printed as one of the options, this issue only affects open cloze." },
      kind: "cloze-fill",
      questions: [
        {
          id: "marking-q1",
          instruction: CLICK_INSTRUCTION,
          before: "On some exam boards, only the exact original word earns the mark, while others accept a close",
          options: ["synonym", "antonym", "homophone", "rhyme"],
          correctIdx: 0,
          after: "with the same meaning.",
          correction: "“synonym” — some boards accept a word with the same meaning as the original, while others require the exact word.",
          hint: "Think about the type of word that means roughly the same thing as another.",
        },
        {
          id: "marking-q2",
          instruction: CLICK_INSTRUCTION,
          before: "The passage originally read “the crowd cheered ___ as the runner crossed the finish line”, and the exact word required was",
          options: ["loudly", "quietly", "calmly", "softly"],
          correctIdx: 0,
          after: "— a synonym like “noisily” might still earn credit under a lenient mark scheme.",
          correction: "“loudly” is the original word — under a strict mark scheme only this exact word (or possibly close synonyms like “noisily”) would earn the mark, depending on the exam board’s rules.",
          hint: "Think about how a cheering crowd at the finish line would most naturally be described.",
        },
        {
          id: "marking-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Because marking rules vary, it’s always worth checking whether the paper wants the exact word or accepts any word that fits the",
          options: ["meaning", "font", "margin", "page number"],
          correctIdx: 0,
          after: "of the sentence.",
          correction: "“meaning” — the key distinction in marking is whether any sensible word is accepted or only the exact original.",
          hint: "Think about what a lenient mark scheme would judge an alternative word against.",
        },
      ],
      mistakes: [
        "Assuming every board accepts synonyms and losing marks under a strict, exact-word scheme.",
        "Giving up on a gap entirely because you can’t recall the exact word, instead of writing the closest sensible synonym you can think of.",
      ],
      examTip: "If you can’t recall the exact word, write the most precise synonym you can — it costs nothing to try and may well earn the mark.",
      searchTerms: ["marking", "mark scheme", "synonym", "exact word", "spelling", "cloze marking"],
    },
    {
      id: "cloze-misconceptions",
      title: "Common Misconceptions About Cloze",
      tier: "Standard",
      objective: "Identify and avoid common misconceptions about cloze tests, especially the idea that any grammatically correct word will do.",
      whyMatters: "the single most common cloze mistake is picking a word that grammatically fits but doesn’t actually make sense — this subtopic exists to stop that habit early.",
      conceptTitle: "Grammar fit is not enough on its own",
      conceptBullets: [
        'The biggest misconception: <b style="color:#C9A24B">"any word that fits grammatically must be right."</b> It isn’t — the word also has to make sense.',
        "A second misconception: that the fanciest or longest-sounding word is automatically the best choice — simple, precise words are often correct.",
        "A third misconception: that a gap can always be answered from its own sentence alone, without reading anything else.",
        "Careful readers check every option against both grammar and meaning before deciding, rather than stopping at the first plausible one.",
      ],
      conceptNote: "<b>Test yourself:</b> for any answer you're considering, ask “could I picture this actually happening?” — if not, it probably fails the meaning test.",
      glossary: [
        { term: "misconception", def: "a common but incorrect belief about how something works" },
        { term: "plausible option", def: "an answer that looks reasonable but may not truly fit" },
        { term: "meaning test", def: "checking whether a word’s sense truly matches the context" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: ClozeMisconceptionsDemo,
      worked: {
        question: "A student picks “enormous” for the gap in “She keeps a small, ___ diary by her bed” because it’s grammatically an adjective. Is this correct?",
        fastMethod: "Check the meaning — “small” and “enormous” directly contradict each other in the same phrase.",
        steps: [
          "Confirm “enormous” is grammatically an adjective, so it does fit the sentence structure.",
          "Check the meaning against the rest of the sentence — “small” already describes the diary.",
          "“Small” and “enormous” cannot both describe the same diary at once — it’s a contradiction.",
          "The grammar fits, but the meaning fails, so “enormous” is wrong despite being the right part of speech.",
        ],
        answer: "The word is <b>wrong</b> — it’s the correct part of speech, but its meaning contradicts “small” earlier in the sentence.",
      },
      selfCheck: { prompt: "True or false: if a word is grammatically correct in a gap, it must be the right answer.", answer: "<b>False</b> — several grammatically correct words can fit a gap, but only one will also make sense in context." },
      kind: "cloze-fill",
      questions: [
        {
          id: "misconceptions-q1",
          instruction: CLICK_INSTRUCTION,
          before: "A common misconception is that any grammatically correct word will do — but the chosen word must also match the",
          options: ["meaning", "font size", "spelling rules only", "word count"],
          correctIdx: 0,
          after: "of the whole sentence.",
          correction: "“meaning” — grammar alone isn’t enough; the word must also make sense with the sentence’s meaning.",
          hint: "Think about what else besides grammar has to be checked before picking an answer.",
        },
        {
          id: "misconceptions-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Another misconception is that skimming just the gap’s sentence is always enough — but sometimes you need clues from",
          options: ["elsewhere in the passage", "the cover page", "the exam timer", "a dictionary"],
          correctIdx: 0,
          after: "to choose correctly.",
          correction: "“elsewhere in the passage” — some gaps can only be answered confidently using information from other sentences.",
          hint: "Think about where extra clues for a tricky gap might be hiding, beyond just its own sentence.",
        },
        {
          id: "misconceptions-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Students sometimes assume the longest word in the options is the most impressive choice, but the best answer is simply the one that",
          options: ["fits best", "is spelled hardest", "sounds fanciest", "is used least"],
          correctIdx: 0,
          after: "grammatically and in meaning.",
          correction: "“fits best” — a fancy or long word is not automatically correct; the simplest word that truly fits is often right.",
          hint: "Think about what actually makes an answer correct, rather than how impressive it looks.",
        },
      ],
      mistakes: [
        "Stopping at the first grammatically plausible word instead of checking every option against the meaning too.",
        "Assuming a longer or more sophisticated-sounding word is more likely to be correct than a short, simple one.",
      ],
      examTip: "Before finalising any answer, silently read the full sentence back with your chosen word in place — contradictions and nonsense usually become obvious.",
      searchTerms: ["misconceptions", "common mistakes", "grammar fit", "meaning fit", "plausible answer"],
    },
    {
      id: "read-passage-first",
      title: "Why Reading the Whole Passage First Matters",
      tier: "Extension",
      objective: "Understand why reading a cloze passage in full before attempting any gap improves accuracy.",
      whyMatters: "diving straight into the first gap without context is one of the most common reasons capable students lose marks on cloze.",
      conceptTitle: "Context before commitment",
      conceptBullets: [
        'Reading the whole passage first builds a <b style="color:#C9A24B">mental picture</b> of the topic, setting and tone before you commit to any answer.',
        "Some gaps depend on information revealed only later in the passage — attempting them too early means guessing blind.",
        "A first read also reveals the passage’s overall tone (serious, humorous, tense), which helps rule out wrongly-toned word choices.",
        "It costs very little time — a short passage takes moments to read — but can prevent several wrong answers.",
      ],
      conceptNote: "<b>Two-pass method:</b> read the whole passage once for understanding, then go back and fill in the gaps on a second, closer read.",
      glossary: [
        { term: "first-pass read", def: "an initial read-through for overall understanding, before answering" },
        { term: "tone", def: "the overall mood or attitude of a passage" },
        { term: "blind guess", def: "an answer chosen without enough context to be confident" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: ReadPassageFirstDemo,
      worked: {
        question: "The first gap in a passage is “The weather had been ___ for days.” Later, the passage mentions flooded fields and ruined crops. What does this tell you?",
        fastMethod: "Use the later flood and crop details to work out that the early weather gap must describe heavy, persistent rain.",
        steps: [
          "Notice the first gap alone gives very little to go on — many weather words could fit grammatically.",
          "Read on and spot the later details: flooded fields, ruined crops.",
          "These details only make sense if the earlier weather was wet and stormy for an extended period.",
          "Return to the first gap with this context and choose a word like “wet” or “stormy” rather than guessing blind.",
        ],
        answer: "The passage as a whole reveals the answer is something like <b>wet</b> or <b>stormy</b> — information from later sentences was needed to be sure.",
      },
      selfCheck: { prompt: "True or false: it is always faster and just as accurate to answer each gap the moment you reach it, without reading ahead.", answer: "<b>False</b> — some gaps genuinely cannot be answered confidently without information revealed later in the passage." },
      kind: "cloze-fill",
      questions: [
        {
          id: "read-first-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Skipping straight to the gaps without reading the whole passage first can cause you to miss important",
          options: ["context", "punctuation", "word count", "font"],
          correctIdx: 0,
          after: "that later gaps depend on.",
          correction: "“context” — reading the whole passage first builds the context you need for gaps that rely on information given elsewhere.",
          hint: "Think about the background information a full read-through provides.",
        },
        {
          id: "read-first-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Reading the whole passage first helps you understand its overall",
          options: ["tone and topic", "page number", "font style", "exam duration"],
          correctIdx: 0,
          after: "before you commit to any single answer.",
          correction: "“tone and topic” — knowing the overall subject and mood of a passage helps every individual gap make more sense.",
          hint: "Think about what a quick first read tells you about the passage as a whole, before focusing on details.",
        },
        {
          id: "read-first-q3",
          instruction: CLICK_INSTRUCTION,
          before: "It is often better to leave a difficult gap blank on a first pass and return to it after finishing the",
          options: ["rest of the passage", "exam hall", "pencil case", "cover sheet"],
          correctIdx: 0,
          after: "since later sentences may clarify it.",
          correction: "“rest of the passage” — coming back to a hard gap after reading everything else often makes the answer obvious.",
          hint: "Think about what you should finish reading before returning to a gap you’re unsure about.",
        },
      ],
      mistakes: [
        "Answering the first gap immediately, before knowing anything about the passage’s topic, tone or later events.",
        "Refusing to leave a hard gap blank and move on, wasting time that could be spent gathering context from the rest of the passage.",
      ],
      examTip: "Budget your first read as pure reading — no writing, no filling gaps — then do a focused second pass to answer everything.",
      searchTerms: ["read first", "first pass", "context", "tone", "strategy", "whole passage"],
    },
    {
      id: "combined-skills",
      title: "The Combined Skills Cloze Tests",
      tier: "Extension",
      objective: "Recognise that cloze questions require vocabulary, grammar and comprehension working together, not any one skill alone.",
      whyMatters: "understanding cloze as a combined skill — rather than a vocabulary quiz or a grammar drill — explains why practising all three areas improves your score.",
      conceptTitle: "Three skills, one question",
      conceptBullets: [
        'Cloze draws on <b style="color:#C9A24B">vocabulary</b> (knowing enough words to recognise or recall the right one), <b>grammar</b> (using the correct form) and <b>comprehension</b> (understanding the passage) — all at once.',
        "Weakness in any single one of these three areas can cause a wrong answer, even if the other two are strong.",
        "Strong vocabulary without comprehension can produce a word that sounds sophisticated but doesn’t fit the situation.",
        "Strong comprehension without grammar can produce the right idea in the wrong word form.",
      ],
      conceptNote: "<b>Balanced practice</b> — reading widely builds vocabulary and comprehension together, while grammar exercises sharpen the third skill needed to finish the job.",
      glossary: [
        { term: "vocabulary", def: "the range of words a student knows and can recall" },
        { term: "grammar", def: "using the correct word form for the sentence" },
        { term: "comprehension", def: "understanding what a passage is actually saying" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: CombinedSkillsDemo,
      worked: {
        question: "A student writes “furious” for a gap describing a character who has just won a competition. What has gone wrong?",
        fastMethod: "“Furious” is grammatically fine and a real word (good vocabulary and grammar) but the wrong emotion for winning (weak comprehension).",
        steps: [
          "Check the grammar — “furious” is a correctly formed adjective, so grammar isn’t the issue.",
          "Check the vocabulary — it’s a real, well-spelled word, so vocabulary isn’t the issue either.",
          "Check the comprehension — winning a competition would typically make someone “delighted” or “thrilled”, not furious.",
          "The error lies specifically in comprehension: misreading the situation the passage describes.",
        ],
        answer: "The mistake is a <b>comprehension error</b> — the word is grammatically fine, but the wrong emotion for someone who has just won.",
      },
      selfCheck: { prompt: "True or false: excellent grammar alone is enough to guarantee correct cloze answers.", answer: "<b>False</b> — vocabulary and comprehension are just as necessary; strong grammar alone cannot guarantee the meaning is right." },
      kind: "cloze-fill",
      questions: [
        {
          id: "combined-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Answering a cloze gap correctly draws on vocabulary, grammar and",
          options: ["comprehension", "handwriting speed", "memorising times tables", "spelling of other words"],
          correctIdx: 0,
          after: "all working together at once.",
          correction: "“comprehension” — cloze questions combine knowing words (vocabulary), using them correctly (grammar) and understanding the passage (comprehension).",
          hint: "Think about the third skill, alongside vocabulary and grammar, needed to understand a passage’s meaning.",
        },
        {
          id: "combined-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Without strong vocabulary, you might not recognise the best word even if your grammar and",
          options: ["comprehension are strong", "handwriting is neat", "pencil is sharp", "desk is tidy"],
          correctIdx: 0,
          after: "because you simply don’t know the word.",
          correction: "“comprehension are strong” — all three skills are needed together; strength in two areas can’t fully make up for a gap in vocabulary.",
          hint: "Think about which other two skills were mentioned as working alongside vocabulary.",
        },
        {
          id: "combined-q3",
          instruction: CLICK_INSTRUCTION,
          before: "A student with excellent grammar but weak comprehension might choose a word that fits the sentence structure but not the",
          options: ["overall meaning", "paragraph length", "font", "punctuation style"],
          correctIdx: 0,
          after: "of the passage.",
          correction: "“overall meaning” — grammar alone can produce a sentence that reads correctly but doesn’t actually make sense in context.",
          hint: "Think about what strong comprehension, specifically, would catch that grammar alone would miss.",
        },
      ],
      mistakes: [
        "Focusing revision entirely on grammar rules while neglecting wide reading, which builds both vocabulary and comprehension.",
        "Assuming a strong vocabulary alone is enough, without checking that a word’s grammatical form actually fits the gap.",
      ],
      examTip: "Balance your practice — read varied fiction and non-fiction for vocabulary and comprehension, and drill grammar separately for word forms.",
      searchTerms: ["combined skills", "vocabulary", "grammar", "comprehension", "reading widely"],
    },
    {
      id: "cloze-expectations",
      title: "Setting Expectations: Cloze Feels Harder Than It Is",
      tier: "Extension",
      objective: "Combine grammar-fit and meaning-fit checks confidently on a trickier mixed example, recognising that cloze rarely requires more than careful reading.",
      whyMatters: "cloze questions often feel disproportionately intimidating under time pressure — this final subtopic pulls every earlier idea together so you can approach them calmly.",
      conceptTitle: "It's simpler than it feels",
      conceptBullets: [
        'Most cloze gaps have exactly <b style="color:#C9A24B">one</b> answer that is both grammatically correct and meaningful in context — there is usually no real ambiguity once you check both.',
        "The format can feel harder than it is because several options often look superficially plausible at first glance.",
        "Slowing down to apply the grammar-fit and meaning-fit checks together, rather than guessing quickly, resolves almost every gap.",
        "Cloze does not require specialist knowledge — it draws on everyday vocabulary and careful reading you already have.",
      ],
      conceptNote: "<b>Final reminder:</b> read the whole passage first, check every option against grammar, then check the survivors against meaning — this combination rarely fails.",
      glossary: [
        { term: "ambiguity", def: "when more than one answer could seem to fit" },
        { term: "time pressure", def: "the stress of limited time that can cause rushed guessing" },
        { term: "systematic check", def: "working through grammar and meaning in order, rather than guessing" },
      ],
      diagramLabel: "Interactive · Fill the Gap",
      Diagram: ClozeExpectationsDemo,
      worked: {
        question: "Which word fits: “Despite arriving early, Tom found the queue had already ___ around the block”? Options: (stretched / stretching / stretch / stretches)",
        fastMethod: "The sentence is in the past tense (“had already ___”), which immediately narrows the grammar to one form.",
        steps: [
          "Notice “had already ___” requires a past participle to follow the helping verb “had”.",
          "Eliminate “stretching” (wrong form), “stretch” (base form) and “stretches” (present tense) on grammar alone.",
          "“Stretched” is the only option that is grammatically correct after “had already”.",
          "Check the meaning too — a queue stretching around the block, despite Tom arriving early, makes complete sense.",
        ],
        answer: "The answer is <b>stretched</b> — the only option that passes both the grammar check and the meaning check.",
      },
      selfCheck: { prompt: "True or false: cloze questions usually require knowledge beyond what a careful reader already has.", answer: "<b>False</b> — cloze mainly rewards careful, systematic reading rather than specialist or obscure knowledge." },
      kind: "cloze-fill",
      questions: [
        {
          id: "expectations-q1",
          instruction: CLICK_INSTRUCTION,
          before: "Cloze questions often look intimidating at first glance, but they usually only require careful reading rather than",
          options: ["specialist knowledge", "basic vocabulary", "common sense", "attention"],
          correctIdx: 0,
          after: "you haven’t already learned.",
          correction: "“specialist knowledge” — cloze tests draw on everyday vocabulary and reasoning you already have, not obscure facts.",
          hint: "Think about what cloze questions do NOT usually require, compared to what careful reading provides.",
        },
        {
          id: "expectations-q2",
          instruction: CLICK_INSTRUCTION,
          before: "Despite feeling harder under time pressure, most cloze gaps have only one answer that is both grammatically correct and",
          options: ["meaningful in context", "the longest word", "the first option listed", "alphabetically first"],
          correctIdx: 0,
          after: "so there is usually no real ambiguity.",
          correction: "“meaningful in context” — despite feeling tricky, cloze gaps are normally designed to have exactly one answer that satisfies both grammar and meaning.",
          hint: "Think back to the two conditions every good cloze answer must satisfy together.",
        },
        {
          id: "expectations-q3",
          instruction: CLICK_INSTRUCTION,
          before: "Although the wind had been rising all afternoon, the sailors were surprised by how quickly the storm",
          options: ["arrived", "arrival", "arriving", "arrives"],
          correctIdx: 0,
          after: "once the clouds turned black.",
          correction: "“arrived” is grammatically correct (matching the past tense of the passage) and fits the meaning of a storm catching the sailors off guard — exactly the combination of grammar-fit and meaning-fit that makes cloze feel trickier than it is.",
          hint: "Check both the tense of the surrounding sentence and which option actually describes a storm arriving, not a different form of the same idea.",
        },
      ],
      mistakes: [
        "Panicking under time pressure and guessing the first option that looks vaguely right, instead of applying the grammar-then-meaning check.",
        "Believing cloze requires rare or advanced vocabulary, and second-guessing a correct, simple answer in favour of a fancier-sounding wrong one.",
      ],
      examTip: "If a cloze passage feels overwhelming, slow down rather than speed up — the grammar-then-meaning method resolves almost every gap methodically.",
      searchTerms: ["expectations", "exam confidence", "grammar fit", "meaning fit", "time pressure", "strategy review"],
    },
  ],
};
