import type { TopicContent } from "../types";
import {
  WhatIsWordRelationshipsDemo,
  SynonymsDemo,
  AntonymsDemo,
  OddOneOutDemo,
  WordAnalogiesDemo,
  AlphabetAnalogiesDemo,
  TrapWordsDemo,
  WorkingSystematicallyDemo,
  CategoryPrecisionDemo,
  TimingStrategyDemo,
} from "../notes-diagrams/word-relationships-demos";

export const wordRelationshipsEssentialsTopic: TopicContent = {
  slug: "word-relationships-essentials",
  subject: "VR",
  subjectSlug: "verbal-reasoning",
  title: "Word Relationships Essentials",
  glyphs: ["A", "→", "≈", "≠", "B", "?"],
  description:
    "Every GL-style Verbal Reasoning paper includes a run of questions built on how words connect to each other — words that mean nearly the same thing, words that mean the opposite, a word that doesn't belong in a group, and pairs of words linked by a hidden rule. This module trains all four core formats from the ground up, then builds the working method that carries a student through the trickier trap-word and timing questions built on top of them.",
  subtopics: [
    {
      id: "what-is-word-relationships",
      title: "What Is a Word-Relationships Question?",
      tier: "Foundation",
      objective: "Recognise the four core Verbal Reasoning formats built on how words relate to each other.",
      whyMatters: "these four formats appear in almost every GL Verbal Reasoning paper — spotting which one you're facing instantly tells you what kind of thinking the question needs.",
      conceptTitle: "Four formats, one shared skill",
      conceptBullets: [
        '<b style="color:#C9A24B">Word relationships</b> questions test how well you understand what words mean and how they connect to other words — not spelling, not grammar.',
        "The four core formats are: closest in meaning (synonyms), most opposite in meaning (antonyms), odd one out, and word analogies.",
        "Every format gives you a small group of words or a word pair, and asks you to spot a relationship — similarity, opposition, category, or a hidden rule.",
        "Recognising the format in the first few seconds tells you exactly what kind of thinking to switch on.",
      ],
      conceptNote: "<b>Golden rule:</b> read the instruction line first, every time — 'closest in meaning' and 'most opposite in meaning' are easy to mix up under time pressure, and mixing them up gives you the exact wrong answer.",
      glossary: [
        { term: "synonym", def: "a word that means nearly the same as another word" },
        { term: "antonym", def: "a word that means the opposite of another word" },
        { term: "odd one out", def: "the item in a group that breaks the shared pattern" },
        { term: "analogy", def: "a relationship between one pair of words applied to a second pair" },
      ],
      diagramLabel: "Interactive · Word Relationships",
      Diagram: WhatIsWordRelationshipsDemo,
      worked: {
        question: "Instruction: 'Click the word closest in meaning to swift.' Options: slow, quick, heavy, quiet, careful.",
        fastMethod: "Recognise the instruction as a synonym question, then scan for the word matching 'swift' in meaning.",
        steps: [
          "Read the instruction: 'closest in meaning' signals a synonym question, not an antonym or odd-one-out question.",
          "Recall what 'swift' means: fast-moving.",
          "Scan the options for a word meaning the same thing.",
          "'Quick' shares the meaning of 'swift' — the other options don't.",
        ],
        answer: 'The answer is <b>quick</b>.',
      },
      selfCheck: { prompt: "True or false: 'closest in meaning' and 'most opposite in meaning' test exactly the same skill in exactly the same way.", answer: "<b>False</b> — they use the same word-knowledge skill, but ask for opposite answers; misreading the instruction line gives the wrong answer even with perfect vocabulary." },
      kind: "click-evidence",
      questions: [
        {
          id: "what-is-wr-q1",
          instruction: "Click the word closest in meaning to 'brave'.",
          passage: ["nervous", "courageous", "gentle", "tired", "quiet"],
          correctIdx: 1,
          correction: '"courageous" shares the meaning of "brave" — both describe facing danger or difficulty without fear.',
          hint: "look for the word describing facing fear, not the opposite.",
        },
        {
          id: "what-is-wr-q2",
          instruction: "Click the word most opposite in meaning to 'ancient'.",
          passage: ["old", "modern", "historic", "faded", "worn"],
          correctIdx: 1,
          correction: '"modern" is the opposite of "ancient" — one means very old, the other means very recent.',
          hint: "three of these options actually mean the same as 'ancient' — find the true opposite.",
        },
        {
          id: "what-is-wr-q3",
          instruction: "Click the word that does not belong with the others.",
          passage: ["whisper", "shout", "mumble", "sprint", "murmur"],
          correctIdx: 3,
          correction: '"sprint" is the odd one out — whisper, shout, mumble and murmur are all ways of speaking, but sprint is a way of moving.',
          hint: "find the shared category linking four of the five words first.",
        },
      ],
      mistakes: [
        "Answering a 'most opposite' question with a synonym instead, because the two instruction lines look similar at a glance.",
        "Picking the first word that seems roughly related, instead of checking it matches the exact relationship asked for.",
      ],
      examTip: "Underline or say the key instruction word to yourself — 'closest' or 'opposite' or 'odd' — before you even look at the word group.",
      searchTerms: ["word relationships", "synonyms", "antonyms", "odd one out", "analogies", "verbal reasoning"],
    },
    {
      id: "synonyms-closest-in-meaning",
      title: "Closest in Meaning (Synonyms)",
      tier: "Foundation",
      objective: "Confidently identify the word from a group that means nearly the same as a given word.",
      whyMatters: "synonym questions are some of the fastest, most reliable marks on a GL Verbal Reasoning paper if your vocabulary is strong and your method is quick.",
      conceptTitle: "Finding the closest match, not just 'a bit similar'",
      conceptBullets: [
        '<b style="color:#C9A24B">Closest in meaning</b> questions ask for the word that means nearly the same as the word given — not just a word from a related topic.',
        "A good technique is to build your own quick definition of the given word in your head before looking at the options.",
        "Watch out for options that are related to the topic but don't actually share the meaning — a decoy word about the same subject, not the same idea.",
        "If two options both seem close, pick the one that's the strongest, most precise match — GL questions are written so only one option is truly correct.",
      ],
      conceptNote: "<b>Strategy:</b> silently replace the given word with each option in a short sentence — the one that keeps the sentence meaning almost identical is the synonym.",
      glossary: [
        { term: "synonym", def: "a word that means nearly the same as another word" },
        { term: "precise match", def: "the option that shares the meaning most closely, not just loosely" },
        { term: "decoy", def: "an option connected to the topic but not actually a synonym" },
        { term: "definition", def: "a short explanation of what a word means" },
      ],
      diagramLabel: "Interactive · Word Relationships",
      Diagram: SynonymsDemo,
      worked: {
        question: "Instruction: 'Click the word closest in meaning to reluctant.' Options: eager, unwilling, confident, curious, careless.",
        fastMethod: "Build a quick definition of 'reluctant' — not wanting to do something — then scan for the closest match.",
        steps: [
          "Define 'reluctant' in your own words: unwilling, hesitant, not wanting to do something.",
          "Scan the options for a word matching that definition.",
          "'Unwilling' matches directly.",
          "Check the others don't fit as well: 'eager' is the opposite, and the rest are unrelated.",
        ],
        answer: 'The answer is <b>unwilling</b>.',
      },
      selfCheck: { prompt: "If two options both seem loosely related to the given word, what should you do?", answer: "<b>Pick the one that is the strongest, most precise match</b> — only one option genuinely shares the meaning; the other is a decoy." },
      kind: "click-evidence",
      questions: [
        {
          id: "syn-q1",
          instruction: "Click the word closest in meaning to 'exhausted'.",
          passage: ["excited", "worried", "drained", "confused", "hopeful"],
          correctIdx: 2,
          correction: '"drained" matches "exhausted" — both describe being completely out of energy.',
          hint: "find the word describing extreme tiredness.",
        },
        {
          id: "syn-q2",
          instruction: "Click the word closest in meaning to 'furious'.",
          passage: ["enraged", "nervous", "pleased", "sleepy", "amused"],
          correctIdx: 0,
          correction: '"enraged" matches "furious" — both describe intense anger.',
          hint: "find the word describing extreme anger, not another emotion entirely.",
        },
        {
          id: "syn-q3",
          instruction: "Click the word closest in meaning to 'obvious'.",
          passage: ["hidden", "evident", "unlikely", "distant", "fragile"],
          correctIdx: 1,
          correction: '"evident" matches "obvious" — both describe something clearly easy to see or understand.',
          hint: "the opposite of this word means 'hidden' — look for the one meaning the reverse.",
        },
      ],
      mistakes: [
        "Choosing a word that's simply longer or sounds more impressive, rather than checking it actually shares the meaning.",
        "Picking a topic-related decoy word instead of a genuine synonym.",
      ],
      examTip: "If you're unsure of the given word's meaning, look at how confidently you can rule out the wrong options first — sometimes elimination gets you there faster than definition.",
      searchTerms: ["synonyms", "closest in meaning", "vocabulary", "word choice", "verbal reasoning"],
    },
    {
      id: "antonyms-most-opposite",
      title: "Most Opposite in Meaning (Antonyms)",
      tier: "Foundation",
      objective: "Confidently identify the word from a group that means the opposite of a given word.",
      whyMatters: "antonym questions are deliberately paired with synonym-like decoys — knowing the difference between 'related' and 'opposite' is the whole game here.",
      conceptTitle: "Finding the true opposite, not a near-synonym",
      conceptBullets: [
        '<b style="color:#C9A24B">Most opposite in meaning</b> questions ask for the word furthest away in meaning from the word given.',
        "GL papers often include one or more near-synonyms of the given word among the options, specifically to catch a rushed reader.",
        "A safe method: mentally rule out every option that means roughly the same as the given word first — the real answer is what's left.",
        "For less common words, think of the word's opposite in your own words before scanning the options, so a decoy can't mislead you.",
      ],
      conceptNote: "<b>Trap to know:</b> the strongest-looking decoy in an antonym question is usually a synonym of the given word, not an unrelated word — read carefully.",
      glossary: [
        { term: "antonym", def: "a word that means the opposite of another word" },
        { term: "near-synonym decoy", def: "an option meaning roughly the same as the given word, placed to mislead" },
        { term: "elimination", def: "ruling out wrong options to leave the correct one" },
        { term: "opposite pair", def: "two words with contrasting meanings" },
      ],
      diagramLabel: "Interactive · Word Relationships",
      Diagram: AntonymsDemo,
      worked: {
        question: "Instruction: 'Click the word most opposite in meaning to generous.' Options: kind, wealthy, selfish, cheerful, patient.",
        fastMethod: "Rule out any option meaning roughly the same as 'generous' first, then check what's genuinely opposite.",
        steps: [
          "Define 'generous': freely giving to others.",
          "'Kind' is related but not truly opposite — rule it out as a near-synonym decoy.",
          "'Selfish' means refusing to give or share — the true opposite of generous.",
          "Check the rest don't fit better: wealthy, cheerful and patient are all unrelated to generosity.",
        ],
        answer: 'The answer is <b>selfish</b>.',
      },
      selfCheck: { prompt: "In an antonym question, what type of wrong option is most likely to trick a rushed reader?", answer: "<b>A near-synonym</b> of the given word — a word meaning roughly the same thing, not something unrelated." },
      kind: "click-evidence",
      questions: [
        {
          id: "ant-q1",
          instruction: "Click the word most opposite in meaning to 'cautious'.",
          passage: ["careful", "reckless", "quiet", "thoughtful", "slow"],
          correctIdx: 1,
          correction: '"reckless" is the true opposite of "cautious" — one means careful, the other means acting without thinking of danger.',
          hint: "several options here are near-synonyms of 'cautious' — find the one meaning the reverse.",
        },
        {
          id: "ant-q2",
          instruction: "Click the word most opposite in meaning to 'genuine'.",
          passage: ["honest", "sincere", "fake", "loyal", "modest"],
          correctIdx: 2,
          correction: '"fake" is the true opposite of "genuine" — genuine means real and authentic, fake means the reverse.',
          hint: "rule out the words meaning roughly the same as 'genuine' first.",
        },
        {
          id: "ant-q3",
          instruction: "Click the word most opposite in meaning to 'abundant'.",
          passage: ["plentiful", "scarce", "generous", "large", "common"],
          correctIdx: 1,
          correction: '"scarce" is the true opposite of "abundant" — abundant means plentiful, scarce means very little available.',
          hint: "one option here means almost the same as 'abundant' — don't be caught by it.",
        },
      ],
      mistakes: [
        "Picking a near-synonym of the given word by mistake, especially under time pressure.",
        "Confusing 'most opposite' with 'closest in meaning' after misreading the instruction line.",
      ],
      examTip: "Say the given word's opposite out loud (in your head) before you even glance at the options — it stops a strong-looking decoy from pulling you off course.",
      searchTerms: ["antonyms", "most opposite", "opposite meaning", "vocabulary", "verbal reasoning"],
    },
    {
      id: "odd-one-out",
      title: "Odd One Out",
      tier: "Standard",
      objective: "Identify the shared category linking most items in a group, then spot the one item that breaks it.",
      whyMatters: "odd-one-out questions reward working out the rule first — guessing item by item wastes time and often lands on the wrong answer.",
      conceptTitle: "Find the rule before you find the answer",
      conceptBullets: [
        '<b style="color:#C9A24B">Odd one out</b> questions give a small group of words, most of which share a category or property — one word breaks the pattern.',
        "Work out what links the majority of the words first — a category (types of fish), a property (all verbs), or a feature (all contain double letters).",
        "Once the shared rule is clear, the item that doesn't fit becomes obvious rather than a guess.",
        "On the real GL paper this format sometimes asks for two words that don't belong out of five — the same rule-finding method still applies, just with two exceptions instead of one.",
      ],
      conceptNote: "<b>Common categories to check for:</b> types/categories of thing, all being the same part of speech (all nouns, all verbs), or a spelling pattern shared by most of the words.",
      glossary: [
        { term: "shared category", def: "the property or group that most of the words have in common" },
        { term: "odd one out", def: "the item that breaks the shared pattern" },
        { term: "part of speech", def: "the grammatical type of a word, e.g. noun, verb, adjective" },
        { term: "pattern", def: "a rule connecting most items in a group" },
      ],
      diagramLabel: "Interactive · Word Relationships",
      Diagram: OddOneOutDemo,
      worked: {
        question: "Instruction: 'Click the word that does not belong.' Options: oak, maple, birch, river, willow.",
        fastMethod: "Spot the category shared by four of the five words, then check the fifth against it.",
        steps: [
          "Look at each word: oak, maple, birch and willow are all types of tree.",
          "'River' is not a type of tree — it belongs to a different category entirely.",
          "Confirm the other four genuinely share the tree category and nothing else fits better.",
          "'River' is the odd one out.",
        ],
        answer: 'The answer is <b>river</b>.',
      },
      selfCheck: { prompt: "What should you work out first in an odd-one-out question: the shared category, or the odd word?", answer: "<b>The shared category</b> — once you know what links the majority, the odd word becomes obvious rather than a guess." },
      kind: "click-evidence",
      questions: [
        {
          id: "odd-q1",
          instruction: "Click the word that does not belong with the others.",
          passage: ["trumpet", "violin", "flute", "hammer", "clarinet"],
          correctIdx: 3,
          correction: '"hammer" is the odd one out — trumpet, violin, flute and clarinet are all musical instruments, but a hammer is a tool.',
          hint: "find the category shared by four of the five words.",
        },
        {
          id: "odd-q2",
          instruction: "Click the word that does not belong with the others.",
          passage: ["quickly", "slowly", "carefully", "table", "loudly"],
          correctIdx: 3,
          correction: '"table" is the odd one out — quickly, slowly, carefully and loudly are all adverbs, but table is a noun.',
          hint: "check the part of speech of each word, not just its topic.",
        },
        {
          id: "odd-q3",
          instruction: "Click the word that does not belong with the others.",
          passage: ["triangle", "square", "pentagon", "cylinder", "hexagon"],
          correctIdx: 3,
          correction: '"cylinder" is the odd one out — triangle, square, pentagon and hexagon are all flat (2D) shapes, but a cylinder is a solid (3D) shape.',
          hint: "the category here is about how many dimensions each shape has.",
        },
      ],
      mistakes: [
        "Picking the first word that 'feels' different without confirming what the other four actually share.",
        "Spotting a surface-level category (e.g. all outdoor things) and missing a more precise one (e.g. all types of tree specifically) that changes the answer.",
      ],
      examTip: "If two words both seem like they could be the odd one out, look for a second, more precise category — GL questions are designed so exactly one word breaks the rule.",
      searchTerms: ["odd one out", "category", "classification", "word groups", "verbal reasoning"],
    },
    {
      id: "word-analogies",
      title: "Word Analogies",
      tier: "Standard",
      objective: "Work out the exact relationship linking a first pair of words, then apply the same relationship to complete a second pair.",
      whyMatters: "analogy questions are worth easy marks once the relationship is spotted correctly, but a vague or half-right relationship almost always leads to the wrong option.",
      conceptTitle: "Name the relationship precisely",
      conceptBullets: [
        '<b style="color:#C9A24B">Word analogies</b> follow the pattern "A is to B as C is to ?" — the relationship between A and B must also connect C and the answer.',
        "Common relationship types include: baby animal to adult animal, part to whole, object to its purpose, and worker to their tool or workplace.",
        "State the relationship in a precise sentence — 'a puppy grows into a dog' — before checking it against the answer options.",
        "Test your chosen answer by reading the full analogy back as one sentence to check it still makes sense.",
      ],
      conceptNote: "<b>Common trap:</b> a vague relationship like 'these are both animals' isn't precise enough — the real rule is usually more specific, such as 'baby is to adult'.",
      glossary: [
        { term: "analogy", def: "a relationship between one pair of words applied to a second pair" },
        { term: "relationship", def: "the precise connection linking the first pair of words" },
        { term: "part-to-whole", def: "a relationship where one word names a part of the thing the other word names" },
        { term: "worker-to-tool", def: "a relationship linking a job to the equipment used for it" },
      ],
      diagramLabel: "Interactive · Word Relationships",
      Diagram: WordAnalogiesDemo,
      worked: {
        question: "Instruction: 'Chef is to kitchen as pilot is to...?' Options: engine, sky, aeroplane, airport, wing.",
        fastMethod: "Name the relationship precisely — 'a chef works in a kitchen' — then apply it to pilot.",
        steps: [
          "State the relationship between chef and kitchen: a chef's workplace is the kitchen.",
          "Apply the same relationship to pilot: where does a pilot work?",
          "A pilot's workplace, in the sense of where they carry out the job, is inside the aeroplane.",
          "Read the analogy back: 'chef is to kitchen as pilot is to aeroplane' makes sense as a workplace relationship.",
        ],
        answer: 'The answer is <b>aeroplane</b>.',
      },
      selfCheck: { prompt: "Why is 'these are both animals' too vague a relationship to rely on in an analogy question?", answer: "<b>Because the real rule is usually more specific</b> (e.g. baby-to-adult, or predator-to-prey) — a vague relationship can match more than one wrong option." },
      kind: "click-evidence",
      questions: [
        {
          id: "analogy-q1",
          instruction: "Petal is to flower as leaf is to...? Click the answer.",
          passage: ["root", "tree", "branch", "seed", "soil"],
          correctIdx: 1,
          correction: 'the relationship is part-to-whole — a petal is part of a flower, so a leaf is part of a "tree".',
          hint: "work out exactly how a petal relates to a flower before choosing.",
        },
        {
          id: "analogy-q2",
          instruction: "Author is to book as composer is to...? Click the answer.",
          passage: ["piano", "song", "orchestra", "concert", "note"],
          correctIdx: 1,
          correction: 'the relationship is creator-to-creation — an author writes a book, so a composer writes a "song".',
          hint: "think about what each person in the pair actually creates.",
        },
        {
          id: "analogy-q3",
          instruction: "Kitten is to cat as cub is to...? Click the answer.",
          passage: ["lion", "puppy", "fur", "den", "paw"],
          correctIdx: 0,
          correction: 'the relationship is baby-to-adult animal — a kitten grows into a cat, so a cub grows into a "lion".',
          hint: "this is a baby-animal-to-adult-animal relationship — which option is the adult animal?",
        },
      ],
      mistakes: [
        "Choosing an option that's simply associated with the third word, without checking it fits the exact relationship from the first pair.",
        "Stopping at a vague relationship instead of pinning it down precisely enough to rule out close-looking wrong answers.",
      ],
      examTip: "Turn the relationship into a short sentence template — '___ is a baby ___', '___ is used to ___' — and test every option against that exact template.",
      searchTerms: ["word analogies", "A is to B", "relationships", "verbal reasoning", "reasoning"],
    },
    {
      id: "alphabet-letter-analogies",
      title: "Alphabet-Letter Analogies",
      tier: "Standard",
      objective: "Apply the same analogy method to letters of the alphabet, using letter position rather than word meaning.",
      whyMatters: "GL papers include a letter-based variant of the analogy format, and treating it as a word-meaning problem instead of a position problem is a common way to lose easy marks.",
      conceptTitle: "Same method, but count positions instead of meanings",
      conceptBullets: [
        '<b style="color:#C9A24B">Alphabet-letter analogies</b> follow "A is to B as C is to ?" using letters, where the relationship is a jump forward or backward in the alphabet, not a meaning.',
        "Work out the letter jump between the first pair by counting: how many places forward or backward does the alphabet move?",
        "Apply that exact same jump, in the same direction, starting from the third letter.",
        "Keep an alphabet strip in mind (or sketch one on scrap paper) so the counting is fast and error-free under time pressure.",
      ],
      conceptNote: "<b>Common trap:</b> a mixed-direction jump (e.g. +2 then -1) is rare but does appear — always check the jump direction and size on the first pair before assuming.",
      glossary: [
        { term: "letter position", def: "a letter's place in the alphabet, e.g. A is 1st, Z is 26th" },
        { term: "jump", def: "how many places forward or backward the alphabet moves between two letters" },
        { term: "alphabet strip", def: "the full sequence A-Z, useful for counting quickly" },
        { term: "direction", def: "whether a letter jump moves forward or backward through the alphabet" },
      ],
      diagramLabel: "Interactive · Word Relationships",
      Diagram: AlphabetAnalogiesDemo,
      worked: {
        question: "Instruction: 'C is to F as J is to...?' Options: K, M, L, N, I.",
        fastMethod: "Count the jump from C to F, then apply the same jump starting at J.",
        steps: [
          "Count from C to F: C, D, E, F — a jump of +3 letters.",
          "Apply the same +3 jump starting at J: J, K, L, M.",
          "That lands on 'M'.",
          "Double-check the direction was forward both times, not reversed.",
        ],
        answer: 'The answer is <b>M</b>.',
      },
      selfCheck: { prompt: "In an alphabet-letter analogy, what exactly should you count between the first pair of letters?", answer: "<b>The jump</b> — how many places forward or backward the alphabet moves, and in which direction." },
      kind: "click-evidence",
      questions: [
        {
          id: "alpha-analogy-q1",
          instruction: "D is to A as H is to...? Click the answer.",
          passage: ["E", "K", "F", "G", "C"],
          correctIdx: 0,
          correction: 'D to A is a jump of -3 (backward three letters). Applying -3 to H (H, G, F, E) gives "E".',
          hint: "work out whether this jump moves forward or backward, and by how many places.",
        },
        {
          id: "alpha-analogy-q2",
          instruction: "M is to P as R is to...? Click the answer.",
          passage: ["S", "T", "U", "Q", "V"],
          correctIdx: 2,
          correction: 'M to P is a jump of +3 (forward three letters). Applying +3 to R (R, S, T, U) gives "U".',
          hint: "count exactly how many letters forward M moves to reach P.",
        },
        {
          id: "alpha-analogy-q3",
          instruction: "K is to I as N is to...? Click the answer.",
          passage: ["P", "M", "O", "L", "Q"],
          correctIdx: 1,
          correction: 'K to I is a jump of -2 (backward two letters). Applying -2 to N (N, M) gives "M".',
          hint: "this jump moves backward through the alphabet — apply the same backward move to N.",
        },
      ],
      mistakes: [
        "Counting the jump using word-meaning instinct instead of actually counting alphabet positions.",
        "Applying the jump in the wrong direction (forward instead of backward, or vice versa).",
      ],
      examTip: "Write the relevant stretch of the alphabet on scrap paper if you're unsure — a quick sketch is faster and safer than counting in your head under pressure.",
      searchTerms: ["alphabet analogies", "letter series", "letter position", "verbal reasoning", "letter jump"],
    },
    {
      id: "multiple-meanings-trap-words",
      title: "Multiple Meanings & Trap Words",
      tier: "Standard",
      objective: "Recognise when a word has more than one meaning, and use the surrounding sentence to identify which meaning is intended.",
      whyMatters: "some of the trickiest word-relationships questions rely on a word having two unrelated meanings — picking the wrong one is a very common, very avoidable mistake.",
      conceptTitle: "The same word, two different meanings",
      conceptBullets: [
        '<b style="color:#C9A24B">Multiple-meaning words</b> (e.g. "bank", "bark", "bat", "spring") have two or more unrelated meanings depending on context.',
        "Always check whether the given word is used inside a sentence — the sentence tells you exactly which meaning is intended.",
        "A trap option often matches the word's *other*, unintended meaning — designed to catch a student who didn't read the context carefully.",
        "If no sentence is given, the most common or literal meaning is usually intended, but stay alert for a clue elsewhere in the question.",
      ],
      conceptNote: "<b>Test:</b> re-read the sentence with your chosen meaning substituted in — if the sentence stops making sense, you've picked the wrong meaning.",
      glossary: [
        { term: "multiple meaning", def: "a word that has two or more unrelated meanings" },
        { term: "context", def: "the surrounding sentence that shows which meaning is intended" },
        { term: "trap option", def: "a wrong answer that matches the word's unintended meaning" },
        { term: "literal meaning", def: "a word's most common, everyday meaning" },
      ],
      diagramLabel: "Interactive · Word Relationships",
      Diagram: TrapWordsDemo,
      worked: {
        question: "Sentence: 'The dog began to bark at the stranger.' Question: 'Click the word closest in meaning to bark as used here.' Options: tree, howl, boat, skin, shout.",
        fastMethod: "Use the sentence, not the word alone, to work out which meaning of 'bark' is intended.",
        steps: [
          "Notice 'bark' has multiple meanings: a dog's sound, or the outer covering of a tree.",
          "Read the sentence: 'the dog began to bark' — this is clearly the sound a dog makes.",
          "Scan the options for a word matching that meaning, not the tree-related meaning.",
          "'Howl' is the closest match to this meaning of 'bark'; 'tree' and 'skin' are traps for the other meaning.",
        ],
        answer: 'The answer is <b>howl</b>.',
      },
      selfCheck: { prompt: "If a multiple-meaning word appears with no surrounding sentence at all, which meaning should you generally assume?", answer: "<b>The most common or literal meaning</b> — but stay alert, since some questions still hide a clue elsewhere." },
      kind: "click-evidence",
      questions: [
        {
          id: "trap-q1",
          instruction: "Sentence: 'She wound the bandage carefully around his arm.' Click the word closest in meaning to 'wound' as used here.",
          passage: ["injury", "wrapped", "hurt", "cut", "damaged"],
          correctIdx: 1,
          correction: 'in this sentence "wound" (pronounced differently from "injury") means to wrap something around repeatedly, so "wrapped" is the correct match — not the injury meaning.',
          hint: "read the full sentence carefully — this is not the 'injury' meaning of the word.",
        },
        {
          id: "trap-q2",
          instruction: "Sentence: 'The batter hit the ball out of the park.' Click the word closest in meaning to 'batter' as used here.",
          passage: ["mixture", "player", "cake", "sauce", "coating"],
          correctIdx: 1,
          correction: 'in this sentence "batter" means the player holding the bat in a game, so "player" is the correct match — not the cooking-mixture meaning.',
          hint: "this sentence is about a sport, not baking — pick the meaning that fits.",
        },
        {
          id: "trap-q3",
          instruction: "Sentence: 'Fresh water bubbled up from the spring in the hillside.' Click the word closest in meaning to 'spring' as used here.",
          passage: ["season", "jump", "source", "coil", "bounce"],
          correctIdx: 2,
          correction: 'in this sentence "spring" means a natural water source, so "source" is the correct match — not the season or the jumping-movement meaning.',
          hint: "this sentence is about water in a hillside, not a season or a movement.",
        },
      ],
      mistakes: [
        "Choosing the word's most common meaning automatically, without checking the meaning that actually fits the sentence given.",
        "Falling for a trap option that matches an unintended meaning of the word.",
      ],
      examTip: "Whenever a word has an obvious double meaning, treat the sentence as the real question — the word is just the disguise.",
      searchTerms: ["multiple meanings", "trap words", "homonyms", "context", "verbal reasoning"],
    },
    {
      id: "working-systematically",
      title: "Working Systematically Through Five Options",
      tier: "Extension",
      objective: "Use a consistent elimination method to work through all five options rather than stopping at the first plausible one.",
      whyMatters: "GL questions are written with at least one strong-looking decoy among the five options — stopping early is one of the most common ways confident students still lose marks.",
      conceptTitle: "Check every option, in order, every time",
      conceptBullets: [
        '<b style="color:#C9A24B">Systematic elimination</b> means checking each of the five options against the question in the same order every time, rather than jumping straight to the one that looks right.',
        "For synonym and antonym questions, mentally mark each option as 'fits', 'opposite', or 'unrelated' as you go.",
        "For odd-one-out questions, confirm the shared category against all four remaining words, not just three of them.",
        "Only commit to an answer once you've checked every option — a stronger match sometimes appears later in the row.",
      ],
      conceptNote: "<b>Speed vs. safety:</b> systematic checking feels slower question by question, but prevents the costly mistake of locking in a decoy — well worth the extra second or two.",
      glossary: [
        { term: "systematic elimination", def: "checking every option in a consistent order rather than guessing" },
        { term: "decoy", def: "a wrong option deliberately designed to look plausible" },
        { term: "commit", def: "finalising your chosen answer" },
        { term: "consistent order", def: "checking options in the same sequence every time to avoid missing one" },
      ],
      diagramLabel: "Interactive · Word Relationships",
      Diagram: WorkingSystematicallyDemo,
      worked: {
        question: "Instruction: 'Click the word most opposite in meaning to transparent.' Options: clear, glassy, opaque, fragile, visible.",
        fastMethod: "Mark each option as fits/opposite/unrelated in order, rather than grabbing the first word that looks different.",
        steps: [
          "Check 'clear': means roughly the same as transparent — not the answer.",
          "Check 'glassy': also close to the meaning of transparent — not the answer.",
          "Check 'opaque': means the opposite of transparent — a strong candidate.",
          "Check 'fragile' and 'visible': both unrelated to the transparent/opaque relationship — confirming 'opaque' is correct.",
        ],
        answer: 'The answer is <b>opaque</b>.',
      },
      selfCheck: { prompt: "Why is it worth checking all five options even after finding one that looks correct?", answer: "<b>Because GL questions often include a stronger, more precise match later in the row</b> — an early plausible option can still be a decoy." },
      kind: "click-evidence",
      questions: [
        {
          id: "systematic-q1",
          instruction: "Click the word closest in meaning to 'vast'.",
          passage: ["tiny", "narrow", "immense", "distant", "steady"],
          correctIdx: 2,
          correction: 'checking each option in turn, "immense" is the only genuine match for "vast" — the rest are unrelated or opposite in meaning.',
          hint: "check every option before committing — don't stop at the first one that seems plausible.",
        },
        {
          id: "systematic-q2",
          instruction: "Click the word most opposite in meaning to 'permit'.",
          passage: ["allow", "grant", "forbid", "approve", "consent"],
          correctIdx: 2,
          correction: 'four of these five options mean roughly the same as "permit" — only "forbid" is a genuine opposite.',
          hint: "most of the options here are near-synonyms of the given word — find the true opposite among them.",
        },
        {
          id: "systematic-q3",
          instruction: "Click the word that does not belong with the others.",
          passage: ["whisk", "spatula", "saucepan", "ladle", "sieve"],
          correctIdx: 2,
          correction: 'checking each word against the category "kitchen tools you hold and use directly", "saucepan" is the odd one out — it is a container, not a hand tool.',
          hint: "check all four remaining words against your chosen category before deciding the odd one out.",
        },
      ],
      mistakes: [
        "Locking in the first option that seems to fit, without checking the remaining options for a stronger match.",
        "Losing track of which options have already been checked, and accidentally re-checking the same one twice.",
      ],
      examTip: "Develop a habit of scanning left to right through all five options exactly once before answering — consistency beats speed here.",
      searchTerms: ["elimination", "systematic method", "five options", "decoys", "verbal reasoning strategy"],
    },
    {
      id: "category-precision-traps",
      title: "Category & Precision Traps",
      tier: "Extension",
      objective: "Distinguish between a broad, surface-level category and the precise rule a question actually requires.",
      whyMatters: "the hardest odd-one-out and analogy questions are hard specifically because the obvious category is wrong, or only half-right — precision is what separates a confident guess from a correct answer.",
      conceptTitle: "When the obvious category isn't precise enough",
      conceptBullets: [
        '<b style="color:#C9A24B">A precision trap</b> is a question where a broad, easy-to-spot category exists, but a more specific rule is actually needed to find the true answer.',
        "Example: 'these are all shapes' is broad and easy to spot — but 'these are all flat, 2D shapes' is the precise rule that actually identifies the odd one out.",
        "If your first category doesn't cleanly rule out exactly one word (or leaves you unsure between two), you've probably found the broad version, not the precise one.",
        "Look for a second layer — dimension, part of speech, spelling pattern, or a shared prefix/suffix — hiding underneath the obvious category.",
      ],
      conceptNote: "<b>Warning sign:</b> if a category you've spotted fits all five words equally well, it isn't the rule the question is testing — dig one layer deeper.",
      glossary: [
        { term: "broad category", def: "an easy-to-spot but imprecise grouping" },
        { term: "precise rule", def: "the exact, specific pattern the question is actually testing" },
        { term: "second layer", def: "a more specific rule hidden underneath an obvious category" },
        { term: "precision trap", def: "a question designed so the obvious category doesn't give the right answer" },
      ],
      diagramLabel: "Interactive · Word Relationships",
      Diagram: CategoryPrecisionDemo,
      worked: {
        question: "Instruction: 'Click the word that does not belong.' Options: square, triangle, cube, pentagon, hexagon.",
        fastMethod: "Notice the broad category ('all shapes') doesn't cleanly identify one odd word, so look for a more precise rule.",
        steps: [
          "Broad category check: 'these are all shapes' — but that fits all five words equally, so it isn't precise enough.",
          "Look for a second layer: how many dimensions does each shape have?",
          "Square, triangle, pentagon and hexagon are all flat, 2D shapes.",
          "'Cube' is a solid, 3D shape — the precise rule identifies it as the odd one out.",
        ],
        answer: 'The answer is <b>cube</b>.',
      },
      selfCheck: { prompt: "What's the warning sign that you've only found the broad version of a category, not the precise rule?", answer: "<b>The category fits all the words equally well</b> — a true rule should cleanly rule out exactly one word (or two, for a two-odd-ones-out question)." },
      kind: "click-evidence",
      questions: [
        {
          id: "precision-q1",
          instruction: "Click the word that does not belong with the others.",
          passage: ["run", "jump", "walk", "table", "swim"],
          correctIdx: 3,
          correction: 'the broad category "these could all relate to sport" is imprecise — the precise rule is part of speech: run, jump, walk and swim are all verbs, but "table" is a noun.',
          hint: "the broad topic connection is a trap — check the part of speech of each word instead.",
        },
        {
          id: "precision-q2",
          instruction: "Click the word that does not belong with the others.",
          passage: ["kitten", "puppy", "cat", "foal", "cub"],
          correctIdx: 2,
          correction: 'the broad category "these are all animals" is imprecise — the precise rule is baby animals specifically: kitten, puppy, foal and cub are all baby animals, but "cat" is an adult animal.',
          hint: "'these are all animals' fits every word — look for a more specific rule about age.",
        },
        {
          id: "precision-q3",
          instruction: "Click the word that does not belong with the others.",
          passage: ["happily", "quickly", "green", "slowly", "loudly"],
          correctIdx: 2,
          correction: 'the broad category "these are all describing words" is imprecise — the precise rule is adverbs ending in -ly: happily, quickly, slowly and loudly all fit, but "green" is an adjective, not an adverb.',
          hint: "check the exact grammatical type and word ending, not just whether each word is descriptive.",
        },
      ],
      mistakes: [
        "Settling for the first, broadest category that comes to mind and answering before checking it's precise enough.",
        "Assuming a category is correct just because it fits most of the words, without checking it fits all but exactly one.",
      ],
      examTip: "If your chosen category doesn't cleanly separate one word from the rest, don't guess — actively hunt for a second, more specific layer.",
      searchTerms: ["category traps", "precision", "broad category", "odd one out", "verbal reasoning"],
    },
    {
      id: "timing-exam-strategy",
      title: "Timing & Exam Strategy for Word Relationships",
      tier: "Extension",
      objective: "Apply time-efficient habits across a full run of word-relationships questions on a timed paper.",
      whyMatters: "word-relationships questions are usually the fastest section of a Verbal Reasoning paper to answer correctly — wasting time here eats into time needed for harder code and logic questions later on.",
      conceptTitle: "Move fast on the clear ones, mark and return on the hard ones",
      conceptBullets: [
        '<b style="color:#C9A24B">Trust a strong first instinct</b> on a word you clearly know — re-checking a question you were already confident about wastes valuable seconds.',
        "If a word or relationship is genuinely unfamiliar, don't freeze — make your best educated guess, mark the question, and move on.",
        "Return to marked/skipped questions only after finishing the rest of the section, using any spare time at the end.",
        "Never leave a word-relationships question blank — an educated guess costs nothing on GL-style scoring, but a blank answer guarantees zero.",
      ],
      conceptNote: "<b>Pacing habit:</b> word-relationships questions should feel like some of your fastest on the paper — if one is taking far longer than the others, mark it and come back rather than losing momentum.",
      glossary: [
        { term: "first instinct", def: "your immediate, confident reaction to a clear question" },
        { term: "mark and return", def: "skipping a hard question temporarily and answering it later with remaining time" },
        { term: "educated guess", def: "a reasoned guess based on partial knowledge, rather than a blank answer" },
        { term: "pacing", def: "managing your speed through a paper so every section gets attempted" },
      ],
      diagramLabel: "Interactive · Word Relationships",
      Diagram: TimingStrategyDemo,
      worked: {
        question: "Scenario: on a timed practice paper, a student reaches question 12 of 20 word-relationships questions with 90 seconds left for this section, and question 12 looks unfamiliar. Question: 'What should the student do?'",
        fastMethod: "Make an educated guess, mark the question, and keep moving rather than freezing on one hard item.",
        steps: [
          "Recognise that time is limited and 8 more questions remain in the section.",
          "Rather than freezing on question 12, eliminate any option that's clearly wrong to narrow the guess.",
          "Make the best educated guess from what's left, and mark the question to revisit if time allows.",
          "Move on immediately to question 13, protecting time for the rest of the section.",
        ],
        answer: "The student should <b>make an educated guess, mark it, and move on</b> — never leave it blank or freeze on it.",
      },
      selfCheck: { prompt: "Why should you never leave a word-relationships question blank, even if you're genuinely unsure?", answer: "<b>Because an educated guess has a chance of being correct, while a blank answer guarantees zero marks.</b>" },
      kind: "click-evidence",
      questions: [
        {
          id: "timing-q1",
          instruction: "Click the word closest in meaning to 'assist'.",
          passage: ["hinder", "help", "ignore", "delay", "avoid"],
          correctIdx: 1,
          correction: '"help" matches "assist" directly — a clear synonym like this should be answered quickly and confidently, without over-checking.',
          hint: "trust your first instinct here — this is a clear, well-known pair of words.",
        },
        {
          id: "timing-q2",
          instruction: "Click the word most opposite in meaning to 'permanent'.",
          passage: ["lasting", "fixed", "temporary", "stable", "constant"],
          correctIdx: 2,
          correction: '"temporary" is the clear opposite of "permanent" — this kind of well-known opposite pair is a fast, confident mark, not one to dwell on.',
          hint: "this is a common, well-known opposite pair — don't slow down checking it repeatedly.",
        },
        {
          id: "timing-q3",
          instruction: "Click the word that does not belong with the others.",
          passage: ["novel", "biography", "textbook", "bookshelf", "encyclopedia"],
          correctIdx: 3,
          correction: '"bookshelf" is the odd one out — novel, biography, textbook and encyclopedia are all types of book, but a bookshelf is furniture used to store them.',
          hint: "one item here is used to store the others, rather than being an example of the same category.",
        },
      ],
      mistakes: [
        "Spending too long double-checking a question you were already confident about, at the cost of questions later in the section.",
        "Leaving a hard question blank instead of marking it and making an educated guess to return to later.",
      ],
      examTip: "Practise noticing, in the moment, when a question is taking noticeably longer than the ones around it — that's the signal to mark it and move on.",
      searchTerms: ["timing", "exam strategy", "pacing", "educated guess", "verbal reasoning", "time management"],
    },
  ],
};
